### ISSUE TITLE
Installation problem - Cannot find module 'is-my-json-valid'

### ISSUE THREAD

**Issue by antonsekatski** [sass/node-sass#1008]
Ubuntu 14.04.2 LTS
Node: v0.12.4
Npm: 2.10.1

What could it be?

```
npm install node-sass
> node-sass@3.2.0 install /home/anton/projects/test/node_modules/node-sass
> node scripts/install.js

module.js:338
    throw err;
    ^
Error: Cannot find module 'is-my-json-valid'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/anton/projects/test/node_modules/har-validator/src/index.js:5:17)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
npm ERR! Linux 3.16.0-38-generic
npm ERR! argv "/home/anton/.nvm/versions/node/v0.12.4/bin/node" "/home/anton/.nvm/versions/node/v0.12.4/bin/npm" "install" "node-sass"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.2.0 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.2.0 install script 'node scripts/install.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/anton/projects/test/npm-debug.log
```

**Comment by saper** [comment]
This is most likely some problem with `har-validator` install you have already in `home/anton/projects/test/node_modules/har-validator`. Somehow it does not work with the `request` module we are using.

**Comment by antonsekatski** [comment]
That was a strange bug with permissions. I used NVM and it didn't allow me to install har-validator without sudo at all.

I reinstalled Node as a system package and everything works now :+1: 

Thanks for the advice.

**Comment by saper** [comment]
Good to know. Hopefully others running into this can find this issue. Can you close this?
