### ISSUE TITLE
Standardize on os-tmpdir

### ISSUE THREAD

**Issue by xzyfer** [sass/node-sass#1018]
As per https://github.com/sass/node-sass/issues/989 `os.tmpDir` is deprecated since 0.10 and is now `os.tmpdir`.

Rather than dealing with this switching internally we'll use https://github.com/sindresorhus/os-tmpdir.

Fixes https://github.com/sass/node-sass/issues/989

**Comment by xzyfer** [comment]
My mistake. We do not use `os.tmpDir`. The issue was in a transient dependency which has since been patched. https://github.com/sass/node-sass/issues/989#issuecomment-136362839

**Comment by AlexanderElias** [comment]
It looks like this might still be an issue. 

```
(node:18923) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
Error: ENOENT: no such file or directory, scandir '/root/.nvm/versions/node/v7.4.0/lib/node_modules/muleify/node_modules/node-sass/vendor'
at Object.fs.readdirSync (fs.js:871:18)
at Object.getInstalledBinaries (/root/.nvm/versions/node/v7.4.0/lib/node_modules/muleify/node_modules/node-sass/lib/extensions.js:121:13)
at foundBinariesList (/root/.nvm/versions/node/v7.4.0/lib/node_modules/muleify/node_modules/node-sass/lib/errors.js:20:15)
at foundBinaries (/root/.nvm/versions/node/v7.4.0/lib/node_modules/muleify/node_modules/node-sass/lib/errors.js:15:5)
at Object.module.exports.missingBinary (/root/.nvm/versions/node/v7.4.0/lib/node_modules/muleify/node_modules/node-sass/lib/errors.js:45:5)
at module.exports (/root/.nvm/versions/node/v7.4.0/lib/node_modules/muleify/node_modules/node-sass/lib/binding.js:15:30)
at Object. (/root/.nvm/versions/node/v7.4.0/lib/node_modules/muleify/node_modules/node-sass/lib/index.js:14:35)
at Module._compile (module.js:571:32)
at Object.Module._extensions..js (module.js:580:10)
at Module.load (module.js:488:32)
```

**Comment by xzyfer** [comment]
I can't find the called referenced in that error. I suspect you're running an old version of node-sass

**Comment by AlexanderElias** [comment]
Node-sass is a dependency for a pack I maintain so let me check with the guy that has it on his system.
