### ISSUE TITLE
SmartOS: libsass/units.hpp:39:5: error: expected identifier before numeric constant

### ISSUE THREAD

**Issue by djensen47** [sass/node-sass#1025]
```
$ sudo npm install -g node-sass
```

```
In file included from ../src/libsass/ast.hpp:34:0,
                 from ../src/libsass/ast.cpp:1:
../src/libsass/units.hpp:39:5: error: expected identifier before numeric constant
../src/libsass/units.hpp:39:5: error: expected '}' before numeric constant
../src/libsass/units.hpp:39:5: error: expected unqualified-id before numeric constant
../src/libsass/units.hpp:62:3: error: 'SassUnit' does not name a type
../src/libsass/units.hpp:63:30: error: 'SassUnit' was not declared in this scope
../src/libsass/units.hpp:63:30: note: suggested alternative:
../src/libsass/units.hpp:22:8: note:   'Sass::SassUnit'
../src/libsass/units.hpp:64:3: error: 'SassUnitType' does not name a type
../src/libsass/units.hpp:66:34: error: 'string' does not name a type
../src/libsass/units.hpp:66:40: error: ISO C++ forbids declaration of 'parameter' with no type [-fpermissive]
../src/libsass/units.hpp:66:49: error: 'string' does not name a type
../src/libsass/units.hpp:66:55: error: ISO C++ forbids declaration of 'parameter' with no type [-fpermissive]
../src/libsass/units.hpp:69:3: error: expected class-name before '{' token
../src/libsass/units.hpp:72:34: error: expected ')' before 'a'
../src/libsass/units.hpp:87:1: error: expected declaration before '}' token
src/libsass.target.mk:128: recipe for target 'Release/obj.target/libsass/src/libsass/ast.o' failed
make: *** [Release/obj.target/libsass/src/libsass/ast.o] Error 1
make: Leaving directory '/opt/local/lib/node_modules/node-sass/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/local/lib/node_modules/node-sass/node_modules/pangyp/lib/build.js:271:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System SunOS 5.11
gyp ERR! command "/opt/local/bin/node" "/opt/local/lib/node_modules/node-sass/node_modules/pangyp/bin/node-gyp" "rebuild" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /opt/local/lib/node_modules/node-sass
gyp ERR! node -v v0.12.0
gyp ERR! pangyp -v v2.2.1
gyp ERR! not ok
Build failed
npm ERR! SunOS 5.11
npm ERR! argv "/opt/local/bin/node" "/opt/local/bin/npm" "install" "-g" "node-sass"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.2.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.2.0 postinstall script 'node scripts/build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.
```

**Comment by djensen47** [comment]
Is this is `node-sass` or a `libsass` issue?

**Comment by saper** [comment]
`libsass`

**Comment by clord** [comment]
looks like a pending PR fixes this: https://github.com/sass/libsass/pull/1782

**Comment by xzyfer** [comment]
Merged https://github.com/sass/libsass/pull/1782.
This will be released when https://github.com/sass/node-sass/issues/1317 is closed. Subscribe to that issue for updates.
