### ISSUE TITLE
CLI --source-map option broken

### ISSUE THREAD

**Issue by johnpolacek** [sass/node-sass#1026]
In a new directory, create a test.scss file with one line of css, save then in CLI run:
```node-sass test.scss test.css --source-map```

You will get the following error:
```
var sourceMapIsDirectory = options.sourceMapOriginal.indexOf('.map', optio
TypeError: Object true has no method 'indexOf'
```

**Comment by am11** [comment]
This was a breaking change in v3, see https://github.com/sass/node-sass/pull/964.

In your case, use `node-sass test.scss test.css --source-map true` or ` node-sass test.scss test.css --source-map custom-path/to/whatever.map`

**Comment by nhunzaker** [comment]
I just hit this as well and the error message is very cryptic. What do you think about improving the error here if a value isn't present?

**Comment by glassdimly** [comment]
I am of the opinion that node-sass --help ought to note that --source-map needs a boolean parameter. Otherwise most people would reasonably assume that this was just a standard unix parameter that did not need a boolean. It should not be necessary to google this bug or read the source: that's what the --help or man page is for.

**Comment by sant123** [comment]
This error is still happening... I have this

```json
  "scripts": {
    "ts" : "node_modules\\.bin\\tsc -w -p .",
    "sass_env" : "SET node-sass=node_modules\\.bin\\node-sass",
    "sass_compile" : "npm run sass_env && node-sass styles -o styles --output-style compressed --source-map ",
    "sass" : "npm run sass_compile && node-sass styles -wo styles --output-style compressed --source-map "
  }
```

When I execute ```npm run sass``` I get the following error:

``` 
D:\santiagoah\informacion\Desktop\Visor de documentos>npm run sass                                                                                                 
                                                                                                                                                                   
> visor-de-documentos@1.0.0 sass D:\santiagoah\informacion\Desktop\Visor de documentos                                                                             
> npm run sass_compile && node-sass styles -wo styles --output-style compressed                                                                                    
                                                                                                                                                                   
                                                                                                                                                                   
> visor-de-documentos@1.0.0 sass_compile D:\santiagoah\informacion\Desktop\Visor de documentos                                                                     
> npm run sass_env && node-sass styles -o styles --output-style compressed --source-map                                                                            
                                                                                                                                                                   
                                                                                                                                                                   
> visor-de-documentos@1.0.0 sass_env D:\santiagoah\informacion\Desktop\Visor de documentos                                                                         
> SET node-sass=node_modules\.bin\node-sass                                                                                                                        
                                                                                                                                                                   
D:\santiagoah\informacion\Desktop\Visor de documentos\node_modules\node-sass\bin\node-sass:209                                                                     
    var sourceMapIsDirectory = options.sourceMapOriginal.indexOf('.map', options.sourceMapOriginal.length - 4) === -1 && isDirectory(options.sourceMapOriginal);   
                                                         ^                                                                                                         
                                                                                                                                                                   
TypeError: options.sourceMapOriginal.indexOf is not a function                                                                                                     
    at getOptions (D:\santiagoah\informacion\Desktop\Visor de documentos\node_modules\node-sass\bin\node-sass:209:58)                                              
    at Object.<anonymous> (D:\santiagoah\informacion\Desktop\Visor de documentos\node_modules\node-sass\bin\node-sass:386:15)                                      
    at Module._compile (module.js:541:32)                                                                                                                          
    at Object.Module._extensions..js (module.js:550:10)                                                                                                            
    at Module.load (module.js:458:32)                                                                                                                              
    at tryModuleLoad (module.js:417:12)                                                                                                                            
    at Function.Module._load (module.js:409:3)                                                                                                                     
    at Module.runMain (module.js:575:10)                                                                                                                           
    at run (node.js:348:7)                                                                                                                                         
    at startup (node.js:140:9)  
```
re-open?

**Comment by AntonKL** [comment]
Documentation says
```--source-map   =>            Emit source map```

Accroding to this issue the correct syntax is to include a ```true``` after ```--source-map```
```--source-map true =>               Emit source map```

Would suggest a update on docs.

**Comment by sant123** [comment]
Thank you @AntonKL It worked as expected!

**Comment by BenRacicot** [comment]
Docs still not updated. Thumbs up @AntonKL

**Comment by ZelphirKaltstahl** [comment]
5 years later, and the error message is still just as cryptic.

```
/root/app/node_modules/node-sass/bin/node-sass:208
    var sourceMapIsDirectory = options.sourceMapOriginal.indexOf('.map', options.sourceMapOriginal.length - 4) === -1 && isDirectory(options.sourceMapOriginal);
                                                         ^

TypeError: options.sourceMapOriginal.indexOf is not a function
    at getOptions (/root/app/node_modules/node-sass/bin/node-sass:208:58)
    at Object.<anonymous> (/root/app/node_modules/node-sass/bin/node-sass:376:15)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
```

**Comment by williamdes** [comment]
> 5 years later, and the error message is still just as cryptic.

One more year to the counter, seriously add some code handle this
