### ISSUE TITLE
functions.cpp:224:34: error: 'round' is not a member of 'std'

### ISSUE THREAD

**Issue by elliotlings** [sass/node-sass#1034]
Can anyone tell me why we may be getting this error?

```
npm info postinstall node-sass@3.2.0

> node-sass@3.2.0 postinstall /usr/home/webs/myproject/node_modules/gulp-sass/node_modules/node-sass
> node scripts/build.js

` /usr/home/webs/myproject/node_modules/gulp-sass/node_modules/node-sass/vendor/freebsd-x64-11/binding.node ` exists.
 testing binary.
Problem with the binary.
Manual build incoming.
Building: /usr/local/bin/node node_modules/pangyp/bin/node-gyp rebuild --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp info using pangyp@2.2.1
gyp info using node@0.10.26 | freebsd | x64
gyp info spawn python
gyp info spawn args [ '/usr/home/webs/myproject/node_modules/gulp-sass/node_modules/node-sass/node_modules/pangyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/home/webs/myproject/node_modules/gulp-sass/node_modules/node-sass/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/home/webs/myproject/node_modules/gulp-sass/node_modules/node-sass/node_modules/pangyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/var/www/.node-gyp/0.10.26/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/var/www/.node-gyp/0.10.26',
gyp info spawn args   '-Druntime=node',
gyp info spawn args   '-Dmodule_root_dir=/usr/home/webs/myproject/node_modules/gulp-sass/node_modules/node-sass',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn gmake
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
gmake: Entering directory `/usr/home/webs/myproject/node_modules/gulp-sass/node_modules/node-sass/build'
  CXX(target) Release/obj.target/libsass/src/libsass/ast.o
cc1plus: error: unrecognized command line option "-std=c++0x"
gmake: *** [Release/obj.target/libsass/src/libsass/ast.o] Error 1
gmake: Leaving directory `/usr/home/webs/myproject/node_modules/gulp-sass/node_modules/node-sass/build'
gyp ERR! build error
gyp ERR! stack Error: `gmake` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/home/webs/myproject/node_modules/gulp-sass/node_modules/node-sass/node_modules/pangyp/lib/build.js:271:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System FreeBSD 9.3-RELEASE-p13
gyp ERR! command "/usr/local/bin/node" "/usr/home/webs/myproject/node_modules/gulp-sass/node_modules/node-sass/node_modules/pangyp/bin/node-gyp" "rebuild" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /usr/home/webs/myproject/node_modules/gulp-sass/node_modules/node-sass
gyp ERR! node -v v0.10.26
gyp ERR! pangyp -v v2.2.1
gyp ERR! not ok
Build failed
npm info node-sass@3.2.0 Failed to exec postinstall script
npm info /usr/home/webs/myproject/node_modules/gulp-sass/node_modules/node-sass unbuild
npm info preuninstall node-sass@3.2.0
npm info uninstall node-sass@3.2.0
npm info postuninstall node-sass@3.2.0
npm info /usr/home/webs/myproject/node_modules/gulp-sass unbuild
npm info preuninstall gulp-sass@2.0.3
npm info uninstall gulp-sass@2.0.3
npm info postuninstall gulp-sass@2.0.3
npm ERR! node-sass@3.2.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.2.0 postinstall script.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! System FreeBSD 9.3-RELEASE-p13
npm ERR! command "node" "/usr/local/bin/npm" "install" "-d"
npm ERR! cwd /usr/home/webs/myproject
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.6
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /usr/home/webs/myproject/npm-debug.log
npm ERR! not ok code 0
```

We have GCC installed at /usr/local/bin/gcc49

**Comment by saper** [comment]
Can you try with `env V=1 npm install ...` ?

**Comment by elliotlings** [comment]
CC=gcc49 CXX=g++49 MAKE=gmake V=1 npm install ...

```
> node-sass@3.2.0 install /usr/home/webs/myproject/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /usr/home/webs/myproject/node_modules/node-sass/vendor/freebsd-x64-11/binding.node

> node-sass@3.2.0 postinstall /usr/home/webs/myproject/node_modules/node-sass
> node scripts/build.js

` /usr/home/webs/myproject/node_modules/node-sass/vendor/freebsd-x64-11/binding.node ` exists.
 testing binary.
Problem with the binary.
Manual build incoming.
Building: /usr/local/bin/node node_modules/pangyp/bin/node-gyp rebuild --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gmake: Entering directory `/usr/home/webs/myproject/node_modules/node-sass/build'
  g++49 '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DLIBSASS_VERSION="3.2.5"' -I/var/www/.node-gyp/0.10.26/src -I/var/www/.node-gyp/0.10.26/deps/uv/include -I/var/www/.node-gyp/0.10.26/deps/v8/include  -fPIC -Wall -Wextra -Wno-unused-parameter -pthread -m64 -O2 -fno-strict-aliasing -fno-tree-vrp -fno-tree-sink -fno-omit-frame-pointer -fno-rtti -std=c++0x -fexceptions -frtti -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/ast.o.d.raw  -c -o Release/obj.target/libsass/src/libsass/ast.o ../src/libsass/ast.cpp
  g++49 '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DLIBSASS_VERSION="3.2.5"' -I/var/www/.node-gyp/0.10.26/src -I/var/www/.node-gyp/0.10.26/deps/uv/include -I/var/www/.node-gyp/0.10.26/deps/v8/include  -fPIC -Wall -Wextra -Wno-unused-parameter -pthread -m64 -O2 -fno-strict-aliasing -fno-tree-vrp -fno-tree-sink -fno-omit-frame-pointer -fno-rtti -std=c++0x -fexceptions -frtti -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/base64vlq.o.d.raw  -c -o Release/obj.target/libsass/src/libsass/base64vlq.o ../src/libsass/base64vlq.cpp
  g++49 '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DLIBSASS_VERSION="3.2.5"' -I/var/www/.node-gyp/0.10.26/src -I/var/www/.node-gyp/0.10.26/deps/uv/include -I/var/www/.node-gyp/0.10.26/deps/v8/include  -fPIC -Wall -Wextra -Wno-unused-parameter -pthread -m64 -O2 -fno-strict-aliasing -fno-tree-vrp -fno-tree-sink -fno-omit-frame-pointer -fno-rtti -std=c++0x -fexceptions -frtti -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/bind.o.d.raw  -c -o Release/obj.target/libsass/src/libsass/bind.o ../src/libsass/bind.cpp
  gcc49 '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DLIBSASS_VERSION="3.2.5"' -I/var/www/.node-gyp/0.10.26/src -I/var/www/.node-gyp/0.10.26/deps/uv/include -I/var/www/.node-gyp/0.10.26/deps/v8/include  -fPIC -Wall -Wextra -Wno-unused-parameter -pthread -m64 -O2 -fno-strict-aliasing -fno-tree-vrp -fno-tree-sink -fno-omit-frame-pointer  -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/cencode.o.d.raw  -c -o Release/obj.target/libsass/src/libsass/cencode.o ../src/libsass/cencode.c
  g++49 '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DLIBSASS_VERSION="3.2.5"' -I/var/www/.node-gyp/0.10.26/src -I/var/www/.node-gyp/0.10.26/deps/uv/include -I/var/www/.node-gyp/0.10.26/deps/v8/include  -fPIC -Wall -Wextra -Wno-unused-parameter -pthread -m64 -O2 -fno-strict-aliasing -fno-tree-vrp -fno-tree-sink -fno-omit-frame-pointer -fno-rtti -std=c++0x -fexceptions -frtti -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/constants.o.d.raw  -c -o Release/obj.target/libsass/src/libsass/constants.o ../src/libsass/constants.cpp
  g++49 '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DLIBSASS_VERSION="3.2.5"' -I/var/www/.node-gyp/0.10.26/src -I/var/www/.node-gyp/0.10.26/deps/uv/include -I/var/www/.node-gyp/0.10.26/deps/v8/include  -fPIC -Wall -Wextra -Wno-unused-parameter -pthread -m64 -O2 -fno-strict-aliasing -fno-tree-vrp -fno-tree-sink -fno-omit-frame-pointer -fno-rtti -std=c++0x -fexceptions -frtti -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/context.o.d.raw  -c -o Release/obj.target/libsass/src/libsass/context.o ../src/libsass/context.cpp
  g++49 '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DLIBSASS_VERSION="3.2.5"' -I/var/www/.node-gyp/0.10.26/src -I/var/www/.node-gyp/0.10.26/deps/uv/include -I/var/www/.node-gyp/0.10.26/deps/v8/include  -fPIC -Wall -Wextra -Wno-unused-parameter -pthread -m64 -O2 -fno-strict-aliasing -fno-tree-vrp -fno-tree-sink -fno-omit-frame-pointer -fno-rtti -std=c++0x -fexceptions -frtti -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/contextualize.o.d.raw  -c -o Release/obj.target/libsass/src/libsass/contextualize.o ../src/libsass/contextualize.cpp
  g++49 '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DLIBSASS_VERSION="3.2.5"' -I/var/www/.node-gyp/0.10.26/src -I/var/www/.node-gyp/0.10.26/deps/uv/include -I/var/www/.node-gyp/0.10.26/deps/v8/include  -fPIC -Wall -Wextra -Wno-unused-parameter -pthread -m64 -O2 -fno-strict-aliasing -fno-tree-vrp -fno-tree-sink -fno-omit-frame-pointer -fno-rtti -std=c++0x -fexceptions -frtti -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/contextualize_eval.o.d.raw  -c -o Release/obj.target/libsass/src/libsass/contextualize_eval.o ../src/libsass/contextualize_eval.cpp
  g++49 '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DLIBSASS_VERSION="3.2.5"' -I/var/www/.node-gyp/0.10.26/src -I/var/www/.node-gyp/0.10.26/deps/uv/include -I/var/www/.node-gyp/0.10.26/deps/v8/include  -fPIC -Wall -Wextra -Wno-unused-parameter -pthread -m64 -O2 -fno-strict-aliasing -fno-tree-vrp -fno-tree-sink -fno-omit-frame-pointer -fno-rtti -std=c++0x -fexceptions -frtti -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/cssize.o.d.raw  -c -o Release/obj.target/libsass/src/libsass/cssize.o ../src/libsass/cssize.cpp
  g++49 '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DLIBSASS_VERSION="3.2.5"' -I/var/www/.node-gyp/0.10.26/src -I/var/www/.node-gyp/0.10.26/deps/uv/include -I/var/www/.node-gyp/0.10.26/deps/v8/include  -fPIC -Wall -Wextra -Wno-unused-parameter -pthread -m64 -O2 -fno-strict-aliasing -fno-tree-vrp -fno-tree-sink -fno-omit-frame-pointer -fno-rtti -std=c++0x -fexceptions -frtti -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/emitter.o.d.raw  -c -o Release/obj.target/libsass/src/libsass/emitter.o ../src/libsass/emitter.cpp
  g++49 '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DLIBSASS_VERSION="3.2.5"' -I/var/www/.node-gyp/0.10.26/src -I/var/www/.node-gyp/0.10.26/deps/uv/include -I/var/www/.node-gyp/0.10.26/deps/v8/include  -fPIC -Wall -Wextra -Wno-unused-parameter -pthread -m64 -O2 -fno-strict-aliasing -fno-tree-vrp -fno-tree-sink -fno-omit-frame-pointer -fno-rtti -std=c++0x -fexceptions -frtti -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/error_handling.o.d.raw  -c -o Release/obj.target/libsass/src/libsass/error_handling.o ../src/libsass/error_handling.cpp
  g++49 '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DLIBSASS_VERSION="3.2.5"' -I/var/www/.node-gyp/0.10.26/src -I/var/www/.node-gyp/0.10.26/deps/uv/include -I/var/www/.node-gyp/0.10.26/deps/v8/include  -fPIC -Wall -Wextra -Wno-unused-parameter -pthread -m64 -O2 -fno-strict-aliasing -fno-tree-vrp -fno-tree-sink -fno-omit-frame-pointer -fno-rtti -std=c++0x -fexceptions -frtti -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/eval.o.d.raw  -c -o Release/obj.target/libsass/src/libsass/eval.o ../src/libsass/eval.cpp
  g++49 '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DLIBSASS_VERSION="3.2.5"' -I/var/www/.node-gyp/0.10.26/src -I/var/www/.node-gyp/0.10.26/deps/uv/include -I/var/www/.node-gyp/0.10.26/deps/v8/include  -fPIC -Wall -Wextra -Wno-unused-parameter -pthread -m64 -O2 -fno-strict-aliasing -fno-tree-vrp -fno-tree-sink -fno-omit-frame-pointer -fno-rtti -std=c++0x -fexceptions -frtti -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/expand.o.d.raw  -c -o Release/obj.target/libsass/src/libsass/expand.o ../src/libsass/expand.cpp
  g++49 '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DLIBSASS_VERSION="3.2.5"' -I/var/www/.node-gyp/0.10.26/src -I/var/www/.node-gyp/0.10.26/deps/uv/include -I/var/www/.node-gyp/0.10.26/deps/v8/include  -fPIC -Wall -Wextra -Wno-unused-parameter -pthread -m64 -O2 -fno-strict-aliasing -fno-tree-vrp -fno-tree-sink -fno-omit-frame-pointer -fno-rtti -std=c++0x -fexceptions -frtti -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/extend.o.d.raw  -c -o Release/obj.target/libsass/src/libsass/extend.o ../src/libsass/extend.cpp
  g++49 '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DLIBSASS_VERSION="3.2.5"' -I/var/www/.node-gyp/0.10.26/src -I/var/www/.node-gyp/0.10.26/deps/uv/include -I/var/www/.node-gyp/0.10.26/deps/v8/include  -fPIC -Wall -Wextra -Wno-unused-parameter -pthread -m64 -O2 -fno-strict-aliasing -fno-tree-vrp -fno-tree-sink -fno-omit-frame-pointer -fno-rtti -std=c++0x -fexceptions -frtti -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/file.o.d.raw  -c -o Release/obj.target/libsass/src/libsass/file.o ../src/libsass/file.cpp
  g++49 '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DLIBSASS_VERSION="3.2.5"' -I/var/www/.node-gyp/0.10.26/src -I/var/www/.node-gyp/0.10.26/deps/uv/include -I/var/www/.node-gyp/0.10.26/deps/v8/include  -fPIC -Wall -Wextra -Wno-unused-parameter -pthread -m64 -O2 -fno-strict-aliasing -fno-tree-vrp -fno-tree-sink -fno-omit-frame-pointer -fno-rtti -std=c++0x -fexceptions -frtti -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/functions.o.d.raw  -c -o Release/obj.target/libsass/src/libsass/functions.o ../src/libsass/functions.cpp
../src/libsass/functions.cpp: In function 'Sass::Expression* Sass::Functions::mix(Sass::Env&, Sass::Env&, Sass::Context&, Sass::Signature, Sass::ParserState, Sass::Backtrace*)':
../src/libsass/functions.cpp:224:34: error: 'round' is not a member of 'std'
                                  std::round(w1*color1->r() + w2*color2->r()),
                                  ^
../src/libsass/functions.cpp:224:34: note: suggested alternatives:
In file included from /usr/local/lib/gcc49/include/c++/cmath:44:0,
                 from /usr/local/lib/gcc49/include/c++/random:38,
                 from /usr/local/lib/gcc49/include/c++/bits/stl_algo.h:66,
                 from /usr/local/lib/gcc49/include/c++/algorithm:62,
                 from ../src/libsass/ast.hpp:11,
                 from ../src/libsass/functions.cpp:2:
/usr/include/math.h:273:8: note:   'round'
 double round(double);
        ^
In file included from ../src/libsass/functions.cpp:1:0:
../src/libsass/functions.hpp:142:14: note:   'Sass::Functions::round'
     BUILT_IN(round);
              ^
../src/libsass/functions.hpp:11:1: note: in definition of macro 'BUILT_IN'
 name(Env& env, Env& d_env, Context& ctx, Signature sig, ParserState pstate, Backtrace* backtrace)
 ^
../src/libsass/functions.cpp:225:34: error: 'round' is not a member of 'std'
                                  std::round(w1*color1->g() + w2*color2->g()),
                                  ^
../src/libsass/functions.cpp:225:34: note: suggested alternatives:
In file included from /usr/local/lib/gcc49/include/c++/cmath:44:0,
                 from /usr/local/lib/gcc49/include/c++/random:38,
                 from /usr/local/lib/gcc49/include/c++/bits/stl_algo.h:66,
                 from /usr/local/lib/gcc49/include/c++/algorithm:62,
                 from ../src/libsass/ast.hpp:11,
                 from ../src/libsass/functions.cpp:2:
/usr/include/math.h:273:8: note:   'round'
 double round(double);
        ^
In file included from ../src/libsass/functions.cpp:1:0:
../src/libsass/functions.hpp:142:14: note:   'Sass::Functions::round'
     BUILT_IN(round);
              ^
../src/libsass/functions.hpp:11:1: note: in definition of macro 'BUILT_IN'
 name(Env& env, Env& d_env, Context& ctx, Signature sig, ParserState pstate, Backtrace* backtrace)
 ^
../src/libsass/functions.cpp:226:34: error: 'round' is not a member of 'std'
                                  std::round(w1*color1->b() + w2*color2->b()),
                                  ^
../src/libsass/functions.cpp:226:34: note: suggested alternatives:
In file included from /usr/local/lib/gcc49/include/c++/cmath:44:0,
                 from /usr/local/lib/gcc49/include/c++/random:38,
                 from /usr/local/lib/gcc49/include/c++/bits/stl_algo.h:66,
                 from /usr/local/lib/gcc49/include/c++/algorithm:62,
                 from ../src/libsass/ast.hpp:11,
                 from ../src/libsass/functions.cpp:2:
/usr/include/math.h:273:8: note:   'round'
 double round(double);
        ^
In file included from ../src/libsass/functions.cpp:1:0:
../src/libsass/functions.hpp:142:14: note:   'Sass::Functions::round'
     BUILT_IN(round);
              ^
../src/libsass/functions.hpp:11:1: note: in definition of macro 'BUILT_IN'
 name(Env& env, Env& d_env, Context& ctx, Signature sig, ParserState pstate, Backtrace* backtrace)
 ^
../src/libsass/functions.cpp:228:5: warning: control reaches end of non-void function [-Wreturn-type]
     }
     ^
gmake: *** [Release/obj.target/libsass/src/libsass/functions.o] Error 1
gmake: Leaving directory `/usr/home/webs/myproject/node_modules/node-sass/build'
```

**Comment by saper** [comment]
ok, that's a different error :) checking out...

**Comment by saper** [comment]
One proposal: can you checkout my `namespaces` branch of libsass (from https://github.com/sass/libsass/pull/1310) (https://github.com/saper/libsass/tree/namespaces), compile it and point the `npm` to it by using

`env CC=gcc49 CXX=g++49 V=1 LIBSASS_EXT=yes LIBSASS_LIBRARY=path_to_libsass.a
LIBSASS_CFLAGS=-Ipath_to_libsass_include npm install`

**Comment by elliotlings** [comment]
```functions.cpp: In function 'Sass::Expression* Sass::Functions::mix(Sass::Env&, Sass::Env&, Sass::Context&, Sass::Signature, Sass::ParserState, Sass::Backtrace*)': functions.cpp:224:34: error: 'round' is not a member of 'std'                                   std::round(w1*color1->r() + w2*color2->r()),
```

again :(

**Comment by saper** [comment]
Ok, I pushed https://github.com/saper/libsass/commit/d724a5e5c42c8c8525aa585f8053923e057109e7 now to the branch... Can you `git pull`?

**Comment by elliotlings** [comment]
```
functions.cpp:224:34: error: 'round' is not a member of 'std'                                   std::round(w1*color1->r() + w2*color2->r()),
```
again! :(

**Comment by saper** [comment]
can you post more lines of context? Do you have `#include <cmath>` in functions.cpp ?

**Comment by elliotlings** [comment]
```
functions.cpp:224:34: error: 'round' is not a member of 'std'
                                  std::round(w1*color1->r() + w2*color2->r()),
                                  ^
functions.cpp:224:34: note: suggested alternatives:
In file included from /usr/local/lib/gcc49/include/c++/cmath:44:0,
                from /usr/local/lib/gcc49/include/c++/random:38,
                from /usr/local/lib/gcc49/include/c++/bits/stl_algo.h:66,
                from /usr/local/lib/gcc49/include/c++/algorithm:62,
                from ast.hpp:11,
                from functions.cpp:2:
/usr/include/math.h:273:8: note:  'round'
double round(double);
```

**Comment by saper** [comment]
Can you try to 

1) remove '#include <algorithm>' from ast.hpp and
2) in functions.cpp: move `#include <algorithm>` below `#include <cmath>`

I wonder if this is https://gcc.gnu.org/ml/gcc/2002-09/msg00579.html

**Comment by elliotlings** [comment]
Apparently the same again :(

**Comment by saper** [comment]
ok, let me refresh my 9.3 jail to try to reproduce

**Comment by saper** [comment]
This might be related to https://gcc.gnu.org/bugzilla/show_bug.cgi?id=51749

**Comment by xzyfer** [comment]
Tracking this in LibSass https://github.com/sass/libsass/issues/1457
