### ISSUE TITLE
Cannot download "v3.2.0/freebsd-x64-0x000C_binding.node" by npm install

### ISSUE THREAD

**Issue by bobo52310** [sass/node-sass#1036]
I Can't download "https://github.com/sass/node-sass/releases/download/v3.2.0/freebsd-x64-0x000C_binding.node" by npm install.

```
> node-sass@3.2.0 install /.amd_mnt/account/users/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/node-sass
> node scripts/install.js
 
Cannot download "https://github.com/sass/node-sass/releases/download/v3.2.0/freebsd-x64-0x000C_binding.node": HTTP error 404
 
> node-sass@3.2.0 postinstall /.amd_mnt/account/users/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/node-sass
> node scripts/build.js
 
Building: /.amd_mnt/account/users/bin/node node_modules/pangyp/bin/node-gyp rebuild --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gmake: Entering directory '/.amd_mnt/account/users/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/node-sass/build'
  CXX(target) Release/obj.target/libsass/src/libsass/ast.o
cc1plus: error: unrecognized command line option "-std=c++0x"
src/libsass.target.mk:127: recipe for target 'Release/obj.target/libsass/src/libsass/ast.o' failed
gmake: *** [Release/obj.target/libsass/src/libsass/ast.o] Error 1
gmake: Leaving directory '/.amd_mnt/account/users/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/node-sass/build'
gyp ERR! build error
gyp ERR! stack Error: `gmake` failed with exit code: 2
```

**Comment by saper** [comment]
This is really strange, where did you get your node from?

**Comment by bobo52310** [comment]
Just general install it from node server.
node version v0.11.1
npm version v2.13.0
Can You check the URL "https://github.com/sass/node-sass/releases/download/v3.2.0/freebsd-x64-0x000C_binding.node" still work?

**Comment by saper** [comment]
Node 0.11 is not supported, you need to use node 0.12 or 0.10

**Comment by bobo52310** [comment]
I use Node 0.10.35, NPM 2.2.0 and got the same error...

```
 node-sass@3.2.0 install /.amd_mnt/projects/faq/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /.amd_mnt/projects/faq/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/node-sass/vendor/freebsd-x64-11/binding.node

> caniuse-api@1.3.2 postinstall /.amd_mnt/projects/faq/node_modules/gulp-cssnext/node_modules/cssnext/node_modules/caniuse-api
> node -e "require('shelljs/global');if(test('-d', 'dist'))exec('node dist/generate-features.js')"


> node-sass@3.2.0 postinstall /.amd_mnt/projects/faq/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/node-sass
> node scripts/build.js

` /.amd_mnt/projects/faq/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/node-sass/vendor/freebsd-x64-11/binding.node ` exists.
 testing binary.
Problem with the binary.
Manual build incoming.
Building: /usr/local/bin/node node_modules/pangyp/bin/node-gyp rebuild --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gmake: Entering directory '/.amd_mnt/projects/faq/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/node-sass/build'
  CXX(target) Release/obj.target/libsass/src/libsass/ast.o
cc1plus: error: unrecognized command line option "-std=c++0x"
src/libsass.target.mk:128: recipe for target 'Release/obj.target/libsass/src/libsass/ast.o' failed
gmake: *** [Release/obj.target/libsass/src/libsass/ast.o] Error 1
gmake: Leaving directory '/.amd_mnt/projects/faq/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/node-sass/build'
gyp ERR! build error
gyp ERR! stack Error: `gmake` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/.amd_mnt/projects/faq/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/node-sass/node_modules/pangyp/lib/build.js:271:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System FreeBSD 9.3-RELEASE
gyp ERR! command "/usr/local/bin/node" "/.amd_mnt/projects/faq/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/node-sass/node_modules/pangyp/bin/node-gyp" "rebuild" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /.amd_mnt/projects/faq/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/node-sass
gyp ERR! node -v v0.10.35
gyp ERR! pangyp -v v2.2.1
gyp ERR! not ok
Build failed
```

**Comment by saper** [comment]
Now that's something different.

You are using `FreeBSD 9.3-RELEASE` and our binaries are built for `FreeBSD 10.x` or later, and they use `clang` C++ libraries.

It is still possible to compile the binding and libsass yourself, it's just some work:

1. you need to install `lang/gcc48` or later from ports (the compiler you have in base is not enough)
2. you can start the build process with `env CC=gcc48 CXX=g++48 LINK=gcc48 LINKXX=g++48 npm install node-sass` and it should build the binary.
3. if you get complaints about undefined symbols trying to run node-sass, you need to compile `node` with the `gcc48` compiler.
