### ISSUE TITLE
error installing - this fails on node build.js

### ISSUE THREAD

**Issue by jcc2303** [sass/node-sass#1050]
Hi I have this issue installing a package with npm

```bash
npm install lasso-sass --save
npm WARN package.json marko-presenter@0.1.0 No repository field.
npm WARN package.json marko-presenter@0.1.0 No license field.
\
> node-sass@0.9.6 install /home/javiercabrera/smi-workspace/rapid-render/node_modules/lasso-sass/node_modules/node-sass
> node build.js

(node) child_process: options.customFds option is deprecated. Use options.stdio instead.
make: Entering directory `/home/javiercabrera/smi-workspace/rapid-render/node_modules/lasso-sass/node_modules/node-sass/build'
  CXX(target) Release/obj.target/binding/binding.o
In file included from ../binding.cpp:1:0:
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Signature> NanNew(v8::Handle<v8::FunctionTemplate>, int, v8::Handle<v8::FunctionTemplate>*)’:
../node_modules/nan/nan.h:189:78: error: no matching function for call to ‘v8::Signature::New(v8::Isolate*, v8::Handle<v8::FunctionTemplate>&, int&, v8::Handle<v8::FunctionTemplate>*&)’
     return v8::Signature::New(v8::Isolate::GetCurrent(), receiver, argc, argv);
                                                                              ^
../node_modules/nan/nan.h:189:78: note: candidate is:
In file included from /home/javiercabrera/.node-gyp/2.5.0/src/node.h:42:0,
                 from ../node_modules/nan/nan.h:23,
                 from ../binding.cpp:1:
/home/javiercabrera/.node-gyp/2.5.0/deps/v8/include/v8.h:4188:27: note: static v8::Local<v8::Signature> v8::Signature::New(v8::Isolate*, v8::Handle<v8::FunctionTemplate>)
   static Local<Signature> New(
                           ^
/home/javiercabrera/.node-gyp/2.5.0/deps/v8/include/v8.h:4188:27: note:   candidate expects 2 arguments, 4 provided
In file included from ../binding.cpp:1:0:
../node_modules/nan/nan.h: At global scope:
../node_modules/nan/nan.h:481:19: error: ‘NanNew’ declared as an ‘inline’ variable
       v8::String::ExternalAsciiStringResource *resource) {
                   ^
../node_modules/nan/nan.h:481:19: warning: ‘always_inline’ attribute ignored [-Wattributes]
../node_modules/nan/nan.h:481:19: error: ‘v8::Local<v8::String> NanNew’ redeclared as different kind of symbol
../node_modules/nan/nan.h:475:36: error: previous declaration of ‘v8::Local<v8::String> NanNew(v8::String::ExternalStringResource*)’
   NAN_INLINE v8::Local<v8::String> NanNew(
                                    ^
../node_modules/nan/nan.h:481:7: error: ‘ExternalAsciiStringResource’ is not a member of ‘v8::String’
       v8::String::ExternalAsciiStringResource *resource) {
       ^
../node_modules/nan/nan.h:481:48: error: ‘resource’ was not declared in this scope
       v8::String::ExternalAsciiStringResource *resource) {
                                                ^
../node_modules/nan/nan.h: In function ‘bool _NanGetExternalParts(v8::Handle<v8::Value>, const char**, size_t*)’:
../node_modules/nan/nan.h:2103:12: error: ‘class v8::String’ has no member named ‘IsExternalAscii’
   if (str->IsExternalAscii()) {
            ^
../node_modules/nan/nan.h:2104:11: error: ‘ExternalAsciiStringResource’ in ‘class v8::String’ does not name a type
     const v8::String::ExternalAsciiStringResource* ext;
           ^
../node_modules/nan/nan.h:2105:5: error: ‘ext’ was not declared in this scope
     ext = str->GetExternalAsciiStringResource();
     ^
../node_modules/nan/nan.h:2105:16: error: ‘class v8::String’ has no member named ‘GetExternalAsciiStringResource’
     ext = str->GetExternalAsciiStringResource();
                ^
../binding.cpp: In function ‘void MakeCallback(uv_work_t*)’:
../binding.cpp:138:35: warning: ‘void node::FatalException(const v8::TryCatch&)’ is deprecated (declared at /home/javiercabrera/.node-gyp/2.5.0/src/node.h:282): Use FatalException(isolate, ...) [-Wdeprecated-declarations]
     node::FatalException(try_catch);
                                   ^
make: *** [Release/obj.target/binding/binding.o] Error 1
make: Leaving directory `/home/javiercabrera/smi-workspace/rapid-render/node_modules/lasso-sass/node_modules/node-sass/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/javiercabrera/.nvm/versions/io.js/v2.5.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.13.0-53-generic
gyp ERR! command "/home/javiercabrera/.nvm/versions/io.js/v2.5.0/bin/iojs" "/home/javiercabrera/.nvm/versions/io.js/v2.5.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/javiercabrera/smi-workspace/rapid-render/node_modules/lasso-sass/node_modules/node-sass
gyp ERR! node -v v2.5.0
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
Build failed
npm ERR! Linux 3.13.0-53-generic
npm ERR! argv "/home/javiercabrera/.nvm/versions/io.js/v2.5.0/bin/iojs" "/home/javiercabrera/.nvm/versions/io.js/v2.5.0/bin/npm" "install" "lasso-sass" "--save"
npm ERR! node v2.5.0
npm ERR! npm  v2.13.2
npm ERR! code ELIFECYCLE

npm ERR! node-sass@0.9.6 install: `node build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@0.9.6 install script 'node build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.


```

**Comment by saper** [comment]
node-sass@0.9.6 is ancient and will not work with node 2.5

**Comment by xzyfer** [comment]
Please update to recent 3.x version of node-sass.
