### ISSUE TITLE
Node sass build failure on windows 10

### ISSUE THREAD

**Issue by hitautodestruct** [sass/node-sass#1173]
While trying to install node-sass on windows 10 I get the following output:

```
C:\gulp\node_modules\gulp-sass>npm install node-sass
npm WARN deprecated pangyp@2.3.2: use node-gyp@3+, it does all the things
|
> node-sass@2.1.1 install C:\gulp\node_modules\gulp-sass\node_modules\node-sass
> node scripts/install.js

Can not download file from https://raw.githubusercontent.com/sass/node-sass-binaries/v2.1.1/win32-x64-node-4.1/binding.node

> node-sass@2.1.1 postinstall C:\gulp\node_modules\gulp-sass\node_modules\node-sass
> node scripts/build.js

gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: 404 status code downloading 64-bit node.lib
gyp ERR! stack     at Request.<anonymous> (C:\gulp\node_modules\gulp-sass\node_modules\node-sass\node_modules\pangyp\lib\install.js:403:20)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:169:7)
gyp ERR! stack     at Request.onRequestResponse (C:\gulp\node_modules\gulp-sass\node_modules\node-sass\node_modules\pangyp\node_modules\request\request.js:1255:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:415:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:305:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\gulp\\node_modules\\gulp-sass\\node_modules\\node-sass\\node_modules\\pangyp\\bin\\node-gyp" "rebuild"
gyp ERR! cwd C:\gulp\node_modules\gulp-sass\node_modules\node-sass
gyp ERR! node -v v4.1.1
gyp ERR! pangyp -v v2.3.2
gyp ERR! not ok
Build failed
node-sass@2.1.1 node_modules\node-sass
├── get-stdin@4.0.1
├── object-assign@2.1.1
├── replace-ext@0.0.1
├── semver@4.3.6
├── shelljs@0.3.0
├── cross-spawn@0.2.9 (lru-cache@2.7.0)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── chalk@0.5.1 (ansi-styles@1.1.0, escape-string-regexp@1.0.3, supports-color@0.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)
├── npmconf@2.1.2 (ini@1.3.4, uid-number@0.0.5, inherits@2.0.1, once@1.3.2, osenv@0.1.3, config-chain@1.1.9, nopt@3.0.4)
├── nan@1.9.0
├── gaze@0.5.1 (globule@0.1.0)
├── meow@3.3.0 (object-assign@3.0.0, minimist@1.2.0, camelcase-keys@1.0.0, indent-string@1.2.2)
├── sass-graph@1.3.0 (lodash@2.4.2, commander@2.8.1, glob@4.5.3)
├── mocha@2.3.3 (escape-string-regexp@1.0.2, diff@1.4.0, commander@2.3.0, growl@1.8.1, supports-color@1.2.0, debug@2.0.0, mkdirp@0.5.0, glob@3.2.3, jade@0.26.3)
├── request@2.63.0 (aws-sign2@0.5.0, forever-agent@0.6.1, tunnel-agent@0.4.1, oauth-sign@0.8.0, caseless@0.11.0, stringstream@0.0.4, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, qs@5.1.0, node-uuid@1.4.3, combined-stream@1.0.5, form-data@1.0.0-rc3, mime-types@2.1.7, tough-cookie@2.0.0, http-signature@0.11.0, hawk@3.1.0, bl@1.0.0, har-validator@1.8.0)
└── pangyp@2.3.2 (which@1.0.9, graceful-fs@3.0.8, rimraf@2.2.8, osenv@0.1.3, nopt@3.0.4, glob@4.3.5, fstream@1.0.8, minimatch@2.0.10, tar@1.0.3, request@2.51.0, npmlog@1.0.0)
```

**Comment by saper** [comment]
node-sass@2.1.1 is an old version that does not work with node 4.x. You need to upgrade to [node-sass@3.3.3](https://github.com/sass/node-sass/releases/tag/v3.3.3)
