### ISSUE TITLE
unable to build project that has node-sass on heroku (Error: libsass bindings not found. Try reinstalling node-sass?)

### ISSUE THREAD

**Issue by jianshentan** [sass/node-sass#1182]
I'm trying to get my keystone project up onto heroku. I'm able to run it locally, but when i push to heroku, it tells me that there is a problem with my node-sass. so i try rebuilding it (on heroku) but nothing i try seems to work.

Anyone know why?

Error that gets called when i check the heroku logs: 
"Error: libsass bindings not found. Try reinstalling node-sass"

I've attached the package.json file, the heroku deploy output and the heroku logs.

## package.json 

{
  "name": "thetoiletseatproject",
  "version": "0.0.0",
  "private": true,
  "dependencies": {
    "async": "^0.9.0",
    "cloudinary": "^1.0.12",
    "dotenv": "^1.1.0",
    "express-handlebars": "^1.1.0",
    "handlebars": "^2.0.0",
    "keystone": "^0.3.11",
    "moment": "^2.8.1",
    "node-sass": "^2.1.1",
    "node-sass-middleware": "^0.5.0",
    "underscore": "^1.8.0"
  },
  "devDependencies": {
    "grunt": "^0.4.4",
    "grunt-concurrent": "^0.5.0",
    "grunt-contrib-jshint": "^0.7.1",
    "grunt-contrib-watch": "^0.6.1",
    "grunt-express-server": "^0.4.17",
    "grunt-node-inspector": "^0.1.5",
    "grunt-nodemon": "^0.2.1",
    "grunt-sass": "^1.0.0",
    "jshint-stylish": "^0.1.3",
    "load-grunt-configs": "^0.4.1",
    "load-grunt-tasks": "^0.4.0",
    "open": "0.0.5",
    "time-grunt": "^0.3.1"
  },
  "engines": {
    "node": ">=0.12.4",
    "npm": ">=1.3.14"
  },
  "scripts": {
    "postinstall": "npm rebuild node-sass",
    "start": "node keystone.js"
  },
  "main": "keystone.js"
}

## when i run 'git push heroku master'

Counting objects: 3, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 288 bytes | 0 bytes/s, done.
Total 3 (delta 2), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Node.js app detected
remote: 
remote: -----> Creating runtime environment
remote:        
remote:        NPM_CONFIG_LOGLEVEL=error
remote:        NPM_CONFIG_PRODUCTION=true
remote:        NODE_ENV=production
remote:        NODE_MODULES_CACHE=true
remote: 
remote: -----> Installing binaries
remote:        engines.node (package.json):  >=0.12.4
remote:        engines.npm (package.json):   >=1.3.14
remote:        
remote:        Resolving node version >=0.12.4 via semver.io...
remote:        Downloading and installing node 4.1.1...
remote:        Resolving npm version >=1.3.14 via semver.io...
remote:        Downloading and installing npm 3.3.4 (replacing version 2.14.4)...
remote: 
remote: -----> Restoring cache
remote:        Loading 1 from cacheDirectories (default):
remote:        - node_modules
remote: 
remote: -----> Building dependencies
remote:        Pruning any extraneous modules
remote:        Installing node modules (package.json)
remote:        
remote:        > bson@0.2.22 install /tmp/build_0f7bd057d46896890e66be6434ed668c/node_modules/bson
remote:        > (node-gyp rebuild 2> builderror.log) || (exit 0)
remote:        
remote:        make: Entering directory `/tmp/build_0f7bd057d46896890e66be6434ed668c/node_modules/bson/build'
remote:          CXX(target) Release/obj.target/bson/ext/bson.o
remote:        make: Leaving directory `/tmp/build_0f7bd057d46896890e66be6434ed668c/node_modules/bson/build'
remote:        
remote:        > buffertools@2.1.3 install /tmp/build_0f7bd057d46896890e66be6434ed668c/node_modules/buffertools
remote:        > node-gyp rebuild
remote:        
remote:        make: Entering directory `/tmp/build_0f7bd057d46896890e66be6434ed668c/node_modules/buffertools/build'
remote:          CXX(target) Release/obj.target/buffertools/buffertools.o
remote:          SOLINK_MODULE(target) Release/obj.target/buffertools.node
remote:          COPY Release/buffertools.node
remote:        make: Leaving directory `/tmp/build_0f7bd057d46896890e66be6434ed668c/node_modules/buffertools/build'
remote:        
remote:        > kerberos@0.0.11 install /tmp/build_0f7bd057d46896890e66be6434ed668c/node_modules/kerberos
remote:        > (node-gyp rebuild 2> builderror.log) || (exit 0)
remote:        
remote:        make: Entering directory `/tmp/build_0f7bd057d46896890e66be6434ed668c/node_modules/kerberos/build'
remote:          CXX(target) Release/obj.target/kerberos/lib/kerberos.o
remote:        make: Leaving directory `/tmp/build_0f7bd057d46896890e66be6434ed668c/node_modules/kerberos/build'
remote:        
remote:        > unicode@0.6.1 postinstall /tmp/build_0f7bd057d46896890e66be6434ed668c/node_modules/unicode
remote:        > node install.js
remote:        
remote:        try to read file /usr/share/unicode/UnicodeData.txt …
remote:        /usr/share/unicode/UnicodeData.txt not found.
remote:        try to read file /usr/share/unicode-data/UnicodeData.txt …
remote:        /usr/share/unicode-data/UnicodeData.txt not found.
remote:        try to read file UnicodeData.txt …
remote:        UnicodeData.txt not found.
remote:        try to download …
remote:        GET unicode.org:80/Public/UNIDATA/UnicodeData.txt
remote:        fetching …
remote:        saving data as Cc.js …
remote:        saving data as Zs.js …
remote:        saving data as Po.js …
remote:        saving data as Sc.js …
remote:        saving data as Ps.js …
remote:        saving data as Pe.js …
remote:        saving data as Sm.js …
remote:        saving data as Pd.js …
remote:        saving data as Nd.js …
remote:        saving data as Lu.js …
remote:        saving data as Sk.js …
remote:        saving data as Pc.js …
remote:        saving data as Ll.js …
remote:        saving data as So.js …
remote:        saving data as Lo.js …
remote:        saving data as Pi.js …
remote:        saving data as Cf.js …
remote:        saving data as No.js …
remote:        saving data as Pf.js …
remote:        saving data as Lt.js …
remote:        saving data as Lm.js …
remote:        saving data as Mn.js …
remote:        saving data as Me.js …
remote:        saving data as Mc.js …
remote:        saving data as Nl.js …
remote:        saving data as Zl.js …
remote:        saving data as Zp.js …
remote:        saving data as Cs.js …
remote:        saving data as Co.js …
remote:        done.
remote:        
remote:        > thetoiletseatproject@0.0.0 postinstall /tmp/build_0f7bd057d46896890e66be6434ed668c
remote:        > npm rebuild node-sass
remote:        
remote:        
remote:        > node-sass@2.1.1 install /tmp/build_0f7bd057d46896890e66be6434ed668c/node_modules/node-sass
remote:        > node scripts/install.js
remote:        
remote:        
remote:        > node-sass@2.1.1 postinstall /tmp/build_0f7bd057d46896890e66be6434ed668c/node_modules/node-sass
remote:        > node scripts/build.js
remote:        
remote:        module.js:338
remote:            throw err;
remote:            ^
remote:        
remote:        Error: Cannot find module '/tmp/build_0f7bd057d46896890e66be6434ed668c/node_modules/node-sass/node_modules/pangyp/bin/node-gyp'
remote:            at Function.Module._resolveFilename (module.js:336:15)
remote:            at Function.Module._load (module.js:286:25)
remote:            at Function.Module.runMain (module.js:475:10)
remote:            at startup (node.js:117:18)
remote:            at node.js:951:3
remote:        Build failed
remote:        node-sass@2.1.1 /tmp/build_0f7bd057d46896890e66be6434ed668c/node_modules/node-sass
remote: 
remote: -----> Caching build
remote:        Clearing previous node cache
remote:        Saving 1 cacheDirectories (default):
remote:        - node_modules
remote: 
remote: -----> Build succeeded!
remote:        ├── async@0.9.2
remote:        ├── cloudinary@1.2.4
remote:        ├── dotenv@1.2.0
remote:        ├── express-handlebars@1.2.2
remote:        ├── handlebars@2.0.0
remote:        ├── keystone@0.3.14
remote:        ├── moment@2.10.6
remote:        ├── node-sass@2.1.1
remote:        ├── node-sass-middleware@0.5.0
remote:        └── underscore@1.8.3
remote:        
remote: -----> Discovering process types
remote:        Procfile declares types -> web
remote: 
remote: -----> Compressing... done, 44.5MB
remote: -----> Launching... done, v24
remote:        https://thetoiletseatproject.herokuapp.com/ deployed to Heroku
remote: 
remote: Verifying deploy.... done.
To https://git.heroku.com/thetoiletseatproject.git
   7174e58..9289878  master -> master

## when i run 'heroku logs'

2015-09-27T01:27:15.896927+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/node-sass/lib/index.js:188:23)
2015-09-27T01:27:15.896929+00:00 app[web.1]:     at Module._compile (module.js:434:26)
2015-09-27T01:27:15.896930+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:452:10)
2015-09-27T01:27:15.896932+00:00 app[web.1]:     at Module.load (module.js:355:32)
2015-09-27T01:27:15.896934+00:00 app[web.1]:     at Function.Module._load (module.js:310:12)
2015-09-27T01:27:15.896938+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/node-sass-middleware/middleware.js:1:74)
2015-09-27T01:27:15.896935+00:00 app[web.1]:     at Module.require (module.js:365:17)
2015-09-27T01:27:15.896940+00:00 app[web.1]:     at Module._compile (module.js:434:26)
2015-09-27T01:27:15.896937+00:00 app[web.1]:     at require (module.js:384:17)
2015-09-27T01:27:15.896942+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:452:10)
2015-09-27T01:27:15.896943+00:00 app[web.1]:     at Module.load (module.js:355:32)
2015-09-27T01:27:15.896945+00:00 app[web.1]:     at Function.Module._load (module.js:310:12)
2015-09-27T01:27:15.896946+00:00 app[web.1]:     at Module.require (module.js:365:17)
2015-09-27T01:27:15.896948+00:00 app[web.1]:     at require (module.js:384:17)
2015-09-27T01:27:15.896949+00:00 app[web.1]:     at mount (/app/node_modules/keystone/lib/core/mount.js:306:21)
2015-09-27T01:27:15.896953+00:00 app[web.1]:     at Object.<anonymous> (/app/keystone.js:71:10)
2015-09-27T01:27:15.896951+00:00 app[web.1]:     at start (/app/node_modules/keystone/lib/core/start.js:239:7)
2015-09-27T01:27:15.896954+00:00 app[web.1]:     at Module._compile (module.js:434:26)
2015-09-27T01:27:15.896956+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:452:10)
2015-09-27T01:27:15.896957+00:00 app[web.1]:     at Module.load (module.js:355:32)
2015-09-27T01:27:15.896959+00:00 app[web.1]:     at Function.Module._load (module.js:310:12)
2015-09-27T01:27:16.782961+00:00 heroku[web.1]: Process exited with status 1
2015-09-27T01:27:16.800158+00:00 heroku[web.1]: State changed from starting to crashed
2015-09-27T01:34:24.639406+00:00 heroku[api]: Deploy 9289878 by jianshentan@gmail.com
2015-09-27T01:34:24.639443+00:00 heroku[api]: Release v24 created by jianshentan@gmail.com
2015-09-27T01:34:24.774715+00:00 heroku[web.1]: State changed from crashed to starting
2015-09-27T01:34:24.701423+00:00 heroku[slug-compiler]: Slug compilation started
2015-09-27T01:34:24.701443+00:00 heroku[slug-compiler]: Slug compilation finished
2015-09-27T01:34:30.832592+00:00 heroku[web.1]: Starting process with command `node keystone.js`
2015-09-27T01:34:41.140038+00:00 app[web.1]: js-bson: Failed to load c++ bson extension, using pure JS version
2015-09-27T01:34:41.135527+00:00 app[web.1]: { [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
2015-09-27T01:34:43.555732+00:00 app[web.1]: Warning: connect.session() MemoryStore is not
2015-09-27T01:34:43.555736+00:00 app[web.1]: designed for a production environment, as it will leak
2015-09-27T01:34:43.555737+00:00 app[web.1]: memory, and will not scale past a single process.
2015-09-27T01:34:43.601234+00:00 app[web.1]: 				throw e;
2015-09-27T01:34:43.601230+00:00 app[web.1]: /app/node_modules/keystone/lib/core/mount.js:316
2015-09-27T01:34:43.601239+00:00 app[web.1]: 
2015-09-27T01:34:43.601241+00:00 app[web.1]: Error: `libsass` bindings not found. Try reinstalling `node-sass`?
2015-09-27T01:34:43.601238+00:00 app[web.1]: 				^
2015-09-27T01:34:43.601243+00:00 app[web.1]:     at getBinding (/app/node_modules/node-sass/lib/index.js:22:11)
2015-09-27T01:34:43.601244+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/node-sass/lib/index.js:188:23)
2015-09-27T01:34:43.601246+00:00 app[web.1]:     at Module._compile (module.js:434:26)
2015-09-27T01:34:43.601247+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:452:10)
2015-09-27T01:34:43.601250+00:00 app[web.1]:     at Function.Module._load (module.js:310:12)
2015-09-27T01:34:43.601249+00:00 app[web.1]:     at Module.load (module.js:355:32)
2015-09-27T01:34:43.601251+00:00 app[web.1]:     at Module.require (module.js:365:17)
2015-09-27T01:34:43.601253+00:00 app[web.1]:     at require (module.js:384:17)
2015-09-27T01:34:43.601254+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/node-sass-middleware/middleware.js:1:74)
2015-09-27T01:34:43.601258+00:00 app[web.1]:     at Module.load (module.js:355:32)
2015-09-27T01:34:43.601257+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:452:10)
2015-09-27T01:34:43.601256+00:00 app[web.1]:     at Module._compile (module.js:434:26)
2015-09-27T01:34:43.601260+00:00 app[web.1]:     at Function.Module._load (module.js:310:12)
2015-09-27T01:34:43.601261+00:00 app[web.1]:     at Module.require (module.js:365:17)
2015-09-27T01:34:43.601262+00:00 app[web.1]:     at require (module.js:384:17)
2015-09-27T01:34:43.601264+00:00 app[web.1]:     at mount (/app/node_modules/keystone/lib/core/mount.js:306:21)
2015-09-27T01:34:43.601265+00:00 app[web.1]:     at start (/app/node_modules/keystone/lib/core/start.js:239:7)
2015-09-27T01:34:43.601266+00:00 app[web.1]:     at Object.<anonymous> (/app/keystone.js:71:10)
2015-09-27T01:34:43.601268+00:00 app[web.1]:     at Module._compile (module.js:434:26)
2015-09-27T01:34:43.601269+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:452:10)
2015-09-27T01:34:43.601270+00:00 app[web.1]:     at Module.load (module.js:355:32)
2015-09-27T01:34:43.601271+00:00 app[web.1]:     at Function.Module._load (module.js:310:12)
2015-09-27T01:34:44.481939+00:00 heroku[web.1]: Process exited with status 1
2015-09-27T01:34:44.511228+00:00 heroku[web.1]: State changed from starting to crashed
2015-09-27T01:36:07.734199+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=thetoiletseatproject.herokuapp.com request_id=6f0976c4-2ed6-4e91-b83f-ed77f2bd42b9 fwd="64.134.128.17" dyno= connect= service= status=503 bytes=
2015-09-27T01:36:08.392613+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=thetoiletseatproject.herokuapp.com request_id=e818a26e-9fc6-49a3-9006-b401a395b35a fwd="64.134.128.17" dyno= connect= service= status=503 bytes=
2015-09-27T01:40:41.275354+00:00 heroku[web.1]: State changed from crashed to starting
2015-09-27T01:40:47.112291+00:00 heroku[web.1]: Starting process with command `node keystone.js`
2015-09-27T01:40:52.538564+00:00 app[web.1]: { [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
2015-09-27T01:40:52.540218+00:00 app[web.1]: js-bson: Failed to load c++ bson extension, using pure JS version
2015-09-27T01:40:52.968995+00:00 app[web.1]: Warning: connect.session() MemoryStore is not
2015-09-27T01:40:52.969002+00:00 app[web.1]: memory, and will not scale past a single process.
2015-09-27T01:40:52.969000+00:00 app[web.1]: designed for a production environment, as it will leak
2015-09-27T01:40:52.981073+00:00 app[web.1]: 				throw e;
2015-09-27T01:40:52.981070+00:00 app[web.1]: /app/node_modules/keystone/lib/core/mount.js:316
2015-09-27T01:40:52.981075+00:00 app[web.1]: 				^
2015-09-27T01:40:52.981078+00:00 app[web.1]: Error: `libsass` bindings not found. Try reinstalling `node-sass`?
2015-09-27T01:40:52.981076+00:00 app[web.1]: 
2015-09-27T01:40:52.981080+00:00 app[web.1]:     at getBinding (/app/node_modules/node-sass/lib/index.js:22:11)
2015-09-27T01:40:52.981081+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/node-sass/lib/index.js:188:23)
2015-09-27T01:40:52.981083+00:00 app[web.1]:     at Module._compile (module.js:434:26)
2015-09-27T01:40:52.981086+00:00 app[web.1]:     at Module.load (module.js:355:32)
2015-09-27T01:40:52.981084+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:452:10)
2015-09-27T01:40:52.981087+00:00 app[web.1]:     at Function.Module._load (module.js:310:12)
2015-09-27T01:40:52.981088+00:00 app[web.1]:     at Module.require (module.js:365:17)
2015-09-27T01:40:52.981090+00:00 app[web.1]:     at require (module.js:384:17)
2015-09-27T01:40:52.981091+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/node-sass-middleware/middleware.js:1:74)
2015-09-27T01:40:52.981093+00:00 app[web.1]:     at Module._compile (module.js:434:26)
2015-09-27T01:40:52.981094+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:452:10)
2015-09-27T01:40:52.981095+00:00 app[web.1]:     at Module.load (module.js:355:32)
2015-09-27T01:40:52.981097+00:00 app[web.1]:     at Function.Module._load (module.js:310:12)
2015-09-27T01:40:52.981099+00:00 app[web.1]:     at require (module.js:384:17)
2015-09-27T01:40:52.981098+00:00 app[web.1]:     at Module.require (module.js:365:17)
2015-09-27T01:40:52.981101+00:00 app[web.1]:     at mount (/app/node_modules/keystone/lib/core/mount.js:306:21)
2015-09-27T01:40:52.981102+00:00 app[web.1]:     at start (/app/node_modules/keystone/lib/core/start.js:239:7)
2015-09-27T01:40:52.981103+00:00 app[web.1]:     at Object.<anonymous> (/app/keystone.js:71:10)
2015-09-27T01:40:52.981105+00:00 app[web.1]:     at Module._compile (module.js:434:26)
2015-09-27T01:40:52.981106+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:452:10)
2015-09-27T01:40:52.981107+00:00 app[web.1]:     at Module.load (module.js:355:32)
2015-09-27T01:40:52.981108+00:00 app[web.1]:     at Function.Module._load (module.js:310:12)
2015-09-27T01:40:53.781838+00:00 heroku[web.1]: State changed from starting to crashed
2015-09-27T01:40:53.769654+00:00 heroku[web.1]: Process exited with status 1

**Comment by xzyfer** [comment]
You're installing node-sass@2.1.1 which only works on node 0.10 and 0.12, but you've told npm you require node >= 0.12.4.

```
"engines": {
  "node": ">=0.12.4",
  "npm": ">=1.3.14"
},
```

Please confirm you're using either node 0.10 or 0.12. You should also update to npm@2.x or 3.x because npm@1.x has issue with install scripts.

**Comment by corydorning** [comment]
I'm using Node v0.12.7, NPM 2.13.1 and this error just starting popping up. I'm using gulp-sass which defines node-sass v^2.0.1 as a dependency. My entire team is getting this. Any ideas?

**Comment by xzyfer** [comment]
> this error just starting popping up

This suggests your environment has changed. The `libsass bindings not found` _only_ happens when you have changed runtime environments after installing node-sass. This is easily resolved by running `npm rebuild node-sass` or removing your node_modules and reinstalling.

>The libsass binding was not found in x
>
>For context this error is almost always because npm install ran with a
>different version of node than the version you're current running.
>
>Since node-sass is a native module we build the c++ code on installation.
>That code is tied to the version of node that ran the installation. If you
change your node version the extension needs to be rebuilt, that's what
npm rebuild does.
>#906 (comment)

**Comment by Saturn2888** [comment]
This happened to me too when deploying to Heroku w/ Webpack and Express:

`git push heroku master` output
```shell
remote:        Installing node modules (package.json)
remote:
remote:        > node-sass@3.4.2 install /tmp/build_587da4274511f94f1010125c57cb5756/node_modules/node-sass
remote:        > node scripts/install.js
remote:
remote:        Binary downloaded and installed at /tmp/build_587da4274511f94f1010125c57cb5756/node_modules/node-sass/vendor/linux-x64-47/binding.node
remote:
remote:        > spawn-sync@1.0.13 postinstall /tmp/build_587da4274511f94f1010125c57cb5756/node_modules/spawn-sync
remote:        > node postinstall
remote:
remote:
remote:        > node-sass@3.4.2 postinstall /tmp/build_587da4274511f94f1010125c57cb5756/node_modules/node-sass
remote:        > node scripts/build.js
remote:
remote:        ` /tmp/build_587da4274511f94f1010125c57cb5756/node_modules/node-sass/vendor/linux-x64-47/binding.node ` exists.
remote:         testing binary.
remote:        Binary is fine; exiting.
```

`heroku logs` output
```shell
2015-12-24T10:44:29.092723+00:00 app[web.1]: ERROR in Cannot find module 'node-sass'
2015-12-24T10:44:29.092724+00:00 app[web.1]:  @ ./~/slick-carousel/slick/slick.scss 4:14-130
2015-12-24T10:44:29.092724+00:00 app[web.1]:
2015-12-24T10:44:29.092725+00:00 app[web.1]: ERROR in Cannot find module 'node-sass'
2015-12-24T10:44:29.092725+00:00 app[web.1]:  @ ./~/slick-carousel/slick/slick-theme.scss 4:14-136
```

And my `package.json` has:
```json
{
  "private": true,
  "scripts": {
    "postinstall": "npm prune",
    "prestart": "npm install",
    "start": "coffee index.coffee"
  },
  "engines": {
    "node": "5.3.0",
    "npm": "3.5.2"
  },
  "dependencies": {
    "babel-core": "^6.3.21",
    "babel-eslint": "^5.0.0-beta6",
    "babel-loader": "^6.2.0",
    "babel-preset-es2015": "^6.3.13",
    "babel-preset-react": "^6.3.13",
    "babel-preset-stage-0": "^6.3.13",
    "coffee-jsx-loader": "^0.1.3",
    "coffee-script": "^1.10.0",
    "css-loader": "^0.23.1",
    "eslint-plugin-react": "^3.11.3",
    "express": "^4.13.3",
    "file-loader": "^0.8.5",
    "history": "^1.17.0",
    "img-loader": "^1.2.2",
    "livescript-loader": "^0.1.5",
    "node-sass": "^3.4.2",
    "react": "^0.14.3",
    "react-dom": "^0.14.3",
    "react-hot-loader": "^1.3.0",
    "react-redux": "^4.0.1",
    "react-slick": "^0.9.3",
    "redux": "^3.0.5",
    "redux-thunk": "^1.0.2",
    "sass-loader": "^3.1.2",
    "style-loader": "^0.13.0",
    "stylus-loader": "^1.4.2",
    "url-loader": "^0.5.7",
    "webpack": "^1.12.9",
    "webpack-dev-server": "^1.14.0"
  },
  "optionalDependencies": {
    "react-router": "^1.0.2",
    "redux-simple-router": "^1.0.1"
  },
  "peerDependencies": {
    "history": "1.x",
    "node-sass": "^3.4.2"
  }
}
```

For whatever reason the site's loading now, and it appears it is building from node-sass, but this isn't the first time I got the error. What's going on?

**Comment by Saturn2888** [comment]
Maybe I did `heroku logs` to soon. It appears to be working now.

**Comment by Muzzamil75** [comment]
add this script in package.json
```
 "postinstall": "npm rebuild node-sass && npm install --unsafe-perm -f node-sass"
```

**Comment by askdesigners** [comment]
That did not solve my issue. Man I have never spent as much time deshitting a library as node-sass. I don't know why, after using this thing for 6 years, it still sucks every single time I have to update a node version. I'm grateful for Sass, and of course for the open source community, but this library is a constant thorn in my side.
