### ISSUE TITLE
node-sass@3.3.3 build error with Fedora core 22 

### ISSUE THREAD

**Issue by udomsak** [sass/node-sass#1187]
# Node version 
- OS: Distributor ID:	Fedora Description:	Fedora release 22 (Twenty Two) 
- Node Version: v4.0.0

# Error

```
[udomsak@dhcppc1 easykept]$ npm rebuild node-sass

> node-sass@2.1.1 install /home/udomsak/Developments/Spike/easykept/node_modules/gulp-sass/node_modules/node-sass
> node scripts/install.js

(node) child_process: options.customFds option is deprecated. Use options.stdio instead.

> node-sass@2.1.1 postinstall /home/udomsak/Developments/Spike/easykept/node_modules/gulp-sass/node_modules/node-sass
> node scripts/build.js

make: Entering directory '/home/udomsak/Developments/Spike/easykept/node_modules/gulp-sass/node_modules/node-sass/build'
  CXX(target) Release/obj.target/binding/src/binding.o
In file included from ../src/binding.cpp:1:0:
../node_modules/nan/nan.h:324:27: error: redefinition of ‘template<class T> v8::Local<T> Nan::imp::NanEnsureHandleOrPersistent(const v8::Local<T>&)’
   NAN_INLINE v8::Local<T> NanEnsureHandleOrPersistent(const v8::Local<T> &val) {
                           ^
../node_modules/nan/nan.h:319:17: note: ‘template<class T> v8::Handle<T> Nan::imp::NanEnsureHandleOrPersistent(v8::Handle<T>&)’ previously declared here
   v8::Handle<T> NanEnsureHandleOrPersistent(const v8::Handle<T> &val) {
                 ^
../node_modules/nan/nan.h:344:27: error: redefinition of ‘template<class T> v8::Local<T> Nan::imp::NanEnsureLocal(v8::Handle<T>&)’
   NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Handle<T> &val) {
                           ^
../node_modules/nan/nan.h:334:27: note: ‘template<class T> v8::Local<T> Nan::imp::NanEnsureLocal(const v8::Local<T>&)’ previously declared here
   NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Local<T> &val) {
                           ^
../node_modules/nan/nan.h:757:13: error: ‘node::smalloc’ has not been declared
     , node::smalloc::FreeCallback callback
             ^
../node_modules/nan/nan.h:757:35: error: expected ‘,’ or ‘...’ before ‘callback’
     , node::smalloc::FreeCallback callback
                                   ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)’:
../node_modules/nan/nan.h:761:50: error: ‘callback’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                  ^
../node_modules/nan/nan.h:761:60: error: ‘hint’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                            ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)’:
../node_modules/nan/nan.h:768:67: error: no matching function for call to ‘New(v8::Isolate*, const char*&, uint32_t&)’
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
In file included from ../node_modules/nan/nan.h:25:0,
                 from ../src/binding.cpp:1:
/home/udomsak/.node-gyp/4.0.0/src/node_buffer.h:31:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/udomsak/.node-gyp/4.0.0/src/node_buffer.h:31:40: note:   conversion of argument 3 would be ill-formed:
In file included from ../src/binding.cpp:1:0:
../node_modules/nan/nan.h:768:67: error: invalid conversion from ‘uint32_t {aka unsigned int}’ to ‘node::encoding’ [-fpermissive]
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
In file included from ../node_modules/nan/nan.h:25:0,
                 from ../src/binding.cpp:1:
/home/udomsak/.node-gyp/4.0.0/src/node_buffer.h:43:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/udomsak/.node-gyp/4.0.0/src/node_buffer.h:43:40: note:   conversion of argument 2 would be ill-formed:
In file included from ../src/binding.cpp:1:0:
../node_modules/nan/nan.h:768:67: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(uint32_t)’:
../node_modules/nan/nan.h:772:29: error: could not convert ‘node::Buffer::New(v8::Isolate::GetCurrent(), ((size_t)size))’ from ‘v8::MaybeLocal<v8::Object>’ to ‘v8::Local<v8::Object>’
     return node::Buffer::New(v8::Isolate::GetCurrent(), size);
                             ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanBufferUse(char*, uint32_t)’:
../node_modules/nan/nan.h:779:12: error: ‘Use’ is not a member of ‘node::Buffer’
     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
            ^
../src/binding.cpp: In function ‘void dispatched_async_uv_callback(uv_async_t*)’:
../src/binding.cpp:70:35: warning: ‘void node::FatalException(const v8::TryCatch&)’ is deprecated: Use FatalException(isolate, ...) [-Wdeprecated-declarations]
     node::FatalException(try_catch);
                                   ^
In file included from ../node_modules/nan/nan.h:24:0,
                 from ../src/binding.cpp:1:
/home/udomsak/.node-gyp/4.0.0/src/node.h:283:29: note: declared here
                 inline void FatalException(const v8::TryCatch& try_catch) {
                             ^
/home/udomsak/.node-gyp/4.0.0/src/node.h:66:42: note: in definition of macro ‘NODE_DEPRECATED’
     __attribute__((deprecated(message))) declarator
                                          ^
../src/binding.cpp: In function ‘void make_callback(uv_work_t*)’:
../src/binding.cpp:245:35: warning: ‘void node::FatalException(const v8::TryCatch&)’ is deprecated: Use FatalException(isolate, ...) [-Wdeprecated-declarations]
     node::FatalException(try_catch);
                                   ^
In file included from ../node_modules/nan/nan.h:24:0,
                 from ../src/binding.cpp:1:
/home/udomsak/.node-gyp/4.0.0/src/node.h:283:29: note: declared here
                 inline void FatalException(const v8::TryCatch& try_catch) {
                             ^
/home/udomsak/.node-gyp/4.0.0/src/node.h:66:42: note: in definition of macro ‘NODE_DEPRECATED’
     __attribute__((deprecated(message))) declarator
                                          ^
../src/binding.cpp: In function ‘void ImportedCallback(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/binding.cpp:365:35: warning: ‘void node::FatalException(const v8::TryCatch&)’ is deprecated: Use FatalException(isolate, ...) [-Wdeprecated-declarations]
     node::FatalException(try_catch);
                                   ^
In file included from ../node_modules/nan/nan.h:24:0,
                 from ../src/binding.cpp:1:
/home/udomsak/.node-gyp/4.0.0/src/node.h:283:29: note: declared here
                 inline void FatalException(const v8::TryCatch& try_catch) {
                             ^
/home/udomsak/.node-gyp/4.0.0/src/node.h:66:42: note: in definition of macro ‘NODE_DEPRECATED’
     __attribute__((deprecated(message))) declarator
                                          ^
binding.target.mk:128: recipe for target 'Release/obj.target/binding/src/binding.o' failed
make: *** [Release/obj.target/binding/src/binding.o] Error 1
make: Leaving directory '/home/udomsak/Developments/Spike/easykept/node_modules/gulp-sass/node_modules/node-sass/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/udomsak/Developments/Spike/easykept/node_modules/gulp-sass/node_modules/node-sass/node_modules/pangyp/lib/build.js:272:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.1.6-201.fc22.x86_64
gyp ERR! command "/usr/local/bin/node" "/home/udomsak/Developments/Spike/easykept/node_modules/gulp-sass/node_modules/node-sass/node_modules/pangyp/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/udomsak/Developments/Spike/easykept/node_modules/gulp-sass/node_modules/node-sass
gyp ERR! node -v v4.0.0
gyp ERR! pangyp -v v2.3.2
gyp ERR! not ok 
Build failed

> node-sass@3.3.3 install /home/udomsak/Developments/Spike/easykept/node_modules/node-sass
> node scripts/install.js


> node-sass@3.3.3 postinstall /home/udomsak/Developments/Spike/easykept/node_modules/node-sass
> node scripts/build.js

` /home/udomsak/Developments/Spike/easykept/node_modules/node-sass/vendor/linux-x64-46/binding.node ` exists. 
 testing binary.
Binary is fine; exiting.

```

##  Error when try to run from ionic-framework 

```
[udomsak@dhcppc1 easykept]$ ionic setup sass 
npmnpm WARN package.json easykept@1.0.0 No README data
npm WARN package.json easykept@1.0.0 No license field.

> node-sass@3.3.3 install /home/udomsak/Developments/Spike/easykept/node_modules/node-sass
> node scripts/install.js


> node-sass@3.3.3 postinstall /home/udomsak/Developments/Spike/easykept/node_modules/node-sass
> node scripts/build.js

` /home/udomsak/Developments/Spike/easykept/node_modules/node-sass/vendor/linux-x64-46/binding.node ` exists. 
 testing binary.
Binary is fine; exiting.

Successful npm install
Updated /home/udomsak/Developments/Spike/easykept/www/index.html <link href> references to sass compiled css

Ionic project ready to use Sass!
 * Customize the app using scss/ionic.app.scss
 * Run ionic serve to start a local dev server and watch/compile Sass to CSS

/home/udomsak/Developments/Spike/easykept/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:22
    throw new Error('`libsass` bindings not found. Try reinstalling `node-sass`?');
    ^

Error: `libsass` bindings not found. Try reinstalling `node-sass`?
    at getBinding (/home/udomsak/Developments/Spike/easykept/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:22:11)
    at Object.<anonymous> (/home/udomsak/Developments/Spike/easykept/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:188:23)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/udomsak/Developments/Spike/easykept/node_modules/gulp-sass/index.js:3:17)
    at Module._compile (module.js:434:26)

Error running gulp sass

```

**Comment by xzyfer** [comment]
The first error is due to you using node-sass@2.1.1 which is not compatible with Node 4.
The second error is confusing and unclear. Ionic is not compatible with node-sass 3.3.3.

Please install node-sass 3.3.3 on it's own without ionic to assert it's actually broken on your OS.

**Comment by xzyfer** [comment]
@saper I've PR'd ionic to fix their broken dependency https://github.com/driftyco/ionic/pull/4449

**Comment by udomsak** [comment]
@xzyfer  ok. confirm problem occur with ionic.  Thank you 

- install node-sass on it own work. :+1: 
- with ionic not work ( version 1.6.5 )  
- ionic work with node version 10.3.36  / npm version 1.4.28
