### ISSUE TITLE
cannot install node-sass with Linux 2.6.32_1-15-0-0 node v0.12.2 npm v2.14.8

### ISSUE THREAD

**Issue by tshawn** [sass/node-sass#1200]
I tried many times,but still cannot install the node-sass, it seems has some problem with Linux 2.6.32_1-15-0-0 node v0.12.2 npm v2.14.8, here is the errors in last of the npm-debug.log:

> spawn-sync@1.0.13 postinstall /home/users/xiaoguang01/.jumbo/lib/node_modules/node-sass/node_modules/cross-spawn/node_modules/spawn-sync
> node postinstall

/home/users/xiaoguang01/.jumbo/bin/node-sass -> /home/users/xiaoguang01/.jumbo/lib/node_modules/node-sass/bin/node-sass

> node-sass@3.3.3 install /home/users/xiaoguang01/.jumbo/lib/node_modules/node-sass
> node scripts/install.js

Cannot download "https://github.com/sass/node-sass/releases/download/v3.3.3/linux-x64-14_binding.node": connect ETIMEDOUT

> node-sass@3.3.3 postinstall /home/users/xiaoguang01/.jumbo/lib/node_modules/node-sass
> node scripts/build.js

Building: /home/users/xiaoguang01/.jumbo/bin/node /home/users/xiaoguang01/.jumbo/lib/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/home/users/xiaoguang01/.jumbo/bin/node',
gyp verb cli   '/home/users/xiaoguang01/.jumbo/lib/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.0.3
gyp info using node@0.12.2 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /home/users/xiaoguang01/.jumbo/bin/python2
gyp verb check python version `python2 -c "import platform; print(platform.python_version());"` returned: "2.7.3\n"
gyp verb get node dir no --target version specified, falling back to host node version: 0.12.2
gyp verb command install [ '0.12.2' ]
gyp verb install input version string "0.12.2"
gyp verb install installing version: 0.12.2
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 0.12.2
gyp verb build dir attempting to create "build" dir: /home/users/xiaoguang01/.jumbo/lib/node_modules/node-sass/build
gyp verb build dir "build" dir needed to be created? /home/users/xiaoguang01/.jumbo/lib/node_modules/node-sass/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /home/users/xiaoguang01/.jumbo/lib/node_modules/node-sass/build/config.gypi
gyp verb config.gypi checking for gypi file: /home/users/xiaoguang01/.jumbo/lib/node_modules/node-sass/config.gypi
gyp verb common.gypi checking for gypi file: /home/users/xiaoguang01/.jumbo/lib/node_modules/node-sass/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn python2
gyp info spawn args [ '/home/users/xiaoguang01/.jumbo/lib/node_modules/node-sass/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/users/xiaoguang01/.jumbo/lib/node_modules/node-sass/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/users/xiaoguang01/.jumbo/lib/node_modules/node-sass/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/users/xiaoguang01/.node-gyp/0.12.2/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/users/xiaoguang01/.node-gyp/0.12.2',
gyp info spawn args   '-Dnode_gyp_dir=/home/users/xiaoguang01/.jumbo/lib/node_modules/node-sass/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/users/xiaoguang01/.jumbo/lib/node_modules/node-sass',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /home/users/xiaoguang01/.node-gyp/0.12.2
gyp verb `which` succeeded for `make` /home/users/xiaoguang01/.jumbo/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
make: 进入目录“/home/users/xiaoguang01/.jumbo/lib/node_modules/node-sass/build”
  g++ '-DNODE_GYP_MODULE_NAME=libsass' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DLIBSASS_VERSION="3.2.5"' -I/home/users/xiaoguang01/.node-gyp/0.12.2/include/node -I/home/users/xiaoguang01/.node-gyp/0.12.2/src -I/home/users/xiaoguang01/.node-gyp/0.12.2/deps/uv/include -I/home/users/xiaoguang01/.node-gyp/0.12.2/deps/v8/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -ffunction-sections -fdata-sections -fno-tree-vrp -fno-omit-frame-pointer -fno-rtti -std=c++0x -fexceptions -frtti -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/ast.o.d.raw  -c -o Release/obj.target/libsass/src/libsass/ast.o ../src/libsass/ast.cpp
cc1plus: error: unrecognized command line option "-std=c++0x"
cc1plus: error: unrecognized command line option "-fno-tree-vrp"
make: *** [Release/obj.target/libsass/src/libsass/ast.o] 错误 1
make: 离开目录“/home/users/xiaoguang01/.jumbo/lib/node_modules/node-sass/build”
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/users/xiaoguang01/.jumbo/lib/node_modules/node-sass/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 2.6.32_1-15-0-0
gyp ERR! command "/home/users/xiaoguang01/.jumbo/bin/node" "/home/users/xiaoguang01/.jumbo/lib/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/users/xiaoguang01/.jumbo/lib/node_modules/node-sass
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
Build failed
npm ERR! Linux 2.6.32_1-15-0-0
npm ERR! argv "/home/users/xiaoguang01/.jumbo/bin/node" "/home/users/xiaoguang01/.jumbo/bin/npm" "install" "node-sass" "-g"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.3.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.3.3 postinstall script 'node scripts/build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/users/xiaoguang01/npm-debug.log

**Comment by saper** [comment]
This is because the installer could not connect to https://github.com/sass/node-sass/releases/download/v3.3.3/linux-x64-14_binding.node - this is just a networking error. You can download it by hand or try to configure `npm` to use proxy, in order to have a better connection to Github.

**Comment by tshawn** [comment]
thanks for your help , I fixed the  networking error, and has download the linux-x64-14/binding.node, but still has promble, with the error msg :"Problem with the binary."

` /home/users/xiaoguang01/.jumbo/lib/node_modules/phantomas/node_modules/analyze-css/node_modules/node-sass/vendor/linux-x64-14/binding.node ` exists. 
 testing binary.
Problem with the binary.            (=================== here===============)
Manual build incoming.
Building: /home/users/xiaoguang01/.jumbo/bin/node /home/users/xiaoguang01/.jumbo/lib/node_modules/phantomas/node_modules/analyze-css/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/home/users/xiaoguang01/.jumbo/bin/node',
gyp verb cli   '/home/users/xiaoguang01/.jumbo/lib/node_modules/phantomas/node_modules/analyze-css/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.0.3
gyp info using node@0.12.2 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /home/users/xiaoguang01/.jumbo/bin/python2
gyp verb check python version `python2 -c "import platform; print(platform.python_version());"` returned: "2.7.3\n"
gyp verb get node dir no --target version specified, falling back to host node version: 0.12.2
gyp verb command install [ '0.12.2' ]
gyp verb install input version string "0.12.2"
gyp verb install installing version: 0.12.2
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 0.12.2
gyp verb build dir attempting to create "build" dir: /home/users/xiaoguang01/.jumbo/lib/node_modules/phantomas/node_modules/analyze-css/node_modules/node-sass/build
gyp verb build dir "build" dir needed to be created? /home/users/xiaoguang01/.jumbo/lib/node_modules/phantomas/node_modules/analyze-css/node_modules/node-sass/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /home/users/xiaoguang01/.jumbo/lib/node_modules/phantomas/node_modules/analyze-css/node_modules/node-sass/build/config.gypi
gyp verb config.gypi checking for gypi file: /home/users/xiaoguang01/.jumbo/lib/node_modules/phantomas/node_modules/analyze-css/node_modules/node-sass/config.gypi
gyp verb common.gypi checking for gypi file: /home/users/xiaoguang01/.jumbo/lib/node_modules/phantomas/node_modules/analyze-css/node_modules/node-sass/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn python2
gyp info spawn args [ '/home/users/xiaoguang01/.jumbo/lib/node_modules/phantomas/node_modules/analyze-css/node_modules/node-sass/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/users/xiaoguang01/.jumbo/lib/node_modules/phantomas/node_modules/analyze-css/node_modules/node-sass/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/users/xiaoguang01/.jumbo/lib/node_modules/phantomas/node_modules/analyze-css/node_modules/node-sass/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/users/xiaoguang01/.node-gyp/0.12.2/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/users/xiaoguang01/.node-gyp/0.12.2',
gyp info spawn args   '-Dnode_gyp_dir=/home/users/xiaoguang01/.jumbo/lib/node_modules/phantomas/node_modules/analyze-css/node_modules/node-sass/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/users/xiaoguang01/.jumbo/lib/node_modules/phantomas/node_modules/analyze-css/node_modules/node-sass',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /home/users/xiaoguang01/.node-gyp/0.12.2
gyp verb `which` succeeded for `make` /home/users/xiaoguang01/.jumbo/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
make: 进入目录“/home/users/xiaoguang01/.jumbo/lib/node_modules/phantomas/node_modules/analyze-css/node_modules/node-sass/build”
  g++ '-DNODE_GYP_MODULE_NAME=libsass' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DLIBSASS_VERSION="3.2.5"' -I/home/users/xiaoguang01/.node-gyp/0.12.2/include/node -I/home/users/xiaoguang01/.node-gyp/0.12.2/src -I/home/users/xiaoguang01/.node-gyp/0.12.2/deps/uv/include -I/home/users/xiaoguang01/.node-gyp/0.12.2/deps/v8/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -ffunction-sections -fdata-sections -fno-tree-vrp -fno-omit-frame-pointer -fno-rtti -std=c++0x -fexceptions -frtti -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/ast.o.d.raw  -c -o Release/obj.target/libsass/src/libsass/ast.o ../src/libsass/ast.cpp
cc1plus: error: unrecognized command line option "-std=c++0x"
cc1plus: error: unrecognized command line option "-fno-tree-vrp"
make: *** [Release/obj.target/libsass/src/libsass/ast.o] 错误 1
make: 离开目录“/home/users/xiaoguang01/.jumbo/lib/node_modules/phantomas/node_modules/analyze-css/node_modules/node-sass/build”
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/users/xiaoguang01/.jumbo/lib/node_modules/phantomas/node_modules/analyze-css/node_modules/node-sass/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 2.6.32_1-15-0-0
gyp ERR! command "/home/users/xiaoguang01/.jumbo/bin/node" "/home/users/xiaoguang01/.jumbo/lib/node_modules/phantomas/node_modules/analyze-css/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/users/xiaoguang01/.jumbo/lib/node_modules/phantomas/node_modules/analyze-css/node_modules/node-sass
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
Build failed
npm ERR! Linux 2.6.32_1-15-0-0
npm ERR! argv "node" "/home/users/xiaoguang01/.jumbo/lib/node_modules/cnpm/node_modules/.bin/npm" "--userconfig=/home/users/xiaoguang01/.cnpmrc" "--disturl=https://npm.taobao.org/mirrors/node" "--cache=/home/users/xiaoguang01/.cnpm" "--registry=https://registry.npm.taobao.org" "--node-gyp=/home/users/xiaoguang01/.jumbo/lib/node_modules/cnpm/node_modules/node-gyp/bin/node-gyp.js" "install" "-g" "phantomas"
npm ERR! node v0.12.2
npm ERR! npm  v2.14.8
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.3.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.3.3 postinstall script 'node scripts/build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/users/xiaoguang01/friendly/npm-debug.log

**Comment by xzyfer** [comment]
It would appear your system is incompatible with out binary. Please follow the steps in the [troubleshooting guide](https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md) and persist **all** the output into a github gist.

Do **not** post the output in this is issue directly.

**Comment by xzyfer** [comment]
Closing due to inactivity.
