### ISSUE TITLE
Libsass binding was not found - node-sass/vendor/linux-x64-47

### ISSUE THREAD

**Issue by bhargav175** [sass/node-sass#1249]
I am running Node - 5.0.0. I get this error when I am using webpack with node-sass.

    Module build failed: Error: The `libsass` binding was not found in     /home/bhargav/code/flash/node_modules/node-sass/vendor/linux-x64-47/binding.node
    This usually happens because your node version has changed.
    Run `npm rebuild node-sass` to build the binding for your current node version.
    at Object.sass.getBinaryPath (/home/bhargav/code/flash/node_modules/node-sass/lib/extensions.js:158:11)
    at Object.<anonymous> (/home/bhargav/code/flash/node_modules/node-sass/lib/index.js:16:36)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/bhargav/code/flash/node_modules/sass-loader/index.js:4:12)
    at Module._compile (module.js:425:26)
    Child extract-text-webpack-plugin:
    
    ERROR in The `libsass` binding was not found in /home/bhargav/code/flash/node_modules/node-sass/vendor/linux-x64-47/binding.node
        This usually happens because your node version has changed.
        Run `npm rebuild node-sass` to build the binding for your current node version.
    
I am using node-sass 3.4.1. I tried npm rebuild. I tried it on node 0.12.7 and node 4.0.0 as well. I tried removing node_modules and running npm update as well. Please help.

**Comment by bhargav175** [comment]
It worked on reopening the terminal.
