### ISSUE TITLE
Error installing/building node-sass [node v4.2.1]

### ISSUE THREAD

**Issue by Zorgatone** [sass/node-sass#1250]
I don't know if it's related to `node-sass` or `libsass` but I get these compilation errors when I try to install node-sass:

```bash
TR: ~/repos/ionic-webpack tommaso$ npm install --save node-sass

> bignum@0.9.3 install /Users/webdev1/repos/ionic-webpack/node_modules/bignum
> node-gyp configure build

2015-11-09 12:00:22.985 xcodebuild[5507:103708] [MT] PluginLoading: Required plug-in compatibility UUID 7265231C-39B4-402C-89E1-16167C4CC990 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/EditorConfig.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2015-11-09 12:00:22.987 xcodebuild[5507:103708] [MT] PluginLoading: Required plug-in compatibility UUID 7265231C-39B4-402C-89E1-16167C4CC990 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin' not present in DVTPlugInCompatibilityUUIDs
  CXX(target) Release/obj.target/bignum/bignum.o
In file included from ../bignum.cc:8:
../node_modules/nan/nan.h:261:25: error: redefinition of '_NanEnsureLocal'
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../node_modules/nan/nan.h:256:25: note: previous definition is here
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                        ^
../node_modules/nan/nan.h:661:13: error: no member named 'smalloc' in namespace 'node'
    , node::smalloc::FreeCallback callback
      ~~~~~~^
../node_modules/nan/nan.h:672:12: error: no matching function for call to 'New'
    return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
           ^~~~~~~~~~~~~~~~~
/Users/webdev1/.node-gyp/4.2.1/include/node/node_buffer.h:31:40: note: candidate function
      not viable: no known conversion from 'uint32_t' (aka 'unsigned int') to
      'enum encoding' for 3rd argument
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/webdev1/.node-gyp/4.2.1/include/node/node_buffer.h:43:40: note: candidate function
      not viable: 2nd argument ('const char *') would lose const qualifier
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/webdev1/.node-gyp/4.2.1/include/node/node_buffer.h:28:40: note: candidate function
      not viable: requires 2 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                       ^
/Users/webdev1/.node-gyp/4.2.1/include/node/node_buffer.h:36:40: note: candidate function
      not viable: requires 5 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
In file included from ../bignum.cc:8:
../node_modules/nan/nan.h:676:12: error: no viable conversion from
      'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object>'
    return node::Buffer::New(v8::Isolate::GetCurrent(), size);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/webdev1/.node-gyp/4.2.1/include/node/v8.h:210:7: note: candidate constructor (the
      implicit copy constructor) not viable: no known conversion from
      'v8::MaybeLocal<v8::Object>' to 'const v8::Local<v8::Object> &' for 1st argument
class Local {
      ^
/Users/webdev1/.node-gyp/4.2.1/include/node/v8.h:210:7: note: candidate constructor (the
      implicit move constructor) not viable: no known conversion from
      'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object> &&' for 1st argument
class Local {
      ^
/Users/webdev1/.node-gyp/4.2.1/include/node/v8.h:214:13: note: candidate template ignored:
      could not match 'Local' against 'MaybeLocal'
  V8_INLINE Local(Local<S> that)
            ^
/Users/webdev1/.node-gyp/4.2.1/include/node/v8.h:326:13: note: candidate template ignored:
      could not match 'S *' against 'v8::MaybeLocal<v8::Object>'
  V8_INLINE Local(S* that)
            ^
In file included from ../bignum.cc:8:
../node_modules/nan/nan.h:683:26: error: no member named 'Use' in namespace 'node::Buffer'
    return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
           ~~~~~~~~~~~~~~^
In file included from ../bignum.cc:8:
In file included from ../node_modules/nan/nan.h:24:
In file included from /Users/webdev1/.node-gyp/4.2.1/include/node/node.h:42:
/Users/webdev1/.node-gyp/4.2.1/include/node/v8.h:221:5: error: assigning to
      'v8::Primitive *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/webdev1/.node-gyp/4.2.1/include/node/v8.h:180:37: note: expanded from macro
      'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:414:12: note: in instantiation of function template
      specialization 'v8::Local<v8::Primitive>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::Undefined(v8::Isolate::GetCurrent())));
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../bignum.cc:8:
In file included from ../node_modules/nan/nan.h:24:
In file included from /Users/webdev1/.node-gyp/4.2.1/include/node/node.h:42:
/Users/webdev1/.node-gyp/4.2.1/include/node/v8.h:221:5: error: assigning to
      'v8::Boolean *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/webdev1/.node-gyp/4.2.1/include/node/v8.h:180:37: note: expanded from macro
      'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:424:12: note: in instantiation of function template
      specialization 'v8::Local<v8::Boolean>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::True(v8::Isolate::GetCurrent())));
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../bignum.cc:8:
In file included from ../node_modules/nan/nan.h:24:
In file included from /Users/webdev1/.node-gyp/4.2.1/include/node/node.h:42:
/Users/webdev1/.node-gyp/4.2.1/include/node/v8.h:221:5: error: assigning to
      'v8::Function *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/webdev1/.node-gyp/4.2.1/include/node/v8.h:180:37: note: expanded from macro
      'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1514:12: note: in instantiation of function template
      specialization 'v8::Local<v8::Function>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(handle)->Get(kCallbackIndex)
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../bignum.cc:8:
In file included from ../node_modules/nan/nan.h:24:
In file included from /Users/webdev1/.node-gyp/4.2.1/include/node/node.h:42:
/Users/webdev1/.node-gyp/4.2.1/include/node/v8.h:221:5: error: assigning to
      'v8::Object *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/webdev1/.node-gyp/4.2.1/include/node/v8.h:180:37: note: expanded from macro
      'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1632:12: note: in instantiation of function template
      specialization 'v8::Local<v8::Object>::Local<v8::Value>' requested here
    return NanEscapeScope(handle->Get(NanNew(key)).As<v8::Object>());
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
9 errors generated.
make: *** [Release/obj.target/bignum/bignum.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /Users/webdev1/repos/ionic-webpack/node_modules/bignum
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN install:bignum@0.9.3 bignum@0.9.3 install: `node-gyp configure build`
npm WARN install:bignum@0.9.3 Exit status 1

> node-sass@3.4.1 install /Users/webdev1/repos/ionic-webpack/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /Users/webdev1/repos/ionic-webpack/node_modules/node-sass/vendor/darwin-x64-46/binding.node

> node-sass@3.4.1 postinstall /Users/webdev1/repos/ionic-webpack/node_modules/node-sass
> node scripts/build.js

` /Users/webdev1/repos/ionic-webpack/node_modules/node-sass/vendor/darwin-x64-46/binding.node ` exists.
 testing binary.
Binary is fine; exiting.
- readable-stream@2.0.4 node_modules/bl/node_modules/readable-stream
- graceful-fs@1.2.3 node_modules/globule/node_modules/graceful-fs
- minimatch@0.2.14 node_modules/globule/node_modules/minimatch
- glob@5.0.15 node_modules/node-sass/node_modules/glob
- glob@5.0.15 node_modules/rimraf/node_modules/glob
- glob@5.0.15 node_modules/sass-graph/node_modules/glob
ionic-webpack@0.0.1 /Users/webdev1/repos/ionic-webpack
├─┬ bower@1.6.5
│ ├─┬ bower-config@1.2.2
│ │ └── graceful-fs@4.1.2
│ ├─┬ bower-registry-client@1.0.0
│ │ └── graceful-fs@4.1.2
│ ├─┬ decompress-zip@0.1.0
│ │ └── readable-stream@1.1.13
│ ├─┬ fs-write-stream-atomic@1.0.4
│ │ └── graceful-fs@4.1.2
│ ├─┬ fstream@1.0.8
│ │ └── graceful-fs@4.1.2
│ ├─┬ fstream-ignore@1.0.2
│ │ └── minimatch@2.0.10
│ ├─┬ glob@4.5.3
│ │ └── minimatch@2.0.10
│ ├─┬ insight@0.7.0
│ │ ├─┬ configstore@1.2.1
│ │ │ └── graceful-fs@4.1.2
│ │ └─┬ os-name@1.0.3
│ │   └─┬ win-release@1.1.1
│ │     └── semver@5.0.3
│ ├─┬ rimraf@2.4.3
│ │ └─┬ glob@5.0.15
│ │   └── minimatch@3.0.0
│ └─┬ update-notifier@0.3.2
│   └─┬ semver-diff@2.0.0
│     └── semver@4.3.6
├─┬ del@0.1.3
│ └─┬ globby@0.1.1
│   └─┬ glob@4.5.3
│     └── minimatch@2.0.10
├─┬ gulp@3.9.0
│ ├─┬ liftoff@2.2.0
│ │ └─┬ findup-sync@0.3.0
│ │   └─┬ glob@5.0.15
│ │     └── minimatch@3.0.0
│ ├── semver@4.3.6
│ └─┬ vinyl-fs@0.3.14
│   └─┬ glob-stream@3.1.18
│     ├── glob@4.5.3
│     └── minimatch@2.0.10
├─┬ gulp-util@3.0.7
│ ├─┬ multipipe@0.1.2
│ │ └─┬ duplexer2@0.0.2
│ │   └── readable-stream@1.1.13
│ └─┬ through2@2.0.0
│   └── readable-stream@2.0.4
├─┬ html-webpack-plugin@1.6.2
│ └─┬ html-minifier@0.7.2
│   └─┬ concat-stream@1.4.10
│     └── readable-stream@1.1.13
├─┬ node-sass@3.4.1
│ ├─┬ cross-spawn@2.0.0
│ │ └─┬ spawn-sync@1.0.14
│ │   └── concat-stream@1.5.1
│ ├─┬ gaze@0.5.2
│ │ └─┬ globule@0.1.0
│ │   ├─┬ glob@3.1.21
│ │   │ └── graceful-fs@1.2.3
│ │   └── minimatch@0.2.14
│ ├─┬ glob@5.0.15
│ │ └── minimatch@3.0.0
│ ├─┬ meow@3.5.0
│ │ └─┬ read-pkg-up@1.0.1
│ │   └─┬ read-pkg@1.1.0
│ │     ├─┬ load-json-file@1.0.1
│ │     │ └── graceful-fs@4.1.2
│ │     └─┬ path-type@1.0.0
│ │       └── graceful-fs@4.1.2
│ ├─┬ node-gyp@3.0.3
│ │ ├─┬ fstream@1.0.8
│ │ │ └── graceful-fs@4.1.2
│ │ ├─┬ glob@4.5.3
│ │ │ └── minimatch@2.0.10
│ │ ├── graceful-fs@4.1.2
│ │ ├─┬ npmlog@1.2.1
│ │ │ └─┬ are-we-there-yet@1.0.4
│ │ │   └── readable-stream@1.1.13
│ │ └── semver@5.0.3
│ ├─┬ npmconf@2.1.2
│ │ └── semver@4.3.6
│ └─┬ request@2.65.0
│   └─┬ bl@1.0.0
│     └── readable-stream@2.0.4
└─┬ webpack@1.12.3
  ├─┬ enhanced-resolve@0.9.1
  │ └── graceful-fs@4.1.2
  ├─┬ node-libs-browser@0.5.3
  │ ├── readable-stream@1.1.13
  │ └─┬ stream-browserify@1.0.0
  │   └── readable-stream@1.1.13
  └─┬ watchpack@0.2.9
    ├─┬ chokidar@1.2.0
    │ ├─┬ fsevents@1.0.5
    │ │ └─┬ node-pre-gyp@0.6.15
    │ │   ├─┬ npmlog@1.2.1
    │ │   │ └─┬ are-we-there-yet@1.0.4
    │ │   │   └── readable-stream@1.1.13
    │ │   ├─┬ request@2.65.0
    │ │   │ └─┬ bl@1.0.0
    │ │   │   └── readable-stream@2.0.4
    │ │   ├─┬ rimraf@2.4.3
    │ │   │ └─┬ glob@5.0.15
    │ │   │   └── minimatch@3.0.0
    │ │   ├── semver@5.0.3
    │ │   └─┬ tar-pack@3.1.0
    │ │     ├─┬ fstream-ignore@1.0.3
    │ │     │ └── minimatch@3.0.0
    │ │     └── graceful-fs@4.1.2
    │ └─┬ readdirp@2.0.0
    │   ├── graceful-fs@4.1.2
    │   ├── minimatch@2.0.10
    │   └── readable-stream@2.0.4
    └── graceful-fs@4.1.2

npm WARN EPACKAGEJSON ionic-webpack@0.0.1 No repository field.
npm WARN EPACKAGEJSON ionic-webpack@0.0.1 No license field.
TR: ~/repos/ionic-webpack tommaso$

```

**Comment by saper** [comment]
node-sass installed fine and seems to work.

You need to check your `ionic-webpack` dependency, it uses an old  `bignum@0.9.3` version that does not support newer versions of node. Current [version of bignum is 0.11.0](https://github.com/justmoon/node-bignum/releases/tag/v0.11.0), which might work.

Alternatively you might downgrade your node engine.
