### ISSUE TITLE
Issues with python 3.5.0 and python 2.7.10 and/or gyp

### ISSUE THREAD

**Issue by nicolasdanelon** [sass/node-sass#1251]
I'm trying to use node-sass but when I run my gulp task I got the following issues:

[Here I run the node-sass test script](https://gist.github.com/nicolasdanelon/722a585a1761808633d1)

```bash

[nda@stark frontend]$ gulp watch
/srv/http/website/frontend/node_modules/node-sass/lib/index.js:22
    throw new Error('`libsass` bindings not found. Try reinstalling `node-sass`?');
    ^

Error: `libsass` bindings not found. Try reinstalling `node-sass`?
    at getBinding (/srv/http/website/frontend/node_modules/node-sass/lib/index.js:22:11)
    at Object.<anonymous> (/srv/http/website/frontend/node_modules/node-sass/lib/index.js:188:23)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/srv/http/website/frontend/node_modules/gulp-sass/index.js:3:17)
    at Module._compile (module.js:425:26)
[nda@stark frontend]$ 
```

I got this information... I try switching between **Python 2.7.10** and **Python 3.5.0** but no luck

```bash
[nda@stark frontend]$ gulp -v
[09:30:37] CLI version 3.9.0
[09:30:37] Local version 3.9.0

[nda@stark frontend]$ node -v
v5.0.0

[nda@stark frontend]$ uname -a
Linux stark 4.2.5-1-ARCH #1 SMP PREEMPT Tue Oct 27 08:13:28 CET 2015 x86_64 GNU/Linux

[nda@stark frontend]$ python --version
Python 3.5.0
[nda@stark frontend]$ npm rebuild node-sass

> node-sass@2.1.1 install /srv/http/website/frontend/node_modules/node-sass
> node scripts/install.js


> node-sass@2.1.1 postinstall /srv/http/website/frontend/node_modules/node-sass
> node scripts/build.js

gyp ERR! configure error 
gyp ERR! stack Error: Python executable "python" is v3.5.0, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (/srv/http/website/frontend/node_modules/node-sass/node_modules/pangyp/lib/configure.js:110:14)
gyp ERR! stack     at /srv/http/website/frontend/node_modules/node-sass/node_modules/pangyp/lib/configure.js:99:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:194:7)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:818:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
gyp ERR! System Linux 4.2.5-1-ARCH
gyp ERR! command "/usr/bin/node" "/srv/http/website/frontend/node_modules/node-sass/node_modules/pangyp/bin/node-gyp" "rebuild"
gyp ERR! cwd /srv/http/website/frontend/node_modules/node-sass
gyp ERR! node -v v5.0.0
gyp ERR! pangyp -v v2.3.3
gyp ERR! not ok 
Build failed
node-sass@2.1.1 /srv/http/website/frontend/node_modules/node-sass
```

```bash
[nda@stark frontend]$ python --version
Python 2.7.10
[nda@stark frontend]$ npm rebuild node-sass

> node-sass@2.1.1 install /srv/http/website/frontend/node_modules/node-sass
> node scripts/install.js


> node-sass@2.1.1 postinstall /srv/http/website/frontend/node_modules/node-sass
> node scripts/build.js

gyp: /home/nda/.node-gyp/5.0.0/common.gypi not found (cwd: /srv/http/website/frontend/node_modules/node-sass) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/srv/http/website/frontend/node_modules/node-sass/node_modules/pangyp/lib/configure.js:346:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.2.5-1-ARCH
gyp ERR! command "/usr/bin/node" "/srv/http/website/frontend/node_modules/node-sass/node_modules/pangyp/bin/node-gyp" "rebuild"
gyp ERR! cwd /srv/http/website/frontend/node_modules/node-sass
gyp ERR! node -v v5.0.0
gyp ERR! pangyp -v v2.3.3
gyp ERR! not ok 
Build failed
node-sass@2.1.1 /srv/http/website/frontend/node_modules/node-sass
[nda@stark frontend]$ 
```

my packages
```json
  "devDependencies": {
    "browser-sync": "^2.9.11",
    "gulp": "^3.9.0",
    "gulp-concat": "^2.6.0",
    "gulp-jshint": "^1.11.2",
    "gulp-minify-css": "^1.2.1",
    "gulp-notify": "^2.2.0",
    "gulp-plumber": "^1.0.1",
    "gulp-sass": "^1.0.3",
    "gulp-sourcemaps": "^1.6.0",
    "gulp-strip-debug": "^1.0.2",
    "gulp-uglify": "^1.4.2",
    "gulp-util": "^3.0.7"
  }
```

**Comment by nicolasdanelon** [comment]
Oh, I try with the latest version of **gulp-sass**.. and with **1.0.3** neither work... and also try [issues/918](https://github.com/sass/node-sass/issues/918) and [issues/538](https://github.com/yeoman/generator-webapp/issues/538) and [issues/174](https://github.com/dlmanning/gulp-sass/issues/174) nothing work

**Comment by saper** [comment]
Your packages are ancient. node-sass@2.1.1 is very old and does not support your node.

Just try `npm install node-sass` and see if it installs properly.

**Comment by nicolasdanelon** [comment]
yup, solved! thanks!
