### ISSUE TITLE
Getting Gyp error when building for Windows/Cygwin

### ISSUE THREAD

**Issue by jrgleason** [sass/node-sass#1273]
I am trying to build node-sass using the directions found in the readme. However, when I run...

    node scripts/build -f

I get the following error

    gyp info spawn args   '-Goutput_dir=.' ]
    Traceback (most recent call last):
      File "C:\Users\user\dev\code\node-sass\node_modules\node-gyp\gyp\gyp_main.py", line 13, in <module>
        import gyp
    ImportError: No module named gyp
    gyp ERR! configure error
    gyp ERR! stack Error: `gyp` failed with exit code: 1
    gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\user\dev\code\node-sass\node_modules\node-gyp\lib\configure.js:355:16)
    gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
    gyp ERR! System Windows_NT 6.1.7601
    gyp ERR! command "C:\\Users\\user\\AppData\\Roaming\\nvm\\v0.12.4\\node.exe" "C:\\Users\\user\\dev\\code\\node-sass\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
    gyp ERR! cwd C:\Users\user\dev\code\node-sass
    gyp ERR! node -v v0.12.4

**Comment by saper** [comment]
Which version of Python do you have installed? One caveat: Python 2.x and not Python 3.x is needed.

Do you have the following file installed?

    C:\Users\user\dev\code\node-sass\node_modules\node-gyp\gyp\pylib\gyp\__init__.py

**Comment by xzyfer** [comment]
Closing due to inactivity.

**Comment by Sawtaytoes** [comment]
Where in the documentation does it say to have Python installed as a dependency? It isn't installed within a regular `npm i` right?

**Comment by saper** [comment]
Python and a good C++ compiler are needed when building from source. For most cases you should be able to have a binary module downloaded by `npm install node-sass`. If the download fails (or when you prefer building from source) you need python 2 as well.
