### ISSUE TITLE
Unable to install version 3.3.2 - "cannot download"

### ISSUE THREAD

**Issue by pirelenito** [sass/node-sass#1274]
I have an old project that stopped working because of this. The error on `npm install` is:

```
Cannot download "https://github.com/sass/node-sass/releases/download/v3.3.2/darwin-x64-47_binding.node": HTTP error 404 Not Found
```

Here is a complete log on trying to install it on an empty directory:

```
$ npm install node-sass@3.3.2
npm WARN deprecated pangyp@2.3.3: use node-gyp@3+ instead
npm WARN peerDependencies The peer dependency sshpk@^1.4.6 included from http-signature will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
\
> node-sass@3.3.2 install /private/tmp/testing/node_modules/node-sass
> node scripts/install.js

Cannot download "https://github.com/sass/node-sass/releases/download/v3.3.2/darwin-x64-47_binding.node": HTTP error 404 Not Found

> node-sass@3.3.2 postinstall /private/tmp/testing/node_modules/node-sass
> node scripts/build.js

Building: /usr/local/Cellar/node/5.0.0/bin/node /private/tmp/testing/node_modules/node-sass/node_modules/pangyp/bin/node-gyp.js rebuild --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp: /Users/paulo.ragonha/.node-gyp/5.0.0/common.gypi not found (cwd: /private/tmp/testing/node_modules/node-sass) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/private/tmp/testing/node_modules/node-sass/node_modules/pangyp/lib/configure.js:346:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/usr/local/Cellar/node/5.0.0/bin/node" "/private/tmp/testing/node_modules/node-sass/node_modules/pangyp/bin/node-gyp.js" "rebuild" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /private/tmp/testing/node_modules/node-sass
gyp ERR! node -v v5.0.0
gyp ERR! pangyp -v v2.3.3
gyp ERR! not ok
Build failed
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/Cellar/node/5.0.0/bin/node" "/usr/local/bin/npm" "install" "node-sass@3.3.2"
npm ERR! node v5.0.0
npm ERR! npm  v2.14.10
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.3.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.3.2 postinstall script 'node scripts/build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/tmp/testing/npm-debug.log
```

I'll try updating it to a newer version. But shouldn't we keep supporting older versions?

Thanks :)

**Comment by xzyfer** [comment]
v3.3.2 was release long before node 5 which is why it is unsupported. It's
simply not possible for support all versions if node for all releases. We
support up to the latest node version available at the time of the release,
which was node 4 for v3.3.2.
