### ISSUE TITLE
error on postinstall: `node scripts/build.js` python command failed

### ISSUE THREAD

**Issue by ccsandrew** [sass/node-sass#1286]
Hi 

I'm simply trying to install the latest version of node-sass.  Here is the log output:

```
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\r\\Documents\\x\\node_modules\\node-sass\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.2.0
gyp info using node@4.2.1 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at F (C:\Users\r\Documents\x\node_modules\node-sass\node_modules\node-gyp\node_modules\which\which.js:78:19)
gyp verb `which` failed     at E (C:\Users\r\Documents\x\node_modules\node-sass\node_modules\node-gyp\node_modules\which\which.js:82:29)
gyp verb `which` failed     at C:\Users\r\Documents\x\node_modules\node-sass\node_modules\node-gyp\node_modules\which\which.js:93:16
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:82:15)
gyp verb `which` failed  python2 [Error: not found: python2]
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Python33\python.EXE
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Python33\python.EXE -c import platform; print(platform.python_version());
gyp ERR! stack Traceback (most recent call last):
gyp ERR! stack   File "<string>", line 1, in <module>
gyp ERR! stack TypeError: source code string cannot contain null bytes
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:203:12)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:818:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:319:11)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at Socket.emit (events.js:169:7)
gyp ERR! stack     at Pipe._onclose (net.js:469:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\r\\Documents\\x\\node_modules\\node-sass\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild
" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\r\Documents\x\node_modules\node-sass
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.2.0
gyp ERR! not ok
Build failed
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--proxy=null" "node-sass" "--save-dev"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.4.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.4.2 postinstall script 'node scripts/build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\r\Documents\x\npm-debug.log
```

Thanks for your help.

**Comment by xzyfer** [comment]
Node Sass is a native extension. Native extensions are compiled via node-gyp which requires python2. Node Sass should attempt to download the precompiled binary for you system if can. It appears it was unable to in this case but that part of the log hasn't been provided.

Please follow our [troubleshooting guide](https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md) and provide **all** the output as a github gist. Do not post the output in this issue.

**Comment by ccsandrew** [comment]
Rolled back to python 2.7 and that seemed to fix the issue.

**Comment by saper** [comment]
Gyp utility used be chromium and other projects (including node) does not work with Python 3.

**Comment by saper** [comment]
@wisetc without full output we cannot help you. You need to check why the download failed.
