### ISSUE TITLE
Npm install issue

### ISSUE THREAD

**Issue by Zenuka** [sass/node-sass#1294]
I'm not sure if this is a node-sass issue or a libsass. I'm trying to install node-sass through the following command:
    npm install node-sass --msvs_version=2013

But it keeps failing with the following messages:
> ..\..\src\libsass\src\functions.cpp(215): error C2146: syntax error : missing ';' before identifier 'GetSeed' [C:\Build\w\8\s\SignIn.Web\node_modules\node-sass\build\src\libsass.vcxproj]
> ..\..\src\libsass\src\functions.cpp(215): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [C:\Build\w\8\s\SignIn.Web\node_modules\node-sass\build\src\libsass.vcxproj]
> ..\..\src\libsass\src\functions.cpp(216): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [C:\Build\w\8\s\SignIn.Web\node_modules\node-sass\build\src\libsass.vcxproj]
> ..\..\src\libsass\src\functions.cpp(1176): error C2065: 'uint_fast32_t' : undeclared identifier [C:\Build\w\8\s\SignIn.Web\node_modules\node-sass\build\src\libsass.vcxproj]
> ..\..\src\libsass\src\functions.cpp(1176): error C2146: syntax error : missing ';' before identifier 'distributed' [C:\Build\w\8\s\SignIn.Web\node_modules\node-sass\build\src\libsass.vcxproj]
> ..\..\src\libsass\src\functions.cpp(1176): error C2065: 'distributed' : undeclared identifier [C:\Build\w\8\s\SignIn.Web\node_modules\node-sass\build\src\libsass.vcxproj]
> ..\..\src\libsass\src\functions.cpp(1176): error C2061: syntax error : identifier 'uint_fast32_t' [C:\Build\w\8\s\SignIn.Web\node_modules\node-sass\build\src\libsass.vcxproj]
> ..\..\src\libsass\src\functions.cpp(1177): error C2065: 'distributed' : undeclared identifier [C:\Build\w\8\s\SignIn.Web\node_modules\node-sass\build\src\libsass.vcxproj]
> ..\..\src\libsass\src\functions.cpp(1917): error C2065: 'uint_fast32_t' : undeclared identifier [C:\Build\w\8\s\SignIn.Web\node_modules\node-sass\build\src\libsass.vcxproj]
> ..\..\src\libsass\src\functions.cpp(1917): error C2146: syntax error : missing ';' before identifier 'distributed' [C:\Build\w\8\s\SignIn.Web\node_modules\node-sass\build\src\libsass.vcxproj]
> ..\..\src\libsass\src\functions.cpp(1917): error C2065: 'distributed' : undeclared identifier [C:\Build\w\8\s\SignIn.Web\node_modules\node-sass\build\src\libsass.vcxproj]
> ..\..\src\libsass\src\functions.cpp(1917): error C2061: syntax error : identifier 'uint_fast32_t' [C:\Build\w\8\s\SignIn.Web\node_modules\node-sass\build\src\libsass.vcxproj]
> ..\..\src\libsass\src\functions.cpp(1918): error C2065: 'distributed' : undeclared identifier [C:\Build\w\8\s\SignIn.Web\node_modules\node-sass\build\src\libsass.vcxproj]

Any suggestions?

Some extra info:
> gyp ERR! build error
> gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
> gyp ERR! stack     at ChildProcess.onExit (C:\Build\w\8\s\SignIn.Web\node_modules\node-sass\node_modules\node-gyp\lib\build.js:276:23)
> gyp ERR! stack     at emitTwo (events.js:87:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
> gyp ERR! System Windows_NT 6.3.9600
> gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Build\\w\\8\\s\\SignIn.Web\\node_modules\\node-sass\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
> gyp ERR! cwd C:\Build\w\8\s\SignIn.Web\node_modules\node-sass
> gyp ERR! node -v v4.2.3
> gyp ERR! node-gyp -v v3.2.1
> gyp ERR! not ok
> Build failed
> npm ERR! Windows_NT 6.3.9600
> npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Zenuka\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-sass" "--msvs_version=2013"
> npm ERR! node v4.2.3
> npm ERR! npm  v2.14.3
> npm ERR! code ELIFECYCLE
> 
> npm ERR! node-sass@3.4.2 postinstall: `node scripts/build.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the node-sass@3.4.2 postinstall script 'node scripts/build.js'.
> npm ERR! This is most likely a problem with the node-sass package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node scripts/build.js
> npm ERR! You can get their info via:
> npm ERR!     npm owner ls node-sass
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     C:\Build\w\8\s\SignIn.Web\npm-debug.log

**Comment by Zenuka** [comment]
Nevermind, I read that they've dropped VS2013 support (unintentionally) and I had issues switching to VS2015 because C++ compiler is not default installed. Run the installation again for VS2015 and under programming languages, check c++. Then you'll be able to compile with VS2015.
