### ISSUE TITLE
404 not found on npm install sass (darwin-x64-47_binding.node)

### ISSUE THREAD

**Issue by debugwand** [sass/node-sass#1299]
I get the following error when trying to run `npm install sass`

`Cannot download "https://github.com/sass/node-sass/releases/download/v3.2.0/darwin-x64-47_binding.node": HTTP error 404 Not Found`

npm -v 3.3.12
node -v v5.1.1
osx 10.11.1

**Comment by saper** [comment]
You need to update your node-sass to use node 5.

**Comment by davidann** [comment]
I have this issue and I'm using node 5.10.1:

```bash
$ npm install node-sass@3.2.0
npm WARN deprecated pangyp@2.3.3: use node-gyp@3+ instead
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN prefer global pangyp@2.3.3 should be installed with -g

> node-sass@3.2.0 install /Users/davidann/workspace/drake/node_modules/node-sass
> node scripts/install.js

Cannot download "https://github.com/sass/node-sass/releases/download/v3.2.0/darwin-x64-47_binding.node": HTTP error 404 Not Found

> node-sass@3.2.0 postinstall /Users/davidann/workspace/drake/node_modules/node-sass
> node scripts/build.js

Building: /Users/davidann/.nvm/versions/node/v5.10.1/bin/node node_modules/pangyp/bin/node-gyp rebuild --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
module.js:341
    throw err;
    ^

Error: Cannot find module '/Users/davidann/workspace/drake/node_modules/node-sass/node_modules/pangyp/bin/node-gyp'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:146:18)
    at node.js:404:3
Build failed
npm WARN webpack@1.10.1 requires a peer of node-libs-browser@>= 0.4.0 <=0.6.0 but none was installed.
npm ERR! Darwin 14.4.0
npm ERR! argv "/Users/davidann/.nvm/versions/node/v5.10.1/bin/node" "/Users/davidann/.nvm/versions/node/v5.10.1/bin/npm" "install" "node-sass@3.2.0"
npm ERR! node v5.10.1
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE
```

Or am I missing something?

**Comment by saper** [comment]
Why dion't you just try `npm install node-sass`? The version you are trying to use did not support node 5 yet.

**Comment by xzyfer** [comment]
Node sass 3.2.0 is ancient and no longer supported. Update to the latest
version.
