### ISSUE TITLE
How to skip rebuild step? (compiling sass failed, OS Windows)

### ISSUE THREAD

**Issue by Sogl** [sass/node-sass#1302]
Hi!

I use framework that uses `node-sass` as dependency. In build step I see this error:
```
C:\OpenServer\domains\aviashelf>php bootstrap.php build
[ 1/3] building trl...... OK (103ms)
[ 2/3] building events... OK (349ms)
[ 3/3] building assets...
calculating dependencies...
100% [#####################] Maintenance printcss
compiling assets...
 54% [###########----------] kwf/views/user/master.scss                        exception 'Kwf_Exception' with message 'compiling sass failed: C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\node_modules\node-sass\lib\extensions.js:158
    throw new Error([
    ^

Error: The `libsass` binding was not found in C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\node_modules\node-sass\vendor\win32-x64-46\binding.node
This usually happens because your node version has changed.
Run `npm rebuild node-sass` to build the binding for your current node version.
    at Object.sass.getBinaryPath (C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\node_modules\node-sass\lib\extensions.js:158:11)
    at Object.<anonymous> (C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\node_modules\node-sass\lib\index.js:16:36)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\node_modules\node-sass\lib\render.js:9:12)
    at Module._compile (module.js:435:26)' in C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Assets\Dependency\File\Scss.php:96
Stack trace:
#0 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Util\Build\Types\Assets.php(168): Kwf_Assets_Dependency_File_Scss->warmupCaches() #1 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Util\Build\Types\Abstract.php(15): Kwf_Util_Build_Types_Assets->_build(Array)
#2 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Util\Build.php(97): Kwf_Util_Build_Types_Abstract->build(Array)
#3 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Action\Cli\BuildController.php(35): Kwf_Util_Build->build(Array)
#4 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Action.php(33): Kwf_Controller_Action_Cli_BuildController->indexAction()
#5 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Controller\Dispatcher\Standard.php(308): Kwf_Controller_Action->dispatch('indexAction')
#6 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Kwf_Controller_Request_Cli), Object(Kwf_Controller_Response_Http))
#7 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Front.php(140): Zend_Controller_Front->dispatch(Object(Kwf_Controller_Request_Cli), Object(Kwf_Controller_Response_Http))
#8 C:\OpenServer\domains\aviashelf\bootstrap.php(22): Kwf_Controller_Front->dispatch()
#9 {main} [ERROR]
C:\OpenServer\domains\aviashelf>
```

I found a workaround:
```
C:\OpenServer\domains\aviashelf>cd C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework

C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework>npm rebuild node-sass

> node-sass@3.4.2 install C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\node_modules\node-sass
> node scripts/install.js

Binary downloaded and installed at C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\node_modules\node-sass\vendor\win32-x64-46\binding.node

> node-sass@3.4.2 postinstall C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\node_modules\node-sass
> node scripts/build.js

` C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\node_modules\node-sass\vendor\win32-x64-46\binding.node ` exists.
 testing binary.
Binary is fine; exiting.
node-sass@3.4.2 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\node_modules\node-sass

C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework>
```

After this rebuild node-sass works fine.
How to skip this step?

Env:
This error on both Windows 7 x64 and Windows 8 x64
node 4.2.2
npm 3.3.12
node-sass       3.4.2   (Wrapper)       [JavaScript]
libsass         3.3.2   (Sass Compiler) [C/C++]

**Comment by xzyfer** [comment]
This cannot be skipped. Every node native extension needs to be built to
work. The building happens during npm install. The error you're seeing
means that you npm installed node-sass under a different environment or
node version than the one you're trying to run node-sass on.

This usually happens if you've recently changed node versions, npm install
on a virtual machine or check your node_modules into git/svn.

**Comment by Sogl** [comment]
But why `node-sass rebuild` not included into standard npm call? If this step cannot be skipped.

What I do on every machine:
```
1. git clone repo
2. composer install
3. php bootstrap.php build
4. php bootstrap.php clear-cache
```
I need to include `npm install` command?

**Comment by xzyfer** [comment]
Any time use node packages with npm you need npm install. I don't
understand how your code can work without it.

This is not a node-sass issue it's just the way npm works.

**Comment by Sogl** [comment]
>I don't understand how your code can work without it.

With this tool:
https://github.com/koala-framework/composer-extra-assets

Some info:
http://www.nikosams.net/blog/17_composer_npm_bower_assets_installation_using_composer-extra-assets

**Comment by xzyfer** [comment]
Looks like tool isn't doing the right thing with npm. This is a bug with them.
