### ISSUE TITLE
node-sass for node v5.2.0 (failed)

### ISSUE THREAD

**Issue by askucher** [sass/node-sass#1303]
Steps to reproduce

1.
```
root# node -v
v5.2.0
```

2.

```
npm rebuild node-sass   
```

Result
```
make: *** [Release/obj.target/binding/src/binding.o] Error 1
make: Leaving directory `//node_modules/grunt-sass/node_modules/node-sass/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (//node_modules/grunt-sass/node_modules/node-sass/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:88:13)
gyp ERR! stack     at ChildProcess.emit (events.js:173:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:201:12)
gyp ERR! System Linux 2.6.32-41-pve
gyp ERR! command "/usr/local/bin/node" "/var/www/Dashboard/node_modules/grunt-sass/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /var/www/Dashboard/node_modules/grunt-sass/node_modules/node-sass
gyp ERR! node -v v5.2.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
Build failed

npm ERR! Linux 2.6.32-41-pve
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "rebuild" "node-sass"
npm ERR! node v5.2.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! node-sass@3.4.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.4.0 postinstall script 'node scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /npm-debug.log
```

**Comment by xzyfer** [comment]
@askucher unfortunately you have cut off the important output. Please follow our [troubleshooting guide](https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md) making sure to copy *all* output into a github gist. Do *not* post the output into this issue.

**Comment by fustic** [comment]
On empty dir, using these env:
```javascript
npm -v
3.5.2
➜  node -v
v5.2.0
➜  node -p process.versions
node -p process.platform
node -p process.arch
{ http_parser: '2.6.0',
  node: '5.2.0',
  v8: '4.6.85.31',
  uv: '1.7.5',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '56.1',
  modules: '47',
  openssl: '1.0.2e' }
➜  node -p process.platform
darwin
➜  node -p process.arch
x64
```
it worked out for me

**Comment by fengyuanchen** [comment]
@askucher If you are installing **grunt-sass**, you can install the **node-sass** first:

```shell
cd project-directory
npm uninstall node-sass
npm install node-sass
npm install grunt-sass
```

**Comment by xzyfer** [comment]
Closed due to inactivity.
