### ISSUE TITLE
Fail to install node-sass on Windows 10

### ISSUE THREAD

**Issue by Mash19** [sass/node-sass#1313]
I have not been able to reinstall node-sass since Windows 10 upgrade. Fails whether direct install or as a dependency.
Steps to reproduce 
1. Npm install node-sass

npm ERR! node v5.1.1
npm ERR! npm  v3.3.7
npm ERR! code ELIFECYCLE
npm ERR! node-sass@3.4.2 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.4.2 install script 'node scripts/install.js'.

Diagnostic files at https://gist.github.com/Mash19/22411af6d43dd2f9f3e4

**Comment by xzyfer** [comment]
Suspect lines

```
npm sill install node-sass@3.4.2 C:\temp1\node_modules\.staging\node-sass-73242a0ba899f54cc668c05465315f47
npm info lifecycle node-sass@3.4.2~install: node-sass@3.4.2
'node' is not recognized as an internal or external command,
operable program or batch file.
```
Followed by
```
npm verb lifecycle node-sass@3.4.2~install: unsafe-perm in lifecycle true
npm verb lifecycle node-sass@3.4.2~install: PATH: C:\Users\Michael\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\temp1\node_modules\sass-graph\node_modules\.bin;C:\temp1\node_modules\.bin;C:\Users\Michael\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\temp1\node_modules\yargs\node_modules\.bin;C:\temp1\node_modules\.bin;C:\Users\Michael\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\temp1\node_modules\y18n\node_modules\.bin;C:\temp1\node_modules\.bin;C:\Users\Michael\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\temp1\node_modules\node-gyp\node_modules\.bin;C:\temp1\node_modules\.bin;C:\Users\Michael\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\temp1\node_modules\request\node_modules\.bin;C:\temp1\node_modules\.bin;C:\Users\Michael\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\temp1\node_modules\har-validator\node_modules\.bin;C:\temp1\node_modules\.bin;C:\Users\Michael\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\temp1\node_modules\is-my-json-valid\node_modules\.bin;C:\temp1\node_modules\.bin;C:\Users\Michael\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\temp1\node_modules\xtend\node_modules\.bin;C:\temp1\node_modules\.bin;C:\Users\Michael\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\temp1\node_modules\tar\node_modules\.bin;C:\temp1\node_modules\.bin;C:\Users\Michael\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\temp1\node_modules\fstream\node_modules\.bin;C:\temp1\node_modules\.bin;C:\Users\Michael\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\temp1\node_modules\rimraf\node_modules\.bin;C:\temp1\node_modules\.bin;C:\Users\Michael\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\temp1\node_modules\glob\node_modules\.bin;C:\temp1\node_modules\.bin
npm verb lifecycle node-sass@3.4.2~install: CWD: C:\temp1\node_modules\node-sass
npm sill lifecycle node-sass@3.4.2~install: Args: [ '/d /s /c', 'node scripts/install.js' ]
npm sill lifecycle node-sass@3.4.2~install: Returned: code: 1  signal: null
npm info lifecycle node-sass@3.4.2~install: Failed to exec install script
npm verb unlock done using C:\Users\Michael\AppData\Roaming\npm-cache\_locks\staging-03104c7349a1da4e.lock for C:\temp1\node_modules\.staging
npm sill rollbackFailedOptional Starting
npm sill rollbackFailedOptional Finishing
npm sill runTopLevelLifecycles Starting
npm sill runTopLevelLifecycles Finishing
npm sill install printInstalled
npm WARN ENOENT ENOENT: no such file or directory, open 'C:\temp1\package.json'
npm WARN EPACKAGEJSON temp1 No description
npm WARN EPACKAGEJSON temp1 No repository field.
npm WARN EPACKAGEJSON temp1 No README data
npm WARN EPACKAGEJSON temp1 No license field.
npm verb stack Error: node-sass@3.4.2 install: `node scripts/install.js`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (C:\Users\Michael\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:222:16)
npm verb stack     at emitTwo (events.js:87:13)
npm verb stack     at EventEmitter.emit (events.js:172:7)
npm verb stack     at ChildProcess.<anonymous> (C:\Users\Michael\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:24:14)
npm verb stack     at emitTwo (events.js:87:13)
npm verb stack     at ChildProcess.emit (events.js:172:7)
npm verb stack     at maybeClose (internal/child_process.js:818:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
npm verb pkgid node-sass@3.4.2
npm verb cwd C:\temp1
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Michael\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-ddd" "node-sass"
npm ERR! node v5.1.1
npm ERR! npm  v3.3.7
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.4.2 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.4.2 install script 'node scripts/install.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]
```

**Comment by saper** [comment]
Does `cmd /d /s /c node` launch node?

**Comment by xzyfer** [comment]
Closing due to inactivity.
