### ISSUE TITLE
'node' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by notionslate** [sass/node-sass#1361]
I encountered a problem trying to npm install --save-dev node-sass. I've reviewed similar issues without success. (Troubleshooting npm.err and npm.log files attached.)

Note: I do not have a global node installed. I am working a project that installs node, npm, and all packages local to the repo.  I've had to create several .cmd files in my project root that point to specific node packages (like bower and grunt...) to run them.  I suspect this error may be related to this environment. Here is the original console error:
```
$ npm install --save-dev node-sass
npm WARN install Couldn't install optional dependency: Unsupported

> node-sass@3.4.2 install c:\Users\troy.day\Development\spyglass-webapp\smc-ui-webapp\node_modules\node-sass
> node scripts/install.js

'node' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\\Users\\troy.day\\Development\\spyglass-webapp\\smc-ui-webapp\\node\\node.exe" "c:\\Users\\troy.day\\Development\\spyglass-webapp\\smc-ui-webapp\\node\\node_modules\\npm\\bin\\npm-cli.js" "install"
 "--save-dev" "node-sass"
npm ERR! node v5.3.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.4.2 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.4.2 install script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\Users\troy.day\Development\spyglass-webapp\smc-ui-webapp\npm-debug.log
```

...and here is the npm-debug.log
```
3389 silly install node-sass@3.4.2 c:\Users\troy.day\Development\spyglass-webapp\smc-ui-webapp\node_modules\.staging\node-sass-1c3494d23c1ef5b7da57c222c7f85550
3390 info lifecycle node-sass@3.4.2~install: node-sass@3.4.2
3391 verbose lifecycle node-sass@3.4.2~install: unsafe-perm in lifecycle true
3392 verbose lifecycle node-sass@3.4.2~install: PATH: c:\Users\troy.day\Development\spyglass-webapp\smc-ui-webapp\node\node_modules\npm\bin\node-gyp-bin;c:\Users\troy.day\Development\spyglass-webapp\smc-ui-webapp\node_modules\node-sass\node_modules\.bin;c:\Users\troy.day\Development\spyglass-webapp\smc-ui-webapp\node_modules\.bin;c:\Users\troy.day\bin;.;C:\Program Files (x86)\Git\local\bin;C:\Program Files (x86)\Git\mingw\bin;C:\Program Files (x86)\Git\bin;C:\Program Files (x86)\Git\bin;c:\Ruby200\bin;c:\RubyDevKit472\bin;c:\ProgramData\Oracle\Java\javapath;c:\Program Files\RSA SecurID Token Common;c:\Windows\system32;c:\Windows;c:\Windows\System32\Wbem;c:\Windows\System32\WindowsPowerShell\v1.0\;c:\HashiCorp\Vagrant\bin;c:\apache-tomcat-8.0.24\bin;c:\Python27;c:\Python27\Scripts;c:\Program Files\Apache Software Foundation\apache-maven-3.3.1\bin;c:\Program Files\Java\jdk1.8.0_31\bin;c:\ffmpeg\bin;C:\Program Files (x86)\Git\bin;c:\play-2.2.6;c:\browserdrivers
3393 verbose lifecycle node-sass@3.4.2~install: CWD: c:\Users\troy.day\Development\spyglass-webapp\smc-ui-webapp\node_modules\node-sass
3394 silly lifecycle node-sass@3.4.2~install: Args: [ '/d /s /c', 'node scripts/install.js' ]
3395 silly lifecycle node-sass@3.4.2~install: Returned: code: 1  signal: null
3396 info lifecycle node-sass@3.4.2~install: Failed to exec install script
3397 verbose unlock done using C:\Users\troy.day\AppData\Roaming\npm-cache\_locks\staging-c2e00b71d541401f.lock for c:\Users\troy.day\Development\spyglass-webapp\smc-ui-webapp\node_modules\.staging
3398 silly rollbackFailedOptional Starting
3399 silly rollbackFailedOptional Finishing
3400 silly runTopLevelLifecycles Starting
3401 silly runTopLevelLifecycles Finishing
3402 silly install printInstalled
3403 verbose stack Error: node-sass@3.4.2 install: `node scripts/install.js`
3403 verbose stack Exit status 1
3403 verbose stack     at EventEmitter.<anonymous> (c:\Users\troy.day\Development\spyglass-webapp\smc-ui-webapp\node\node_modules\npm\lib\utils\lifecycle.js:232:16)
3403 verbose stack     at emitTwo (events.js:87:13)
3403 verbose stack     at EventEmitter.emit (events.js:172:7)
3403 verbose stack     at ChildProcess.<anonymous> (c:\Users\troy.day\Development\spyglass-webapp\smc-ui-webapp\node\node_modules\npm\lib\utils\spawn.js:24:14)
3403 verbose stack     at emitTwo (events.js:87:13)
3403 verbose stack     at ChildProcess.emit (events.js:172:7)
3403 verbose stack     at maybeClose (internal/child_process.js:818:16)
3403 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
3404 verbose pkgid node-sass@3.4.2
3405 verbose cwd c:\Users\troy.day\Development\spyglass-webapp\smc-ui-webapp
3406 error Windows_NT 6.1.7601
3407 error argv "c:\\Users\\troy.day\\Development\\spyglass-webapp\\smc-ui-webapp\\node\\node.exe" "c:\\Users\\troy.day\\Development\\spyglass-webapp\\smc-ui-webapp\\node\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save-dev" "node-sass"
3408 error node v5.3.0
3409 error npm  v3.3.12
3410 error code ELIFECYCLE
3411 error node-sass@3.4.2 install: `node scripts/install.js`
3411 error Exit status 1
3412 error Failed at the node-sass@3.4.2 install script 'node scripts/install.js'.
3412 error Make sure you have the latest version of node.js and npm installed.
3412 error If you do, this is most likely a problem with the node-sass package,
3412 error not with npm itself.
3412 error Tell the author that this fails on your system:
3412 error     node scripts/install.js
3412 error You can get their info via:
3412 error     npm owner ls node-sass
3412 error There is likely additional logging output above.
3413 verbose exit [ 1, true ]
```
[npmerr.txt](https://github.com/sass/node-sass/files/110216/npmerr.txt)
[npmlog.txt](https://github.com/sass/node-sass/files/110215/npmlog.txt)

**Comment by notionslate** [comment]
I tried several things, but the work-around that helped was to add my local node path to my PATH environment variable so the script could find my local node.  If another developer has node installed globally, then they may not run into this issue.  I'd rather not make other devs jump through the environment PATH variable hoop - can anyone think of another way to address this issue? Kind Thanks!

**Comment by xzyfer** [comment]
I don't expect Node install scripts can work if node is not in your PATH. Maybe @am11 knows more.
Doesn't feel like a node-sass specific issue.

**Comment by am11** [comment]
That's correct; npm requires node to be present in PATH or in the current working directory to execute the post-build install task.

**Comment by xzyfer** [comment]
Closing due to inactivity.

**Comment by lalitsinha2008** [comment]
System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: The source completed without providing data to receive.
   at System.Threading.Tasks.Dataflow.Internal.Common.InitializeStackTrace(Exception exception)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.VisualStudio.ProjectSystem.Utilities.Designers.ProjectDataSources.<>c__DisplayClass14_0.<<SyncLinkTo>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.InvalidOperationException: The source completed without providing data to receive.
   at System.Threading.Tasks.Dataflow.Internal.Common.InitializeStackTrace(Exception exception)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.VisualStudio.ProjectSystem.Utilities.Designers.ProjectDataSources.<>c__DisplayClass14_0.<<SyncLinkTo>b__0>d.MoveNext()<---

---> (Inner Exception #1) System.InvalidOperationException: The source completed without providing data to receive.
   at System.Threading.Tasks.Dataflow.Internal.Common.InitializeStackTrace(Exception exception)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.VisualStudio.ProjectSystem.Utilities.Designers.ProjectDataSources.<>c__DisplayClass14_0.<<SyncLinkTo>b__0>d.MoveNext()<---

---> (Inner Exception #2) System.InvalidOperationException: The source completed without providing data to receive.
   at System.Threading.Tasks.Dataflow.Internal.Common.InitializeStackTrace(Exception exception)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.VisualStudio.ProjectSystem.Utilities.Designers.ProjectDataSources.<>c__DisplayClass14_0.<<SyncLinkTo>b__0>d.MoveNext()<---

---> (Inner Exception #3) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---
