### ISSUE TITLE
Watch issue "/*"

### ISSUE THREAD

**Issue by MoAnsir** [sass/node-sass#1372]
If i use node-sass in the command line i can watch individual files but not a whole folder. 
This works:
node-sass --watch src/css/mobile.scss --output dist/css

This dose not:
node-sass --watch src/css/* --output dist/css

This is the output:
fs.js:839
  return binding.lstat(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, lstat 'C:\wamp\www\CMD\cmdForWeb\L4\src\css\*'
    at Error (native)
    at Object.fs.lstatSync (fs.js:839:18)
    at Object.module.exports.parseDir (C:\Users\lenny\AppData\Roaming\npm\node_modules\node-sass\node_modules\sass-graph\sass-graph.js:145:10)
    at watch (C:\Users\lenny\AppData\Roaming\npm\node_modules\node-sass\bin\node-sass:233:21)
    at run (C:\Users\lenny\AppData\Roaming\npm\node_modules\node-sass\bin\node-sass:303:5)
    at Object.<anonymous> (C:\Users\lenny\AppData\Roaming\npm\node_modules\node-sass\bin\node-sass:383:3)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)

**Comment by xzyfer** [comment]
```
node-sass --watch src/css/ --ouput dist/css
```
