### ISSUE TITLE
Error while building on Ubuntu 12.04 LTS (32 bit)

### ISSUE THREAD

**Issue by ruandre** [sass/node-sass#1378]
While building [phantomas](https://github.com/macbre/phantomas/) I get the following error related to node-sass:

```
../src/binding.cpp:335:42:   instantiated from here
../../nan/nan.h:1865:33: error: 'GetFunction' was not declared in this scope
make: *** [Release/obj.target/binding/src/binding.o] Error 1
make: Leaving directory `/usr/lib/node_modules/phantomas/node_modules/node-sass/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/phantomas/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.2.0-23-generic-pae
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/phantomas/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /usr/lib/node_modules/phantomas/node_modules/node-sass
gyp ERR! node -v v5.6.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok
Build failed
/usr/lib
`-- (empty)

npm ERR! Linux 3.2.0-23-generic-pae
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "phantomas"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.3.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.3.3 postinstall script 'node scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /phantomas/npm-debug.log
npm ERR! code 1
```

**Comment by xzyfer** [comment]
You need at least node-sass@3.4.1 for node 5 support. You're running
node-sass@3.3.0. Please update.
