### ISSUE TITLE
Error: `libsass` bindings not found. Try reinstalling `node-sass`?

### ISSUE THREAD

**Issue by braun2002** [sass/node-sass#1398]
Hi people! i have some problem with sass and node

vagrant@homestead:/var/www/carsrentalmiami.app/www$ gulp html:build
/var/www/carsrentalmiami.app/www/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:22
    throw new Error('`libsass` bindings not found. Try reinstalling `node-sass`?');
    ^

Error: `libsass` bindings not found. Try reinstalling `node-sass`?
    at getBinding (/var/www/carsrentalmiami.app/www/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:22:11)
    at Object.<anonymous> (/var/www/carsrentalmiami.app/www/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:188:23)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/var/www/carsrentalmiami.app/www/node_modules/gulp-sass/index.js:3:17)
    at Module._compile (module.js:413:34)

npm -v
3.3.12

{
  "name": "devil",
  "version": "1.0.1",
  "description": "css apps",
  "dependencies": {
    "browser-sync": "^2.2.3",
    "gulp": "^3.8.11",
    "gulp-autoprefixer": "^2.1.0",
    "gulp-imagemin": "^2.2.1",
    "gulp-minify-css": "^1.0.0",
    "gulp-rigger": "^0.5.8",
    "gulp-sass": "^1.3.3",
    "gulp-sourcemaps": "^1.5.0",
    "gulp-uglify": "^1.1.0",
    "gulp-watch": "^4.1.1",
    "imagemin-pngquant": "^4.0.0",
    "rimraf": "^2.3.1"
  }
}

'use strict';

var gulp = require('gulp'),
    watch = require('gulp-watch'),
    prefixer = require('gulp-autoprefixer'),
    uglify = require('gulp-uglify'),
    sass = require('gulp-sass'),
    sourcemaps = require('gulp-sourcemaps'),
    rigger = require('gulp-rigger'),
    cssmin = require('gulp-minify-css'),
    imagemin = require('gulp-imagemin'),
    pngquant = require('imagemin-pngquant'),
    rimraf = require('rimraf'),
    browserSync = require("browser-sync"),
    reload = browserSync.reload;

What i do wrong?

**Comment by jingzhou123** [comment]
try `npm rebuild node-sass`

**Comment by xzyfer** [comment]
You're running a very old version of gulp-sass. Please update.

**Comment by braun2002** [comment]
thank you guys! it's work)
