### ISSUE TITLE
Failed at the node-sass@3.4.2 postinstall script 'node scripts/build.js

### ISSUE THREAD

**Issue by rguthikonda** [sass/node-sass#1400]
I am facing this issue very often, please let me know the solution for this

I tried the troubleshooting guidelines also, then also I faced the same issue. 

Log Files from troubleshooting: 
[npm-debug.txt](https://github.com/sass/node-sass/files/146171/npm-debug.txt)
[npm-err.txt](https://github.com/sass/node-sass/files/146170/npm-err.txt)
[npm-log.txt](https://github.com/sass/node-sass/files/146169/npm-log.txt)

```
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\raghuveer.guthikonda\AppData
\Roaming\npm\node_modules\node-sass\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\raghuveer.gut
hikonda\\AppData\\Roaming\\npm\\node_modules\\node-sass\\node_modules\\node-gyp\
\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "-
-libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\raghuveer.guthikonda\AppData\Roaming\npm\node_modules\node
-sass
gyp ERR! node -v v4.3.1
gyp ERR! node-gyp -v v3.3.0
gyp ERR! not ok
Build failed
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "node-sass"
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.4.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.4.2 postinstall script 'node scripts/build.js
'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\npm-debug.log
```

**Comment by rguthikondazc** [comment]
[npm-debug.txt](https://github.com/sass/node-sass/files/146171/npm-debug.txt)
[npm-err.txt](https://github.com/sass/node-sass/files/146170/npm-err.txt)
[npm-log.txt](https://github.com/sass/node-sass/files/146169/npm-log.txt)

**Comment by xzyfer** [comment]
Please upload your logs as [https://gist.github.com](github gist's).

**Comment by rguthikondazc** [comment]
@xzyfer please check now I've reattached files to the same post

**Comment by xzyfer** [comment]
I see that but I cannot download your files on my system. Please post them into github gists so I can read them in my browser,

**Comment by rguthikonda** [comment]
@xzyfer 
https://gist.github.com/rguthikonda/dbb922870ee5ea2a8296

**Comment by xzyfer** [comment]
Looks like a simple networking issue.

```
npm info install node-sass@3.4.2
Cannot download "https://github.com/sass/node-sass/releases/download/v3.4.2/win32-x64-46_binding.node": 

connect ETIMEDOUT 54.231.49.194:443

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g. 

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080
```

This error should have appeared in your console telling you how to resolve the issue.

The error you're seeing is because you couldn't download the file above, and your system tried to compile the extension without Visual Studio installed.

**Comment by rguthikonda** [comment]
@xzyfer thanks for the update

 but I have VS 2013 installed in my system
 and I have access to that url via browser

`Cannot download "https://github.com/sass/node-sass/releases/download/v3.4.2/win32-x64-46_binding.node": `

are there any other scenarios this error will come?

**Comment by xzyfer** [comment]
No, the error is a networking error.

**Comment by xzyfer** [comment]
I may have misread the error message but `msbuild.exe` cannot compile the extension. Maybe you have an incompatible version. Also, if you're on Windows XP there is an issue preventing v3.4.2 compiling.

```
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir C:\Users\raghuveer.guthikonda\.node-gyp\4.3.1
gyp verb found first Solution file build/binding.sln
gyp verb could not find "msbuild.exe" in PATH - finding location in registry 
gyp verb "Release" dir needed to be created? null
gyp verb copying "node.lib" for x64 C:\Users\raghuveer.guthikonda\.node-gyp\4.3.1\Release\node.lib
gyp info spawn C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\temp1\node_modules\node-sass\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\temp1\\node_modules\\node-sass\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\temp1\node_modules\node-sass
gyp ERR! node -v v4.3.1
gyp ERR! node-gyp -v v3.3.0
gyp ERR! not ok 
Build failed
```

**Comment by saper** [comment]
@rguthikonda are you installing node-sass from the visual studio command prompt? Looks like Microsoft developer tools are not on your PATH (this is normal if you run normal cmd.exe). If you can't get the VS command prompt, there should be a vcvarsall.bat file somewhere which can set your environment variables correctly.
