### ISSUE TITLE
Syntax error when dynamically interpolating/invoking mixin by name

### ISSUE THREAD

**Issue by jkymarsh** [sass/node-sass#1404]
On node-sass `3.4.2`, I have the following 2 mixins defined:

```sass
@mixin h-create-css-properties($args...) {
  $property: nth($args, 1);
  $values: remove-nth($args, 1);

  @each $value in $values {
    #{$property}: $value;
  }
}

@mixin h-create-media-queries($mixin-name, $breakpoint, $args...) {
  $breakpoints-map: h-map-deep-get($h-config, breakpoints);

  @if $breakpoint == null {
    // PROBLEMATIC LINE
    @include #{$mixin-name}($args...);
  }
  @else if map-has-key($breakpoints-map, $breakpoint) {
    $mapped-breakpoint: map-get($breakpoints-map, $breakpoint);

    @media screen and (min-width: $mapped-breakpoint) {
      // PROBLEMATIC LINE
      @include #{$mixin-name}($args...);
    }
  }
}
```

The latter mixin would be invoked as such:

```sass
@mixin h-create-responsive-font-size($breakpoint, $font-size) {
  @include h-create-media-queries(
      h-create-css-properties,
      $breakpoint,
      font-size,
      $font-size,
      h-calculate-px-to-rem($font-size));
}
```

The line indicated via code comments throws the following error and stack trace upon compilation:

```
Error: Invalid CSS after "    @include": expected identifier, was "ixin-name}($arg..."
      at Object.module.exports.renderSync (node_modules/node-sass/lib/index.js:424:22)
      at Object.Utilities.compileFromString (node_modules/sassaby/src/utilities.js:9:18)
      at Object.Utilities.compileWithFile (node_modules/sassaby/src/utilities.js:15:17)
      at Object.Utilities.createCss (node_modules/sassaby/src/utilities.js:19:24)
      at compileCss (node_modules/sassaby/src/funcResult.js:30:22)
      at Object.FuncResult (node_modules/sassaby/src/funcResult.js:45:14)
      at Object.Func.calledWithArgs (node_modules/sassaby/src/types/func.js:23:12)
      at Context.<anonymous> (glue/releases/latest/scss/hercules/tests/unit/type/_mixins.spec.js:10:45)
```

It's my understanding that that Sass code should be valid syntax - in fact, it works in other implementations of the interpreter, such as [PyScss](https://github.com/Kronuz/pyScss). If this is an incorrect assumption, I'd love to know!

**Comment by xzyfer** [comment]
This not valid Sass see https://github.com/sass/sass/issues/626

In future please test your code against Ruby Sass in http://www.sassmeister.com/ before opening an issue.
