### ISSUE TITLE
problem on installing node-sas on win10 - ".NET Framework 2.0 SDK" required?!

### ISSUE THREAD

**Issue by dermoritz** [sass/node-sass#1408]
i am trying to build a project with ```"node-sass": "3.3.3"``` in package.json.
i am getting the error

```
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.           
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Fram 
ework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if  
it is installed elsewhere.
...
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\moritz\entwicklung\osram\code\responsive-design\osram-templates\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Users\\moritz\\entwicklung\\nodejs\\node.exe" "C:\\Users\\moritz\\entwicklung\\osram\\code\\responsive-design\\osram-templates\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\moritz\entwicklung\osram\code\responsive-design\osram-templates\node_modules\node-sass
gyp ERR! node -v v5.6.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
Build failed
npm WARN osram-templates@0.1.0 No repository field.
npm WARN osram-templates@0.1.0 No license field.
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Users\\moritz\\entwicklung\\nodejs\\node.exe" "C:\\Users\\moritz\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "update" "node-sass"
npm ERR! node v5.6.0
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.3.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
```

Do i really need to install 300mb+ sdk to use node-sass?

my node version: 5.6.0
npm version: 3.7.3

**Comment by xzyfer** [comment]
You need atleast node-sass@v3.4.1 for Node 5 support. Upgrade your node-sass it will run fine.

**Comment by dermoritz** [comment]
thanks, in meanwhile i installed node 0.12.12. It is working now. Is there a way to give a more use full error?

**Comment by xzyfer** [comment]
It's certainly something we could look into.
