### ISSUE TITLE
Failed at the node-sass@3.4.2 postinstall script 'node scripts/build.js'.

### ISSUE THREAD

**Issue by Fnatical** [sass/node-sass#1433]
Good afternoon,

This is my first post on GiT so please bear with me if I haven't provided you with enough information to answer my query.

I ran in to the following error:
_Failed at the node-sass@3.4.2 postinstall script 'node scripts/build.js'._

I have attached an image below showing exactly what happened:
![screen shot 2016-03-31 at 3 18 09 pm](https://cloud.githubusercontent.com/assets/12572899/14166127/dede351c-f753-11e5-9b9b-41917382d64c.png)

Thanks in advance!

**Comment by xzyfer** [comment]
Hi @Fnatical, before opening an issue you always read a projects `CONTRIBUTING.md`. The GitHub UI tells you do so when creating a new issue. Without following that document we cannot help you.

![](https://www.evernote.com/l/AJkAbGpPwnxLcoMlHANTpKfqM8QSfYmGJrIB/image.png)

**Comment by jippi** [comment]
Hi,

I'm seeing the same issue

```
-> lsb_release -a && sh node-sass.sh
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 7.9 (wheezy)
Release:	7.9
Codename:	wheezy
3.8.3
v5.10.0
{ http_parser: '2.6.2',
  node: '5.10.0',
  v8: '4.6.85.31',
  uv: '1.8.0',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '56.1',
  modules: '47',
  openssl: '1.0.2g' }
linux
x64
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.

> node-sass@3.4.2 install /root/node_modules/node-sass
> node scripts/install.js


module.js:341
    throw err;
    ^

Error: Cannot find module '/root/node_modules/node-sass/scripts/install.js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:146:18)
    at node.js:404:3

node-sass.sh: 15: node-sass.sh: ./node_modules/.bin/node-sass: not found
/root/node_modules/node-sass/lib/extensions.js:158
    throw new Error([
    ^

Error: The `libsass` binding was not found in /root/node_modules/node-sass/vendor/linux-x64-47/binding.node
This usually happens because your node version has changed.
Run `npm rebuild node-sass` to build the binding for your current node version.
    at Object.sass.getBinaryPath (/root/node_modules/node-sass/lib/extensions.js:158:11)
    at Object.<anonymous> (/root/node_modules/node-sass/lib/index.js:16:36)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at [eval]:1:13
    at Object.exports.runInThisContext (vm.js:54:17)
/root/node_modules/node-sass/lib/extensions.js:158
    throw new Error([
    ^

Error: The `libsass` binding was not found in /root/node_modules/node-sass/vendor/linux-x64-47/binding.node
This usually happens because your node version has changed.
Run `npm rebuild node-sass` to build the binding for your current node version.
    at Object.sass.getBinaryPath (/root/node_modules/node-sass/lib/extensions.js:158:11)
    at Object.<anonymous> (/root/node_modules/node-sass/lib/index.js:16:36)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at [eval]:1:13
    at Object.exports.runInThisContext (vm.js:54:17)
node-sass.sh: 22: cd: can't cd to node_modules/node-sass/vendor
/root/node_modules/node-sass/lib/extensions.js:158
    throw new Error([
    ^

Error: The `libsass` binding was not found in /root/node_modules/node-sass/vendor/linux-x64-47/binding.node
This usually happens because your node version has changed.
Run `npm rebuild node-sass` to build the binding for your current node version.
    at Object.sass.getBinaryPath (/root/node_modules/node-sass/lib/extensions.js:158:11)
    at Object.<anonymous> (/root/node_modules/node-sass/lib/index.js:16:36)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at [eval]:1:13
    at Object.exports.runInThisContext (vm.js:54:17)
```

**Comment by xzyfer** [comment]
@jippi you issue is covered by our documentation.
In the future please read the CONTRIBUTING.md before opening an issue.

**Comment by jippi** [comment]
@xzyfer I've read it, i don't see it covered - maybe point me in the right direction instead of just closing the issue?

**Comment by xzyfer** [comment]
@jippi I closed the issue for two reasons:

- the original issue did not, and since not, supplied the required information to debug
- your issue is not related to the original issue (as seen from the different error messages)

I did not supply a direct link to encourage you to (re-)read the relevant documentation.

Your issue covered in the [TROUBLESHOOTING.md](https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md#cannot-find-module-rootinstalljs) which is linked to from the contributing documentation.
