### ISSUE TITLE
installation of node-sass@2.1.1 fails due to missing file on githubusercontent

### ISSUE THREAD

**Issue by wallymathieu** [sass/node-sass#1483]
Running nodejs LTS: v4.4.3 on windows
```
C:\src\Prg_1_0\Prg\Prg.Web>npm install node-sass@2 --save-dev
npm WARN package.json Prg.Web.SassWatcher@0.0.1 No repository field.
npm WARN package.json Prg.Web.SassWatcher@0.0.1 No README data
npm WARN package.json Prg.Web.SassWatcher@0.0.1 license should be a valid SPDX license expression
npm WARN deprecated pangyp@2.3.3: use node-gyp@3+ instead
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated graceful-fs@2.0.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
/
> node-sass@2.1.1 install C:\src\Prg_1_0\Prg\Prg.Web\node_modules\node-sass
> node scripts/install.js

Can not download file from https://raw.githubusercontent.com/sass/node-sass-binaries/v2.1.1/win32-x64-node-4.4/binding.node

> node-sass@2.1.1 postinstall C:\src\Prg_1_0\Prg\Prg.Web\node_modules\node-sass
> node scripts/build.js

gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: 404 status code downloading 32-bit node.lib
gyp ERR! stack     at Request.<anonymous> (C:\src\Prg_1_0\Prg\Prg.Web\node_modules\node-sass\node_modules\pangyp\lib\install.js:377:20)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:169:7)
gyp ERR! stack     at Request.onRequestResponse (C:\src\Prg_1_0\Prg\Prg.Web\node_modules\node-sass\node_modules\pangyp\node_modules\request\request.js:1255:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:419:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:309:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\src\\Prg_1_0\\Prg\\Prg.Web\\node_modules\\node-sass\\node_modules\\pangyp\\bin\\node-gyp" "rebuild"
gyp ERR! cwd C:\src\Prg_1_0\Prg\Prg.Web\node_modules\node-sass
gyp ERR! node -v v4.4.3
gyp ERR! pangyp -v v2.3.3
gyp ERR! not ok
Build failed
node-sass@2.1.1 node_modules\node-sass
├── get-stdin@4.0.1
├── object-assign@2.1.1
├── replace-ext@0.0.1
├── semver@4.3.6
├── chalk@0.5.1 (ansi-styles@1.1.0, escape-string-regexp@1.0.5, supports-color@0.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)
├── shelljs@0.3.0
├── cross-spawn@0.2.9 (lru-cache@2.7.3)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── npmconf@2.1.2 (ini@1.3.4, uid-number@0.0.5, inherits@2.0.1, once@1.3.3, osenv@0.1.3, config-chain@1.1.10, nopt@3.0.6)
├── gaze@0.5.2 (globule@0.1.0)
├── sass-graph@1.3.0 (commander@2.9.0, lodash@2.4.2, glob@4.5.3)
├── nan@1.9.0
├── meow@3.7.0 (map-obj@1.0.1, trim-newlines@1.0.0, decamelize@1.2.0, object-assign@4.0.1, camelcase-keys@2.1.0, minimist@1.2.0, loud-rejection@1.3.0, redent@1.0.0, normalize-package-data@2.3.5, read-pkg-up@1.0.1)
├── mocha@2.4.5 (escape-string-regexp@1.0.2, commander@2.3.0, diff@1.4.0, growl@1.8.1, supports-color@1.2.0, debug@2.2.0, glob@3.2.3, jade@0.26.3)
├── request@2.72.0 (aws-sign2@0.6.0, forever-agent@0.6.1, tunnel-agent@0.4.2, oauth-sign@0.8.1, caseless@0.11.0, is-typedarray@1.0.0, stringstream@0.0.5, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, tough-cookie@2.2.2, node-uuid@1.4.7, qs@6.1.0, combined-stream@1.0.5, mime-types@2.1.10, form-data@1.0.0-rc4, aws4@1.3.2, bl@1.1.2, hawk@3.1.3, http-signature@1.1.1, har-validator@2.0.6)
└── pangyp@2.3.3 (which@1.0.9, graceful-fs@3.0.8, rimraf@2.2.8, osenv@0.1.3, nopt@3.0.6, glob@4.3.5, minimatch@2.0.10, fstream@1.0.8, tar@1.0.3, request@2.51.0, npmlog@1.0.0)

C:\src\Prg_1_0\Prg\Prg.Web>
```

It complains about a 404 for the URL:
https://raw.githubusercontent.com/sass/node-sass-binaries/v2.1.1/win32-x64-node-4.4/binding.node

**Comment by wallymathieu** [comment]
Duplicate of https://github.com/sass/node-sass/issues/699

**Comment by xzyfer** [comment]
Version 2.1.1 in predates node 4 by about 2 years, and is no longer
supported. Update to 3.6.0
