### ISSUE TITLE
Not able to install node-sass on ubuntu

### ISSUE THREAD

**Issue by ast0708** [sass/node-sass#1501]
I am not able to install node-sass using npm on ubuntu 12.04 machine. 

This is the error that I get

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
TypeError: Object #<Object> has no method 'existsSync'
    at Object.hasBinary (node-sass/lib/extensions.js:199:13)
    at checkAndDownloadBinary (node-sass/scripts/install.js:101:12)
    at Object.<anonymous> (node-sass/scripts/install.js:135:1)
    
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:32)
    at Function._load (module.js:308:12)
    at Array.0 (module.js:479:10)
    at EventEmitter._tickCallback (node.js:192:41)

Node version - 5.8.0
npm version - 3.8.1

Thanks

**Comment by xzyfer** [comment]
Please read the troubleshooting documentation so you know how to report an installation. Make sure to capture the full output into a [gist](https://gist.github.com). Do *not* post the output in this issue or upload your log file.

**Comment by ast0708** [comment]
@xzyfer 
Please find the the gist with the logs and the outputs
[https://gist.github.com/ast0708/092d36ffd2606dd4cc21c17adcd8a314]

**Comment by nschonni** [comment]
The log shows you trying to install 3.4.2 on Node 6. You need to use node-sass 3.7 for node 6 support
