### ISSUE TITLE
Unsupported environment error: "re-evaluating native module sources is not supported"

### ISSUE THREAD

**Issue by marvindanig** [sass/node-sass#1535]
When I start `$ gulp`, I get an error that points to node-sass:

```
(node:13141) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
/Users/admin/projects/comics/fisheye/Intro/node_modules/node-sass/lib/index.js:12
    throw new Error(errors.unsupportedEnvironment());
    ^

Error: Node Sass does not yet support your current environment: OS X 64-bit with false
For more information on which environments are supported please see:
TODO URL
    at Object.<anonymous> (/Users/admin/projects/comics/fisheye/Intro/node_modules/node-sass/lib/index.js:12:11)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/admin/projects/comics/fisheye/Intro/node_modules/gulp-sass/index.js:186:21)
    at Module._compile (module.js:541:32)
```

I'm on node 6.1.0. This was working until 6.0.0, i.e before the latest upgrade to node.

**Comment by xzyfer** [comment]
npm update

**Comment by autoboxer** [comment]
Was this ever proven to be resolved, or was it just closed?  I'm running into the same issue with Node 7.2.0.
