### ISSUE TITLE
npm install node-sass failed in Linux vagrant 3.2.0-23-generic #36-Ubuntu

### ISSUE THREAD

**Issue by Liang-Henry** [sass/node-sass#1536]
run `uname -a` in terminal

> Linux vagrant 3.2.0-23-generic #36-Ubuntu SMP Tue Apr 10 20:39:51 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux

error log is here
```
../src/binding.cpp:335:42:   instantiated from here
../../nan/nan.h:1878:3: error: ‘GetFunction’ was not declared in this scope
make: *** [Release/obj.target/binding/src/binding.o] Error 1
make: Leaving directory `/home/vagrant/henry/genosha/genosha/node_modules/node-sass/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/vagrant/henry/genosha/genosha/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.2.0-23-generic
gyp ERR! command "/usr/bin/nodejs" "/home/vagrant/henry/genosha/genosha/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/vagrant/henry/genosha/genosha/node_modules/node-sass
gyp ERR! node -v v4.4.4
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
Build failed
npm ERR! Linux 3.2.0-23-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "node-sass" "--save-dev"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.7.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.7.0 postinstall script 'node scripts/build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/henry/genosha/genosha/npm-debug.log
```
 gcc version is 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5) now
need help~

**Comment by xzyfer** [comment]
Please read the troubleshooting documentation so you know how to report an installation. Make sure to capture the full output into a [gist](https://gist.github.com). Do *not* post the output in this issue or upload your log file.

**Comment by Liang-Henry** [comment]
thanks, problem is solved when replacing the binding.node file.
BTW, when I update the gcc version to 4.7.3, the problem could be solved, too.
