### ISSUE TITLE
Building crashes on Solaris

### ISSUE THREAD

**Issue by drook** [sass/node-sass#1546]
GCC: 4.5.2
Solaris: 11.2 amd64

Build log:
````build
make: Вход в каталог `/usr/local/grafana/src/github.com/grafana/grafana/node_modules/grunt-sass/node_modules/node-sass/build'
  g++ '-DNODE_GYP_MODULE_NAME=libsass' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DLIBSASS_VERSION="3.3.6"' -I/root/.node-gyp/0.12.2/include/node -I/root/.node-gyp/0.12.2/src -I/root/.node-gyp/0.12.2/deps/uv/include -I/root/.node-gyp/0.12.2/deps/v8/include -I../src/libsass/include  -fPIC -Wall -Wextra -Wno-unused-parameter -m64 -pthreads -O3 -ffunction-sections -fdata-sections -fno-tree-vrp -fno-omit-frame-pointer -std=c++0x -fexceptions -frtti -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/src/ast.o.d.raw   -c -o Release/obj.target/libsass/src/libsass/src/ast.o ../src/libsass/src/ast.cpp
In file included from /usr/gcc/4.5/lib/gcc/i386-pc-solaris2.11/4.5.2/../../../../include/c++/4.5.2/bits/postypes.h:42:0,
                 from /usr/gcc/4.5/lib/gcc/i386-pc-solaris2.11/4.5.2/../../../../include/c++/4.5.2/bits/char_traits.h:42,
                 from /usr/gcc/4.5/lib/gcc/i386-pc-solaris2.11/4.5.2/../../../../include/c++/4.5.2/string:42,
                 from ../src/libsass/src/ast.hpp:7,
                 from ../src/libsass/src/ast.cpp:2:
/usr/gcc/4.5/lib/gcc/i386-pc-solaris2.11/4.5.2/../../../../include/c++/4.5.2/cwchar:166:11: error: ‘::vfwscanf’ has not been declared
/usr/gcc/4.5/lib/gcc/i386-pc-solaris2.11/4.5.2/../../../../include/c++/4.5.2/cwchar:172:11: error: ‘::vswscanf’ has not been declared
/usr/gcc/4.5/lib/gcc/i386-pc-solaris2.11/4.5.2/../../../../include/c++/4.5.2/cwchar:176:11: error: ‘::vwscanf’ has not been declared
/usr/gcc/4.5/lib/gcc/i386-pc-solaris2.11/4.5.2/../../../../include/c++/4.5.2/cwchar:193:11: error: ‘::wcstof’ has not been declared
In file included from /usr/gcc/4.5/lib/gcc/i386-pc-solaris2.11/4.5.2/../../../../include/c++/4.5.2/cwchar:287:0,
                 from /usr/gcc/4.5/lib/gcc/i386-pc-solaris2.11/4.5.2/../../../../include/c++/4.5.2/bits/postypes.h:42,
                 from /usr/gcc/4.5/lib/gcc/i386-pc-solaris2.11/4.5.2/../../../../include/c++/4.5.2/bits/char_traits.h:42,
                 from /usr/gcc/4.5/lib/gcc/i386-pc-solaris2.11/4.5.2/../../../../include/c++/4.5.2/string:42,
                 from ../src/libsass/src/ast.hpp:7,
                 from ../src/libsass/src/ast.cpp:2:
/usr/gcc/4.5/lib/gcc/i386-pc-solaris2.11/4.5.2/../../../../include/c++/4.5.2/tr1_impl/cwchar:37:14: error: ‘std::wcstof’ has not been declared
/usr/gcc/4.5/lib/gcc/i386-pc-solaris2.11/4.5.2/../../../../include/c++/4.5.2/tr1_impl/cwchar:40:14: error: ‘std::vfwscanf’ has not been declared
/usr/gcc/4.5/lib/gcc/i386-pc-solaris2.11/4.5.2/../../../../include/c++/4.5.2/tr1_impl/cwchar:43:14: error: ‘std::vswscanf’ has not been declared
/usr/gcc/4.5/lib/gcc/i386-pc-solaris2.11/4.5.2/../../../../include/c++/4.5.2/tr1_impl/cwchar:46:14: error: ‘std::vwscanf’ has not been declared
In file included from /usr/gcc/4.5/lib/gcc/i386-pc-solaris2.11/4.5.2/../../../../include/c++/4.5.2/cctype:93:0,
                 from /usr/gcc/4.5/lib/gcc/i386-pc-solaris2.11/4.5.2/../../../../include/c++/4.5.2/bits/localefwd.h:44,
                 from /usr/gcc/4.5/lib/gcc/i386-pc-solaris2.11/4.5.2/../../../../include/c++/4.5.2/string:45,
                 from ../src/libsass/src/ast.hpp:7,
                 from ../src/libsass/src/ast.cpp:2:
/usr/gcc/4.5/lib/gcc/i386-pc-solaris2.11/4.5.2/../../../../include/c++/4.5.2/tr1_impl/cctype:38:11: error: ‘::isblank’ has not been declared
In file included from /usr/gcc/4.5/lib/gcc/i386-pc-solaris2.11/4.5.2/../../../../include/c++/4.5.2/bits/locale_facets.h:41:0,
                 from /usr/gcc/4.5/lib/gcc/i386-pc-solaris2.11/4.5.2/../../../../include/c++/4.5.2/bits/basic_ios.h:39,
                 from /usr/gcc/4.5/lib/gcc/i386-pc-solaris2.11/4.5.2/../../../../include/c++/4.5.2/ios:45,
                 from /usr/gcc/4.5/lib/gcc/i386-pc-solaris2.11/4.5.2/../../../../include/c++/4.5.2/istream:40,
                 from /usr/gcc/4.5/lib/gcc/i386-pc-solaris2.11/4.5.2/../../../../include/c++/4.5.2/sstream:39,
                 from ../src/libsass/src/ast.hpp:8,
                 from ../src/libsass/src/ast.cpp:2:
/usr/gcc/4.5/lib/gcc/i386-pc-solaris2.11/4.5.2/../../../../include/c++/4.5.2/cwctype:85:11: error: ‘::iswblank’ has not been declared
In file included from /usr/gcc/4.5/lib/gcc/i386-pc-solaris2.11/4.5.2/../../../../include/c++/4.5.2/cwctype:118:0,
                 from /usr/gcc/4.5/lib/gcc/i386-pc-solaris2.11/4.5.2/../../../../include/c++/4.5.2/bits/locale_facets.h:41,
                 from /usr/gcc/4.5/lib/gcc/i386-pc-solaris2.11/4.5.2/../../../../include/c++/4.5.2/bits/basic_ios.h:39,
                 from /usr/gcc/4.5/lib/gcc/i386-pc-solaris2.11/4.5.2/../../../../include/c++/4.5.2/ios:45,
                 from /usr/gcc/4.5/lib/gcc/i386-pc-solaris2.11/4.5.2/../../../../include/c++/4.5.2/istream:40,
                 from /usr/gcc/4.5/lib/gcc/i386-pc-solaris2.11/4.5.2/../../../../include/c++/4.5.2/sstream:39,
                 from ../src/libsass/src/ast.hpp:8,
                 from ../src/libsass/src/ast.cpp:2:
/usr/gcc/4.5/lib/gcc/i386-pc-solaris2.11/4.5.2/../../../../include/c++/4.5.2/tr1_impl/cwctype:37:14: error: ‘std::iswblank’ has not been declared
In file included from ../src/libsass/src/ast.cpp:2:0:
../src/libsass/src/ast.hpp: In member function ‘virtual size_t Sass::Vectorized<T>::hash()’:
../src/libsass/src/ast.hpp:257:20: error: expected initializer before ‘:’ token
../src/libsass/src/ast.hpp:260:7: error: expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:260:7: error: expected ‘;’ before ‘}’ token
../src/libsass/src/ast.hpp:260:7: error: expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:260:7: error: expected ‘)’ before ‘}’ token
../src/libsass/src/ast.hpp:260:7: error: expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:260:7: error: expected ‘;’ before ‘}’ token
../src/libsass/src/ast.hpp: In member function ‘Sass::Hashed& Sass::Hashed::operator+=(Sass::Hashed*)’:
../src/libsass/src/ast.hpp:336:21: error: expected initializer before ‘:’ token
../src/libsass/src/ast.hpp:340:27: error: could not convert ‘Sass::Hashed::reset_duplicate_key()’ to ‘bool’
../src/libsass/src/ast.hpp:341:7: error: expected primary-expression before ‘return’
../src/libsass/src/ast.hpp:341:7: error: expected ‘)’ before ‘return’
../src/libsass/src/ast.hpp: In member function ‘virtual size_t Sass::Map::hash()’:
../src/libsass/src/ast.hpp:936:23: error: expected initializer before ‘:’ token
../src/libsass/src/ast.hpp:940:7: error: expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:940:7: error: expected ‘;’ before ‘}’ token
../src/libsass/src/ast.hpp:940:7: error: expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:940:7: error: expected ‘)’ before ‘}’ token
../src/libsass/src/ast.hpp:940:7: error: expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:940:7: error: expected ‘;’ before ‘}’ token
../src/libsass/src/ast.hpp: In member function ‘virtual size_t Sass::Function_Call::hash()’:
../src/libsass/src/ast.hpp:1232:28: error: expected initializer before ‘:’ token
../src/libsass/src/ast.hpp:1234:7: error: expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:1234:7: error: expected ‘;’ before ‘}’ token
../src/libsass/src/ast.hpp:1234:7: error: expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:1234:7: error: expected ‘)’ before ‘}’ token
../src/libsass/src/ast.hpp:1234:7: error: expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:1234:7: error: expected ‘;’ before ‘}’ token
../src/libsass/src/ast.hpp: In member function ‘virtual size_t Sass::Number::hash()’:
../src/libsass/src/ast.hpp:1361:35: error: expected initializer before ‘:’ token
../src/libsass/src/ast.hpp:1363:9: error: expected primary-expression before ‘for’
../src/libsass/src/ast.hpp:1363:9: error: expected ‘;’ before ‘for’
../src/libsass/src/ast.hpp:1363:9: error: expected primary-expression before ‘for’
../src/libsass/src/ast.hpp:1363:9: error: expected ‘)’ before ‘for’
../src/libsass/src/ast.hpp:1363:37: error: expected initializer before ‘:’ token
../src/libsass/src/ast.hpp:1365:7: error: expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:1365:7: error: expected ‘;’ before ‘}’ token
../src/libsass/src/ast.hpp:1365:7: error: expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:1365:7: error: expected ‘)’ before ‘}’ token
../src/libsass/src/ast.hpp:1365:7: error: expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:1365:7: error: expected ‘;’ before ‘}’ token
../src/libsass/src/ast.hpp: In member function ‘bool Sass::String_Schema::has_interpolants()’:
../src/libsass/src/ast.hpp:1502:20: error: expected initializer before ‘:’ token
../src/libsass/src/ast.hpp:1505:7: error: expected primary-expression before ‘return’
../src/libsass/src/ast.hpp:1505:7: error: expected ‘;’ before ‘return’
../src/libsass/src/ast.hpp:1505:7: error: expected primary-expression before ‘return’
../src/libsass/src/ast.hpp:1505:7: error: expected ‘)’ before ‘return’
../src/libsass/src/ast.hpp: In member function ‘virtual size_t Sass::String_Schema::hash()’:
../src/libsass/src/ast.hpp:1514:26: error: expected initializer before ‘:’ token
../src/libsass/src/ast.hpp:1516:7: error: expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:1516:7: error: expected ‘;’ before ‘}’ token
../src/libsass/src/ast.hpp:1516:7: error: expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:1516:7: error: expected ‘)’ before ‘}’ token
../src/libsass/src/ast.hpp:1516:7: error: expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:1516:7: error: expected ‘;’ before ‘}’ token
In file included from ../src/libsass/src/ast.cpp:2:0:
../src/libsass/src/ast.hpp: In member function ‘virtual void Sass::Selector_List::set_media_block(Sass::Media_Block*)’:
../src/libsass/src/ast.hpp:2505:33: error: expected initializer before ‘:’ token
../src/libsass/src/ast.hpp:2508:5: error: expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:2508:5: error: expected ‘;’ before ‘}’ token
../src/libsass/src/ast.hpp:2508:5: error: expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:2508:5: error: expected ‘)’ before ‘}’ token
../src/libsass/src/ast.hpp:2508:5: error: expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:2508:5: error: expected ‘;’ before ‘}’ token
../src/libsass/src/ast.cpp: In member function ‘virtual bool Sass::Compound_Selector::has_parent_ref()’:
../src/libsass/src/ast.cpp:139:29: error: expected initializer before ‘:’ token
../src/libsass/src/ast.cpp:142:5: error: expected primary-expression before ‘return’
../src/libsass/src/ast.cpp:142:5: error: expected ‘;’ before ‘return’
../src/libsass/src/ast.cpp:142:5: error: expected primary-expression before ‘return’
../src/libsass/src/ast.cpp:142:5: error: expected ‘)’ before ‘return’
../src/libsass/src/ast.cpp: In member function ‘virtual bool Sass::Compound_Selector::is_superselector_of(Sass::Selector_List*, std::string)’:
../src/libsass/src/ast.cpp:661:33: error: expected initializer before ‘:’ token
../src/libsass/src/ast.cpp:664:5: error: expected primary-expression before ‘return’
../src/libsass/src/ast.cpp:664:5: error: expected ‘;’ before ‘return’
../src/libsass/src/ast.cpp:664:5: error: expected primary-expression before ‘return’
../src/libsass/src/ast.cpp:664:5: error: expected ‘)’ before ‘return’
../src/libsass/src/ast.cpp: In member function ‘Sass::Selector_List* Sass::Complex_Selector::parentize(Sass::Selector_List*, Sass::Context&)’:
../src/libsass/src/ast.cpp:1171:32: error: expected initializer before ‘:’ token
../src/libsass/src/ast.cpp:2216:1: error: expected primary-expression at end of input
../src/libsass/src/ast.cpp:2216:1: error: expected ‘;’ at end of input
../src/libsass/src/ast.cpp:2216:1: error: expected primary-expression at end of input
../src/libsass/src/ast.cpp:2216:1: error: expected ‘)’ at end of input
../src/libsass/src/ast.cpp:2216:1: error: expected statement at end of input
../src/libsass/src/ast.cpp:2216:1: error: expected ‘}’ at end of input
../src/libsass/src/ast.cpp:2216:1: error: expected ‘}’ at end of input
../src/libsass/src/ast.cpp: At global scope:
../src/libsass/src/ast.cpp:2216:1: error: expected ‘}’ at end of input
../src/libsass/src/ast.cpp: In member function ‘Sass::Selector_List* Sass::Complex_Selector::parentize(Sass::Selector_List*, Sass::Context&)’:
../src/libsass/src/ast.cpp:2216:1: warning: control reaches end of non-void function
../src/libsass/src/ast.cpp: In member function ‘virtual bool Sass::Compound_Selector::is_superselector_of(Sass::Selector_List*, std::string)’:
../src/libsass/src/ast.cpp:665:3: warning: control reaches end of non-void function
../src/libsass/src/ast.cpp: In member function ‘virtual bool Sass::Compound_Selector::has_parent_ref()’:
../src/libsass/src/ast.cpp:143:3: warning: control reaches end of non-void function
../src/libsass/src/units.hpp: At global scope:
../src/libsass/src/units.hpp:10:16: warning: ‘Sass::PI’ defined but not used
make: *** [Release/obj.target/libsass/src/libsass/src/ast.o] Ошибка 1
make: Выход из каталога `/usr/local/grafana/src/github.com/grafana/grafana/node_modules/grunt-sass/node_modules/node-sass/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/grafana/src/github.com/grafana/grafana/node_modules/grunt-sass/node_modules/node-sass/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System SunOS 5.11
gyp ERR! command "/usr/local/node.js-0.12.2/bin/node" "/usr/local/grafana/src/github.com/grafana/grafana/node_modules/grunt-sass/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /usr/local/grafana/src/github.com/grafana/grafana/node_modules/grunt-sass/node_modules/node-sass
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
Build failed
npm ERR! SunOS 5.11
npm ERR! argv "/usr/local/node.js-0.12.2/bin/node" "/usr/local/node.js/bin/npm" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! phantomjs-prebuilt@2.1.7 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs-prebuilt@2.1.7 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/grafana/src/github.com/grafana/grafana/npm-debug.log
````

**Comment by xzyfer** [comment]
A quick search of issues or a look at the release notes would have shown that SunOS is not currently supported, and that gcc 4.7 is required.

**Comment by drook** [comment]
Okay, I managed to build it using gcc 4.8.6. But node-sass still complains:

````node-sass
[root@hyperion grafana]# grunt
Version 3.0.1
Loading "sass.js" tasks...ERROR
>> Error: Node Sass does not yet support your current environment: Unsupported platform (sunos) 64-bit with Node 0.12.x
>> For more information on which environments are supported please see:
>> https://github.com/sass/node-sass/releases/tag/v3.7.0
````

and then grunt (I'm using this inside grafana tree) bails out. Is there any way around ?

**Comment by drook** [comment]
Figured out myself, all you have to do is add a line in extensions.js. At least grunt-sass finished without errors. Thanks.
