### ISSUE TITLE
«Cannot find module 'mkdirp'» error ruins `node-sass@3.7.0` installation

### ISSUE THREAD

**Issue by artuska** [sass/node-sass#1555]
This is what I got trying to install `node-sass@3.7.0` on `node v6.2.0` and `npm v3.9.0`.

This is main start of installation log:

```
E:\> npm install node-sass
npm WARN prefer global node-gyp@3.3.1 should be installed with -g
npm WARN prefer global npm@3.9.0 should be installed with -g

> node-sass@3.7.0 install E:\node_modules\node-sass
> node scripts/install.js

module.js:442
    throw err;
    ^

Error: Cannot find module 'mkdirp'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (E:\node_modules\node-sass\scripts\install.js:7:13)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
Flat@0.0.1 E:\
+-- bower@1.7.7  extraneous
+-- mkdirp@0.5.1
+-- node-static@0.7.7  extraneous
`-- npm@3.9.0  extraneous
```

This is the end of installation log:

```
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\nodejs\\node.exe" "C:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-sass"
npm ERR! node v6.2.0
npm ERR! npm  v3.9.0
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.7.0 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.7.0 install script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\npm-debug.log
```

Full installation log — http://plnkr.co/edit/xBc5ZGbDl1sOtNAxZKYs

**Comment by artuska** [comment]
Updating Bower to the `bower@1.7.9` did the trick :)
