### ISSUE TITLE
The system cannot find message text for message number 0x%1 in the message file for %2

### ISSUE THREAD

**Issue by sunalyou** [sass/node-sass#1562]
### Stack Trace

Uncaught Error: The system cannot find message text for message number 0x%1 in the message file for %2.
\\?\C:\Users\Administrator\.atom\packages\atom-react-native-css\node_modules\node-sass\vendor\win32-ia32-47\binding.node

```
At ATOM_SHELL_ASAR.js:159

Error: The system cannot find message text for message number 0x%1 in the message file for %2.
\\?\C:\Users\Administrator\.atom\packages\atom-react-native-css\node_modules\node-sass\vendor\win32-ia32-47\binding.node
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ATOM_SHELL_ASAR.js:159:20)
    at Object.Module._extensions..node (module.js:450:18)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:159:20)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\Administrator\AppData\Local\atom\app-1.7.3\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\Administrator\.atom\packages\atom-react-native-css\node_modules\node-sass\lib\index.js:23:15)
    at Module._compile (C:\Users\Administrator\AppData\Local\atom\app-1.7.3\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\Administrator\AppData\Local\atom\app-1.7.3\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\Administrator\AppData\Local\atom\app-1.7.3\resources\app.asar\src\native-compile-cache.js:50:27)
    at compile.parseJSS (C:\Users\Administrator\.atom\packages\atom-react-native-css\lib\compile.js:79:77)
    at C:\Users\Administrator\.atom\packages\atom-react-native-css\lib\index.js:64:37
```

### Commands

```
     -5:08.2.0 core:save (atom-text-editor.editor.is-focused)
  2x -4:46.7.0 tree-view:toggle (atom-text-editor.editor.is-focused)
     -3:56.7.0 core:save (atom-text-editor.editor.is-focused)
     -3:41.6.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -3:41.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -3:40.3.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -3:40.3.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
  4x -3:38.1.0 core:save (atom-text-editor.editor.is-focused)
     -2:43.7.0 tree-view:remove-project-folder (div.header.list-item)
     -2:41 application:add-project-folder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  2x -2:22.9.0 core:save (atom-text-editor.editor.is-focused)
```

**Comment by nschonni** [comment]
The Atom shell isn't supported by this project. You'll need to ask upstream in the Atom plug-in project for support
