### ISSUE TITLE
Issue with update from 3.7 to 3.8

### ISSUE THREAD

**Issue by amit777** [sass/node-sass#1606]
I know this is going to be an extremely vague report.  However, I'm using mongoose 4.5.2, email-templates 2.3.0 and node-sass 3.7.0.  Everything works fine when I render an email template.  When I update to node-sass 3.8.0, I get a strange issue where it seems like the template function is attempting to clone a mongoose object that I pass into the rendering engine..  Here is the stack trace (it seems to be related to getOptions that may have changed in 3.8.0).  This may not be a node-sass issue, but either a mongoose or email-templates issue. I'm only reporting it here to help get clarity since if I revert to 3.7.0, everything works fine:

```
TypeError: Cannot read property 'states' of undefined
    at model.Document.$__shouldModify (/opt/app/node_modules/mongoose/lib/document.js:765:35)
    at model.Document.$__set (/opt/app/node_modules/mongoose/lib/document.js:785:27)
    at model.Document.set (/opt/app/node_modules/mongoose/lib/document.js:705:10)
    at model.Object.defineProperty.set [as domainname] (/opt/app/node_modules/mongoose/lib/document.js:1712:25)
    at assignValue (/opt/app/node_modules/lodash._baseclone/index.js:758:17)
    at /opt/app/node_modules/lodash._baseclone/index.js:863:5
    at arrayEach (/opt/app/node_modules/lodash._baseclone/index.js:164:9)
    at baseClone (/opt/app/node_modules/lodash._baseclone/index.js:858:3)
    at /opt/app/node_modules/lodash._baseclone/index.js:863:30
    at arrayEach (/opt/app/node_modules/lodash._baseclone/index.js:164:9)
    at baseClone (/opt/app/node_modules/lodash._baseclone/index.js:858:3)
    at /opt/app/node_modules/lodash._baseclone/index.js:863:30
    at arrayEach (/opt/app/node_modules/lodash._baseclone/index.js:164:9)
    at baseClone (/opt/app/node_modules/lodash._baseclone/index.js:858:3)
    at /opt/app/node_modules/lodash._baseclone/index.js:863:30
    at arrayEach (/opt/app/node_modules/lodash._baseclone/index.js:164:9)
    at baseClone (/opt/app/node_modules/lodash._baseclone/index.js:858:3)
    at /opt/app/node_modules/lodash._baseclone/index.js:863:30
    at arrayEach (/opt/app/node_modules/lodash._baseclone/index.js:164:9)
    at baseClone (/opt/app/node_modules/lodash._baseclone/index.js:858:3)
    at /opt/app/node_modules/lodash._baseclone/index.js:863:30
    at arrayEach (/opt/app/node_modules/lodash._baseclone/index.js:164:9)
    at baseClone (/opt/app/node_modules/lodash._baseclone/index.js:858:3)
    at /opt/app/node_modules/lodash._baseclone/index.js:863:30
    at arrayEach (/opt/app/node_modules/lodash._baseclone/index.js:164:9)
    at baseClone (/opt/app/node_modules/lodash._baseclone/index.js:858:3)
    at /opt/app/node_modules/lodash._baseclone/index.js:863:30
    at arrayEach (/opt/app/node_modules/lodash._baseclone/index.js:164:9)
    at baseClone (/opt/app/node_modules/lodash._baseclone/index.js:858:3)
    at /opt/app/node_modules/lodash._baseclone/index.js:863:30
    at arrayEach (/opt/app/node_modules/lodash._baseclone/index.js:164:9)
    at baseClone (/opt/app/node_modules/lodash._baseclone/index.js:858:3)
    at cloneDeep (/opt/app/node_modules/lodash.clonedeep/index.js:28:10)
    at getOptions (/opt/app/node_modules/node-sass/lib/index.js:175:17)
    at Object.module.exports.render (/opt/app/node_modules/node-sass/lib/index.js:268:17)
    at /opt/app/node_modules/email-templates/lib/template-manager.js:124:10
    at Promise._execute (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/debuggability.js:272:9)
    at Promise._resolveFromExecutor (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/promise.js:475:18)
    at new Promise (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/promise.js:77:14)
    at renderSass (/opt/app/node_modules/email-templates/lib/template-manager.js:123:10)
    at /opt/app/node_modules/email-templates/lib/template-manager.js:63:22
    at Promise._execute (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/debuggability.js:272:9)
    at Promise._resolveFromExecutor (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/promise.js:475:18)
    at new Promise (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/promise.js:77:14)
    at render (/opt/app/node_modules/email-templates/lib/template-manager.js:45:10)
    at renderFile (/opt/app/node_modules/email-templates/lib/util.js:53:38)
    at /opt/app/node_modules/email-templates/lib/email-template.js:200:38
    at Promise._execute (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/debuggability.js:272:9)
    at Promise._resolveFromExecutor (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/promise.js:475:18)
    at new Promise (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/promise.js:77:14)
    at EmailTemplate._renderStyle (/opt/app/node_modules/email-templates/lib/email-template.js:188:14)
    at /opt/app/node_modules/email-templates/lib/email-template.js:146:97
    at tryCatcher (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/promise.js:685:18)
    at Promise._fulfill (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/promise.js:630:18)
    at Promise._resolveCallback (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/promise.js:425:57)
    at Promise._settlePromiseFromHandler (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/promise.js:516:17)
    at Promise._settlePromise (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/promise.js:685:18)
    at Promise._fulfill (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/promise.js:630:18)
    at Promise._resolveCallback (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/promise.js:425:57)
    at Promise._settlePromiseFromHandler (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/promise.js:516:17)
    at Promise._settlePromise (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/promise.js:685:18)
    at Promise._fulfill (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/promise.js:630:18)
    at MappingPromiseArray.PromiseArray._resolve (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/promise_array.js:125:19)
    at MappingPromiseArray._promiseFulfilled (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/map.js:97:18)
    at Promise._settlePromise (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/promise.js:566:26)
    at Promise._settlePromise0 (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/promise.js:685:18)
    at Promise._fulfill (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/promise.js:630:18)
    at Promise._resolveCallback (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/promise.js:425:57)
    at Promise._settlePromiseFromHandler (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/promise.js:516:17)
    at Promise._settlePromise (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/promise.js:685:18)
    at Promise._fulfill (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/promise.js:630:18)
    at /opt/app/node_modules/email-templates/node_modules/bluebird/js/release/nodeback.js:42:21
```

**Comment by xzyfer** [comment]
>it seems like the template function is attempting to clone a mongoose object that I pass into the rendering engine

This is correct. In 3.8.0 we started cloning the options object passed into render to prevent mutations leaking into the calling code.

**Comment by amit777** [comment]
Got it.. I'm not sure if it makes sense to have a flag to clone or not clone. This is all a bit over my head.

**Comment by xzyfer** [comment]
It does not. JavaScript are only shallow copied when used as function arguments. So if that object has nested objects or arrays they're still reference to the originals. If they're altered by us they are altered in your code. This means we could change your mongoose object and change your database. Since these objects would be available to custom js functions this would be very bad.

I'm not sure why you would be passing mongoose object to node-sass, but I highly recommend never doing this.

**Comment by vkarpov15** [comment]
Agreed with @xzyfer . Use `doc.toObject()` before passing a mongoose object in as a param to an outside lib, a mongoose document is a very complex object that you don't want to clone directly.
