### ISSUE TITLE
Error in Module._extensions[extension](this, filename)

### ISSUE THREAD

**Issue by TiagoGouvea** [sass/node-sass#1611]
I opened this issue because I follow a lot of another issues to solve it, but I can't, and the error still happening.

```
MacBook-Pro:public TiagoGouvea$ node-sass
module.js:355
  Module._extensions[extension](this, filename);
                               ^

Error: dlopen(/Users/TiagoGouvea/.nvm/versions/node/v4.1.1/lib/node_modules/node-sass/vendor/darwin-x64-46/binding.node, 1): no suitable image found.  Did find:
	/Users/TiagoGouvea/.nvm/versions/node/v4.1.1/lib/node_modules/node-sass/vendor/darwin-x64-46/binding.node: truncated mach-o error: segment __TEXT extends to 1212416 which is past end of file 382512
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/TiagoGouvea/.nvm/versions/node/v4.1.1/lib/node_modules/node-sass/lib/index.js:24:15)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

MacBook-Pro:public TiagoGouvea$ node -v
v4.1.1
MacBook-Pro:public TiagoGouvea$ npm -v
3.9.5
```

The install:
```
MacBook-Pro:public TiagoGouvea$ npm install -g node-sass
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
/Users/TiagoGouvea/.npm-packages/bin/node-sass -> /Users/TiagoGouvea/.npm-packages/lib/node_modules/node-sass/bin/node-sass

> node-sass@3.8.0 install /Users/TiagoGouvea/.npm-packages/lib/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /Users/TiagoGouvea/.npm-packages/lib/node_modules/node-sass/vendor/darwin-x64-46/binding.node

> node-sass@3.8.0 postinstall /Users/TiagoGouvea/.npm-packages/lib/node_modules/node-sass
> node scripts/build.js

"/Users/TiagoGouvea/.npm-packages/lib/node_modules/node-sass/vendor/darwin-x64-46/binding.node" exists. 
 testing binary.
Binary is fine; exiting.
```

**Comment by TiagoGouvea** [comment]
[WORKAROUND]
I don't mind why, but running the same with sudo, make it work. 

```
MacBook-Pro:public TiagoGouvea$ sudo npm install node-sass -g
```
