### ISSUE TITLE
npm install node-sass fails in Ubuntu 16.04

### ISSUE THREAD

**Issue by aspiring-astro** [sass/node-sass#1627]
I'm attaching a npm debug log that shows node-sass is failing in Ubuntu:
10812 verbose stack Error: node-sass@3.4.2 install: `node scripts/install.js`
10812 verbose stack spawn ENOENT
10812 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:17:16)
10812 verbose stack     at emitTwo (events.js:87:13)
10812 verbose stack     at ChildProcess.emit (events.js:172:7)
10812 verbose stack     at maybeClose (internal/child_process.js:821:16)
10812 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10813 verbose pkgid node-sass@3.4.2
10814 verbose cwd /home/$USER/learn/npm/react-isomorphic-starterkit
10815 error Linux 4.4.0-28-generic
10816 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "node-sass"
10817 error node v4.2.6
10818 error npm  v3.5.2
10819 error file sh
10820 error code ELIFECYCLE
10821 error errno ENOENT
10822 error syscall spawn
10823 error node-sass@3.4.2 install: `node scripts/install.js`
10823 error spawn ENOENT
10824 error Failed at the node-sass@3.4.2 install script 'node scripts/install.js'.
10824 error Make sure you have the latest version of node.js and npm installed.
10824 error If you do, this is most likely a problem with the node-sass package,
10824 error not with npm itself.
10824 error Tell the author that this fails on your system:
10824 error     node scripts/install.js
10824 error You can get information on how to open an issue for this project with:
10824 error     npm bugs node-sass
10824 error Or if that isn't available, you can get their info via:
10824 error     npm owner ls node-sass
10824 error There is likely additional logging output above.
10825 verbose exit [ 1, true ]

**Comment by aspiring-astro** [comment]
Here is the fix for the problem - The root cause appears to a package name conflict in Ubuntu repository for the 'node' package. So, it is installed as nodejs in /usr/bin and the install script for node-sass invokes node which fails to locate the dependency manager. This is the root cause for the ENOENT ( No such file or directory) error seen during install.

I fixed this by creating a symbolic link:
sudo ln -s /usr/bin/nodejs /usr/bin/node

Hope this helps someone.
