### ISSUE TITLE
Missing binding for 3.2.0 darwin-x64-46 (404) 

### ISSUE THREAD

**Issue by elliottshort** [sass/node-sass#1653]
```
npm ERR! Please include the following file with any support request:
npm ERR!
/Users/Elliott/.meteor/packages/fourseven_scss/.3.2.0.ht468a++os.osx.x86_64+web.browser+web.cordova/plugin.compileScss.os.osx.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/.temp-q1nbef/npm-debug.log
Cannot download "https://github.com/sass/node-sass/releases/download/v3.2.0/darwin-x64-46_binding.node": HTTP error 404 Not Found
gyp: /Users/Elliott/.node-gyp/4.4.7/common.gypi not found (cwd:
/Users/Elliott/.meteor/packages/fourseven_scss/.3.2.0.ht468a++os.osx.x86_64+web.browser+web.cordova/plugin.compileScss.os.osx.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/.temp-q1nbef/node_modules/node-sass)
while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit
(/Users/Elliott/.meteor/packages/fourseven_scss/.3.2.0.ht468a++os.osx.x86_64+web.browser+web.cordova/plugin.compileScss.os.osx.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/.temp-q1nbef/node_modules/node-sass/node_modules/pangyp/lib/configure.js:345:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.5.0
gyp ERR! command
"/Users/Elliott/.meteor/packages/meteor-tool/.1.4.0-1.1jkhhim++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node"
"/Users/Elliott/.meteor/packages/fourseven_scss/.3.2.0.ht468a++os.osx.x86_64+web.browser+web.cordova/plugin.compileScss.os.osx.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/.temp-q1nbef/node_modules/node-sass/node_modules/pangyp/bin/node-gyp"
"rebuild" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd
/Users/Elliott/.meteor/packages/fourseven_scss/.3.2.0.ht468a++os.osx.x86_64+web.browser+web.cordova/plugin.compileScss.os.osx.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/.temp-q1nbef/node_modules/node-sass
gyp ERR! node -v v4.4.7
gyp ERR! pangyp -v v2.2.1
gyp ERR! not ok 
Build failed

```

**Comment by xzyfer** [comment]
You need atleast v3.4.0 for Node 4 support. Update to v3.8.0 for support.
