### ISSUE TITLE
npm installation error on AWS Elastic Beanstalk linux environment

### ISSUE THREAD

**Issue by patrickbussmann** [sass/node-sass#1656]
Hey guys,

I have the same error as this both guys have. (#799, #1639, #1641)
But not on their environments... I'm using the AWS Elastic Beanstalk.

    System Linux 4.4.14-24.50.amzn1.x86_64
    node -v v0.10.42
    npm -v 1.3.6

**npm-debug.log:**
[npm-debug.log.txt](https://github.com/sass/node-sass/files/405808/npm-debug.log.txt)

    > node-sass@3.8.0 install /var/app/ondeck/node_modules/gulp-sass/node_modules/node-sass
    > node scripts/install.js
    
    npm ERR! Error: spawn ENOENT
    npm ERR!     at errnoException (child_process.js:1011:11)
    npm ERR!     at Process.ChildProcess._handle.onexit (child_process.js:802:34)
    npm ERR! If you need help, you may report this log at:
    npm ERR!     <http://github.com/isaacs/npm/issues>
    npm ERR! or email it to:
    npm ERR!     <npm-@googlegroups.com>

**Used command:**
`container_commands:
  100-install-npm-packages:
    command: "npm install"`

The funny thing is that I have a lot of gulp modules... And only `gulp-sass` fails. Don't know why :-1: 

But nice package. So I hope the installation can be easier in future and thanks in Advance for fixing it :+1:

**Comment by xzyfer** [comment]
>The funny thing is that I have a lot of gulp modules

Is it funny?

****

Node 0.10 ships with a very old, very broken npm. You'll need to update to at least npm@2.

```
npm install -g npm@2
```
