### ISSUE TITLE
node sass rebuild not working for ionic app

### ISSUE THREAD

**Issue by agastya26** [sass/node-sass#1729]
Agastyas-MacBook-Air:ionic-firebase-chat-master EnterTheAku$ ionic serve
WARN: ionic.project has been renamed to ionic.config.json, please rename it.
(node:44321) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.

There is an error in your gulpfile: 
Error: The `libsass` binding was not found in /Users/EnterTheAku/Desktop/Ionic Vault/ionic-firebase-chat-master/node_modules/gulp-sass/node_modules/node-sass/vendor/darwin-x64-48/binding.node
This usually happens because your node version has changed.
Run `npm rebuild node-sass` to build the binding for your current node version.
    at Object.sass.getBinaryPath (/Users/EnterTheAku/Desktop/Ionic Vault/ionic-firebase-chat-master/node_modules/gulp-sass/node_modules/node-sass/lib/extensions.js:158:11)
    at Object.<anonymous> (/Users/EnterTheAku/Desktop/Ionic Vault/ionic-firebase-chat-master/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:16:36)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/EnterTheAku/Desktop/Ionic Vault/ionic-firebase-chat-master/node_modules/gulp-sass/index.js:186:21)

Agastyas-MacBook-Air:ionic-firebase-chat-master EnterTheAku$ npm rebuild node-sass

> node-sass@3.4.2 install /Users/EnterTheAku/Desktop/Ionic Vault/ionic-firebase-chat-master/node_modules/gulp-sass/node_modules/node-sass
> node scripts/install.js

module.js:457
    throw err;
    ^

Error: Cannot find module 'is-property'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/EnterTheAku/Desktop/Ionic Vault/ionic-firebase-chat-master/node_modules/gulp-sass/node_modules/node-sass/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/node_modules/generate-object-property/index.js:1:80)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)

npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/Cellar/node/6.4.0/bin/node" "/usr/local/bin/npm" "rebuild" "node-sass"
npm ERR! node v6.4.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! node-sass@3.4.2 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.4.2 install script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/EnterTheAku/Desktop/Ionic Vault/ionic-firebase-chat-master/npm-debug.log

**Comment by nschonni** [comment]
Sorry, you didn't follow the issue template, so we can't help you.

**Comment by xzyfer** [comment]
Your version of node-sass is too old for Node 6. Down grade to Node 4 or update to node-sass@v3.10
