### ISSUE TITLE
Upgraded Node and receiving the following  errors  when trying to rebuild node-sass (foundation 6)

### ISSUE THREAD

**Issue by caesar103** [sass/node-sass#1732]
../node_modules/nan/nan.h:602:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:608:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback) {
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:613:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:619:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback) {
      ~~~~~~~~~~~~~^
4 errors generated.
make: *** [Release/obj.target/binding/src/binding.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/caesar/Documents/websites/jameetareneehair/jamhair/node_modules/gulp-sass/node_modules/node-sass/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/usr/local/Cellar/node/6.6.0/bin/node" "/Users/caesar/Documents/websites/jameetareneehair/jamhair/node_modules/gulp-sass/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/caesar/Documents/websites/jameetareneehair/jamhair/node_modules/gulp-sass/node_modules/node-sass
gyp ERR! node -v v6.6.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok 
Build failed

**Comment by nschonni** [comment]
Sorry, you didn't follow the issue template, so we can't help you.

**Comment by xzyfer** [comment]
You need to update to atleast node-sass@v3.9.0 for Node 6 support.

**Comment by caesar103** [comment]
Thanks @xzyfer I actually did it earlier by accident by having npm upgrade the project.  Wasnt sure what solved it till you said that!!!
