### ISSUE TITLE
Node 7 support

### ISSUE THREAD

**Issue by xzyfer** [sass/node-sass#1766]
Currently blocked on AppVeyor supporting Node 7.
- [x] https://github.com/appveyor/ci/issues/1131
- [x] Windows (https://github.com/sass/node-sass-binaries/pull/140)
- [x] OSX (https://github.com/sass/node-sass-binaries/pull/141)
- [x] Linux (https://github.com/sass/node-sass-binaries/pull/141)
- [ ] FreeBSD

**Comment by xzyfer** [comment]
The AppVeyor update is scheduled for the 30th.

@am11 could I possibly bother you to build the Windows Node 7 binaries for 3.10.1?

**Comment by am11** [comment]
Hey @xzyfer, :)
I have built node-sass current master (bd6d7a3) with v7.0.0 x86 and x64, and found two failing tests with both:

```cmd
  5906 passing (2m)
  322 pending
  2 failing

  1) cli node-sass sass/ --output css/ should not error if output directory is a symlink:
     Error: EEXIST: file already exists, mkdir 'C:\Users\Adeel\Source\Repos\node-sass\test\fixtures\input-directory\css'
      at Object.fs.mkdirSync (fs.js:846:18)
      at Context.<anonymous> (C:\Users\Adeel\Source\Repos\node-sass\test\cli.js:582:10)
      at callFnAsync (C:\Users\Adeel\Source\Repos\node-sass\node_modules\mocha\lib\runnable.js:349:8)
      at Test.Runnable.run (C:\Users\Adeel\Source\Repos\node-sass\node_modules\mocha\lib\runnable.js:301:7)
      at Runner.runTest (C:\Users\Adeel\Source\Repos\node-sass\node_modules\mocha\lib\runner.js:422:10)
      at C:\Users\Adeel\Source\Repos\node-sass\node_modules\mocha\lib\runner.js:528:12
      at next (C:\Users\Adeel\Source\Repos\node-sass\node_modules\mocha\lib\runner.js:342:14)
      at C:\Users\Adeel\Source\Repos\node-sass\node_modules\mocha\lib\runner.js:352:7
      at next (C:\Users\Adeel\Source\Repos\node-sass\node_modules\mocha\lib\runner.js:284:14)
      at Immediate.<anonymous> (C:\Users\Adeel\Source\Repos\node-sass\node_modules\mocha\lib\runner.js:320:5)

  2) cli node-sass --follow --output output-dir input-dir should compile with the --follow option:
     Error: EEXIST: file already exists, mkdir 'C:\Users\Adeel\Source\Repos\node-sass\test\fixtures\follow\input-dir'
      at Object.fs.mkdirSync (fs.js:846:18)
      at Context.<anonymous> (C:\Users\Adeel\Source\Repos\node-sass\test\cli.js:623:10)
      at callFnAsync (C:\Users\Adeel\Source\Repos\node-sass\node_modules\mocha\lib\runnable.js:349:8)
      at Test.Runnable.run (C:\Users\Adeel\Source\Repos\node-sass\node_modules\mocha\lib\runnable.js:301:7)
      at Runner.runTest (C:\Users\Adeel\Source\Repos\node-sass\node_modules\mocha\lib\runner.js:422:10)
      at C:\Users\Adeel\Source\Repos\node-sass\node_modules\mocha\lib\runner.js:528:12
      at next (C:\Users\Adeel\Source\Repos\node-sass\node_modules\mocha\lib\runner.js:342:14)
      at C:\Users\Adeel\Source\Repos\node-sass\node_modules\mocha\lib\runner.js:352:7
      at next (C:\Users\Adeel\Source\Repos\node-sass\node_modules\mocha\lib\runner.js:284:14)
      at Immediate.<anonymous> (C:\Users\Adeel\Source\Repos\node-sass\node_modules\mocha\lib\runner.js:320:5)



npm ERR! Test failed.  See above for more details.
```

Is it still good to go? I will send a PR to binaries repo afterwards.

**Comment by xzyfer** [comment]
Life saver @am11.

I think those tests are due to the test suit not cleaning up after itself properly. Nothing to worry about.

**Comment by marioanton** [comment]
isn´t possible to speed this up a bit ? :)

**Comment by nikolowry** [comment]
Just giving a heads up that ArchLinux updated to 7.0.0 today. So there might be an influx of Linux devs opening/adding-to issues in the next couple days if a new release doesn't happen.  Any eta?

Regardless thanks for maintaining one of the most important packages in the Node-ecosystem. I'll just `sudo pacman -U /var/cache/pacman/pkg/nodejs-6.9.1-1-x86_64.pkg.tar.xz` for now.

**Comment by tleunen** [comment]
Looks like node 7 is available on appveyor: http://help.appveyor.com/discussions/suggestions/1132-make-nodejs-7-available

**Comment by xzyfer** [comment]
Thanks for the heads up @nikolowry.

It's worthing noting that the latest node-sass will install and work perfectly fine on Node 7. This is largely a meta issue so we know when to update some copy and CI config.

**Comment by nikolowry** [comment]
@xzyfer I didn't initially "rm -rf node_modules && npm install" after update. Just went directly to my project repo dir and ran `npm run serve` - which is when I saw the unsupported version note.  

So just user error! Thanks again

**Comment by xzyfer** [comment]
@nikolowry correct. You should always do a fresh install when change Node version or environments (i.e. mounting into a container). This is because native extensions are compiled against the current os and Node version.

**Comment by anaibol** [comment]
![](https://media.giphy.com/media/9QrNWBKvBpCw0/giphy.gif)

**Comment by kyrylkov** [comment]
@anaibol 3.11.1 is there already https://www.npmjs.com/package/node-sass

**Comment by anaibol** [comment]
Cool! It says "I Supported Node.js versions 0.10, 0.12, 1, 2, 3, 4, 5, and 6."

**Comment by kyrylkov** [comment]
The latest supports Node.js 7 on all platforms except FreeBSD. See GitHub
release notes.
