### ISSUE TITLE
osx node v7 listed as supported on 3.10.1 but says otherwise

### ISSUE THREAD

**Issue by theskillwithin** [sass/node-sass#1775]
see here it gives error that my enviroment is not supported, then in the provided link 
https://github.com/sass/node-sass/releases/tag/v3.10.1  OSX does provide support for node 7.0.0 here?

```
npm ls node-sass
heartcup@1.2.0 /Users/Austin/Projects/hrtcup
└── node-sass@3.10.1
node -v
v7.0.0
```

```
  hrtcup git:(master) ✗ node-sass src/assets/css/main.sass dist/assets/css/main.css --indented-syntax --sourceMap true --outFile xmain.css
/usr/local/lib/node_modules/node-sass/lib/index.js:13
    throw new Error(errors.unsupportedEnvironment());
    ^

Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (51)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v3.10.0
    at Object.<anonymous> (/usr/local/lib/node_modules/node-sass/lib/index.js:13:11)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/node-sass/bin/node-sass:11:10)
    at Module._compile (module.js:573:32)
➜  hrtcup git:(master) ✗
```

**Comment by xzyfer** [comment]
Native extensions are compiled against the version of Node used when you first installed it. If you change your version of node you need to reinstall your node modules

```
rm -rf node_modules
npm install
```

or rebuild any native extensions you have installed

```
npm rebuild node-sass
```
