### ISSUE TITLE
Install fail on alpine linux - Cannot find module 'mkdirp'

### ISSUE THREAD

**Issue by Ducatel** [sass/node-sass#1794]
Hi everybody,
I have an error when I try to install node-sass by a simple `npm install node-sass`.

## Error log

```
npm install node-sass

> node-sass@3.11.2 install /node_modules/node-sass
> node scripts/install.js

module.js:442
    throw err;
    ^

Error: Cannot find module 'mkdirp'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/node_modules/node-sass/scripts/install.js:7:11)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
npm WARN enoent ENOENT: no such file or directory, open '/package.json'
npm WARN !invalid#1 No description
npm WARN !invalid#1 No repository field.
npm WARN !invalid#1 No README data
npm WARN !invalid#1 No license field.
npm ERR! Linux 4.4.27-moby
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "node-sass"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.11.2 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.11.2 install script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /npm-debug.log
```

## Step to reproduce

To reproduce it easily, you should use a docker alpine image.
```sh
docker run -ti --rm alpine:3.4 sh
apk update && apk add nodejs 
npm init # with default option
npm install node-sass
```

## Extra Information

- OS: `Alpine linux 3.4`
- NPM version :` 3.8.9`
- Node version: `v6.2.0`
- Node Platform : `linux`
- Node architecture: `x64`
- Node Process: 
```
{ http_parser: '2.7.0',
  node: '6.2.0',
  v8: '5.0.71.47',
  uv: '1.9.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '57.1',
  modules: '48',
  openssl: '1.0.2h' }
```

**Comment by xzyfer** [comment]
This is likely a permission issue. Try

```
npm install node-sass --unsafe-perm
```

**Comment by Ducatel** [comment]
It's failing again but with another error stack.
Now I saw that
```
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
````

I will try to add python before

**Comment by xzyfer** [comment]
Yes python and cpp will need to be installed because we don't support
alpine at the moment. So npm will compile node-sass on install. There's a
PR with an alpine dockerfile floating around if want an example. On my
phone now so I cannot link directly.

**Comment by Ducatel** [comment]
Ah ok, I didn't saw you not support directly alpine.
My apologize 😅 

So I have write a docker which build with success node-sass
```sh
docker run -ti --rm alpine:3.4 sh
apk update && apk add nodejs python gcc g++ make
npm init # with default option
npm install node-sass --unsafe-perm # also work with yarn add node-sass
```

So, it's good for me.
Thanks for your help ;)

**Comment by asimqt** [comment]
@xzyfer Are we supporting alpine now? I am having some issues with node:8.2-alpine Docker.

**Comment by tony** [comment]
I'm actually getting this one with [Yarn Workspaces](https://yarnpkg.com/lang/en/docs/workspaces/) (which does some sort of kung-fu with packages).

node 8.9.1
yarn 1.3.2

command

yarn upgrade node-sass@4.6.1

```
yarn upgrade v1.3.2
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Rebuilding all packages...
[1/4] ⠄ uglifyjs-webpack-plugin
[2/4] ⠄ fsevents
[3/4] ⠄ node-sass
[4/4] ⠄ node-sass
error /Users/me/work/develtech/based/ux/node_modules/node-sass: Command failed.
Exit code: 1
Command: node scripts/install.js
Arguments:
Directory: /Users/me/work/develtech/based/ux/node_modules/node-sass
Output:
module.js:538
    throw err;
    ^

Error: Cannot find module 'mkdirp'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/me/work/develtech/based/ux/node_modules/node-sass/scripts/install.js:7:11)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
```
