### ISSUE TITLE
Unable to install node-sass and so gulp-sass on windows x64

### ISSUE THREAD

**Issue by merhawifissehaye** [sass/node-sass#1817]
Followed the guide on https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md with a failed result:

Here are my installation details
- NPM version (`npm -v`): 3.10.9
- Node version (`node -v`): v7.2.0
- Node Process (`node -p process.versions`):
```
{ http_parser: '2.7.0',
  node: '7.2.0',
  v8: '5.4.500.43',
  uv: '1.10.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  modules: '51',
  openssl: '1.0.2j',
  icu: '58.1',
  unicode: '9.0',
  cldr: '30.0.2',
  tz: '2016g' }
```
- Node Platform (`node -p process.platform`): win32
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`): 
```
module.js:472
    throw err;
    ^

Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at [eval]:1:1
    at ContextifyScript.Script.runInThisContext (vm.js:26:33)
    at Object.exports.runInThisContext (vm.js:79:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:571:32)
    at Immediate.<anonymous> (bootstrap_node.js:383:29)
```
- npm node-sass versions (`npm ls node-sass`):
```
`-- (empty)

npm ERR! code 1
```

**Comment by saper** [comment]
Do you have both 32 and 64 bit versions of node?

**Comment by xzyfer** [comment]
The result of npm la s suggesta you haven't got node-sass installed. What's
the contents of your node_modules folder?

**Comment by merhawifissehaye** [comment]
@saper I don't understand. I am using [nvm for windows](https://github.com/coreybutler/nvm-windows) to manage my node installations. The currently active version of node is 7.2.0 (using 64-bit executable)
@xzyfer I tried to install node-sass as `npm install --save node-sass` but I still got an error message:

```
Time Elapsed 00:00:02.01
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\wamp64\www\medium\wp-content\theme
s\medium\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:215:12)
gyp ERR! System Windows_NT 6.1.7600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\wamp64\\www\\medium\
\wp-content\\themes\\medium\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
 "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsas
s_library="
gyp ERR! cwd C:\wamp64\www\medium\wp-content\themes\medium\node_modules\node-sas
s
gyp ERR! node -v v7.2.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN enoent ENOENT: no such file or directory, open 'C:\wamp64\www\medium\wp
-content\themes\medium\package.json'
npm WARN medium No description
npm WARN medium No repository field.
npm WARN medium No README data
npm WARN medium No license field.
npm ERR! Windows_NT 6.1.7600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "--save" "install" "node-sass"
npm ERR! node v7.2.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.13.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.13.0 postinstall script 'node scripts/build.j
s'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\wamp64\www\medium\wp-content\themes\medium\npm-debug.log
```

**Comment by saper** [comment]
@merhawifissehaye Can you post a full log of your installation into gist.github.com ? It is important to check why the download of the node-sass binary file fails.

Also using NVM can be a source of trouble, because the node-sass binary module needs to match the current version of node. Switching node engines after installation will not work and you need to re-install node-sass.

**Comment by mrmartineau** [comment]
I am getting a similar issue on my build server, see part of the error log below, the entire log is here: https://gist.github.com/mrmartineau/64830dd767fd581ee9b03b2abc28effd

```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN tmwsite@0.1.0 license should be a valid SPDX license expression
npm WARN tmwsite@0.1.0 repo should probably be repository.
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\teamcityuser\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i"
npm ERR! node v7.1.0
npm ERR! npm  v4.0.2
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.10.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.10.0 postinstall script 'node scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\BuildAgent\work\33aa7c45146a0267\source\npm-debug.log
```

Any ideas?

**Comment by nicbell** [comment]
@mrmartineau you may have more luck with a node-sass@3.13.0 try updating some deps.

**Comment by pritisolanki** [comment]
I am also getting the same issue 
> npm install sass-loader@3.1.2 node-sass@3.4.2 --save-dev

15309 verbose stack Error: node-sass@3.4.2 postinstall: `node scripts/build.js`
15309 verbose stack Exit status 1
15309 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
15309 verbose stack     at emitTwo (events.js:106:13)
15309 verbose stack     at EventEmitter.emit (events.js:191:7)
15309 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
15309 verbose stack     at emitTwo (events.js:106:13)
15309 verbose stack     at ChildProcess.emit (events.js:191:7)
15309 verbose stack     at maybeClose (internal/child_process.js:877:16)
15309 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15310 verbose pkgid node-sass@3.4.2
15311 verbose cwd C:\ReactApps\ReactWeather
15312 error Windows_NT 10.0.14393
15313 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "sass-loader@3.1.2" "node-sass@3.4.2" "--save-dev"
15314 error node v6.9.1
15315 error npm  v3.10.8
15316 error code ELIFECYCLE
15317 error node-sass@3.4.2 postinstall: `node scripts/build.js`
15317 error Exit status 1
15318 error Failed at the node-sass@3.4.2 postinstall script 'node scripts/build.js'.
15318 error Make sure you have the latest version of node.js and npm installed.
15318 error If you do, this is most likely a problem with the node-sass package,
15318 error not with npm itself.
15318 error Tell the author that this fails on your system:
15318 error     node scripts/build.js
15318 error You can get information on how to open an issue for this project with:
15318 error     npm bugs node-sass
15318 error Or if that isn't available, you can get their info via:
15318 error     npm owner ls node-sass
15318 error There is likely additional logging output above.
15319 verbose exit [ 1, true ]

**Comment by moanrose** [comment]
I had the same issue, downgrading from 3.13.0 to 3.11.1 resolved the issue

**Comment by xzyfer** [comment]
There appear to be separate issues. @pritisolanki you issue is that npm was unable to download the binary from github.

```
node-sass@3.4.2 install C:\ReactApps\ReactWeather\node_modules\node-sass
node scripts/install.js
Cannot download "https://github.com/sass/node-sass/releases/download/v3.4.2/win32-x64-48_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
try setting a proxy via HTTP_PROXY, e.g.

  export HTTP_PROXY=http://example.com:1234
or configure npm proxy via

  npm config set proxy http://example.com:8080
```

**Comment by xzyfer** [comment]
@mrmartineau node-sass v3.10.0 doesn't support node 7. You'll need update to a newer version.

**Comment by xzyfer** [comment]
@pritisolanki you issue is that npm was unable to download the binary from github. This is because v3.4.2 is very old and doesn't support node 6. You'll need update to a newer version.

**Comment by xzyfer** [comment]
@merhawifissehaye node-sass v3.10 does not support Node 7. You'll need to upgrade to a newer version.

**Comment by mrmartineau** [comment]
@xzyfer thanks for your help, I was not aware of the v7 limitation.

**Comment by Zedonboy** [comment]
am get same issue here am using node 6.10
```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\ch
okidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
)
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\are-we-there-yet\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\async-foreach\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\bcrypt-pbkdf\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\asynckit\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\boom\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\combined-stream\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\camelcase-keys\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\cryptiles\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\dashdash\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\delayed-stream\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\delegates\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\extsprintf\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\form-data\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\fstream\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\gauge\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\gaze\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\getpass\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\globule\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\gulp-sass\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\har-validator\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\cross-spawn\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\asn1\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\http-signature\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\hoek\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\is-my-json-valid\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\isexe\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\jodid25519\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\in-publish\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\json-stringify-safe\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\jsprim\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\lodash.mergewith\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\meow\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\nan\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\ecc-jsbn\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\npmlog\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\osenv\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\redent\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\request\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\sass-graph\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\sntp\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\sshpk\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\stdout-stream\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\stringstream\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\strip-indent\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\tar\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\tough-cookie\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\trim-newlines\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\tunnel-agent\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\tweetnacl\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\uuid\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\verror\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\node-gyp\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\which\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\yargs-parser\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\wide-align\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\hawk\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\json-schema\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\gulp-sass\node_modules\asn1\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\gulp-sass\node_modules\combined-stream\package.js
on'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\gulp-sass\node_modules\cross-spawn\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\gulp-sass\node_modules\boom\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\are-we-there-yet\node_modules\readable-stream\pac
kage.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\gulp-sass\node_modules\cryptiles\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\gulp-sass\node_modules\are-we-there-yet\package.j
son'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\gulp-sass\node_modules\delayed-stream\package.jso
n'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\gulp-sass\node_modules\delegates\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\gulp-sass\node_modules\ecc-jsbn\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\gulp-sass\node_modules\form-data\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\gulp-sass\node_modules\extsprintf\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\gulp-sass\node_modules\dashdash\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\gulp-sass\node_modules\gaze\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\gulp-sass\node_modules\fstream\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\gulp-sass\node_modules\har-validator\package.json
'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\gulp-sass\node_modules\hawk\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\gulp-sass\node_modules\hoek\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\gulp-sass\node_modules\asynckit\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\gulp-sass\node_modules\http-signature\package.jso
n'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\gulp-sass\node_modules\is-my-json-valid\package.j
son'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\gulp-sass\node_modules\isexe\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\gulp-sass\node_modules\getpass\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\gulp-sass\node_modules\jodid25519\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\gulp-sass\node_modules\json-schema\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\gulp-sass\node_modules\jsprim\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\gulp-sass\node_modules\in-publish\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\gulp-sass\node_modules\json-stringify-safe\packag
e.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\gulp-sass\node_modules\minimist\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\gulp-sass\node_modules\async-foreach\package.json
'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\gulp-sass\node_modules\node-sass\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\gulp-sass\node_modules\nan\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\gulp-sass\node_modules\qs\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\gulp-sass\node_modules\osenv\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\gulp-sass\node_modules\readable-stream\package.js
on'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\gulp-sass\node_modules\request\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\gulp-sass\node_modules\sntp\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\gulp-sass\node_modules\sass-graph\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\gulp-sass\node_modules\tar\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\gulp-sass\node_modules\tough-cookie\package.json'

npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\gulp-sass\node_modules\uuid\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\gulp-sass\node_modules\verror\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\gulp-sass\node_modules\sshpk\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\gulp-sass\node_modules\which\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\gulp-sass\node_modules\yargs\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\gulp-sass\node_modules\wide-align\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\gulp-sass\node_modules\yargs-parser\package.json'

npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\gulp-sass\node_modules\lodash\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\meow\node_modules\minimist\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\gulp-sass\node_modules\globule\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\stdout-stream\node_modules\isarray\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\request\node_modules\qs\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\globule\node_modules\lodash\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\sshpk\node_modules\assert-plus\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\yargs-parser\node_modules\camelcase\package.json'

npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\sass-graph\node_modules\yargs\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\gulp-sass\node_modules\node-gyp\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Website
s\Vue\Purple Cash\node_modules\stdout-stream\node_modules\readable-stream\packag
e.json'
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\nodejs\\node.exe" "C:\\Users\\Declan\\AppData\\Roaming\\npm\\
node_modules\\npm\\bin\\npm-cli.js" "install" "--unsafe-perm" "node-sass"
npm ERR! node v6.10.0
npm ERR! npm  v4.1.1
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.13.1 postinstall script 'node scripts/build.j
s'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\xampp\htdocs\Websites\Vue\Purple Cash\npm-debug.log
```

**Comment by Zedonboy** [comment]
someone should help am stuck in development..................i cant use gulp, laravel-elixir, webpack..................because of one fucking node-sass :(

**Comment by ponyack** [comment]
I have the same problem.  :(

**Comment by Zedonboy** [comment]
@ponyack i guess yours is build.js failed in node-sass right?

**Comment by ponyack** [comment]
Yeah, I am new to all of this so I am following along with Lynda tutorial on building a website from scratch and i wind up with a gulp-sass error.

I am working through this page

 https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md#installation-problems

**Comment by Zedonboy** [comment]
well i had issues with node-sass,  to be specific.  thats what i can help
you with.  but i think,  gulp-sass needs node-sass. checj the stack-trace
or drop it.

On Nov 2, 2017 3:51 PM, "ponyack" <notifications@github.com> wrote:

Yeah, I am new to all of this so I am following along with Lynda tutorial
on building a website from scratch and i wind up with a gulp-sass error.

I am working through this page

https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md#
installation-problems

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/sass/node-sass/issues/1817#issuecomment-341446378>, or mute
the thread

**Comment by ponyack** [comment]
Hey Thanks!  I am totally new to all of this - I am just trying to learn more about WP - so I am not sure what you mean "checj the stack-trace or drop it."  or how to do that 

I have tried this npm install gulp-sass --save-dev  and npm install node-sass --save-dev

Still get fails

**Comment by Zedonboy** [comment]
most of the time the issue is, network connection is bad,  to download a
 .node binary. even though you have good connection.
so since you are new,  send me your email.  let me see how i can help you
out. Baby Web Dev. :-)

**Comment by Zedonboy** [comment]
by stack_trace i mean those output from console/terminal

**Comment by ponyack** [comment]
Is there messaging on this site?  Not sure I want to drop my email in this thread

**Comment by Zedonboy** [comment]
Hey here's mine zedonboy063@gmail.com.  though mine is a work around

On Nov 2, 2017 4:31 PM, "ponyack" <notifications@github.com> wrote:

Is there messaging on this site? Not sure I want to drop my email in this
thread

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/sass/node-sass/issues/1817#issuecomment-341459715>, or mute
the thread

**Comment by ponyack** [comment]
email sent

**Comment by Zedonboy** [comment]
get my mail?  @ponyack

On Nov 2, 2017 4:46 PM, "ponyack" <notifications@github.com> wrote:

email sent

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/sass/node-sass/issues/1817#issuecomment-341464728>, or mute
the thread

**Comment by faizanalvi** [comment]
Bro you should install python 2.7 and make it run on CMD ;Also Make sure the Python Scripts Runs too in CMD. Then start your Xwamp and Open your Window Powershell As a administrator, put the whole gulp-dev location address ( npm install gulp-sass --save-dev
