### ISSUE TITLE
Micromatch from glob dependency failing to split a string

### ISSUE THREAD

**Issue by akshay-since1987** [sass/node-sass#1835]
Here's my code while trying to generate SASS. This appears to occur only on windows though.
Also raised with micromatch owner [#82](https://github.com/jonschlinkert/micromatch/issues/82) (In case that helps). 
```
const fs = require( 'fs-extra' );
const glob = require( 'glob-fs' )( {gitignore: true} );
const chalk = require( 'chalk' );
const sassImport = require( 'node-sass-import' );
const sass = require( 'node-sass' );
const buildenv = ( function () {
    if ( process.argv[ 2 ] === 'production' ) {
        return true;
    }
} )();

glob.readdirStream( './src/sass/*.scss', {} )
    .on( 'data', function ( file ) {
        sass.render( {
            file: file.relative,
            outFile: file.name + '.css',
            //includePaths: [ 'lib/', 'mod/' ],
            outputStyle: 'compressed',
            sourceMap: buildenv ? true : false
        }, ( error, result ) => {
            if ( error ) {
                console.log( chalk.white.bgRed.bold( 'Sass Compliation' ) );
                console.log( chalk.white.bold( error.formatted ) );
            } else {
                fs.outputFile( './build/css/' + file.name + '.css', result.css, err => {
                    if ( err ) {
                        console.log( chalk.white.bgRed.bold( 'Error writing css file!' ) );
                    } else {
                        console.log( chalk.white.bgGreen.bold( 'Sass Compiled ' + file.basename ) );

                    }
                } );
            }
        } );

    } );

```

Here's the log generated on running in verbose mode. 

```
C:\Users\akshayr2\Desktop\fq-test\node_modules\glob-fs\node_modules\micromatch\l
ib\utils.js:66
    return fp.split('\\').join('/');
             ^

TypeError: Cannot read property 'split' of undefined
    at Object.unixify (C:\Users\akshayr2\Desktop\fq-test\node_modules\glob-fs\no
de_modules\micromatch\lib\utils.js:66:14)
    at Function.matcher (C:\Users\akshayr2\Desktop\fq-test\node_modules\glob-fs\
node_modules\micromatch\index.js:288:19)
    at module.exports (C:\Users\akshayr2\Desktop\fq-test\node_modules\glob-fs\mi
ddleware\include.js:19:10)
    at Object.include (C:\Users\akshayr2\Desktop\fq-test\node_modules\glob-fs\in
dex.js:196:14)
    at Object.setPattern (C:\Users\akshayr2\Desktop\fq-test\node_modules\glob-fs
\index.js:124:10)
    at Object.readdirStream (C:\Users\akshayr2\Desktop\fq-test\node_modules\glob
-fs\lib\readers.js:92:12)
    at Object.<anonymous> (C:\Users\akshayr2\Desktop\fq-test\bin\tasks\sass.js:1
2:6)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)

npm verb lifecycle fq-corporate@2.2.0~sass: unsafe-perm in lifecycle true
npm verb lifecycle fq-corporate@2.2.0~sass: PATH: C:\Program Files\nodejs\node_m
odules\npm\bin\node-gyp-bin;C:\Users\akshayr2\Desktop\fq-test\node_modules\.bin;
C:\Python27\;C:\Python27\Scripts;C:\Windows\system32;C:\Windows;C:\Windows\Syste
m32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\nodejs\;C:
\Program Files\TortoiseSVN\bin;C:\Program Files\Git\cmd;C:\Program Files\Git\min
gw64\bin;C:\Program Files\Git\usr\bin;C:\Ruby23\bin;C:\Users\akshayr2\AppData\Ro
aming\npm
npm verb lifecycle fq-corporate@2.2.0~sass: CWD: C:\Users\akshayr2\Desktop\fq-te
st
npm info lifecycle fq-corporate@2.2.0~sass: Failed to exec sass script
npm verb stack Error: fq-corporate@2.2.0 sass: `node ./bin/tasks/sass && node ./
bin/tasks/postcss`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_mod
ules\npm\lib\utils\lifecycle.js:255:16)
npm verb stack     at emitTwo (events.js:106:13)
npm verb stack     at EventEmitter.emit (events.js:191:7)
npm verb stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_mod
ules\npm\lib\utils\spawn.js:40:14)
npm verb stack     at emitTwo (events.js:106:13)
npm verb stack     at ChildProcess.emit (events.js:191:7)
npm verb stack     at maybeClose (internal/child_process.js:877:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:226:5)
npm verb pkgid fq-corporate@2.2.0
npm verb cwd C:\Users\akshayr2\Desktop\fq-test
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "run" "sass" "--verbose"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! fq-corporate@2.2.0 sass: `node ./bin/tasks/sass && node ./bin/tasks/pos
tcss`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fq-corporate@2.2.0 sass script 'node ./bin/tasks/sass &&
node ./bin/tasks/postcss'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fq-corporate package,

npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/tasks/sass && node ./bin/tasks/postcss
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fq-corporate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fq-corporate
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\akshayr2\Desktop\fq-test\npm-debug.log
```

**Comment by xzyfer** [comment]
This not a node-sass issue. Looks like either glob-fs or micromatch is the cause.

**Comment by akshay-since1987** [comment]
Okay! So as per Micromatch owner, this is not a micromatch issue. Can you please check and verify if this is some issue with your code?
