### ISSUE TITLE
Can't watch bash Windows 10 

### ISSUE THREAD

**Issue by borgchrist1** [sass/node-sass#1860]
My npm `build:styles` works but `watch:styles`  results in error. What I'm I doing wrong?

These are my npm scripts:  

```json
"build:styles": "node-sass --source-map true src/styles/giphy.scss --output public/assets/",
"watch:styles": "node-sass --watch src/styles/giphy.scss public/assets/styles/giphy.css"
```
This is the error from npm:
```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: watch /mnt/c/Users/chris/Documents/GitHub/giphy/src/styles/ EPERM
    at exports._errnoException (util.js:1022:11)
    at FSWatcher.start (fs.js:1306:19)
    at Object.fs.watch (fs.js:1331:11)
    at Gaze._watchDir (/mnt/c/Users/chris/Documents/GitHub/giphy/node_modules/gaze/lib/gaze.js:304:30)
    at /mnt/c/Users/chris/Documents/GitHub/giphy/node_modules/gaze/lib/gaze.js:377:10
    at iterate (/mnt/c/Users/chris/Documents/GitHub/giphy/node_modules/gaze/lib/helper.js:69:5)
    at Object.forEachSeries (/mnt/c/Users/chris/Documents/GitHub/giphy/node_modules/gaze/lib/helper.js:83:3)
    at Gaze._initWatched (/mnt/c/Users/chris/Documents/GitHub/giphy/node_modules/gaze/lib/gaze.js:373:10)
    at Gaze.add (/mnt/c/Users/chris/Documents/GitHub/giphy/node_modules/gaze/lib/gaze.js:192:8)
    at watch (/mnt/c/Users/chris/Documents/GitHub/giphy/node_modules/node-sass/bin/node-sass:257:8)
```

- NPM version (`npm -v`): 4.0.5
- Node version (`node -v`): 7.4.0
- Node Process (`node -p process.versions`): 7.4.0
- Node Platform (`node -p process.platform`): linux
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`):

    ```
    node-sass       4.3.0   (Wrapper)       [JavaScript]
    libsass         3.4.3   (Sass Compiler) [C/C++]
    ```
- npm node-sass versions (`npm ls node-sass`): node-sass@4.3.0

I'm new to this so any help would be appreciated.

**Comment by xzyfer** [comment]
EPERM suggests you're having a permission error

**Comment by borgchrist1** [comment]
Ok. Thank you. I tried with with windows power shell and that worked. So I guess the ubuntu bash promt is missing primission in windows? I will check that out, tanks again.

**Comment by nschonni** [comment]
I think it will depend on the user you're running as in the Bash prompt.

**Comment by vinkla** [comment]
This could be related to this: https://github.com/gulpjs/gulp/issues/660#issuecomment-264718667

[Read more about the bug in Microsoft's release notes.](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes?f=255&MSPPError=-2147217396#build-14942)
