### ISSUE TITLE
node-sass does not properly exclude non-css files

### ISSUE THREAD

**Issue by johnbendi** [sass/node-sass#1867]
Here is the stacktrace of my error:

```
fs.js:906
  return binding.stat(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, stat '~/projects/sample/src/app/qmod/containers/.#qmod.dashboard.component.css'
    at Object.fs.statSync (fs.js:906:18)
    at Graph.addFile (~/projects/sample/node_modules/sass-graph/sass-graph.js:57:18)
    at ~/projects/sample/node_modules/sass-graph/sass-graph.js:47:13
    at arrayEach (~/projects/sample/node_modules/lodash/lodash.js:537:11)
    at Function.forEach (~/projects/sample/node_modules/lodash/lodash.js:9359:14)
    at new Graph (~/projects/sample/node_modules/sass-graph/sass-graph.js:46:7)
    at Object.module.exports.parseDir (~/projects/sample/node_modules/sass-graph/sass-graph.js:148:17)
    at buildGraph (~/projects/sample/node_modules/node-sass/bin/node-sass:240:23)
    at watch (~/projects/sample/node_modules/node-sass/bin/node-sass:249:15)
    at run (~/projects/sample/node_modules/node-sass/bin/node-sass:332:5)
```

As you can see node-sass wrongly includes a temporary ide working file which it should have excluded. Node-sass should also have a way of specifying which files it should include by way of regular expression or some such.

**Comment by xzyfer** [comment]
> As you can see node-sass wrongly includes a temporary ide working file which it should have excluded

I cannot see that from the limited information you've provided. What's the `@import` that's causing this error?

> Node-sass should also have a way of specifying which files it should include by way of regular expression or some such.

No it should not. Node Sass includes .sass, .scss, and .css files. This is part of the language spec and not negotiable. To tell Node Sass where to look for files you set the `includePaths`.
