### ISSUE TITLE
installation failed node-sass 4.5

### ISSUE THREAD

**Issue by coderhawk** [sass/node-sass#1901]
Hi,

I am getting following error while installing node-sass.  I am working behind proxy, so successfully configured proxy and done a npm install jshint without any issues. 
Please help. 

--------------------------------------------------
C:\Dashboard\Research\Angular2\temp>npm install -g node-sass
C:\Users\sandeep.km\AppData\Roaming\npm\node-sass -> C:\Users\sandeep.km\AppData\Roaming\npm\node_modules\node-sass\bin\node-sass

> node-sass@4.5.0 install C:\Users\sandeep.km\AppData\Roaming\npm\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.0/win32-ia32-48_binding.node

assert.js:85
  throw new assert.AssertionError({
  ^
AssertionError: 2235 == 0
    at ClientRequest.onConnect (C:\Users\sandeep.km\AppData\Roaming\npm\node_modules\node-sass\node_modules\tunnel-agent\index.js:159:14)
    at ClientRequest.g (events.js:291:16)
    at emitThree (events.js:116:13)
    at ClientRequest.emit (events.js:194:7)
    at Socket.socketOnData (_http_client.js:395:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "node-sass"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! node-sass@4.5.0 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.5.0 install script 'node scripts/install.js'.
--------------------------------------------------------
- NPM version (`npm -v`): 3.10.10
- Node version (`node -v`): 6.9.5
- Node Process (`node -p process.versions`): 
{ http_parser: '2.7.0',
  node: '6.9.5',
  v8: '5.1.281.89',
  uv: '1.9.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '57.1',
  modules: '48',
  openssl: '1.0.2k' }
- Node Platform (`node -p process.platform`): win32
- Node architecture (`node -p process.arch`): ia32

**Comment by coderhawk** [comment]
Updated npm version to 4+ and reconfigured proxy settings. Successfully installed :)
