### ISSUE TITLE
everytime install new package， must do  npm rebuild

### ISSUE THREAD

**Issue by QuietWind** [sass/node-sass#1916]
```
fs.js:951
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir '/Users/chenhuan/www/65Page/node_modules/node-sass/vendor'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at Object.getInstalledBinaries (/Users/chenhuan/www/65Page/node_modules/node-sass/lib/extensions.js:121:13)
    at foundBinariesList (/Users/chenhuan/www/65Page/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/Users/chenhuan/www/65Page/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/Users/chenhuan/www/65Page/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/Users/chenhuan/www/65Page/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/Users/chenhuan/www/65Page/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
```

```

- NPM version (`npm -v`): 3.10.3
- Node version (`node -v`): 6.5.0
- Node Process (`node -p process.versions`):

> { http_parser: '2.7.0',
  node: '6.5.0',
 v8: '5.1.281.81',
  uv: '1.9.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '57.1',
  modules: '48',
  openssl: '1.0.2h' }

- Node Platform (`node -p process.platform`): darwin
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`): 3.13.1
- npm node-sass versions (`npm ls node-sass`):  3.13.1

everytime, i resolve make `npm rebuild`

**Comment by xzyfer** [comment]
Looks like a permission issue. You can try `npm cache clean`. Also try updating to a newer version of node-sass.
