### ISSUE TITLE
在本地项目根目录下使用npm install命令，node-sass安装失败

### ISSUE THREAD

**Issue by Chenmy0917** [sass/node-sass#1927]
[窗口截屏](http://www.chenmy0917.cn/wp-content/uploads/2017/03/error.png)
[log文件信息](http://www.chenmy0917.cn/wp-content/uploads/2017/03/log.txt)
版本信息：
npm 4.4.1
node v6.10.0

**Comment by ossso** [comment]
97393 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})


大哥，你的系统不对啊

**Comment by xzyfer** [comment]
```
94483 silly postinstall node-sass@4.5.0
94484 info lifecycle node-sass@4.5.0~postinstall: node-sass@4.5.0
94485 verbose lifecycle node-sass@4.5.0~postinstall: unsafe-perm in lifecycle true
94486 verbose lifecycle node-sass@4.5.0~postinstall: PATH: C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;F:\web\baiyunAirport\node_modules\node-sass\node_modules\.bin;F:\web\baiyunAirport\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\MySQL\MySQL Utilities 1.6\;F:\JDK\bin;F:\JDK\jre\bin;E:\matlab\runtime\win64;E:\matlab\bin;E:\matlab\polyspace\bin;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Ruby23-x64\bin;C:\Program Files\Git\bin;C:\Users\Administrator\AppData\Roaming\npm
94487 verbose lifecycle node-sass@4.5.0~postinstall: CWD: F:\web\baiyunAirport\node_modules\node-sass
94488 silly lifecycle node-sass@4.5.0~postinstall: Args: [ '/d /s /c', 'node scripts/build.js' ]
94489 silly lifecycle node-sass@4.5.0~postinstall: Returned: code: 1  signal: null
94490 info lifecycle node-sass@4.5.0~postinstall: Failed to exec postinstall script

...

97395 verbose stack Error: node-sass@4.5.0 postinstall: `node scripts/build.js`
97395 verbose stack Exit status 1
97395 verbose stack     at EventEmitter.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:279:16)
97395 verbose stack     at emitTwo (events.js:106:13)
97395 verbose stack     at EventEmitter.emit (events.js:191:7)
97395 verbose stack     at ChildProcess.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
97395 verbose stack     at emitTwo (events.js:106:13)
97395 verbose stack     at ChildProcess.emit (events.js:191:7)
97395 verbose stack     at maybeClose (internal/child_process.js:877:16)
97395 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
97396 verbose pkgid node-sass@4.5.0
97397 verbose cwd F:\web\baiyunAirport
97398 verbose Windows_NT 6.3.9600
97399 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
97400 verbose node v6.10.0
97401 verbose npm  v4.4.1
97402 error code ELIFECYCLE
97403 error errno 1
97404 error node-sass@4.5.0 postinstall: `node scripts/build.js`
97404 error Exit status 1
97405 error Failed at the node-sass@4.5.0 postinstall script 'node scripts/build.js'.
97405 error Make sure you have the latest version of node.js and npm installed.
97405 error If you do, this is most likely a problem with the node-sass package,
97405 error not with npm itself.
97405 error Tell the author that this fails on your system:
97405 error     node scripts/build.js
97405 error You can get information on how to open an issue for this project with:
97405 error     npm bugs node-sass
97405 error Or if that isn't available, you can get their info via:
97405 error     npm owner ls node-sass
97405 error There is likely additional logging output above.
97406 verbose exit [ 1, true ]
```
