### ISSUE TITLE
Add node 8 support 

### ISSUE THREAD

**Issue by bemon** [sass/node-sass#1945]
node-sass is currently not working with node 8 environment.

**Comment by xzyfer** [comment]
Please define not working? Also Node 8 is not stable we don't officially support it yet, but it should work.

**Comment by bemon** [comment]
When trying to install i got:
```
Failed at the node-sass@3.13.1 postinstall script 'node scripts/build.js'.
```

I think this is configuration issue not node-sass itself.

**Comment by xzyfer** [comment]
You'll need the latest node-sass at a minimum to get Node 8 compilation working.

https://github.com/sass/node-sass/releases/tag/v4.5.2

**Comment by bemon** [comment]
I still have same error:
```
Failed at the node-sass@4.5.2 postinstall script 'node scripts/build.js'.
```

**Comment by xzyfer** [comment]
Can you please produce more of the log? Without knowing exactly what failed there isn't much we can do.

**Comment by bemon** [comment]
From npm log i got only this:

```
11002 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
11002 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
11002 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
11002 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
11003 warn You are using a pre-release version of node and things may not work as expected
11004 verbose If you need help, you may report this error at:
11004 verbose     <https://github.com/npm/npm/issues>
11005 verbose stack Error: node-sass@4.5.2 postinstall: `node scripts/build.js`
11005 verbose stack Exit status 1
11005 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:279:16)
11005 verbose stack     at emitTwo (events.js:125:13)
11005 verbose stack     at EventEmitter.emit (events.js:213:7)
11005 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
11005 verbose stack     at emitTwo (events.js:125:13)
11005 verbose stack     at ChildProcess.emit (events.js:213:7)
11005 verbose stack     at maybeClose (internal/child_process.js:882:16)
11005 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:5)
11006 verbose pkgid node-sass@4.5.2
11007 verbose cwd C:\SourceCodes\Arrow4.1
11008 error Windows_NT 10.0.14393
11009 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
11010 error node v8.0.0-nightly20170405491d59da84
11011 error npm  v4.2.0
11012 error code ELIFECYCLE
11013 error errno 1
11014 error node-sass@4.5.2 postinstall: `node scripts/build.js`
11014 error Exit status 1
11015 error Failed at the node-sass@4.5.2 postinstall script 'node scripts/build.js'.
11015 error Make sure you have the latest version of node.js and npm installed.
```

**Comment by xzyfer** [comment]
There should be more further up. The installation process attempts to downloading a binary, which will fail for Node 8. Then it'll attempt to build the binary locally which will fail if you don't have the appropriate toolchain to compile native extensions (which is what I suspect the error is).

**Comment by bemon** [comment]
I tried to build node-sass but I still get error
```
gyp verb validating download checksum for win-x64/node.lib (6b725cdeac99bc9574a46ee0a468fb08d6fae69f7cbd69569c3e442a85b28220 == 6b725cdeac99bc9574a46ee0a468fb08d6fae69f7cbd69569c3e442a85b28220)
gyp ERR! configure error
gyp ERR! stack Error: 404 status code downloading 32-bit node.lib
```

Clearly its trying to build 32bit node-sass but node v8 doesnt have 32bit builds on theirs servers.

```
gyp http 404 https://nodejs.org/download/nightly/v8.0.0-nightly20170405491d59da84/win-x86/node.lib
```
Any suggestions ?

**Comment by xzyfer** [comment]
That's a node-gyp issue.

**Comment by doodirock** [comment]
Now that Node 8 has been release is there any support for this?

**Comment by nschonni** [comment]
@doodirock you can follow #1985

**Comment by doodirock** [comment]
Thanks @nschonni

**Comment by jasonxia23** [comment]
@bemon Your problem seems to be a network problem. Downloading win-x86/node.lib fails.

**Comment by bemon** [comment]
@jasonxia23 its closed issue now, there was no proper libs on node server when i was using node 8 beta releases. All working now.

**Comment by tom31415** [comment]
For Mac Users:
Had this issue, resolved by having to agree to license agreement on xcodebuild. Run the following to resolve, read carefully and follow instructions. Then:

 sudo xcodebuild -license

**Comment by mehrdadphp** [comment]
update node-sass to 4.7.2
