### ISSUE TITLE
Issue running on Windows

### ISSUE THREAD

**Issue by visualcookie** [sass/node-sass#1957]
Installed `node-sass` globally and get an error while running. Details further below.

**OS:** Windows 8
**Node Version:** 7.9.0

**Console Output:**
```
λ node-sass --include-path scss assets/scss/main.scss assets/css/main.css
C:\Users\dean\AppData\Roaming\npm\node_modules\node-sass\node_modules\scss-tokenizer\lib\entry.js:1
(function (exports, require, module, __filename, __dirname) { import Input from './input';
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\dean\AppData\Roaming\npm\node_modules\node-sass\node_modules\babel-core\lib\api\register\node.js:214:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
```

**Comment by HitomiTenshi** [comment]
I have the same issue and it's driving me nuts!

**Comment by visualcookie** [comment]
@HitomiTenshi Exactly the same for me. Haven't had that yesterday and now it's like 🎉 .

**Comment by floviolleau** [comment]
Yes, I have the same. 
sass-graph just published a new version 2.2.0 (23 hours ago) which contains a new dependency: scss-tokenizer.

**Comment by floviolleau** [comment]
Maybe node-sass should keep the dependency of sass-graph to 2.1.2. So ~2.1.2 instead of ^2.1.2

**Comment by visualcookie** [comment]
@floviolleau Thanks. Thought that there's some 3rd or 4th part involved in this issue. Gonna take an old yarn.lock file of another project. Thank god we have yarn nowadays.

**Comment by floviolleau** [comment]
I use npm :(

**Comment by xzyfer** [comment]
Thanks all for the reports. I've unpublished sass-graph@2.2.0 until I can look into it. Clear your node_modules and npm install to pull down the previous working version.
