### ISSUE TITLE
Error to install in Debian Jessie 8 linux 64

### ISSUE THREAD

**Issue by francisrod01** [sass/node-sass#1972]
* $ npm -v
4.2.0

* $ node -v
v7.10.0

* $ node -p process.version
v7.10.0

* $ node -p process.platform
linux

* $ node -p process.arch
x64

* $ node -p "require('node-sass').info"

```
node-sass	4.5.3	(Wrapper)	[JavaScript]
libsass  	3.5.0.beta.2	(Sass Compiler)	[C/C++]
```

* $ npm ls node-sass

```
healthy-gulp-angular@0.0.0 /home/paneladm/projects/healthy-gulp-angular
├─┬ gulp-sass@1.3.3
│ └── node-sass@2.1.1 
├── UNMET PEER DEPENDENCY karma-chrome-launcher@~0.1.0
├── UNMET PEER DEPENDENCY karma-coffee-preprocessor@~0.1.0
├── UNMET PEER DEPENDENCY karma-firefox-launcher@~0.1.0
├── UNMET PEER DEPENDENCY karma-html2js-preprocessor@~0.1.0
├── UNMET PEER DEPENDENCY karma-jasmine@~0.1.0
├── UNMET PEER DEPENDENCY karma-phantomjs-launcher@~0.1.0
├── UNMET PEER DEPENDENCY karma-requirejs@~0.2.0
├── UNMET PEER DEPENDENCY karma-script-launcher@~0.1.0
└── node-sass@4.5.3 

npm ERR! peer dep missing: karma-jasmine@~0.1.0, required by karma@0.10.10
npm ERR! peer dep missing: karma-requirejs@~0.2.0, required by karma@0.10.10
npm ERR! peer dep missing: karma-coffee-preprocessor@~0.1.0, required by karma@0.10.10
npm ERR! peer dep missing: karma-html2js-preprocessor@~0.1.0, required by karma@0.10.10
npm ERR! peer dep missing: karma-chrome-launcher@~0.1.0, required by karma@0.10.10
npm ERR! peer dep missing: karma-firefox-launcher@~0.1.0, required by karma@0.10.10
npm ERR! peer dep missing: karma-phantomjs-launcher@~0.1.0, required by karma@0.10.10
npm ERR! peer dep missing: karma-script-launcher@~0.1.0, required by karma@0.10.10
```

* Install node-sass:

```
$ npm install
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> node-sass@2.1.1 install /home/paneladm/projects/healthy-gulp-angular/node_modules/gulp-sass/node_modules/node-sass
> node scripts/install.js

Can not download file from https://raw.githubusercontent.com/sass/node-sass-binaries/v2.1.1/linux-x64-node-7.10/binding.node

> node-sass@2.1.1 postinstall /home/paneladm/projects/healthy-gulp-angular/node_modules/gulp-sass/node_modules/node-sass
> node scripts/build.js

module.js:472
    throw err;
    ^

Error: Cannot find module '/home/paneladm/projects/healthy-gulp-angular/node_modules/gulp-sass/node_modules/node-sass/node_modules/pangyp/bin/node-gyp'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3
Build failed

> healthy-gulp-angular@0.0.0 postinstall /home/paneladm/projects/healthy-gulp-angular
> bower install

healthy-gulp-angular@0.0.0 /home/paneladm/projects/healthy-gulp-angular
├─┬ gulp-sass@1.3.3 
│ ├── clone@0.1.19 
│ └─┬ node-sass@2.1.1 
│   ├─┬ chalk@0.5.1 
│   │ ├── ansi-styles@1.1.0 
│   │ ├─┬ has-ansi@0.1.0 
│   │ │ └── ansi-regex@0.2.1 
│   │ ├── strip-ansi@0.3.0 
│   │ └── supports-color@0.2.0 
│   ├── cross-spawn@0.2.9 
│   ├── nan@1.9.0 
│   ├── object-assign@2.1.1 
│   ├─┬ sass-graph@1.3.0 
│   │ ├─┬ glob@4.5.3 
│   │ │ └── minimatch@2.0.10 
│   │ └── lodash@2.4.2 
│   └── shelljs@0.3.0 
├── UNMET PEER DEPENDENCY karma-chrome-launcher@~0.1.0
├── UNMET PEER DEPENDENCY karma-coffee-preprocessor@~0.1.0
├── UNMET PEER DEPENDENCY karma-firefox-launcher@~0.1.0
├── UNMET PEER DEPENDENCY karma-html2js-preprocessor@~0.1.0
├── UNMET PEER DEPENDENCY karma-jasmine@~0.1.0
├── UNMET PEER DEPENDENCY karma-phantomjs-launcher@~0.1.0
├── UNMET PEER DEPENDENCY karma-requirejs@~0.2.0
└── UNMET PEER DEPENDENCY karma-script-launcher@~0.1.0

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@github:pipobscure/fsevents#7dcdf9fa3f8956610fd6f69f72c67bace2de7138 (node_modules/karma/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@0.2.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN karma@0.10.10 requires a peer of karma-jasmine@~0.1.0 but none was installed.
npm WARN karma@0.10.10 requires a peer of karma-requirejs@~0.2.0 but none was installed.
npm WARN karma@0.10.10 requires a peer of karma-coffee-preprocessor@~0.1.0 but none was installed.
npm WARN karma@0.10.10 requires a peer of karma-html2js-preprocessor@~0.1.0 but none was installed.
npm WARN karma@0.10.10 requires a peer of karma-chrome-launcher@~0.1.0 but none was installed.
npm WARN karma@0.10.10 requires a peer of karma-firefox-launcher@~0.1.0 but none was installed.
npm WARN karma@0.10.10 requires a peer of karma-phantomjs-launcher@~0.1.0 but none was installed.
npm WARN karma@0.10.10 requires a peer of karma-script-launcher@~0.1.0 but none was installed.
```

* Trying to Build gulp app dev:

```
r$ gulp build-app-dev
[00:16:23] Using gulpfile ~/projects/healthy-gulp-angular/gulpfile.js
[00:16:23] Starting 'build-app-dev'...
[00:16:23] 'build-app-dev' errored after 310 ms
[00:16:23] Error: `libsass` bindings not found. Try reinstalling `node-sass`?
    at getBinding (/home/paneladm/projects/healthy-gulp-angular/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:22:11)
    at Object.<anonymous> (/home/paneladm/projects/healthy-gulp-angular/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:188:23)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/paneladm/projects/healthy-gulp-angular/node_modules/gulp-sass/index.js:3:17)
```

**Comment by xzyfer** [comment]
node-sass@2.1.1 is very old, and unsupported. It will only work with Node 0.10 or 0.12. Update to the lastest node sass for Node 7 support.

**Comment by francisrod01** [comment]
Thanks @xzyfer, but I install the latest version. The 2.1.1 version is dependency of another package.

**Comment by xzyfer** [comment]
You'll need to update that dependency then. It looks like `gulp-sass` which I also maintain and has a much newer version.

**Comment by francisrod01** [comment]
Thanks, was solved with latest version.
