### ISSUE TITLE
Support for Node 8 (runtime 57)

### ISSUE THREAD

**Issue by paulschreiber** [sass/node-sass#1984]
I updated to Node 8, and node-sass fails:
```
>> Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (57)
>> For more information on which environments are supported please see:
>> https://github.com/sass/node-sass/releases/tag/v4.5.2
```
That release references #1934, which bumps the release to 54. However, Node 8.0.0 is using 57.

Config:
* macOS 10.12.5 (16F73)
* npm 5.0
* node 8.0.0
* platform: darwin
* arch: x64

```
{ http_parser: '2.7.0',
  node: '8.0.0',
  v8: '5.8.283.41',
  uv: '1.11.0',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  openssl: '1.0.2k',
  icu: '59.1',
  unicode: '9.0',
  cldr: '31.0.1',
  tz: '2017b' }
```

```
$ node -p "require('node-sass').info"
/Users/schreipa/.dev/espn-fivethirtyeight/node_modules/node-sass/lib/binding.js:13
      throw new Error(errors.unsupportedEnvironment());
      ^

Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (57)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.5.2
    at module.exports (/Users/schreipa/.dev/espn-fivethirtyeight/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/Users/schreipa/.dev/espn-fivethirtyeight/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at [eval]:1:1
```

```
$ npm ls node-sass
fivethirtyeight@0.1.0 /Users/schreipa/.dev/espn-fivethirtyeight
└─┬ grunt-sass@2.0.0
  └── node-sass@4.5.2 
```

**Comment by nschonni** [comment]
There are no provided binaries, but https://github.com/sass/node-sass/releases/tag/v4.5.3 already fixed the unsupported version message for 57
