### ISSUE TITLE
Cannot download linux-x64-57_binding.node

### ISSUE THREAD

**Issue by AndRvn** [sass/node-sass#1989]
Hello. I have next error:

```
npm WARN prefer global node-gyp@3.6.1 should be installed with -g

> node-sass@4.5.3 install /var/www/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.3/linux-x64-57_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.3/linux-x64-57_binding.node": 

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g. 

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.5.3 postinstall /var/www/node_modules/node-sass
> node scripts/build.js

Building: /home/laradock/.nvm/versions/node/v8.0.0/bin/node /var/www/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/home/laradock/.nvm/versions/node/v8.0.0/bin/node',
gyp verb cli   '/var/www/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.1
gyp info using node@8.0.0 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/var/www/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/var/www/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/var/www/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /var/www/node_modules/which/which.js:89:16
gyp verb `which` failed     at /var/www/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /var/www/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/var/www/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/var/www/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/var/www/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /var/www/node_modules/which/which.js:89:16
gyp verb `which` failed     at /var/www/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /var/www/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21) code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (/var/www/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/var/www/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/var/www/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /var/www/node_modules/which/which.js:89:16
gyp verb `which` failed     at /var/www/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /var/www/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (/var/www/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/var/www/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/var/www/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /var/www/node_modules/which/which.js:89:16
gyp verb `which` failed     at /var/www/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /var/www/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21) code: 'ENOENT' }
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/var/www/node_modules/node-gyp/lib/configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/var/www/node_modules/node-gyp/lib/configure.js:397:16)
gyp ERR! stack     at F (/var/www/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/var/www/node_modules/which/which.js:80:29)
gyp ERR! stack     at /var/www/node_modules/which/which.js:89:16
gyp ERR! stack     at /var/www/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /var/www/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Linux 4.4.0-78-generic
gyp ERR! command "/home/laradock/.nvm/versions/node/v8.0.0/bin/node" "/var/www/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /var/www/node_modules/node-sass
gyp ERR! node -v v8.0.0
gyp ERR! node-gyp -v v3.6.1
gyp ERR! not ok 
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.5.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.5.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

How can I fix it?

**Comment by xzyfer** [comment]
Downgrade to node 7
