### ISSUE TITLE
Problems with Nodejs 8 and/or npm 5 on Linux

### ISSUE THREAD

**Issue by benneq** [sass/node-sass#1994]
I've just updated our build process to Nodejs 8.0.0 and npm 5.0.0 (also tried 5.0.1).

Now it tries to download `linux-x64-57_binding.node` which doesn't exist.

I can't figure out why it tries to download this particular version. I event don't know what those different binding versions mean (I don't care as long as it works).

The build is running on Jenkins with Webpack 2, though build log might look a bit different.

Here's the build log:
```
[INFO] Running 'npm install' in /var/lib/jenkins/workspace/app/webapp/src/main/frontend
[WARNING] npm WARN prefer global node-gyp@3.6.1 should be installed with -g
[INFO] 
[INFO] > websocket@1.0.24 install /var/lib/jenkins/workspace/app/webapp/src/main/frontend/node_modules/websocket
[INFO] > (node-gyp rebuild 2> builderror.log) || (exit 0)
[INFO] 
[INFO] 
[INFO] > node-sass@4.5.3 install /var/lib/jenkins/workspace/app/webapp/src/main/frontend/node_modules/node-sass
[INFO] > node scripts/install.js
[INFO] 
[INFO] Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.3/linux-x64-57_binding.node
[ERROR] Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.3/linux-x64-57_binding.node": 
[ERROR] 
[ERROR] HTTP error 404 Not Found
[ERROR] 
[ERROR] Hint: If github.com is not accessible in your location
[ERROR]       try setting a proxy via HTTP_PROXY, e.g. 
[ERROR] 
[ERROR]       export HTTP_PROXY=http://example.com:1234
[ERROR] 
[ERROR] or configure npm proxy via
[ERROR] 
[ERROR]       npm config set proxy http://example.com:8080
[INFO] 
[INFO] > fsevents@1.1.1 install /var/lib/jenkins/workspace/app/webapp/src/main/frontend/node_modules/fsevents
[INFO] > node install
[INFO] 
[INFO] 
[INFO] > node-sass@4.5.3 postinstall /var/lib/jenkins/workspace/app/webapp/src/main/frontend/node_modules/node-sass
[INFO] > node scripts/build.js
[INFO] 
[INFO] Building: /var/lib/jenkins/workspace/app/webapp/target/node/node /var/lib/jenkins/workspace/app/webapp/src/main/frontend/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
[ERROR] gyp info it worked if it ends with ok
[ERROR] gyp verb cli [ '/var/lib/jenkins/workspace/app/webapp/target/node/node',
[ERROR] gyp verb cli   '/var/lib/jenkins/workspace/app/webapp/src/main/frontend/node_modules/node-gyp/bin/node-gyp.js',
[ERROR] gyp verb cli   'rebuild',
[ERROR] gyp verb cli   '--verbose',
[ERROR] gyp verb cli   '--libsass_ext=',
[ERROR] gyp verb cli   '--libsass_cflags=',
[ERROR] gyp verb cli   '--libsass_ldflags=',
[ERROR] gyp verb cli   '--libsass_library=' ]
[ERROR] gyp info using node-gyp@3.6.1
[ERROR] gyp info using node@8.0.0 | linux | x64
[ERROR] gyp verb command rebuild []
[ERROR] gyp verb command clean []
[ERROR] gyp verb clean removing "build" directory
[ERROR] gyp verb command configure []
[ERROR] gyp verb check python checking for Python executable "python2" in the PATH
[ERROR] gyp verb `which` succeeded python2 /usr/bin/python2
[ERROR] gyp verb check python version `/usr/bin/python2 -c "import platform; print(platform.python_version());"` returned: "2.7.3\n"
[ERROR] gyp verb get node dir no --target version specified, falling back to host node version: 8.0.0
[ERROR] gyp verb command install [ '8.0.0' ]
[ERROR] gyp verb install input version string "8.0.0"
[ERROR] gyp verb install installing version: 8.0.0
[ERROR] gyp verb install --ensure was passed, so won't reinstall if already installed
[ERROR] gyp verb install version is already installed, need to check "installVersion"
[ERROR] gyp verb got "installVersion" 9
[ERROR] gyp verb needs "installVersion" 9
[ERROR] gyp verb install version is good
[ERROR] gyp verb get node dir target node version installed: 8.0.0
[ERROR] gyp verb build dir attempting to create "build" dir: /var/lib/jenkins/workspace/app/webapp/src/main/frontend/node_modules/node-sass/build
[ERROR] gyp verb build dir "build" dir needed to be created? /var/lib/jenkins/workspace/app/webapp/src/main/frontend/node_modules/node-sass/build
[ERROR] gyp verb build/config.gypi creating config file
[ERROR] gyp verb build/config.gypi writing out config file: /var/lib/jenkins/workspace/app/webapp/src/main/frontend/node_modules/node-sass/build/config.gypi
[ERROR] gyp verb config.gypi checking for gypi file: /var/lib/jenkins/workspace/app/webapp/src/main/frontend/node_modules/node-sass/config.gypi
[ERROR] gyp verb common.gypi checking for gypi file: /var/lib/jenkins/workspace/app/webapp/src/main/frontend/node_modules/node-sass/common.gypi
[ERROR] gyp verb gyp gyp format was not specified; forcing "make"
[ERROR] gyp info spawn /usr/bin/python2
[ERROR] gyp info spawn args [ '/var/lib/jenkins/workspace/app/webapp/src/main/frontend/node_modules/node-gyp/gyp/gyp_main.py',
[ERROR] gyp info spawn args   'binding.gyp',
[ERROR] gyp info spawn args   '-f',
[ERROR] gyp info spawn args   'make',
[ERROR] gyp info spawn args   '-I',
[ERROR] gyp info spawn args   '/var/lib/jenkins/workspace/app/webapp/src/main/frontend/node_modules/node-sass/build/config.gypi',
[ERROR] gyp info spawn args   '-I',
[ERROR] gyp info spawn args   '/var/lib/jenkins/workspace/app/webapp/src/main/frontend/node_modules/node-gyp/addon.gypi',
[ERROR] gyp info spawn args   '-I',
[ERROR] gyp info spawn args   '/var/lib/jenkins/.node-gyp/8.0.0/include/node/common.gypi',
[ERROR] gyp info spawn args   '-Dlibrary=shared_library',
[ERROR] gyp info spawn args   '-Dvisibility=default',
[ERROR] gyp info spawn args   '-Dnode_root_dir=/var/lib/jenkins/.node-gyp/8.0.0',
[ERROR] gyp info spawn args   '-Dnode_gyp_dir=/var/lib/jenkins/workspace/app/webapp/src/main/frontend/node_modules/node-gyp',
[ERROR] gyp info spawn args   '-Dnode_lib_file=node.lib',
[ERROR] gyp info spawn args   '-Dmodule_root_dir=/var/lib/jenkins/workspace/app/webapp/src/main/frontend/node_modules/node-sass',
[ERROR] gyp info spawn args   '-Dnode_engine=v8',
[ERROR] gyp info spawn args   '--depth=.',
[ERROR] gyp info spawn args   '--no-parallel',
[ERROR] gyp info spawn args   '--generator-output',
[ERROR] gyp info spawn args   'build',
[ERROR] gyp info spawn args   '-Goutput_dir=.' ]
[ERROR] gyp verb command build []
[ERROR] gyp verb build type Release
[ERROR] gyp verb architecture x64
[ERROR] gyp verb node dev dir /var/lib/jenkins/.node-gyp/8.0.0
[ERROR] gyp ERR! build error 
[ERROR] gyp ERR! stack Error: not found: make
[ERROR] gyp ERR! stack     at getNotFoundError (/var/lib/jenkins/workspace/app/webapp/src/main/frontend/node_modules/which/which.js:13:12)
[ERROR] gyp ERR! stack     at F (/var/lib/jenkins/workspace/app/webapp/src/main/frontend/node_modules/which/which.js:68:19)
[ERROR] gyp ERR! stack     at E (/var/lib/jenkins/workspace/app/webapp/src/main/frontend/node_modules/which/which.js:80:29)
[ERROR] gyp ERR! stack     at /var/lib/jenkins/workspace/app/webapp/src/main/frontend/node_modules/which/which.js:89:16
[ERROR] gyp ERR! stack     at /var/lib/jenkins/workspace/app/webapp/src/main/frontend/node_modules/isexe/index.js:42:5
[ERROR] gyp ERR! stack     at /var/lib/jenkins/workspace/app/webapp/src/main/frontend/node_modules/isexe/mode.js:8:5
[ERROR] gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
[ERROR] gyp ERR! System Linux 4.4.27-x86_64-jb1
[ERROR] gyp ERR! command "/var/lib/jenkins/workspace/app/webapp/target/node/node" "/var/lib/jenkins/workspace/app/webapp/src/main/frontend/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
[ERROR] gyp ERR! cwd /var/lib/jenkins/workspace/app/webapp/src/main/frontend/node_modules/node-sass
[ERROR] gyp ERR! node -v v8.0.0
[ERROR] gyp ERR! node-gyp -v v3.6.1
[ERROR] gyp ERR! not ok 
[ERROR] Build failed with error code: 1
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! errno 1
[ERROR] npm ERR! node-sass@4.5.3 postinstall: `node scripts/build.js`
[ERROR] npm ERR! Exit status 1
[ERROR] npm ERR! 
[ERROR] npm ERR! Failed at the node-sass@4.5.3 postinstall script.
[ERROR] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[ERROR] 
[ERROR] npm ERR! A complete log of this run can be found in:
[ERROR] npm ERR!     /var/lib/jenkins/.npm/_logs/2017-06-01T07_43_36_466Z-debug.log
```

**Comment by gucong3000** [comment]
```shell
> node-sass@4.5.3 install /home/gitlab-runner/builds/ba320957/0/static/account/node_modules/node-sass
> node scripts/install.js

Downloading binary from http://npm.taobao.org/mirrors/node-sass/v4.5.3/linux-x64-57_binding.node
Cannot download "http://npm.taobao.org/mirrors/node-sass/v4.5.3/linux-x64-57_binding.node": 
```

**Comment by xzyfer** [comment]
Please search for issues before opening a new one. Tracking this in #1985.
