### ISSUE TITLE
Constant cryptic error messages

### ISSUE THREAD

**Issue by megamindbrian** [sass/node-sass#2004]
npm WARN prefer global node-gyp@3.6.1 should be installed with -g

> node-sass@4.5.2 install C:\Users\brian.cullinan\Documents\portal\node_modules\node-sass
> node scripts/install.js

module.js:472
    throw err;
    ^

Error: Cannot find module 'code-point-at'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\brian.cullinan\Documents\portal\node_modules\wide-align\node_modules\string-width\index.js:3:19)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
n

**Comment by nschonni** [comment]
Sorry, you didn't follow the issue template, so we can't help you.

**Comment by megamindbrian** [comment]
What makes you think the template would have helped?
