### ISSUE TITLE
TypeError node-sass-magic-importer/dist/index.js:133

### ISSUE THREAD

**Issue by charsdavy** [sass/node-sass#2039]
I use it design my hexo theme, but I find the error:
```
/Users/chars/hexo/node_modules/hexo-renderer-scss/node_modules/node-sass-magic-importer/dist/index.js:133
      if (!hasFilters && this.store[storeKey] && this.store[storeKey].includes(absoluteUrl)) {
                                                                      ^
TypeError: this.store[storeKey].includes is not a function
    at MagicImporter.isInStore (/Users/chars/hexo/node_modules/hexo-renderer-scss/node_modules/node-sass-magic-importer/dist/index.js:133:71)
    at MagicImporter.resolveSync (/Users/chars/hexo/node_modules/hexo-renderer-scss/node_modules/node-sass-magic-importer/dist/index.js:199:16)
    at Object.importer (/Users/chars/hexo/node_modules/hexo-renderer-scss/node_modules/node-sass-magic-importer/dist/index.js:296:26)
    at options.importer (/Users/chars/hexo/node_modules/hexo-renderer-scss/node_modules/node-sass/lib/index.js:331:31)
```
How I can do it? Thanks

**Comment by xzyfer** [comment]
This is a bug with node-sass-magic-importer. Please open an issue there.

**Comment by maoberlehner** [comment]
If others also have the same problem and the Google search leads you to this comment, please update your Node.js environment to at least version 6.x: https://github.com/maoberlehner/node-sass-magic-importer/issues/118#issuecomment-313839539
