### ISSUE TITLE
Error: node-sass@4.5.3 postinstall: `node scripts/build.js`

### ISSUE THREAD

**Issue by mmohamedbasith** [sass/node-sass#2041]
While doing "npm install' , getting error at this step.

Below is the log
```console
6430 silly lifecycle sass-graph@2.2.4~postinstall: no script for postinstall, continuing
6431 silly postinstall node-sass@4.5.3 C:\Local\GWIS\GWIS\node_modules\.staging\node-sass-c4dbd921
6432 info lifecycle node-sass@4.5.3~postinstall: node-sass@4.5.3
6433 verbose lifecycle node-sass@4.5.3~postinstall: unsafe-perm in lifecycle true
6434 verbose lifecycle node-sass@4.5.3~postinstall: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Local\GWIS\GWIS\node_modules\node-sass\node_modules\.bin;C:\Local\GWIS\GWIS\node_modules\.bin;C:\Program Files\Common Files\Microsoft Shared\Microsoft Online Services;C:\Program Files (x86)\Common Files\Microsoft Shared\Microsoft Online Services;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Citrix\ICAService\;C:\Program Files\Citrix\System32\;C:\Program Files\Citrix\Virtual Desktop Agent\;C:\Program Files (x86)\Common Files\Citrix\System32;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\VSShell\Common7\IDE\;C:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files\nodejs\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\;C:\Program Files (x86)\Windows Kits\8.0\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Users\X114946\AppData\Roaming\npm;C:\Program Files (x86)\Microsoft VS Code\bin
6435 verbose lifecycle node-sass@4.5.3~postinstall: CWD: C:\Local\GWIS\GWIS\node_modules\node-sass
6436 silly lifecycle node-sass@4.5.3~postinstall: Args: [ '/d /s /c', 'node scripts/build.js' ]
6437 silly lifecycle node-sass@4.5.3~postinstall: Returned: code: 1  signal: null
6438 info lifecycle node-sass@4.5.3~postinstall: Failed to exec postinstall script
6439 verbose unlock done using C:\Users\X114946\AppData\Roaming\npm-cache\_locks\staging-880cbbef49cd10b4.lock for C:\Local\GWIS\GWIS\node_modules\.staging
6440 silly rollbackFailedOptional Starting
6441 silly rollbackFailedOptional Finishing
6442 silly runTopLevelLifecycles Finishing
6444 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
6445 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
6446 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
6446 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
6446 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
6446 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
6447 verbose stack Error: node-sass@4.5.3 postinstall: `node scripts/build.js`
6447 verbose stack Exit status 1
6447 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
6447 verbose stack     at emitTwo (events.js:106:13)
6447 verbose stack     at EventEmitter.emit (events.js:191:7)
6447 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
6447 verbose stack     at emitTwo (events.js:106:13)
6447 verbose stack     at ChildProcess.emit (events.js:191:7)
6447 verbose stack     at maybeClose (internal/child_process.js:891:16)
6447 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
6448 verbose pkgid node-sass@4.5.3
6449 verbose cwd C:\Local\GWIS\GWIS
6450 error Windows_NT 6.1.7601
6451 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
6452 error node v6.11.0
6453 error npm  v3.10.10
6454 error code ELIFECYCLE
6455 error node-sass@4.5.3 postinstall: `node scripts/build.js`
6455 error Exit status 1
6456 error Failed at the node-sass@4.5.3 postinstall script 'node scripts/build.js'.
6456 error Make sure you have the latest version of node.js and npm installed.
6456 error If you do, this is most likely a problem with the node-sass package,
6456 error not with npm itself.
6456 error Tell the author that this fails on your system:
6456 error     node scripts/build.js
6456 error You can get information on how to open an issue for this project with:
6456 error     npm bugs node-sass
6456 error Or if that isn't available, you can get their info via:
6456 error     npm owner ls node-sass
6456 error There is likely additional logging output above.
6457 verbose exit [ 1, true ]
```

**Comment by nschonni** [comment]
Sorry, you didn't follow the issue template, so we can't help you.

**Comment by Drmzindec** [comment]
This is still an issuer, whether he followed your stupid template or not. Than ks for fuck'all!
