### ISSUE TITLE
Unable to install on debian 8.9

### ISSUE THREAD

**Issue by bzctoons** [sass/node-sass#2067]
Hello, 
I can't install node-sass on a fresh debian install
I'm not sure about what informations tu provides to help
Regards

 node-sass@4.5.3 install /var/www/virtual/****.com/htdocs/public/templates/*****/node_modules/node-sass
> node scripts/install.js

module.js:471
    throw err;
    ^

Error: Cannot find module '/var/www/virtual/****.com/htdocs/public/templates/***/node_modules/node-sass/scripts/install.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3

npm ERR! Linux 4.4.67-1-pve
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "i" "node-sass"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! node-sass@4.5.3 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.5.3 install script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/virtual/123goodies.com/htdocs/public/templates/123goodies/npm-debug.log

**Comment by bzctoons** [comment]
I've found the solution :   npm install --unsafe-perm node-sass
