### ISSUE TITLE
Yarn install.js fails. Windows 10 x64

### ISSUE THREAD

**Issue by phawxby** [sass/node-sass#2076]
Diagnostics
```
>npm -v
5.3.0

>node -v
v8.4.0

>node -p process.versions
{ http_parser: '2.7.0',
  node: '8.4.0',
  v8: '6.0.286.52',
  uv: '1.13.1',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  nghttp2: '1.22.0',
  openssl: '1.0.2l',
  icu: '59.1',
  unicode: '9.0',
  cldr: '31.0.1',
  tz: '2017b' }

>node -p process.platform
win32

>node -p process.arch
x64

> yarn -v
yarn install v0.27.5

> node -p "require('node-sass').info
C:\Users\Z269CJBB\Documents\GitHub\xerox-drupal\node_modules\node-sass\lib\binding.js:13
      throw new Error(errors.unsupportedEnvironment());
      ^

Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (57)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.5.2
    at module.exports (C:\Users\Z269CJBB\Documents\GitHub\xerox-drupal\node_modules\node-sass\lib\binding.js:13:13)
    at Object.<anonymous> (C:\Users\Z269CJBB\Documents\GitHub\xerox-drupal\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at [eval]:1:1

> npm ls node-sass
xerox-drupal@1.0.0 C:\Users\Z269CJBB\Documents\GitHub\xerox-drupal
`-- gulp-sass@3.1.0
  `-- node-sass@4.5.2
```

It appears to be a simple case of the precompiled binary being missing, it's right, the file does not exist.
https://github.com/sass/node-sass/releases/download/v4.5.2/win32-x64-57_binding.node 

```
>npm rebuild node-sass

> node-sass@4.5.2 install C:\Users\Z269CJBB\Documents\GitHub\xerox-drupal\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.2/win32-x64-57_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.2/win32-x64-57_binding.node":

HTTP error 404 Not Found
```

**Comment by phawxby** [comment]
4.5.3 should fix this. The problem is elsewhere
