### ISSUE TITLE
gyp ERR! stack Error: connect ECONNREFUSED 104.20.22.46:443 when installing Node-sass

### ISSUE THREAD

**Issue by kunalgithub** [sass/node-sass#2096]
Behind CORP PROXY - npm config list

````
; cli configs
metrics-registry = "http://registry.npmjs.org/"
scope = ""
user-agent = "npm/5.4.1 node/v6.11.3 win32 x64"

; userconfig C:\Users\ME\.npmrc
http-proxy = "http://BLA"
https-proxy = "http://BLA"
python = "C:\\Python27"
registry = "http://registry.npmjs.org/"
strict-ssl = false
````
-------------------------------------------------
- NPM version (`npm -v`):  -- 5.4.1
- Node version (`node -v`): -- v6.11.3
- Node Process (`node -p process.versions`):  
{ http_parser: '2.7.0',
  node: '6.11.3',
  v8: '5.1.281.107',
  uv: '1.11.0',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  icu: '58.2',
  modules: '48',
  openssl: '1.0.2l' }
- Node Platform (`node -p process.platform`): --> win32
- Node architecture (`node -p process.arch`): --> x64
- node-sass version (`node -p "require('node-sass').info"`): Not Installed 
- npm node-sass versions (`npm ls node-sass`):
npm ERR! missing: node-sass
-------------------------------------------------
I am getting the below error : 

````
npm info lifecycle node-sass@4.5.3~postinstall: node-sass@4.5.3

> node-sass@4.5.3 postinstall C:\Program Files\nodejs\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\node-sass\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --
libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Program Files\\nodejs\\node_modules\\node-sass\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@6.11.3 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "C:\Python27" in the PATH
gyp verb `which` failed Error: not found: C:\Python27
gyp verb `which` failed     at getNotFoundError (C:\Program Files\nodejs\node_modules\node-sass\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Program Files\nodejs\node_modules\node-sass\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Program Files\nodejs\node_modules\node-sass\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Program Files\nodejs\node_modules\node-sass\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Program Files\nodejs\node_modules\node-sass\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Program Files\nodejs\node_modules\node-sass\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15)
gyp verb `which` failed  C:\Python27 { Error: not found: C:\Python27
gyp verb `which` failed     at getNotFoundError (C:\Program Files\nodejs\node_modules\node-sass\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Program Files\nodejs\node_modules\node-sass\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Program Files\nodejs\node_modules\node-sass\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Program Files\nodejs\node_modules\node-sass\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Program Files\nodejs\node_modules\node-sass\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Program Files\nodejs\node_modules\node-sass\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15)
gyp verb `which` failed   stack: 'Error: not found: C:\\Python27\n    at getNotFoundError (C:\\Program Files\\nodejs\\node_modules\\node-sass\\node_modules\\which\\which.js:13:12)\n    at F (C:\\Progr
am Files\\nodejs\\node_modules\\node-sass\\node_modules\\which\\which.js:68:19)\n    at E (C:\\Program Files\\nodejs\\node_modules\\node-sass\\node_modules\\which\\which.js:80:29)\n    at C:\\Program
Files\\nodejs\\node_modules\\node-sass\\node_modules\\which\\which.js:89:16\n    at C:\\Program Files\\nodejs\\node_modules\\node-sass\\node_modules\\isexe\\index.js:42:5\n    at C:\\Program Files\\no
dejs\\node_modules\\node-sass\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:123:15)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb could not find "C:\Python27". checking python launcher
gyp verb could not find "C:\Python27". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp verb check python version `C:\Python27\python.exe -c "import platform; print(platform.python_version());"` returned: "2.7.13\r\n"
gyp verb get node dir no --target version specified, falling back to host node version: 6.11.3
gyp verb command install [ '6.11.3' ]
gyp verb install input version string "6.11.3"
gyp verb install installing version: 6.11.3
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 6.11.3
gyp verb ensuring nodedir is created C:\Users\n029468\.node-gyp\6.11.3
gyp verb created nodedir C:\Users\n029468\.node-gyp\6.11.3
gyp http GET https://nodejs.org/download/release/v6.11.3/node-v6.11.3-headers.tar.gz
gyp WARN install got an error, rolling back install
gyp verb command remove [ '6.11.3' ]
gyp verb remove using node-gyp dir: C:\Users\n029468\.node-gyp
gyp verb remove removing target version: 6.11.3
gyp verb remove removing development files for version: 6.11.3
## _**gyp ERR! configure error
**gyp ERR! stack Error: connect ECONNREFUSED 104.20.22.46:443**_
gyp ERR! stack     at Object.exports._errnoException (util.js:1020:11)
gyp ERR! stack     at exports._exceptionWithHostPort (util.js:1043:20)
gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\node-sass\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_
cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Program Files\nodejs\node_modules\node-sass
gyp ERR! node -v v6.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok**
Build failed with error code: 1
````

When encountering a syntax, or compilation issue:

- [Open an issue on `LibSass`](https://github.com/sass/LibSass/issues/new). You
may link it back here, but any change will be required there, not here

*If you delete this text without following it, your issue will be closed.*

**Comment by saper** [comment]
There should be something earlier indicating why npm cannot fetch your binary. 

But we are unlikely to help you with your connectivity problems.

**Comment by kunalgithub** [comment]
I solved this problem by setting Sass binary path
