### ISSUE TITLE
Can't install node-sass in Windows 10 : %1 is not a valid win32 application

### ISSUE THREAD

**Issue by mathwww** [sass/node-sass#2116]
- NPM version (`npm -v`):
5.5.1
- Node version (`node -v`):
v6.11.4
- Node Process (`node -p process.versions`):

{ http_parser: '2.7.0',
  node: '6.11.4',
  v8: '5.1.281.108',
  uv: '1.11.0',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  icu: '58.2',
  modules: '48',
  openssl: '1.0.2l' }

- Node Platform (`node -p process.platform`):

win32
- Node architecture (`node -p process.arch`):
x64

- node-sass version (`node -p "require('node-sass').info"`):

module.js:471
    throw err;
    ^

Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at [eval]:1:1
    at ContextifyScript.Script.runInThisContext (vm.js:25:33)
    at Object.runInThisContext (vm.js:97:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:570:32)
    at evalScript (bootstrap_node.js:347:27)

- npm node-sass versions (`npm ls node-sass`):

`-- (empty)

My log are files attached.
[npm.log](https://github.com/sass/node-sass/files/1387706/npm.log)

[npm.err.log](https://github.com/sass/node-sass/files/1387724/npm.err.log)

[2017-10-16T13_42_37_626Z-debug.log](https://github.com/sass/node-sass/files/1387735/2017-10-16T13_42_37_626Z-debug.log)

**Comment by Deilan** [comment]
Tried to install with `--verbose` option. Here's what I've found in the logs:
```
Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-57_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-57_binding.node":

HTTP error 404 Not Found
```

Seems that after failing to download it tries to build bindings, but fails due to absent dependencies.

**Comment by TFAstudio** [comment]
> Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-57_binding.node
> Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-57_binding.node":
> HTTP error 404 Not Found

That's the same error I get in Windows 7 64-bit (trying to create a Foundation web project via "foundation new"). Not a great start to using Foundation framework.

**Comment by nschonni** [comment]
@Deilan and @TFAstudio your issue is related to https://github.com/sass/node-sass/issues/2034
I'm deleting your comments as they are unrelated to the issue you're posting on

**Comment by nschonni** [comment]
@mathwww did you try this again in a clean directory after clearing the NPM cache? From the logs, it looks like something was corrupted in your install
> Binary found at D:\Users\mmsousa\node_modules\node-sass\vendor\win32-x64-48\binding.node
Testing binary
Binary has a problem: Error: %1 não é um aplicativo Win32 válido.
\\?\D:\Users\mmsousa\node_modules\node-sass\vendor\win32-x64-48\binding.node
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at module.exports (D:\Users\mmsousa\node_modules\node-sass\lib\binding.js:19:10)
    at Object.<anonymous> (D:\Users\mmsousa\node_modules\node-sass\lib\index.js:14:35)

**Comment by nschonni** [comment]
This seems very similar to https://github.com/sass/node-sass/issues/2101
