### ISSUE TITLE
Compile error error: no type named 'GCEpilogueCallback' in 'v8::Isolate' 

### ISSUE THREAD

**Issue by michelevirgilio** [sass/node-sass#2150]
I've this error:

In file included from ../src/binding.cpp:1:
../node_modules/nan/nan.h:602:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:608:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback) {
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:613:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:619:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback) {
      ~~~~~~~~~~~~~^
4 errors generated.
make: *** [Release/obj.target/binding/src/binding.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/michelevirgilio/Dropbox/SharedMOVE/Proj/ionic/bancando/bancando2/node_modules/gulp-sass/node_modules/node-sass/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/bin/node" "/Users/michelevirgilio/Dropbox/SharedMOVE/Proj/ionic/bancando/bancando2/node_modules/gulp-sass/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/michelevirgilio/Dropbox/SharedMOVE/Proj/ionic/bancando/bancando2/node_modules/gulp-sass/node_modules/node-sass
gyp ERR! node -v v8.9.1
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok 
Build failed
npm WARN bancando2@1.1.1 No repository field.
npm WARN bancando2@1.1.1 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.4.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.4.2 postinstall script.


npm -v
5.5.1
node -v
v8.9.1
node -p process.versions
{ http_parser: '2.7.0',
  node: '8.9.1',
  v8: '6.1.534.47',
  uv: '1.15.0',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  nghttp2: '1.25.0',
  openssl: '1.0.2m',
  icu: '59.1',
  unicode: '9.0',
  cldr: '31.0.1',
  tz: '2017b' }

node -p process.platform
darwin

node -p process.arch
x64

node -p "require('node-sass').info"
module.js:538
    throw err;
    ^

Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at [eval]:1:1
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at Object.runInThisContext (vm.js:139:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:635:30)
    at evalScript (bootstrap_node.js:462:27)

npm ls node-sass
bancando2@1.1.1 /Users/michelevirgilio/Dropbox/SharedMOVE/Proj/ionic/bancando/bancando2
└─┬ UNMET DEPENDENCY gulp-sass@2.1.1
  └── UNMET DEPENDENCY node-sass@3.4.2 

npm ERR! missing: gulp-sass@2.1.1, required by bancando2@1.1.1
npm ERR! missing: node-sass@3.4.2, required by gulp-sass@2.1.1



any clue please?
Thanks

**Comment by nschonni** [comment]
You'll need to upgrade your version of node-sass to support Node 8, or downgrade your version of Node to support that version of node-sass.
