### ISSUE TITLE
I get this error when running "Gulp".

### ISSUE THREAD

**Issue by drojas002** [sass/node-sass#2172]
[17:53:56] Using gulpfile ~\predix\front_end\pre
[17:53:56] Starting 'default'...
[17:53:56] Starting 'compile:sass'...
[17:53:56] 'compile:sass' errored after 17 ms
[17:53:56] Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (module.
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Administrato
:187:21)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)

**Comment by nschonni** [comment]
Sorry, you didn't follow the issue template, so we can't help you.
