### ISSUE TITLE
Error While installing npm install in ionic3 

### ISSUE THREAD

**Issue by sreejithmv** [sass/node-sass#2187]
- NPM version (`npm -v`):5.3.0
- Node version (`node -v`):8.2.1
- Node Process (`node -p process.versions`):{ http_parser: '2.7.0',
  node: '8.2.1',
  v8: '5.8.283.41',
  uv: '1.13.1',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  openssl: '1.0.2l',
  icu: '59.1',
  unicode: '9.0',
  cldr: '31.0.1',
  tz: '2017b' }
- Node Platform (`node -p process.platform`):win32
- Node architecture (`node -p process.arch`):ia32
- node-sass version (`node -p "require('node-sass').info"`): error
- npm node-sass versions (`npm ls node-sass`): error

I am getting below error while  i am trying to install 

```npm WARN deprecated babili@0.1.2: babili has been renamed to babel-minify. Please update to babel-minify
npm WARN deprecated babel-preset-babili@0.1.4: babili has been renamed to babel-minify. Please update to babel-preset-minify
npm WARN deprecated object-keys@0.2.0: Please update to the latest object-keys

> node-sass@4.5.3 install D:\Mobile Apps\ShipPartner\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.3/win32-ia32-57_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.3/win32-ia32-57_binding.node":

tunneling socket could not be established, statusCode=407
Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> uglifyjs-webpack-plugin@0.4.6 postinstall D:\Mobile Apps\ShipPartner\node_modules\uglifyjs-webpack-plugin
> node lib/post_install.js
> node-sass@4.5.3 postinstall D:\Mobile Apps\ShipPartner\node_modules\node-sass
> node scripts/build.js

Building: D:\Applns\nodejs\node.exe D:\Mobile Apps\ShipPartner\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'D:\\Applns\\nodejs\\node.exe',
gyp verb cli   'D:\\Mobile Apps\\ShipPartner\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.2.1 | win32 | ia32
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (D:\Mobile Apps\ShipPartner\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\Mobile Apps\ShipPartner\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\Mobile Apps\ShipPartner\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\Mobile Apps\ShipPartner\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\Mobile Apps\ShipPartner\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\Mobile Apps\ShipPartner\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (D:\Mobile Apps\ShipPartner\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\Mobile Apps\ShipPartner\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\Mobile Apps\ShipPartner\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\Mobile Apps\ShipPartner\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\Mobile Apps\ShipPartner\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\Mobile Apps\ShipPartner\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (D:\\Mobile Apps\\ShipPartner\\node_modules\\which\\which.js:13:12)\n    at F (D:\\Mobile Apps\\ShipPartner\\node_modules\\which\\which.js:68:19)\n    at E (D:\\Mobile Apps\\ShipPartner\\node_modules\\which\\which.js:80:29)\n    at D:\\Mobile Apps\\ShipPartner\\node_modules\\which\\which.js:89:16\n    at D:\\Mobile Apps\\ShipPartner\\node_modules\\isexe\\index.js:42:5\n    at D:\\Mobile Apps\\ShipPartner\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:152:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python D:\Applns\Python\Python36\python.EXE
gyp verb check python version `D:\Applns\Python\Python36\python.EXE -c "import platform; print(platform.python_version());"` returned: "3.6.2\r\n"
gyp verb could not find "D:\Applns\Python\Python36\python.EXE". checking python launcher
gyp verb could not find "D:\Applns\Python\Python36\python.EXE". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "D:\Applns\Python\Python36\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (D:\Mobile Apps\ShipPartner\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (D:\Mobile Apps\ShipPartner\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at D:\Mobile Apps\ShipPartner\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "D:\\Applns\\nodejs\\node.exe" "D:\\Mobile Apps\\ShipPartner\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd D:\Mobile Apps\ShipPartner\node_modules\node-sass
gyp ERR! node -v v8.2.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm WARN @ionic-native/barcode-scanner@4.5.2 requires a peer of @ionic-native/core@^4.2.0 but none was installed.
npm WARN @ionic-native/camera@4.5.2 requires a peer of @ionic-native/core@^4.2.0 but none was installed.
npm WARN @ionic-native/document-viewer@4.5.2 requires a peer of @ionic-native/core@^4.2.0 but none was installed.
npm WARN @ionic-native/geolocation@4.5.2 requires a peer of @ionic-native/core@^4.2.0 but none was installed.
npm WARN @ionic-native/google-maps@4.5.2 requires a peer of @ionic-native/core@^4.2.0 but none was installed.
npm WARN @ionic-native/in-app-browser@4.5.2 requires a peer of @ionic-native/core@^4.2.0 but none was installed.
npm WARN @ionic-native/keyboard@4.5.2 requires a peer of @ionic-native/core@^4.2.0 but none was installed.
npm WARN @ionic-native/photo-viewer@4.5.2 requires a peer of @ionic-native/core@^4.2.0 but none was installed.
npm WARN @ionic-native/push@4.5.2 requires a peer of @ionic-native/core@^4.2.0 but none was installed.
npm WARN ionic-angular@3.6.0 requires a peer of @angular/common@4.1.3 but none was installed.
npm WARN ionic-angular@3.6.0 requires a peer of @angular/compiler@4.1.3 but none was installed.
npm WARN ionic-angular@3.6.0 requires a peer of @angular/compiler-cli@4.1.3 but none was installed.
npm WARN ionic-angular@3.6.0 requires a peer of @angular/core@4.1.3 but none was installed.
npm WARN ionic-angular@3.6.0 requires a peer of @angular/forms@4.1.3 but none was installed.
npm WARN ionic-angular@3.6.0 requires a peer of @angular/http@4.1.3 but none was installed.
npm WARN ionic-angular@3.6.0 requires a peer of @angular/platform-browser@4.1.3 but none was installed.
npm WARN ionic-angular@3.6.0 requires a peer of @angular/platform-browser-dynamic@4.1.3 but none was installed.
npm WARN ionic-img-viewer@2.9.0 requires a peer of ionic-angular@~3.9.0 but none was installed.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.5.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.5.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.```

**Comment by amenks** [comment]
[node-sass/lib/extensions.js](https://github.com/sass/node-sass/blob/master/lib/extensions.js) line 242:
` 'https://github.com/sass/node-sass/releases/download'`

leads to error 404.
May be this is the problem.

**Comment by xzyfer** [comment]
Please read the issue template. You have a version mismatch between node
sass and bide. Downgrade node or upgrade node sass.

**Comment by sreejithmv** [comment]
i am trying to install node-sass@4.5.3 and while i checking in https://github.com/sass/node-sass/releases for supporting node version its saying this will support node 8. My node version is 8.2.1..

**Comment by xzyfer** [comment]
```
tunneling socket could not be established, statusCode=407
Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080
```

Looks like you're firewall may be blocking our binary download. Please check your proxy settings.
