### ISSUE TITLE
Node Sass does not yet support your current environment: Windows 64-bit

### ISSUE THREAD

**Issue by BasmaRadadi** [sass/node-sass#2191]
Hello every body i have an error (in below) i am instaling Jhipster microservice on windows 10 i pursue this tutorial  link [https://www.youtube.com/watch?v=NdcnpD-GpZ4&lc=z23idtur5wunt55ho04t1aokgqw4wnpuoog3nhjxt2zlbk0h00410.1513606360876224](url)
I am in the level 13min18sec in that video : when i execute ./gradle to configure the gateway it show me this errors , i need help

`PS C:\Users\Omar\Desktop\MicroServiceJhipsterRADADIBasma\MicroServicesBR2\gateway> ./gradlew

> Task :yarn_install
yarn install v0.19.1
[1/4] Resolving packages...
success Already up-to-date.
$ webdriver-manager update
[17:36:18] I/update - chromedriver: file exists C:\Users\Omar\Desktop\MicroServiceJhipsterRADADIBasma\MicroServicesBR2\gateway\node_modules\webdriver-manager\selenium\chromedriver_2.34.zip
[17:36:18] I/update - chromedriver: unzipping chromedriver_2.34.zip
[17:36:18] I/update - chromedriver: chromedriver_2.34.exe up to date
[17:36:18] I/update - selenium standalone: file exists C:\Users\Omar\Desktop\MicroServiceJhipsterRADADIBasma\MicroServicesBR2\gateway\node_modules\webdriver-manager\selenium\selenium-server-standalone-3.8.1.jar
[17:36:18] I/update - selenium standalone: selenium-server-standalone-3.8.1.jar up to date
[17:36:19] I/update - geckodriver: file exists C:\Users\Omar\Desktop\MicroServiceJhipsterRADADIBasma\MicroServicesBR2\gateway\node_modules\webdriver-manager\selenium\geckodriver-v0.19.1.zip
[17:36:19] I/update - geckodriver: unzipping geckodriver-v0.19.1.zip
[17:36:19] I/update - geckodriver: geckodriver-v0.19.1.exe up to date
Done in 3.43s.

> Task :gulpConstantDev
C:\Users\Omar\Desktop\MicroServiceJhipsterRADADIBasma\MicroServicesBR2\gateway\node_modules\node-sass\lib\binding.js:13
      throw new Error(errors.unsupportedEnvironment());
      ^

Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (57)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v3.13.1
    at module.exports (C:\Users\Omar\Desktop\MicroServiceJhipsterRADADIBasma\MicroServicesBR2\gateway\node_modules\node-sass\lib\binding.js:13:13)
    at Object.<anonymous> (C:\Users\Omar\Desktop\MicroServiceJhipsterRADADIBasma\MicroServicesBR2\gateway\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Omar\Desktop\MicroServiceJhipsterRADADIBasma\MicroServicesBR2\gateway\node_modules\gulp-sass\index.js:187:21)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':gulpConstantDev'.
> Process 'command 'node'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s
6 actionable tasks: 5 executed, 1 up-to-date`

**Comment by nschonni** [comment]
Sorry, you didn't follow the issue template, so we can't help you. The answer is included there

**Comment by BasmaRadadi** [comment]
@nschonni  Sorry i didn't get it , i am a biginner here so please can u explain what u mean please what's wrong with my issue , thnks for ur time ^^

**Comment by salmanulfaris** [comment]
I have the same problem 
**Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (57**
@nschonni Can you please explain what you meant?

**Comment by xzyfer** [comment]
@salmanulfaris you need to update your node-sass version to a version that supports (57) Node 9. That's 4.7.2.

**Comment by S2Gteam** [comment]
Use Windows | x86 & x64 | 
> 0.10, 0.12, 1, 2, 3, 4, 5, 6,7
 **Node**
Downgrade Node.js version if you have upgraded to higher than 7

**Comment by badcop666** [comment]
@nschonni that's a fairly un-helpful approach. Could you perhaps point out constructively to @BasmaRadadi so he can use the correct template? It's all about building the community then instead of shutting people down.

Likewise @S2Gteam - that's not a bad start, but it's not extremely helpful, how do you tell the node version? how do you downgrade?

Come on people! Let's be helpful - sitting facing a screen shouldn't mean you forget you are dealing with people. Cheers.

**Comment by nschonni** [comment]
We close these issues because if we don't get the information requested in our issue template, we waste alot of time asking for the basics. If someone in this tread is experiencing an issue then please open a new issue and follow the template
