### ISSUE TITLE
Installing Angular IDE

### ISSUE THREAD

**Issue by chaitanyash** [sass/node-sass#2211]
ngide install ~/Development/angular-ide
Installing Angular IDE in: /home/hp/Development/angular-ide
/usr/lib/node_modules/angular-ide/node_modules/rx/dist/rx.js:77
    throw e;
    ^

Error: connect ETIMEDOUT 209.135.140.102:443
    at Object._errnoException (util.js:999:13)
    at _exceptionWithHostPort (util.js:1020:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1207:14)

**Comment by nschonni** [comment]
Sorry, you didn't follow the issue template, so we can't help you.
