### ISSUE TITLE
Gulp-sass is installed but Error: Cannot find module Gulp-sass

### ISSUE THREAD

**Issue by StarboyAP77** [sass/node-sass#2229]
Node Version : v8.9.0
gulp : CLI Version 3.9.1

module.js:538
    throw err;
    ^

Error: Cannot find module 'gulp-sass'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (\gulpfile.js:6:12)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)

**Comment by NataliShip** [comment]
I have the same issue

**Comment by nschonni** [comment]
Sorry, you didn't follow the issue template, so we can't help you.

**Comment by StarboyAP77** [comment]
can you help me with that ? @nschonni

**Comment by ragasjohn** [comment]
Same here
Error: Cannot find module 'gulp-sass'
    at Function.Module._resolveFilename (module.js:557:15)
    at Function.Module._load (module.js:484:25)
    at Module.require (module.js:606:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Yannis\Documents\Repos\VerticlyMicrosite\gulpfile.js:4:14)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
