### ISSUE TITLE
`npm i` success; `yarn install` fail

### ISSUE THREAD

**Issue by iTonyYo** [sass/node-sass#2259]
also check,
- [ ] https://github.com/yarnpkg/yarn/issues/5203
- [ ] https://github.com/sass/libsass/issues/2458

errors,
![image](https://user-images.githubusercontent.com/5499703/34757090-fcbe9cfa-f609-11e7-92e0-219d53321fe9.png)

**Comment by deoxxa** [comment]
Hey @iTonyYo - there's an issue template on this repository. It'd be great if you could follow that template and provide the information it asks for.

Also, instead of a screenshot, could you just paste the text instead? That'll make it easier to work with.

**Comment by saper** [comment]
Definitely, thanks for pointing that out @deoxxa. Also please answer my question from the other bug:

Did you compile node yourself? Can you check config.gypi file in the build directory?

**Comment by mxchange** [comment]
I'm having the exact same issue lately:

```
error An unexpected error occurred: "/home/project/cp/node_modules/node-sass: Command failed.
Exit code: 1
Command: sh
Arguments: -c node scripts/build.js
Directory: /home/project/cp/node_modules/node-sass
Output:
Building: /usr/bin/node /home/project/cp/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/bin/node',
gyp verb cli   '/home/project/cp/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.9.4 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing \"build\" directory
gyp verb command configure []
gyp verb check python checking for Python executable \"python2\" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c \"import platform; print(platform.python_version());\"` returned: \"2.7.12\
\"
gyp verb get node dir no --target version specified, falling back to host node version: 8.9.4
gyp verb command install [ '8.9.4' ]
gyp verb install input version string \"8.9.4\"
gyp verb install installing version: 8.9.4
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check \"installVersion\"
gyp verb got \"installVersion\" 9
gyp verb needs \"installVersion\" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 8.9.4
gyp verb build dir attempting to create \"build\" dir: /home/project/cp/node_modules/node-sass/build
gyp verb build dir \"build\" dir needed to be created? /home/project/cp/node_modules/node-sass/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /home/project/cp/node_modules/node-sass/build/config.gypi
gyp verb config.gypi checking for gypi file: /home/project/cp/node_modules/node-sass/config.gypi
gyp verb common.gypi checking for gypi file: /home/project/cp/node_modules/node-sass/common.gypi
gyp verb gyp gyp format was not specified; forcing \"make\"
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/home/project/cp/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/project/cp/node_modules/node-sass/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/project/cp/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/me/.node-gyp/8.9.4/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/me/.node-gyp/8.9.4',
gyp info spawn args   '-Dnode_gyp_dir=/home/project/cp/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/me/.node-gyp/8.9.4/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/project/cp/node_modules/node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /home/me/.node-gyp/8.9.4
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/project/cp/node_modules/node-sass/build'
  g++ '-DNODE_GYP_MODULE_NAME=libsass' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DLIBSASS_VERSION=\"3.3.6\"' -I/home/me/.node-gyp/8.9.4/include/node -I/home/me/.node-gyp/8.9.4/src -I/home/me/.node-gyp/8.9.4/deps/uv/include -I/home/me/.node-gyp/8.9.4/deps/v8/include -I../src/libsass/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -std=gnu++0x -std=c++0x -fexceptions -frtti -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/src/ast.o.d.raw   -c -o Release/obj.target/libsass/src/libsass/src/ast.o ../src/libsass/src/ast.cpp
make: g++: Command not found
make: *** [Release/obj.target/libsass/src/libsass/src/ast.o] Error 127
src/libsass.target.mk:139: recipe for target 'Release/obj.target/libsass/src/libsass/src/ast.o' failed
make: Leaving directory '/home/project/cp/node_modules/node-sass/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/project/cp/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.10.0-35-generic
gyp ERR! command \"/usr/bin/node\" \"/home/project/cp/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\" \"--verbose\" \"--libsass_ext=\" \"--libsass_cflags=\" \"--libsass_ldflags=\" \"--libsass_library=\"
gyp ERR! cwd /home/project/cp/node_modules/node-sass
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2


```

**Comment by mxchange** [comment]
Maybe something is wrong with my `make`?

```
make -v
GNU Make 4.1
Built for x86_64-pc-linux-gnu
```

**Comment by mauricionr** [comment]
same issue here

```
yarn install v1.5.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > gulp-babel@7.0.0" has unmet peer dependency "babel-core@6 || 7 || ^7.0.0-alpha || ^7.0.0-beta || ^7.0.0-rc".
[4/4] 📃  Building fresh packages...
[11/11] ⠐ electron[10/11] ⠐ node-sass: `which` succeeded python /usr/local/bin/python[-/11] ⠐ waiting...
[-/11] ⠐ waiting...
error An unexpected error occurred: "/Users/mauricionr/workspace/petlove/greyhound/node_modules/gulp-sass/node_modules/node-sass: Command failed.
Exit code: 1
Command: sh
Arguments: -c node scripts/build.js
Directory: /Users/mauricionr/workspace/petlove/greyhound/node_modules/gulp-sass/node_modules/node-sass
Output:
Building: /Users/mauricionr/.asdf/installs/nodejs/8.9.4/bin/node /Users/mauricionr/workspace/petlove/greyhound/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library
=
gyp info it worked if it ends with ok
gyp verb cli [ '/Users/mauricionr/.asdf/installs/nodejs/8.9.4/bin/node',
gyp verb cli   '/Users/mauricionr/workspace/petlove/greyhound/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.9.4 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing \"build\" directory
gyp verb command configure []
gyp verb check python checking for Python executable \"python2\" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/Users/mauricionr/workspace/petlove/greyhound/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/Users/mauricionr/workspace/petlove/greyhound/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/Users/mauricionr/workspace/petlove/greyhound/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /Users/mauricionr/workspace/petlove/greyhound/node_modules/which/which.js:89:16
gyp verb `which` failed     at /Users/mauricionr/workspace/petlove/greyhound/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /Users/mauricionr/workspace/petlove/greyhound/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/Users/mauricionr/workspace/petlove/greyhound/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/Users/mauricionr/workspace/petlove/greyhound/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/Users/mauricionr/workspace/petlove/greyhound/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /Users/mauricionr/workspace/petlove/greyhound/node_modules/which/which.js:89:16
gyp verb `which` failed     at /Users/mauricionr/workspace/petlove/greyhound/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /Users/mauricionr/workspace/petlove/greyhound/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python2\
    at getNotFoundError (/Users/mauricionr/workspace/petlove/greyhound/node_modules/which/which.js:13:12)\
    at F (/Users/mauricionr/workspace/petlove/greyhound/node_modules/which/which.js:68:19)\
    at E (/Users/mauricionr/workspace/petlove/greyhound/node_modules/which/which.js:80:29)\
    at /Users/mauricionr/workspace/petlove/greyhound/node_modules/which/which.js:89:16\
    at /Users/mauricionr/workspace/petlove/greyhound/node_modules/isexe/index.js:42:5\
    at /Users/mauricionr/workspace/petlove/greyhound/node_modules/isexe/mode.js:8:5\
    at FSReqWrap.oncomplete (fs.js:152:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable \"python\" in the PATH
gyp verb `which` succeeded python /usr/local/bin/python
gyp verb check python version `/usr/local/bin/python -c \"import platform; print(platform.python_version());\"` returned: \"3.6.4\
\"
gyp ERR! configure error
gyp ERR! stack Error: Python executable \"/usr/local/bin/python\" is v3.6.4, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at PythonFinder.failPythonVersion (/Users/mauricionr/workspace/petlove/greyhound/node_modules/node-gyp/lib/configure.js:492:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/Users/mauricionr/workspace/petlove/greyhound/node_modules/node-gyp/lib/configure.js:474:14)
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:267:7)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:346:11)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at Socket.emit (events.js:211:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:554:12)
gyp ERR! System Darwin 17.4.0
gyp ERR! command \"/Users/mauricionr/.asdf/installs/nodejs/8.9.4/bin/node\" \"/Users/mauricionr/workspace/petlove/greyhound/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\" \"--verbose\" \"--libsass_ext=\" \"--libsass_cflags=\" \"--libsass_ldflags=\" \"--libsass_library=\"
gyp ERR! cwd /Users/mauricionr/workspace/petlove/greyhound/node_modules/gulp-sass/node_modules/node-sass
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
```

**Comment by mxchange** [comment]
Looks like `sasslint-webpack-plugin` was the culprit, removing it will fix the issue.

**Comment by nschonni** [comment]
@mxchange you're trying to install 3.13.1 (or one of your dependecies is) on Node 8, which isn't supported. Please open a new issue next time and follow the issue instrutions, since this has been reported a bunch of times.

Closing and locking since there has been no response from the original poster
