### ISSUE TITLE
Impossible to compile on web server

### ISSUE THREAD

**Issue by KevinFuret** [sass/node-sass#2308]
I have a problem of compilation on my Plesk web server 

- NPM version = 8.9.3:
- Node version = 5.5.1
- Architecture = Linux 3.16.0-5-amd64:
- node-sass version = 4.8.2:

```
23558 info lifecycle node-sass@4.8.2~install: node-sass@4.8.2
23559 verbose lifecycle node-sass@4.8.2~install: unsafe-perm in lifecycle true
23560 verbose lifecycle node-sass@4.8.2~install: PATH: /opt/plesk/node/8/lib/node_modules/npm/bin/node-gyp-bin:/var/www/vhosts/mleborgne.com/httpdocs/node_modules/node-sass/node_modules/.bin:/var/www/vhosts/mleborgne.com/httpdocs/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
23561 verbose lifecycle node-sass@4.8.2~install: CWD: /var/www/vhosts/mleborgne.com/httpdocs/node_modules/node-sass
23562 silly lifecycle node-sass@4.8.2~install: Args: [ '-c', 'node scripts/install.js' ]
23563 info lifecycle node-sass@4.8.2~install: Failed to exec install script
23564 verbose unlock done using /var/www/vhosts/mleborgne.com/.npm/_locks/staging-b988e6c63c95a29e.lock for /var/www/vhosts/mleborgne.com/httpdocs/node_modules/.staging
23565 warn mleborgne2k18@1.0.0 No license field.
23566 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
23567 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
23568 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
23568 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
23568 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
23568 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
23569 verbose stack Error: node-sass@4.8.2 install: `node scripts/install.js`
23569 verbose stack spawn ENOENT
23569 verbose stack     at ChildProcess.<anonymous> (/opt/plesk/node/8/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
23569 verbose stack     at emitTwo (events.js:126:13)
23569 verbose stack     at ChildProcess.emit (events.js:214:7)
23569 verbose stack     at maybeClose (internal/child_process.js:925:16)
23569 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
23570 verbose pkgid node-sass@4.8.2
23571 verbose cwd /var/www/vhosts/mleborgne.com/httpdocs
23572 verbose Linux 3.16.0-5-amd64
23573 verbose argv "/opt/plesk/node/8/bin/node" "/opt/plesk/node/8/bin/npm" "install"
23574 verbose node v8.9.3
23575 verbose npm  v5.5.1
23576 error file sh
23577 error code ELIFECYCLE
23578 error errno ENOENT
23579 error syscall spawn
23580 error node-sass@4.8.2 install: `node scripts/install.js`
23580 error spawn ENOENT
23581 error Failed at the node-sass@4.8.2 install script.
23581 error This is probably not a problem with npm. There is likely additional logging output above.
23582 verbose exit [ 1, true ]

```

**Comment by xzyfer** [comment]
Are you running as sudo or root? If so you need the --unsafe-perms flag for
npm install.

Also we do not provide pre compiled binaries for arm so you'll need a C++
toolchain to compile the add-on.

In general we recommend using node-sass as a device dependency to avoid
needing to install it on production servers.

**Comment by mjmnagy** [comment]
Same issue here

I am using plesk NPM install. 

Fails not sure how to install it
