### ISSUE TITLE
regarding installation of node-sass 

### ISSUE THREAD

**Issue by srjkrl20011991** [sass/node-sass#2327]
## I am not able to install node-sass
**npm install -g node-sass**

1765 verbose unlock done using C:\Users\suraj.karale\AppData\Roaming\npm-cache\_locks\staging-908c2556e208a959.lock for C:\Users\suraj.karale\AppData\Roaming\npm\node_modules\.staging
1766 verbose stack Error: node-sass@4.8.3 postinstall: `node scripts/build.js`
1766 verbose stack Exit status 1
1766 verbose stack     at EventEmitter.<anonymous> (C:\Users\suraj.karale\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:283:16)
1766 verbose stack     at emitTwo (events.js:126:13)
1766 verbose stack     at EventEmitter.emit (events.js:214:7)
1766 verbose stack     at ChildProcess.<anonymous> (C:\Users\suraj.karale\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
1766 verbose stack     at emitTwo (events.js:126:13)
1766 verbose stack     at ChildProcess.emit (events.js:214:7)
1766 verbose stack     at maybeClose (internal/child_process.js:925:16)
1766 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
1767 verbose pkgid node-sass@4.8.3
1768 verbose cwd C:\Users\suraj.karale
1769 verbose Windows_NT 10.0.14393
1770 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\suraj.karale\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-sass" "-g"
1771 verbose node v8.11.1
1772 verbose npm  v5.8.0
1773 error code ELIFECYCLE
1774 error errno 1
1775 error node-sass@4.8.3 postinstall: `node scripts/build.js`
1775 error Exit status 1
1776 error Failed at the node-sass@4.8.3 postinstall script.
1776 error This is probably not a problem with npm. There is likely additional logging output above.
1777 verbose exit [ 1, true ]

## create project ng new templatesnew --style=scss

and run > **ng serve** 

through an error => 
ERROR in ./node_modules/raw-loader!./node_modules/postcss-loader/lib??embedded!./node_modules/sass-loader/lib/loader.js??ref--8-3!./src/styles.scss
Module build failed: Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\Demo\Angular4\templates\node_modules\sass-loader\lib\loader.js:3:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at loadLoader (D:\Demo\Angular4\templates\node_modules\loader-runner\lib\loadLoader.js:13:17)
    at iteratePitchingLoaders (D:\Demo\Angular4\templates\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (D:\Demo\Angular4\templates\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
    at D:\Demo\Angular4\templates\node_modules\loader-runner\lib\LoaderRunner.js:173:18
ERROR in ./src/app/app.component.scss
Module build failed: Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\Demo\Angular4\templates\node_modules\sass-loader\lib\loader.js:3:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at loadLoader (D:\Demo\Angular4\templates\node_modules\loader-runner\lib\loadLoader.js:13:17)
    at iteratePitchingLoaders (D:\Demo\Angular4\templates\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (D:\Demo\Angular4\templates\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
    at D:\Demo\Angular4\templates\node_modules\loader-runner\lib\LoaderRunner.js:173:18

**Comment by srjkrl20011991** [comment]
can you please mention the solution?

**Comment by xzyfer** [comment]
> npm install --unsafe-perms
