### ISSUE TITLE
Can't get past an error shown by node-sass when running npm-install

### ISSUE THREAD

**Issue by dugajean** [sass/node-sass#2332]
- NPM version (`npm -v`): 2.14.0
- Node version (`node -v`): 0.12.7
- Node Process (`node -p process.versions`):
```
{ http_parser: '2.3',
  node: '0.12.7',
  v8: '3.28.71.19',
  uv: '1.6.1',
  zlib: '1.2.8',
  modules: '14',
  openssl: '1.0.1p' }
```
- Node Platform (`node -p process.platform`): linux
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`): `Error: Cannot find module 'node-sass'`
- npm node-sass versions (`npm ls node-sass`): (empty)

The error looks like this:

```
> node-sass@3.13.1 install /home/vagrant/Code/saas-app/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/node-sass
> node scripts/install.js

/home/vagrant/Code/saas-app/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/node-sass/node_modules/request/node_modules/hawk/node_modules/boom/lib/index.js:5
const Hoek = require('hoek');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/vagrant/Code/saas-app/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/node-sass/node_modules/request/node_modules/hawk/lib/index.js:5:33)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
\
> uws@9.14.0 install /home/vagrant/Code/saas-app/node_modules/laravel-elixir/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/uws
> node-gyp rebuild > build_log.txt 2>&1 || exit 0

npm ERR! Linux 4.4.0-116-generic
npm ERR! argv "node" "/home/vagrant/.nvm/versions/node/v0.12.7/bin/npm" "install" "--unsafe-perm"
npm ERR! node v0.12.7
npm ERR! npm  v2.14.0
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.13.1 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.13.1 install script 'node scripts/install.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/Code/saas-app/npm-debug.log
```

My `packages.json` looks like this:

```
{
	"private": true,
	"devDependencies": {
		"browserify": "^14.4.0",
		"gulp": "^3.8.8",
		"gulp-notify": "~2.2.0",
		"watchify": "^3.9.0"
	},
	"dependencies": {
		"bootstrap-sass": "^3.0.0",
		"ioredis": "^1.9.1",
		"jsonwebtoken": "^5.4.1",
		"laravel-elixir": "^3.0.0",
		"mysql": "^2.11.1",
		"node-env-file": "^0.1.8",
		"shelljs": "^0.5.3",
		"socket.io": "^1.3.7",
		"through": "^2.3.8"
	}
}
```

I have tried using the solution people suggested, but with no success. These solutions suggested using the `--unsafe-perm` flag, clearing cache, using `sudo` to install etc.

A solution would be highly appreciated.

**Comment by xzyfer** [comment]
npm install node-sass@latests

**Comment by mjoppich** [comment]
Since I ran also into this issue:

Reason was versioning conflict of multiple dependencies. Finally removing node_modules and reinstalling solved the issue.
