### ISSUE TITLE
Can not find module noda-sass

### ISSUE THREAD

**Issue by kartheekgadduru** [sass/node-sass#2366]
I getting following error when I am trying to run ng2-file-manager project which is from github using npm start.

Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\IKEA_sales\ng2-file-manager\scripts\lib\css.ts:3:12)
    at Module._compile (module.js:652:30)
    at Object.require.extensions..ts (D:\IKEA_sales\ng2-file-manager\scripts\cmd.js:17:14)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular2-rollup-starter@0.0.56 serve: `node ./scripts/cmd.js serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-rollup-starter@0.0.56 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\gakarthe\AppData\Roaming\npm-cache\_logs\2018-05-03T11_09_20_188Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular2-rollup-starter@0.0.56 start: `npm run serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-rollup-starter@0.0.56 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\gakarthe\AppData\Roaming\npm-cache\_logs\2018-05-03T11_09_20_264Z-debug.log

**Comment by xzyfer** [comment]
Please open an issue with ng2-file-manager
