### ISSUE TITLE
Error rebuilding node-sass on Node v10, Linux x64

### ISSUE THREAD

**Issue by ranggaperwiratama** [sass/node-sass#2377]
```
$ npm -v              
6.0.0
$ node -v
v10.0.0
$ node -p process.versions
{ http_parser: '2.8.1',
  node: '10.0.0',
  v8: '6.6.346.24-node.5',
  uv: '1.20.2',
  zlib: '1.2.11',
  ares: '1.13.0',
  modules: '64',
  nghttp2: '1.31.1',
  napi: '3',
  openssl: '1.1.0h',
  icu: '61.1',
  unicode: '10.0',
  cldr: '33.0',
  tz: '2018c' }
$ node -p process.platform
linux
$ node -p process.arch
x64
```
When trying to rebuild got this error (both using npm rebuild node-sass and deleting node_modules and then use npm install):
```
make: *** [binding.target.mk:115: Release/obj.target/binding/src/binding.o] Error 1
make: Leaving directory '/opt/lampp/htdocs/ng-kondisiadmin/node_modules/node-sass/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/lampp/htdocs/ng-kondisiadmin/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:225:12)
gyp ERR! System Linux 4.14.39-1-MANJARO
gyp ERR! command "/usr/bin/node" "/opt/lampp/htdocs/ng-kondisiadmin/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /opt/lampp/htdocs/ng-kondisiadmin/node_modules/node-sass
gyp ERR! node -v v10.0.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.5.3 (node_modules/node-sass):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.5.3 postinstall: `node scripts/build.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

added 916 packages from 1109 contributors in 135.189s
[!] 43 vulnerabilities found [4698 packages audited]
    Severity: 31 low | 5 moderate | 7 high
    Run `npm audit` for more detail
```

**Comment by nschonni** [comment]
Node 10 isn't supported by that version, either upgrade you node-sass or downgrade your node.

**Comment by xzyfer** [comment]
https://github.com/sass/node-sass/releases/tag/v4.9.0
