### ISSUE TITLE
Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (64)

### ISSUE THREAD

**Issue by AndresBillini** [sass/node-sass#2401]
- NPM version (`npm -v 6.1.0`):
- Node version (`node -v 10.1.0`):
- Node Process (`node -p process.versions`):
- Node Platform (`node -p process.platform`):
- Node architecture (`node -p process.arch`):
- node-sass version (`node -p "require('node-sass').info"`):
- npm node-sass versions (`npm ls node-sass`):

Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (64)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.7.2
    at module.exports (D:\xampp\htdocs\reef\node_modules\node-sass\lib\binding.js:13:13)
    at Object.<anonymous> (D:\xampp\htdocs\reef\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (D:\xampp\htdocs\reef\node_modules\@ionic\app-scripts\dist\core\bundle-components.js:6:16)

**Comment by jaenulton** [comment]
Same problem here.

Some have said to remove modules directory and do npm install (didn't work for me)...
Others have said to simply run npm rebuild node-sass (also didn't work for me).

Very stuck and don't know how to revert to whatever package was working for me yesterday.
