### ISSUE TITLE
Node sass package fails to install (http-signature)

### ISSUE THREAD

**Issue by thebarty** [sass/node-sass#2439]
Hi guys,

just ran into an issue with this package after doing some changes to my codebase.

I can not install this anymore. Neither locally NOR on production, which means that I can't deploy right now... bad stuff!!!

This is the stacktrace on production:
```
v0116
2018-07-07 17:23:29+02:00Error: Cannot find module 'http-signature'
v0116
2018-07-07 17:23:29+02:00 at Function.Module._resolveFilename (module.js:325:15)
v0116
2018-07-07 17:23:29+02:00 at Function.Module._load (module.js:276:25)
v0116
2018-07-07 17:23:29+02:00 at Module.require (module.js:353:17)
v0116
2018-07-07 17:23:29+02:00 at require (internal/module.js:12:17)
v0116
2018-07-07 17:23:29+02:00 at Object.<anonymous> (/app/bundle/programs/server/npm/node_modules/request/request.js:11:21)
v0116
2018-07-07 17:23:29+02:00 at Module._compile (module.js:409:26)
v0116
2018-07-07 17:23:29+02:00 at Object.Module._extensions..js (module.js:416:10)
v0116
2018-07-07 17:23:29+02:00 at Module.load (module.js:343:32)
v0116
2018-07-07 17:23:29+02:00 at Function.Module._load (module.js:300:12)
v0116
2018-07-07 17:23:29+02:00 at Module.require (module.js:353:17)
v0116
2018-07-07 17:23:29+02:00npm ERR! code ELIFECYCLE
v0116
2018-07-07 17:23:29+02:00npm ERR! errno 1
v0116
2018-07-07 17:23:29+02:00npm ERR! node-sass@3.13.1 install: `node scripts/install.js`
v0116
2018-07-07 17:23:29+02:00npm ERR! Exit status 1
v0116
2018-07-07 17:23:29+02:00npm ERR!
v0116
2018-07-07 17:23:29+02:00npm ERR! Failed at the node-sass@3.13.1 install script 'node scripts/install.js'.
v0116
2018-07-07 17:23:29+02:00npm ERR! Make sure you have the latest version of node.js and npm installed.
v0116
2018-07-07 17:23:29+02:00npm ERR! If you do, this is most likely a problem with the node-sass package,
v0116
2018-07-07 17:23:29+02:00npm ERR! not with npm itself.
v0116
2018-07-07 17:23:29+02:00npm ERR! Tell the author that this fails on your system:
v0116
2018-07-07 17:23:29+02:00npm ERR! node scripts/install.js
v0116
2018-07-07 17:23:29+02:00npm ERR! You can get information on how to open an issue for this project with:
v0116
2018-07-07 17:23:29+02:00npm ERR! npm bugs node-sass
v0116
2018-07-07 17:23:29+02:00npm ERR! Or if that isn't available, you can get their info via:
v0116
2018-07-07 17:23:29+02:00npm ERR! npm owner ls node-sass
v0116
2018-07-07 17:23:29+02:00npm ERR! There is likely additional logging output above.
```

Any ideas what to try?

**Comment by nschonni** [comment]
Sorry, 3.13.1 is an old version, I'd suggest updating to the latest
