### ISSUE TITLE
yarn install failed to install node-sass 4.9.2 on Alpine Linux

### ISSUE THREAD

**Issue by iczman** [sass/node-sass#2447]
- NPM version (`npm -v`): 5.5.1
- Node version (`node -v`): v8.9.3
- Node Process (`node -p process.versions`):
{ http_parser: '2.7.1',
  node: '8.9.3',
  v8: '6.1.534.48',
  uv: '1.17.0',
  zlib: '1.2.11',
  ares: '1.13.0',
  modules: '57',
  nghttp2: '1.25.0',
  openssl: '1.0.2o',
  icu: '59.1',
  unicode: '9.0',
  cldr: '31.0.1',
  tz: '2017b' }
- Node Platform (`node -p process.platform`): linux
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`): Error: Cannot find module 'node-sass'
- npm node-sass versions (`npm ls node-sass`): `-- (empty)

```console
yarn install v1.3.2
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "@rails/webpacker > postcss-cssnext@3.1.0" has unmet peer dependency "caniuse-lite@^1.0.30000697".
warning "@rails/webpacker > webpack-assets-manifest@3.0.1" has unmet peer dependency "webpack-sources@^1.0".
warning " > webpack-cli@2.1.5" has unmet peer dependency "webpack@^4.0.0".
warning " > webpack-dev-server@3.1.4" has unmet peer dependency "webpack@^4.0.0-beta.1".
warning "webpack-dev-server > webpack-dev-middleware@3.1.3" has unmet peer dependency "webpack@^4.0.0".
[4/4] Building fresh packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
error /usr/src/app/node_modules/node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: /usr/src/app/node_modules/node-sass
Output:
Building: /usr/bin/node /usr/src/app/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/bin/node',
gyp verb cli   '/usr/src/app/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.7.0
gyp info using node@8.9.3 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/usr/src/app/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/usr/src/app/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/usr/src/app/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /usr/src/app/node_modules/which/which.js:89:16
gyp verb `which` failed     at /usr/src/app/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /usr/src/app/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/usr/src/app/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/usr/src/app/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/usr/src/app/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /usr/src/app/node_modules/which/which.js:89:16
gyp verb `which` failed     at /usr/src/app/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /usr/src/app/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (/usr/src/app/node_modules/which/which.js:13:12)\n    at F (/usr/src/app/node_modules/which/which.js:68:19)\n    at E (/usr/src/app/node_modules/which/which.js:80:29)\n    at /usr/src/app/node_modules/which/which.js:89:16\n    at /usr/src/app/node_modules/isexe/index.js:42:5\n    at /usr/src/app/node_modules/isexe/mode.js:8:5\n    at FSReqWrap.oncomplete (fs.js:152:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (/usr/src/app/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/usr/src/app/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/usr/src/app/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /usr/src/app/node_modules/which/which.js:89:16
gyp verb `which` failed     at /usr/src/app/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /usr/src/app/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (/usr/src/app/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/usr/src/app/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/usr/src/app/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /usr/src/app/node_modules/which/which.js:89:16
gyp verb `which` failed     at /usr/src/app/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /usr/src/app/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python\n    at getNotFoundError (/usr/src/app/node_modules/which/which.js:13:12)\n    at F (/usr/src/app/node_modules/which/which.js:68:19)\n    at E (/usr/src/app/node_modules/which/which.js:80:29)\n    at /usr/src/app/node_modules/which/which.js:89:16\n    at /usr/src/app/node_modules/isexe/index.js:42:5\n    at /usr/src/app/node_modules/isexe/mode.js:8:5\n    at FSReqWrap.oncomplete (fs.js:152:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/usr/src/app/node_modules/node-gyp/lib/configure.js:492:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/src/app/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! stack     at F (/usr/src/app/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/usr/src/app/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/src/app/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/src/app/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/src/app/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Linux 4.16.14
gyp ERR! command "/usr/bin/node" "/usr/src/app/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /usr/src/app/node_modules/node-sass
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
Build failed with error code: 1
```

package.json
```json
{
  "name": "<snipped>",
  "private": true,
  "dependencies": {
    "@rails/webpacker": "4.0.0-pre.2",
    "material-components-web": "0.36.0",
    "normalize.css": "8.0.0"
  },
  "devDependencies": {
    "webpack-cli": "^2.1.4",
    "webpack-dev-server": "3.1.4"
  }
}
```

[yarn.lock](https://pastebin.com/FsYZ63MG)

**Comment by nschonni** [comment]
> gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.

I'm not seeing where Yarn is trying to download the pre-built bindings. Because it can't/isn't doing that, you need to have the node-gyp prerequisites to build yourself https://github.com/nodejs/node-gyp#on-unix

**Comment by xzyfer** [comment]
What version of node sass is trying to be installed? Please provide the
full log file.

**Comment by iczman** [comment]
@xzyfer it's trying to install 4.9.2, the current latest. Could you clarify which log should I provide?

**Comment by iczman** [comment]
For context I'm running webpacker gem for Rails. It uses webpack + package.json (provided on top) to install JS packages. I ran `yarn install` and encountered error above.

**Comment by nottrobin** [comment]
@nschonni do you know why it is that `npm install` downloads the binary, whereas `yarn install` doesn't and tries to built it (often leading to failure)?

**Comment by anhdn** [comment]
you can try. It worked for me
> yarn --cache-folder ~/.my-yarn-cache-dir/

**Comment by chase439** [comment]
I upgraded to the latest webpacker gem and the error went away

```
bundle update webpacker
rails webpacker:binstubs
yarn upgrade @rails/webpacker --latest
yarn upgrade webpack-dev-server --latest
```
https://github.com/rails/webpacker#upgrading

**Comment by absyah** [comment]
> I upgraded to the latest webpacker gem and the error went away
> 
> ```
> bundle update webpacker
> rails webpacker:binstubs
> yarn upgrade @rails/webpacker --latest
> yarn upgrade webpack-dev-server --latest
> ```
> 
> https://github.com/rails/webpacker#upgrading

Confirmed. It works!
