### ISSUE TITLE
Node sass could not find a binding: detecting wrong node version / ABI

### ISSUE THREAD

**Issue by andrebautista** [sass/node-sass#2460]
- NPM version (`npm -v`): 5.6.0
- Node version (`node -v`): v8.11.3
- Node Process (`node -p process.versions`): 
{ http_parser: '2.8.0',
  node: '8.11.3',
  v8: '6.2.414.54',
  uv: '1.19.1',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  nghttp2: '1.32.0',
  napi: '3',
  openssl: '1.0.2o',
  icu: '60.1',
  unicode: '10.0',
  cldr: '32.0',
  tz: '2017c' }
- Node Platform (`node -p process.platform`): darwin 
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`):
node-sass	4.9.2	(Wrapper)	[JavaScript]
libsass  	3.5.4	(Sass Compiler)	[C/C++]
- npm node-sass versions (`npm ls node-sass`):
preact-test@0.0.0 /Users/AndreBautista/client_work/*****/preact-test
└── node-sass@4.9.2

I'm running into an issue trying to debug my webpack configuration with the [node-nightly](https://github.com/hemanth/node-nightly) package. This is not the same issue that can be debugged via `npm rebuild node-sass` I've tried that command and several other things regarding the binaries. I've determined it comes down to node versioning.

My stack trace looks like this:
```
ERROR in ./app/style/index.scss (./node_modules/css-loader??ref--5-1!./node_modules/postcss-loader/lib??ref--5-2!./node_modules/sass-loader/lib/loader.js!./app/style/index.scss)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: Missing binding /Users/andre/client_work/*****/preact-test/node_modules/node-sass/vendor/darwin-x64-64/binding.node
Node Sass could not find a binding for your current environment: OS X 64-bit with Node.js 10.x

Found bindings for the following environments:
  - OS X 64-bit with Node.js 8.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to download the binding for your current environment.
    at module.exports (/Users/andre/client_work/*****/preact-test/node_modules/node-sass/lib/binding.js:15:13)
    at Object.<anonymous> (/Users/andre/client_work/*****/preact-test/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (/Users/andre/client_work/*****/preact-test/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (/Users/andre/client_work/*****/preact-test/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.sassLoader (/Users/andre/client_work/*****/preact-test/node_modules/sass-loader/lib/loader.js:24:22)
```

I dug into `node-sass/lib/extensions.js` to try and see where the error message about `Node.js 10.x` being used when I have node 8.x installed and when I put a log inside `getHumanNodeVersion(abi)` to `console.log(abi)` it alternated and returned:
```
undefined
64
57
undefined
64
...
```
That's as far as I could dig since I'm not exactly sure where ABI is being set but according to node 57 is my version and 64 is the 10.x which may be running on my computer somewhere but not that I'm aware of.

Not sure if something else in my build is calling that version of node somehow?

**Comment by xzyfer** [comment]
Looks like you've got multiple versoy of node in your path. Because
node-gyp spawns nkde in a child process the versions seem to be switching.

You can confirm this by changing your console.log to process.versions.node

**Comment by andrebautista** [comment]
@xzyfer when I add a `console.log(process.versions.node)` after the existing console.log the output is
```
undefined
11.0.0-nightly20180719373aae1f86
64
11.0.0-nightly20180719373aae1f86
57
11.0.0-nightly20180719373aae1f86
undefined
...
```

**Comment by andrebautista** [comment]
I believe so, when I did a `console.log(process.versions)` to get more details it returned
```
{ http_parser: '2.8.0',
  node: '11.0.0-nightly20180719373aae1f86',
  v8: '6.7.288.49-node.15',
  uv: '1.22.0',
  zlib: '1.2.11',
  ares: '1.14.0',
  modules: '64',
  nghttp2: '1.32.0',
  napi: '3',
  openssl: '1.1.0h',
  icu: '62.1',
  unicode: '11.0',
  cldr: '33.1',
  tz: '2018e' }
```
I'll try asking the nightly people why the name of node is changed. Is there another field that could be used to set the node version here?

**Comment by xzyfer** [comment]
No. It has to be module because that is what represents the version of V8s
ABI it's compiled against.

**Comment by Goblinlordx** [comment]
I am having this issue as well (and it is quite frustrating actually):
- NPM version (npm -v): v6.2.0
- Node version (npm -v): v8.9.4
- Node Process (node -p process.versions): { http_parser: '2.7.0',
  node: '8.9.4',
  v8: '6.1.534.50',
  uv: '1.15.0',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  nghttp2: '1.25.0',
  openssl: '1.0.2n',
  icu: '59.1',
  unicode: '9.0',
  cldr: '31.0.1',
  tz: '2017b' }
- Node Platform (node -p process.platform): darwin
- Node architecture (node -p process.arch): x64
- node-sass version (node -p "require('node-sass').info"):
node-sass	4.9.2	(Wrapper)	[JavaScript]
libsass 3.5.4	(Sass Compiler)	[C/C++]
-  npm ls node-sass
dash@0.0.0 /Users/benbaldivia/dev/dashboard
└── node-sass@4.9.2

I use `node-sass` via `webpack -> sass-loader -> node-sass`.  The most frustrating part about this is sometimes it works and then, seemingly randomly, it will suddenly start outputting this error.  If I stop webpack, make a file change (even in a js file and not a sass file) sometimes it will start working again.  Sometimes it won't.

I have tried completely removing node, npm, npm cache, and project node_modules.  Removing `node-sass` from dependencies and removing the `package-lock.json`, reinstalling packages and then last re-adding `node-sass` as a new dependency again.  After all that, I still eventually start getting this error again.

**Comment by Goblinlordx** [comment]
Geez... sorry actually mine is an Unsupported Environment error not missing binding.  Will open a new issue I guess.

**Comment by Goblinlordx** [comment]
@xzyfer Maybe you are not understanding.  1. I start a process which runs webpack.
2. It compiles everything successfully.
3. I make a change to a file.
3a. In some cases, this works and there is no error.
3b. In other cases, I start seeing the "Unsupported environment" error in browser console.
4. After changing a file again sometimes it starts compiling successfully again.

During this time webpack was never stopped.  If you are saying the executing version of node changed while running and in memory... I think this is a pretty unreasonable thing to state.

**Comment by xzyfer** [comment]
I'm simply stating the only circumstance under which node-sass can do what
you're saying it's doing.

It's possible you are changing node versions, it's possible you've got
multiple node-sass versions installed. Many weird environmental things are
possible.

What's not possible is what's you're describing without either the Node or
node-sass version changing.

**Comment by estani** [comment]
I don't understand if there's a solution/workaround or explanation. I have the same message with node-sass 4.12.0 And I have tried rebuilding it from scratch (--force) and it replies always the same... perhaps is an issue with nvm. I haven't change the version, but in any case, I can't compile it for the current version... it just doesn't work...

**Comment by sandro-pasquali** [comment]
If you're using `nvm` ensure that it has the targeted node version as its default. Run `nvm ls` and you'll see a `default -> <some version>` listed. It seems `node-sass` ends up reading that. To update the `nvm` default run `nvm alias default <your target version>`

**Comment by Arcanorum** [comment]
Doesn't work. :S
Seems totally broken.

**Comment by UsAndRufus** [comment]
I had to stop using `nvm` and just update Node to fix this issue. I update Node via `n`, Node's version manager.
