### ISSUE TITLE
Trouble installing node-sass

### ISSUE THREAD

**Issue by mabdrew** [sass/node-sass#2461]
- NPM version (`npm -v`): `6.2.0`
- Node version (`node -v`): `v8.11.3`
- Node Process (`node -p process.versions`):
```
{ http_parser: '2.8.0',
  node: '8.11.3',
  v8: '6.2.414.54',
  uv: '1.19.1',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  nghttp2: '1.32.0',
  napi: '3',
  openssl: '1.0.2o',
  icu: '60.1',
  unicode: '10.0',
  cldr: '32.0',
  tz: '2017c' }
```
- Node Platform (`node -p process.platform`): `win32`
- Node architecture (`node -p process.arch`): `x64`
- node-sass version (`node -p "require('node-sass').info"`):  
```
module.js:549
    throw err;
    ^

Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (modul
    at Function.Module._load (module.js:474:25
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at [eval]:1:1
    at ContextifyScript.Script.runInThisContex
    at Object.runInThisContext (vm.js:139:38)
    at Object.<anonymous> ([eval]-wrapper:6:22
    at Module._compile (module.js:652:30)
    at evalScript (bootstrap_node.js:466:27)
```
- npm node-sass versions (`npm ls node-sass`): `-- (empty)`

I am right now attempting to install the node-sass 4.9.2. I have node-gyp 3.7.0 installed. At the end of this post are the contents of my npm.err and npm.log files.

```

PS D:\sass_install_test> node -p process.env.comspec
C:\WINDOWS\system32\cmd.exe
PS D:\sass_install_test> npm -v
6.2.0
PS D:\sass_install_test> node -v
v8.11.3
PS D:\sass_install_test> node -p process.versions
{ http_parser: '2.8.0',
  node: '8.11.3',
  v8: '6.2.414.54',
  uv: '1.19.1',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  nghttp2: '1.32.0',
  napi: '3',
  openssl: '1.0.2o',
  icu: '60.1',
  unicode: '10.0',
  cldr: '32.0',
  tz: '2017c' }
PS D:\sass_install_test> node -p process.platform
win32
PS D:\sass_install_test> node -p process.arch
x64
PS D:\sass_install_test> npm cache clean --force
npm WARN using --force I sure hope you know what you are doing.
PS D:\sass_install_test>

```

**npm.log**

```
> node-sass@4.9.2 install D:\sass_install_test_no_proxy\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.9.2/win32-x64-57_binding.node

> node-sass@4.9.2 postinstall D:\sass_install_test_no_proxy\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe D:\sass_install_test_no_proxy\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=


```

**npm.err**

[npm.err](https://github.com/sass/node-sass/files/2220671/npm.err.txt)

**Comment by lazharichir** [comment]
Same... all packages install but node-sass...

```
{
  "devDependencies": {
    "babel-core": "^6.26.3",
    "babel-loader": "^7.1.5",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-preset-env": "^1.7.0",
    "babel-preset-react": "^6.24.1",
    "clean-webpack-plugin": "^0.1.19",
    "css-loader": "^1.0.0",
    "dexie": "^2.0.4",
    "html-loader": "^0.5.5",
    "html-webpack-plugin": "^3.2.0",
    "mini-css-extract-plugin": "^0.4.1",
    "node-sass": "~4.9.2",
    "react": "^16.4.1",
    "react-dom": "^16.4.1",
    "react-router-dom": "^4.3.1",
    "react-stripe-elements": "^2.0.1",
    "react-svg-gauge": "^1.0.8",
    "react-table": "^6.8.6",
    "react-toastify": "^4.1.0",
    "sass-loader": "^7.0.3",
    "serviceworker-webpack-plugin": "^1.0.0-alpha02",
    "style-loader": "^0.21.0",
    "webpack": "^4.16.2",
    "webpack-bundle-analyzer": "^2.13.1",
    "webpack-cli": "^3.0.8",
    "webpack-dev-server": "^3.1.4"
  },
  "dependencies": {
    "@firebase/app": "0.3.3",
    "@firebase/auth": "0.7.0"
  }
}
```

**Comment by xzyfer** [comment]
The answer is right in the your output

```
Cannot download "https://github.com/sass/node-sass/releases/download/v4.9.2/win32-x64-57_binding.node": 

connect ETIMEDOUT 192.30.253.112:443

Timed out whilst downloading the prebuilt binary

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g. 

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080
```
