### ISSUE TITLE
node-sass/vendor/linux-x64-57/binding.node: failed to map segment from shared object: Operation not permitted

### ISSUE THREAD

**Issue by Insidexa** [sass/node-sass#2474]
I create `docker-compose.yml` configuration and `dockerfile` for frontend development.
```
FROM node:8

RUN usermod -u 1000 node
RUN groupmod -g 1000 node

WORKDIR /var/www

USER node
```

Node image is a debian jessie, SELinux doest not exists

When i up all containers, i got errors on frontend service, example:

```
[0] ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./application/modules/bonuses/styles.scss 1.27 kB {0} [built] [failed] [1 error]

    ERROR in ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./application/modules/bonuses/styles.scss
    Module build failed: Error: /var/www/node_modules/node-sass/vendor/linux-x64-57/binding.node: failed to map segment from shared object: Operation not permitted
        at Object.Module._extensions..node (module.js:681:18)
        at Module.load (module.js:565:32)
        at tryModuleLoad (module.js:505:12)
        at Function.Module._load (module.js:497:3)
        at Module.require (module.js:596:17)
        at require (internal/module.js:11:18)
        at module.exports (/var/www/node_modules/node-sass/lib/binding.js:19:10)
        at Object.<anonymous> (/var/www/node_modules/node-sass/lib/index.js:14:35)
        at Module._compile (module.js:652:30)
        at Object.Module._extensions..js (module.js:663:10)
        at Module.load (module.js:565:32)
        at tryModuleLoad (module.js:505:12)
        at Function.Module._load (module.js:497:3)
        at Module.require (module.js:596:17)
        at require (internal/module.js:11:18)
        at Object.<anonymous> (/var/www/node_modules/sass-loader/lib/loader.js:3:14)
        at Module._compile (module.js:652:30)
        at Object.Module._extensions..js (module.js:663:10)
        at Module.load (module.js:565:32)
        at tryModuleLoad (module.js:505:12)
        at Function.Module._load (module.js:497:3)
        at Module.require (module.js:596:17)
```

I try to use any this ways, not working  
- try to change TMPDIR  
- try change node version
- npm rebuild node-sass  

--

- NPM version 5.6.0:
- Node version v8.11.3:
- Node Process
```
{ http_parser: '2.8.0',
  node: '8.11.3',
  v8: '6.2.414.54',
  uv: '1.19.1',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  nghttp2: '1.32.0',
  napi: '3',
  openssl: '1.0.2o',
  icu: '60.1',
  unicode: '10.0',
  cldr: '32.0',
  tz: '2017c' }
```
- Node Platform linux:
- Node architecture x64:
- node-sass version 
```
node@603519e433f6:/var/www$ node -p "require('node-sass').info"
module.js:681
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: /var/www/node_modules/node-sass/vendor/linux-x64-57/binding.node: failed to map segment from shared object: Operation not permitted
    at Object.Module._extensions..node (module.js:681:18)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at module.exports (/var/www/node_modules/node-sass/lib/binding.js:19:10)
    at Object.<anonymous> (/var/www/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
```
- npm node-sass versions -- node-sass@4.9.3:

**Comment by xzyfer** [comment]
Run npm rebuild node-sass inside the container

**Comment by Insidexa** [comment]
@xzyfer not working

**Comment by saper** [comment]
You didn't post the output of a failure.

**Comment by Insidexa** [comment]
@saper https://pastebin.com/9i1PsBSi - output of `npm rebuild node-sass` inside container

**Comment by nschonni** [comment]
Sounds similar to this https://github.com/lovell/sharp/issues/704#issuecomment-278354475 this is a problem with the mounting
Also https://stackoverflow.com/questions/45077967/error-with-webpack-vue-cli-sass-failed-to-map-segment-from-shared-object

**Comment by Insidexa** [comment]
I try to install global `node-sass` and i created link to locally project, its work, but it bullshit ( sorry for bad word )
i need to right way to solve this problem (

**Comment by saper** [comment]
Yes, thisi a problem with a filesystem. Probably set to `noexec`. Probably your image is doing this for you, the [Stackoverflow post about changing /etc/fstab](https://stackoverflow.com/a/45138968) quoted by @nschonni is most probably the right answer. It is not related to node-sass at all.

**Comment by saper** [comment]
Linking may work because things are on different filesystems probably. Please research your environment more carefully.

**Comment by delanthear** [comment]
I think I'm running into this on a Chromebook and I don't think there is an easy way to get around it?

```
> node-sass@4.9.3 postinstall /home/chronos/u-6264041317e5864e8f0891065e7585fa25e8958c/Downloads/projects/vue-starter/node_modules/node-sass
> node scripts/build.js

Binary found at /home/chronos/u-6264041317e5864e8f0891065e7585fa25e8958c/Downloads/projects/vue-starter/node_modules/node-sass/vendor/linux-x64-57/binding.node
Testing binary
Binary has a problem: Error: /home/chronos/u-6264041317e5864e8f0891065e7585fa25e8958c/Downloads/projects/vue-starter/node_modules/node-sass/vendor/linux-x64-57/binding.node: failed to map segment from shared object
    at Object.Module._extensions..node (module.js:682:18)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at module.exports (/home/chronos/u-6264041317e5864e8f0891065e7585fa25e8958c/Downloads/projects/vue-starter/node_modules/node-sass/lib/binding.js:19:10)
    at Object.<anonymous> (/home/chronos/u-6264041317e5864e8f0891065e7585fa25e8958c/Downloads/projects/vue-starter/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
```

The mount output for this dir:
`/dev/mmcblk0p1 on /home/user/6264041317e5864e8f0891065e7585fa25e8958c type ext4 (rw,nosuid,nodev,noexec,noatime,commit=600,data=ordered)`

Not convinced this is easily solvable for me?

**Comment by xzyfer** [comment]
I would say not. Chromebooks must have a non-standard libc

**Comment by saper** [comment]
Did the comment you responded to got deleted? I think the `failed to map segment from shared object` can be caused by having the filesystem mounted as `noexec`.

**Comment by delanthear** [comment]
Apologies I deleted the comment as I got around it.  I didn't expect it to be picked up and responded to :) 

I managed to install node-sass using the global option and while I was in a different directory (no idea if this affected it) and it installed fine!  (no idea!)

**Comment by saper** [comment]
Yes, this was confusing - I got an email notification and then I could not find it on Github. Yes, it is quite possible that your global installation directory is on another file system. You can say "mount" and see all your file systems. There is probably "noexec" word in the line that begins with "/home" and there is probably nothing like that in "/usr" or wherever your global install directory might be.

**Comment by surak** [comment]
+1 to @saper . The default (at least on ubuntu) for a mount on fstab is "noexec". Adding the "exec" to the fstab options fixed this. Someone should fix this error message.

**Comment by saper** [comment]
@surak The message comes from the kernel and the C library. Sorry for that, but it cannot be fixed here.

**Comment by surak** [comment]
Thanks @saper , I mean that since the error is known, a useful message would be more helpful than a simple stack trace, don't you think?

**Comment by saper** [comment]
It is not known that filesystem settings are the cause of this. This is only one of the possible explanations what happened.

This error is not generated by node-sass, it comes from the way node itself uses system-specific way to load a shared library.
