### ISSUE TITLE
installing in linux arm failed

### ISSUE THREAD

**Issue by duguying** [sass/node-sass#2478]
- NPM version (`npm -v`): 5.6.0
- Node version (`node -v`): v8.11.4
- Node Process (`node -p process.versions`):
```
{ http_parser: '2.8.0',
  node: '8.11.4',
  v8: '6.2.414.54',
  uv: '1.19.1',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  nghttp2: '1.32.0',
  napi: '3',
  openssl: '1.0.2p',
  icu: '60.1',
  unicode: '10.0',
  cldr: '32.0',
  tz: '2017c' }
```
- Node Platform (`node -p process.platform`): linux
- Node architecture (`node -p process.arch`): arm
- node-sass version (`node -p "require('node-sass').info"`):
```
module.js:549
    throw err;
    ^

Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at [eval]:1:1
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at Object.runInThisContext (vm.js:139:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:652:30)
    at evalScript (bootstrap_node.js:466:27)
```
- npm node-sass versions (`npm ls node-sass`):
```
/root
└── (empty)
```

installing command
```
npm install node-sass --save
```

error logs:
```
4648 verbose stack Error: node-sass@4.9.3 install: `node scripts/install.js`
4648 verbose stack Exit status 1
4648 verbose stack     at EventEmitter.<anonymous> (/usr/local/node/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
4648 verbose stack     at emitTwo (events.js:126:13)
4648 verbose stack     at EventEmitter.emit (events.js:214:7)
4648 verbose stack     at ChildProcess.<anonymous> (/usr/local/node/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
4648 verbose stack     at emitTwo (events.js:126:13)
4648 verbose stack     at ChildProcess.emit (events.js:214:7)
4648 verbose stack     at maybeClose (internal/child_process.js:925:16)
4648 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
4649 verbose pkgid node-sass@4.9.3
4650 verbose cwd /root
4651 verbose Linux 4.14.34-v7+
4652 verbose argv "/usr/local/node/bin/node" "/usr/local/node/bin/npm" "install" "node-sass" "--save"
4653 verbose node v8.11.4
4654 verbose npm  v5.6.0
4655 error code ELIFECYCLE
4656 error errno 1
4657 error node-sass@4.9.3 install: `node scripts/install.js`
4657 error Exit status 1
4658 error Failed at the node-sass@4.9.3 install script.
4658 error This is probably not a problem with npm. There is likely additional logging output above.
4659 verbose exit [ 1, true ]
```

**Comment by nschonni** [comment]
Sorry, ARM isn't a supported architecture

**Comment by duguying** [comment]
OMG...
