### ISSUE TITLE
Cannot find module 'strip-ansi' on install

### ISSUE THREAD

**Issue by benwiley4000** [sass/node-sass#2488]
When trying to install a project depending on node-sass I get the following error and node-sass fails to install:

```
> node-sass@4.7.1 install /home/ben/Documents/Code/react-responsive-audio-player/node_modules/node-sass
> node scripts/install.js

module.js:538
    throw err;
    ^

Error: Cannot find module 'strip-ansi'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ben/Documents/Code/react-responsive-audio-player/node_modules/string-width/index.js:2:17)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
```

I've tried different versions and nothing works.

- NPM version (`npm -v`): 6.0.0
- Node version (`node -v`): 8.9.0
- Node Process (`node -p process.versions`): 
```js
{ http_parser: '2.7.0',
  node: '8.9.0',
  v8: '6.1.534.46',
  uv: '1.15.0',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  nghttp2: '1.25.0',
  openssl: '1.0.2l',
  icu: '59.1',
  unicode: '9.0',
  cldr: '31.0.1',
  tz: '2017b' }
```
- Node Platform (`node -p process.platform`): linux
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`): Can't install so can't give you this
- npm node-sass versions (`npm ls node-sass`): Again I can't install but I tried with 4.5.3, 4.7.1, 4.7.2, 4.9.3.

**Comment by benwiley4000** [comment]
I was able to solve by upgrading from npm@6.0.0 to npm@6.4.1.

**Comment by christianhaller3000** [comment]
Same problem here :(
