### ISSUE TITLE
install fails silently

### ISSUE THREAD

**Issue by raffomania** [sass/node-sass#2509]
- NPM version (`npm -v`): 3.10.10
- Node version (`node -v`): 6.14.4
- Node Process (`node -p process.versions`):
```
{ http_parser: '2.8.0',
  node: '6.14.4',
  v8: '5.1.281.111',
  uv: '1.16.1',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  icu: '58.2',
  modules: '48',
  napi: '3',
  openssl: '1.0.2p' }
```
- Node Platform (`node -p process.platform`): linux
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`): Trying to install 3.13.1
- npm node-sass versions (`npm ls node-sass`): node-sass@3.13.1

We're using ubuntu 16.04. `npm install` exits with status 1, when trying to run `node -p "require('node-sass').info"` I get the following error:
```
fs.js:961
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir '/usr/local/src/hauscodeployment/hausco/frontend/node_modules/node-sass/vendor'
    at Error (native)
    at Object.fs.readdirSync (fs.js:961:18)
    at Object.getInstalledBinaries (/usr/local/src/hauscodeployment/hausco/frontend/node_modules/node-sass/lib/extensions.js:121:13)
    at foundBinariesList (/usr/local/src/hauscodeployment/hausco/frontend/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/usr/local/src/hauscodeployment/hausco/frontend/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/usr/local/src/hauscodeployment/hausco/frontend/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/usr/local/src/hauscodeployment/hausco/frontend/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/usr/local/src/hauscodeployment/hausco/frontend/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
```

Running `npm install --no-optional` is a workaround, but I don't want to depend on that. I don't even understand why it works - there are no optional dependencies in node-sass' package.json, maybe a transitive dependency is causing the trouble?

**Comment by xzyfer** [comment]
Node sass 3.x out support up to node 0.12

**Comment by raffomania** [comment]
That's interesting? The release page for 3.13.0 says '0.10, 0.12, 1, 2, 3, 4, 5, 6, 7' (https://github.com/sass/node-sass/releases/tag/v3.13.0).
Is the documentation on releases wrong?

**Comment by xzyfer** [comment]
The error you're seeing essentially says node-sass files weren't installed. Usually happens due to permission issues or running npm as sudo (which you should never do). Follow the troubleshooting documentation for a solution. 

3.x is very old and we are unable to support it any further.
