### ISSUE TITLE
Install Error on NodeJS 11

### ISSUE THREAD

**Issue by Toso82** [sass/node-sass#2525]
- NPM version (`npm -v`): 6.4.1
- Node version (`node -v`): v11.0.0
- Node Process (`node -p process.versions`): 

```
{ http_parser: '2.8.0',
  node: '11.0.0',
  v8: '7.0.276.28-node.5',
  uv: '1.23.2',
  zlib: '1.2.11',
  ares: '1.14.0',
  modules: '67',
  nghttp2: '1.34.0',
  napi: '3',
  openssl: '1.1.0i \n',
  icu: '62.1',
  unicode: '11.0',
  cldr: '33.1',
  tz: '2018e' }
```
> 

- Node Platform (`node -p process.platform`):  win32
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`):

```
internal/modules/cjs/loader.js:589
    throw err;
    ^

Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
    at Function.Module._load (internal/modules/cjs/loader.js:513:25)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at [eval]:1:1
    at Script.runInThisContext (vm.js:119:20)
    at Object.runInThisContext (vm.js:316:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at evalScript (internal/bootstrap/node.js:715:27)
```
- npm node-sass versions (`npm ls node-sass`):
```
prova@0.0.0 C:\Users\Giacomo\Documents\Visual Studio 2017\Projects\Angular\prova
`-- @angular-devkit/build-angular@0.10.3
  `-- UNMET OPTIONAL DEPENDENCY node-sass@4.9.3
```

Error on installation 

```
npm install node-sass@latest

> node-sass@4.9.3 install C:\Users\Giacomo\Documents\Visual Studio 2017\Projects\Angular\prova\node_modules\@angular-devkit\build-angular\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.9.3/win32-x64-67_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.9.3/win32-x64-67_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.9.4 install C:\Users\Giacomo\Documents\Visual Studio 2017\Projects\Angular\prova\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.9.4/win32-x64-67_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.9.4/win32-x64-67_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.9.3 postinstall C:\Users\Giacomo\Documents\Visual Studio 2017\Projects\Angular\prova\node_modules\@angular-devkit\build-angular\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe C:\Users\Giacomo\Documents\Visual Studio 2017\Projects\Angular\prova\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\Giacomo\\Documents\\Visual Studio 2017\\Projects\\Angular\\prova\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@11.0.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\Giacomo\Documents\Visual Studio 2017\Projects\Angular\prova\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Giacomo\Documents\Visual Studio 2017\Projects\Angular\prova\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Giacomo\Documents\Visual Studio 2017\Projects\Angular\prova\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Giacomo\Documents\Visual Studio 2017\Projects\Angular\prova\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Giacomo\Documents\Visual Studio 2017\Projects\Angular\prova\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\Giacomo\Documents\Visual Studio 2017\Projects\Angular\prova\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:161:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\Giacomo\Documents\Visual Studio 2017\Projects\Angular\prova\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Giacomo\Documents\Visual Studio 2017\Projects\Angular\prova\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Giacomo\Documents\Visual Studio 2017\Projects\Angular\prova\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Giacomo\Documents\Visual Studio 2017\Projects\Angular\prova\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Giacomo\Documents\Visual Studio 2017\Projects\Angular\prova\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\Giacomo\Documents\Visual Studio 2017\Projects\Angular\prova\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:161:21)
gyp verb `which` failed   stack:
gyp verb `which` failed    'Error: not found: python2\n    at getNotFoundError (C:\\Users\\Giacomo\\Documents\\Visual Studio 2017\\Projects\\Angular\\prova\\node_modules\\which\\which.js:13:12)\n    at F (C:\\Users\\Giacomo\\Documents\\Visual Studio 2017\\Projects\\Angular\\prova\\node_modules\\which\\which.js:68:19)\n    at E (C:\\Users\\Giacomo\\Documents\\Visual Studio 2017\\Projects\\Angular\\prova\\node_modules\\which\\which.js:80:29)\n    at C:\\Users\\Giacomo\\Documents\\Visual Studio 2017\\Projects\\Angular\\prova\\node_modules\\which\\which.js:89:16\n    at C:\\Users\\Giacomo\\Documents\\Visual Studio 2017\\Projects\\Angular\\prova\\node_modules\\isexe\\index.js:42:5\n    at C:\\Users\\Giacomo\\Documents\\Visual Studio 2017\\Projects\\Angular\\prova\\node_modules\\isexe\\windows.js:36:5\n    at FSReqCallback.oncomplete (fs.js:161:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Users\Giacomo\Documents\Visual Studio 2017\Projects\Angular\prova\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Giacomo\Documents\Visual Studio 2017\Projects\Angular\prova\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Giacomo\Documents\Visual Studio 2017\Projects\Angular\prova\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Giacomo\Documents\Visual Studio 2017\Projects\Angular\prova\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Giacomo\Documents\Visual Studio 2017\Projects\Angular\prova\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\Giacomo\Documents\Visual Studio 2017\Projects\Angular\prova\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:161:21)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Users\Giacomo\Documents\Visual Studio 2017\Projects\Angular\prova\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Giacomo\Documents\Visual Studio 2017\Projects\Angular\prova\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Giacomo\Documents\Visual Studio 2017\Projects\Angular\prova\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Giacomo\Documents\Visual Studio 2017\Projects\Angular\prova\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Giacomo\Documents\Visual Studio 2017\Projects\Angular\prova\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\Giacomo\Documents\Visual Studio 2017\Projects\Angular\prova\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:161:21)
gyp verb `which` failed   stack:
gyp verb `which` failed    'Error: not found: python\n    at getNotFoundError (C:\\Users\\Giacomo\\Documents\\Visual Studio 2017\\Projects\\Angular\\prova\\node_modules\\which\\which.js:13:12)\n    at F (C:\\Users\\Giacomo\\Documents\\Visual Studio 2017\\Projects\\Angular\\prova\\node_modules\\which\\which.js:68:19)\n    at E (C:\\Users\\Giacomo\\Documents\\Visual Studio 2017\\Projects\\Angular\\prova\\node_modules\\which\\which.js:80:29)\n    at C:\\Users\\Giacomo\\Documents\\Visual Studio 2017\\Projects\\Angular\\prova\\node_modules\\which\\which.js:89:16\n    at C:\\Users\\Giacomo\\Documents\\Visual Studio 2017\\Projects\\Angular\\prova\\node_modules\\isexe\\index.js:42:5\n    at C:\\Users\\Giacomo\\Documents\\Visual Studio 2017\\Projects\\Angular\\prova\\node_modules\\isexe\\windows.js:36:5\n    at FSReqCallback.oncomplete (fs.js:161:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\Giacomo\Documents\Visual Studio 2017\Projects\Angular\prova\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\Giacomo\Documents\Visual Studio 2017\Projects\Angular\prova\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at C:\Users\Giacomo\Documents\Visual Studio 2017\Projects\Angular\prova\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:161:21)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Giacomo\\Documents\\Visual Studio 2017\\Projects\\Angular\\prova\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\Giacomo\Documents\Visual Studio 2017\Projects\Angular\prova\node_modules\@angular-devkit\build-angular\node_modules\node-sass
gyp ERR! node -v v11.0.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1

> node-sass@4.9.4 postinstall C:\Users\Giacomo\Documents\Visual Studio 2017\Projects\Angular\prova\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe C:\Users\Giacomo\Documents\Visual Studio 2017\Projects\Angular\prova\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\Giacomo\\Documents\\Visual Studio 2017\\Projects\\Angular\\prova\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@11.0.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\Giacomo\Documents\Visual Studio 2017\Projects\Angular\prova\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Giacomo\Documents\Visual Studio 2017\Projects\Angular\prova\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Giacomo\Documents\Visual Studio 2017\Projects\Angular\prova\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Giacomo\Documents\Visual Studio 2017\Projects\Angular\prova\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Giacomo\Documents\Visual Studio 2017\Projects\Angular\prova\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\Giacomo\Documents\Visual Studio 2017\Projects\Angular\prova\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:161:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\Giacomo\Documents\Visual Studio 2017\Projects\Angular\prova\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Giacomo\Documents\Visual Studio 2017\Projects\Angular\prova\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Giacomo\Documents\Visual Studio 2017\Projects\Angular\prova\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Giacomo\Documents\Visual Studio 2017\Projects\Angular\prova\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Giacomo\Documents\Visual Studio 2017\Projects\Angular\prova\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\Giacomo\Documents\Visual Studio 2017\Projects\Angular\prova\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:161:21)
gyp verb `which` failed   stack:
gyp verb `which` failed    'Error: not found: python2\n    at getNotFoundError (C:\\Users\\Giacomo\\Documents\\Visual Studio 2017\\Projects\\Angular\\prova\\node_modules\\which\\which.js:13:12)\n    at F (C:\\Users\\Giacomo\\Documents\\Visual Studio 2017\\Projects\\Angular\\prova\\node_modules\\which\\which.js:68:19)\n    at E (C:\\Users\\Giacomo\\Documents\\Visual Studio 2017\\Projects\\Angular\\prova\\node_modules\\which\\which.js:80:29)\n    at C:\\Users\\Giacomo\\Documents\\Visual Studio 2017\\Projects\\Angular\\prova\\node_modules\\which\\which.js:89:16\n    at C:\\Users\\Giacomo\\Documents\\Visual Studio 2017\\Projects\\Angular\\prova\\node_modules\\isexe\\index.js:42:5\n    at C:\\Users\\Giacomo\\Documents\\Visual Studio 2017\\Projects\\Angular\\prova\\node_modules\\isexe\\windows.js:36:5\n    at FSReqCallback.oncomplete (fs.js:161:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Users\Giacomo\Documents\Visual Studio 2017\Projects\Angular\prova\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Giacomo\Documents\Visual Studio 2017\Projects\Angular\prova\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Giacomo\Documents\Visual Studio 2017\Projects\Angular\prova\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Giacomo\Documents\Visual Studio 2017\Projects\Angular\prova\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Giacomo\Documents\Visual Studio 2017\Projects\Angular\prova\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\Giacomo\Documents\Visual Studio 2017\Projects\Angular\prova\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:161:21)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Users\Giacomo\Documents\Visual Studio 2017\Projects\Angular\prova\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Giacomo\Documents\Visual Studio 2017\Projects\Angular\prova\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Giacomo\Documents\Visual Studio 2017\Projects\Angular\prova\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Giacomo\Documents\Visual Studio 2017\Projects\Angular\prova\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Giacomo\Documents\Visual Studio 2017\Projects\Angular\prova\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\Giacomo\Documents\Visual Studio 2017\Projects\Angular\prova\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:161:21)
gyp verb `which` failed   stack:
gyp verb `which` failed    'Error: not found: python\n    at getNotFoundError (C:\\Users\\Giacomo\\Documents\\Visual Studio 2017\\Projects\\Angular\\prova\\node_modules\\which\\which.js:13:12)\n    at F (C:\\Users\\Giacomo\\Documents\\Visual Studio 2017\\Projects\\Angular\\prova\\node_modules\\which\\which.js:68:19)\n    at E (C:\\Users\\Giacomo\\Documents\\Visual Studio 2017\\Projects\\Angular\\prova\\node_modules\\which\\which.js:80:29)\n    at C:\\Users\\Giacomo\\Documents\\Visual Studio 2017\\Projects\\Angular\\prova\\node_modules\\which\\which.js:89:16\n    at C:\\Users\\Giacomo\\Documents\\Visual Studio 2017\\Projects\\Angular\\prova\\node_modules\\isexe\\index.js:42:5\n    at C:\\Users\\Giacomo\\Documents\\Visual Studio 2017\\Projects\\Angular\\prova\\node_modules\\isexe\\windows.js:36:5\n    at FSReqCallback.oncomplete (fs.js:161:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\Giacomo\Documents\Visual Studio 2017\Projects\Angular\prova\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\Giacomo\Documents\Visual Studio 2017\Projects\Angular\prova\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at C:\Users\Giacomo\Documents\Visual Studio 2017\Projects\Angular\prova\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:161:21)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Giacomo\\Documents\\Visual Studio 2017\\Projects\\Angular\\prova\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\Giacomo\Documents\Visual Studio 2017\Projects\Angular\prova\node_modules\node-sass
gyp ERR! node -v v11.0.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.9.3 (node_modules\@angular-devkit\build-angular\node_modules\node-sass):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.9.3 postinstall: `node scripts/build.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.9.4 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.9.4 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Giacomo\AppData\Roaming\npm-cache\_logs\2018-10-25T09_46_10_484Z-debug.log


```

**Comment by xzyfer** [comment]
Duplicate

**Comment by glennlawyer** [comment]
@xzyfer I understand why you'd close this as a duplicate. But it would be helpful if you had linked to what it is a duplicate of. I'm also having this issue, and Google took me to this page to find a solution.

**Comment by xzyfer** [comment]
This is documented as the first line in the read me.

**Comment by wemod123** [comment]
same issue!
 
I refered to almost all issues, and tried with different node version and node-sass version, but no way to solve!
