### ISSUE TITLE
Error: ENOSPC: no space left on device

### ISSUE THREAD

**Issue by j-o-d-o** [sass/node-sass#2534]
With this watch command:
```
node-sass --include-path src src/index.scss public/bundle.css -w -r
```

Sometimes I get the Error: 'Error: ENOSPC: no space left on device on'. I am not 100% sure where this is coming from or what it means, but it is not the "disk space" as there is plenty left.

I am also not sure if it actually is a node-sass issue or an issue with my system. Maybe someone can enlighten me here.

- NPM version (`npm -v`): 6.1.0
- Node version (`node -v`): v10.6.0
- Node Process (`node -p process.versions`):
{ http_parser: '2.8.0',
  node: '10.6.0',
  v8: '6.7.288.46-node.13',
  uv: '1.21.0',
  zlib: '1.2.11',
  ares: '1.14.0',
  modules: '64',
  nghttp2: '1.32.0',
  napi: '3',
  openssl: '1.1.0h',
  icu: '61.1',
  unicode: '10.0',
  cldr: '33.0',
  tz: '2018c' }
- Node Platform (`node -p process.platform`): linux
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`): 
node-sass    4.9.4    (Wrapper)            [Javascript]
libsass         3.5.4    (Sass Compiler)   [C/C++]
- npm node-sass versions (`npm ls node-sass`): 4.9.4

This is the complete error log:
```
Error: ENOSPC: no space left on device, watch '/home/jo/Desktop/project/src/'
    at FSWatcher.start (internal/fs/watchers.js:161:26)
    at Object.watch (fs.js:1227:11)
    at Gaze._watchDir (/home/jo/Desktop/project/node_modules/gaze/lib/gaze.js:314:30)
    at /home/jo/Desktop/project/node_modules/gaze/lib/gaze.js:387:10
    at iterate (/home/jo/Desktop/project/node_modules/gaze/lib/helper.js:69:5)
    at Object.forEachSeries (/home/jo/Desktop/project/node_modules/gaze/lib/helper.js:83:3)
    at Gaze._initWatched (/home/jo/Desktop/project/node_modules/gaze/lib/gaze.js:383:10)
    at Gaze.add (/home/jo/Desktop/project/node_modules/gaze/lib/gaze.js:192:8)
    at watch (/home/jo/Desktop/project/node_modules/node-sass/bin/node-sass:260:8)
    at run (/home/jo/Desktop/project/node_modules/node-sass/bin/node-sass:319:5)
Emitted 'error' event at:
    at Gaze.emit (/home/jo/Desktop/project/node_modules/gaze/lib/gaze.js:102:32)
    at Gaze._handleError (/home/jo/Desktop/project/node_modules/gaze/lib/gaze.js:468:15)
    at Gaze._watchDir (/home/jo/Desktop/project/node_modules/gaze/lib/gaze.js:331:17)
    at /home/jo/Desktop/project/node_modules/gaze/lib/gaze.js:387:10
    [... lines matching original stack trace ...]
    at run (/home/jo/Desktop/project/node_modules/node-sass/bin/node-sass:319:5)
```

**Comment by xzyfer** [comment]
This is not a node sass issue try. You can try opening an issue with gaze.
You might have better luck Googling for the error.

**Comment by j-o-d-o** [comment]
Increasing max user watches resolved the issue:

```
>> sudo sysctl fs.inotify.max_user_watches=16384
```

Was at 8192 originally

**Comment by harrie006** [comment]
@j-o-d-o this worked for me.

**Comment by joanDeveloper** [comment]
Thanks, also worked for me

**Comment by sarojkumar007** [comment]
Great, It works for me ... Thanks for the help.

**Comment by nutcracker53** [comment]
sudo sysctl fs.inotify.max_user_watches=16384
This solved my problem on the ENOSPC issue. Am installating ERPNext v12

muchas gracias..

**Comment by asheshpaul** [comment]
@j-o-d-o thanks, also worked for me

**Comment by Draymonders** [comment]
@j-o-d-o  thanks, and also worked for me.
