### ISSUE TITLE
Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (67)

### ISSUE THREAD

**Issue by wolfkumpitsch1** [sass/node-sass#2540]
while running inside VS2017, upgraded 7/11/2018

Failed to run "C:\Projects\WKGIT\DBDRV Website\DBDRV-Website\DBDRVWebsite.Web\Gulpfile.js"...
cmd.exe /c gulp --tasks-simple
C:\Projects\WKGIT\DBDRV Website\DBDRV-Website\DBDRVWebsite.Web\node_modules\node-sass\lib\binding.js:13
      throw new Error(errors.unsupportedEnvironment());
      ^
Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (67)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.9.4
    at module.exports (C:\Projects\WKGIT\DBDRV Website\DBDRV-Website\DBDRVWebsite.Web\node_modules\node-sass\lib\binding.js:13:13)
    at Object.<anonymous> (C:\Projects\WKGIT\DBDRV Website\DBDRV-Website\DBDRVWebsite.Web\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Projects\WKGIT\DBDRV Website\DBDRV-Website\DBDRVWebsite.Web\node_modules\gulp-sass\index.js:187:21)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Module.require (internal/modules/cjs/loader.js:643:17)

- NPM version (`npm -v`):6.4.1
- Node version (`node -v`):v11.0.0
- Node Process (`node -p process.versions`):{ http_parser: '2.8.0',
  node: '11.0.0',
  v8: '7.0.276.28-node.5',
  uv: '1.23.2',
  zlib: '1.2.11',
  ares: '1.14.0',
  modules: '67',
  nghttp2: '1.34.0',
  napi: '3',
  openssl: '1.1.0i \n',
  icu: '62.1',
  unicode: '11.0',
  cldr: '33.1',
  tz: '2018e' }
- Node Platform (`node -p process.platform`):win32
- Node architecture (`node -p process.arch`):x64
- node-sass version (`node -p "require('node-sass').info"`):
C:\Projects\WKGIT\DBDRV Website\DBDRV-Website\DBDRVWebsite.Web>node -p "require('node-sass').info"
C:\Projects\WKGIT\DBDRV Website\DBDRV-Website\DBDRVWebsite.Web\node_modules\node-sass\lib\binding.js:13
      throw new Error(errors.unsupportedEnvironment());
      ^

Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (67)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.9.4
    at module.exports (C:\Projects\WKGIT\DBDRV Website\DBDRV-Website\DBDRVWebsite.Web\node_modules\node-sass\lib\binding.js:13:13)
    at Object.<anonymous> (C:\Projects\WKGIT\DBDRV Website\DBDRV-Website\DBDRVWebsite.Web\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at [eval]:1:1

- npm node-sass versions (`npm ls node-sass`):C:\Users\ICT User>npm ls node-sass
dbdrv@0.0.1 C:\Projects\WKGIT\DBDRV Website\DBDRV-Website\DBDRVWebsite.Web
`-- opine-styles@0.4.6
  `-- gulp-sass@3.2.1
    `-- node-sass@4.9.4

**Comment by xzyfer** [comment]
Update to node-sass@4.10
