### ISSUE TITLE
Cannot install node-sass

### ISSUE THREAD

**Issue by Stadly** [sass/node-sass#2542]
I am not able to install node-sass version 4.10.0 in a Docker container using the image `node:8-alpine`.

I get the following error ([full log](https://pastebin.com/gy9BhaCF))
```sh
/var/www/html/include # npm install node-sass

> node-sass@4.10.0 install /var/www/html/include/node_modules/node-sass
> node scripts/install.js

fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EINVAL: invalid argument, open '/var/www/html/include/node_modules/node-sass/package.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.Module._extensions..json (module.js:670:20)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/www/html/include/node_modules/node-sass/lib/extensions.js:7:9)
    at Module._compile (module.js:653:30)


...


npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.10.0 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.10.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-11-09T13_19_00_382Z-debug.log
```

What can be the cause of this?

Platform details
- NPM version (`npm -v`): 6.4.1
- Node version (`node -v`): 8.12.0
- Node Process (`node -p process.versions`):
```js
{ http_parser: '2.8.0',
  node: '8.12.0',
  v8: '6.2.414.66',
  uv: '1.19.2',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  nghttp2: '1.32.0',
  napi: '3',
  openssl: '1.0.2p',
  icu: '60.1',
  unicode: '10.0',
  cldr: '32.0',
  tz: '2017c' }
```
- Node Platform (`node -p process.platform`): linux
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`): Not applicable
- npm node-sass versions (`npm ls node-sass`): Not applicable

**Comment by xzyfer** [comment]
Duplicate https://github.com/sass/node-sass/issues/2520

**Comment by tahirakbar1** [comment]
update latest node-sass 
npm install node-sass@latest
