### ISSUE TITLE
Module build failed: Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (67)

### ISSUE THREAD

**Issue by ivawen** [sass/node-sass#2568]
npm@6.5.0
node version: v11.0.0
```
{ http_parser: '2.8.0',
  node: '11.0.0',
  v8: '7.0.276.28-node.5',
  uv: '1.23.2',
  zlib: '1.2.11',
  ares: '1.14.0',
  modules: '67',
  nghttp2: '1.34.0',
  napi: '3',
  openssl: '1.1.0i \n',
  icu: '62.1',
  unicode: '11.0',
  cldr: '33.1',
  tz: '2018e' }
```
Node Platform (node -p process.platform): tform darwin
Node architecture (node -p process.arch): x64
node -p "require('node-sass').info"
node-sass       3.13.1  (Wrapper)       [JavaScript]
libsass         3.3.6   (Sass Compiler) [C/C++]

```
Error: Module build failed: Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (67)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v3.10.1
    at Object.<anonymous> (/REPO/SL/so-inventory-web-app/frontend/node_modules/node-sass/lib/index.js:13:11)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/REPO/SL/so-inventory-web-app/frontend/node_modules/sass-loader/index.js:4:12)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
at http://localhost:9876/base/config/spec-bundle.js?1b6586e6c0a788b0c327178af8f8da10ed1e71eb:149640
```

i removed node_modules and did npm install but it did not work, i also tried to force sass rebuild nom rebuild node-sass --force same thing did not work

**Comment by xzyfer** [comment]
Done
