### ISSUE TITLE
Problem installing node-sass 4.11 on Windows 7 x64

### ISSUE THREAD

**Issue by jlifton** [sass/node-sass#2593]
I'm having  problems installing node-sass. We upgraded our node version to node 10.0, and npm install on our project installs everything except node-sass.
I am trying to install node-sass via a devDependencies entry in package.json using:
"node-sass": "^4.11.0"

My environment is Windows 7 x64. npm version is 5.6.0

The snippet of the end of my debug.log with the problem shown is:
...
1469 verbose stack Error: node-sass@4.11.0 install: `node scripts/install.js`
1469 verbose stack spawn C:\Windows\system32\cmd.exe;C:\Program Files\nodejs\; ENOENT
1469 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:217:19)
1469 verbose stack     at onErrorNT (internal/child_process.js:394:16)
1469 verbose stack     at process._tickCallback (internal/process/next_tick.js:174:19)
1470 verbose pkgid node-sass@4.11.0
1471 verbose cwd C:\projects\padm-4764-smtp-integ
1472 verbose Windows_NT 6.1.7601
1473 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
1474 verbose node v10.0.0
1475 verbose npm  v5.6.0
1476 error file C:\Windows\system32\cmd.exe;C:\Program Files\nodejs\;
1477 error path C:\Windows\system32\cmd.exe;C:\Program Files\nodejs\;
1478 error code ELIFECYCLE
1479 error errno ENOENT
1480 error syscall spawn C:\Windows\system32\cmd.exe;C:\Program Files\nodejs\;
1481 error node-sass@4.11.0 install: `node scripts/install.js`
1481 error spawn C:\Windows\system32\cmd.exe;C:\Program Files\nodejs\; ENOENT
1482 error Failed at the node-sass@4.11.0 install script.
1482 error This is probably not a problem with npm. There is likely additional logging output above.
1483 verbose exit [ 1, true ]

The 2nd line above seems suspect, indicating an ENOENT, implying a missing/incorrect file / path ? 
C:\Program Files\nodejs\ definitely exists.

Another point of suspicion is npm itself. Any invocation of npm from a command prompt always starts with the warning below (example npm --version), although it seems to carry 
on with whatever npm command I trying to do. Note the double slash:

'CALL "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\\node_modules\npm\bin\npm-cli.js" prefix -g' is not recognized as an internal or external command,
operable program or batch file.

I've already checked to make sure I dont have any other instances of npm installed.
I've also tried npm install -f node-sass, which does install something, but when building my Angular 7 project via ng build, I get an error that there is no 
ENOENT: no such file or directory, scandir 'C:\projects\padm-4764-smtp-integ\node_modules\node-sass\vendor'

Thanks,
Jonathan

**Comment by jlifton** [comment]
Problem solved.  For some reason, the Comspec enivronment variable had the node path tacked on to it. I removed it and all is ok now.
