### ISSUE TITLE
Module build failed: Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (69)

### ISSUE THREAD

**Issue by Lynn-cc** [sass/node-sass#2603]
- NPM version (`npm -v`): 6.0.7
- Node version (`node -v`): v10.15.1
- Node Process (`node -p process.versions`):
{ http_parser: '2.8.0',
  node: '10.15.1',
  v8: '6.8.275.32-node.12',
  uv: '1.23.2',
  zlib: '1.2.11',
  ares: '1.15.0',
  modules: '64',
  nghttp2: '1.34.0',
  napi: '3',
  openssl: '1.1.0j',
  icu: '62.1',
  unicode: '11.0',
  cldr: '33.1',
  tz: '2018e' }

- Node Platform (`node -p process.platform`):win32
- Node architecture (`node -p process.arch`):x64
- node-sass version (`node -p "require('node-sass').info"`):
node-sass       4.11.0  (Wrapper)       [JavaScript]
libsass         3.5.4   (Sass Compiler) [C/C++]

- npm node-sass versions (`npm ls node-sass`):

fusion_proj@1.0.0 D:\workspace\fusion_proj
+-- element-theme@2.0.1
| `-- gulp-sass@3.2.1
|   `-- node-sass@4.11.0  deduped
`-- node-sass@4.11.0

the error output:

 ERROR  Failed to compile with 3 errors下午8:47:56

 error  in ./src/module/demo/ui/App.vue?vue&type=style&index=0&lang=scss&

Module build failed: Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (69)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.11.0
    at module.exports (D:\workspace\fusion_proj\node_modules\node-sass\lib\binding.js:13:13)
    at Object.<anonymous> (D:\workspace\fusion_proj\node_modules\node-sass\lib\index.js:14:35)
    at Object.<anonymous> (D:\workspace\fusion_proj\node_modules\node-sass\lib\index.js:477:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.sassLoader (D:\workspace\fusion_proj\node_modules\sass-loader\lib\loader.js:46:72)

 @ ./node_modules/vue-style-loader!./node_modules/css-loader/dist/cjs.js??ref--11-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/lib??ref--11-2!./node_modules/sass-loader/lib/loader.js??ref--11-3!./node_modules/vue-loader/lib??vue-loader-options!./src/module/demo/ui/App.vue?vue&type=style&index=0&lang=scss& 4:14-391 14:3-18:5 15:22-399
 @ ./src/module/demo/ui/App.vue?vue&type=style&index=0&lang=scss&
 @ ./src/module/demo/ui/App.vue
 @ ./src/module/demo/ui/main.js
 @ multi ./build/dev-client ./src/module/demo/ui/main.js ./src/common/script/console_text.js

 error  in ./src/common/style/ui/index.scss

Module build failed: Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (69)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.11.0
    at module.exports (D:\workspace\fusion_proj\node_modules\node-sass\lib\binding.js:13:13)
    at Object.<anonymous> (D:\workspace\fusion_proj\node_modules\node-sass\lib\index.js:14:35)
    at Object.<anonymous> (D:\workspace\fusion_proj\node_modules\node-sass\lib\index.js:477:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.sassLoader (D:\workspace\fusion_proj\node_modules\sass-loader\lib\loader.js:46:72)

 @ ./src/common/style/ui/index.scss 4:14-224 14:3-18:5 15:22-232
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/module/demo/ui/App.vue?vue&type=script&lang=js&
 @ ./src/module/demo/ui/App.vue?vue&type=script&lang=js&
 @ ./src/module/demo/ui/App.vue
 @ ./src/module/demo/ui/main.js
 @ multi ./build/dev-client ./src/module/demo/ui/main.js ./src/common/script/console_text.js

 error  in ./src/common/style/ui/_reset.scss

Module build failed: Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (69)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.11.0
    at module.exports (D:\workspace\fusion_proj\node_modules\node-sass\lib\binding.js:13:13)
    at Object.<anonymous> (D:\workspace\fusion_proj\node_modules\node-sass\lib\index.js:14:35)
    at Object.<anonymous> (D:\workspace\fusion_proj\node_modules\node-sass\lib\index.js:477:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.sassLoader (D:\workspace\fusion_proj\node_modules\sass-loader\lib\loader.js:46:72)

 @ ./src/common/style/ui/_reset.scss 4:14-225 14:3-18:5 15:22-233
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/module/demo/ui/App.vue?vue&type=script&lang=js&
 @ ./src/module/demo/ui/App.vue?vue&type=script&lang=js&
 @ ./src/module/demo/ui/App.vue
 @ ./src/module/demo/ui/main.js
 @ multi ./build/dev-client ./src/module/demo/ui/main.js ./src/common/script/console_text.js

ERROR in ./node_modules/css-loader/dist/cjs.js??ref--11-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/lib??ref--11-2!./node_modules/sass-loader/lib/loader.js??ref--11-3!./node_modules/vue-loader/lib??vue-loader-options!./src/module/demo/ui/App.vue?vue&type=style&index=0&lang=scss&
Module build failed: Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (69)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.11.0
    at module.exports (D:\workspace\fusion_proj\node_modules\node-sass\lib\binding.js:13:13)
    at Object.<anonymous> (D:\workspace\fusion_proj\node_modules\node-sass\lib\index.js:14:35)
    at Object.<anonymous> (D:\workspace\fusion_proj\node_modules\node-sass\lib\index.js:477:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.sassLoader (D:\workspace\fusion_proj\node_modules\sass-loader\lib\loader.js:46:72)
 @ ./node_modules/vue-style-loader!./node_modules/css-loader/dist/cjs.js??ref--11-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/lib??ref--11-2!./node_modules/sass-loader/lib/loader.js??ref--11-3!./node_modules/vue-loader/lib??vue-loader-options!./src/module/demo/ui/App.vue?vue&type=style&index=0&lang=scss& 4:14-391 14:3-18:5 15:22-399
 @ ./src/module/demo/ui/App.vue?vue&type=style&index=0&lang=scss&
 @ ./src/module/demo/ui/App.vue
 @ ./src/module/demo/ui/main.js
 @ multi ./build/dev-client ./src/module/demo/ui/main.js ./src/common/script/console_text.js

ERROR in ./node_modules/css-loader/dist/cjs.js??ref--11-1!./node_modules/postcss-loader/lib??ref--11-2!./node_modules/sass-loader/lib/loader.js??ref--11-3!./src/common/style/ui/index.scss
Module build failed: Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (69)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.11.0
    at module.exports (D:\workspace\fusion_proj\node_modules\node-sass\lib\binding.js:13:13)
    at Object.<anonymous> (D:\workspace\fusion_proj\node_modules\node-sass\lib\index.js:14:35)
    at Object.<anonymous> (D:\workspace\fusion_proj\node_modules\node-sass\lib\index.js:477:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.sassLoader (D:\workspace\fusion_proj\node_modules\sass-loader\lib\loader.js:46:72)
 @ ./src/common/style/ui/index.scss 4:14-224 14:3-18:5 15:22-232
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/module/demo/ui/App.vue?vue&type=script&lang=js&
 @ ./src/module/demo/ui/App.vue?vue&type=script&lang=js&
 @ ./src/module/demo/ui/App.vue
 @ ./src/module/demo/ui/main.js
 @ multi ./build/dev-client ./src/module/demo/ui/main.js ./src/common/script/console_text.js

ERROR in ./node_modules/css-loader/dist/cjs.js??ref--11-1!./node_modules/postcss-loader/lib??ref--11-2!./node_modules/sass-loader/lib/loader.js??ref--11-3!./src/common/style/ui/_reset.scss
Module build failed: Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (69)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.11.0
    at module.exports (D:\workspace\fusion_proj\node_modules\node-sass\lib\binding.js:13:13)
    at Object.<anonymous> (D:\workspace\fusion_proj\node_modules\node-sass\lib\index.js:14:35)
    at Object.<anonymous> (D:\workspace\fusion_proj\node_modules\node-sass\lib\index.js:477:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.sassLoader (D:\workspace\fusion_proj\node_modules\sass-loader\lib\loader.js:46:72)
 @ ./src/common/style/ui/_reset.scss 4:14-225 14:3-18:5 15:22-233
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/module/demo/ui/App.vue?vue&type=script&lang=js&
 @ ./src/module/demo/ui/App.vue?vue&type=script&lang=js&
 @ ./src/module/demo/ui/App.vue
 @ ./src/module/demo/ui/main.js
 @ multi ./build/dev-client ./src/module/demo/ui/main.js ./src/common/script/console_text.js

**Comment by xzyfer** [comment]
I don't recognise the node version being used here. Are you running inside some strange environment like electron?

**Comment by Lynn-cc** [comment]
@xzyfer yes,electron

**Comment by xzyfer** [comment]
Electron doesn't co-ordinate their V8 updates with nodejs do we cannot
officially support it. When electron is using a release that matches nodejs
then it will work.

You can try changing your electron version until you find one that works.
There's nothing we can do for the time being.

**Comment by Lynn-cc** [comment]
Ok.
Thank you.

**Comment by Lynn-cc** [comment]
@xzyfer there's another problem, could you give me some advice? That is when I use `fork` to run a script that the error shows, but no errors when I use `exec` to run a command with the same function. (I had to use `fork` because I need the`ipc` to comunicate with child process)

**Comment by Lynn-cc** [comment]
I solved this !
With the problem I said in last comment that `exec` is ok but `fork` can't. So I found the `fork` description in the node doc:
```
By default, child_process.fork() will spawn new Node.js instances using the process.execPath of the parent process. The execPath property in the options object allows for an alternative execution path to be used.
```

And then I set the `execPath` path option to my local node path and it works. Now I can use both `fork` with `ipc` communication channel in electron.

**Comment by kingdragon2108** [comment]
i have same error suddenly. Could you explain about me?
i want you advice sincerely.
