### ISSUE TITLE
[Unsupported] Installing 4.7.2 with Node 6.9.1

### ISSUE THREAD

**Issue by opsaharan01** [sass/node-sass#2618]
Teamcity  build unable to install node-sass.

Facing an issue to installing node-sass@4.7.2 with node@6.9.1, even I tried "npm rebuild node-sass" as suggested in any other QA.

Building it on linux x64 build server, as its on build server I don't have much controls to experiments over there.

**npm@3.10.8
node@v6.9.1
node-sass@4.7.2
linux x64**

npm info lifecycle node-sass@4.7.2  install: node-sass@4.7.2
[13:36:51][Step 3/8] 
[13:36:51][Step 3/8] > node-sass@4.7.2 install /export/agt/BuildAgent/work/a036dfc53f5/node_modules/node-sass
[13:36:51][Step 3/8] > node scripts/install.js
[13:36:51][Step 3/8] 
**[13:36:52][Step 3/8] Downloading binary from https://github.com/sass/node-sass/releases/download/v4.7.2/linux-x64-48_binding.node
[13:36:52][Step 3/8] Cannot download "https://github.com/sass/node-sass/releases/download/v4.7.2/linux-x64-48_binding.node": 
[13:36:52][Step 3/8] 
[13:36:52][Step 3/8] getaddrinfo ENOTFOUND github.com github.com:443
[13:36:52][Step 3/8] 
[13:36:52][Step 3/8] Hint: If github.com is not accessible in your location
[13:36:52][Step 3/8]       try setting a proxy via HTTP_PROXY, e.g. 
[13:36:52][Step 3/8] 
[13:36:52][Step 3/8]       export HTTP_PROXY=http://example.com:1234
[13:36:52][Step 3/8] 
[13:36:52][Step 3/8] or configure npm proxy via**
[13:36:52][Step 3/8] 
[13:36:52][Step 3/8]       npm config set proxy http://example.com:8080
[13:36:52][Step 3/8] npm info lifecycle abbrev@1.1.1 postinstall: abbrev@1.1.1
[13:36:52][Step 3/8] npm info lifecycle amdefine@1.0.1 postinstall: amdefine@1.0.1
[13:36:52][Step 3/8] npm info lifecycle ansi-regex@2.1.1 postinstall: ansi-regex@2.1.1
..........
[13:36:53][Step 3/8] npm info lifecycle node-sass@4.7.2 postinstall: node-sass@4.7.2
[13:36:53][Step 3/8] 
[13:36:53][Step 3/8] > node-sass@4.7.2 postinstall /export/ agt/BuildAgent/work/a36dfc53f5/node_modules/node-sass
[13:36:53][Step 3/8] > node scripts/build.js
[13:36:53][Step 3/8] 
[13:36:53][Step 3/8] Building: /xenv/NodeJS/X/6.9.1/bin/node /export/ agt/BuildAgent/work/a36dfc53f5/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
[13:36:53][Step 3/8] gyp info it worked if it ends with ok
[13:36:53][Step 3/8] gyp verb cli [ '/xenv/NodeJS/X/6.9.1/bin/node',
[13:36:53][Step 3/8] gyp verb cli   '/export/ agt/BuildAgent/work/a36dfc53f5/node_modules/node-gyp/bin/node-gyp.js',
[13:36:53][Step 3/8] gyp verb cli   'rebuild',
[13:36:53][Step 3/8] gyp verb cli   '--verbose',
[13:36:53][Step 3/8] gyp verb cli   '--libsass_ext=',
[13:36:53][Step 3/8] gyp verb cli   '--libsass_cflags=',
[13:36:53][Step 3/8] gyp verb cli   '--libsass_ldflags=',
[13:36:53][Step 3/8] gyp verb cli   '--libsass_library=' ]
[13:36:53][Step 3/8] gyp info using node-gyp@3.8.0
[13:36:53][Step 3/8] gyp info using node@6.9.1 | linux | x64
[13:36:53][Step 3/8] gyp verb command rebuild []
[13:36:53][Step 3/8] gyp verb command clean []
[13:36:53][Step 3/8] gyp verb clean removing "build" directory
[13:36:53][Step 3/8] gyp verb command configure []
[13:36:53][Step 3/8] gyp verb check python checking for Python executable "python2" in the PATH
[13:36:53][Step 3/8] gyp verb `which` succeeded python2 /usr/bin/python2
[13:36:53][Step 3/8] gyp verb check python version `/usr/bin/python2 -c "import sys; print "2.6.6
[13:36:53][Step 3/8] gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
[13:36:53][Step 3/8] gyp verb get node dir no --target version specified, falling back to host node version: 6.9.1
[13:36:53][Step 3/8] gyp verb command install [ '6.9.1' ]
[13:36:53][Step 3/8] gyp verb install input version string "6.9.1"
[13:36:53][Step 3/8] gyp verb install installing version: 6.9.1
[13:36:53][Step 3/8] gyp verb install --ensure was passed, so won't reinstall if already installed
[13:36:53][Step 3/8] gyp verb install version not already installed, continuing with install 6.9.1
[13:36:53][Step 3/8] gyp verb ensuring nodedir is created /export/ agt/.node-gyp/6.9.1
[13:36:53][Step 3/8] gyp verb created nodedir /export/ agt/.node-gyp
[13:36:53][Step 3/8] gyp http GET https://nodejs.org/download/release/v6.9.1/node-v6.9.1-headers.tar.gz
[13:36:54][Step 3/8] gyp WARN install got an error, rolling back install
[13:36:54][Step 3/8] gyp verb command remove [ '6.9.1' ]
[13:36:54][Step 3/8] gyp verb remove using node-gyp dir: /export/ agt/.node-gyp
[13:36:54][Step 3/8] gyp verb remove removing target version: 6.9.1
[13:36:54][Step 3/8] gyp verb remove removing development files for version: 6.9.1
[13:36:54][Step 3/8] gyp ERR! configure error 
[13:36:54][Step 3/8] gyp ERR! stack Error: This is most likely not a problem with node-gyp or the package itself and
[13:36:54][Step 3/8] gyp ERR! stack is related to network connectivity. In most cases you are behind a proxy or have bad 
[13:36:54][Step 3/8] gyp ERR! stack network settings.
[13:36:54][Step 3/8] gyp ERR! stack     at Request.<anonymous> (/export/ agt/BuildAgent/work/a36dfc53f5/node_modules/node-gyp/lib/install.js:197:21)
[13:36:54][Step 3/8] gyp ERR! stack     at emitOne (events.js:96:13)
[13:36:54][Step 3/8] gyp ERR! stack     at Request.emit (events.js:188:7)
[13:36:54][Step 3/8] gyp ERR! stack     at Request.onRequestError (/export/ agt/BuildAgent/work/a36dfc53f5/node_modules/node-gyp/node_modules/request/request.js:881:8)
[13:36:54][Step 3/8] gyp ERR! stack     at emitOne (events.js:96:13)
[13:36:54][Step 3/8] gyp ERR! stack     at ClientRequest.emit (events.js:188:7)
[13:36:54][Step 3/8] gyp ERR! stack     at TLSSocket.socketErrorListener (_http_client.js:310:9)
[13:36:54][Step 3/8] gyp ERR! stack     at emitOne (events.js:96:13)
[13:36:54][Step 3/8] gyp ERR! stack     at TLSSocket.emit (events.js:188:7)
[13:36:54][Step 3/8] gyp ERR! stack     at connectErrorNT (net.js:1020:8)
[13:36:54][Step 3/8] gyp ERR! System Linux 2.6.32-754.11.1.el6.x86_64
[13:36:54][Step 3/8] gyp ERR! command "/xenv/NodeJS/X/6.9.1/bin/node" "/export/ agt/BuildAgent/work/a36dfc53f5/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
[13:36:54][Step 3/8] gyp ERR! cwd /export/ agt/BuildAgent/work/a36dfc53f5/node_modules/node-sass
[13:36:54][Step 3/8] gyp ERR! node -v v6.9.1
[13:36:54][Step 3/8] gyp ERR! node-gyp -v v3.8.0
[13:36:54][Step 3/8] gyp ERR! not ok 
[13:36:54][Step 3/8] Build failed with error code: 1
[13:36:54][Step 3/8] npm info lifecycle node-sass@4.7.2 postinstall: Failed to exec postinstall script
[13:36:59][Step 3/8] npm ERR! Linux 2.6.32-754.11.1.el6.x86_64
[13:36:59][Step 3/8] npm ERR! argv "/xenv/NodeJS/X/6.9.1/bin/node" "/xenv/NodeJS/X/6.9.1/bin/npm" "install" "node-sass@4.7.2"
[13:36:59][Step 3/8] npm ERR! node v6.9.1
[13:36:59][Step 3/8] npm ERR! npm  v3.10.8
[13:36:59][Step 3/8] npm ERR! code ELIFECYCLE
[13:36:59][Step 3/8] 
[13:36:59][Step 3/8] npm ERR! node-sass@4.7.2 postinstall: `node scripts/build.js`
[13:36:59][Step 3/8] npm ERR! Exit status 1
[13:36:59][Step 3/8] npm ERR! 
[13:36:59][Step 3/8] npm ERR! Failed at the node-sass@4.7.2 postinstall script 'node scripts/build.js'.
[13:36:59][Step 3/8] npm ERR! Make sure you have the latest version of node.js and npm installed.
[13:36:59][Step 3/8] npm ERR! If you do, this is most likely a problem with the node-sass package,
[13:36:59][Step 3/8] npm ERR! not with npm itself.
[13:36:59][Step 3/8] npm ERR! Tell the author that this fails on your system:
[13:36:59][Step 3/8] npm ERR!     node scripts/build.js
[13:36:59][Step 3/8] npm ERR! You can get information on how to open an issue for this project with:
[13:36:59][Step 3/8] npm ERR!     npm bugs node-sass
[13:36:59][Step 3/8] npm ERR! Or if that isn't available, you can get their info via:
[13:36:59][Step 3/8] npm ERR!     npm owner ls node-sass
[13:36:59][Step 3/8] npm ERR! There is likely additional logging output above.
[13:36:59][Step 3/8] 
[13:36:59][Step 3/8] npm ERR! Please include the following file with any support request:
[13:36:59][Step 3/8] npm ERR!     /export/ agt/BuildAgent/work/a36dfc53f5/npm-debug.log
[13:37:00][Step 3/8] npm info it worked if it ends with ok
[13:37:00][Step 3/8] npm info using npm@3.10.8
[13:37:00][Step 3/8] npm info using node@v6.9.1

=============================================
**package.json**

 ```
 "dependencies": {
    "@angular/animations": "^5.2.11",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/router": "^5.2.0",
    "core-js": "^2.4.1",    
    "rxjs": "^5.5.6",
    "web-animations-js": "^2.3.1",
    "zone.js": "^0.8.19",
    "node-sass": "4.7.2"
  },
  "devDependencies": {
    "@angular/cli": "~1.7.4",
    "@angular/compiler-cli": "^5.2.0",
    "@angular/language-service": "^5.2.0",
    "@types/jasmine": "~2.8.3",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",   
    "protractor": "^5.4.2",
    "ts-node": "~4.1.0",
    "tslint": "~5.9.1",
    "typescript": "~2.5.3"
  }
```

**Comment by xzyfer** [comment]
Your network was unable to access the binary at
https://github.com/sass/node-sass/releases/download/v4.7.2/linux-x64-48_binding.node
.

Check that you can download the file with your network or configure npm
with your proxy settings.
