### ISSUE TITLE
latest 4.12.0 version doesn't support nodejs 6.9.1

### ISSUE THREAD

**Issue by kadinwu** [sass/node-sass#2652]
NPM version (npm -v): 3.10.8
Node version (node -v): 6.9.1
Node Process (node -p process.versions): 6.9.1
Node Platform (node -p process.platform): Linux
Node architecture (node -p process.arch): x64
node-sass version (node -p "require('node-sass').info"): 4.12.0
npm node-sass versions (npm ls node-sass): 4.12.0

npm install which will install latest node-sasss 4.12.0 version, failed with below errors.
4.11.0 version is fine.

Detail logs:
```
222424 verbose lifecycle node-sass@4.12.0~postinstall: CWD: C:\frontend\node_modules\node-sass
222425 silly lifecycle node-sass@4.12.0~postinstall: Args: [ '/d /s /c', 'node scripts/build.js' ]
222426 silly lifecycle node-sass@4.12.0~postinstall: Returned: code: 1  signal: null
222427 info lifecycle node-sass@4.12.0~postinstall: Failed to exec postinstall script
222428 verbose unlock done using C:\Users\wuhongwe.CORPDOM\AppData\Roaming\npm-cache\_locks\staging-23a59feab1bf2de9.lock for C:\frontend\node_modules\.staging
222429 silly rollbackFailedOptional Starting
222430 silly rollbackFailedOptional Finishing
222431 silly runTopLevelLifecycles Finishing
222432 silly install printInstalled
222433 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
222434 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
222435 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
222435 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
222435 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
222435 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
222436 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.3 (node_modules\sane\node_modules\fsevents):
222437 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
222438 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
222438 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
222438 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
222438 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
222439 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\nodemon\node_modules\chokidar\node_modules\fsevents):
222440 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
222441 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
222441 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
222441 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
222441 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
222442 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\watchpack\node_modules\chokidar\node_modules\fsevents):
222443 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
222444 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
222444 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
222444 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
222444 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
222445 warn react-mfb@0.6.0 requires a peer of react@^15.3.1 but none was installed.
222446 verbose If you need help, you may report this error at:
222446 verbose     <https://github.com/npm/npm/issues>
222447 warn react-dom@15.6.2 requires a peer of react@^15.6.2 but none was installed.
222448 verbose If you need help, you may report this error at:
222448 verbose     <https://github.com/npm/npm/issues>
222449 warn @micro-focus/quantum-ux-grommet@1.0.33 requires a peer of quantum-ux@^1.0.21 but none was installed.
222450 verbose If you need help, you may report this error at:
222450 verbose     <https://github.com/npm/npm/issues>
222451 warn @micro-focus/quantum-ux-grommet@1.0.33 requires a peer of react@^15.6.1 but none was installed.
222452 verbose If you need help, you may report this error at:
222452 verbose     <https://github.com/npm/npm/issues>
222453 warn @micro-focus/quantum-ux-grommet@1.0.33 requires a peer of react-dom@15.6.1 but none was installed.
222454 verbose If you need help, you may report this error at:
222454 verbose     <https://github.com/npm/npm/issues>
222455 warn react-daterange-picker@2.0.1 requires a peer of moment-range@^3.0.3 but none was installed.
222456 verbose If you need help, you may report this error at:
222456 verbose     <https://github.com/npm/npm/issues>
222457 warn react-addons-test-utils@15.6.2 requires a peer of react-dom@^15.4.2 but none was installed.
222458 verbose If you need help, you may report this error at:
222458 verbose     <https://github.com/npm/npm/issues>
222459 warn eslint-config-airbnb@9.0.1 requires a peer of eslint@^2.9.0 but none was installed.
222460 verbose If you need help, you may report this error at:
222460 verbose     <https://github.com/npm/npm/issues>
222461 warn eslint-config-airbnb@9.0.1 requires a peer of eslint-plugin-import@^1.7.0 but none was installed.
222462 verbose If you need help, you may report this error at:
222462 verbose     <https://github.com/npm/npm/issues>
222463 warn eslint-config-airbnb@9.0.1 requires a peer of eslint-plugin-react@^5.0.1 but none was installed.
222464 verbose If you need help, you may report this error at:
222464 verbose     <https://github.com/npm/npm/issues>
222465 warn eslint-config-airbnb-base@3.0.1 requires a peer of eslint@^2.9.0 but none was installed.
222466 verbose If you need help, you may report this error at:
222466 verbose     <https://github.com/npm/npm/issues>
222467 warn eslint-config-airbnb-base@3.0.1 requires a peer of eslint-plugin-import@^1.7.0 but none was installed.
222468 verbose If you need help, you may report this error at:
222468 verbose     <https://github.com/npm/npm/issues>
222469 warn redux-app@1.0.0 license should be a valid SPDX license expression
222470 verbose If you need help, you may report this error at:
222470 verbose     <https://github.com/npm/npm/issues>
222471 verbose stack Error: node-sass@4.12.0 postinstall: `node scripts/build.js`
222471 verbose stack Exit status 1
222471 verbose stack     at EventEmitter.<anonymous> (C:\frontend\node\node_modules\npm\lib\utils\lifecycle.js:255:16)
222471 verbose stack     at emitTwo (events.js:106:13)
222471 verbose stack     at EventEmitter.emit (events.js:191:7)
222471 verbose stack     at ChildProcess.<anonymous> (C:\frontend\node\node_modules\npm\lib\utils\spawn.js:40:14)
222471 verbose stack     at emitTwo (events.js:106:13)
222471 verbose stack     at ChildProcess.emit (events.js:191:7)
222471 verbose stack     at maybeClose (internal/child_process.js:877:16)
222471 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
222472 verbose pkgid node-sass@4.12.0
222473 verbose cwd C:\frontend
222474 error Windows_NT 10.0.16299
222475 error argv "C:\\frontend\\node\\node.exe" "C:\\frontend\\node\\node_modules\\npm\\bin\\npm-cli.js" "install" "--proxy=http://web-proxy.houston.softwaregrp.net:8080"
222476 error node v6.9.1
222477 error npm  v3.10.8
222478 error code ELIFECYCLE
222479 error node-sass@4.12.0 postinstall: `node scripts/build.js`
222479 error Exit status 1
222480 error Failed at the node-sass@4.12.0 postinstall script 'node scripts/build.js'.
222480 error Make sure you have the latest version of node.js and npm installed.
222480 error If you do, this is most likely a problem with the node-sass package,
222480 error not with npm itself.
222480 error Tell the author that this fails on your system:
222480 error     node scripts/build.js
222480 error You can get information on how to open an issue for this project with:
222480 error     npm bugs node-sass
222480 error Or if that isn't available, you can get their info via:
222480 error     npm owner ls node-sass
222480 error There is likely additional logging output above.
222481 verbose exit [ 1, true ]
```

**Comment by xzyfer** [comment]
Please post the full log output. The error is not in the output you've
provided

**Comment by omguddu99** [comment]
why this error is coming while installing node-sass any version.
![image](https://user-images.githubusercontent.com/49862325/57777193-e37fec00-773e-11e9-9a00-e8046c44cce4.png)

**Comment by ShahanaFarooqui** [comment]
+3. We are using node-sass in our application and 3 of our rpi user are facing the same issue. I have requested them to provide the full log but npm doesn’t provide more detailed log than you already have it here, ie. ‘222480 error Failed at the node-sass@4.12.0 postinstall script 'node scripts/build.js’.

**Comment by bereska** [comment]
hi all, here is the log file https://www.dropbox.com/s/etdeio90ca62s0r/2019-05-13T18_11_26_044Z-debug.log?dl=0

**Comment by blockhart** [comment]
I found this googling the same issue : "Failed at the node-sass@4.12.0 postinstall script."

node version 11.13.0
npm version 6.9.0
sass version 1.20.1

**Comment by bereska** [comment]
just want to confirm that there is still an issue even after running 'npm cache clear', 'npm cache verify' and 'npm install'

**Comment by blockhart** [comment]
I just completely reinstalled (from erased drive) MacOS Mojave (10.14.5) and did little else but install node and npm (direct download from their site) and then gulp and then node-sass.  I still get the "Failed at the node-sass@4.12.0 postinstall script." Log of install below.
[2019-05-23T04_34_55_052Z-debug.log](https://github.com/sass/node-sass/files/3210269/2019-05-23T04_34_55_052Z-debug.log)

**Comment by ShahanaFarooqui** [comment]
Hi. The issue still has awaiting response label, so just wanted to confirm, if it is still waiting for any response from us?

**Comment by xzyfer** [comment]
npm install --unsafe-perms
