### ISSUE TITLE
Distribution support for linux s390x?

### ISSUE THREAD

**Issue by viane** [sass/node-sass#2658]
Hi, is it possible to contribute s390x binaries to the official repo without providing a s390x env? I have built those by using node v8-v11 under a real s390x node but unfortunately there is no way for me to get a public one for testing...

[linux-s390x-57_binding.node.zip](https://github.com/sass/node-sass/files/3135422/linux-s390x-57_binding.node.zip)
[linux-s390x-59_binding.node.zip](https://github.com/sass/node-sass/files/3135423/linux-s390x-59_binding.node.zip)
[linux-s390x-64_binding.node.zip](https://github.com/sass/node-sass/files/3135424/linux-s390x-64_binding.node.zip)
[linux-s390x-67_binding.node.zip](https://github.com/sass/node-sass/files/3135425/linux-s390x-67_binding.node.zip)

**Comment by nschonni** [comment]
Unless we can get a CI to consistently produce the binaries as part of our release process, we can't support the platform. This is similar to the requests for ARM support (which may change if the CI testing for that works out)

**Comment by saper** [comment]
@viane could this work under Hercules or something?

**Comment by viane** [comment]
@saper I read couple things about Hercules simulator running zlinux, and it sounds very achievable, i will play around the simulator and get back to you guys. Big thanks for brought this up!

**Comment by saper** [comment]
While here we don't we get node-sass working on MVS :)

**Comment by nschonni** [comment]
Looks like Travis has added support now https://blog.travis-ci.com/2019-11-12-multi-cpu-architecture-ibm-power-ibm-z

**Comment by viane** [comment]
I tested build with travis, they seems like having issue with s390x arch builds. Will come back on this once they resolve the issue.

Also in few failed s390x builds, they are 2 common failing testcases:

```
  6084 passing (35s)
  753 pending
  2 failing
  1) binding missing error should be useful:
     Error: Node Sass does not yet support your current environment: Unsupported platform (unknown) 64-bit with Node.js 6.x
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.13.0
      at module.exports (lib/binding.js:13:13)
      at test/binding.js:16:22
      at _tryBlock (assert.js:320:5)
      at _throws (assert.js:339:12)
      at Function.throws (assert.js:369:3)
      at Context.<anonymous> (test/binding.js:15:14)
  2) binding missing error should list currently installed bindings:
     Error: Node Sass does not yet support your current environment: Unsupported platform (unknown) 64-bit with Node.js 6.x
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.13.0
      at module.exports (lib/binding.js:13:13)
      at test/binding.js:28:22
      at _tryBlock (assert.js:320:5)
      at _throws (assert.js:339:12)
      at Function.throws (assert.js:369:3)
      at Context.<anonymous> (test/binding.js:27:14)
```

**Comment by nschonni** [comment]
It would also need to be added to the known architectures like in https://github.com/sass/node-sass/pull/2783

**Comment by saper** [comment]
@nschonni I think we should fix those tests...
