### ISSUE TITLE
I can not install the node-sass

### ISSUE THREAD

**Issue by EmirCanSANCAR** [sass/node-sass#2662]
I can not install the node-sass. Is there a problem in the package now?

```> node-sass@4.11.0 install C:\Users\emirc\www\exampleng\node_modules\@angular-devkit\build-angular\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.11.0/win32-x64-72_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.11.0/win32-x64-72_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.12.0 install C:\Users\emirc\www\exampleng\node_modules\node-sass
> node scripts/install.js

Cached binary found at C:\Users\emirc\AppData\Roaming\npm-cache\node-sass\4.12.0\win32-x64-72_binding.node

> node-sass@4.11.0 postinstall C:\Users\emirc\www\exampleng\node_modules\@angular-devkit\build-angular\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe C:\Users\emirc\www\exampleng\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\emirc\\www\\exampleng\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@12.1.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\emirc\www\exampleng\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\emirc\www\exampleng\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\emirc\www\exampleng\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\emirc\www\exampleng\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\emirc\www\exampleng\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\emirc\www\exampleng\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:166:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\emirc\www\exampleng\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\emirc\www\exampleng\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\emirc\www\exampleng\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\emirc\www\exampleng\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\emirc\www\exampleng\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\emirc\www\exampleng\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:166:21) {
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError ' +
gyp verb `which` failed     '(C:\\Users\\emirc\\www\\exampleng\\node_modules\\which\\which.js:13:12)\n ' +
gyp verb `which` failed     '   at F ' +
gyp verb `which` failed     '(C:\\Users\\emirc\\www\\exampleng\\node_modules\\which\\which.js:68:19)\n ' +
gyp verb `which` failed     '   at E ' +
gyp verb `which` failed     '(C:\\Users\\emirc\\www\\exampleng\\node_modules\\which\\which.js:80:29)\n ' +
gyp verb `which` failed     '   at ' +
gyp verb `which` failed     'C:\\Users\\emirc\\www\\exampleng\\node_modules\\which\\which.js:89:16\n   ' +
gyp verb `which` failed     ' at C:\\Users\\emirc\\www\\exampleng\\node_modules\\isexe\\index.js:42:5\n' +
gyp verb `which` failed     '    at ' +
gyp verb `which` failed     'C:\\Users\\emirc\\www\\exampleng\\node_modules\\isexe\\windows.js:36:5\n  ' +
gyp verb `which` failed     '  at FSReqCallback.oncomplete (fs.js:166:21)',
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Users\emirc\www\exampleng\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\emirc\www\exampleng\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\emirc\www\exampleng\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\emirc\www\exampleng\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\emirc\www\exampleng\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\emirc\www\exampleng\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:166:21)
gyp verb `which` failed  python Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Users\emirc\www\exampleng\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\emirc\www\exampleng\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\emirc\www\exampleng\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\emirc\www\exampleng\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\emirc\www\exampleng\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\emirc\www\exampleng\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:166:21) {
gyp verb `which` failed   stack: 'Error: not found: python\n    at getNotFoundError ' +
gyp verb `which` failed     '(C:\\Users\\emirc\\www\\exampleng\\node_modules\\which\\which.js:13:12)\n    at F ' +
gyp verb `which` failed     '(C:\\Users\\emirc\\www\\exampleng\\node_modules\\which\\which.js:68:19)\n    at E ' +
gyp verb `which` failed     '(C:\\Users\\emirc\\www\\exampleng\\node_modules\\which\\which.js:80:29)\n    at ' +
gyp verb `which` failed     'C:\\Users\\emirc\\www\\exampleng\\node_modules\\which\\which.js:89:16\n    at ' +
gyp verb `which` failed     'C:\\Users\\emirc\\www\\exampleng\\node_modules\\isexe\\index.js:42:5\n    at ' +
gyp verb `which` failed     'C:\\Users\\emirc\\www\\exampleng\\node_modules\\isexe\\windows.js:36:5\n    at ' +
gyp verb `which` failed     'FSReqCallback.oncomplete (fs.js:166:21)',
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\emirc\www\exampleng\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\emirc\www\exampleng\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at C:\Users\emirc\www\exampleng\node_modules\graceful-fs\polyfills.js:282:31
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:166:21)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\emirc\\www\\exampleng\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\emirc\www\exampleng\node_modules\@angular-devkit\build-angular\node_modules\node-sass
gyp ERR! node -v v12.1.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1

> node-sass@4.12.0 postinstall C:\Users\emirc\www\exampleng\node_modules\node-sass
> node scripts/build.js

Binary found at C:\Users\emirc\www\exampleng\node_modules\node-sass\vendor\win32-x64-72\binding.node
Testing binary
Binary is fine
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.11.0 (node_modules\@angular-devkit\build-angular\node_modules\node-sass):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.11.0 postinstall: `node scripts/build.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

added 4 packages from 2 contributors and audited 43140 packages in 10.073s
found 4 vulnerabilities (2 low, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details```

**Comment by xzyfer** [comment]
Updated node-sass to 4.12.0

**Comment by EmirCanSANCAR** [comment]
I get the error when I try to install by specifying the latest version. Do not have a way to install it?

```
C:\Users\emirc\www\exampleng>npm install node-sass@4.12.0

> node-sass@4.11.0 install C:\Users\emirc\www\exampleng\node_modules\@angular-devkit\build-angular\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://npm.taobao.org/mirrors/node-sass/v4.11.0/win32-x64-72_binding.node
Cannot download "https://npm.taobao.org/mirrors/node-sass/v4.11.0/win32-x64-72_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.12.0 install C:\Users\emirc\www\exampleng\node_modules\node-sass
> node scripts/install.js

Cached binary found at C:\Users\emirc\AppData\Roaming\npm-cache\node-sass\4.12.0\win32-x64-72_binding.node

> node-sass@4.11.0 postinstall C:\Users\emirc\www\exampleng\node_modules\@angular-devkit\build-angular\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe C:\Users\emirc\www\exampleng\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\emirc\\www\\exampleng\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@12.1.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb download using dist-url https://npm.taobao.org/dist
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\emirc\www\exampleng\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\emirc\www\exampleng\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\emirc\www\exampleng\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\emirc\www\exampleng\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\emirc\www\exampleng\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\emirc\www\exampleng\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:166:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\emirc\www\exampleng\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\emirc\www\exampleng\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\emirc\www\exampleng\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\emirc\www\exampleng\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\emirc\www\exampleng\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\emirc\www\exampleng\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:166:21) {
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError ' +
gyp verb `which` failed     '(C:\\Users\\emirc\\www\\exampleng\\node_modules\\which\\which.js:13:12)\n ' +
gyp verb `which` failed     '   at F ' +
gyp verb `which` failed     '(C:\\Users\\emirc\\www\\exampleng\\node_modules\\which\\which.js:68:19)\n ' +
gyp verb `which` failed     '   at E ' +
gyp verb `which` failed     '(C:\\Users\\emirc\\www\\exampleng\\node_modules\\which\\which.js:80:29)\n ' +
gyp verb `which` failed     '   at ' +
gyp verb `which` failed     'C:\\Users\\emirc\\www\\exampleng\\node_modules\\which\\which.js:89:16\n   ' +
gyp verb `which` failed     ' at C:\\Users\\emirc\\www\\exampleng\\node_modules\\isexe\\index.js:42:5\n' +
gyp verb `which` failed     '    at ' +
gyp verb `which` failed     'C:\\Users\\emirc\\www\\exampleng\\node_modules\\isexe\\windows.js:36:5\n  ' +
gyp verb `which` failed     '  at FSReqCallback.oncomplete (fs.js:166:21)',
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Users\emirc\www\exampleng\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\emirc\www\exampleng\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\emirc\www\exampleng\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\emirc\www\exampleng\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\emirc\www\exampleng\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\emirc\www\exampleng\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:166:21)
gyp verb `which` failed  python Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Users\emirc\www\exampleng\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\emirc\www\exampleng\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\emirc\www\exampleng\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\emirc\www\exampleng\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\emirc\www\exampleng\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\emirc\www\exampleng\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:166:21) {
gyp verb `which` failed   stack: 'Error: not found: python\n    at getNotFoundError ' +
gyp verb `which` failed     '(C:\\Users\\emirc\\www\\exampleng\\node_modules\\which\\which.js:13:12)\n    at F ' +
gyp verb `which` failed     '(C:\\Users\\emirc\\www\\exampleng\\node_modules\\which\\which.js:68:19)\n    at E ' +
gyp verb `which` failed     '(C:\\Users\\emirc\\www\\exampleng\\node_modules\\which\\which.js:80:29)\n    at ' +
gyp verb `which` failed     'C:\\Users\\emirc\\www\\exampleng\\node_modules\\which\\which.js:89:16\n    at ' +
gyp verb `which` failed     'C:\\Users\\emirc\\www\\exampleng\\node_modules\\isexe\\index.js:42:5\n    at ' +
gyp verb `which` failed     'C:\\Users\\emirc\\www\\exampleng\\node_modules\\isexe\\windows.js:36:5\n    at ' +
gyp verb `which` failed     'FSReqCallback.oncomplete (fs.js:166:21)',
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\emirc\www\exampleng\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\emirc\www\exampleng\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at C:\Users\emirc\www\exampleng\node_modules\graceful-fs\polyfills.js:282:31
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:166:21)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\emirc\\www\\exampleng\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\emirc\www\exampleng\node_modules\@angular-devkit\build-angular\node_modules\node-sass
gyp ERR! node -v v12.1.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1

> node-sass@4.12.0 postinstall C:\Users\emirc\www\exampleng\node_modules\node-sass
> node scripts/build.js

Binary found at C:\Users\emirc\www\exampleng\node_modules\node-sass\vendor\win32-x64-72\binding.node
Testing binary
Binary is fine
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.11.0 (node_modules\@angular-devkit\build-angular\node_modules\node-sass):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.11.0 postinstall: `node scripts/build.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ node-sass@4.12.0
updated 12 packages and audited 43140 packages in 24.738s
found 4 vulnerabilities (2 low, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details

C:\Users\emirc\www\exampleng>```

**Comment by xzyfer** [comment]
Looks like some other dependency has a dependency on node-sass@4.11.0. You
can confirm this by running npm ls node-sass. You can try running npm
update node-sass to update all the transitive node-sass dependencies.

**Comment by pablocarreraest** [comment]
im in the same problema... don't know what to do.

I try and try but m! m! is not working

**Comment by EmirCanSANCAR** [comment]
I've temporarily installed this way.
`npm install node-sass@4.12.0`

**Comment by pablocarreraest** [comment]
thanks @EmirCanSANCAR for the quick response I hace to downgrade my node version to node 10 is other posible solution.

🙃

**Comment by omguddu99** [comment]
why this error is coming while installing node-sass any version 

![image](https://user-images.githubusercontent.com/49862325/57777075-9a2f9c80-773e-11e9-945f-eaabdcec3108.png)

**Comment by matthiaslischka** [comment]
I downgraded node to fix the problem.
I now use [NVM](https://github.com/nvm-sh/nvm) to quickly switch between node versions in case this happens again. Very happy with this tool.

**Comment by omguddu99** [comment]
Thanks

**Comment by green6erry** [comment]
> I downgraded node to fix the problem.
> I now use [NVM](https://github.com/nvm-sh/nvm) to quickly switch between node versions. Very happy with this tool.

What did you downgrade to?

**Comment by nschonni** [comment]
Compatible versions are listed on the readme https://github.com/sass/node-sass#supported-nodejs-versions-vary-by-release-please-consult-the-releases-page-below-is-a-quick-guide-for-minimium-support

**Comment by j33n** [comment]
I used `nvm` and downgraded to `node v10`, you should be okay if you have compatible versions as mentioned 🔼

**Comment by GaryWenneker** [comment]
even if you're on Node 12, make sure you keep a local package of Node v 11 in your devdependencies: 

"node": "11.15.0",

Then it will work.

**Comment by xzyfer** [comment]
Update to 4.12 for node 12

**Comment by yairEO** [comment]
I also cannot install _node-sass_ `v4.12.0` with Node `v12.3.1` & NPM `6.9.0`

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.12.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.12.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by enricoreich** [comment]
Same problem here!

Tried to install node-sass 4.12.0 & 4.11.0 with nvm and node v10.16.0 (lts) & 11.15.0 & 12.4.0
Everytime I get this error:

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.12.0 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.12.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

What is going on?

**Comment by pssshete** [comment]
node-sass@4.12.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1

**Comment by pssshete** [comment]
p ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/angular-cli/node_modules/node-sass/.node-gyp'
gyp ERR! System Linux 4.15.0-51-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/angular-cli/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /usr/lib/node_modules/angular-cli/node_modules/node-sass
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
npm WARN @angular/core@2.4.10 requires a peer of rxjs@^5.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/angular-cli/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.12.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.12.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pranavshete/.npm/_logs/2019-06-21T06_09_10_071Z-debug.log

**Comment by xzyfer** [comment]
npm install node-sass--unsafe-perms

**Comment by willi-dev** [comment]
just update to node-sass `4.12.0` with node `v12.5` and it works for me!

**Comment by suminpixel** [comment]
sudo npm install --save-dev  --unsafe-perm node-sass
