### ISSUE TITLE
Cannot compile node-sass with Visual Studio 2019 installed

### ISSUE THREAD

**Issue by youfoundkris** [sass/node-sass#2700]
With Visual Studio 2019 installed the build of node-sass breaks.
Reinstalling Visual Studio 2017 along side does not solve the problem.

```
λ node -v
v12.4.0
```

```
λ npm -v
6.9.0
```

```
λ node -p process.versions
{
  node: '12.4.0',
  v8: '7.4.288.27-node.18',
  uv: '1.29.1',
  zlib: '1.2.11',
  brotli: '1.0.7',
  ares: '1.15.0',
  modules: '72',
  nghttp2: '1.38.0',
  napi: '4',
  llhttp: '1.1.3',
  http_parser: '2.8.0',
  openssl: '1.1.1b',
  cldr: '35.1',
  icu: '64.2',
  tz: '2019a',
  unicode: '12.1'
}
```

```
λ node -p process.platform
win32

```
```
λ node -p process.arch
x64
```

```
λ npm ls node-sass
cdhfrontend@0.1.0 C:\_projects\customer\project\src\Frontend\ClientApp
`-- node-sass@4.11.0
```

```
λ yarn install
yarn install v1.16.0
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.0.6: The platform "win32" is incompatible with this module.
info "fsevents@2.0.6" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.4: The platform "win32" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.9: The platform "win32" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > connected-react-router@6.4.0" has unmet peer dependency "history@^4.7.2".
warning " > connected-react-router@6.4.0" has incorrect peer dependency "react-redux@^6.0.0".
warning " > connected-react-router@6.4.0" has unmet peer dependency "react-router@^4.3.1 || ^5.0.0".
warning " > echarts-for-react@2.0.14" has unmet peer dependency "prop-types@^15.5.7".
[4/4] Building fresh packages...
[1/2] ⠐ node-sass
error C:\_projects\fake_customer\fake_project\src\Frontend\ClientApp\node_modules\node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: C:\_projects\fake_customer\fake_project\src\Frontend\ClientApp\node_modules\node-sass
Output:
Building: C:\Users\fake_user\scoop\apps\nodejs\current\node.exe C:\_projects\fake_customer\fake_project\src\Frontend\ClientApp\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\Users\\fake_user\\scoop\\apps\\nodejs\\current\\node.exe',
gyp verb cli   'C:\\_projects\\fake_customer\\fake_project\\src\\Frontend\\ClientApp\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@12.4.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 C:\Users\fake_user\scoop\shims\python2.EXE
gyp verb check python version `C:\Users\fake_user\scoop\shims\python2.EXE -c "import sys; print "2.7.16
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 12.4.0
gyp verb command install [ '12.4.0' ]
gyp verb install input version string "12.4.0"
gyp verb install installing version: 12.4.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 12.4.0
gyp verb build dir attempting to create "build" dir: C:\_projects\fake_customer\fake_project\src\Frontend\ClientApp\node_modules\node-sass\build
gyp verb build dir "build" dir needed to be created? C:\_projects\fake_customer\fake_project\src\Frontend\ClientApp\node_modules\node-sass\build
gyp verb find vs2017 Found installation at: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.Windows10SDK.17763
gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.VC.Tools.x86.x64
gyp verb find vs2017   - Found Microsoft.VisualStudio.VC.MSBuild.Base
gyp verb find vs2017   - Using this installation with Windows 10 SDK
gyp verb find vs2017 using installation: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: C:\_projects\fake_customer\fake_project\src\Frontend\ClientApp\node_modules\node-sass\build\config.gypi
gyp verb config.gypi checking for gypi file: C:\_projects\fake_customer\fake_project\src\Frontend\ClientApp\node_modules\node-sass\config.gypi
gyp verb common.gypi checking for gypi file: C:\_projects\fake_customer\fake_project\src\Frontend\ClientApp\node_modules\node-sass\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Users\fake_user\scoop\shims\python2.EXE
gyp info spawn args [
gyp info spawn args   'C:\\_projects\\fake_customer\\fake_project\\src\\Frontend\\ClientApp\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\_projects\\fake_customer\\fake_project\\src\\Frontend\\ClientApp\\node_modules\\node-sass\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\_projects\\fake_customer\\fake_project\\src\\Frontend\\ClientApp\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\fake_user\\.node-gyp\\12.4.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\fake_user\\.node-gyp\\12.4.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\_projects\\fake_customer\\fake_project\\src\\Frontend\\ClientApp\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\fake_user\\.node-gyp\\12.4.0\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\_projects\\fake_customer\\fake_project\\src\\Frontend\\ClientApp\\node_modules\\node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\_projects\\fake_customer\\fake_project\\src\\Frontend\\ClientApp\\node_modules\\node-sass\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir C:\Users\fake_user\.node-gyp\12.4.0
gyp verb found first Solution file build/binding.sln
gyp verb using MSBuild: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\15.0\Bin\MSBuild.exe ENOENT
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
gyp ERR! stack     at onErrorNT (internal/child_process.js:456:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:84:9)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Users\\fake_user\\scoop\\apps\\nodejs\\current\\node.exe" "C:\\_projects\\fake_customer\\fake_project\\src\\Frontend\\ClientApp\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\_projects\fake_customer\fake_project\src\Frontend\ClientApp\node_modules\node-sass
gyp ERR! node -v v12.4.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
Build failed with error code: 7
```

**Comment by xzyfer** [comment]
npm update node-sass to install the right version for node 12. This means you don't have tinxonoiy locally at all.
*****
```
gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\15.0\Bin\MSBuild.exe ENOENT
```
This error suggests a possible issue with node-gyp. It may not yet support vs2019. Try checking their issue tracker..

**Comment by junalmeida** [comment]
@xzyfer You might be correct that node-gyp@3.8.0 does not support vs 2019, however node-gyp is currently on version 6.
According to this https://github.com/nodejs/node-gyp/commit/360ddbdf3a (and changelog) it has been fixed on version 5.0.0

**Comment by nschonni** [comment]
@junalmeida node-gyp can't be bumped because the major version change breaks support for old Node versions that this current node-sass release still supports

**Comment by junalmeida** [comment]
> @junalmeida node-gyp can't be bumped because the major version change breaks support for old Node versions that this current node-sass release still supports

Ow, sad to read this bad news, seems like a deadlock 🤣 to me. I can't manage to compile this using latest visual studio on windows without really awful workarounds.

**Comment by X-Y** [comment]
Same issue here, have to use node 10.16.3 to go around the problem.
