### ISSUE TITLE
Problems with installing in Windows 10 NodeJS 10

### ISSUE THREAD

**Issue by dioubernardo** [sass/node-sass#2712]
```
T:\casca\js\lib.ts>npm install node-sass

> node-sass@4.12.0 install T:\casca\js\lib.ts\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.12.0/win32-x64-64_binding.node
Download complete..] - :
Binary saved to T:\casca\js\lib.ts\node_modules\node-sass\vendor\win32-x64-64\binding.node
Caching binary to C:\Users\Usuário\AppData\Roaming\npm-cache\node-sass\4.12.0\win32-x64-64_binding.node

> node-sass@4.12.0 postinstall T:\casca\js\lib.ts\node_modules\node-sass
> node scripts/build.js

Binary found at T:\casca\js\lib.ts\node_modules\node-sass\vendor\win32-x64-64\binding.node
Testing binary
Binary has a problem: { Error: Cannot find module 'lodash/cloneDeep'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (T:\casca\js\lib.ts\node_modules\node-sass\lib\index.js:6:15)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3) code: 'MODULE_NOT_FOUND' }
Building the binary locally
Building: C:\Program Files\nodejs\node.exe T:\casca\js\lib.ts\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'T:\\casca\\js\\lib.ts\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@10.16.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (T:\casca\js\lib.ts\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (T:\casca\js\lib.ts\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (T:\casca\js\lib.ts\node_modules\which\which.js:80:29)
gyp verb `which` failed     at T:\casca\js\lib.ts\node_modules\which\which.js:89:16
gyp verb `which` failed     at T:\casca\js\lib.ts\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at T:\casca\js\lib.ts\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:153:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (T:\casca\js\lib.ts\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (T:\casca\js\lib.ts\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (T:\casca\js\lib.ts\node_modules\which\which.js:80:29)
gyp verb `which` failed     at T:\casca\js\lib.ts\node_modules\which\which.js:89:16
gyp verb `which` failed     at T:\casca\js\lib.ts\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at T:\casca\js\lib.ts\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:153:21) code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (T:\casca\js\lib.ts\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (T:\casca\js\lib.ts\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (T:\casca\js\lib.ts\node_modules\which\which.js:80:29)
gyp verb `which` failed     at T:\casca\js\lib.ts\node_modules\which\which.js:89:16
gyp verb `which` failed     at T:\casca\js\lib.ts\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at T:\casca\js\lib.ts\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:153:21)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (T:\casca\js\lib.ts\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (T:\casca\js\lib.ts\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (T:\casca\js\lib.ts\node_modules\which\which.js:80:29)
gyp verb `which` failed     at T:\casca\js\lib.ts\node_modules\which\which.js:89:16
gyp verb `which` failed     at T:\casca\js\lib.ts\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at T:\casca\js\lib.ts\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:153:21) code: 'ENOENT' }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp verb check python version `C:\Python27\python.exe -c "import platform; print(platform.python_version());"` returned: "2.7.16\r\n"
gyp verb get node dir no --target version specified, falling back to host node version: 10.16.0
gyp verb command install [ '10.16.0' ]
gyp verb install input version string "10.16.0"
gyp verb install installing version: 10.16.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 10.16.0
gyp verb build dir attempting to create "build" dir: T:\casca\js\lib.ts\node_modules\node-sass\build
gyp verb build dir "build" dir needed to be created? T:\casca\js\lib.ts\node_modules\node-sass\build
gyp verb find vs2017 Found installation at: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community
gyp verb find vs2017   - Missing Visual Studio C++ core features (Microsoft.VisualStudio.VC.MSBuild.Base)
gyp verb find vs2017   - Missing VC++ 2017 v141 toolset (x86,x64) (Microsoft.VisualStudio.Component.VC.Tools.x86.x64)
gyp verb find vs2017   - Missing a Windows SDK (Microsoft.VisualStudio.Component.Windows10SDK.* or Microsoft.VisualStudio.Component.Windows81SDK)
gyp verb find vs2017   - Some required components are missing, not using this installation
gyp verb Not using VS2017: No usable installation of VS2017 found
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: T:\casca\js\lib.ts\node_modules\node-sass\build\config.gypi
gyp verb config.gypi checking for gypi file: T:\casca\js\lib.ts\node_modules\node-sass\config.gypi
gyp verb common.gypi checking for gypi file: T:\casca\js\lib.ts\node_modules\node-sass\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Python27\python.exe
gyp info spawn args [ 'T:\\casca\\js\\lib.ts\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'T:\\casca\\js\\lib.ts\\node_modules\\node-sass\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'T:\\casca\\js\\lib.ts\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Usuário\\.node-gyp\\10.16.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Usuário\\.node-gyp\\10.16.0',
gyp info spawn args   '-Dnode_gyp_dir=T:\\casca\\js\\lib.ts\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\Usuário\\.node-gyp\\10.16.0\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=T:\\casca\\js\\lib.ts\\node_modules\\node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'T:\\casca\\js\\lib.ts\\node_modules\\node-sass\\build',
gyp info spawn args   '-Goutput_dir=.' ]
```

**Comment by dioubernardo** [comment]
I just discovered that this error is occurring when I run npm install on a network share drive

**Comment by abdulsalamemesh** [comment]
I have the same problem, some binary link return 404

```

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.9.4/win32-x64-67_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.9.4/win32-x64-67_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080
``

**Comment by abdulsalamemesh** [comment]
i have the same problem, some binary link is returning `404`

```bash
Downloading binary from https://github.com/sass/node-sass/releases/download/v4.9.4/win32-x64-67_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.9.4/win32-x64-67_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

``

**Comment by xzyfer** [comment]
Explained in the very first line of the readme
