### ISSUE TITLE
Issue running: gulp compile

### ISSUE THREAD

**Issue by mgreen27** [sass/node-sass#2719]
Hello, Im getting the following error and wondering if you can asssit?

$ gulp compile
/home/matt/go/src/www.velocidex.com/golang/velociraptor/gui/static/node_modules/node-sass/lib/binding.js:13
      throw new Error(errors.unsupportedEnvironment());
      ^

Error: Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (72)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.11.0
    at module.exports (/home/matt/go/src/www.velocidex.com/golang/velociraptor/gui/static/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/home/matt/go/src/www.velocidex.com/golang/velociraptor/gui/static/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:868:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
    at Module.require (internal/modules/cjs/loader.js:771:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/home/matt/go/src/www.velocidex.com/golang/velociraptor/gui/static/node_modules/gulp-sass/index.js:162:21)
    at Module._compile (internal/modules/cjs/loader.js:868:30)

**--Troubleshooting information--**

$ node -p process.platform
linux

$ node -p process.arch
x64

$ node -p "require('node-sass').info"
/home/matt/go/src/www.velocidex.com/golang/velociraptor/gui/static/node_modules/node-sass/lib/binding.js:13
      throw new Error(errors.unsupportedEnvironment());
      ^

Error: Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (72)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.11.0
    at module.exports (/home/matt/go/src/www.velocidex.com/golang/velociraptor/gui/static/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/home/matt/go/src/www.velocidex.com/golang/velociraptor/gui/static/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:868:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
    at Module.require (internal/modules/cjs/loader.js:771:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at [eval]:1:1
    at Script.runInThisContext (vm.js:126:20)

$ npm ls node-sass
velociraptor-ui@0.0.2 /home/matt/go/src/www.velocidex.com/golang/velociraptor/gui/static
├─┬ gulp-sass@4.0.2
│ └── node-sass@4.11.0  deduped
└── node-sass@4.11.0 

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic

**Comment by xzyfer** [comment]
You need node-sass@4.12.0 for node 12 support.

**Comment by mgreen27** [comment]
Thank for that. I just installed version 12 and now getting an error that by bindings are version 11.
I have tried rebuilding node-sass and seem to be getting the same error.

$ npm ls node-sass
velociraptor-ui@0.0.2 /home/matt/go/src/www.velocidex.com/golang/velociraptor/gui/static
├─┬ gulp-sass@4.0.2
│ └── node-sass@4.12.0  deduped
└── node-sass@4.12.0 



**Error:**
$ node -p "require('node-sass').info"
/home/matt/go/src/www.velocidex.com/golang/velociraptor/gui/static/node_modules/node-sass/lib/binding.js:15
      throw new Error(errors.missingBinary());
      ^

Error: Missing binding /home/matt/go/src/www.velocidex.com/golang/velociraptor/gui/static/node_modules/node-sass/vendor/linux-x64-72/binding.node
Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 12.x

Found bindings for the following environments:
  - Linux 64-bit with Node.js 11.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to download the binding for your current environment.
    at module.exports (/home/matt/go/src/www.velocidex.com/golang/velociraptor/gui/static/node_modules/node-sass/lib/binding.js:15:13)
    at Object.<anonymous> (/home/matt/go/src/www.velocidex.com/golang/velociraptor/gui/static/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:868:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
    at Module.require (internal/modules/cjs/loader.js:771:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at [eval]:1:1
    at Script.runInThisContext (vm.js:126:20)

**Comment by xzyfer** [comment]
Looks like the install script didn't run. Try npm rebuild node-sass.

**Comment by mgreen27** [comment]
Thank you for the response, I treid that previously and just tried again but looks like the same issue:
Note: I also tried: npm rebuild node-sass -force

$ npm rebuild node-sass

> node-sass@4.12.0 install /home/matt/go/src/www.velocidex.com/golang/velociraptor/gui/static/node_modules/node-sass
> node scripts/install.js

node-sass build Binary found at /home/matt/go/src/www.velocidex.com/golang/velociraptor/gui/static/node_modules/node-sass/vendor/linux-x64-67/binding.node

> node-sass@4.12.0 postinstall /home/matt/go/src/www.velocidex.com/golang/velociraptor/gui/static/node_modules/node-sass
> node scripts/build.js

Binary found at /home/matt/go/src/www.velocidex.com/golang/velociraptor/gui/static/node_modules/node-sass/vendor/linux-x64-67/binding.node
Testing binary
Binary is fine
node-sass@4.12.0 /home/matt/go/src/www.velocidex.com/golang/velociraptor/gui/static/node_modules/node-sass
matt@uglyGorilla -> ~/g/s/w/g/v/g/static 
$ node -p "require('node-sass').info"
/home/matt/go/src/www.velocidex.com/golang/velociraptor/gui/static/node_modules/node-sass/lib/binding.js:15
      throw new Error(errors.missingBinary());
      ^

Error: Missing binding /home/matt/go/src/www.velocidex.com/golang/velociraptor/gui/static/node_modules/node-sass/vendor/linux-x64-72/binding.node
Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 12.x

Found bindings for the following environments:
  - Linux 64-bit with Node.js 11.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to download the binding for your current environment.
    at module.exports (/home/matt/go/src/www.velocidex.com/golang/velociraptor/gui/static/node_modules/node-sass/lib/binding.js:15:13)
    at Object.<anonymous> (/home/matt/go/src/www.velocidex.com/golang/velociraptor/gui/static/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:868:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
    at Module.require (internal/modules/cjs/loader.js:771:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at [eval]:1:1
    at Script.runInThisContext (vm.js:126:20)

**Comment by xzyfer** [comment]
You may have to delete the binding.node file referenced in the output so
that the rebuild command tries to fetch the binary.

**Comment by mgreen27** [comment]
Sorry for the late reply. I have just tried to remove the binding.node file referenced in there error and then rebuilt. I receive exactly the same error.

Error: Missing binding /home/matt/go/src/www.velocidex.com/golang/velociraptor/gui/static/node_modules/node-sass/vendor/linux-x64-72/binding.node

It looks like the rebuild adds a different version:
./node_modules/node-sass/vendor/linux-x64-67/binding.node 

Im wondering if there is a config somewhere I can set the right binding.node?

**Comment by mgreen27** [comment]
I just resolved my issue by installing an older version of node instead.
$ sudo npm install -g n
$ sudo n 11.15.0
(after confirming this version of node had the compatible binding.node)

**Comment by murraycollingwood** [comment]
Everybody tells us to upgrade to node-sass@4.12.0
I've also tried the rebuild but it fails miserably with errors.
So, can somebody please tell us how to upgrade to node-sass@4.12.0 on a fresh install without needing to downgrade 'node' ?

**Comment by saper** [comment]
I am sorry, "fail miserably with errors" is nothing we can help about. Please try to be as specific as possible.

After changing node engine version ALL binary node modules (not only node-sass) need to be rebuild from source. Sometimes it is faster to reinstall everything.

**Comment by murraycollingwood** [comment]
Hi Saper, sorry, I was frustrated at the time and needed to vent a little.  I had my son help fix it up, he knows a little more than I do and managed to get it working again.  Sorry, I'm not sure exactly what he did.

**Comment by saper** [comment]
No worries, glad you guys got it working!
