### ISSUE TITLE
Post install build failed

### ISSUE THREAD

**Issue by ChunAllen** [sass/node-sass#2722]
I'm currently running my build in Jenkins with Node `8.15.1`
and my current node-sass version is `4.12.0` in my devDependencies

I'm using a private registry since Jenkins cannot hit external network. 
But I tried also putting `sass-binary-path` / `sass-binary-site` from `.npmrc`

Here's the logs from Jenkins
```
+ node --version
v8.15.1
+ npm --version
6.4.1
+ npm config get registry
http://10.30.23.129:8081/repository/stb-npm-hosted/
+ echo 'Installing dependencies'
Installing dependencies
+ npm install

> node-sass@4.12.0 install /var/lib/jenkins/workspace/stb-tc.vs-app-admin.workspace/stb-tc.vs-app-admin-it/node_modules/node-sass
> node scripts/install.js

Cached binary found at /var/lib/jenkins/.npm/node-sass/4.12.0/linux-x64-57_binding.node

> bootstrap-vue@2.0.0-rc.14 postinstall /var/lib/jenkins/workspace/stb-tc.vs-app-admin.workspace/stb-tc.vs-app-admin-it/node_modules/bootstrap-vue
> opencollective || exit 0

                       Thanks for installing bootstrap-vue 
                 Please consider donating to our open collective
                        to help us maintain this package.
                                         
                                         
              Donate: https://opencollective.com/bootstrap-vue/donate
                                         

> node-sass@4.12.0 postinstall /var/lib/jenkins/workspace/stb-tc.vs-app-admin.workspace/stb-tc.vs-app-admin-it/node_modules/node-sass
> node scripts/build.js

Binary found at /var/lib/jenkins/workspace/stb-tc.vs-app-admin.workspace/stb-tc.vs-app-admin-it/node_modules/node-sass/vendor/linux-x64-57/binding.node
Testing binary
Binary has a problem: Error: /var/lib/jenkins/workspace/stb-tc.vs-app-admin.workspace/stb-tc.vs-app-admin-it/node_modules/node-sass/vendor/linux-x64-57/binding.node: invalid ELF header
    at Object.Module._extensions..node (module.js:682:18)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at module.exports (/var/lib/jenkins/workspace/stb-tc.vs-app-admin.workspace/stb-tc.vs-app-admin-it/node_modules/node-sass/lib/binding.js:19:10)
    at Object.<anonymous> (/var/lib/jenkins/workspace/stb-tc.vs-app-admin.workspace/stb-tc.vs-app-admin-it/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
Building the binary locally
Building: /usr/bin/node /var/lib/jenkins/workspace/stb-tc.vs-app-admin.workspace/stb-tc.vs-app-admin-it/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/bin/node',
gyp verb cli   '/var/lib/jenkins/workspace/stb-tc.vs-app-admin.workspace/stb-tc.vs-app-admin-it/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@8.15.1 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /bin/python2
gyp verb check python version `/bin/python2 -c "import sys; print "2.7.5
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 8.15.1
gyp verb command install [ '8.15.1' ]
gyp verb install input version string "8.15.1"
gyp verb install installing version: 8.15.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 8.15.1
gyp verb ensuring nodedir is created /var/lib/jenkins/.node-gyp/8.15.1
gyp verb created nodedir /var/lib/jenkins/.node-gyp/8.15.1
gyp http GET https://nodejs.org/download/release/v8.15.1/node-v8.15.1-headers.tar.gz
gyp WARN install got an error, rolling back install
gyp verb command remove [ '8.15.1' ]
gyp verb remove using node-gyp dir: /var/lib/jenkins/.node-gyp
gyp verb remove removing target version: 8.15.1
gyp verb remove removing development files for version: 8.15.1
gyp ERR! configure error 
gyp ERR! stack Error: connect ETIMEDOUT 104.20.23.46:443
gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
gyp ERR! System Linux 3.10.0-957.21.3.el7.x86_64
gyp ERR! command "/usr/bin/node" "/var/lib/jenkins/workspace/stb-tc.vs-app-admin.workspace/stb-tc.vs-app-admin-it/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /var/lib/jenkins/workspace/stb-tc.vs-app-admin.workspace/stb-tc.vs-app-admin-it/node_modules/node-sass
gyp ERR! node -v v8.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.12.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.12.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/lib/jenkins/.npm/_logs/2019-08-29T06_55_24_214Z-debug.log
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

Why does it still hitting nodejs.org to get 8.15.0 if I already setup a sass-binary-path in registry?

**Comment by ChunAllen** [comment]
@xzyfer I tried adding `npm cache clear` still not working even I added the `--force` flag

I tried another way
I downgraded to `node-sass v4.10.0` and remove `sass-binary-site` from `.npmrc`

but It now hits `https://github.com/sass/node-sass/releases/download/v4.10.0/linux-x64-57_binding.node` 

My question is how can I use `sass-binary-path` if I put the `linux-x64-57_binding.node` inside the root of my project? 

```
For example:
my-project/local-packages/linux-x64-57_binding.node
```

should it be `sass-binary-path`
```
sass-binary-path: ~/local-packages/linux-x64-57_binding.node
```
?

**Comment by ChunAllen** [comment]
Anyway working now I upgrade to `node-sass v4.11.0` 

Hope this will have a better resolution by including the linux node in node-sass package
