### ISSUE TITLE
node-sass 

### ISSUE THREAD

**Issue by d1y** [sass/node-sass#2727]
```console
 error  in ./src/pages/set/new_pwd/new_pwd.vue?vue&type=style&index=0&id=628a60ac&scoped=true&lang=scss&

Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Error: Missing binding /Users/kozo4/xx/ccy-web/node_modules/node-sass/vendor/darwin-x64-72/binding.node
Node Sass could not find a binding for your current environment: OS X 64-bit with Node.js 12.x

Found bindings for the following environments:
  - OS X 64-bit with Node.js 12.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to download the binding for your current environment.
    at module.exports (/Users/kozo4/xx/ccy-web/node_modules/node-sass/lib/binding.js:15:13)
    at Object.<anonymous> (/Users/kozo4/xx/ccy-web/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at getDefaultSassImpl (/Users/kozo4/xx/ccy-web/node_modules/sass-loader/dist/index.js:198:10)
    at Object.loader (/Users/kozo4/xx/ccy-web/node_modules/sass-loader/dist/index.js:80:29)

 @ ./node_modules/@dcloudio/vue-cli-plugin-uni/packages/h5-vue-style-loader??ref--8-oneOf-1-0!./node_modules/@dcloudio/vue-cli-plugin-uni/packages/webpack-preprocess-loader??ref--8-oneOf-1-1!./node_modules/css-loader/dist/cjs.js??ref--8-oneOf-1-2!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--8-oneOf-1-3!./node_modules/sass-loader/dist/cjs.js??ref--8-oneOf-1-4!./node_modules/@dcloudio/vue-cli-plugin-uni/packages/webpack-preprocess-loader??ref--8-oneOf-1-5!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/@dcloudio/vue-cli-plugin-uni/packages/webpack-custom-block-loader??ref--0-1!./node_modules/@dcloudio/vue-cli-plugin-uni/packages/webpack-scoped-loader!./src/pages/set/new_pwd/new_pwd.vue?vue&type=style&index=0&id=628a60ac&scoped=true&lang=scss& 4:14-874 14:3-18:5 15:22-882
 @ ./src/pages/set/new_pwd/new_pwd.vue?vue&type=style&index=0&id=628a60ac&scoped=true&lang=scss&
 @ ./src/pages/set/new_pwd/new_pwd.vue
 @ ./src/pages.json
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.0.129:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js
```

**Comment by d1y** [comment]
try all command

```console

npm rebuild node-sass

```

solve
