### ISSUE TITLE
Binary has a problem: Error: Cannot find module './_baseClone'

### ISSUE THREAD

**Issue by mahanteshk** [sass/node-sass#2733]
in a clean-up activity today we cleared yarn cache and when triggered the jenkin builds  below error is thrown.

Node version 11.0.0
npm version 6.11.3
yarn version 1.10.1

```
00:01:31.471 [4/4] Building fresh packages...
00:01:43.035 error E:\jenkins\workspace\Development\..\PrintApplication\node_modules\node-sass: Command failed.
00:01:43.035 Exit code: 1
00:01:43.035 Command: node scripts/build.js
00:01:43.035 Arguments: 
00:01:43.035 Directory: E:\jenkins\workspace\Development\..\PrintApplication\node_modules\node-sass
00:01:43.035 Output:
00:01:43.035 Binary found at E:\jenkins\workspace\Development\..\PrintApplication\node_modules\node-sass\vendor\win32-x64-67\binding.node
00:01:43.035 Testing binary
00:01:43.035 Binary has a problem: { Error: Cannot find module './_baseClone'
00:01:43.035     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
00:01:43.035     at Function.Module._load (internal/modules/cjs/loader.js:513:25)
00:01:43.035     at Module.require (internal/modules/cjs/loader.js:643:17)
00:01:43.035     at require (internal/modules/cjs/helpers.js:22:18)
00:01:43.035     at Object.<anonymous> (E:\jenkins\workspace\Development\..\PrintApplication\node_modules\lodash\cloneDeep.js:1:79)
00:01:43.035     at Module._compile (internal/modules/cjs/loader.js:707:30)
00:01:43.035     at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
00:01:43.035     at Module.load (internal/modules/cjs/loader.js:605:32)
00:01:43.035     at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
00:01:43.035     at Function.Module._load (internal/modules/cjs/loader.js:536:3) code: 'MODULE_NOT_FOUND' }
00:01:43.035 Building the binary locally
00:01:43.035 Building: C:\Program Files\nodejs\node.exe E:\jenkins\workspace\Development\..\PrintApplication\node_modules\node-sass\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
00:01:43.035 gyp info it worked if it ends with ok
00:01:43.035 gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
00:01:43.035 gyp verb cli   'E:\\jenkins\\workspace\\Development\\..\\PrintApplication\\node_modules\\node-sass\\node_modules\\node-gyp\\bin\\node-gyp.js',
00:01:43.035 gyp verb cli   'rebuild',
00:01:43.035 gyp verb cli   '--verbose',
00:01:43.035 gyp verb cli   '--libsass_ext=',
00:01:43.035 gyp verb cli   '--libsass_cflags=',
00:01:43.035 gyp verb cli   '--libsass_ldflags=',
00:01:43.035 gyp verb cli   '--libsass_library=' ]
00:01:43.035 gyp info using node-gyp@3.8.0
00:01:43.035 gyp info using node@11.0.0 | win32 | x64
00:01:43.035 gyp verb command rebuild []
00:01:43.035 gyp verb command clean []
00:01:43.035 gyp verb clean removing "build" directory
00:01:43.035 gyp verb command configure []
00:01:43.035 gyp verb check python checking for Python executable "python2" in the PATH
00:01:43.035 gyp verb `which` failed Error: not found: python2
00:01:43.035 gyp verb `which` failed     at getNotFoundError (E:\jenkins\workspace\Development\..\PrintApplication\node_modules\which\which.js:13:12)
00:01:43.035 gyp verb `which` failed     at F (E:\jenkins\workspace\Development\..\PrintApplication\node_modules\which\which.js:68:19)
00:01:43.035 gyp verb `which` failed     at E (E:\jenkins\workspace\Development\..\PrintApplication\node_modules\which\which.js:80:29)
00:01:43.035 gyp verb `which` failed     at E:\jenkins\workspace\Development\..\PrintApplication\node_modules\which\which.js:89:16
00:01:43.035 gyp verb `which` failed     at E:\jenkins\workspace\Development\..\PrintApplication\node_modules\isexe\index.js:42:5
00:01:43.035 gyp verb `which` failed     at E:\jenkins\workspace\Development\..\PrintApplication\node_modules\isexe\windows.js:36:5
00:01:43.035 gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:161:21)
00:01:43.035 gyp verb `which` failed  python2 { Error: not found: python2
00:01:43.035 gyp verb `which` failed     at getNotFoundError (E:\jenkins\workspace\Development\ ..\PrintApplication\node_modules\which\which.js:13:12)
00:01:43.035 gyp verb `which` failed     at F (E:\jenkins\workspace\Development\ ..\PrintApplication\node_modules\which\which.js:68:19)
00:01:43.035 gyp verb `which` failed     at E (E:\jenkins\workspace\Development\ ..\PrintApplication\node_modules\which\which.js:80:29)
00:01:43.035 gyp verb `which` failed     at E:\jenkins\workspace\Development\ ..\PrintApplication\node_modules\which\which.js:89:16
00:01:43.035 gyp verb `which` failed     at E:\jenkins\workspace\Development\ ..\PrintApplication\node_modules\isexe\index.js:42:5
00:01:43.035 gyp verb `which` failed     at E:\jenkins\workspace\Development\ ..\PrintApplication\node_modules\isexe\windows.js:36:5
00:01:43.035 gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:161:21)
00:01:43.035 gyp verb `which` failed   stack:
00:01:43.035 gyp verb `which` failed    'Error: not found: python2\n    at getNotFoundError (E:\\jenkins\\workspace\\Development\\Dev_3_0\\Products-Development\\ZoomCMS\\ZoomCMS.UI\\App_Client\\ZoomFeatures\\PrintApplication\\node_modules\\which\\which.js:13:12)\n    at F (E:\\jenkins\\workspace\\Development\\Dev_3_0\\Products-Development\\ZoomCMS\\ZoomCMS.UI\\App_Client\\ZoomFeatures\\PrintApplication\\node_modules\\which\\which.js:68:19)\n    at E (E:\\jenkins\\workspace\\Development\\Dev_3_0\\Products-Development\\ZoomCMS\\ZoomCMS.UI\\App_Client\\ZoomFeatures\\PrintApplication\\node_modules\\which\\which.js:80:29)\n    at E:\\jenkins\\workspace\\Development\\Dev_3_0\\Products-Development\\ZoomCMS\\ZoomCMS.UI\\App_Client\\ZoomFeatures\\PrintApplication\\node_modules\\which\\which.js:89:16\n    at E:\\jenkins\\workspace\\Development\\Dev_3_0\\Products-Development\\ZoomCMS\\ZoomCMS.UI\\App_Client\\ZoomFeatures\\PrintApplication\\node_modules\\isexe\\index.js:42:5\n    at E:\\jenkins\\workspace\\Development\\Dev_3_0\\Products-Development\\ZoomCMS\\ZoomCMS.UI\\App_Client\\ZoomFeatures\\PrintApplication\\node_modules\\isexe\\windows.js:36:5\n    at FSReqCallback.oncomplete (fs.js:161:21)',
00:01:43.035 gyp verb `which` failed   code: 'ENOENT' }
00:01:43.035 gyp verb check python checking for Python executable "python" in the PATH
00:01:43.035 gyp verb `which` succeeded python C:\Python27\python.EXE
00:01:43.035 gyp verb check python version `C:\Python27\python.EXE -c "import sys; print "2.7.14
00:01:43.035 gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
00:01:43.035 gyp verb get node dir no --target version specified, falling back to host node version: 11.0.0
00:01:43.035 gyp verb command install [ '11.0.0' ]
00:01:43.035 gyp verb install input version string "11.0.0"
00:01:43.035 gyp verb install installing version: 11.0.0
00:01:43.035 gyp verb install --ensure was passed, so won't reinstall if already installed
00:01:43.035 gyp verb install version is already installed, need to check "installVersion"
00:01:43.035 gyp verb got "installVersion" 9
00:01:43.035 gyp verb needs "installVersion" 9
00:01:43.035 gyp verb install version is good
00:01:43.035 gyp verb get node dir target node version installed: 11.0.0
00:01:43.035 gyp verb build dir attempting to create "build" dir: E:\jenkins\workspace\Development\ ..\PrintApplication\node_modules\node-sass\build
00:01:43.035 gyp verb build dir "build" dir needed to be created? E:\jenkins\workspace\Development\ ..\PrintApplication\node_modules\node-sass\build
00:01:43.035 gyp verb find vs2017 Found installation at: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools
00:01:43.035 gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.Windows10SDK.17763
00:01:43.035 gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.VC.Tools.x86.x64
00:01:43.035 gyp verb find vs2017   - Found Microsoft.VisualStudio.VC.MSBuild.Base
00:01:43.035 gyp verb find vs2017   - Using this installation with Windows 10 SDK
00:01:43.035 gyp verb find vs2017 using installation: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools
00:01:43.035 gyp verb build/config.gypi creating config file
00:01:43.036 gyp verb build/config.gypi writing out config file: E:\jenkins\workspace\Development\ ..\PrintApplication\node_modules\node-sass\build\config.gypi
00:01:43.036 gyp verb config.gypi checking for gypi file: E:\jenkins\workspace\Development\ ..\PrintApplication\node_modules\node-sass\config.gypi
00:01:43.036 gyp verb common.gypi checking for gypi file: E:\jenkins\workspace\Development\ ..\PrintApplication\node_modules\node-sass\common.gypi
00:01:43.036 gyp verb gyp gyp format was not specified; forcing "msvs"
00:01:43.036 gyp info spawn C:\Python27\python.EXE
00:01:43.036 gyp info spawn args [ 'E:\\jenkins\\workspace\\Development\\Dev_3_0\\Products-Development\\ZoomCMS\\ZoomCMS.UI\\App_Client\\ZoomFeatures\\PrintApplication\\node_modules\\node-sass\\node_modules\\node-gyp\\gyp\\gyp_main.py',
00:01:43.036 gyp info spawn args   'binding.gyp',
00:01:43.036 gyp info spawn args   '-f',
00:01:43.036 gyp info spawn args   'msvs',
00:01:43.036 gyp info spawn args   '-G',
00:01:43.036 gyp info spawn args   'msvs_version=2015',
00:01:43.036 gyp info spawn args   '-I',
00:01:43.036 gyp info spawn args   'E:\\jenkins\\workspace\\Development\\Dev_3_0\\Products-Development\\ZoomCMS\\ZoomCMS.UI\\App_Client\\ZoomFeatures\\PrintApplication\\node_modules\\node-sass\\build\\config.gypi',
00:01:43.036 gyp info spawn args   '-I',
00:01:43.036 gyp info spawn args   'E:\\jenkins\\workspace\\Development\\Dev_3_0\\Products-Development\\ZoomCMS\\ZoomCMS.UI\\App_Client\\ZoomFeatures\\PrintApplication\\node_modules\\node-sass\\node_modules\\node-gyp\\addon.gypi',
00:01:43.036 gyp info spawn args   '-I',
00:01:43.036 gyp info spawn args   'C:\\Users\\insindia.ZOOMCOBRA\\.node-gyp\\11.0.0\\include\\node\\common.gypi',
00:01:43.036 gyp info spawn args   '-Dlibrary=shared_library',
00:01:43.036 gyp info spawn args   '-Dvisibility=default',
00:01:43.036 gyp info spawn args   '-Dnode_root_dir=C:\\Users\\insindia.ZOOMCOBRA\\.node-gyp\\11.0.0',
00:01:43.036 gyp info spawn args   '-Dnode_gyp_dir=E:\\jenkins\\workspace\\Development\\Dev_3_0\\Products-Development\\ZoomCMS\\ZoomCMS.UI\\App_Client\\ZoomFeatures\\PrintApplication\\node_modules\\node-sass\\node_modules\\node-gyp',
00:01:43.036 gyp info spawn args   '-Dnode_lib_file=C:\\Users\\insindia.ZOOMCOBRA\\.node-gyp\\11.0.0\\<(target_arch)\\node.lib',
00:01:43.036 gyp info spawn args   '-Dmodule_root_dir=E:\\jenkins\\workspace\\Development\\Dev_3_0\\Products-Development\\ZoomCMS\\ZoomCMS.UI\\App_Client\\ZoomFeatures\\PrintApplication\\node_modules\\node-sass',
00:01:43.036 gyp info spawn args   '-Dnode_engine=v8',
00:01:43.036 gyp info spawn args   '--depth=.',
00:01:43.036 gyp info spawn args   '--no-parallel',
00:01:43.036 gyp info spawn args   '--generator-output',
00:01:43.036 gyp info spawn args   'E:\\jenkins\\workspace\\Development\\Dev_3_0\\Products-Development\\ZoomCMS\\ZoomCMS.UI\\App_Client\\ZoomFeatures\\PrintApplication\\node_modules\\node-sass\\build',
00:01:43.036 gyp info spawn args   '-Goutput_dir=.' ]
00:01:43.036 gyp verb command build []
00:01:43.036 gyp verb build type Release
00:01:43.036 gyp verb architecture x64
00:01:43.036 gyp verb node dev dir C:\Users\insindia.ZOOMCOBRA\.node-gyp\11.0.0
00:01:43.036 gyp verb found first Solution file build/binding.sln
00:01:43.036 gyp verb `which` succeeded for `msbuild` C:\Windows\system32\msbuild.EXE
00:01:43.036 gyp info spawn msbuild
00:01:43.036 gyp info spawn args [ 'build/binding.sln',
00:01:43.036 gyp info spawn args   '/nologo',
00:01:43.036 gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
00:01:43.036 Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
00:01:43.036 Build started 9/10/2019 1:21:00 PM.
00:01:43.036 Project "E:\jenkins\workspace\Development\ ..\PrintApplication\node_modules\node-sass\build\binding.sln" on node 1 (default targets).
00:01:43.036 ValidateSolutionConfiguration:
00:01:43.036   Building solution configuration "Release|x64".
00:01:43.036 The target "BeforeGenerateProjectPriFile" listed in a BeforeTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets (186,61)" does not exist in the project, and will be ignored.
00:01:43.036 Project "E:\jenkins\workspace\Development\ ..\PrintApplication\node_modules\node-sass\build\binding.sln" (1) is building "E:\jenkins\workspace\Development\ ..\PrintApplication\node_modules\node-sass\build\binding.vcxproj.metaproj" (2) on node 1 (default targets).
00:01:43.036 Project "E:\jenkins\workspace\Development\ ..\PrintApplication\node_modules\node-sass\build\binding.vcxproj.metaproj" (2) is building "E:\jenkins\workspace\Development\ ..\PrintApplication\node_modules\node-sass\build\src\libsass.vcxproj" (3) on node 1 (default targets).
00:01:43.036 C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets(57,5): error MSB8020: The build tools for v141 (Platform Toolset = 'v141') cannot be found. To build using the v141 build tools, please install v141 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [E:\jenkins\workspace\Development\ ..\PrintApplication\node_modules\node-sass\build\src\libsass.vcxproj]
00:01:43.036 Done Building Project "E:\jenkins\workspace\Development\ ..\PrintApplication\node_modules\node-sass\build\src\libsass.vcxproj" (default targets) -- FAILED.
00:01:43.036 Done Building Project "E:\jenkins\workspace\Development\ ..\PrintApplication\node_modules\node-sass\build\binding.vcxproj.metaproj" (default targets) -- FAILED.
00:01:43.036 Done Building Project "E:\jenkins\workspace\Development\ ..\PrintApplication\node_modules\node-sass\build\binding.sln" (default targets) -- FAILED.
00:01:43.036 
00:01:43.036 Build FAILED.
00:01:43.036 
00:01:43.036 "E:\jenkins\workspace\Development\ ..\PrintApplication\node_modules\node-sass\build\binding.sln" (default target) (1) ->
00:01:43.036 "E:\jenkins\workspace\Development\ ..\PrintApplication\node_modules\node-sass\build\binding.vcxproj.metaproj" (default target) (2) ->
00:01:43.036 "E:\jenkins\workspace\Development\ ..\PrintApplication\node_modules\node-sass\build\src\libsass.vcxproj" (default target) (3) ->
00:01:43.036 (PlatformPrepareForBuild target) -> 
00:01:43.036   C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets(57,5): error MSB8020: The build tools for v141 (Platform Toolset = 'v141') cannot be found. To build using the v141 build tools, please install v141 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [E:\jenkins\workspace\Development\ ..\PrintApplication\node_modules\node-sass\build\src\libsass.vcxproj]
00:01:43.036 
00:01:43.036     0 Warning(s)
00:01:43.036     1 Error(s)
00:01:43.036 
00:01:43.036 Time Elapsed 00:00:00.47
00:01:43.036 gyp ERR! build error 
00:01:43.036 gyp ERR! stack Error: `msbuild` failed with exit code: 1
00:01:43.036 gyp ERR! stack     at ChildProcess.onExit (E:\jenkins\workspace\Development\ ..\PrintApplication\node_modules\node-sass\node_modules\node-gyp\lib\build.js:262:23)
00:01:43.036 gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
00:01:43.036 gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
00:01:43.036 gyp ERR! System Windows_NT 6.3.9600
00:01:43.036 gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\jenkins\\workspace\\Development\\Dev_3_0\\Products-Development\\ZoomCMS\\ZoomCMS.UI\\App_Client\\ZoomFeatures\\PrintApplication\\node_modules\\node-sass\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
00:01:43.036 gyp ERR! cwd E:\jenkins\workspace\Development\ ..\PrintApplication\node_modules\node-sass
00:01:43.037 gyp ERR! node -v v11.0.0
00:01:43.037 gyp ERR! node-gyp -v v3.8.0
00:01:43.037 gyp ERR! not ok 
00:01:43.037 Build failed with error code: 1
00:01:43.037 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
00:01:43.181 Build step 'Execute Windows batch command' marked build as failure
```

**Comment by saper** [comment]
It seems you have some trouble locating https://www.npmjs.com/package/lodash._baseclone module? I don't think it is related to node-sass.

**Comment by lytrungtin** [comment]
I have got this issue when deploy to Centos 6, fixed by:
Login ssh to server with deploy user and run:
```
yarn cache clean
```
