### ISSUE TITLE
return of Missing binding

### ISSUE THREAD

**Issue by cekvenich** [sass/node-sass#2735]
```
root@intu-1vcpu-2gb-nyc3:/usr/local/bin# mbake-x
/usr/local/share/.config/yarn/global/node_modules/mbake-x/node_modules/node-sass/lib/binding.js:15
      throw new Error(errors.missingBinary());
      ^

Error: Missing binding /usr/local/share/.config/yarn/global/node_modules/mbake-x/node_modules/node-sass/vendor/linux-x64-72/binding.node
Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 12.x

Found bindings for the following environments:
  - OS X 64-bit with Node.js 12.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to download the binding for your current environment.
    at module.exports (/usr/local/share/.config/yarn/global/node_modules/mbake-x/node_modules/node-sass/lib/binding.js:15:13)
    at Object.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/mbake-x/node_modules/node-sass/lib/index.js:14:35)
```
So it is global and yarn.
I tried yarn remove global and back and no joy.

**Comment by nschonni** [comment]
Sorry, you didn't follow the issue template, so we can't help you.
