### ISSUE TITLE
Error Stack Exit Status 1

### ISSUE THREAD

**Issue by petervijeh** [sass/node-sass#2740]
node-sass won't run and throughs an extremely cryptic error:  stack exit status 1.

ive tried various different versions of node / node-sass and also completely removing and re-installing node.  no idea whats broken, but it sounds like this is a common problem. 

below is my log output and relevant versioning info. 

- NPM version (`npm -v`): 6.41
- Node version (`node -v`): 10.13.0
- Node Process (`node -p process.versions`): { http_parser: '2.8.0',
  node: '10.13.0',
  v8: '6.8.275.32-node.36',
  uv: '1.23.2',
  zlib: '1.2.11',
  ares: '1.14.0',
  modules: '64',
  nghttp2: '1.34.0',
  napi: '3',
  openssl: '1.1.0i',
  icu: '62.1',
  unicode: '11.0',
  cldr: '33.1',
  tz: '2018e' }
- Node Platform (`node -p process.platform`): darwin
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`):

node-sass	4.12.0	(Wrapper)	[JavaScript]
libsass  	3.5.4	(Sass Compiler)	[C/C++]

- npm node-sass versions (`npm ls node-sass`):

├── node-sass@4.12.0
└─┬ node-sass-middleware@0.11.0
  └── node-sass@4.12.0  deduped

output of npm logs

````
0 info it worked if it ends with ok
1 verbose cli [ '/Users/petervijeh/.nvm/versions/node/v10.13.0/bin/node',
1 verbose cli   '/Users/petervijeh/.nvm/versions/node/v10.13.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'tttt' ]
2 info using npm@6.4.1
3 info using node@v10.13.0
4 verbose run-script [ 'pretttt', 'tttt', 'posttttt' ]
5 info lifecycle hackathon-starter@4.0.1~pretttt: hackathon-starter@4.0.1
6 info lifecycle hackathon-starter@4.0.1~tttt: hackathon-starter@4.0.1
7 verbose lifecycle hackathon-starter@4.0.1~tttt: unsafe-perm in lifecycle true
8 verbose lifecycle hackathon-starter@4.0.1~tttt: PATH: /Users/petervijeh/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/petervijeh/workspace/scent-find-beta-version/node_modules/.bin:/Users/petervijeh/.nvm/versions/node/v10.13.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle hackathon-starter@4.0.1~tttt: CWD: /Users/petervijeh/workspace/scent-find-beta-version
10 silly lifecycle hackathon-starter@4.0.1~tttt: Args: [ '-c', 'node-sass css -o output' ]
11 silly lifecycle hackathon-starter@4.0.1~tttt: Returned: code: 1  signal: null
12 info lifecycle hackathon-starter@4.0.1~tttt: Failed to exec tttt script
13 verbose stack Error: hackathon-starter@4.0.1 tttt: `node-sass css -o output`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/petervijeh/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/Users/petervijeh/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid hackathon-starter@4.0.1
15 verbose cwd /Users/petervijeh/workspace/scent-find-beta-version
16 verbose Darwin 16.7.0
17 verbose argv "/Users/petervijeh/.nvm/versions/node/v10.13.0/bin/node" "/Users/petervijeh/.nvm/versions/node/v10.13.0/bin/npm" "run" "tttt"
18 verbose node v10.13.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error hackathon-starter@4.0.1 tttt: `node-sass css -o output`
22 error Exit status 1
23 error Failed at the hackathon-starter@4.0.1 tttt script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by saper** [comment]
What command are you running that is going to get `['-c', 'node-sass css -o output']` parameters?
Can you prepare a small repository or a script to reproduce the problem?
