### ISSUE TITLE
[CentOS5] node v6.17.1: Binary has a problem: Error: /home/nodetest/node_modules/node-sass/vendor/linux-ia32-48/binding.node: cannot restore segment prot after reloc: Permission denied

### ISSUE THREAD

**Issue by saper** [sass/node-sass#2760]
- NPM version (`3.10.10`):
- Node version (`v6.17.1`):
- Node Process (```javascript
{ http_parser: '2.8.0',
  node: '6.17.1',
  v8: '5.1.281.111',
  uv: '1.16.1',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  icu: '58.2',
  modules: '48',
  napi: '3',
  openssl: '1.0.2r' }
```):
- Node Platform (`linux`):
- Node architecture (`ia32`):
- node-sass version (```
module.js:478
    throw err;
    ^

Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (module.js:476:15)
    at Function.Module._load (module.js:424:25)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at [eval]:1:1
    at ContextifyScript.Script.runInThisContext (vm.js:25:33)
    at Object.runInThisContext (vm.js:97:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:577:32)
    at evalScript (bootstrap_node.js:358:27)
```):
- npm node-sass versions (```
/home/nodetest
└── (empty)

npm ERR! code 1
```):

**Comment by saper** [comment]
Ooops, wrong node has been used (32-bit instead of 64-bit), sorry
