### ISSUE TITLE
NPM install fails; gyp is trying to run python 2

### ISSUE THREAD

**Issue by mccalluc** [sass/node-sass#2792]
- NPM version (`npm -v`): 6.12.1
- Node version (`node -v`): v12.13.1
- Node Process (`node -p process.versions`):
```
{
  node: '12.13.1',
  v8: '7.7.299.13-node.16',
  uv: '1.33.1',
  zlib: '1.2.11',
  brotli: '1.0.7',
  ares: '1.15.0',
  modules: '72',
  nghttp2: '1.39.2',
  napi: '5',
  llhttp: '1.1.4',
  http_parser: '2.8.0',
  openssl: '1.1.1d',
  cldr: '35.1',
  icu: '64.2',
  tz: '2019a',
  unicode: '12.1'
}
```
- Node Platform (`node -p process.platform`): darwin
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`):
```
node-sass	4.13.0	(Wrapper)	[JavaScript]
libsass  	3.5.4	(Sass Compiler)	[C/C++]
```
- npm node-sass versions (`npm ls node-sass`):
```
node-sass-bug-reproducer@0.0.1 /Users/chuck/github/mccalluc/reproducer
└── node-sass@4.13.0
```

With a package.json like this:
```json
{
  "name": "node-sass-bug-reproducer",
  "version": "0.0.1",
  "description": "Try to reproduce a problem with node-sass",
  "license": "MIT",
  "dependencies": {
    "node-sass": "^4.13.0"
  },
  "devDependencies": {
    "nwb": "^0.23.0"
  }
}
```
`npm install nwb-sass --save-dev` fails like this:

<details>

```
$ npm install nwb-sass --save-dev

> node-sass@4.9.2 install /Users/chuck/github/mccalluc/reproducer/node_modules/nwb-sass/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.9.2/darwin-x64-72_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.9.2/darwin-x64-72_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.9.2 postinstall /Users/chuck/github/mccalluc/reproducer/node_modules/nwb-sass/node_modules/node-sass
> node scripts/build.js

Building: /usr/local/Cellar/node@12/12.13.1/bin/node /Users/chuck/github/mccalluc/reproducer/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/usr/local/Cellar/node@12/12.13.1/bin/node',
gyp verb cli   '/Users/chuck/github/mccalluc/reproducer/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@12.13.1 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "/opt/anaconda3/bin/python" in the PATH
gyp verb `which` succeeded /opt/anaconda3/bin/python /opt/anaconda3/bin/python
gyp ERR! configure error
gyp ERR! stack Error: Command failed: /opt/anaconda3/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:295:12)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:430:11)
gyp ERR! stack     at Socket.emit (events.js:210:5)
gyp ERR! stack     at Pipe.<anonymous> (net.js:659:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/Cellar/node@12/12.13.1/bin/node" "/Users/chuck/github/mccalluc/reproducer/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/chuck/github/mccalluc/reproducer/node_modules/nwb-sass/node_modules/node-sass
gyp ERR! node -v v12.13.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN babel-plugin-inferno@5.0.1 requires a peer of inferno@^5 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.9.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.9.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/chuck/.npm/_logs/2019-11-25T22_27_28_898Z-debug.log
```

</details>

It seems to be trying to run Python2 code: Is Python2 an expected dependency? Or the root cause may be the HTTP 404 earlier in the log?

Repo including package.lock is [here](https://github.com/mccalluc/node-sass-bug-reproducer).

I came across this problem when trying to upgrade NodeJS: With earlier node versions, it doesn't seem to happen.

**Comment by xzyfer** [comment]
This is not a bug.

nwb-sass is using a very old version of node-sass that doesn't support Node 12. Node version support is documented **in bold text as the very first line of the README**.

**Comment by mccalluc** [comment]
I apologize: I had meant to file this on `nwb-sass`, not `node-sass`. Thank you / sorry for the bother.
