### ISSUE TITLE
Issue when using the cluster mode of PM2 and node-sass

### ISSUE THREAD

**Issue by anthonycluse** [sass/node-sass#2797]
Hello,

I get an issue using "node-sass" and PM2. When running my app with the cluster mode of PM2 I get an error :

```
Error: Missing binding /var/www/*****/cms/node_modules/node-sass/vendor/linux-x64-57/binding.node
Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 8.x
Found bindings for the following environments:
  - Linux 64-bit with Node.js 6.x
This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to download the binding for your current environment.
    at module.exports (/var/www/*****/cms/node_modules/node-sass/lib/binding.js:15:13)
    at Object.<anonymous> (/var/www/*****/cms/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function._load (/usr/local/lib/node_modules/pm2/node_modules/@pm2/io/build/main/src/metrics/transaction.js:109:33)
    at Module.require (module.js:596:17)
    at Module.newFunc [as require] (/usr/local/lib/node_modules/pm2/node_modules/deep-metrics/lib/aspect.js:101:26)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/www/*****/cms/app/controllers/OptionController.js:4:25)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function._load (/usr/local/lib/node_modules/pm2/node_modules/@pm2/io/build/main/src/metrics/transaction.js:109:33)
    at Module.require (module.js:596:17)
    at Module.newFunc [as require] (/usr/local/lib/node_modules/pm2/node_modules/deep-metrics/lib/aspect.js:101:26)
    at require (internal/module.js:11:18)
    at /var/www/*****/cms/server.js:64:18
```

It works on my local server, and on my remote server without the cluster mode.

**Versions and architecture :**

- NPM version : 3.10.10
- Node version : v6.9.4
- Node Process :
```
{ http_parser: '2.7.0',
  node: '6.9.4',
  v8: '5.1.281.89',
  uv: '1.9.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '57.1',
  modules: '48',
  openssl: '1.0.2j' }
```
- Node Platform : linux
- Node architecture : x64
- node-sass version :
```
node-sass       4.13.0  (Wrapper)       [JavaScript]
libsass         3.5.4   (Sass Compiler) [C/C++]
```
- npm node-sass versions : node-sass@4.13.0

**Comment by nschonni** [comment]
Sorry, I'm not sure what "PM2" is, but we do test the Linux & Node 13 combo in our CI
