### ISSUE TITLE
Suddenly cannot npm install using node-sass 4.7.2 / node 6.9.2

### ISSUE THREAD

**Issue by Awbelton** [sass/node-sass#2814]
Using node 6.9.2, npm 6.13.4 and node-sass 4.7.2. Everything worked fine a few days ago, now I hit this snag:

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for semver@~5.3.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'node-gyp'
```

I've tried everything at this point, but to no avail.

**Comment by Rc85** [comment]
I also cannot install anymore but I'm getting a different error message.

Node 10.18.0, node-sass 4.13.0.

```
> node-sass@4.13.0 install /opt/portfolio/node_modules/node-sass
> node scripts/install.js

Unable to save binary /opt/portfolio/node_modules/node-sass/vendor/linux-x64-64 : { Error: EACCES: permission denied, mkdir '/opt/portfolio/node_modules/node-sass/vendor'
    at Object.mkdirSync (fs.js:757:3)
    at sync (/opt/portfolio/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/opt/portfolio/node_modules/mkdirp/index.js:77:24)
    at checkAndDownloadBinary (/opt/portfolio/node_modules/node-sass/scripts/install.js:114:11)
    at Object.<anonymous> (/opt/portfolio/node_modules/node-sass/scripts/install.js:157:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path: '/opt/portfolio/node_modules/node-sass/vendor' }

> node-sass@4.13.0 postinstall /opt/portfolio/node_modules/node-sass
> node scripts/build.js

Building: /usr/bin/node /opt/portfolio/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/bin/node',
gyp verb cli   '/opt/portfolio/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@10.18.0 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /bin/python2
gyp verb check python version `/bin/python2 -c "import sys; print "2.7.5
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 10.18.0
gyp verb command install [ '10.18.0' ]
gyp verb install input version string "10.18.0"
gyp verb install installing version: 10.18.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/10.18.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/opt/portfolio/node_modules/node-sass/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '--node_gyp_internal_noretry', '10.18.0' ]
gyp verb install input version string "10.18.0"
gyp verb install installing version: 10.18.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 10.18.0
gyp verb ensuring nodedir is created /opt/portfolio/node_modules/node-sass/.node-gyp/10.18.0
gyp WARN install got an error, rolling back install
gyp verb command remove [ '10.18.0' ]
gyp verb remove using node-gyp dir: /opt/portfolio/node_modules/node-sass/.node-gyp
gyp verb remove removing target version: 10.18.0
gyp verb remove removing development files for version: 10.18.0
gyp WARN install got an error, rolling back install
gyp verb command remove [ '10.18.0' ]
gyp verb remove using node-gyp dir: /opt/portfolio/node_modules/node-sass/.node-gyp
gyp verb remove removing target version: 10.18.0
gyp verb remove removing development files for version: 10.18.0
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/opt/portfolio/node_modules/node-sass/.node-gyp'
gyp ERR! System Linux 3.10.0-1062.9.1.el7.x86_64
gyp ERR! command "/usr/bin/node" "/opt/portfolio/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /opt/portfolio/node_modules/node-sass
gyp ERR! node -v v10.18.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/jest-haste-map/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.13.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.13.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-01-16T04_52_04_783Z-debug.log
```
Looks like a node-gyp problem but at the very beginning, it cannot save binary. I don't know what that is about.

**Comment by xzyfer** [comment]
@Rc85 you have a permission issue writing to `/opt/portfolio/node_modules/node-sass/vendor`. Check your permissions or try running `npm install --unsafe-perms`.

**Comment by xzyfer** [comment]
@Awbelton this is not a node-sass issue. Might be an node-gyp issue.

```
No matching version found for semver@~5.3.0.
...
It was specified as a dependency of 'node-gyp'
```
