### ISSUE TITLE
"Binary has a problem" with 4.13.1

### ISSUE THREAD

**Issue by ckaczor** [sass/node-sass#2822]
We're getting the following during builds with 4.13.1 - if we go back to 4.13.0 everything is fine.

2020-01-16T17:04:44.3993932Z > node-sass@4.13.1 postinstall /node_modules/node-sass
2020-01-16T17:04:44.4010867Z > node scripts/build.js
2020-01-16T17:04:44.4016913Z 
2020-01-16T17:04:44.5530663Z Binary found at /node_modules/node-sass/vendor/linux_musl-x64-64/binding.node
2020-01-16T17:04:44.5548706Z Testing binary
2020-01-16T17:04:44.6559773Z Binary has a problem: Error: Error relocating /node_modules/node-sass/vendor/linux_musl-x64-64/binding.node: _ZNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEC1Ev: symbol not found
2020-01-16T17:04:44.6609834Z     at Object.Module._extensions..node (internal/modules/cjs/loader.js:718:18)
2020-01-16T17:04:44.6623255Z     at Module.load (internal/modules/cjs/loader.js:599:32)
2020-01-16T17:04:44.6640744Z     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
2020-01-16T17:04:44.6653951Z     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
2020-01-16T17:04:44.6667669Z     at Module.require (internal/modules/cjs/loader.js:637:17)
2020-01-16T17:04:44.6681340Z     at require (internal/modules/cjs/helpers.js:22:18)
2020-01-16T17:04:44.6696639Z     at module.exports (/node_modules/node-sass/lib/binding.js:19:10)
2020-01-16T17:04:44.6713582Z     at Object.<anonymous> (/node_modules/node-sass/lib/index.js:14:35)
2020-01-16T17:04:44.6730091Z     at Module._compile (internal/modules/cjs/loader.js:689:30)
2020-01-16T17:04:44.6743279Z     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)

**Comment by nschonni** [comment]
Did you clear your node_modules or vendor folder? The binding code was changed so it won't be able to reusing the binding.node from 4.13.0

**Comment by rwoody** [comment]
We got this in a docker build as well. We aren't using any lock files. Changed the package.json from `^4.9.3` to `4.13.0` and everything works again.

Our npm installs were complaining about python 2 not being found...

**Comment by b3n01t** [comment]
@xzyfer Are you guys fixing this? 
We have dependencies using node-sass and we cannot have them pin their dependencies to what we need.

**Comment by b3n01t** [comment]
Logs from npm install in a Docker image from `node:10.14-alpine`

```
> node-sass@4.13.1 postinstall /usr/src/node_modules/xxx/node_modules/node-sass
> node scripts/build.js

Binary found at /usr/src/node_modules/xxx/node_modules/node-sass/vendor/linux_musl-x64-64/binding.node
Testing binary
Binary has a problem: Error: Error relocating /usr/src/node_modules/xxx/node_modules/node-sass/vendor/linux_musl-x64-64/binding.node: _ZNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEC1Ev: symbol not found
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:718:18)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at module.exports (/usr/src/node_modules/xxx/node_modules/node-sass/lib/binding.js:19:10)
    at Object.<anonymous> (/usr/src/node_modules/xxx/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
Building the binary locally
Building: /usr/local/bin/node /usr/src/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/bin/node',
gyp verb cli   '/usr/src/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@10.14.2 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/usr/src/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/usr/src/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/usr/src/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /usr/src/node_modules/which/which.js:89:16
gyp verb `which` failed     at /usr/src/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /usr/src/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:154:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/usr/src/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/usr/src/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/usr/src/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /usr/src/node_modules/which/which.js:89:16
gyp verb `which` failed     at /usr/src/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /usr/src/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:154:21)
gyp verb `which` failed   stack:
gyp verb `which` failed    'Error: not found: python2\n    at getNotFoundError (/usr/src/node_modules/which/which.js:13:12)\n    at F (/usr/src/node_modules/which/which.js:68:19)\n    at E (/usr/src/node_modules/which/which.js:80:29)\n    at /usr/src/node_modules/which/which.js:89:16\n    at /usr/src/node_modules/isexe/index.js:42:5\n    at /usr/src/node_modules/isexe/mode.js:8:5\n    at FSReqWrap.oncomplete (fs.js:154:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (/usr/src/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/usr/src/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/usr/src/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /usr/src/node_modules/which/which.js:89:16
gyp verb `which` failed     at /usr/src/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /usr/src/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:154:21)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (/usr/src/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/usr/src/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/usr/src/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /usr/src/node_modules/which/which.js:89:16
gyp verb `which` failed     at /usr/src/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /usr/src/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:154:21)
gyp verb `which` failed   stack:
gyp verb `which` failed    'Error: not found: python\n    at getNotFoundError (/usr/src/node_modules/which/which.js:13:12)\n    at F (/usr/src/node_modules/which/which.js:68:19)\n    at E (/usr/src/node_modules/which/which.js:80:29)\n    at /usr/src/node_modules/which/which.js:89:16\n    at /usr/src/node_modules/isexe/index.js:42:5\n    at /usr/src/node_modules/isexe/mode.js:8:5\n    at FSReqWrap.oncomplete (fs.js:154:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/usr/src/node_modules/node-gyp/lib/configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/src/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! stack     at F (/usr/src/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/usr/src/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/src/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/src/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/src/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:154:21)
gyp ERR! System Linux 4.9.184-linuxkit
gyp ERR! command "/usr/local/bin/node" "/usr/src/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /usr/src/node_modules/xxx/node_modules/node-sass
gyp ERR! node -v v10.14.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/jest-haste-map/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN connected-react-router@4.5.0 requires a peer of react-router@^4.3.1 but none is installed. You must install peer dependencies yourself.
npm WARN react-codemirror@1.0.0 requires a peer of react@>=15.5 <16 but none is installed. You must install peer dependencies yourself.
npm WARN react-codemirror@1.0.0 requires a peer of react-dom@>=15.5 <16 but none is installed. You must install peer dependencies yourself.
npm WARN extract-text-webpack-plugin@3.0.2 requires a peer of webpack@^3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ansi-regex@2.1.1 (node_modules/fsevents/node_modules/ansi-regex):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/usr/src/node_modules/fsevents/node_modules/ansi-regex' -> '/usr/src/node_modules/fsevents/node_modules/.ansi-regex.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: balanced-match@1.0.0 (node_modules/fsevents/node_modules/balanced-match):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/usr/src/node_modules/fsevents/node_modules/balanced-match' -> '/usr/src/node_modules/fsevents/node_modules/.balanced-match.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: code-point-at@1.1.0 (node_modules/fsevents/node_modules/code-point-at):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/usr/src/node_modules/fsevents/node_modules/code-point-at' -> '/usr/src/node_modules/fsevents/node_modules/.code-point-at.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: concat-map@0.0.1 (node_modules/fsevents/node_modules/concat-map):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/usr/src/node_modules/fsevents/node_modules/concat-map' -> '/usr/src/node_modules/fsevents/node_modules/.concat-map.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: console-control-strings@1.1.0 (node_modules/fsevents/node_modules/console-control-strings):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/usr/src/node_modules/fsevents/node_modules/console-control-strings' -> '/usr/src/node_modules/fsevents/node_modules/.console-control-strings.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: inherits@2.0.4 (node_modules/fsevents/node_modules/inherits):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/usr/src/node_modules/fsevents/node_modules/inherits' -> '/usr/src/node_modules/fsevents/node_modules/.inherits.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: minimist@0.0.8 (node_modules/fsevents/node_modules/minimist):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/usr/src/node_modules/fsevents/node_modules/minimist' -> '/usr/src/node_modules/fsevents/node_modules/.minimist.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: number-is-nan@1.0.1 (node_modules/fsevents/node_modules/number-is-nan):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/usr/src/node_modules/fsevents/node_modules/number-is-nan' -> '/usr/src/node_modules/fsevents/node_modules/.number-is-nan.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: safe-buffer@5.1.2 (node_modules/fsevents/node_modules/safe-buffer):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/usr/src/node_modules/fsevents/node_modules/safe-buffer' -> '/usr/src/node_modules/fsevents/node_modules/.safe-buffer.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: wrappy@1.0.2 (node_modules/fsevents/node_modules/wrappy):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/usr/src/node_modules/fsevents/node_modules/wrappy' -> '/usr/src/node_modules/fsevents/node_modules/.wrappy.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: yallist@3.1.1 (node_modules/fsevents/node_modules/yallist):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/usr/src/node_modules/fsevents/node_modules/yallist' -> '/usr/src/node_modules/fsevents/node_modules/.yallist.DELETE'

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-01-16T17_50_28_963Z-debug.log
```

**Comment by yury-sannikov** [comment]
Seeing the same

**Comment by amaschas** [comment]
Seeing in the same problem in our docker build using `3.7.2-alpine3.8`. The check on the binary fails with a `symbol not found` and tried to build `node-sass` from source, which also fails because the relevant dependencies are not available in alpine.

```
#28 121.2 Binary found at /app/node_modules/node-sass/vendor/linux_musl-x64-57/binding.node
#28 121.2 Testing binary
#28 121.3 Binary has a problem: Error: Error relocating /app/node_modules/node-sass/vendor/linux_musl-x64-57/binding.node: _ZNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEC1Ev: symbol not found
#28 121.3     at Object.Module._extensions..node (module.js:682:18)
#28 121.3     at Module.load (module.js:566:32)
#28 121.3     at tryModuleLoad (module.js:506:12)
#28 121.3     at Function.Module._load (module.js:498:3)
#28 121.3     at Module.require (module.js:597:17)
#28 121.3     at require (internal/module.js:11:18)
#28 121.3     at module.exports (/app/node_modules/node-sass/lib/binding.js:19:10)
#28 121.3     at Object.<anonymous> (/app/node_modules/node-sass/lib/index.js:14:35)
#28 121.3     at Module._compile (module.js:653:30)
#28 121.3     at Object.Module._extensions..js (module.js:664:10)
#28 121.3 Building the binary locally
```

**Comment by xzyfer** [comment]
@ckaczor @b3n01t I've rebuilt the `linux_musl-x64-64` binary. Can you try again?

**Comment by b3n01t** [comment]
Thanks for looking at this.
Here is how I tested:

`docker container run --name test --rm -i -t node:10.14-alpine npm i node-sass@4.13.1`

This is still failing:
```
#docker container run --name test2 --rm -i -t node:10.14-alpine npm i node-sass@4.13.1

> node-sass@4.13.1 install /node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.13.1/linux_musl-x64-64_binding.node
Download complete  ] - :
Binary saved to /node_modules/node-sass/vendor/linux_musl-x64-64/binding.node
Caching binary to /root/.npm/node-sass/4.13.1/linux_musl-x64-64_binding.node

> node-sass@4.13.1 postinstall /node_modules/node-sass
> node scripts/build.js

Binary found at /node_modules/node-sass/vendor/linux_musl-x64-64/binding.node
Testing binary
Binary has a problem: Error: Error relocating /node_modules/node-sass/vendor/linux_musl-x64-64/binding.node: _ZNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEC1Ev: symbol not found
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:718:18)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at module.exports (/node_modules/node-sass/lib/binding.js:19:10)
    at Object.<anonymous> (/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
Building the binary locally
Building: /usr/local/bin/node /node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/bin/node',
gyp verb cli   '/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@10.14.2 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /node_modules/which/which.js:89:16
gyp verb `which` failed     at /node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:154:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /node_modules/which/which.js:89:16
gyp verb `which` failed     at /node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:154:21)
gyp verb `which` failed   stack:
gyp verb `which` failed    'Error: not found: python2\n    at getNotFoundError (/node_modules/which/which.js:13:12)\n    at F (/node_modules/which/which.js:68:19)\n    at E (/node_modules/which/which.js:80:29)\n    at /node_modules/which/which.js:89:16\n    at /node_modules/isexe/index.js:42:5\n    at /node_modules/isexe/mode.js:8:5\n    at FSReqWrap.oncomplete (fs.js:154:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /node_modules/which/which.js:89:16
gyp verb `which` failed     at /node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:154:21)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /node_modules/which/which.js:89:16
gyp verb `which` failed     at /node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:154:21)
gyp verb `which` failed   stack:
gyp verb `which` failed    'Error: not found: python\n    at getNotFoundError (/node_modules/which/which.js:13:12)\n    at F (/node_modules/which/which.js:68:19)\n    at E (/node_modules/which/which.js:80:29)\n    at /node_modules/which/which.js:89:16\n    at /node_modules/isexe/index.js:42:5\n    at /node_modules/isexe/mode.js:8:5\n    at FSReqWrap.oncomplete (fs.js:154:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/node_modules/node-gyp/lib/configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! stack     at F (/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/node_modules/which/which.js:80:29)
gyp ERR! stack     at /node_modules/which/which.js:89:16
gyp ERR! stack     at /node_modules/isexe/index.js:42:5
gyp ERR! stack     at /node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:154:21)
gyp ERR! System Linux 4.9.184-linuxkit
gyp ERR! command "/usr/local/bin/node" "/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /node_modules/node-sass
gyp ERR! node -v v10.14.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN enoent ENOENT: no such file or directory, open '/package.json'
npm WARN !invalid#1 No description
npm WARN !invalid#1 No repository field.
npm WARN !invalid#1 No README data
npm WARN !invalid#1 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-01-16T21_35_47_726Z-debug.log
b3n01t:~❱ docker container run --name test2 --rm -i -t node:10.14-alpine npm i node-sass@4.13.2
npm ERR! code ETARGET
npm ERR! notarget No matching version found for node-sass@4.13.2
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-01-16T21_37_01_037Z-debug.log
```

**Comment by chrflo** [comment]
still occurring for me as well 
`Binary has a problem: Error: Error relocating /node_modules/node-sass/vendor/linux_musl-x64-64/binding.node: _ZNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEC1Ev: symbol not found
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:718:18)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at module.exports (/node_modules/node-sass/lib/binding.js:19:10)
    at Object.<anonymous> (/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)`

**Comment by chrflo** [comment]
This is still occurring for us as well.

Binary has a problem: Error: Error relocating /node_modules/node-sass/vendor/linux_musl-x64-64/binding.node: _ZNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEC1Ev: symbol not found

**Comment by xzyfer** [comment]
Ok thanks. Nothing has changed in how we build binaries for a couple
releases now so this could take a while. I don't have time to look into for
a day or two.

**Comment by simoncoulton** [comment]
Seeing the same issue here in our CI/CD. Alpine Linux, was ^4.11.0 in the package.json file, will pin as per some other suggestions and report back.

**Comment by yuchunyu97** [comment]
I had the same problem on Alpine.
But I upgraded Alpine from 3.10 to 3.11 to solve the problem.

I guess it may be caused by different versions of Alpine.

**Comment by xzyfer** [comment]
I've digging into this. It looks an issue with node:-alpine containers < 10.18. Something may have changed in with the newer containers which is causing incompatibilities with older node:-alpine containers.

This works fine
```
docker container run --name test --rm -i -t node:10.18-alpine npm i node-sass@4.13.1
```
Where this fails with the errors reported here
```
docker container run --name test --rm -i -t node:10.17-alpine npm i node-sass@4.13.1
```

Judging by the reports in this issue this isn't isolated to Node 10 builds since we have reports from Node 8 also.

**Comment by xzyfer** [comment]
I've rebuilt the Node 10 alpine binary with node 10.16. This appears to address this issue.

**Comment by amaschas** [comment]
Are you sure that the problem is related to Node 10 Alpine? I encountered it running a Python Alpine (3.7.2-alpine3.8) onto which we installed Node.

**Comment by rysinal** [comment]
> Seeing the same. Putting "node-sass": "4.13.0" into the package.json allowed me to build the project.

This works fine

**Comment by turbidwater** [comment]
@xzyfer Retried a build with 4.13.1 today, and still getting the bad binary issue:
`> node-sass@4.13.1 postinstall /opt/atlassian/pipelines/agent/build/node_modules/node-sass
> node scripts/build.js
Binary found at /opt/atlassian/pipelines/agent/build/node_modules/node-sass/vendor/linux_musl-x64-57/binding.node
Testing binary
Binary has a problem: Error: Error relocating /opt/atlassian/pipelines/agent/build/node_modules/node-sass/vendor/linux_musl-x64-57/binding.node: _ZNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEC1Ev: symbol not found
    at Object.Module._extensions..node (module.js:682:18)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at module.exports (/opt/atlassian/pipelines/agent/build/node_modules/node-sass/lib/binding.js:19:10)
    at Object.<anonymous> (/opt/atlassian/pipelines/agent/build/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)`

**Comment by Darep** [comment]
Also having this problem with node:8.12-alpine image:

```
docker run --rm -it node:8.12-alpine npm install node-sass@4.13.1
```

node-sass@4.13.0 works fine

**Comment by anthonycarella** [comment]
Initially, I was able to resolve by also explicitly using `node-sass 4.13.0`.

However, one of the architects on my team ran `docker system prune` to clear out old containers and cache, and that allowed our container to use `node-sass 4.13.1`; seems to have also resolved the issue as well.

**Comment by turbidwater** [comment]
@anthonycarella Ah, excellent point. We have a private registry that serves as a proxy, and I bet it has the old 4.13.1 cached. I'll see if we can get that cleared.

**Comment by xzyfer** [comment]
I've updated the Node 8 binary. It should work now.

**Comment by enricodvn** [comment]
I had this problem with linux kernel 5.0.0-38-generic. My coleagues, while building the same Dockerfile, did not encounter this error (with the version 4.13.1). They were running kernels version 5.3+. I had to downgrade to 4.13.0.

**Comment by artemtam** [comment]
Updating `node:13.8-alpine3.10` to `node:13.8-alpine3.11` solved the problem for me.

**Comment by EvaMalinina** [comment]
I used npm and had the same issue after I run "yarn add node-sass" and it's worked.

**Comment by Freddvch** [comment]
> Updating `node:13.8-alpin`

same for me

**Comment by KingOfCramers** [comment]
I'm using some other libraries that require a newer version of node.js (not 10.14-alpine). Has there been any progress in fixing this bug?

**Comment by saper** [comment]
@KingOfCramers We don't know what the bug really is, sorry. Most certainly not in the node-sass JavaScript or even C++ code.
