### ISSUE TITLE
node-sass/vendor/linux-x64-64 : { Error: EACCES: permission denied

### ISSUE THREAD

**Issue by bi-kai** [sass/node-sass#2824]
```
> node-sass@4.13.1 install /starlab/www/cloudtest/node_modules/node-sass
> node scripts/install.js

Unable to save binary /starlab/www/cloudtest/node_modules/node-sass/vendor/linux-x64-64 : { Error: EACCES: permission denied, mkdir '/starlab/www/cloudtest/node_modules/node-sass/vendor'
    at Object.mkdirSync (fs.js:757:3)
    at sync (/starlab/www/cloudtest/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/starlab/www/cloudtest/node_modules/mkdirp/index.js:77:24)
    at checkAndDownloadBinary (/starlab/www/cloudtest/node_modules/node-sass/scripts/install.js:114:11)
    at Object.<anonymous> (/starlab/www/cloudtest/node_modules/node-sass/scripts/install.js:157:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path: '/starlab/www/cloudtest/node_modules/node-sass/vendor' }

> node-sass@4.13.1 postinstall /starlab/www/cloudtest/node_modules/node-sass
> node scripts/build.js

Building: /starlab/server/node-v10.16.3-linux-x64/bin/node /starlab/www/cloudtest/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/starlab/server/node-v10.16.3-linux-x64/bin/node',
gyp verb cli   '/starlab/www/cloudtest/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@10.16.3 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import sys; print "2.7.15
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 10.16.3
gyp verb command install [ '10.16.3' ]
gyp verb install input version string "10.16.3"
gyp verb install installing version: 10.16.3
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/10.16.3"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/starlab/www/cloudtest/node_modules/node-sass/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '--node_gyp_internal_noretry', '10.16.3' ]
gyp verb install input version string "10.16.3"
gyp verb install installing version: 10.16.3
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 10.16.3
gyp verb ensuring nodedir is created /starlab/www/cloudtest/node_modules/node-sass/.node-gyp/10.16.3
gyp WARN install got an error, rolling back install
gyp verb command remove [ '10.16.3' ]
gyp verb remove using node-gyp dir: /starlab/www/cloudtest/node_modules/node-sass/.node-gyp
gyp verb remove removing target version: 10.16.3
gyp verb remove removing development files for version: 10.16.3
gyp WARN install got an error, rolling back install
gyp verb command remove [ '10.16.3' ]
gyp verb remove using node-gyp dir: /starlab/www/cloudtest/node_modules/node-sass/.node-gyp
gyp verb remove removing target version: 10.16.3
gyp verb remove removing development files for version: 10.16.3
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/starlab/www/cloudtest/node_modules/node-sass/.node-gyp'
gyp ERR! System Linux 4.15.0-45-generic
gyp ERR! command "/starlab/server/node-v10.16.3-linux-x64/bin/node" "/starlab/www/cloudtest/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /starlab/www/cloudtest/node_modules/node-sass
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN vue-admin-template@4.2.1 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

![image](https://user-images.githubusercontent.com/15070379/72666215-0ccde600-3a4b-11ea-8f22-60b7b50a1287.png)

**Comment by nschonni** [comment]
EACCES indicates you have permission issues installing (in general). Delete your node_modules and try again

**Comment by bi-kai** [comment]
@nschonni I have tried many times, and I'm using root user.

**Comment by xzyfer** [comment]
docker container run --name test --rm -i -t node:10.14-alpine npm i node-sass@4.13.1

**Comment by xzyfer** [comment]
https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md#running-with-sudo-or-as-root

**Comment by bi-kai** [comment]
`npm i --unsafe-perm node-sass`, bingo.
