### ISSUE TITLE
gyp verb `which` failed Error: not found: python2

### ISSUE THREAD

**Issue by ylokesh** [sass/node-sass#2825]
We are using "gulp-sass" package where "node-sass" is one of the sub-dependency. Since last day, while doing the build we are getting following error which breaks the build.

gyp verb `which` failed Error: not found: python2

Looks like this issue came to surface with latest upgrade i.e. 4.13.1.

Can you please help us resolving this issue? or suggest an interim resolution.

Package.json
"gulp-sass": "^4.0.1"

Thanks in advance.

**Comment by AaronLayton** [comment]
Note this is causing issues in other packages as well that don't have set in stone version numbers
https://github.com/mcnamee/react-native-starter-kit/issues/236

**Comment by binayatdelhi** [comment]
Hi,
The exact issue is happening with me while running bitbucket pipeline on docker image with OS version "Ansi 6 Alpine Java 3.8"

It is downloading a binary from below url  

`Downloading binary from https://github.com/sass/node-sass/releases/download/v4.13.1/linux_musl-x64-57_binding.node`

and during testing binary, it is failing

```
Binary has a problem: Error: Error relocating /opt/atlassian/pipelines/agent/build/../node_modules/node-sass/vendor/linux_musl-x64-57/binding.node: _ZNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEC1Ev: symbol not found
    at Object.Module._extensions..node (module.js:682:18)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at module.exports (/opt/atlassian/pipelines/agent/build/../node_modules/node-sass/lib/binding.js:19:10)
    at Object.<anonymous> (/opt/atlassian/pipelines/agent/build/../node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
```
Please help in resolving this issue.

**Comment by xzyfer** [comment]
There was an issue with some binaries not working on older node versions. This should be resolved now.
