### ISSUE TITLE
Error: Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (76)

### ISSUE THREAD

**Issue by J0XX0** [sass/node-sass#2846]
I'm trying to use node-sass with Electron (``8.0.0``), but I keep encountering a runtime exception; _Error: Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (76)._ 

I've tried several Node & NPM versions, I've tried rebuilding with electron-rebuild, but I can't get the NODE_MODULE_VERSION to change. It keeps telling me I'm running runtime 76. What's wrong?

P.S.: It's Ubuntu Linux. 

Thanks

- NPM version (`npm -v`):
``6.13.4``
- Node version (`node -v`):
``v12.15.0``
- Node Process (`node -p process.versions`):
```{
  node: '12.15.0',
  v8: '7.7.299.13-node.16',
  uv: '1.33.1',
  zlib: '1.2.11',
  brotli: '1.0.7',
  ares: '1.15.0',
  modules: '72',
  nghttp2: '1.40.0',
  napi: '5',
  llhttp: '2.0.4',
  http_parser: '2.9.3',
  openssl: '1.1.1d',
  cldr: '35.1',
  icu: '64.2',
  tz: '2019c',
  unicode: '12.1'
```
- Node Platform (`node -p process.platform`):
``linux``
- Node architecture (`node -p process.arch`):
``x64``
- node-sass version (`node -p "require('node-sass').info"`):
``4.13.1``
- npm node-sass versions (`npm ls node-sass`):
```
├─┬ gulp-sass@4.0.2
│ └── node-sass@4.13.1  deduped
└── node-sass@4.13.1 
```
### Exception
```
Error: Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (76)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.13.1
    at module.exports (node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:968:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
    at require (internal/modules/cjs/helpers.js:74:18)
```

**Comment by xzyfer** [comment]
Electron is not supported. Look at the **very first line** of the read me, or any of the release notes.
