### ISSUE TITLE
node-sass\lib\index.js:177 - TypeError: options.includePaths.unshift is not a function

### ISSUE THREAD

**Issue by AdamBearWA** [sass/node-sass#2879]
When trying to 'npm run dev' I get the following error:
```
xxx\node_modules\node-sass\lib\index.js:177
  options.includePaths.unshift(process.cwd());
                       ^

TypeError: options.includePaths.unshift is not a function
    at buildIncludePaths (C:\xxx\node_modules\node-sass\lib\index.js:177:24)
    at getOptions (C:\xxx\node_modules\node-sass\lib\index.js:200:26)
    at Object.module.exports.render (C:\xxx\node_modules\node-sass\lib\index.js:287:17)
    at runQueue (C:\xxx\node_modules\neo-async\async.js:8097:9)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
```

npm 6.13.2
node v12.16.1

node process:
```
{
  node: '12.16.1',
  v8: '7.8.279.23-node.31',
  uv: '1.34.0',
  zlib: '1.2.11',
  brotli: '1.0.7',
  ares: '1.15.0',
  modules: '72',
  nghttp2: '1.40.0',
  napi: '5',
  llhttp: '2.0.4',
  http_parser: '2.9.3',
  openssl: '1.1.1d',
  cldr: '35.1',
  icu: '64.2',
  tz: '2019c',
  unicode: '12.1'
}
```

node architecture: x64

node-sass version:
```
node-sass       4.13.1  (Wrapper)       [JavaScript]
libsass         3.5.4   (Sass Compiler) [C/C++]
```

npm node-sass versions:
```
xxx-react-redux@3.0.0 C:\xxx
`-- node-sass@4.13.1
```

**Comment by nschonni** [comment]
What is `npm run dev` and alias for? EX: how is node-sass being invoked

**Comment by AdamBearWA** [comment]
better-npm-run dev, which in turn turns into: nodemon --exec babel-node devScripts/server

I'm going to let this one go as it seems to be a babel related issue
