### ISSUE TITLE
"node-sass@4.13.1 postinstall: `node scripts/build.js`"

### ISSUE THREAD

**Issue by mlmarinas** [sass/node-sass#2901]
I'm trying to run npm install on my nuxt project folder inside a ubuntu 18 droplet from digitalocean but i keep getting an error from node-sass@4.13.1.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by Yossitrx** [comment]
same here using nginx getting the current log: 

```

[03:51:31]	[Step 1/1] Downloading binary from https://github.com/sass/node-sass/releases/download/v4.13.1/linux_musl-x64-83_binding.node
[03:51:32]	[Step 1/1] Cannot download "https://github.com/sass/node-sass/releases/download/v4.13.1/linux_musl-x64-83_binding.node": 
[03:51:32]	[Step 1/1] 
[03:51:32]	[Step 1/1] HTTP error 404 Not Found
[03:51:32]	[Step 1/1] 
[03:51:32]	[Step 1/1] Hint: If github.com is not accessible in your location
[03:51:32]	[Step 1/1]       try setting a proxy via HTTP_PROXY, e.g. 
[03:51:32]	[Step 1/1] 
[03:51:32]	[Step 1/1]       export HTTP_PROXY=http://example.com:1234
[03:51:32]	[Step 1/1] 
[03:51:32]	[Step 1/1] or configure npm proxy via
[03:51:32]	[Step 1/1] 
[03:51:32]	[Step 1/1]       npm config set proxy http://example.com:8080
[03:51:32]	[Step 1/1] 
[03:51:32]	[Step 1/1] > core-js@2.6.11 postinstall /app/node_modules/babel-runtime/node_modules/core-js
[03:51:32]	[Step 1/1] > node -e "try{require('./postinstall')}catch(e){}"
[03:51:32]	[Step 1/1] 
[03:51:32]	[Step 1/1] Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
[03:51:32]	[Step 1/1] 
[03:51:32]	[Step 1/1] The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
[03:51:32]	[Step 1/1] > https://opencollective.com/core-js 
[03:51:32]	[Step 1/1] > https://www.patreon.com/zloirock 
[03:51:32]	[Step 1/1] 
[03:51:32]	[Step 1/1] Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
[03:51:32]	[Step 1/1] 
[03:51:32]	[Step 1/1] 
[03:51:32]	[Step 1/1] > core-js@3.5.0 postinstall /app/node_modules/core-js
[03:51:32]	[Step 1/1] > node -e "try{require('./postinstall')}catch(e){}"
[03:51:32]	[Step 1/1] 
[03:51:32]	[Step 1/1] Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
[03:51:32]	[Step 1/1] 
[03:51:32]	[Step 1/1] The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
[03:51:32]	[Step 1/1] > https://opencollective.com/core-js 
[03:51:32]	[Step 1/1] > https://www.patreon.com/zloirock 
[03:51:32]	[Step 1/1] 
[03:51:32]	[Step 1/1] Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
[03:51:32]	[Step 1/1] 
[03:51:32]	[Step 1/1] 
[03:51:32]	[Step 1/1] > core-js-pure@3.5.0 postinstall /app/node_modules/core-js-pure
[03:51:32]	[Step 1/1] > node -e "try{require('./postinstall')}catch(e){}"
[03:51:32]	[Step 1/1] 
[03:51:32]	[Step 1/1] Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
[03:51:32]	[Step 1/1] 
[03:51:32]	[Step 1/1] The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
[03:51:32]	[Step 1/1] > https://opencollective.com/core-js 
[03:51:32]	[Step 1/1] > https://www.patreon.com/zloirock 
[03:51:32]	[Step 1/1] 
[03:51:32]	[Step 1/1] Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
[03:51:32]	[Step 1/1] 
[03:51:33]	[Step 1/1] 
[03:51:33]	[Step 1/1] > node-sass@4.13.1 postinstall /app/node_modules/node-sass
[03:51:33]	[Step 1/1] > node scripts/build.js
[03:51:33]	[Step 1/1] 
[03:51:33]	[Step 1/1] Building: /usr/local/bin/node /app/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
[03:51:33]	[Step 1/1] gyp info it worked if it ends with ok
[03:51:33]	[Step 1/1] gyp verb cli [
[03:51:33]	[Step 1/1] gyp verb cli   '/usr/local/bin/node',
[03:51:33]	[Step 1/1] gyp verb cli   '/app/node_modules/node-gyp/bin/node-gyp.js',
[03:51:33]	[Step 1/1] gyp verb cli   'rebuild',
[03:51:33]	[Step 1/1] gyp verb cli   '--verbose',
[03:51:33]	[Step 1/1] gyp verb cli   '--libsass_ext=',
[03:51:33]	[Step 1/1] gyp verb cli   '--libsass_cflags=',
[03:51:33]	[Step 1/1] gyp verb cli   '--libsass_ldflags=',
[03:51:33]	[Step 1/1] gyp verb cli   '--libsass_library='
[03:51:33]	[Step 1/1] gyp verb cli ]
[03:51:33]	[Step 1/1] gyp info using node-gyp@3.8.0
[03:51:33]	[Step 1/1] gyp info using node@14.0.0 | linux | x64
[03:51:33]	[Step 1/1] gyp verb command rebuild []
[03:51:33]	[Step 1/1] gyp verb command clean []
[03:51:33]	[Step 1/1] gyp verb clean removing "build" directory
[03:51:33]	[Step 1/1] gyp verb command configure []
[03:51:33]	[Step 1/1] gyp verb check python checking for Python executable "python2" in the PATH
[03:51:33]	[Step 1/1] gyp verb `which` failed Error: not found: python2
[03:51:33]	[Step 1/1] gyp verb `which` failed     at getNotFoundError (/app/node_modules/which/which.js:13:12)
[03:51:33]	[Step 1/1] gyp verb `which` failed     at F (/app/node_modules/which/which.js:68:19)
[03:51:33]	[Step 1/1] gyp verb `which` failed     at E (/app/node_modules/which/which.js:80:29)
[03:51:33]	[Step 1/1] gyp verb `which` failed     at /app/node_modules/which/which.js:89:16
[03:51:33]	[Step 1/1] gyp verb `which` failed     at /app/node_modules/isexe/index.js:42:5
[03:51:33]	[Step 1/1] gyp verb `which` failed     at /app/node_modules/isexe/mode.js:8:5
[03:51:33]	[Step 1/1] gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:175:21)
[03:51:33]	[Step 1/1] gyp verb `which` failed  python2 Error: not found: python2
[03:51:33]	[Step 1/1] gyp verb `which` failed     at getNotFoundError (/app/node_modules/which/which.js:13:12)
[03:51:33]	[Step 1/1] gyp verb `which` failed     at F (/app/node_modules/which/which.js:68:19)
[03:51:33]	[Step 1/1] gyp verb `which` failed     at E (/app/node_modules/which/which.js:80:29)
[03:51:33]	[Step 1/1] gyp verb `which` failed     at /app/node_modules/which/which.js:89:16
[03:51:33]	[Step 1/1] gyp verb `which` failed     at /app/node_modules/isexe/index.js:42:5
[03:51:33]	[Step 1/1] gyp verb `which` failed     at /app/node_modules/isexe/mode.js:8:5
[03:51:33]	[Step 1/1] gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:175:21) {
[03:51:33]	[Step 1/1] gyp verb `which` failed   code: 'ENOENT'
[03:51:33]	[Step 1/1] gyp verb `which` failed }
[03:51:33]	[Step 1/1] gyp verb check python checking for Python executable "python" in the PATH
[03:51:33]	[Step 1/1] gyp verb `which` failed Error: not found: python
[03:51:33]	[Step 1/1] gyp verb `which` failed     at getNotFoundError (/app/node_modules/which/which.js:13:12)
[03:51:33]	[Step 1/1] gyp verb `which` failed     at F (/app/node_modules/which/which.js:68:19)
[03:51:33]	[Step 1/1] gyp verb `which` failed     at E (/app/node_modules/which/which.js:80:29)
[03:51:33]	[Step 1/1] gyp verb `which` failed     at /app/node_modules/which/which.js:89:16
[03:51:33]	[Step 1/1] gyp verb `which` failed     at /app/node_modules/isexe/index.js:42:5
[03:51:33]	[Step 1/1] gyp verb `which` failed     at /app/node_modules/isexe/mode.js:8:5
[03:51:33]	[Step 1/1] gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:175:21)
[03:51:33]	[Step 1/1] gyp verb `which` failed  python Error: not found: python
[03:51:33]	[Step 1/1] gyp verb `which` failed     at getNotFoundError (/app/node_modules/which/which.js:13:12)
[03:51:33]	[Step 1/1] gyp verb `which` failed     at F (/app/node_modules/which/which.js:68:19)
[03:51:33]	[Step 1/1] gyp verb `which` failed     at E (/app/node_modules/which/which.js:80:29)
[03:51:33]	[Step 1/1] gyp verb `which` failed     at /app/node_modules/which/which.js:89:16
[03:51:33]	[Step 1/1] gyp verb `which` failed     at /app/node_modules/isexe/index.js:42:5
[03:51:33]	[Step 1/1] gyp verb `which` failed     at /app/node_modules/isexe/mode.js:8:5
[03:51:33]	[Step 1/1] gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:175:21) {
[03:51:33]	[Step 1/1] gyp verb `which` failed   code: 'ENOENT'
[03:51:33]	[Step 1/1] gyp verb `which` failed }
[03:51:33]	[Step 1/1] gyp ERR! configure error 
[03:51:33]	[Step 1/1] gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
[03:51:33]	[Step 1/1] gyp ERR! stack     at PythonFinder.failNoPython (/app/node_modules/node-gyp/lib/configure.js:484:19)
[03:51:33]	[Step 1/1] gyp ERR! stack     at PythonFinder.<anonymous> (/app/node_modules/node-gyp/lib/configure.js:406:16)
[03:51:33]	[Step 1/1] gyp ERR! stack     at F (/app/node_modules/which/which.js:68:16)
[03:51:33]	[Step 1/1] gyp ERR! stack     at E (/app/node_modules/which/which.js:80:29)
[03:51:33]	[Step 1/1] gyp ERR! stack     at /app/node_modules/which/which.js:89:16
[03:51:33]	[Step 1/1] gyp ERR! stack     at /app/node_modules/isexe/index.js:42:5
[03:51:33]	[Step 1/1] gyp ERR! stack     at /app/node_modules/isexe/mode.js:8:5
[03:51:33]	[Step 1/1] gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:175:21)
[03:51:33]	[Step 1/1] gyp ERR! System Linux 4.20.10-1.el7.elrepo.x86_64
[03:51:33]	[Step 1/1] gyp ERR! command "/usr/local/bin/node" "/app/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
[03:51:33]	[Step 1/1] gyp ERR! cwd /app/node_modules/node-sass
[03:51:33]	[Step 1/1] gyp ERR! node -v v14.0.0
[03:51:33]	[Step 1/1] gyp ERR! node-gyp -v v3.8.0
[03:51:33]	[Step 1/1] gyp ERR! not ok 
[03:51:33]	[Step 1/1] Build failed with error code: 1
[03:51:34]	[Step 1/1] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/react-scripts/node_modules/fsevents):
[03:51:34]	[Step 1/1] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
[03:51:34]	[Step 1/1] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
[03:51:34]	[Step 1/1] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
[03:51:34]	[Step 1/1] 
[03:51:34]	[Step 1/1] npm ERR! code ELIFECYCLE
[03:51:34]	[Step 1/1] npm ERR! errno 1
[03:51:34]	[Step 1/1] npm ERR! node-sass@4.13.1 postinstall: `node scripts/build.js`
[03:51:34]	[Step 1/1] npm ERR! Exit status 1
[03:51:34]	[Step 1/1] npm ERR! 
[03:51:34]	[Step 1/1] npm ERR! Failed at the node-sass@4.13.1 postinstall script.
[03:51:34]	[Step 1/1] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[03:51:34]	[Step 1/1] 
[03:51:34]	[Step 1/1] npm ERR! A complete log of this run can be found in:
[03:51:34]	[Step 1/1] npm ERR!     /root/.npm/_logs/2020-04-23T08_51_34_969Z-debug.log
[03:51:47]	[Step 1/1] The command '/bin/sh -c npm install' returned a non-zero code: 1
[03:51:47]	[Step 1/1] 
[03:51:47]	[Step 1/1] Process exited with code 1
[03:51:47]	[Step 1/1] Process exited with code 1
[03:51:47]	[Step 1/1] Step Build Docker Image (Command Line) failed
```

**Comment by Yossitrx** [comment]
it's trying to get: 
https://github.com/sass/node-sass/releases/download/v4.13.1/linux_musl-x64-83_binding.node 
but it's getting 404

**Comment by goto-bus-stop** [comment]
downgrade Node.js to v13 for a few days and wait for https://github.com/sass/node-sass/issues/2895 to be fully released.

**Comment by Yossitrx** [comment]
I'm using `FROM node:alpine as builder` in my Nginx file it's the node v14? 
I'm also trying to user the v.4.13.1 sass with link attach but getting 404 in my logs when it's trying to download it.

**Comment by xzyfer** [comment]
v4.14.0 has been released.

**Comment by josuevalrob** [comment]
I am having that issue on node 14.15.4: 
```
C02V7296G8WN:node josue.valencia$ npm prune --force
npm WARN using --force I sure hope you know what you are doing.

> node-sass@4.13.1 install node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.13.1/darwin-x64-83_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.13.1/darwin-x64-83_binding.node": 

HTTP error 404 Not Found

```
