### ISSUE TITLE
Unable to install node-sass 4.14.1 with binary linux-x64-72 on Amazon Linux 1

### ISSUE THREAD

**Issue by wkneewalden** [sass/node-sass#2937]
I am attempting to install node-sass on Amazon Linux 1 manually using a local binary. Prior to the installation, I performed the following steps to assume root and set up a proxy (name hidden) to install node (v12.18.1) and yarn (1.22.4).

```
sudo bash
export http_proxy=http://proxy.X.com:80
export https_proxy=http://proxy.X.com:80
curl -sL https://rpm.nodesource.com/setup_12.x | bash -
yum install -y nodejs
curl -sL https://dl.yarnpkg.com/rpm/yarn.repo | sudo tee /etc/yum.repos.d/yarn.repo
yum install yarn
```

The reason node-sass has to be installed with a local binary is because its behind a corporate proxy that is blocking the download. The reason node-sass has to be installed as root and requires yarn is because the application will involve Grafana plugin creation in the folder /etc/grafana using yarn commands:
https://grafana.com/tutorials/build-a-panel-plugin/#3

Here is code from attempted installation of node-sass locally with steps requested from the troubleshooting guide, and tomorrow I will provide the result for a global install which will eventually be required for the application involving Grafana plugins:

```
[root@ip-10-56-250-57 20200624 21:33:41 ec2-user]# mkdir ~/temp1
[root@ip-10-56-250-57 20200624 21:34:48 ec2-user]# cd ~/temp1/
[root@ip-10-56-250-57 20200624 21:34:55 temp1]# pwd
/root/temp1
[root@ip-10-56-250-57 20200624 21:34:58 temp1]# mv /home/ec2-user/linux-x64-72_binding.node .
[root@ip-10-56-250-57 20200624 21:35:07 temp1]# chown root:root linux-x64-72_binding.node
[root@ip-10-56-250-57 20200624 21:35:14 temp1]# npm -v
6.14.5
[root@ip-10-56-250-57 20200624 21:35:25 temp1]# node -v
v12.18.1
[root@ip-10-56-250-57 20200624 21:35:30 temp1]# node -p process.versions
{
  node: '12.18.1',
  v8: '7.8.279.23-node.38',
  uv: '1.38.0',
  zlib: '1.2.11',
  brotli: '1.0.7',
  ares: '1.16.0',
  modules: '72',
  nghttp2: '1.41.0',
  napi: '6',
  llhttp: '2.0.4',
  http_parser: '2.9.3',
  openssl: '1.1.1g',
  cldr: '37.0',
  icu: '67.1',
  tz: '2019c',
  unicode: '13.0'
}
[root@ip-10-56-250-57 20200624 21:35:36 temp1]# node -p process.platform
linux
[root@ip-10-56-250-57 20200624 21:35:41 temp1]# node -p process.arch
x64
[root@ip-10-56-250-57 20200624 21:35:46 temp1]# npm install --sass-binary-path=/root/temp1/linux-x64-72_binding.node --unsafe-perm node-sass
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

> node-sass@4.14.1 install /root/temp1/node_modules/node-sass
> node scripts/install.js

node-sass build Binary found at /root/temp1/linux-x64-72_binding.node

> node-sass@4.14.1 postinstall /root/temp1/node_modules/node-sass
> node scripts/build.js

Binary found at /root/temp1/linux-x64-72_binding.node
Testing binary
Binary is fine
npm WARN saveError ENOENT: no such file or directory, open '/root/temp1/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/root/temp1/package.json'
npm WARN temp1 No description
npm WARN temp1 No repository field.
npm WARN temp1 No README data
npm WARN temp1 No license field.

+ node-sass@4.14.1
added 190 packages from 139 contributors and audited 190 packages in 32.33s

4 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

[root@ip-10-56-250-57 20200624 21:36:38 temp1]# npm ls node-sass
/root/temp1
└── node-sass@4.14.1

[root@ip-10-56-250-57 20200624 21:36:45 temp1]# node -p "require('node-sass').info"
internal/fs/utils.js:230
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir '/root/temp1/node_modules/node-sass/vendor'
    at Object.readdirSync (fs.js:948:3)
    at Object.getInstalledBinaries (/root/temp1/node_modules/node-sass/lib/extensions.js:133:13)
    at foundBinariesList (/root/temp1/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/root/temp1/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/root/temp1/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/root/temp1/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/root/temp1/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/root/temp1/node_modules/node-sass/vendor'
}
[root@ip-10-56-250-57 20200624 21:37:02 temp1]# node-sass --version
bash: node-sass: command not found
[root@ip-10-56-250-57 20200624 21:42:45 temp1]# node-sass -v
bash: node-sass: command not found
```

**Comment by wkneewalden** [comment]
The result from a global install attempt is shown. Identical steps from the above post omitted:

```
[root@ip-10-56-250-222 20200625 15:04:53 temp1]# npm install -g --sass-binary-path=/root/temp1/linux-x64-72_binding.node --unsafe-perm node-sass
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
/usr/bin/node-sass -> /usr/lib/node_modules/node-sass/bin/node-sass

> node-sass@4.14.1 install /usr/lib/node_modules/node-sass
> node scripts/install.js

node-sass build Binary found at /root/temp1/linux-x64-72_binding.node

> node-sass@4.14.1 postinstall /usr/lib/node_modules/node-sass
> node scripts/build.js

Binary found at /root/temp1/linux-x64-72_binding.node
Testing binary
Binary is fine
+ node-sass@4.14.1
added 190 packages from 139 contributors in 24.238s
[root@ip-10-56-250-222 20200625 15:05:56 temp1]# npm ls node-sass
/root/temp1
└── (empty)

[root@ip-10-56-250-222 20200625 15:06:10 temp1]# node -p "require('node-sass').info"
internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module 'node-sass'
Require stack:
- /root/temp1/[eval]
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at [eval]:1:1
    at Script.runInThisContext (vm.js:120:20)
    at Object.runInThisContext (vm.js:311:38)
    at Object.<anonymous> ([eval]-wrapper:10:26)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at evalScript (internal/process/execution.js:94:25) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/root/temp1/[eval]' ]
}
[root@ip-10-56-250-222 20200625 15:06:21 temp1]# node-sass --version
internal/fs/utils.js:230
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir '/usr/lib/node_modules/node-sass/vendor'
    at Object.readdirSync (fs.js:948:3)
    at Object.getInstalledBinaries (/usr/lib/node_modules/node-sass/lib/extensions.js:133:13)
    at foundBinariesList (/usr/lib/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/usr/lib/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/usr/lib/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/usr/lib/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/usr/lib/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/usr/lib/node_modules/node-sass/vendor'
}
[root@ip-10-56-250-222 20200625 15:06:33 temp1]# node-sass -v
internal/fs/utils.js:230
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir '/usr/lib/node_modules/node-sass/vendor'
    at Object.readdirSync (fs.js:948:3)
    at Object.getInstalledBinaries (/usr/lib/node_modules/node-sass/lib/extensions.js:133:13)
    at foundBinariesList (/usr/lib/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/usr/lib/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/usr/lib/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/usr/lib/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/usr/lib/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/usr/lib/node_modules/node-sass/vendor'
}
```

**Comment by auszug** [comment]
@wkneewalden - the problem appears to be in the root privileges. Running it as a normal user without super/sudo privileges did a trick for me.

**Comment by wkneewalden** [comment]
Thanks for the suggestion. I attempted to install node-sass locally with a normal user and got a similar result. In this situation I installed a later version of node (v14.7.0) and thus used a different binary (x64-83):

```
[ec2-user@ip-10-56-248-251 20200803 22:00:21 ~]$ npm install --sass-binary-path=/home/ec2-user/linux-x64-83_binding.node node-sass
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported> node-sass@4.14.1 install /home/ec2-user/node_modules/node-sass
> node scripts/install.jsnode-sass build Binary found at /home/ec2-user/linux-x64-83_binding.node> node-sass@4.14.1 postinstall /home/ec2-user/node_modules/node-sass
> node scripts/build.jsBinary found at /home/ec2-user/linux-x64-83_binding.node
Testing binary
Binary is fine
npm WARN saveError ENOENT: no such file or directory, open '/home/ec2-user/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/home/ec2-user/package.json'
npm WARN ec2-user No description
npm WARN ec2-user No repository field.
npm WARN ec2-user No README data
npm WARN ec2-user No license field.+ node-sass@4.14.1
added 190 packages from 139 contributors and audited 190 packages in 16.587s5 packages are looking for funding
  run `npm fund` for detailsfound 0 vulnerabilities
[ec2-user@ip-10-56-248-251 20200803 22:01:03 ~]$ node-sass -v
-bash: node-sass: command not found
```

**Comment by wkneewalden** [comment]
The issue was related to the corporate proxy. Once the firewall was lifted to the necessary RPM path, the global install went through using root.

**Comment by coder-bing** [comment]
$ mkdir -p node_modules/node-sass/vendor/linux-x64-83
$ cd $_
$ wget https://github.com/sass/node-sass/releases/download/v4.14.1/linux-x64-83_binding.node -O binding.node
