### ISSUE TITLE
Having Issues installing node-saas module in my Windows 10 machine. Binary has a problem: Error: node-sass\vendor\win32-x64-64\binding.node is not a valid Win32 application

### ISSUE THREAD

**Issue by github-amar** [sass/node-sass#2940]
- NPM version (`npm -v`):6.9.0
- Node version (`node -v`):10.16.0
- Node Process (`node -p process.versions`):
{ http_parser: '2.8.0',
  node: '10.16.0',
  v8: '6.8.275.32-node.52',
  uv: '1.28.0',
  zlib: '1.2.11',
  brotli: '1.0.7',
  ares: '1.15.0',
  modules: '64',
  nghttp2: '1.34.0',
  napi: '4',
  openssl: '1.1.1b',
  icu: '64.2',
  unicode: '12.1',
  cldr: '35.1',
  tz: '2019a' }
- Node Platform (`node -p process.platform`):win32
- Node architecture (`node -p process.arch`):x64
- node-sass version (`node -p "require('node-sass').info"`):
internal/modules/cjs/loader.js:805
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: \\?\C:\Temp\node_modules\node-sass\vendor\win32-x64-64\binding.node is not a valid Win32 application.
\\?\C:\Temp\node_modules\node-sass\vendor\win32-x64-64\binding.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:805:18)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at module.exports (C:\Temp\node_modules\node-sass\lib\binding.js:19:10)
    at Object.<anonymous> (C:\Temp\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)

- npm node-sass versions (`npm ls node-sass`):
C:\Temp
`-- node-sass@4.14.1

I have tried several ways of installing node-saas into my Windows 10 environment, but nothing seemed to work, I keep getting the error message "node-sass\vendor\win32-x64-64\binding.node is not a valid Win32 application." Any help regarding this is appreciated.

I have also tried installing node-sass module offline by downloading the binary from https://github.com/sass/node-sass/releases (disabling all proxy settings) and manually copying it to "npm-cache\node-sass\4.14.1" folder and it still didn't work. I have even tried installing several other node-sass versions as well and nothing seemed to work. Everything is giving me the same 'is not a valid Win32 application' error.

**Comment by github-amar** [comment]
This issue seems to be caused by an app-control software running in my machine blocking the 'binding.node' binary file to run, once our security has evaluated and whitelisted this binary I was able to run and use it just fine. Hence, this issue can be closed.
