### ISSUE TITLE
npm --only=dev doesn't work, but npm ci and npm install do

### ISSUE THREAD

**Issue by vadimyen** [sass/node-sass#2957]
- NPM version (`npm -v`): 6.14.7
- Node version (`node -v`): v12.18.2
- Node Process (`node -p process.versions`): 
```
{
  node: '12.18.2',
  v8: '7.8.279.23-node.39',
  uv: '1.38.0',
  zlib: '1.2.11',
  brotli: '1.0.7',
  ares: '1.16.0',
  modules: '72',
  nghttp2: '1.41.0',
  napi: '6',
  llhttp: '2.0.4',
  http_parser: '2.9.3',
  openssl: '1.1.1g',
  cldr: '37.0',
  icu: '67.1',
  tz: '2019c',
  unicode: '13.0'
}
```
- Node Platform (`node -p process.platform`): linux
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`):
```
node-sass       4.14.1  (Wrapper)       [JavaScript]
libsass         3.5.5   (Sass Compiler) [C/C++]
```
- npm node-sass versions (`npm ls node-sass`): node-sass@4.14.1

Everything is okay when i use plain `npm install` or `npm ci`, but now I want to install just devDeps in some jobs on CI and try running the command `npm install --only=dev` as non-root user (as usual), but get the error locally and on CI:

> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! node-sass@4.14.1 install: `node scripts/install.js`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the node-sass@4.14.1 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/vadim/.npm/_logs/2020-08-16T08_43_54_641Z-debug.log

The content of `/home/vadim/.npm/_logs/2020-08-16T08_43_54_641Z-debug.log`:

> 36150 verbose stack Error: node-sass@4.14.1 install: `node scripts/install.js`
> 36150 verbose stack Exit status 1
> 36150 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
> 36150 verbose stack     at EventEmitter.emit (events.js:315:20)
> 36150 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
> 36150 verbose stack     at ChildProcess.emit (events.js:315:20)
> 36150 verbose stack     at maybeClose (internal/child_process.js:1021:16)
> 36150 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
> 36151 verbose pkgid node-sass@4.14.1
> 36152 verbose cwd /home/vadim/SMENA/site-frontend
> 36153 verbose Linux 5.4.0-42-generic
> 36154 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--only=dev"
> 36155 verbose node v12.18.2
> 36156 verbose npm  v6.14.7
> 36157 error code ELIFECYCLE
> 36158 error errno 1
> 36159 error node-sass@4.14.1 install: `node scripts/install.js`
> 36159 error Exit status 1
> 36160 error Failed at the node-sass@4.14.1 install script.
> 36160 error This is probably not a problem with npm. There is likely additional logging output above.
> 36161 verbose exit [ 1, true ]

What can be the reason of that?

**Comment by vadimyen** [comment]
hello!

**Comment by YensZAF** [comment]
I have the same issue when using `npm install --save-dev`

**Comment by YensZAF** [comment]
The error given below:

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.14.1/linux-x64-88_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.14.1/linux-x64-88_binding.node": 

HTTP error 404 Not Found

When looking on github there is no linux-x64-88_binding.node under v4.14.1

`npm -v` = 6.14.9
`node -v` = 15.2.1
