### ISSUE TITLE
node-sass does not compile

### ISSUE THREAD

**Issue by fabianfrz** [sass/node-sass#2959]
- NPM version (`npm -v`): 6.14.7
- Node version (`node -v`): v14.7.0
- Node Process (`node -p process.versions`):
```
{
  node: '14.7.0',
  v8: '8.4.371.19-node.12',
  uv: '1.38.1',
  zlib: '1.2.11',
  brotli: '1.0.7',
  ares: '1.16.1',
  modules: '83',
  nghttp2: '1.41.0',
  napi: '6',
  llhttp: '2.0.4',
  openssl: '1.1.1g',
  cldr: '37.0',
  icu: '67.1',
  tz: '2019c',
  unicode: '13.0'
}
```
- Node Platform (`node -p process.platform`): linux
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`): 
- npm node-sass versions (`npm ls node-sass`):

Additional:
* Distribution: Manjaro Linux

```
./../../../../nan/nan_converters_43_inl.h: In statischer Elementfunktion »static Nan::imp::ToFactoryBase<v8::Boolean>::return_t Nan::imp::ToFactory<v8::Boolean>::convert(v8::Local<v8::Value>)«:
../../../../../nan/nan_converters_43_inl.h:18:49: Fehler: »v8::Local<v8::Context>« kann nicht nach »v8::Isolate*« umgewandelt werden
   18 |       val->To ## TYPE(isolate->GetCurrentContext())                            \
      |                       ~~~~~~~~~~~~~~~~~~~~~~~~~~^~
      |                                                 |
      |                                                 v8::Local<v8::Context>
../../../../../nan/nan_converters_43_inl.h:22:1: Anmerkung: bei Substitution des Makros »X«
   22 | X(Boolean)
      | ^
In Datei, eingebunden von $HOME/.cache/node-gyp/14.7.0/include/node/node.h:67,
                 von ../../../../../nan/nan.h:52,
                 von ../src/binding.cpp:1:
$HOME/.cache/node-gyp/14.7.0/include/node/v8.h:2848:37: Anmerkung:   Argument 1 von »v8::Local<v8::Boolean> v8::Value::ToBoolean(v8::Isolate*) const« wird initialisiert
 2848 |   Local<Boolean> ToBoolean(Isolate* isolate) const;
      |                            ~~~~~~~~~^~~~~~~
In Datei, eingebunden von ../../../../../nan/nan_converters.h:67,
                 von ../../../../../nan/nan.h:221,
                 von ../src/binding.cpp:1:
../../../../../nan/nan_converters_43_inl.h: In statischer Elementfunktion »static Nan::imp::ValueFactoryBase<bool>::return_t Nan::imp::ToFactory<bool>::convert(v8::Local<v8::Value>)«:
../../../../../nan/nan_converters_43_inl.h:37:55: Fehler: »v8::Local<v8::Context>« kann nicht nach »v8::Isolate*« umgewandelt werden
   37 |   return val->NAME ## Value(isolate->GetCurrentContext());                     \
      |                             ~~~~~~~~~~~~~~~~~~~~~~~~~~^~
      |                                                       |
      |                                                       v8::Local<v8::Context>
../../../../../nan/nan_converters_43_inl.h:40:1: Anmerkung: bei Substitution des Makros »X«
   40 | X(bool, Boolean)
      | ^
In Datei, eingebunden von $HOME/.cache/node-gyp/14.7.0/include/node/node.h:67,
                 von ../../../../../nan/nan.h:52,
                 von ../src/binding.cpp:1:
$HOME/.cache/node-gyp/14.7.0/include/node/v8.h:2858:30: Anmerkung:   Argument 1 von »bool v8::Value::BooleanValue(v8::Isolate*) const« wird initialisiert
 2858 |   bool BooleanValue(Isolate* isolate) const;
      |                     ~~~~~~~~~^~~~~~~
In Datei, eingebunden von ../../../../../nan/nan_new.h:189,
                 von ../../../../../nan/nan.h:222,
                 von ../src/binding.cpp:1:
../../../../../nan/nan_implementation_12_inl.h: In statischer Elementfunktion »static Nan::imp::FactoryBase<v8::Function>::return_t Nan::imp::Factory<v8::Function>::New(Nan::FunctionCallback, v8::Local<v8::Value>)«:
../../../../../nan/nan_implementation_12_inl.h:103:42: Fehler: »v8::Isolate*« kann nicht nach »v8::Local<v8::Context>« umgewandelt werden
  103 |   return scope.Escape(v8::Function::New( isolate
      |                                          ^~~~~~~
      |                                          |
      |                                          v8::Isolate*
In Datei, eingebunden von $HOME/.cache/node-gyp/14.7.0/include/node/node.h:67,
                 von ../../../../../nan/nan.h:52,
                 von ../src/binding.cpp:1:
$HOME/.cache/node-gyp/14.7.0/include/node/v8.h:4446:22: Anmerkung:   Argument 1 von »static v8::MaybeLocal<v8::Function> v8::Function::New(v8::Local<v8::Context>, v8::FunctionCallback, v8::Local<v8::Value>, int, v8::ConstructorBehavior, v8::SideEffectType)« wird initialisiert
 4446 |       Local<Context> context, FunctionCallback callback,
      |       ~~~~~~~~~~~~~~~^~~~~~~
In Datei, eingebunden von ../src/binding.cpp:1:
../../../../../nan/nan.h: In Konstruktor »Nan::Utf8String::Utf8String(v8::Local<v8::Value>)«:
../../../../../nan/nan.h:1064:76: Fehler: »v8::Isolate*« kann nicht nach »v8::Local<v8::Context>« umgewandelt werden
 1064 |       v8::Local<v8::String> string = from->ToString(v8::Isolate::GetCurrent());
      |                                                     ~~~~~~~~~~~~~~~~~~~~~~~^~
      |                                                                            |
      |                                                                            v8::Isolate*
In Datei, eingebunden von $HOME/.cache/node-gyp/14.7.0/include/node/node.h:67,
                 von ../../../../../nan/nan.h:52,
                 von ../src/binding.cpp:1:
$HOME/.cache/node-gyp/14.7.0/include/node/v8.h:2811:22: Anmerkung:   Argument 1 von »v8::MaybeLocal<v8::String> v8::Value::ToString(v8::Local<v8::Context>) const« wird initialisiert
 2811 |       Local<Context> context) const;
      |       ~~~~~~~~~~~~~~~^~~~~~~
In Datei, eingebunden von ../src/binding.cpp:1:
../../../../../nan/nan.h: In Elementfunktion »void Nan::AsyncWorker::SaveToPersistent(const char*, const v8::Local<v8::Value>&)«:
../../../../../nan/nan.h:1855:64: Fehler: keine passende Funktion für Aufruf von »v8::Object::Set(v8::Local<v8::String>, const v8::Local<v8::Value>&)«
 1855 |     New(persistentHandle)->Set(New(key).ToLocalChecked(), value);
      |                                                                ^
In Datei, eingebunden von $HOME/.cache/node-gyp/14.7.0/include/node/node.h:67,
                 von ../../../../../nan/nan.h:52,
                 von ../src/binding.cpp:1:
$HOME/.cache/node-gyp/14.7.0/include/node/v8.h:3670:37: Anmerkung: Kandidat: »v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)«
 3670 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
      |                                     ^~~
$HOME/.cache/node-gyp/14.7.0/include/node/v8.h:3670:37: Anmerkung:   Kandidat erwartet 3 Argumente, 2 angegeben
$HOME/.cache/node-gyp/14.7.0/include/node/v8.h:3673:37: Anmerkung: Kandidat: »v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)«
 3673 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
      |                                     ^~~
$HOME/.cache/node-gyp/14.7.0/include/node/v8.h:3673:37: Anmerkung:   Kandidat erwartet 3 Argumente, 2 angegeben
In Datei, eingebunden von ../src/binding.cpp:1:
../../../../../nan/nan.h: In Elementfunktion »void Nan::AsyncWorker::SaveToPersistent(const v8::Local<v8::String>&, const v8::Local<v8::Value>&)«:
../../../../../nan/nan.h:1861:42: Fehler: keine passende Funktion für Aufruf von »v8::Object::Set(const v8::Local<v8::String>&, const v8::Local<v8::Value>&)«
 1861 |     New(persistentHandle)->Set(key, value);
      |                                          ^
In Datei, eingebunden von $HOME/.cache/node-gyp/14.7.0/include/node/node.h:67,
                 von ../../../../../nan/nan.h:52,
                 von ../src/binding.cpp:1:
$HOME/.cache/node-gyp/14.7.0/include/node/v8.h:3670:37: Anmerkung: Kandidat: »v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)«
 3670 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
      |                                     ^~~
$HOME/.cache/node-gyp/14.7.0/include/node/v8.h:3670:37: Anmerkung:   Kandidat erwartet 3 Argumente, 2 angegeben
$HOME/.cache/node-gyp/14.7.0/include/node/v8.h:3673:37: Anmerkung: Kandidat: »v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)«
 3673 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
      |                                     ^~~
$HOME/.cache/node-gyp/14.7.0/include/node/v8.h:3673:37: Anmerkung:   Kandidat erwartet 3 Argumente, 2 angegeben
In Datei, eingebunden von ../src/binding.cpp:1:
../../../../../nan/nan.h: In Elementfunktion »void Nan::AsyncWorker::SaveToPersistent(uint32_t, const v8::Local<v8::Value>&)«:
../../../../../nan/nan.h:1867:44: Fehler: keine passende Funktion für Aufruf von »v8::Object::Set(uint32_t&, const v8::Local<v8::Value>&)«
 1867 |     New(persistentHandle)->Set(index, value);
      |                                            ^
In Datei, eingebunden von $HOME/.cache/node-gyp/14.7.0/include/node/node.h:67,
                 von ../../../../../nan/nan.h:52,
                 von ../src/binding.cpp:1:
$HOME/.cache/node-gyp/14.7.0/include/node/v8.h:3670:37: Anmerkung: Kandidat: »v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)«
 3670 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
      |                                     ^~~
$HOME/.cache/node-gyp/14.7.0/include/node/v8.h:3670:37: Anmerkung:   Kandidat erwartet 3 Argumente, 2 angegeben
$HOME/.cache/node-gyp/14.7.0/include/node/v8.h:3673:37: Anmerkung: Kandidat: »v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)«
 3673 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
      |                                     ^~~
$HOME/.cache/node-gyp/14.7.0/include/node/v8.h:3673:37: Anmerkung:   Kandidat erwartet 3 Argumente, 2 angegeben
In Datei, eingebunden von ../src/binding.cpp:1:
../../../../../nan/nan.h: In Elementfunktion »v8::Local<v8::Value> Nan::AsyncWorker::GetFromPersistent(const char*) const«:
../../../../../nan/nan.h:1873:61: Fehler: keine passende Funktion für Aufruf von »v8::Object::Get(v8::Local<v8::String>)«
 1873 |         New(persistentHandle)->Get(New(key).ToLocalChecked()));
      |                                                             ^
In Datei, eingebunden von $HOME/.cache/node-gyp/14.7.0/include/node/node.h:67,
                 von ../../../../../nan/nan.h:52,
                 von ../src/binding.cpp:1:
$HOME/.cache/node-gyp/14.7.0/include/node/v8.h:3717:43: Anmerkung: Kandidat: »v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, v8::Local<v8::Value>)«
 3717 |   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
      |                                           ^~~
$HOME/.cache/node-gyp/14.7.0/include/node/v8.h:3717:43: Anmerkung:   Kandidat erwartet 2 Argumente, 1 angegeben
$HOME/.cache/node-gyp/14.7.0/include/node/v8.h:3720:43: Anmerkung: Kandidat: »v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, uint32_t)«
 3720 |   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
      |                                           ^~~
$HOME/.cache/node-gyp/14.7.0/include/node/v8.h:3720:43: Anmerkung:   Kandidat erwartet 2 Argumente, 1 angegeben
In Datei, eingebunden von ../src/binding.cpp:1:
../../../../../nan/nan.h: In Elementfunktion »v8::Local<v8::Value> Nan::AsyncWorker::GetFromPersistent(const v8::Local<v8::String>&) const«:
../../../../../nan/nan.h:1879:55: Fehler: keine passende Funktion für Aufruf von »v8::Object::Get(const v8::Local<v8::String>&)«
 1879 |     return scope.Escape(New(persistentHandle)->Get(key));
      |                                                       ^
In Datei, eingebunden von $HOME/.cache/node-gyp/14.7.0/include/node/node.h:67,
                 von ../../../../../nan/nan.h:52,
                 von ../src/binding.cpp:1:
$HOME/.cache/node-gyp/14.7.0/include/node/v8.h:3717:43: Anmerkung: Kandidat: »v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, v8::Local<v8::Value>)«
 3717 |   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
      |                                           ^~~
$HOME/.cache/node-gyp/14.7.0/include/node/v8.h:3717:43: Anmerkung:   Kandidat erwartet 2 Argumente, 1 angegeben
$HOME/.cache/node-gyp/14.7.0/include/node/v8.h:3720:43: Anmerkung: Kandidat: »v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, uint32_t)«
 3720 |   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
      |                                           ^~~
$HOME/.cache/node-gyp/14.7.0/include/node/v8.h:3720:43: Anmerkung:   Kandidat erwartet 2 Argumente, 1 angegeben
In Datei, eingebunden von ../src/binding.cpp:1:
../../../../../nan/nan.h: In Elementfunktion »v8::Local<v8::Value> Nan::AsyncWorker::GetFromPersistent(uint32_t) const«:
../../../../../nan/nan.h:1884:57: Fehler: keine passende Funktion für Aufruf von »v8::Object::Get(uint32_t&)«
 1884 |     return scope.Escape(New(persistentHandle)->Get(index));
      |                                                         ^
In Datei, eingebunden von $HOME/.cache/node-gyp/14.7.0/include/node/node.h:67,
                 von ../../../../../nan/nan.h:52,
                 von ../src/binding.cpp:1:
$HOME/.cache/node-gyp/14.7.0/include/node/v8.h:3717:43: Anmerkung: Kandidat: »v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, v8::Local<v8::Value>)«
 3717 |   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
      |                                           ^~~
$HOME/.cache/node-gyp/14.7.0/include/node/v8.h:3717:43: Anmerkung:   Kandidat erwartet 2 Argumente, 1 angegeben
$HOME/.cache/node-gyp/14.7.0/include/node/v8.h:3720:43: Anmerkung: Kandidat: »v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, uint32_t)«
 3720 |   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
      |                                           ^~~
$HOME/.cache/node-gyp/14.7.0/include/node/v8.h:3720:43: Anmerkung:   Kandidat erwartet 2 Argumente, 1 angegeben
In Datei, eingebunden von ../src/binding.cpp:1:
../../../../../nan/nan.h: In Funktion »void Nan::AsyncQueueWorker(Nan::AsyncWorker*)«:
../../../../../nan/nan.h:2208:7: Warnung: Umwandlung zwischen inkompatiblen Funktionstypen von »void (*)(uv_work_t*)« {aka »void (*)(uv_work_s*)«} nach »uv_after_work_cb« {aka »void (*)(uv_work_s*, int)«} [-Wcast-function-type]
 2208 |     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In Datei, eingebunden von /usr/include/c++/10.1.0/cassert:44,
                 von $HOME/.cache/node-gyp/14.7.0/include/node/node_object_wrap.h:26,
                 von ../../../../../nan/nan.h:54,
                 von ../src/binding.cpp:1:
../../../../../nan/nan_object_wrap.h: In Destruktor »virtual Nan::ObjectWrap::~ObjectWrap()«:
../../../../../nan/nan_object_wrap.h:24:25: Fehler: »class Nan::Persistent<v8::Object>« hat kein Element namens »IsNearDeath«
   24 |     assert(persistent().IsNearDeath());
      |                         ^~~~~~~~~~~
In Datei, eingebunden von ../../../../../nan/nan.h:2698,
                 von ../src/binding.cpp:1:
../../../../../nan/nan_object_wrap.h: In Elementfunktion »void Nan::ObjectWrap::MakeWeak()«:
../../../../../nan/nan_object_wrap.h:67:18: Fehler: »class Nan::Persistent<v8::Object>« hat kein Element namens »MarkIndependent«
   67 |     persistent().MarkIndependent();
      |                  ^~~~~~~~~~~~~~~
In Datei, eingebunden von /usr/include/c++/10.1.0/cassert:44,
                 von $HOME/.cache/node-gyp/14.7.0/include/node/node_object_wrap.h:26,
                 von ../../../../../nan/nan.h:54,
                 von ../src/binding.cpp:1:
../../../../../nan/nan_object_wrap.h: In statischer Elementfunktion »static void Nan::ObjectWrap::WeakCallback(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)«:
../../../../../nan/nan_object_wrap.h:124:26: Fehler: »class Nan::Persistent<v8::Object>« hat kein Element namens »IsNearDeath«
  124 |     assert(wrap->handle_.IsNearDeath());
      |                          ^~~~~~~~~~~
../src/binding.cpp: In Funktion »Nan::NAN_METHOD_RETURN_TYPE render(Nan::NAN_METHOD_ARGS_TYPE)«:
../src/binding.cpp:284:80: Warnung: Umwandlung zwischen inkompatiblen Funktionstypen von »void (*)(uv_work_t*)« {aka »void (*)(uv_work_s*)«} nach »uv_after_work_cb« {aka »void (*)(uv_work_s*, int)«} [-Wcast-function-type]
  284 |     int status = uv_queue_work(uv_default_loop(), &ctx_w->request, compile_it, (uv_after_work_cb)MakeCallback);
      |                                                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/binding.cpp: In Funktion »Nan::NAN_METHOD_RETURN_TYPE render_file(Nan::NAN_METHOD_ARGS_TYPE)«:
../src/binding.cpp:320:80: Warnung: Umwandlung zwischen inkompatiblen Funktionstypen von »void (*)(uv_work_t*)« {aka »void (*)(uv_work_s*)«} nach »uv_after_work_cb« {aka »void (*)(uv_work_s*, int)«} [-Wcast-function-type]
  320 |     int status = uv_queue_work(uv_default_loop(), &ctx_w->request, compile_it, (uv_after_work_cb)MakeCallback);
      |                                                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In Datei, eingebunden von ../../../../../nan/nan.h:52,
                 von ../src/binding.cpp:1:
../src/binding.cpp: Im globalen Gültigkeitsbereich:
$HOME/.cache/node-gyp/14.7.0/include/node/node.h:746:7: Warnung: Umwandlung zwischen inkompatiblen Funktionstypen von »void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)« {aka »void (*)(v8::Local<v8::Object>)«} nach »node::addon_register_func« {aka »void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)«} [-Wcast-function-type]
  746 |       (node::addon_register_func) (regfunc),                          \
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
$HOME/.cache/node-gyp/14.7.0/include/node/node.h:780:3: Anmerkung: bei Substitution des Makros »NODE_MODULE_X«
  780 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
      |   ^~~~~~~~~~~~~
../src/binding.cpp:358:1: Anmerkung: bei Substitution des Makros »NODE_MODULE«
  358 | NODE_MODULE(binding, RegisterModule);
      | ^~~~~~~~~~~
In Datei, eingebunden von ../src/binding.cpp:1:
../../../../../nan/nan.h: In Instanziierung von »void Nan::imp::SetMethodAux(T, v8::Local<v8::String>, v8::Local<v8::FunctionTemplate>, ...) [with T = v8::Local<v8::Object>]«:
../../../../../nan/nan.h:2394:20:   erfordert durch »void Nan::SetMethod(HandleType<T>, const char*, Nan::FunctionCallback) [with T = v8::Object; HandleType = v8::Local; Nan::FunctionCallback = void (*)(const Nan::FunctionCallbackInfo<v8::Value>&)]«
../src/binding.cpp:350:42:   von hier erfordert
../../../../../nan/nan.h:2378:12: Fehler: keine passende Funktion für Aufruf von »v8::Object::Set(v8::Local<v8::String>&, v8::Local<v8::Function>)«
 2378 |   recv->Set(name, GetFunction(tpl).ToLocalChecked());
      |   ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In Datei, eingebunden von $HOME/.cache/node-gyp/14.7.0/include/node/node.h:67,
                 von ../../../../../nan/nan.h:52,
                 von ../src/binding.cpp:1:
$HOME/.cache/node-gyp/14.7.0/include/node/v8.h:3670:37: Anmerkung: Kandidat: »v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)«
 3670 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
      |                                     ^~~
$HOME/.cache/node-gyp/14.7.0/include/node/v8.h:3670:37: Anmerkung:   Kandidat erwartet 3 Argumente, 2 angegeben
$HOME/.cache/node-gyp/14.7.0/include/node/v8.h:3673:37: Anmerkung: Kandidat: »v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)«
 3673 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
      |                                     ^~~
$HOME/.cache/node-gyp/14.7.0/include/node/v8.h:3673:37: Anmerkung:   Kandidat erwartet 3 Argumente, 2 angegeben
make: *** [binding.target.mk:127: Release/obj.target/binding/src/binding.o] Fehler 1
make: Verzeichnis „/path/to/project/node_modules/@angular-devkit/build-angular/node_modules/node-sass/build“ wird verlassen
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/path/to/project/node_modules/@angular-devkit/build-angular/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 5.7.14-1-MANJARO
gyp ERR! command "/usr/bin/node" "/path/to/project/node_modules/@angular-devkit/build-angular/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /path/to/project/node_modules/@angular-devkit/build-angular/node_modules/node-sass
gyp ERR! node -v v14.7.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok 
Build failed with error code: 1
```

**Comment by zdm** [comment]
`node-gyp` need to be upgraded to the latest version.

**Comment by ievgennaida** [comment]
Same problems during the ci/cd build.
Sometimes working, sometimes not. 
Version 5.0.0

**Comment by recoiladam** [comment]
I seem to be having what night look to be the same issue or similiar.

https://pb.recoilnetworks.com/?dc2d0678b09ad30a#gHOUChIthKU5wi5Z1l4ii323/l7ZGmldlXeoOPtLiiY=

```
{
  "name": "...",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build"
  },
  "dependencies": {
    "register-service-worker": "^1.7.1",
    "vue": "^3.0.0",
    "vue-router": "^4.0.0-0",
    "vuex": "^4.0.0-0"
  },
  "devDependencies": {
    "@vue/cli-plugin-pwa": "~4.5.0",
    "@vue/cli-plugin-router": "~4.5.0",
    "@vue/cli-plugin-vuex": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/compiler-sfc": "^3.0.0",
    "node-sass": "4.11.0",
    "sass-loader": "^8.0.2",
    "sass": "^1.26.5"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not dead"
  ]
}
```

npm -v = 7.19.0
node -v = v16.4.0
macos = 11.4 (Mac Pro 2013 - Intel Xeon)

Everything worked until I upgraded node and npm using homebrew. I need this fixed and not sure how. My entire development environment is broken now because of this so any help is appreciated.

**Comment by ievgennaida** [comment]
Migrated to "sass" solves the problem, works ok for now.

**Comment by recoiladam** [comment]
> I seem to be having what night look to be the same issue or similiar.
> 
> https://pb.recoilnetworks.com/?dc2d0678b09ad30a#gHOUChIthKU5wi5Z1l4ii323/l7ZGmldlXeoOPtLiiY=
> 
> ```
> {
>   "name": "...",
>   "version": "0.1.0",
>   "private": true,
>   "scripts": {
>     "serve": "vue-cli-service serve",
>     "build": "vue-cli-service build"
>   },
>   "dependencies": {
>     "register-service-worker": "^1.7.1",
>     "vue": "^3.0.0",
>     "vue-router": "^4.0.0-0",
>     "vuex": "^4.0.0-0"
>   },
>   "devDependencies": {
>     "@vue/cli-plugin-pwa": "~4.5.0",
>     "@vue/cli-plugin-router": "~4.5.0",
>     "@vue/cli-plugin-vuex": "~4.5.0",
>     "@vue/cli-service": "~4.5.0",
>     "@vue/compiler-sfc": "^3.0.0",
>     "node-sass": "4.11.0",
>     "sass-loader": "^8.0.2",
>     "sass": "^1.26.5"
>   },
>   "browserslist": [
>     "> 1%",
>     "last 2 versions",
>     "not dead"
>   ]
> }
> ```
> 
> npm -v = 7.19.0
> node -v = v16.4.0
> macos = 11.4 (Mac Pro 2013 - Intel Xeon)
> 
> Everything worked until I upgraded node and npm using homebrew. I need this fixed and not sure how. My entire development environment is broken now because of this so any help is appreciated.

I ended up downgrading to fix my environment and then switched as many projects over to "sass" as I could.
