### ISSUE TITLE
Problems with Linux 64 bit and Node Saas

### ISSUE THREAD

**Issue by MJabardo** [sass/node-sass#2988]
Hi !!!

I have this problem when I try run my App:

"[02/10/2020 11:19:13] [ERROR] Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (86)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.13.1"

I work with Ubuntu (release 20.04.1 LTS)

- NPM version (`npm -v`): 6.14.8
- Node version (`node -v`): v15.0.0-nightly20201001726143e683
- Node Process (`node -p process.versions`): 

{
  node: '15.0.0-nightly20201001726143e683',
  v8: '8.4.371.19-node.16',
  uv: '1.40.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.16.1',
  modules: '86',
  nghttp2: '1.41.0',
  napi: '7',
  llhttp: '2.1.2',
  openssl: '1.1.1g',
  cldr: '37.0',
  icu: '67.1',
  tz: '2020a',
  unicode: '13.0'
}

- Node Platform (`node -p process.platform`): linux
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`): 

internal/modules/cjs/loader.js:1131
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /snap/core/current/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/manueljabardo/Cells/bxs0-form-moto/node_modules/node-sass/vendor/linux-x64-86/binding.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1131:18)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:14)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at module.exports (/home/manueljabardo/Cells/bxs0-form-moto/node_modules/node-sass/lib/binding.js:19:10)
    at Object.<anonymous> (/home/manueljabardo/Cells/bxs0-form-moto/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:1072:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)

- npm node-sass versions (`npm ls node-sass`):

 bxs0-form-moto@0.1.0 /home/manueljabardo/Cells/bxs0-form-moto
└── node-sass@4.14.1 

thanks a lot!!!

**Comment by xzyfer** [comment]
Only stable versions of node are supported. Downgrade to node 14.

**Comment by liudonghua123** [comment]
Now the node 15 is stable.
