### ISSUE TITLE
Nodejs v8 - v14 Centos 7 EACCES permission denied

### ISSUE THREAD

**Issue by un-fuf-a-doo** [sass/node-sass#2989]
- NPM version (`npm -v`): v6.14.8
- Node version (`node -v`): v14.12.0
- Node Process (`node -p process.versions`):
```
{
  node: '14.12.0',
  v8: '8.4.371.19-node.16',
  uv: '1.39.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.16.0',
  modules: '83',
  nghttp2: '1.41.0',
  napi: '7',
  llhttp: '2.1.2',
  openssl: '1.1.1g',
  cldr: '37.0',
  icu: '67.1',
  tz: '2020a',
  unicode: '13.0'
}
```
- Node Platform (`node -p process.platform`): linux
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`): None
- npm node-sass versions (`npm ls node-sass`): None

On CentOS 7, I cannot get node-sass of any version installed no matter what version of Node is installed. I have gone all the way back to v8 and up to v14.12.  I am simply trying to install using npm and it fails massively each time with the below log.

I am not sure I understand the version requirements node-sass.  Do I have to force npm to install a specific version of node-sass?  Why do I get EACCES permission denied when running as root?  This makes little sense to me and I really could use some help when you have time.

Complete log:
```
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
/usr/bin/node-sass -> /usr/lib/node_modules/node-sass/bin/node-sass

> node-sass@4.14.1 install /usr/lib/node_modules/node-sass
> node scripts/install.js

Unable to save binary /usr/lib/node_modules/node-sass/vendor/linux-x64-83 : Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/node-sass/vendor'
    at Object.mkdirSync (fs.js:948:3)
    at sync (/usr/lib/node_modules/node-sass/node_modules/mkdirp/index.js:72:13)
    at Function.sync (/usr/lib/node_modules/node-sass/node_modules/mkdirp/index.js:78:24)
    at checkAndDownloadBinary (/usr/lib/node_modules/node-sass/scripts/install.js:114:11)
    at Object.<anonymous> (/usr/lib/node_modules/node-sass/scripts/install.js:157:1)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path: '/usr/lib/node_modules/node-sass/vendor'
}

> node-sass@4.14.1 postinstall /usr/lib/node_modules/node-sass
> node scripts/build.js

Building: /usr/bin/node /usr/lib/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/usr/bin/node',
gyp verb cli   '/usr/lib/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@14.12.0 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /bin/python2
gyp verb check python version `/bin/python2 -c "import sys; print "2.7.5
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 14.12.0
gyp verb command install [ '14.12.0' ]
gyp verb install input version string "14.12.0"
gyp verb install installing version: 14.12.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 14.12.0
gyp verb ensuring nodedir is created /root/.node-gyp/14.12.0
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/14.12.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/node-sass/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '--node_gyp_internal_noretry', '14.12.0' ]
gyp verb install input version string "14.12.0"
gyp verb install installing version: 14.12.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 14.12.0
gyp verb ensuring nodedir is created /usr/lib/node_modules/node-sass/.node-gyp/14.12.0
gyp WARN install got an error, rolling back install
gyp verb command remove [ '14.12.0' ]
gyp verb remove using node-gyp dir: /usr/lib/node_modules/node-sass/.node-gyp
gyp verb remove removing target version: 14.12.0
gyp verb remove removing development files for version: 14.12.0
gyp WARN install got an error, rolling back install
gyp verb command remove [ '14.12.0' ]
gyp verb remove using node-gyp dir: /usr/lib/node_modules/node-sass/.node-gyp
gyp verb remove removing target version: 14.12.0
gyp verb remove removing development files for version: 14.12.0
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/node-sass/.node-gyp'
gyp ERR! System Linux 3.10.0-1062.el7.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /usr/lib/node_modules/node-sass
gyp ERR! node -v v14.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.14.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.14.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-10-03T00_38_13_611Z-debug.log
```

**Comment by xzyfer** [comment]
npm install --unsafe-perms

**Comment by un-fuf-a-doo** [comment]
Doesn't work global.

```
npm install --unsafe-perms --global node-sass
```

Same error.

**Comment by nschonni** [comment]
https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md#running-with-sudo-or-as-root
