### ISSUE TITLE
Error: dlopen failed: couldn't map "node_modules/node-sass/vendor/android-arm64-83/binding.node" segment 0: Permission denied

### ISSUE THREAD

**Issue by 2byte** [sass/node-sass#2993]
> 

- NPM version: 6.14.7
- Node version (`node -v`): v14.8.0
- Node Process (`node -p process.versions`):{
  node: '14.8.0',
  v8: '8.4.371.19-node.12',
  uv: '1.38.1',
  zlib: '1.2.11',
  brotli: '1.0.7',
  ares: '1.16.1',
  modules: '83',
  nghttp2: '1.41.0',
  napi: '6',
  llhttp: '2.0.4',
  openssl: '1.1.1g',
  cldr: '37.0',
  icu: '67.1',
  tz: '2019c',
  unicode: '13.0'
}
- Node Platform (`node -p process.platform`): android
- Node architecture (`node -p process.arch`): arm64
- node-sass version (`node -p "require('node-sass').info"`):internal/modules/cjs/loader.js:1302
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: dlopen failed: couldn't map "/storage/emulated/0/Android/data/io.spck/files/Journal-informer/node_modules/node-sass/vendor/android-arm64-83/binding.node" segment 0: Permission denied
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1302:18)
    at Module.load (internal/modules/cjs/loader.js:1100:32)
    at Function.Module._load (internal/modules/cjs/loader.js:962:14)
    at Module.require (internal/modules/cjs/loader.js:1140:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at module.exports (/storage/emulated/0/Android/data/io.spck/files/Journal-informer/node_modules/node-sass/lib/binding.js:19:10)
    at Object.<anonymous> (/storage/emulated/0/Android/data/io.spck/files/Journal-informer/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:1251:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
    at Module.load (internal/modules/cjs/loader.js:1100:32)
- npm node-sass versions (`npm ls node-sass`):journal-informer@1.0.0 /storage/emulated/0/Android/data/io.spck/files/Journal-informer
├─┬ gulp-sass@4.1.0
│ └── node-sass@4.14.1  deduped
└── node-sass@4.14.1

In terminal is work `sass f.scss o.css`, rebuild not hepped. Please help

**Comment by 2byte** [comment]
Run 
```
const sass = require('node-sass')

sass.render({
  file: 'theme/main.scss',
  outFile: 'dist/n.css'
}, (err, res) => {
  console.log(err, res)
})
```

Output

```
$ node bsass.js
internal/modules/cjs/loader.js:1302
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: dlopen failed: couldn't map "/storage/emulated/0/Android/data/io.spck/files/Journal-informer/node_modules/node-sass/vendor/android-arm64-83/binding.node" segment 0: Permission denied
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1302:18)
    at Module.load (internal/modules/cjs/loader.js:1100:32)
    at Function.Module._load (internal/modules/cjs/loader.js:962:14)
    at Module.require (internal/modules/cjs/loader.js:1140:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at module.exports (/storage/emulated/0/Android/data/io.spck/files/Journal-informer/node_modules/node-sass/lib/binding.js:19:10)
    at Object.<anonymous> (/storage/emulated/0/Android/data/io.spck/files/Journal-informer/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:1251:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
    at Module.load (internal/modules/cjs/loader.js:1100:32)
```

**Comment by nschonni** [comment]
Neither arm nor android are supported by node-sass
