### ISSUE TITLE
Release with node-gyp 7.1.0

### ISSUE THREAD

**Issue by KannarFr** [sass/node-sass#3009]
Hi, can we expect a quick release of node-sass with the node-gyp v7.1.0?

**Comment by KannarFr** [comment]
Hi @nschonni can you give me more context? I tried to find related issues without success.

**Comment by KannarFr** [comment]
Here is my context, I dropped support of python2.7 & python3.7 for python3.8 and got this. And IIRC node-gyp 7.1.0 supports python 3.8?

```
kannar@pond ~/git/myle/myle-web (git)-[master] % yarn add node-sass                                                                                                                                                                                                                                 [0][23:10:49 - 23/10/2020]
yarn add v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.2: The platform "linux" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > @material-ui/pickers@3.2.10" has unmet peer dependency "@date-io/core@^1.3.6".
warning " > @material-ui/pickers@3.2.10" has unmet peer dependency "prop-types@^15.6.0".
warning " > material-table@1.62.0" has unmet peer dependency "@date-io/core@^1.3.6".
warning "react-scripts > @typescript-eslint/eslint-plugin > tsutils@3.17.1" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
[4/4] Building fresh packages...
[-/4] ⠁ waiting...
[-/4] ⠁ waiting...
[3/4] ⠁ node-sass
error /home/kannar/git/myle/myle-web/node_modules/node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments: 
Directory: /home/kannar/git/myle/myle-web/node_modules/node-sass
Output:
Building: /usr/x86_64-pc-linux-gnu/bin/node /home/kannar/git/myle/myle-web/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/usr/x86_64-pc-linux-gnu/bin/node',
gyp verb cli   '/home/kannar/git/myle/myle-web/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@15.0.0 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/home/kannar/git/myle/myle-web/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/home/kannar/git/myle/myle-web/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/home/kannar/git/myle/myle-web/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /home/kannar/git/myle/myle-web/node_modules/which/which.js:89:16
gyp verb `which` failed     at /home/kannar/git/myle/myle-web/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /home/kannar/git/myle/myle-web/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:183:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/home/kannar/git/myle/myle-web/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/home/kannar/git/myle/myle-web/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/home/kannar/git/myle/myle-web/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /home/kannar/git/myle/myle-web/node_modules/which/which.js:89:16
gyp verb `which` failed     at /home/kannar/git/myle/myle-web/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /home/kannar/git/myle/myle-web/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:183:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python /usr/host/bin/python
gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /usr/host/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (node:child_process:309:12)
gyp ERR! stack     at ChildProcess.emit (node:events:327:20)
gyp ERR! stack     at maybeClose (node:internal/child_process:1048:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:288:5)
gyp ERR! System Linux 5.9.1+
gyp ERR! command "/usr/x86_64-pc-linux-gnu/bin/node" "/home/kannar/git/myle/myle-web/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/kannar/git/myle/myle-web/node_modules/node-sass
gyp ERR! node -v v15.0.0
gyp ERR! node-gyp -v v3.8.0
```

**Comment by nschonni** [comment]
https://github.com/sass/node-sass/blob/6a33e5318b7e89316dab947e8697818e45530907/package.json#L67 
https://github.com/sass/node-sass/pull/2983

**Comment by KannarFr** [comment]
Ok I thought node-gyp bump could be released without any bump related to the node v15. Thanks.
