### ISSUE TITLE
Node-sass still depends on python 2, switch to python 3 instead.

### ISSUE THREAD

**Issue by MaryWeeb** [sass/node-sass#3013]

**Comment by MaryWeeb** [comment]
Why was this closed? It's preventing me from installing node-sass :/

**Comment by devedse** [comment]
Running into the same issue

**Comment by chron0** [comment]
```
gyp info using node-gyp@3.8.0
gyp info using node@12.20.0 | linux | arm64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "/usr/bin/python3.8" in the PATH
gyp verb `which` succeeded /usr/bin/python3.8 /usr/bin/python3.8
gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /usr/bin/python3.8 -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:308:12)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1022:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
gyp ERR! System Linux 4.9.185+
gyp ERR! command "/home/node-red/.nvm/versions/node/v12.20.0/bin/node" "/home/node-red/node-red/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/node-red/node-red/node_modules/node-sass
gyp ERR! node -v v12.20.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
```

**Comment by mayureshhalarnkar** [comment]
I am still facing issue , please help

**Comment by xzyfer** [comment]
Python 3 is used in newer versions of node-sass. Make sure you update to more recent version
