### ISSUE TITLE
undefined symbol in linux-x64-73/binding.node (Node-sass 5.0.0) on postinstall-script

### ISSUE THREAD

**Issue by jasperbosch** [sass/node-sass#3019]
- NPM version (`npm -v`):
6.14.8
- Node version (`node -v`):
v14.15.0
- Node Process (`node -p process.versions`):
{
  node: '14.15.0',
  v8: '8.4.371.19-node.17',
  uv: '1.40.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.16.1',
  modules: '83',
  nghttp2: '1.41.0',
  napi: '7',
  llhttp: '2.1.3',
  openssl: '1.1.1g',
  cldr: '37.0',
  icu: '67.1',
  tz: '2020a',
  unicode: '13.0'
}
- Node Platform (`node -p process.platform`):
linux
- Node architecture (`node -p process.arch`):
x64
- node-sass version (`node -p "require('node-sass').info"`):
node-sass failed to install
- npm node-sass versions (`npm ls node-sass`):
node-sass failed to install

The problem occurs on our Jenkins-server. I have declared a parameter `SASS_BINARY_SITE` that points to a server that supplies the `binding.node`s.
```
[INFO] > node-sass@5.0.0 postinstall /srv/jenkins/workspace/yjs-node-sass-issue/node_modules/node-sass
[INFO] > node scripts/build.js
[INFO] 
[INFO] Binary found at /srv/jenkins/workspace/yjs-node-sass-issue/node_modules/node-sass/vendor/linux-x64-83/binding.node
[INFO] Testing binary
[INFO] Binary has a problem: Error: /srv/jenkins/workspace/yjs-node-sass-issue/node_modules/node-sass/vendor/linux-x64-83/binding.node: undefined symbol: _ZTVNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEE
[INFO]     at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
[INFO]     at Module.load (internal/modules/cjs/loader.js:928:32)
[INFO]     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
[INFO]     at Module.require (internal/modules/cjs/loader.js:952:19)
[INFO]     at require (internal/modules/cjs/helpers.js:88:18)
[INFO]     at module.exports (/srv/jenkins/workspace/yjs-node-sass-issue/node_modules/node-sass/lib/binding.js:19:10)
[INFO]     at Object.<anonymous> (/srv/jenkins/workspace/yjs-node-sass-issue/node_modules/node-sass/lib/index.js:13:35)
[INFO]     at Module._compile (internal/modules/cjs/loader.js:1063:30)
[INFO]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
[INFO]     at Module.load (internal/modules/cjs/loader.js:928:32)
[INFO] Building the binary locally
[INFO] Building: /srv/jenkins/workspace/yjs-node-sass-issue/target/node/node /srv/jenkins/workspace/yjs-node-sass-issue/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
```

**Comment by nschonni** [comment]
1. What linux distro is your build machine running on?
2. Did you copy the bindings from https://github.com/sass/node-sass/releases/tag/v5.0.0 or one of the previous releases?

**Comment by jasperbosch** [comment]
1. RedHat Enterprise Linux 7
2. I copied the v5.0.0 files

**Comment by Connormiha** [comment]
The same problem.

node-sass 5.0.0
node 14.15.0
centos 7

**Comment by nschonni** [comment]
@jasperbosch Thanks, the binary building used to be done on CentOS in the previous release. Since there shouldn't be any binary changes singe the last 4 release, can you try grabbing the right on from the 4.14.1 release just to confirm

**Comment by jasperbosch** [comment]
Using the binding.nodes from 4.14.1 works.

**Comment by nschonni** [comment]
@xzyfer looks like the change in base build for linux did cause issues. What was the previous image you used in v4?

**Comment by xzyfer** [comment]
We've been using CentOS 5/6/7 depending on the node version. I have the
scripts I can run locally later tonight. I'll push up the build dockerfiles
somewhere if you want to try porting them to GitHub workflows

**Comment by nschonni** [comment]
OK, might be able to do something like the Alpine setup https://github.com/sass/node-sass/blob/master/.github/workflows/alpine.yml#L12

**Comment by nschonni** [comment]
Looks like it's probably CentOS 6 for v10, and 7 for v12+ from https://github.com/nodejs/build/blob/8711367be7db175a4e3a6a3367f9e707b585b27f/jenkins/scripts/VersionSelectorScript.groovy#L21

**Comment by xzyfer** [comment]
I've updated the release binaries. Sorry it took a while to get the scripts working with the python 2.7. Please try again.

**Comment by xzyfer** [comment]
Here are the dockerfiles I use. They're a hodge podge of copy-paste and hacks to get things working over the years. Odds are parts of it aren't needed anymore.

### centos 6 (node <= 10)
```
FROM centos:6

### setup ###

RUN true && \
    printf \
    "\
[devtools-32]\n\
name=CentOS 5 devtools 32bit\n\
baseurl=http://people.centos.org/tru/devtools-2/6/i386/RPMS\n\
gpgcheck=0\n\
    " > \
    /etc/yum.repos.d/devtools32.repo && \
    printf \
    "\
[devtools-64]\n\
name=CentOS 5 devtools 64bit\n\
baseurl=http://people.centos.org/tru/devtools-2/6/x86_64/RPMS\n\
gpgcheck=0\n\
    " > \
    /etc/yum.repos.d/devtools64.repo

RUN yum install -y centos-release-scl

RUN yum install -y \
    curl wget make file which python27 \
    # curl wget make file which python26 \
    devtoolset-2-{gcc,gcc.i686,gcc-c++,gcc-c++.i686,binutils,binutils.i686,libstdc++-devel,libstdc++-devel.i686} \
    glibc-{devel,devel.i686} && \
    yum clean all

### put cc/gcc in PATH ###

ENV PATH /opt/rh/devtoolset-2/root/usr/bin:$PATH

### install nvm ###

RUN mkdir ~/.nvm && \
    wget --no-check-certificate -O ~/.nvm/nvm.sh https://raw.githubusercontent.com/xzyfer/nvm/master/nvm.sh

### make nvm work for iojs ###

RUN mkdir -p ~/.nvm/versions/{node,io.js}

### make nvm command avialable ###

ENV BASH_ENV="~/.bashrc"
RUN echo 'export NVM_DIR="$HOME/.nvm"' >> ~/.bashrc
RUN echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> ~/.bashrc

### allow mounting of node-sass ###

VOLUME /node-sass

### the main event

RUN source ~/.nvm/nvm.sh && nvm install 10
```

```sh
$ docker build --tag xzyfer/node-sass-10:latest - < Dockerfile
$ docker run -v ~/node-sass:/node-sass -w /node-sass -it --rm xzyfer/node-sass-10:latest scl enable python27 "nvm run stable ./scripts/build.js -f"
```

### centos 7 (node > 10)

```
FROM centos:7

### setup ###
RUN yum install -y centos-release-scl

RUN yum install -y \
    curl wget make file which \
    devtoolset-7-{gcc,gcc.i686,gcc-c++,gcc-c++.i686,binutils,binutils.i686,libstdc++-devel,libstdc++-devel.i686} \
    yum clean all

### put cc/gcc in PATH ###

ENV PATH /opt/rh/devtoolset-2/root/usr/bin:$PATH
# ENV PATH /opt/rh/devtoolset-6/root/usr/bin:$PATH

### install nvm ###

RUN mkdir ~/.nvm && \
    wget --no-check-certificate -O ~/.nvm/nvm.sh https://raw.githubusercontent.com/xzyfer/nvm/master/nvm.sh

### make nvm work for iojs ###

RUN mkdir -p ~/.nvm/versions/{node,io.js}

### make nvm command avialable ###

ENV BASH_ENV="~/.bashrc"
RUN echo 'export NVM_DIR="$HOME/.nvm"' >> ~/.bashrc
RUN echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> ~/.bashrc

### allow mounting of node-sass ###

VOLUME /node-sass

### the main event

RUN source ~/.nvm/nvm.sh && nvm install 14
```

```sh
$ docker build --tag xzyfer/node-sass-14:latest - < Dockerfile
$ docker run -v ~/node-sass:/node-sass -w /node-sass -it --rm xzyfer/node-sass-14:latest scl enable devtoolset-7 -- nvm run stable ./scripts/build.js -f
```

**Comment by nschonni** [comment]
I've pulled the discussion around moving back to CentOS for the release builds to a separate issue. Since the bindings on the release have been updated, I'm going to close this issue
