### ISSUE TITLE
Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (83)

### ISSUE THREAD

**Issue by jayjupdhig** [sass/node-sass#3025]
i try to build an older node / angular / sass project with nodeJS 14 and it's current npm version.

get that message:

```
ERROR in ./node_modules/ionicons/scss/ionicons.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (83)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.9.3
```

Why and what's the solution?

Thx for feedback.

**Comment by nschonni** [comment]
https://github.com/sass/node-sass#node-version-support-policy

**Comment by jayjupdhig** [comment]
```
npm rebuild node-sass
```

Doesn't help: https://medium.com/@proustibat/how-to-fix-error-node-sass-does-not-yet-support-your-current-environment-os-x-64-bit-with-c1b3298e4af0

Messsages:

```
npm rebuild node-sass

> node-sass@4.9.3 install C:\Users\xxx\Documents\PF_IPA_Ivo_Angular\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.9.3/win32-x64-83_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.9.3/win32-x64-83_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.9.3 postinstall C:\Users\xxx\Documents\PF_IPA_Ivo_Angular\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe C:\Users\xxx\Documents\PF_IPA_Ivo_Angular\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\xxx\\Documents\\PF_IPA_Ivo_Angular\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@14.15.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\xxx\Documents\PF_IPA_Ivo_Angular\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\xxx\Documents\PF_IPA_Ivo_Angular\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\xxx\Documents\PF_IPA_Ivo_Angular\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\xxx\Documents\PF_IPA_Ivo_Angular\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\xxx\Documents\PF_IPA_Ivo_Angular\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\xxx\Documents\PF_IPA_Ivo_Angular\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:183:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\xxx\Documents\PF_IPA_Ivo_Angular\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\xxx\Documents\PF_IPA_Ivo_Angular\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\xxx\Documents\PF_IPA_Ivo_Angular\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\xxx\Documents\PF_IPA_Ivo_Angular\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\xxx\Documents\PF_IPA_Ivo_Angular\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\xxx\Documents\PF_IPA_Ivo_Angular\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:183:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Python39\python.EXE
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Python39\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:308:12)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\xxx\\Documents\\PF_IPA_Ivo_Angular\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\xxx\Documents\PF_IPA_Ivo_Angular\node_modules\node-sass
gyp ERR! node -v v14.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.9.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.9.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxx\AppData\Roaming\npm-cache\_logs\2020-11-09T15_53_16_613Z-debug.log
```

**Comment by jayjupdhig** [comment]
@nschonni 

Where do i need to open an issue regarding to a solution of my problem?

- Angular Github site?
- NPM Github site?


...due to my experiences, every components developer says: "No, it's not your responsibility, it's the respnsibility of ..."

Thank you for your feedback! ;-)

**Comment by nschonni** [comment]
Upgrade your node-sass or downgrade your node version

**Comment by jayjupdhig** [comment]
ok thx
