### ISSUE TITLE
Binary has a problem: Error: Module did not self-register.

### ISSUE THREAD

**Issue by soorajit1994** [sass/node-sass#3029]
Node version=12.18.0
npm version: 6.14.8
windows10

================Logs======================

Binary saved to node_modules\node-sass\vendor\win32-x64-57\binding.node
Caching binary to npm-cache\node-sass\4.7.2\win32-x64-57_binding.node

node-sass@4.7.2 postinstall node_modules\node-sass
node scripts/build.js

Binary found at node_modules\node-sass\vendor\win32-x64-57\binding.node
Testing binary
Binary has a problem: Error: Module did not self-register.
at Object.Module._extensions..node (module.js:672:18)
at Module.load (module.js:556:32)
at tryModuleLoad (module.js:499:12)
at Function.Module._load (module.js:491:3)
at Module.require (module.js:587:17)
at require (internal/module.js:11:18)
at module.exports (node_modules\node-sass\lib\binding.js:19:10)
at Object. (node_modules\node-sass\lib\index.js:14:35)
at Module._compile (module.js:643:30)
at Object.Module._extensions..js (module.js:654:10)
Building the binary locally

**Comment by nschonni** [comment]
https://github.com/sass/node-sass#node-version-support-policy
