### ISSUE TITLE
in-range breaking change for ^4

### ISSUE THREAD

**Issue by trusktr** [sass/node-sass#3038]
- NPM version (`npm -v`): 6.14.4
- Node version (`node -v`): 14.15.1
- Node Process (`node -p process.versions`):
```
{
  node: '14.15.1',
  v8: '8.4.371.19-node.17',
  uv: '1.40.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.16.1',
  modules: '83',
  nghttp2: '1.41.0',
  napi: '7',
  llhttp: '2.1.3',
  openssl: '1.1.1g',
  cldr: '37.0',
  icu: '67.1',
  tz: '2020a',
  unicode: '13.0'
}
```
- Node Platform (`node -p process.platform`): Linux
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`): fresh install with `^4.12.0` in my package.json
- npm node-sass versions (`npm ls node-sass`):

I blew away node_modules yesterday and started getting errors like this:

<details><summary>error</summary>

```
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Error: ENOENT: no such file or directory, scandir '/home/trusktr/src/lume+lume/packages/live-code/node_modules/node-sass/vendor'
    at Object.readdirSync (fs.js:1021:3)
    at Object.getInstalledBinaries (/home/trusktr/src/lume+lume/packages/live-code/node_modules/node-sass/lib/extensions.js:133:13)
    at foundBinariesList (/home/trusktr/src/lume+lume/packages/live-code/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/home/trusktr/src/lume+lume/packages/live-code/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/home/trusktr/src/lume+lume/packages/live-code/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/home/trusktr/src/lume+lume/packages/live-code/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/home/trusktr/src/lume+lume/packages/live-code/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at getDefaultSassImpl (/home/trusktr/src/lume+lume/packages/live-code/node_modules/sass-loader/dist/index.js:198:10)
    at Object.loader (/home/trusktr/src/lume+lume/packages/live-code/node_modules/sass-loader/dist/index.js:80:29)
    at /home/trusktr/src/lume+lume/packages/live-code/node_modules/webpack/lib/NormalModule.js:316:20
    at /home/trusktr/src/lume+lume/packages/live-code/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/trusktr/src/lume+lume/packages/live-code/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at runSyncOrAsync (/home/trusktr/src/lume+lume/packages/live-code/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
    at iterateNormalLoaders (/home/trusktr/src/lume+lume/packages/live-code/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at /home/trusktr/src/lume+lume/packages/live-code/node_modules/loader-runner/lib/LoaderRunner.js:186:6
    at context.callback (/home/trusktr/src/lume+lume/packages/live-code/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /home/trusktr/src/lume+lume/packages/live-code/node_modules/cache-loader/dist/index.js:171:7
    at /home/trusktr/src/lume+lume/packages/live-code/node_modules/neo-async/async.js:2830:7
    at done (/home/trusktr/src/lume+lume/packages/live-code/node_modules/neo-async/async.js:2865:11)
    at /home/trusktr/src/lume+lume/packages/live-code/node_modules/neo-async/async.js:2818:7
    at /home/trusktr/src/lume+lume/packages/live-code/node_modules/cache-loader/dist/index.js:160:9
    at /home/trusktr/src/lume+lume/packages/live-code/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:85:15
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
```

</details>

To fix the issue, I pinned `node-sass` in my package.json by writing `4.12.0` instead of `^4.12.0`.

I also pinned sass-loader to 7.2.0, but I don't think that is related to the issue (always a chance though).

**Comment by trusktr** [comment]
Weird, I have some new errors after pinning now. Really not sure why all of a sudden I have errors, but now it complains that my platform is not supported (always worked before).

Oh well, out with the old, in with the new. I should just move to v5 or something else.
