### ISSUE TITLE
Failing on PPC64LE, Segmentation fault

### ISSUE THREAD

**Issue by ezeeyahoo** [sass/node-sass#3081]
I have got build successful but runtime segfault 

- NPM version (`npm -v`): 6.14.4
- Node version (`node -v`): 10.21.0
- Node Process (`node -p process.versions`):
```
{ http_parser: '2.9.3',
  node: '10.21.0',
  v8: '6.8.275.32-node.56',
  uv: '1.34.2',
  zlib: '1.2.11',
  brotli: '1.0.7',
  ares: '1.15.0',
  modules: '64',
  nghttp2: '1.41.0',
  napi: '6',
  openssl: '1.1.1c',
  icu: '64.2',
  unicode: '12.1',
  cldr: '35.1',
  tz: '2019c' }
```
- Node Platform (`node -p process.platform`):linux
- Node architecture (`node -p process.arch`): ppc64
- node-sass version (`node -p "require('node-sass').info"`):
```
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at [eval]:1:1
    at Script.runInThisContext (vm.js:122:20)
    at Object.runInThisContext (vm.js:329:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at evalScript (internal/bootstrap/node.js:590:27)
```
- npm node-sass versions (`npm ls node-sass`):
```
node-sass@5.0.0 /root/node-sass
└── (empty)
```

**Comment by nschonni** [comment]
We don't support PPC

**Comment by saper** [comment]
@ezeeyahoo If you run on a platform we do not support normally compilation process with gyp will kick in. You might want to check why it fails. It should have a pretty modern C++ compiler available, among others.
