### ISSUE TITLE
Error: Node Sass does not yet support your current environment: Linux/musl 64-bit with Unsupported runtime (88)

### ISSUE THREAD

**Issue by AskAlice** [sass/node-sass#3087]
using docker
`FROM node:15-alpine as build`

- NPM version (`npm -v`): 7.7.6
- Node version (`node -v`): v15.14.0
- Node Process (`node -p process.versions`):
  - ```json
{
  node: '15.14.0',
  v8: '8.6.395.17-node.28',
  uv: '1.41.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.17.1',
  modules: '88',
  nghttp2: '1.42.0',
  napi: '8',
  llhttp: '2.1.3',
  openssl: '1.1.1k+quic',
  cldr: '38.1',
  icu: '68.2',
  tz: '2020d',
  unicode: '13.0',
  ngtcp2: '0.1.0-DEV',
  nghttp3: '0.1.0-DEV'
}```
- Node Platform (`node -p process.platform`): linux
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`): ``` /app/node_modules/node-sass/lib/binding.js:13
      throw new Error(errors.unsupportedEnvironment());
      ^

Error: Node Sass does not yet support your current environment: Linux/musl 64-bit with Unsupported runtime (88)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.14.1
    at module.exports (/app/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/app/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at [eval]:1:1
    at Script.runInThisContext (node:vm:131:12)
The command '/bin/sh -c node -p "require('node-sass').info"' returned a non-zero code: 1
```
- npm node-sass versions (`npm ls node-sass`): ```
my-package-name@0.1.2 /app
`-- node-sass@4.14.1
```

react-scripts build
```Error: Node Sass does not yet support your current environment: Linux/musl 64-bit with Unsupported runtime (88)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.14.1```

**Comment by nschonni** [comment]
https://github.com/sass/node-sass#node-version-support-policy
