### ISSUE TITLE
error: no matching function for call to ‘v8::Value::ToBoolean(v8::Local<v8::Context>)’

### ISSUE THREAD

**Issue by itsluispatricio** [sass/node-sass#3089]
- NPM version (`npm -v`): 6.14.12
- Node version (`node -v`): v14.16.1
- Node Process (`node -p process.versions`): {
  node: '14.16.1',
  v8: '8.4.371.19-node.18',
  uv: '1.40.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.16.1',
  modules: '83',
  nghttp2: '1.41.0',
  napi: '7',
  llhttp: '2.1.3',
  openssl: '1.1.1k',
  cldr: '37.0',
  icu: '67.1',
  tz: '2020a',
  unicode: '13.0'
}
- Node Platform (`node -p process.platform`): linux
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`):
node-sass	5.0.0	(Wrapper)	[JavaScript]
libsass  	3.5.5	(Sass Compiler)	[C/C++]
- npm node-sass versions (`npm ls node-sass`): node-sass@5.0.0

When I tried to install node-sass using `npm install node-sass` I got this error:

```
In file included from ../../../../../nan/nan_converters.h:67:0,
                 from ../../../../../nan/nan.h:202,
                 from ../src/binding.cpp:1:
../../../../../nan/nan_converters_43_inl.h: In static member function ‘static Nan::imp::ToFactoryBase<v8::Boolean>::return_t Nan::imp::ToFactory<v8::Boolean>::convert(v8::Local<v8::Value>)’:
../../../../../nan/nan_converters_43_inl.h:18:51: error: no matching function for call to ‘v8::Value::ToBoolean(v8::Local<v8::Context>)’
       val->To ## TYPE(isolate->GetCurrentContext())                            \
                                                   ^
../../../../../nan/nan_converters_43_inl.h:22:1: note: in expansion of macro ‘X’
 X(Boolean)
 ^
In file included from /home/luispatr/.node-gyp/14.16.1/include/node/node.h:67:0,
                 from ../../../../../nan/nan.h:51,
                 from ../src/binding.cpp:1:
/home/luispatr/.node-gyp/14.16.1/include/node/v8.h:2848:18: note: candidate: v8::Local<v8::Boolean> v8::Value::ToBoolean(v8::Isolate*) const
   Local<Boolean> ToBoolean(Isolate* isolate) const;
                  ^~~~~~~~~
/home/luispatr/.node-gyp/14.16.1/include/node/v8.h:2848:18: note:   no known conversion for argument 1 from ‘v8::Local<v8::Context>’ to ‘v8::Isolate*’
In file included from ../../../../../nan/nan_converters.h:67:0,
                 from ../../../../../nan/nan.h:202,
                 from ../src/binding.cpp:1:
../../../../../nan/nan_converters_43_inl.h: In static member function ‘static Nan::imp::ValueFactoryBase<bool>::return_t Nan::imp::ToFactory<bool>::convert(v8::Local<v8::Value>)’:
../../../../../nan/nan_converters_43_inl.h:37:57: error: no matching function for call to ‘v8::Value::BooleanValue(v8::Local<v8::Context>)’
   return val->NAME ## Value(isolate->GetCurrentContext());                     \
                                                         ^
../../../../../nan/nan_converters_43_inl.h:40:1: note: in expansion of macro ‘X’
 X(bool, Boolean)
 ^
In file included from /home/luispatr/.node-gyp/14.16.1/include/node/node.h:67:0,
                 from ../../../../../nan/nan.h:51,
                 from ../src/binding.cpp:1:
/home/luispatr/.node-gyp/14.16.1/include/node/v8.h:2858:8: note: candidate: bool v8::Value::BooleanValue(v8::Isolate*) const
   bool BooleanValue(Isolate* isolate) const;
        ^~~~~~~~~~~~
/home/luispatr/.node-gyp/14.16.1/include/node/v8.h:2858:8: note:   no known conversion for argument 1 from ‘v8::Local<v8::Context>’ to ‘v8::Isolate*’
In file included from ../../../../../nan/nan_new.h:189:0,
                 from ../../../../../nan/nan.h:203,
                 from ../src/binding.cpp:1:
../../../../../nan/nan_implementation_12_inl.h: In static member function ‘static Nan::imp::FactoryBase<v8::Function>::return_t Nan::imp::Factory<v8::Function>::New(Nan::FunctionCallback, v8::Local<v8::Value>)’:
../../../../../nan/nan_implementation_12_inl.h:105:32: error: no matching function for call to ‘v8::Function::New(v8::Isolate*&, void (&)(const v8::FunctionCallbackInfo<v8::Value>&), v8::Local<v8::Object>&)’
                           , obj));
                                ^
In file included from /home/luispatr/.node-gyp/14.16.1/include/node/node.h:67:0,
                 from ../../../../../nan/nan.h:51,
                 from ../src/binding.cpp:1:
/home/luispatr/.node-gyp/14.16.1/include/node/v8.h:4445:31: note: candidate: static v8::MaybeLocal<v8::Function> v8::Function::New(v8::Local<v8::Context>, v8::FunctionCallback, v8::Local<v8::Value>, int, v8::ConstructorBehavior, v8::SideEffectType)
   static MaybeLocal<Function> New(
                               ^~~
/home/luispatr/.node-gyp/14.16.1/include/node/v8.h:4445:31: note:   no known conversion for argument 1 from ‘v8::Isolate*’ to ‘v8::Local<v8::Context>’
In file included from ../../../../../nan/nan_new.h:189:0,
                 from ../../../../../nan/nan.h:203,
                 from ../src/binding.cpp:1:
../../../../../nan/nan_implementation_12_inl.h: In static member function ‘static Nan::imp::FactoryBase<v8::StringObject>::return_t Nan::imp::Factory<v8::StringObject>::New(v8::Local<v8::String>)’:
../../../../../nan/nan_implementation_12_inl.h:337:37: error: no matching function for call to ‘v8::StringObject::New(v8::Local<v8::String>&)’
   return v8::StringObject::New(value).As<v8::StringObject>();
                                     ^
In file included from /home/luispatr/.node-gyp/14.16.1/include/node/node.h:67:0,
                 from ../../../../../nan/nan.h:51,
                 from ../src/binding.cpp:1:
/home/luispatr/.node-gyp/14.16.1/include/node/v8.h:5854:23: note: candidate: static v8::Local<v8::Value> v8::StringObject::New(v8::Isolate*, v8::Local<v8::String>)
   static Local<Value> New(Isolate* isolate, Local<String> value);
                       ^~~
/home/luispatr/.node-gyp/14.16.1/include/node/v8.h:5854:23: note:   candidate expects 2 arguments, 1 provided
In file included from ../../../../../nan/nan_new.h:189:0,
                 from ../../../../../nan/nan.h:203,
                 from ../src/binding.cpp:1:
../../../../../nan/nan_implementation_12_inl.h:337:58: error: expected primary-expression before ‘>’ token
   return v8::StringObject::New(value).As<v8::StringObject>();
                                                          ^
../../../../../nan/nan_implementation_12_inl.h:337:60: error: expected primary-expression before ‘)’ token
   return v8::StringObject::New(value).As<v8::StringObject>();
                                                            ^
In file included from ../src/binding.cpp:1:0:
../../../../../nan/nan.h: In constructor ‘Nan::Utf8String::Utf8String(v8::Local<v8::Value>)’:
../../../../../nan/nan.h:1034:53: error: no matching function for call to ‘v8::Value::ToString()’
       v8::Local<v8::String> string = from->ToString();
                                                     ^
In file included from /home/luispatr/.node-gyp/14.16.1/include/node/node.h:67:0,
                 from ../../../../../nan/nan.h:51,
                 from ../src/binding.cpp:1:
/home/luispatr/.node-gyp/14.16.1/include/node/v8.h:2810:44: note: candidate: v8::MaybeLocal<v8::String> v8::Value::ToString(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT MaybeLocal<String> ToString(
                                            ^~~~~~~~
/home/luispatr/.node-gyp/14.16.1/include/node/v8.h:2810:44: note:   candidate expects 1 argument, 0 provided
In file included from ../src/binding.cpp:1:0:
../../../../../nan/nan.h:1044:74: error: no matching function for call to ‘v8::String::WriteUtf8(char*&, int, int, const int&)’
         length_ = string->WriteUtf8(str_, static_cast<int>(len), 0, flags);
                                                                          ^
In file included from /home/luispatr/.node-gyp/14.16.1/include/node/node.h:67:0,
                 from ../../../../../nan/nan.h:51,
                 from ../src/binding.cpp:1:
/home/luispatr/.node-gyp/14.16.1/include/node/v8.h:3037:7: note: candidate: int v8::String::WriteUtf8(v8::Isolate*, char*, int, int*, int) const
   int WriteUtf8(Isolate* isolate, char* buffer, int length = -1,
       ^~~~~~~~~
/home/luispatr/.node-gyp/14.16.1/include/node/v8.h:3037:7: note:   no known conversion for argument 1 from ‘char*’ to ‘v8::Isolate*’
In file included from ../src/binding.cpp:1:0:
../../../../../nan/nan.h: In member function ‘void Nan::AsyncWorker::SaveToPersistent(const char*, const v8::Local<v8::Value>&)’:
../../../../../nan/nan.h:1818:64: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, const v8::Local<v8::Value>&)’
     New(persistentHandle)->Set(New(key).ToLocalChecked(), value);
                                                                ^
In file included from /home/luispatr/.node-gyp/14.16.1/include/node/node.h:67:0,
                 from ../../../../../nan/nan.h:51,
                 from ../src/binding.cpp:1:
/home/luispatr/.node-gyp/14.16.1/include/node/v8.h:3670:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                     ^~~
/home/luispatr/.node-gyp/14.16.1/include/node/v8.h:3670:37: note:   candidate expects 3 arguments, 2 provided
/home/luispatr/.node-gyp/14.16.1/include/node/v8.h:3673:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                     ^~~
/home/luispatr/.node-gyp/14.16.1/include/node/v8.h:3673:37: note:   candidate expects 3 arguments, 2 provided
In file included from ../src/binding.cpp:1:0:
../../../../../nan/nan.h: In member function ‘void Nan::AsyncWorker::SaveToPersistent(const v8::Local<v8::String>&, const v8::Local<v8::Value>&)’:
../../../../../nan/nan.h:1824:42: error: no matching function for call to ‘v8::Object::Set(const v8::Local<v8::String>&, const v8::Local<v8::Value>&)’
     New(persistentHandle)->Set(key, value);
                                          ^
In file included from /home/luispatr/.node-gyp/14.16.1/include/node/node.h:67:0,
                 from ../../../../../nan/nan.h:51,
                 from ../src/binding.cpp:1:
/home/luispatr/.node-gyp/14.16.1/include/node/v8.h:3670:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                     ^~~
/home/luispatr/.node-gyp/14.16.1/include/node/v8.h:3670:37: note:   candidate expects 3 arguments, 2 provided
/home/luispatr/.node-gyp/14.16.1/include/node/v8.h:3673:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                     ^~~
/home/luispatr/.node-gyp/14.16.1/include/node/v8.h:3673:37: note:   candidate expects 3 arguments, 2 provided
In file included from ../src/binding.cpp:1:0:
../../../../../nan/nan.h: In member function ‘void Nan::AsyncWorker::SaveToPersistent(uint32_t, const v8::Local<v8::Value>&)’:
../../../../../nan/nan.h:1830:44: error: no matching function for call to ‘v8::Object::Set(uint32_t&, const v8::Local<v8::Value>&)’
     New(persistentHandle)->Set(index, value);
                                            ^
In file included from /home/luispatr/.node-gyp/14.16.1/include/node/node.h:67:0,
                 from ../../../../../nan/nan.h:51,
                 from ../src/binding.cpp:1:
/home/luispatr/.node-gyp/14.16.1/include/node/v8.h:3670:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                     ^~~
/home/luispatr/.node-gyp/14.16.1/include/node/v8.h:3670:37: note:   candidate expects 3 arguments, 2 provided
/home/luispatr/.node-gyp/14.16.1/include/node/v8.h:3673:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                     ^~~
/home/luispatr/.node-gyp/14.16.1/include/node/v8.h:3673:37: note:   candidate expects 3 arguments, 2 provided
In file included from ../src/binding.cpp:1:0:
../../../../../nan/nan.h: In member function ‘v8::Local<v8::Value> Nan::AsyncWorker::GetFromPersistent(const char*) const’:
../../../../../nan/nan.h:1836:61: error: no matching function for call to ‘v8::Object::Get(v8::Local<v8::String>)’
         New(persistentHandle)->Get(New(key).ToLocalChecked()));
                                                             ^
In file included from /home/luispatr/.node-gyp/14.16.1/include/node/node.h:67:0,
                 from ../../../../../nan/nan.h:51,
                 from ../src/binding.cpp:1:
/home/luispatr/.node-gyp/14.16.1/include/node/v8.h:3717:43: note: candidate: v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                           ^~~
/home/luispatr/.node-gyp/14.16.1/include/node/v8.h:3717:43: note:   candidate expects 2 arguments, 1 provided
/home/luispatr/.node-gyp/14.16.1/include/node/v8.h:3720:43: note: candidate: v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, uint32_t)
   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                           ^~~
/home/luispatr/.node-gyp/14.16.1/include/node/v8.h:3720:43: note:   candidate expects 2 arguments, 1 provided
In file included from ../src/binding.cpp:1:0:
../../../../../nan/nan.h: In member function ‘v8::Local<v8::Value> Nan::AsyncWorker::GetFromPersistent(const v8::Local<v8::String>&) const’:
../../../../../nan/nan.h:1842:55: error: no matching function for call to ‘v8::Object::Get(const v8::Local<v8::String>&)’
     return scope.Escape(New(persistentHandle)->Get(key));
                                                       ^
In file included from /home/luispatr/.node-gyp/14.16.1/include/node/node.h:67:0,
                 from ../../../../../nan/nan.h:51,
                 from ../src/binding.cpp:1:
/home/luispatr/.node-gyp/14.16.1/include/node/v8.h:3717:43: note: candidate: v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                           ^~~
/home/luispatr/.node-gyp/14.16.1/include/node/v8.h:3717:43: note:   candidate expects 2 arguments, 1 provided
/home/luispatr/.node-gyp/14.16.1/include/node/v8.h:3720:43: note: candidate: v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, uint32_t)
   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                           ^~~
/home/luispatr/.node-gyp/14.16.1/include/node/v8.h:3720:43: note:   candidate expects 2 arguments, 1 provided
In file included from ../src/binding.cpp:1:0:
../../../../../nan/nan.h: In member function ‘v8::Local<v8::Value> Nan::AsyncWorker::GetFromPersistent(uint32_t) const’:
../../../../../nan/nan.h:1847:57: error: no matching function for call to ‘v8::Object::Get(uint32_t&)’
     return scope.Escape(New(persistentHandle)->Get(index));
                                                         ^
In file included from /home/luispatr/.node-gyp/14.16.1/include/node/node.h:67:0,
                 from ../../../../../nan/nan.h:51,
                 from ../src/binding.cpp:1:
/home/luispatr/.node-gyp/14.16.1/include/node/v8.h:3717:43: note: candidate: v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                           ^~~
/home/luispatr/.node-gyp/14.16.1/include/node/v8.h:3717:43: note:   candidate expects 2 arguments, 1 provided
/home/luispatr/.node-gyp/14.16.1/include/node/v8.h:3720:43: note: candidate: v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, uint32_t)
   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                           ^~~
/home/luispatr/.node-gyp/14.16.1/include/node/v8.h:3720:43: note:   candidate expects 2 arguments, 1 provided
In file included from /usr/include/c++/7/cassert:44:0,
                 from /home/luispatr/.node-gyp/14.16.1/include/node/node_object_wrap.h:26,
                 from ../../../../../nan/nan.h:53,
                 from ../src/binding.cpp:1:
../../../../../nan/nan_object_wrap.h: In destructor ‘virtual Nan::ObjectWrap::~ObjectWrap()’:
../../../../../nan/nan_object_wrap.h:24:25: error: ‘class Nan::Persistent<v8::Object>’ has no member named ‘IsNearDeath’
     assert(persistent().IsNearDeath());
                         ^
In file included from ../../../../../nan/nan.h:2657:0,
                 from ../src/binding.cpp:1:
../../../../../nan/nan_object_wrap.h: In member function ‘void Nan::ObjectWrap::MakeWeak()’:
../../../../../nan/nan_object_wrap.h:67:18: error: ‘class Nan::Persistent<v8::Object>’ has no member named ‘MarkIndependent’
     persistent().MarkIndependent();
                  ^~~~~~~~~~~~~~~
In file included from /usr/include/c++/7/cassert:44:0,
                 from /home/luispatr/.node-gyp/14.16.1/include/node/node_object_wrap.h:26,
                 from ../../../../../nan/nan.h:53,
                 from ../src/binding.cpp:1:
../../../../../nan/nan_object_wrap.h: In static member function ‘static void Nan::ObjectWrap::WeakCallback(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’:
../../../../../nan/nan_object_wrap.h:124:26: error: ‘class Nan::Persistent<v8::Object>’ has no member named ‘IsNearDeath’
     assert(wrap->handle_.IsNearDeath());
                          ^
In file included from ../src/binding.cpp:1:0:
../../../../../nan/nan.h: In instantiation of ‘void Nan::imp::SetMethodAux(T, v8::Local<v8::String>, v8::Local<v8::FunctionTemplate>, ...) [with T = v8::Local<v8::Object>]’:
../../../../../nan/nan.h:2353:20:   required from ‘void Nan::SetMethod(HandleType<T>, const char*, Nan::FunctionCallback) [with T = v8::Object; HandleType = v8::Local; Nan::FunctionCallback = void (*)(const Nan::FunctionCallbackInfo<v8::Value>&)]’
../src/binding.cpp:350:42:   required from here
../../../../../nan/nan.h:2337:3: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>&, v8::Local<v8::Function>)’
   recv->Set(name, GetFunction(tpl).ToLocalChecked());
   ^~~~
In file included from /home/luispatr/.node-gyp/14.16.1/include/node/node.h:67:0,
                 from ../../../../../nan/nan.h:51,
                 from ../src/binding.cpp:1:
/home/luispatr/.node-gyp/14.16.1/include/node/v8.h:3670:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                     ^~~
/home/luispatr/.node-gyp/14.16.1/include/node/v8.h:3670:37: note:   candidate expects 3 arguments, 2 provided
/home/luispatr/.node-gyp/14.16.1/include/node/v8.h:3673:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                     ^~~
/home/luispatr/.node-gyp/14.16.1/include/node/v8.h:3673:37: note:   candidate expects 3 arguments, 2 provided
binding.target.mk:131: recipe for target 'Release/obj.target/binding/src/binding.o' failed
make: *** [Release/obj.target/binding/src/binding.o] Error 1
make: Leaving directory '/home/luispatr/Documents/airsonic-ui/node_modules/@angular-devkit/build-angular/node_modules/node-sass/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/luispatr/Documents/airsonic-ui/node_modules/@angular-devkit/build-angular/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 5.4.0-72-generic
gyp ERR! command "/usr/bin/node" "/home/luispatr/Documents/airsonic-ui/node_modules/@angular-devkit/build-angular/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/luispatr/Documents/airsonic-ui/node_modules/@angular-devkit/build-angular/node_modules/node-sass
gyp ERR! node -v v14.16.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
```

**Comment by alpwe** [comment]
Hello!
Try this, after that my Gulp is run.  
npm uninstall node-sass
npm cache clear --force

Maybe this help you.

**Comment by saper** [comment]
Which linux distribution is this?

**Comment by saper** [comment]
Can't reproduce with:

```
[saper@fedora0 test]$ npm -v
6.14.12
[saper@fedora0 test]$ node -v
v14.16.1
[saper@fedora0 test]$ node -p process.versions
{
  node: '14.16.1',
  v8: '8.4.371.19-node.18',
  uv: '1.40.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.16.1',
  modules: '83',
  nghttp2: '1.43.0',
  napi: '7',
  llhttp: '2.1.3',
  openssl: '1.1.1k',
  cldr: '37.0',
  icu: '67.1',
  tz: '2019c',
  unicode: '13.0'
}
[saper@fedora0 test]$ uname -r
5.11.14-200.fc33.x86_64
```

Freshly updated Fedora 33

```
[saper@fedora0 test]$ npm install node-sass@5.0.0
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported

> node-sass@5.0.0 install /home/saper/space/test/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v5.0.0/linux-x64-83_binding.node
Download complete..] - :
Binary saved to /home/saper/space/test/node_modules/node-sass/vendor/linux-x64-83/binding.node
Caching binary to /home/saper/.npm/node-sass/5.0.0/linux-x64-83_binding.node

> node-sass@5.0.0 postinstall /home/saper/space/test/node_modules/node-sass
> node scripts/build.js

Binary found at /home/saper/space/test/node_modules/node-sass/vendor/linux-x64-83/binding.node
Testing binary
Binary is fine
npm WARN saveError ENOENT: no such file or directory, open '/home/saper/space/test/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/home/saper/space/test/package.json'
npm WARN test No description
npm WARN test No repository field.
npm WARN test No README data
npm WARN test No license field.

+ node-sass@5.0.0
added 195 packages from 144 contributors and audited 195 packages in 25.593s

7 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

```

**Comment by atstockland** [comment]
Upgrading from node 15.14.0 to 16.0.0 exposed this error for me also.  To confirm, I tried creating a brand new rails app and it also fails with:

[1/4] 🔍  Resolving packages...
warning @rails/webpacker > node-sass > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning @rails/webpacker > node-sass > node-gyp > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning @rails/webpacker > node-sass > request > har-validator@5.1.5: this library is no longer supported
warning @rails/webpacker > webpack > watchpack > watchpack-chokidar2 > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning @rails/webpacker > webpack > watchpack > watchpack-chokidar2 > chokidar > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
warning @rails/webpacker > webpack > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning @rails/webpacker > webpack > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
[-/3] ⠁ waiting...
[-/3] ⠁ waiting...
error /Users/drama/Sites/test_app/node_modules/node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: /Users/drama/Sites/test_app/node_modules/node-sass
Output:
Building: /usr/local/Cellar/node/16.0.0/bin/node /Users/drama/Sites/test_app/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok

**Comment by nschonni** [comment]
@atstockland Node 16 is currently supported, and is being tracked in https://github.com/sass/node-sass/issues/3077

**Comment by digitalhuman** [comment]
Having the same error on

Linux *** 3.10.0-1160.53.1.el7.x86_64 #1 SMP Fri Jan 14 13:59:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux .
node -v
v14.20.0
npm -v
6.14.17

CentOS Linux release 7.9.2009 (Core)
 cc -v
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC)
