### ISSUE TITLE
[Unsupported] Installing node-sass 4.14.1 on Node 16

### ISSUE THREAD

**Issue by Mirocow** [sass/node-sass#3105]
```
1 error generated.
make: *** [Release/obj.target/binding/src/binding.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/mirocow/Projects/Dockers/MomsLab/momslab/modules/sonix/backend/assets/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (node:events:365:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/usr/local/Cellar/node/16.1.0/bin/node" "/Users/mirocow/Projects/Dockers/MomsLab/momslab/modules/sonix/backend/assets/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/mirocow/Projects/Dockers/MomsLab/momslab/modules/sonix/backend/assets/node_modules/node-sass
gyp ERR! node -v v16.1.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
```

- NPM version (`npm -v`): 7.12.1
- Node version (`node -v`): v16.1.0
- Node Process (`node -p process.versions`):
```{
  node: '16.1.0',
  v8: '9.0.257.24-node.11',
  uv: '1.41.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.17.1',
  modules: '93',
  nghttp2: '1.43.0',
  napi: '8',
  llhttp: '6.0.1',
  openssl: '1.1.1k',
  cldr: '39.0',
  icu: '69.1',
  tz: '2021a',
  unicode: '13.0'
}

```
- Node Platform (`node -p process.platform`): darwin
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`):
```
/Users/mirocow/Projects/Dockers/MomsLab/momslab/modules/sonix/backend/assets/node_modules/node-sass/lib/binding.js:13
      throw new Error(errors.unsupportedEnvironment());
      ^

Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (93)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.14.1
    at module.exports (/Users/mirocow/Projects/Dockers/MomsLab/momslab/modules/sonix/backend/assets/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/Users/mirocow/Projects/Dockers/MomsLab/momslab/modules/sonix/backend/assets/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at [eval]:1:1
    at Script.runInThisContext (node:vm:131:12)

```
- npm node-sass versions (`npm ls node-sass`):

```
ideas@0.1.0 /Users/mirocow/Projects/Dockers/MomsLab/momslab/modules/sonix/backend/assets
├─┬ gulp-sass@4.1.0
│ └── node-sass@4.14.1 deduped
└── node-sass@4.14.1

```

**Comment by nschonni** [comment]
https://github.com/sass/node-sass#node-version-support-policy

**Comment by xzyfer** [comment]
You have two versions of node in your npm tree, 6.0.0 and 14.4.1. you can confirm this with `npm list node-sass`. Only 6.0.0 supports Node 16.
