### ISSUE TITLE
node-sass install Throwing Syntax Error on scripts/build.js

### ISSUE THREAD

**Issue by jyosen-ias** [sass/node-sass#3148]
- NPM version (`npm -v`): 2.15.11
- Node version (`node -v`): v4.9.1
- Node Process (`node -p process.versions`): 
{ http_parser: '2.8.0',
  node: '4.9.1',
  v8: '4.5.103.53',
  uv: '1.9.1',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  icu: '56.1',
  modules: '46',
  openssl: '1.0.2o' }
- Node Platform (`node -p process.platform`): darwin
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`):
module.js:327
    throw err;
    ^

Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at [eval]:1:1
    at Object.exports.runInThisContext (vm.js:54:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:409:26)
    at node.js:648:27
    at nextTickCallbackWith0Args (node.js:489:9)

- npm node-sass versions (`npm ls node-sass`):
jyosen@C02CGBSYMD6M ~ % npm ls node-sass
jyosen@1.0.0 /Users/jyosen
└── (empty)

npm ERR! code 1

ERROR MESSAGE: 

```
jyosen@C02CGBSYMD6M ~ % npm install node-sass@5.0.0
npm WARN package.json jyosen@1.0.0 No description
npm WARN package.json jyosen@1.0.0 No repository field.
npm WARN package.json jyosen@1.0.0 No README data
npm WARN engine node-sass@5.0.0: wanted: {"node":">=10"} (current: {"node":"4.9.1","npm":"2.15.11"})
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN engine cross-spawn@7.0.3: wanted: {"node":">= 8"} (current: {"node":"4.9.1","npm":"2.15.11"})
npm WARN engine node-gyp@7.1.2: wanted: {"node":">= 10.12.0"} (current: {"node":"4.9.1","npm":"2.15.11"})
npm WARN engine request@2.88.2: wanted: {"node":">= 6"} (current: {"node":"4.9.1","npm":"2.15.11"})
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN engine path-key@3.1.1: wanted: {"node":">=8"} (current: {"node":"4.9.1","npm":"2.15.11"})
npm WARN engine shebang-command@2.0.0: wanted: {"node":">=8"} (current: {"node":"4.9.1","npm":"2.15.11"})
npm WARN engine which@2.0.2: wanted: {"node":">= 8"} (current: {"node":"4.9.1","npm":"2.15.11"})
npm WARN engine shebang-regex@3.0.0: wanted: {"node":">=8"} (current: {"node":"4.9.1","npm":"2.15.11"})
npm WARN engine har-validator@5.1.5: wanted: {"node":">=6"} (current: {"node":"4.9.1","npm":"2.15.11"})
npm WARN engine punycode@2.1.1: wanted: {"node":">=6"} (current: {"node":"4.9.1","npm":"2.15.11"})
npm WARN engine find-up@3.0.0: wanted: {"node":">=6"} (current: {"node":"4.9.1","npm":"2.15.11"})
npm WARN engine string-width@3.1.0: wanted: {"node":">=6"} (current: {"node":"4.9.1","npm":"2.15.11"})
npm WARN engine get-caller-file@2.0.5: wanted: {"node":"6.* || 8.* || >= 10.*"} (current: {"node":"4.9.1","npm":"2.15.11"})
npm WARN engine camelcase@5.3.1: wanted: {"node":">=6"} (current: {"node":"4.9.1","npm":"2.15.11"})
npm WARN engine strip-ansi@5.2.0: wanted: {"node":">=6"} (current: {"node":"4.9.1","npm":"2.15.11"})
npm WARN engine wrap-ansi@5.1.0: wanted: {"node":">=6"} (current: {"node":"4.9.1","npm":"2.15.11"})
npm WARN engine strip-ansi@5.2.0: wanted: {"node":">=6"} (current: {"node":"4.9.1","npm":"2.15.11"})
npm WARN engine ansi-regex@4.1.0: wanted: {"node":">=6"} (current: {"node":"4.9.1","npm":"2.15.11"})
npm WARN engine ansi-regex@4.1.0: wanted: {"node":">=6"} (current: {"node":"4.9.1","npm":"2.15.11"})
npm WARN engine locate-path@3.0.0: wanted: {"node":">=6"} (current: {"node":"4.9.1","npm":"2.15.11"})
npm WARN engine semver@7.3.5: wanted: {"node":">=10"} (current: {"node":"4.9.1","npm":"2.15.11"})
npm WARN engine which@2.0.2: wanted: {"node":">= 8"} (current: {"node":"4.9.1","npm":"2.15.11"})
npm WARN engine nopt@5.0.0: wanted: {"node":">=6"} (current: {"node":"4.9.1","npm":"2.15.11"})
npm WARN engine tar@6.1.0: wanted: {"node":">= 10"} (current: {"node":"4.9.1","npm":"2.15.11"})
npm WARN engine env-paths@2.2.1: wanted: {"node":">=6"} (current: {"node":"4.9.1","npm":"2.15.11"})
npm WARN engine p-locate@3.0.0: wanted: {"node":">=6"} (current: {"node":"4.9.1","npm":"2.15.11"})
npm WARN engine p-limit@2.3.0: wanted: {"node":">=6"} (current: {"node":"4.9.1","npm":"2.15.11"})
npm WARN engine punycode@2.1.1: wanted: {"node":">=6"} (current: {"node":"4.9.1","npm":"2.15.11"})
npm WARN engine p-try@2.2.0: wanted: {"node":">=6"} (current: {"node":"4.9.1","npm":"2.15.11"})
npm WARN engine mkdirp@1.0.4: wanted: {"node":">=10"} (current: {"node":"4.9.1","npm":"2.15.11"})
npm WARN engine chownr@2.0.0: wanted: {"node":">=10"} (current: {"node":"4.9.1","npm":"2.15.11"})
npm WARN engine minipass@3.1.3: wanted: {"node":">=8"} (current: {"node":"4.9.1","npm":"2.15.11"})
npm WARN engine minizlib@2.1.2: wanted: {"node":">= 8"} (current: {"node":"4.9.1","npm":"2.15.11"})
npm WARN engine fs-minipass@2.1.0: wanted: {"node":">= 8"} (current: {"node":"4.9.1","npm":"2.15.11"})
npm WARN engine lru-cache@6.0.0: wanted: {"node":">=10"} (current: {"node":"4.9.1","npm":"2.15.11"})
/
> node-sass@5.0.0 install /Users/jyosen/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v5.0.0/darwin-x64-46_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v5.0.0/darwin-x64-46_binding.node": 

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g. 

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@5.0.0 postinstall /Users/jyosen/node_modules/node-sass
> node scripts/build.js

/Users/jyosen/node_modules/node-sass/node_modules/cross-spawn/node_modules/which/which.js:21
        ...(isWindows ? [process.cwd()] : []),
        ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/jyosen/node_modules/node-sass/node_modules/cross-spawn/lib/util/resolveCommand.js:4:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
npm ERR! Darwin 19.6.0
npm ERR! argv "/Users/jyosen/.nvm/versions/node/v4.9.1/bin/node" "/Users/jyosen/.nvm/versions/node/v4.9.1/bin/npm" "install" "node-sass@5.0.0"
npm ERR! node v4.9.1
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE

npm ERR! node-sass@5.0.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
```

**Comment by nschonni** [comment]
https://github.com/sass/node-sass#node-version-support-policy
