### ISSUE TITLE
npm run dev : Error: ENOENT: no such file or directory, scandir '/Users/nian/Work/web/node_modules/node-sass/vendor'

### ISSUE THREAD

**Issue by miduoN** [sass/node-sass#3154]
npm run dev  :   Error: ENOENT: no such file or directory, scandir '/Users/.../web/node_modules/node-sass/vendor'

- NPM version (`npm -v`): 7.19.1
- Node version (`node -v`): v16.5.0
- Node Process (`node -p process.versions`): 
- {
  node: '16.5.0',
  v8: '9.1.269.38-node.20',
  uv: '1.41.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.17.1',
  modules: '93',
  nghttp2: '1.42.0',
  napi: '8',
  llhttp: '6.0.2',
  openssl: '1.1.1k+quic',
  cldr: '39.0',
  icu: '69.1',
  tz: '2021a',
  unicode: '13.0',
  ngtcp2: '0.1.0-DEV',
  nghttp3: '0.1.0-DEV'
}
- Node Platform (`node -p process.platform`): darwin
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`):   
 node:internal/fs/utils:343
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir '/Users/.../node_modules/node-sass/vendor'
    at Object.readdirSync (node:fs:1380:3)
    at Object.getInstalledBinaries (/Users/.../node_modules/node-sass/lib/extensions.js:134:13)
    at foundBinariesList (/Users/.../node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/Users/.../node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/Users/...node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/Users/nian/Work/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/Users/nian/Work/node_modules/node-sass/lib/index.js:13:35)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/Users/nian/Work/node_modules/node-sass/vendor'
}

- npm node-sass versions (`npm ls node-sass`):  node-sass@6.0.1
 
i tryed to change version to node v14 and node-sass v4.14+  or run rebuild node-sass   ,still not work

**Comment by nschonni** [comment]
Something went wrong in the install step. Likely swapping around the node versions. Try cleaning out your node_modules and installing again. Nothing we can troubleshoot in this

**Comment by coder-bing** [comment]
$ mkdir -p  node_modules/node-sass/vendor/linux-x64-83
$ cd $_
$ wget https://github.com/sass/node-sass/releases/download/v4.14.1/linux-x64-83_binding.node -O binding.node
