### ISSUE TITLE
Node Sass could not find a binding for your current environment: Windows 64-bit with Node.js 8.x - SPFx

### ISSUE THREAD

**Issue by TechChaitu** [sass/node-sass#3164]
Error: Missing binding node_modules\node-sass\vendor\win32-x64-57\binding.node
Node Sass could not find a binding for your current environment: Windows 64-bit with Node.js 8.x

Found bindings for the following environments:
  - Windows 64-bit with Node.js 8.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to download the binding for your current environment.
    at module.exports (node_modules\node-sass\lib\binding.js:15:13)
    at Object.<anonymous> (node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (node_modules\@microsoft\gulp-core-build-sass\lib\SassTask.js:11:18)

**Comment by nschonni** [comment]
https://github.com/sass/node-sass#node-version-support-policy
