### ISSUE TITLE
Node Sass could not resolve - does not yet support your current environment: Windows 64-bit with Unsupported runtime (83).

### ISSUE THREAD

**Issue by mbangali** [sass/node-sass#3180]
I am getting following error while running this project on my visual studio 2019 powered by windows 10. 

Project Link-https://github.com/VirtoCommerce/vc-platform
Website is launching on google chrome, it is not showing login window and chrome console shows following error,

```
Uncaught Error: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (83)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.12.0
    at module.exports (D:\workspace\open source project\vc-platform-master\vc-platform-master\src\VirtoCommerce.Platform.Web\node_modules\node-sass\lib\binding.js:13:13)
    at Object.<anonymous> (D:\workspace\open source project\vc-platform-master\vc-platform-master\src\VirtoCommerce.Platform.Web\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (D:\workspace\open source project\vc-platform-master\vc-platform-master\src\VirtoCommerce.Platform.Web\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (D:\workspace\open source project\vc-platform-master\vc-platform-master\src\VirtoCommerce.Platform.Web\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at Object.sassLoader (D:\workspace\open source project\vc-platform-master\vc-platform-master\src\VirtoCommerce.Platform.Web\node_modules\sass-loader\lib\loader.js:46:72)
    at D:\workspace\open source project\vc-platform-master\vc-platform-master\src\VirtoCommerce.Platform.Web\node_modules\webpack\lib\NormalModule.js:302:20
    at D:\workspace\open source project\vc-platform-master\vc-platform-master\src\VirtoCommerce.Platform.Web\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at D:\workspace\open source project\vc-platform-master\vc-platform-master\src\VirtoCommerce.Platform.Web\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at runSyncOrAsync (D:\workspace\open source project\vc-platform-master\vc-platform-master\src\VirtoCommerce.Platform.Web\node_modules\loader-runner\lib\LoaderRunner.js:143:3)
    at iterateNormalLoaders (D:\workspace\open source project\vc-platform-master\vc-platform-master\src\VirtoCommerce.Platform.Web\node_modules\loader-runner\lib\LoaderRunner.js:232:2)
    at Array.<anonymous> (D:\workspace\open source project\vc-platform-master\vc-platform-master\src\VirtoCommerce.Platform.Web\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (D:\workspace\open source project\vc-platform-master\vc-platform-master\src\VirtoCommerce.Platform.Web\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:43:16)
    at D:\workspace\open source project\vc-platform-master\vc-platform-master\src\VirtoCommerce.Platform.Web\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:79:9
    at D:\workspace\open source project\vc-platform-master\vc-platform-master\src\VirtoCommerce.Platform.Web\node_modules\enhanced-resolve\node_modules\graceful-fs\graceful-fs.js:90:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:73:3)
    at eval (webpack:///./wwwroot/css/themes/main/sass/main.sass?:1:7)
    at Object../wwwroot/css/themes/main/sass/main.sass (http://localhost:10645/dist/vendor.js?v=2R36p2hZBe8uLW6_NuiAkIn597e6dPCEhM10yJEHugs:4319:1)
    at __webpack_require__ (http://localhost:10645/dist/vendor.js?v=2R36p2hZBe8uLW6_NuiAkIn597e6dPCEhM10yJEHugs:20:30)
    at eval (webpack:///multi_./wwwroot/src/js/vendor.js_./wwwroot/css/themes/main/sass/main.sass?:2:18)
    at Object.0 (http://localhost:10645/dist/vendor.js?v=2R36p2hZBe8uLW6_NuiAkIn597e6dPCEhM10yJEHugs:4365:1)
    at __webpack_require__ (http://localhost:10645/dist/vendor.js?v=2R36p2hZBe8uLW6_NuiAkIn597e6dPCEhM10yJEHugs:20:30)
    at http://localhost:10645/dist/vendor.js?v=2R36p2hZBe8uLW6_NuiAkIn597e6dPCEhM10yJEHugs:84:18
    at http://localhost:10645/dist/vendor.js?v=2R36p2hZBe8uLW6_NuiAkIn597e6dPCEhM10yJEHugs:87:10
:10645/api/platform/security/currentuser:1 Failed to load resource: the server responded with a status of 401 (Unauthorized)

```

npm -v 6.14.15
node -v v14.17.6

node -p process.versions
{
  node: '14.17.6',
  v8: '8.4.371.23-node.76',
  uv: '1.41.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.17.2',
  modules: '83',
  nghttp2: '1.42.0',
  napi: '8',
  llhttp: '2.1.3',
  openssl: '1.1.1l',
  cldr: '39.0',
  icu: '69.1',
  tz: '2021a',
  unicode: '13.0'
}

node -p process.platform win32

node -p process.arch x64

npm ls node-sass
app@1.0.0 D:\vc2\src\VirtoCommerce.Platform.Web
`-- @ionic/app-scripts@3.2.4
  `-- node-sass@4.14.1

**Comment by nschonni** [comment]
https://github.com/sass/node-sass#node-version-support-policy, you're message says 4.12.0, not 4.14.1
