### ISSUE TITLE
Node 14.8, Node-Sass 4.14, python 3.9 instalation fail

### ISSUE THREAD

**Issue by afonsopbarros** [sass/node-sass#3217]
```
/Users/afonsobarros/yonder/frontend/node_modules/node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments: 
Directory: /Users/afonsobarros/yonder/frontend/node_modules/node-sass
Output:
Building: /Users/afonsobarros/.nvm/versions/node/v14.18.2/bin/node /Users/afonsobarros/yonder/frontend/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/Users/afonsobarros/.nvm/versions/node/v14.18.2/bin/node',
gyp verb cli   '/Users/afonsobarros/yonder/frontend/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@14.18.2 | darwin | arm64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "/opt/homebrew/opt/python@3.9/bin/python3" in the PATH
gyp verb `which` succeeded /opt/homebrew/opt/python@3.9/bin/python3 /opt/homebrew/opt/python@3.9/bin/python3
gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /opt/homebrew/opt/python@3.9/bin/python3 -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:383:12)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at maybeClose (internal/child_process.js:1058:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
gyp ERR! System Darwin 21.1.0
gyp ERR! command "/Users/afonsobarros/.nvm/versions/node/v14.18.2/bin/node" "/Users/afonsobarros/yonder/frontend/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/afonsobarros/yonder/frontend/node_modules/node-sass
gyp ERR! node -v v14.18.2
```

**Comment by afonsopbarros** [comment]
reinstall node, reinstall yarn

**Comment by nschonni** [comment]
Node 14 with 4.14 shouldn't be falling back to a manual build, you've got something else going on

**Comment by Bo98** [comment]
> Node 14 with 4.14 shouldn't be falling back to a manual build, you've got something else going on

Even on arm64?

node-sass < 5 doesn't support Python 3 because it pins node-gyp to a very old version.

npm 8 ships with node-gyp 8 which doesn't support Python 2 anymore so many distributions of Node no longer use Python 2 by default.

The env `node_config_python=/usr/bin/python` might work. But using Python 2 under any method will soon break in a future macOS so it's a ticking clock at this point.

**Comment by nschonni** [comment]
OK, we don't support ARM at all, sorry

**Comment by dptole** [comment]
As it has not been clear this comment section should be closed or not, and because I had a similar issue I'll post my solution to it.

While running alpine 3.15, via the php:7-alpine docker image, I had the following error message while running `npm i`:

```
Error: Command failed: /usr/bin/python3 -c import sys; print "%s.%s.%s" % sys.version_info[:3];
```

It happened while trying to build the node-sass binaries.

My solution was to just change all the main repositories:

```
cat <<EOF -> /etc/apk/repositories
https://dl-cdn.alpinelinux.org/alpine/v3.11/main
https://dl-cdn.alpinelinux.org/alpine/v3.11/community
EOF
```

By using this repo instead of 3.15 I was able to download nodejs v12 and all the other dependencies that made my `npm i` command work fine.
