### ISSUE TITLE
[unsupported] Installing node-sass 4.5.3 on Node 12

### ISSUE THREAD

**Issue by kotran88** [sass/node-sass#3255]
I'm using ionic version3. 
m1 Mac
node version is 12 and using with nvm. 

when I ionic Cordova platform rm iOS , build iOS ...
then It cause error 

```

make: *** [Release/obj.target/binding/src/create_string.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/pedrojung/Downloads/ios_0414/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Darwin 21.4.0
gyp ERR! command "/Users/pedrojung/.nvm/versions/node/v12.22.11/bin/node" "/Users/pedrojung/Downloads/ios_0414/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/pedrojung/Downloads/ios_0414/node_modules/@ionic/app-scripts/node_modules/node-sass
gyp ERR! node -v v12.22.11
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.5.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.5.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pedrojung/.npm/_logs/2022-04-13T11_46_59_282Z-debug.log
```

I think I did many things like 
npm I sass
npm rebuild node-sass
remove node_modules 

etc...
but never works. 

how can I remove platform iOS and add or build iOS again ?

**Comment by xzyfer** [comment]
Can you please run these commands and paste the output in this issue?

```
npm -v
node -v
node -p process.versions
node -p process.platform
node -p process.arch
```

**Comment by nschonni** [comment]
https://github.com/sass/node-sass#node-version-support-policy
