### ISSUE TITLE
New release are not compatible with Node 16.3.2

### ISSUE THREAD

**Issue by aryanisml** [sass/node-sass#3297]
We are getting the error in production regarding node-sass.

Please guide. 
In package.JSON we are using 
    "node-sass": "^7.0.1",

**Comment by xzyfer** [comment]
What is the error?

**Comment by shivakumarm125** [comment]
+1

**Comment by aryanisml** [comment]
C:\Users\aryan\Downloads\npm>npm install node-sass
npm ERR! code 1
npm ERR! path C:\Users\aryan\Downloads\npm\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c C:\Users\aryan~1\AppData\Local\Temp\postinstall-2c214eed.cmd
npm ERR! Binary found at C:\Users\aryan\Downloads\npm\node_modules\node-sass\vendor\win32-x64-93\binding.node
npm ERR! Testing binary
npm ERR! Binary has a problem: Error: \\?\C:\Users\aryan\Downloads\npm\node_modules\node-sass\vendor\win32-x64-93\binding.node is not a valid Win32 application.
npm ERR! \\?\C:\Users\aryan\Downloads\npm\node_modules\node-sass\vendor\win32-x64-93\binding.node
npm ERR!     at Object.Module._extensions..node (node:internal/modules/cjs/loader:1210:18)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:1004:32)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:839:12)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1028:19)
npm ERR!     at require (node:internal/modules/cjs/helpers:102:18)
npm ERR!     at module.exports (C:\Users\aryan\Downloads\npm\node_modules\node-sass\lib\binding.js:19:10)
npm ERR!     at Object.<anonymous> (C:\Users\aryan\Downloads\npm\node_modules\node-sass\lib\index.js:13:35)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1126:14)
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:1004:32) {
npm ERR!   code: 'ERR_DLOPEN_FAILED'
npm ERR! }
npm ERR! Building the binary locally
npm ERR! Building: C:\Program Files\nodejs\node.exe C:\Users\aryan\Downloads\npm\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm ERR! gyp verb cli   'C:\\Users\\aryan\\Downloads\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@9.1.0
npm ERR! gyp info using node@16.17.0 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb find Python Python is not set from command line or npm configuration
npm ERR! gyp verb find Python Python is not set from environment variable PYTHON
npm ERR! gyp verb find Python checking if "python3" can be used
npm ERR! gyp verb find Python - executing "python3" to get executable path
npm ERR! gyp verb find Python - "python3" is not in PATH or produced an error
npm ERR! gyp verb find Python checking if "python" can be used
npm ERR! gyp verb find Python - executing "python" to get executable path
npm ERR! gyp verb find Python - "python" is not in PATH or produced an error
npm ERR! gyp verb find Python checking if Python is C:\Users\aryan\AppData\Local\Programs\Python\Python39\python.exe
npm ERR! gyp verb find Python - executing "C:\Users\aryan\AppData\Local\Programs\Python\Python39\python.exe" to get version
npm ERR! gyp verb find Python - "C:\Users\aryan\AppData\Local\Programs\Python\Python39\python.exe" could not be run
npm ERR! gyp verb find Python checking if Python is C:\Program Files\Python39\python.exe
npm ERR! gyp verb find Python - executing "C:\Program Files\Python39\python.exe" to get version
npm ERR! gyp verb find Python - "C:\Program Files\Python39\python.exe" could not be run
npm ERR! gyp verb find Python checking if Python is C:\Users\aryan\AppData\Local\Programs\Python\Python39-32\python.exe
npm ERR! gyp verb find Python - executing "C:\Users\aryan\AppData\Local\Programs\Python\Python39-32\python.exe" to get version
npm ERR! gyp verb find Python - "C:\Users\aryan\AppData\Local\Programs\Python\Python39-32\python.exe" could not be run
npm ERR! gyp verb find Python checking if Python is C:\Program Files\Python39-32\python.exe
npm ERR! gyp verb find Python - executing "C:\Program Files\Python39-32\python.exe" to get version
npm ERR! gyp verb find Python - "C:\Program Files\Python39-32\python.exe" could not be run
npm ERR! gyp verb find Python checking if Python is C:\Program Files (x86)\Python39-32\python.exe
npm ERR! gyp verb find Python - executing "C:\Program Files (x86)\Python39-32\python.exe" to get version
npm ERR! gyp verb find Python - "C:\Program Files (x86)\Python39-32\python.exe" could not be run
npm ERR! gyp verb find Python checking if Python is C:\Users\aryan\AppData\Local\Programs\Python\Python38\python.exe
npm ERR! gyp verb find Python - executing "C:\Users\aryan\AppData\Local\Programs\Python\Python38\python.exe" to get version
npm ERR! gyp verb find Python - "C:\Users\aryan\AppData\Local\Programs\Python\Python38\python.exe" could not be run
npm ERR! gyp verb find Python checking if Python is C:\Program Files\Python38\python.exe
npm ERR! gyp verb find Python - executing "C:\Program Files\Python38\python.exe" to get version
npm ERR! gyp verb find Python - "C:\Program Files\Python38\python.exe" could not be run
npm ERR! gyp verb find Python checking if Python is C:\Users\aryan\AppData\Local\Programs\Python\Python38-32\python.exe
npm ERR! gyp verb find Python - executing "C:\Users\aryan\AppData\Local\Programs\Python\Python38-32\python.exe" to get version
npm ERR! gyp verb find Python - "C:\Users\aryan\AppData\Local\Programs\Python\Python38-32\python.exe" could not be run
npm ERR! gyp verb find Python checking if Python is C:\Program Files\Python38-32\python.exe
npm ERR! gyp verb find Python - executing "C:\Program Files\Python38-32\python.exe" to get version
npm ERR! gyp verb find Python - "C:\Program Files\Python38-32\python.exe" could not be run
npm ERR! gyp verb find Python checking if Python is C:\Program Files (x86)\Python38-32\python.exe
npm ERR! gyp verb find Python - executing "C:\Program Files (x86)\Python38-32\python.exe" to get version
npm ERR! gyp verb find Python - "C:\Program Files (x86)\Python38-32\python.exe" could not be run
npm ERR! gyp verb find Python checking if Python is C:\Users\aryan\AppData\Local\Programs\Python\Python37\python.exe
npm ERR! gyp verb find Python - executing "C:\Users\aryan\AppData\Local\Programs\Python\Python37\python.exe" to get version
npm ERR! gyp verb find Python - "C:\Users\aryan\AppData\Local\Programs\Python\Python37\python.exe" could not be run
npm ERR! gyp verb find Python checking if Python is C:\Program Files\Python37\python.exe
npm ERR! gyp verb find Python - executing "C:\Program Files\Python37\python.exe" to get version
npm ERR! gyp verb find Python - "C:\Program Files\Python37\python.exe" could not be run
npm ERR! gyp verb find Python checking if Python is C:\Users\aryan\AppData\Local\Programs\Python\Python37-32\python.exe
npm ERR! gyp verb find Python - executing "C:\Users\aryan\AppData\Local\Programs\Python\Python37-32\python.exe" to get version
npm ERR! gyp verb find Python - "C:\Users\aryan\AppData\Local\Programs\Python\Python37-32\python.exe" could not be run
npm ERR! gyp verb find Python checking if Python is C:\Program Files\Python37-32\python.exe
npm ERR! gyp verb find Python - executing "C:\Program Files\Python37-32\python.exe" to get version
npm ERR! gyp verb find Python - "C:\Program Files\Python37-32\python.exe" could not be run
npm ERR! gyp verb find Python checking if Python is C:\Program Files (x86)\Python37-32\python.exe
npm ERR! gyp verb find Python - executing "C:\Program Files (x86)\Python37-32\python.exe" to get version
npm ERR! gyp verb find Python - "C:\Program Files (x86)\Python37-32\python.exe" could not be run
npm ERR! gyp verb find Python checking if Python is C:\Users\aryan\AppData\Local\Programs\Python\Python36\python.exe
npm ERR! gyp verb find Python - executing "C:\Users\aryan\AppData\Local\Programs\Python\Python36\python.exe" to get version
npm ERR! gyp verb find Python - "C:\Users\aryan\AppData\Local\Programs\Python\Python36\python.exe" could not be run
npm ERR! gyp verb find Python checking if Python is C:\Program Files\Python36\python.exe
npm ERR! gyp verb find Python - executing "C:\Program Files\Python36\python.exe" to get version
npm ERR! gyp verb find Python - "C:\Program Files\Python36\python.exe" could not be run
npm ERR! gyp verb find Python checking if Python is C:\Users\aryan\AppData\Local\Programs\Python\Python36-32\python.exe
npm ERR! gyp verb find Python - executing "C:\Users\aryan\AppData\Local\Programs\Python\Python36-32\python.exe" to get version
npm ERR! gyp verb find Python - "C:\Users\aryan\AppData\Local\Programs\Python\Python36-32\python.exe" could not be run
npm ERR! gyp verb find Python checking if Python is C:\Program Files\Python36-32\python.exe
npm ERR! gyp verb find Python - executing "C:\Program Files\Python36-32\python.exe" to get version
npm ERR! gyp verb find Python - "C:\Program Files\Python36-32\python.exe" could not be run
npm ERR! gyp verb find Python checking if Python is C:\Program Files (x86)\Python36-32\python.exe
npm ERR! gyp verb find Python - executing "C:\Program Files (x86)\Python36-32\python.exe" to get version
npm ERR! gyp verb find Python - "C:\Program Files (x86)\Python36-32\python.exe" could not be run
npm ERR! gyp verb find Python checking if the py launcher can be used to find Python 3
npm ERR! gyp verb find Python - executing "py.exe" to get Python 3 executable path
npm ERR! gyp verb find Python - "py.exe" is not in PATH or produced an error
npm ERR! gyp ERR! find Python
npm ERR! gyp ERR! find Python Python is not set from command line or npm configuration
npm ERR! gyp ERR! find Python Python is not set from environment variable PYTHON
npm ERR! gyp ERR! find Python checking if "python3" can be used
npm ERR! gyp ERR! find Python - "python3" is not in PATH or produced an error
npm ERR! gyp ERR! find Python checking if "python" can be used
npm ERR! gyp ERR! find Python - "python" is not in PATH or produced an error
npm ERR! gyp ERR! find Python checking if Python is C:\Users\aryan\AppData\Local\Programs\Python\Python39\python.exe
npm ERR! gyp ERR! find Python - "C:\Users\aryan\AppData\Local\Programs\Python\Python39\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files\Python39\python.exe
npm ERR! gyp ERR! find Python - "C:\Program Files\Python39\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Users\aryan\AppData\Local\Programs\Python\Python39-32\python.exe
npm ERR! gyp ERR! find Python - "C:\Users\aryan\AppData\Local\Programs\Python\Python39-32\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files\Python39-32\python.exe
npm ERR! gyp ERR! find Python - "C:\Program Files\Python39-32\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files (x86)\Python39-32\python.exe
npm ERR! gyp ERR! find Python - "C:\Program Files (x86)\Python39-32\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Users\aryan\AppData\Local\Programs\Python\Python38\python.exe
npm ERR! gyp ERR! find Python - "C:\Users\aryan\AppData\Local\Programs\Python\Python38\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files\Python38\python.exe
npm ERR! gyp ERR! find Python - "C:\Program Files\Python38\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Users\aryan\AppData\Local\Programs\Python\Python38-32\python.exe
npm ERR! gyp ERR! find Python - "C:\Users\aryan\AppData\Local\Programs\Python\Python38-32\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files\Python38-32\python.exe
npm ERR! gyp ERR! find Python - "C:\Program Files\Python38-32\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files (x86)\Python38-32\python.exe
npm ERR! gyp ERR! find Python - "C:\Program Files (x86)\Python38-32\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Users\aryan\AppData\Local\Programs\Python\Python37\python.exe
npm ERR! gyp ERR! find Python - "C:\Users\aryan\AppData\Local\Programs\Python\Python37\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files\Python37\python.exe
npm ERR! gyp ERR! find Python - "C:\Program Files\Python37\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Users\aryan\AppData\Local\Programs\Python\Python37-32\python.exe
npm ERR! gyp ERR! find Python - "C:\Users\aryan\AppData\Local\Programs\Python\Python37-32\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files\Python37-32\python.exe
npm ERR! gyp ERR! find Python - "C:\Program Files\Python37-32\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files (x86)\Python37-32\python.exe
npm ERR! gyp ERR! find Python - "C:\Program Files (x86)\Python37-32\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Users\aryan\AppData\Local\Programs\Python\Python36\python.exe
npm ERR! gyp ERR! find Python - "C:\Users\aryan\AppData\Local\Programs\Python\Python36\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files\Python36\python.exe
npm ERR! gyp ERR! find Python - "C:\Program Files\Python36\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Users\aryan\AppData\Local\Programs\Python\Python36-32\python.exe
npm ERR! gyp ERR! find Python - "C:\Users\aryan\AppData\Local\Programs\Python\Python36-32\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files\Python36-32\python.exe
npm ERR! gyp ERR! find Python - "C:\Program Files\Python36-32\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files (x86)\Python36-32\python.exe
npm ERR! gyp ERR! find Python - "C:\Program Files (x86)\Python36-32\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if the py launcher can be used to find Python 3
npm ERR! gyp ERR! find Python - "py.exe" is not in PATH or produced an error
npm ERR! gyp ERR! find Python
npm ERR! gyp ERR! find Python **********************************************************
npm ERR! gyp ERR! find Python You need to install the latest version of Python.
npm ERR! gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
npm ERR! gyp ERR! find Python you can try one of the following options:
npm ERR! gyp ERR! find Python - Use the switch --python="C:\Path\To\python.exe"
npm ERR! gyp ERR! find Python   (accepted by both node-gyp and npm)
npm ERR! gyp ERR! find Python - Set the environment variable PYTHON
npm ERR! gyp ERR! find Python - Set the npm configuration variable python:
npm ERR! gyp ERR! find Python   npm config set python "C:\Path\To\python.exe"
npm ERR! gyp ERR! find Python For more information consult the documentation at:
npm ERR! gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
npm ERR! gyp ERR! find Python **********************************************************
npm ERR! gyp ERR! find Python
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Could not find any Python installation to use
npm ERR! gyp ERR! stack     at PythonFinder.fail (C:\Users\aryan\Downloads\npm\node_modules\node-gyp\lib\find-python.js:330:47)
npm ERR! gyp ERR! stack     at PythonFinder.runChecks (C:\Users\aryan\Downloads\npm\node_modules\node-gyp\lib\find-python.js:159:21)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\aryan\Downloads\npm\node_modules\node-gyp\lib\find-python.js:228:18)
npm ERR! gyp ERR! stack     at PythonFinder.execFileCallback (C:\Users\aryan\Downloads\npm\node_modules\node-gyp\lib\find-python.js:294:16)
npm ERR! gyp ERR! stack     at exithandler (node:child_process:408:5)
npm ERR! gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:420:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
npm ERR! gyp ERR! stack     at onErrorNT (node:internal/child_process:478:16)
npm ERR! gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:83:21)
npm ERR! gyp ERR! System Windows_NT 10.0.22000
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\aryan\\Downloads\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd C:\Users\aryan\Downloads\npm\node_modules\node-sass
npm ERR! gyp ERR! node -v v16.17.0
npm ERR! gyp ERR! node-gyp -v v9.1.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\aryan\AppData\Local\npm-cache\_logs\2022-09-08T07_06_57_672Z-debug-0.log

**Comment by aryanisml** [comment]
node version - v16.17.0
npm version - 8.15.0

**Comment by xzyfer** [comment]
Looks like there is something wrong with the binaries in on the new release. I'm investigating.

**Comment by shivakumarm125** [comment]
Hi @xzyfer,
We are facing similar issue in v7.0.0 as well.
Binary has a problem: Error: /tmp/frontend/node_modules/node-sass/vendor/linux-x64-93/binding.node: file too short

**Comment by xzyfer** [comment]
I'm at a bit of a loss. I've re-uploaded the binaries. I've confirmed a manually downloaded binary works. But when the binary is downloaded from github as part of the install process it's corrupt. It's possible the broken binaries are cached somewhere along the way. 

The only thing I can think of is publishing a new release and hoping the binaries that are uploaded are fine. That should clear out any caches.

**Comment by xzyfer** [comment]
That didn't work either. I created a v7.0.3 for testing locally with a known good binary. When the binary is downloaded it's corrupted. I'm at a loss.

**Comment by xzyfer** [comment]
Oh my, I didn't realise how much was on master that was released in v7.0.2. I had intended to just release #3292. Looks like I also released untested changes to the binary download process. That gives me somewhere to look.

**Comment by xzyfer** [comment]
I've also unpublished v7.0.2 to avoid further issues.

**Comment by aryanisml** [comment]
> This should be resolved in v7.0.3.

Yes verified this issue has been resolved. 

npm install node-sass
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

added 240 packages, and audited 241 packages in 41s
\Downloads\npm>node --version
v16.17.0

**Comment by Rafat97** [comment]
> This should be resolved in v7.0.3.

Solved. 
Thank You @xzyfer.

**Comment by Rafat97** [comment]
The same, problem occurs again. 😢 


```
#0 462.7 error /usr/src/app/node_modules/node-sass: Command failed.
#0 462.7 Exit code: 1
#0 462.7 Command: node scripts/build.js
#0 462.7 Arguments:
#0 462.7 Directory: /usr/src/app/node_modules/node-sass
#0 462.7 Output:
#0 462.7 Building: /usr/local/bin/node /usr/src/app/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
#0 462.7 gyp info it worked if it ends with ok
#0 462.7 gyp verb cli [
#0 462.7 gyp verb cli   '/usr/local/bin/node',
#0 462.7 gyp verb cli   '/usr/src/app/node_modules/node-gyp/bin/node-gyp.js',
#0 462.7 gyp verb cli   'rebuild',
#0 462.7 gyp verb cli   '--verbose',
#0 462.7 gyp verb cli   '--libsass_ext=',
#0 462.7 gyp verb cli   '--libsass_cflags=',
#0 462.7 gyp verb cli   '--libsass_ldflags=',
#0 462.7 gyp verb cli   '--libsass_library='
#0 462.7 gyp verb cli ]
#0 462.7 gyp info using node-gyp@8.4.1
#0 462.7 gyp info using node@18.12.0 | linux | x64
#0 462.7 gyp verb command rebuild []
#0 462.7 gyp verb command clean []
#0 462.7 gyp verb clean removing "build" directory
#0 462.7 gyp verb command configure []
#0 462.7 gyp verb find Python Python is not set from command line or npm configuration
#0 462.7 gyp verb find Python Python is not set from environment variable PYTHON
#0 462.7 gyp verb find Python checking if "python3" can be used
#0 462.7 gyp verb find Python - executing "python3" to get executable path
#0 462.7 gyp verb find Python - "python3" is not in PATH or produced an error
#0 462.7 gyp verb find Python checking if "python" can be used
#0 462.7 gyp verb find Python - executing "python" to get executable path
#0 462.7 gyp verb find Python - "python" is not in PATH or produced an error
#0 462.7 gyp ERR! find Python
#0 462.7 gyp ERR! find Python Python is not set from command line or npm configuration
#0 462.7 gyp ERR! find Python Python is not set from environment variable PYTHON
#0 462.7 gyp ERR! find Python checking if "python3" can be used
#0 462.7 gyp ERR! find Python - "python3" is not in PATH or produced an error
#0 462.7 gyp ERR! find Python checking if "python" can be used
#0 462.7 gyp ERR! find Python - "python" is not in PATH or produced an error
#0 462.7 gyp ERR! find Python
#0 462.7 gyp ERR! find Python **********************************************************
#0 462.7 gyp ERR! find Python You need to install the latest version of Python.
#0 462.7 gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
#0 462.7 gyp ERR! find Python you can try one of the following options:
#0 462.7 gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
#0 462.7 gyp ERR! find Python   (accepted by both node-gyp and npm)
#0 462.7 gyp ERR! find Python - Set the environment variable PYTHON
#0 462.7 gyp ERR! find Python - Set the npm configuration variable python:
#0 462.7 gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
#0 462.7 gyp ERR! find Python For more information consult the documentation at:
#0 462.7 gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
#0 462.7 gyp ERR! find Python **********************************************************
#0 462.7 gyp ERR! find Python
#0 462.7 gyp ERR! configure error
#0 462.7 gyp ERR! stack Error: Could not find any Python installation to use
#0 462.7 gyp ERR! stack     at PythonFinder.fail (/usr/src/app/node_modules/node-gyp/lib/find-python.js:330:47)
#0 462.7 gyp ERR! stack     at PythonFinder.runChecks (/usr/src/app/node_modules/node-gyp/lib/find-python.js:159:21)
#0 462.7 gyp ERR! stack     at PythonFinder.<anonymous> (/usr/src/app/node_modules/node-gyp/lib/find-python.js:202:16)
#0 462.7 gyp ERR! stack     at PythonFinder.execFileCallback (/usr/src/app/node_modules/node-gyp/lib/find-python.js:294:16)
#0 462.7 gyp ERR! stack     at exithandler (node:child_process:420:5)
#0 462.7 gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:432:5)
#0 462.7 gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
#0 462.7 gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:289:12)
#0 462.7 gyp ERR! stack     at onErrorNT (node:internal/child_process:476:16)
#0 462.7 gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
#0 462.7 gyp ERR! System Linux 5.10.104-linuxkit
#0 462.7 gyp ERR! command "/usr/local/bin/node" "/usr/src/app/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
#0 462.7 gyp ERR! cwd /usr/src/app/node_modules/node-sass
#0 462.7 gyp ERR! node -v v18.12.0
#0 462.7 gyp ERR! node-gyp -v v8.4.1
#0 462.7 gyp ERR! not ok
#0 462.7 Build failed with error code: 1
#0 462.7 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by SuperKirik** [comment]
I have the same error with v9.0.0 🤔 

```
node-sass: v9.0.0
Windows 10 and Windows 11 both
Node v21.1.0
```

**Comment by bearfriend** [comment]
I was getting this error with v9 on a fairly barebones new install of Ubuntu 22.04 (ARM64). Skimmed through to errors, installed what seemed to be missing (`make` and `g++`) and it works fine now:

```
sudo apt install make
sudo apt install build-essential
```
