### ISSUE TITLE
React App deployment not working

### ISSUE THREAD

**Issue by Rafat97** [sass/node-sass#3298]
## Error log

Node version `14.16.1`
NPM version `6.14.12`
node-sass version  `7.0.2`

```
2022-09-08T07:06:46.34305Z	Cloning repository...
2022-09-08T07:06:49.517574Z	From https://github.com/carxparts/carxparts-front-end
2022-09-08T07:06:49.51806Z	 * branch            f674fb8ea50fdd686a3f95835ef7a772d38370c7 -> FETCH_HEAD
2022-09-08T07:06:49.5183Z	
2022-09-08T07:06:49.92616Z	HEAD is now at f674fb8 chore: update
2022-09-08T07:06:49.926709Z	
2022-09-08T07:06:50.077412Z	
2022-09-08T07:06:50.105701Z	Success: Finished cloning repository files
2022-09-08T07:06:51.228448Z	Installing dependencies
2022-09-08T07:06:51.240206Z	Python version set to 2.7
2022-09-08T07:06:53.187729Z	Attempting node version '14.16.1' from .nvmrc
2022-09-08T07:06:54.562702Z	Downloading and installing node v14.16.1...
2022-09-08T07:06:54.942444Z	Downloading https://nodejs.org/dist/v14.16.1/node-v14.16.1-linux-x64.tar.xz...
2022-09-08T07:06:55.332687Z	Computing checksum with sha256sum
2022-09-08T07:06:55.461411Z	Checksums matched!
2022-09-08T07:06:59.837864Z	Now using node v14.16.1 (npm v6.14.12)
2022-09-08T07:07:00.243878Z	Started restoring cached build plugins
2022-09-08T07:07:00.256889Z	Finished restoring cached build plugins
2022-09-08T07:07:00.760667Z	Attempting ruby version 2.7.1, read from environment
2022-09-08T07:07:04.374319Z	Using ruby version 2.7.1
2022-09-08T07:07:04.733695Z	Using PHP version 5.6
2022-09-08T07:07:04.892799Z	5.2 is already installed.
2022-09-08T07:07:04.919202Z	Using Swift version 5.2
2022-09-08T07:07:04.91965Z	Started restoring cached node modules
2022-09-08T07:07:04.935908Z	Finished restoring cached node modules
2022-09-08T07:07:05.176714Z	Installing NPM modules using NPM version 6.14.12
2022-09-08T07:07:06.438675Z	npm WARN deprecated redux-devtools-extension@2.13.9: Package moved to @redux-devtools/extension.
2022-09-08T07:07:18.425385Z	npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
2022-09-08T07:07:18.701256Z	npm WARN deprecated @aws-sdk/eventstream-marshaller@3.6.1: The package @aws-sdk/eventstream-marshaller has been renamed to @aws-sdk/eventstream-codec. Please install the renamed package.
2022-09-08T07:07:21.603751Z	npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
2022-09-08T07:07:27.573465Z	npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
2022-09-08T07:07:30.446059Z	npm WARN deprecated @aws-sdk/eventstream-marshaller@3.29.0: The package @aws-sdk/eventstream-marshaller has been renamed to @aws-sdk/eventstream-codec. Please install the renamed package.
2022-09-08T07:07:31.682765Z	npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
2022-09-08T07:08:21.30494Z	
2022-09-08T07:08:21.305383Z	> node-sass@7.0.2 install /opt/buildhome/repo/node_modules/node-sass
2022-09-08T07:08:21.306493Z	> node scripts/install.js
2022-09-08T07:08:21.306738Z	
2022-09-08T07:08:21.972444Z	Downloading binary from https://github.com/sass/node-sass/releases/download/v7.0.2/linux-x64-83_binding.node
2022-09-08T07:08:22.178351Z	Download complete
2022-09-08T07:08:22.178982Z	Binary saved to /opt/buildhome/repo/node_modules/node-sass/vendor/linux-x64-83/binding.node
2022-09-08T07:08:22.252295Z	Caching binary to /opt/buildhome/.npm/node-sass/7.0.2/linux-x64-83_binding.node
2022-09-08T07:08:22.754986Z	
2022-09-08T07:08:22.755438Z	> core-js@3.25.1 postinstall /opt/buildhome/repo/node_modules/core-js
2022-09-08T07:08:22.755612Z	> node -e "try{require('./postinstall')}catch(e){}"
2022-09-08T07:08:22.755871Z	
2022-09-08T07:08:22.868234Z	[96mThank you for using core-js ([94m https://github.com/zloirock/core-js [96m) for polyfilling JavaScript standard library![0m
2022-09-08T07:08:22.868537Z	
2022-09-08T07:08:22.868678Z	[96mThe project needs your help! Please consider supporting of core-js:[0m
2022-09-08T07:08:22.868875Z	[96m>[94m https://opencollective.com/core-js [0m
2022-09-08T07:08:22.869008Z	[96m>[94m https://patreon.com/zloirock [0m
2022-09-08T07:08:22.869128Z	[96m>[94m bitcoin: bc1qlea7544qtsmj2rayg0lthvza9fau63ux0fstcz [0m
2022-09-08T07:08:22.869267Z	
2022-09-08T07:08:22.869383Z	[96mAlso, the author of core-js ([94m https://github.com/zloirock [96m) is looking for a good job -)[0m
2022-09-08T07:08:22.869492Z	
2022-09-08T07:08:22.884499Z	
2022-09-08T07:08:22.884858Z	> core-js-pure@3.25.1 postinstall /opt/buildhome/repo/node_modules/core-js-pure
2022-09-08T07:08:22.885018Z	> node -e "try{require('./postinstall')}catch(e){}"
2022-09-08T07:08:22.885146Z	
2022-09-08T07:08:23.80402Z	
2022-09-08T07:08:23.8044Z	> cwebp-bin@7.0.1 postinstall /opt/buildhome/repo/node_modules/cwebp-bin
2022-09-08T07:08:23.804594Z	> node lib/install.js
2022-09-08T07:08:23.804753Z	
2022-09-08T07:08:24.417297Z	cwebp pre-build test passed successfully
2022-09-08T07:08:24.435939Z	
2022-09-08T07:08:24.436229Z	> gif2webp-bin@3.0.3 postinstall /opt/buildhome/repo/node_modules/gif2webp-bin
2022-09-08T07:08:24.436385Z	> node lib/install.js
2022-09-08T07:08:24.436505Z	
2022-09-08T07:08:25.339734Z	gif2webp pre-build test passed successfully
2022-09-08T07:08:25.355703Z	
2022-09-08T07:08:25.356019Z	> gifsicle@5.3.0 postinstall /opt/buildhome/repo/node_modules/gifsicle
2022-09-08T07:08:25.35675Z	> node lib/install.js
2022-09-08T07:08:25.356914Z	
2022-09-08T07:08:25.748943Z	gifsicle pre-build test passed successfully
2022-09-08T07:08:25.790991Z	
2022-09-08T07:08:25.791341Z	> node-sass@7.0.2 postinstall /opt/buildhome/repo/node_modules/node-sass
2022-09-08T07:08:25.7915Z	> node scripts/build.js
2022-09-08T07:08:25.791619Z	
2022-09-08T07:08:26.068224Z	Binary found at /opt/buildhome/repo/node_modules/node-sass/vendor/linux-x64-83/binding.node
2022-09-08T07:08:26.068655Z	Testing binary
2022-09-08T07:08:26.284727Z	Binary has a problem: Error: /opt/buildhome/repo/node_modules/node-sass/vendor/linux-x64-83/binding.node: file too short
2022-09-08T07:08:26.285803Z	    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
2022-09-08T07:08:26.286056Z	    at Module.load (internal/modules/cjs/loader.js:928:32)
2022-09-08T07:08:26.286216Z	    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
2022-09-08T07:08:26.286359Z	    at Module.require (internal/modules/cjs/loader.js:952:19)
2022-09-08T07:08:26.28648Z	    at require (internal/modules/cjs/helpers.js:88:18)
2022-09-08T07:08:26.286594Z	    at module.exports (/opt/buildhome/repo/node_modules/node-sass/lib/binding.js:19:10)
2022-09-08T07:08:26.286703Z	    at Object.<anonymous> (/opt/buildhome/repo/node_modules/node-sass/lib/index.js:13:35)
2022-09-08T07:08:26.28681Z	    at Module._compile (internal/modules/cjs/loader.js:1063:30)
2022-09-08T07:08:26.286919Z	    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
2022-09-08T07:08:26.287028Z	    at Module.load (internal/modules/cjs/loader.js:928:32)
2022-09-08T07:08:26.287143Z	Building the binary locally
2022-09-08T07:08:26.287282Z	Building: /opt/buildhome/.nvm/versions/node/v14.16.1/bin/node /opt/buildhome/repo/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
2022-09-08T07:08:26.418158Z	gyp info it worked if it ends with ok
2022-09-08T07:08:26.420377Z	gyp verb cli [
2022-09-08T07:08:26.420623Z	gyp verb cli   '/opt/buildhome/.nvm/versions/node/v14.16.1/bin/node',
2022-09-08T07:08:26.420764Z	gyp verb cli   '/opt/buildhome/repo/node_modules/node-gyp/bin/node-gyp.js',
2022-09-08T07:08:26.420889Z	gyp verb cli   'rebuild',
2022-09-08T07:08:26.421Z	gyp verb cli   '--verbose',
2022-09-08T07:08:26.421107Z	gyp verb cli   '--libsass_ext=',
2022-09-08T07:08:26.421245Z	gyp verb cli   '--libsass_cflags=',
2022-09-08T07:08:26.421367Z	gyp verb cli   '--libsass_ldflags=',
2022-09-08T07:08:26.421482Z	gyp verb cli   '--libsass_library='
2022-09-08T07:08:26.421587Z	gyp verb cli ]
2022-09-08T07:08:26.4217Z	gyp info using node-gyp@9.1.0
2022-09-08T07:08:26.421814Z	gyp info using node@14.16.1 | linux | x64
2022-09-08T07:08:26.421931Z	gyp verb command rebuild []
2022-09-08T07:08:26.42316Z	gyp verb command clean []
2022-09-08T07:08:26.437818Z	gyp verb clean removing "build" directory
2022-09-08T07:08:26.440663Z	gyp verb command configure []
2022-09-08T07:08:26.485843Z	gyp verb find Python Python is not set from command line or npm configuration
2022-09-08T07:08:26.48614Z	gyp verb find Python Python is not set from environment variable PYTHON
2022-09-08T07:08:26.486299Z	gyp verb find Python checking if "python3" can be used
2022-09-08T07:08:26.486462Z	gyp verb find Python - executing "python3" to get executable path
2022-09-08T07:08:26.571679Z	gyp verb find Python - executable path is "/usr/bin/python3"
2022-09-08T07:08:26.572091Z	gyp verb find Python - executing "/usr/bin/python3" to get version
2022-09-08T07:08:26.60546Z	gyp verb find Python - version is "3.5.2"
2022-09-08T07:08:26.609314Z	gyp verb find Python - version is 3.5.2 - should be >=3.6.0
2022-09-08T07:08:26.6096Z	gyp verb find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
2022-09-08T07:08:26.609967Z	gyp verb find Python checking if "python" can be used
2022-09-08T07:08:26.610231Z	gyp verb find Python - executing "python" to get executable path
2022-09-08T07:08:26.656205Z	gyp verb find Python - executable path is "/opt/buildhome/python2.7/bin/python"
2022-09-08T07:08:26.656522Z	gyp verb find Python - executing "/opt/buildhome/python2.7/bin/python" to get version
2022-09-08T07:08:26.678374Z	gyp verb find Python - version is "2.7.12"
2022-09-08T07:08:26.678789Z	gyp verb find Python - version is 2.7.12 - should be >=3.6.0
2022-09-08T07:08:26.679208Z	gyp verb find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
2022-09-08T07:08:26.679413Z	gyp ERR! find Python 
2022-09-08T07:08:26.679552Z	gyp ERR! find Python Python is not set from command line or npm configuration
2022-09-08T07:08:26.679702Z	gyp ERR! find Python Python is not set from environment variable PYTHON
2022-09-08T07:08:26.67982Z	gyp ERR! find Python checking if "python3" can be used
2022-09-08T07:08:26.679937Z	gyp ERR! find Python - executable path is "/usr/bin/python3"
2022-09-08T07:08:26.680057Z	gyp ERR! find Python - version is "3.5.2"
2022-09-08T07:08:26.680203Z	gyp ERR! find Python - version is 3.5.2 - should be >=3.6.0
2022-09-08T07:08:26.680418Z	gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
2022-09-08T07:08:26.680605Z	gyp ERR! find Python checking if "python" can be used
2022-09-08T07:08:26.680795Z	gyp ERR! find Python - executable path is "/opt/buildhome/python2.7/bin/python"
2022-09-08T07:08:26.680981Z	gyp ERR! find Python - version is "2.7.12"
2022-09-08T07:08:26.681112Z	gyp ERR! find Python - version is 2.7.12 - should be >=3.6.0
2022-09-08T07:08:26.681329Z	gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
2022-09-08T07:08:26.68151Z	gyp ERR! find Python 
2022-09-08T07:08:26.681633Z	gyp ERR! find Python **********************************************************
2022-09-08T07:08:26.681811Z	gyp ERR! find Python You need to install the latest version of Python.
2022-09-08T07:08:26.681935Z	gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
2022-09-08T07:08:26.682054Z	gyp ERR! find Python you can try one of the following options:
2022-09-08T07:08:26.682562Z	gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
2022-09-08T07:08:26.682774Z	gyp ERR! find Python   (accepted by both node-gyp and npm)
2022-09-08T07:08:26.682933Z	gyp ERR! find Python - Set the environment variable PYTHON
2022-09-08T07:08:26.683053Z	gyp ERR! find Python - Set the npm configuration variable python:
2022-09-08T07:08:26.683176Z	gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
2022-09-08T07:08:26.6833Z	gyp ERR! find Python For more information consult the documentation at:
2022-09-08T07:08:26.683411Z	gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
2022-09-08T07:08:26.683524Z	gyp ERR! find Python **********************************************************
2022-09-08T07:08:26.683637Z	gyp ERR! find Python 
2022-09-08T07:08:26.683754Z	gyp ERR! configure error 
2022-09-08T07:08:26.683861Z	gyp ERR! stack Error: Could not find any Python installation to use
2022-09-08T07:08:26.683967Z	gyp ERR! stack     at PythonFinder.fail (/opt/buildhome/repo/node_modules/node-gyp/lib/find-python.js:330:47)
2022-09-08T07:08:26.684086Z	gyp ERR! stack     at PythonFinder.runChecks (/opt/buildhome/repo/node_modules/node-gyp/lib/find-python.js:159:21)
2022-09-08T07:08:26.68421Z	gyp ERR! stack     at PythonFinder.<anonymous> (/opt/buildhome/repo/node_modules/node-gyp/lib/find-python.js:266:16)
2022-09-08T07:08:26.68435Z	gyp ERR! stack     at PythonFinder.execFileCallback (/opt/buildhome/repo/node_modules/node-gyp/lib/find-python.js:297:7)
2022-09-08T07:08:26.684472Z	gyp ERR! stack     at ChildProcess.exithandler (child_process.js:299:7)
2022-09-08T07:08:26.684581Z	gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
2022-09-08T07:08:26.684689Z	gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
2022-09-08T07:08:26.6848Z	gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
2022-09-08T07:08:26.684908Z	gyp ERR! System Linux 4.4.0
2022-09-08T07:08:26.685015Z	gyp ERR! command "/opt/buildhome/.nvm/versions/node/v14.16.1/bin/node" "/opt/buildhome/repo/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
2022-09-08T07:08:26.685124Z	gyp ERR! cwd /opt/buildhome/repo/node_modules/node-sass
2022-09-08T07:08:26.685264Z	gyp ERR! node -v v14.16.1
2022-09-08T07:08:26.685377Z	gyp ERR! node-gyp -v v9.1.0
2022-09-08T07:08:26.685498Z	gyp ERR! not ok 
2022-09-08T07:08:26.688258Z	Build failed with error code: 1
2022-09-08T07:08:28.039831Z	npm WARN notsup Unsupported engine for eslint@8.23.0: wanted: {"node":"^12.22.0 || ^14.17.0 || >=16.0.0"} (current: {"node":"14.16.1","npm":"6.14.12"})
2022-09-08T07:08:28.040195Z	npm WARN notsup Not compatible with your version of node/npm: eslint@8.23.0
2022-09-08T07:08:28.043646Z	npm WARN notsup Unsupported engine for jest-watch-typeahead@1.1.0: wanted: {"node":"^12.22.0 || ^14.17.0 || >=16.0.0"} (current: {"node":"14.16.1","npm":"6.14.12"})
2022-09-08T07:08:28.043901Z	npm WARN notsup Not compatible with your version of node/npm: jest-watch-typeahead@1.1.0
2022-09-08T07:08:28.049023Z	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^2.3.2 (node_modules/react-scripts/node_modules/fsevents):
2022-09-08T07:08:28.049398Z	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
2022-09-08T07:08:28.052848Z	npm WARN notsup Unsupported engine for @eslint/eslintrc@1.3.1: wanted: {"node":"^12.22.0 || ^14.17.0 || >=16.0.0"} (current: {"node":"14.16.1","npm":"6.14.12"})
2022-09-08T07:08:28.053156Z	npm WARN notsup Not compatible with your version of node/npm: @eslint/eslintrc@1.3.1
2022-09-08T07:08:28.056149Z	npm WARN notsup Unsupported engine for eslint-scope@7.1.1: wanted: {"node":"^12.22.0 || ^14.17.0 || >=16.0.0"} (current: {"node":"14.16.1","npm":"6.14.12"})
2022-09-08T07:08:28.056389Z	npm WARN notsup Not compatible with your version of node/npm: eslint-scope@7.1.1
2022-09-08T07:08:28.059425Z	npm WARN notsup Unsupported engine for eslint-visitor-keys@3.3.0: wanted: {"node":"^12.22.0 || ^14.17.0 || >=16.0.0"} (current: {"node":"14.16.1","npm":"6.14.12"})
2022-09-08T07:08:28.059703Z	npm WARN notsup Not compatible with your version of node/npm: eslint-visitor-keys@3.3.0
2022-09-08T07:08:28.062683Z	npm WARN notsup Unsupported engine for espree@9.4.0: wanted: {"node":"^12.22.0 || ^14.17.0 || >=16.0.0"} (current: {"node":"14.16.1","npm":"6.14.12"})
2022-09-08T07:08:28.062902Z	npm WARN notsup Not compatible with your version of node/npm: espree@9.4.0
2022-09-08T07:08:28.066122Z	npm WARN notsup Unsupported engine for @typescript-eslint/eslint-plugin@5.36.2: wanted: {"node":"^12.22.0 || ^14.17.0 || >=16.0.0"} (current: {"node":"14.16.1","npm":"6.14.12"})
2022-09-08T07:08:28.066361Z	npm WARN notsup Not compatible with your version of node/npm: @typescript-eslint/eslint-plugin@5.36.2
2022-09-08T07:08:28.069356Z	npm WARN notsup Unsupported engine for @typescript-eslint/parser@5.36.2: wanted: {"node":"^12.22.0 || ^14.17.0 || >=16.0.0"} (current: {"node":"14.16.1","npm":"6.14.12"})
2022-09-08T07:08:28.069636Z	npm WARN notsup Not compatible with your version of node/npm: @typescript-eslint/parser@5.36.2
2022-09-08T07:08:28.072987Z	npm WARN notsup Unsupported engine for eslint-plugin-testing-library@5.6.2: wanted: {"node":"^12.22.0 || ^14.17.0 || >=16.0.0","npm":">=6"} (current: {"node":"14.16.1","npm":"6.14.12"})
2022-09-08T07:08:28.073217Z	npm WARN notsup Not compatible with your version of node/npm: eslint-plugin-testing-library@5.6.2
2022-09-08T07:08:28.076425Z	npm WARN notsup Unsupported engine for @typescript-eslint/scope-manager@5.36.2: wanted: {"node":"^12.22.0 || ^14.17.0 || >=16.0.0"} (current: {"node":"14.16.1","npm":"6.14.12"})
2022-09-08T07:08:28.076649Z	npm WARN notsup Not compatible with your version of node/npm: @typescript-eslint/scope-manager@5.36.2
2022-09-08T07:08:28.079808Z	npm WARN notsup Unsupported engine for @typescript-eslint/type-utils@5.36.2: wanted: {"node":"^12.22.0 || ^14.17.0 || >=16.0.0"} (current: {"node":"14.16.1","npm":"6.14.12"})
2022-09-08T07:08:28.080035Z	npm WARN notsup Not compatible with your version of node/npm: @typescript-eslint/type-utils@5.36.2
2022-09-08T07:08:28.083229Z	npm WARN notsup Unsupported engine for @typescript-eslint/utils@5.36.2: wanted: {"node":"^12.22.0 || ^14.17.0 || >=16.0.0"} (current: {"node":"14.16.1","npm":"6.14.12"})
2022-09-08T07:08:28.083433Z	npm WARN notsup Not compatible with your version of node/npm: @typescript-eslint/utils@5.36.2
2022-09-08T07:08:28.086534Z	npm WARN notsup Unsupported engine for @typescript-eslint/visitor-keys@5.36.2: wanted: {"node":"^12.22.0 || ^14.17.0 || >=16.0.0"} (current: {"node":"14.16.1","npm":"6.14.12"})
2022-09-08T07:08:28.086809Z	npm WARN notsup Not compatible with your version of node/npm: @typescript-eslint/visitor-keys@5.36.2
2022-09-08T07:08:28.089781Z	npm WARN notsup Unsupported engine for @typescript-eslint/types@5.36.2: wanted: {"node":"^12.22.0 || ^14.17.0 || >=16.0.0"} (current: {"node":"14.16.1","npm":"6.14.12"})
2022-09-08T07:08:28.089984Z	npm WARN notsup Not compatible with your version of node/npm: @typescript-eslint/types@5.36.2
2022-09-08T07:08:28.093013Z	npm WARN notsup Unsupported engine for @typescript-eslint/typescript-estree@5.36.2: wanted: {"node":"^12.22.0 || ^14.17.0 || >=16.0.0"} (current: {"node":"14.16.1","npm":"6.14.12"})
2022-09-08T07:08:28.093238Z	npm WARN notsup Not compatible with your version of node/npm: @typescript-eslint/typescript-estree@5.36.2
2022-09-08T07:08:28.099983Z	npm WARN notsup Unsupported engine for @typescript-eslint/experimental-utils@5.36.2: wanted: {"node":"^12.22.0 || ^14.17.0 || >=16.0.0"} (current: {"node":"14.16.1","npm":"6.14.12"})
2022-09-08T07:08:28.100211Z	npm WARN notsup Not compatible with your version of node/npm: @typescript-eslint/experimental-utils@5.36.2
2022-09-08T07:08:28.106735Z	npm WARN react-native-get-random-values@1.8.0 requires a peer of react-native@>=0.56 but none is installed. You must install peer dependencies yourself.
2022-09-08T07:08:28.115768Z	npm WARN tsutils@3.21.0 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
2022-09-08T07:08:28.122241Z	npm WARN fork-ts-checker-webpack-plugin@6.5.2 requires a peer of typescript@>= 2.7 but none is installed. You must install peer dependencies yourself.
2022-09-08T07:08:28.128477Z	npm WARN @apideck/better-ajv-errors@0.3.6 requires a peer of ajv@>=8 but none is installed. You must install peer dependencies yourself.
2022-09-08T07:08:28.129374Z	
2022-09-08T07:08:28.149191Z	npm ERR! code ELIFECYCLE
2022-09-08T07:08:28.149716Z	npm ERR! errno 1
2022-09-08T07:08:28.15218Z	npm ERR! node-sass@7.0.2 postinstall: `node scripts/build.js`
2022-09-08T07:08:28.152395Z	npm ERR! Exit status 1
2022-09-08T07:08:28.152607Z	npm ERR! 
2022-09-08T07:08:28.152809Z	npm ERR! Failed at the node-sass@7.0.2 postinstall script.
2022-09-08T07:08:28.15301Z	npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2022-09-08T07:08:28.191817Z	
2022-09-08T07:08:28.192118Z	npm ERR! A complete log of this run can be found in:
2022-09-08T07:08:28.192308Z	npm ERR!     /opt/buildhome/.npm/_logs/2022-09-08T07_08_28_178Z-debug.log
2022-09-08T07:08:28.227712Z	Error during NPM install
2022-09-08T07:08:28.232243Z	Failed: build command exited with code: 1
2022-09-08T07:08:29.749037Z	Failed: an internal error occurred

```

**Comment by aryanisml** [comment]
Thread is already open - https://github.com/sass/node-sass/issues/3297

**Comment by xzyfer** [comment]
Interesting
```
2022-09-08T07:08:21.305383Z	> node-sass@7.0.2 install /opt/buildhome/repo/node_modules/node-sass
2022-09-08T07:08:21.306493Z	> node scripts/install.js
2022-09-08T07:08:21.306738Z	
2022-09-08T07:08:21.972444Z	Downloading binary from https://github.com/sass/node-sass/releases/download/v7.0.2/linux-x64-83_binding.node
2022-09-08T07:08:22.178351Z	Download complete
2022-09-08T07:08:22.178982Z	Binary saved to /opt/buildhome/repo/node_modules/node-sass/vendor/linux-x64-83/binding.node
2022-09-08T07:08:22.252295Z	Caching binary to /opt/buildhome/.npm/node-sass/7.0.2/linux-x64-83_binding.node
...
2022-09-08T07:08:25.790991Z	
2022-09-08T07:08:25.791341Z	> node-sass@7.0.2 postinstall /opt/buildhome/repo/node_modules/node-sass
2022-09-08T07:08:25.7915Z	> node scripts/build.js
2022-09-08T07:08:25.791619Z	
2022-09-08T07:08:26.068224Z	Binary found at /opt/buildhome/repo/node_modules/node-sass/vendor/linux-x64-83/binding.node
2022-09-08T07:08:26.068655Z	Testing binary
2022-09-08T07:08:26.284727Z	Binary has a problem: Error: /opt/buildhome/repo/node_modules/node-sass/vendor/linux-x64-83/binding.node: file too short
2022-09-08T07:08:26.285803Z	    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
2022-09-08T07:08:26.286056Z	    at Module.load (internal/modules/cjs/loader.js:928:32)
2022-09-08T07:08:26.286216Z	    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
2022-09-08T07:08:26.286359Z	    at Module.require (internal/modules/cjs/loader.js:952:19)
2022-09-08T07:08:26.28648Z	    at require (internal/modules/cjs/helpers.js:88:18)
2022-09-08T07:08:26.286594Z	    at module.exports (/opt/buildhome/repo/node_modules/node-sass/lib/binding.js:19:10)
2022-09-08T07:08:26.286703Z	    at Object.<anonymous> (/opt/buildhome/repo/node_modules/node-sass/lib/index.js:13:35)
2022-09-08T07:08:26.28681Z	    at Module._compile (internal/modules/cjs/loader.js:1063:30)
2022-09-08T07:08:26.286919Z	    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
2022-09-08T07:08:26.287028Z	    at Module.load (internal/modules/cjs/loader.js:928:32)
```

**Comment by Rafat97** [comment]
> Thread is already open - #3297

Currently, I used this version - 
Node version => `14.16.1`
NPM version  => `6.14.12`
node-sass version => `7.0.2`

**Comment by xzyfer** [comment]
Closing in favour if #3297
