### ISSUE TITLE
Binary problem sass 9.0.0

### ISSUE THREAD

**Issue by joni1087** [sass/node-sass#3400]
- npm: 10.4.0
- node: 21.4.0
- sass: 9.0.0
- Windows 11

Hi, 

I'm having problems  trying to compiled a project.

Binary has a problem: Error: ...............\node_modules\node-sass\vendor\win32-x64-120\binding.node is not a valid Win32 application.

\node_modules\node-sass\vendor\win32-x64-120\binding.node
npm ERR!     at Module._extensions..node (node:internal/modules/cjs/loader:1473:18)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:1207:32)
npm ERR!     at Module._load (node:internal/modules/cjs/loader:1023:12)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1235:19)
npm ERR!     at require (node:internal/modules/helpers:176:18)
npm ERR!     at module.exports (C:\Proyectos\Repositorios\ecommerce_simulator\node_modules\node-sass\lib\binding.js:19:10)
npm ERR!     at Object.<anonymous> (C:\Proyectos\Repositorios\ecommerce_simulator\node_modules\node-sass\lib\index.js:13:35)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1376:14)
npm ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:1207:32) {
npm ERR!   code: 'ERR_DLOPEN_FAILED'

This project is running fine in another computer.
I checked compatibility versions, but it's ok !

**Comment by joni1087** [comment]
I reinstalled Node and Python
