### ISSUE TITLE
Build failure on Windows

### ISSUE THREAD

**Issue by oliversalzburg** [sass/node-sass#476]
I can't really contribute anything to this report, other than the log:

``` bash

> node-sass@1.0.1 install p:\project\node_modules\node-sass
> node build.js

`win32-x64-v8-3.14` exists; testing

p:\project\node_modules\node-sass>node "c:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild 
Using overrides found in C:\Users\Oliver\.gyp\include.gypi
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
cl : Command line warning D9025: overriding '/GR-' with '/GR' [p:\project\node_modules\node-sass\build\binding.vcxproj]
cl : Command line warning D9025: overriding '/GR-' with '/GR' [p:\project\node_modules\node-sass\build\binding.vcxproj]
cl : Command line warning D9025: overriding '/GR-' with '/GR' [p:\project\node_modules\node-sass\build\binding.vcxproj]
  binding.cpp
cl : Command line warning D9025: overriding '/GR-' with '/GR' [p:\project\node_modules\node-sass\build\binding.vcxproj]
cl : Command line warning D9025: overriding '/GR-' with '/GR' [p:\project\node_modules\node-sass\build\binding.vcxproj]
  sass_context_wrapper.cpp
  ast.cpp
cl : Command line warning D9025: overriding '/GR-' with '/GR' [p:\project\node_modules\node-sass\build\binding.vcxproj]
  base64vlq.cpp
cl : Command line warning D9025: overriding '/GR-' with '/GR' [p:\project\node_modules\node-sass\build\binding.vcxproj]
cl : Command line warning D9025: overriding '/GR-' with '/GR' [p:\project\node_modules\node-sass\build\binding.vcxproj]
  bind.cpp
  constants.cpp
  context.cpp
p:\project\node_modules\node-sass\libsass\sass.h(4): fatal error C1083: Cannot open include file: 'stdbool.h': No such file or directory [p:\project\node_modules\node-sass\build\binding.vcxproj]
  contextualize.cpp
cl : Command line warning D9025: overriding '/GR-' with '/GR' [p:\project\node_modules\node-sass\build\binding.vcxproj]
  copy_c_str.cpp
  error_handling.cpp
  eval.cpp
p:\project\node_modules\node-sass\libsass\sass.h(4): fatal error C1083: Cannot open include file: 'stdbool.h': No such file or directory [p:\project\node_modules\node-sass\build\binding.vcxproj]
p:\project\node_modules\node-sass\libsass\sass.h(4): fatal error C1083: Cannot open include file: 'stdbool.h': No such file or directory [p:\project\node_modules\node-sass\build\binding.vcxproj]
  expand.cpp
  extend.cpp
p:\project\node_modules\node-sass\libsass\sass.h(4): fatal error C1083: Cannot open include file: 'stdbool.h': No such file or directory [p:\project\node_modules\node-sass\build\binding.vcxproj]
  file.cpp
p:\project\node_modules\node-sass\libsass\sass.h(4): fatal error C1083: Cannot open include file: 'stdbool.h': No such file or directory [p:\project\node_modules\node-sass\build\binding.vcxproj]
  functions.cpp
p:\project\node_modules\node-sass\libsass\sass.h(4): fatal error C1083: Cannot open include file: 'stdbool.h': No such file or directory [p:\project\node_modules\node-sass\build\binding.vcxproj]
  inspect.cpp
  node.cpp
  output_compressed.cpp
p:\project\node_modules\node-sass\libsass\sass.h(4): fatal error C1083: Cannot open include file: 'stdbool.h': No such file or directory [p:\project\node_modules\node-sass\build\binding.vcxproj]
  output_nested.cpp
p:\project\node_modules\node-sass\libsass\sass.h(4): fatal error C1083: Cannot open include file: 'stdbool.h': No such file or directory [p:\project\node_modules\node-sass\build\binding.vcxproj]
  parser.cpp
p:\project\node_modules\node-sass\libsass\sass.h(4): fatal error C1083: Cannot open include file: 'stdbool.h': No such file or directory [p:\project\node_modules\node-sass\build\binding.vcxproj]
  prelexer.cpp
p:\project\node_modules\node-sass\libsass\sass.h(4): fatal error C1083: Cannot open include file: 'stdbool.h': No such file or directory [p:\project\node_modules\node-sass\build\binding.vcxproj]
  remove_placeholders.cpp
p:\project\node_modules\node-sass\libsass\sass.h(4): fatal error C1083: Cannot open include file: 'stdbool.h': No such file or directory [p:\project\node_modules\node-sass\build\binding.vcxproj]
  sass.cpp
p:\project\node_modules\node-sass\libsass\sass.h(4): fatal error C1083: Cannot open include file: 'stdbool.h': No such file or directory [p:\project\node_modules\node-sass\build\binding.vcxproj]
  sass2scss.cpp
p:\project\node_modules\node-sass\libsass\sass.h(4): fatal error C1083: Cannot open include file: 'stdbool.h': No such file or directory [p:\project\node_modules\node-sass\build\binding.vcxproj]
p:\project\node_modules\node-sass\node_modules\nan\nan.h(1221): warning C4267: 'argument' : conversion from 'size_t' to 'int', possible loss of data [p:\project\node_modules\node-sass\build\binding.vcxproj]
  sass_interface.cpp
p:\project\node_modules\node-sass\node_modules\nan\nan.h(1247): warning C4267: 'argument' : conversion from 'size_t' to 'int', possible loss of data [p:\project\node_modules\node-sass\build\binding.vcxproj]
p:\project\node_modules\node-sass\libsass\sass.h(4): fatal error C1083: Cannot open include file: 'stdbool.h': No such file or directory [p:\project\node_modules\node-sass\build\binding.vcxproj]
  sass_util.cpp
p:\project\node_modules\node-sass\libsass\sass.h(4): fatal error C1083: Cannot open include file: 'stdbool.h': No such file or directory [p:\project\node_modules\node-sass\build\binding.vcxproj]
  source_map.cpp
..\libsass\prelexer.cpp(65): error C2440: 'specialization' : cannot convert from 'char' to 'const char *const ' [p:\project\node_modules\node-sass\build\binding.vcxproj]
          Conversion from integral type to pointer type requires reinterpret_cast, C-style cast or function-style cast
..\libsass\prelexer.cpp(65): error C2973: 'Sass::Prelexer::exactly' : invalid template argument 'char' [p:\project\node_modules\node-sass\build\binding.vcxproj]
          p:\project\node_modules\node-sass\libsass\prelexer.hpp(17) : see declaration of 'Sass::Prelexer::exactly'
..\libsass\prelexer.cpp(65): error C2563: mismatch in formal parameter list [p:\project\node_modules\node-sass\build\binding.vcxproj]
..\libsass\prelexer.cpp(65): error C2440: 'specialization' : cannot convert from 'char' to 'const char *const ' [p:\project\node_modules\node-sass\build\binding.vcxproj]
          Conversion from integral type to pointer type requires reinterpret_cast, C-style cast or function-style cast
..\libsass\prelexer.cpp(65): error C2973: 'Sass::Prelexer::exactly' : invalid template argument 'char' [p:\project\node_modules\node-sass\build\binding.vcxproj]
          p:\project\node_modules\node-sass\libsass\prelexer.hpp(17) : see declaration of 'Sass::Prelexer::exactly'
..\libsass\prelexer.cpp(65): error C2563: mismatch in formal parameter list [p:\project\node_modules\node-sass\build\binding.vcxproj]
..\libsass\prelexer.cpp(65): error C2563: mismatch in formal parameter list [p:\project\node_modules\node-sass\build\binding.vcxproj]
..\libsass\prelexer.cpp(65): error C2563: mismatch in formal parameter list [p:\project\node_modules\node-sass\build\binding.vcxproj]
..\libsass\prelexer.cpp(65): error C2563: mismatch in formal parameter list [p:\project\node_modules\node-sass\build\binding.vcxproj]
..\libsass\prelexer.cpp(65): error C2563: mismatch in formal parameter list [p:\project\node_modules\node-sass\build\binding.vcxproj]
..\libsass\prelexer.cpp(65): error C2563: mismatch in formal parameter list [p:\project\node_modules\node-sass\build\binding.vcxproj]
..\libsass\prelexer.cpp(65): error C2563: mismatch in formal parameter list [p:\project\node_modules\node-sass\build\binding.vcxproj]
..\libsass\prelexer.cpp(65): error C2563: mismatch in formal parameter list [p:\project\node_modules\node-sass\build\binding.vcxproj]
..\libsass\prelexer.cpp(65): error C2563: mismatch in formal parameter list [p:\project\node_modules\node-sass\build\binding.vcxproj]
..\libsass\prelexer.cpp(65): error C2563: mismatch in formal parameter list [p:\project\node_modules\node-sass\build\binding.vcxproj]
..\libsass\prelexer.cpp(65): error C2563: mismatch in formal parameter list [p:\project\node_modules\node-sass\build\binding.vcxproj]
..\libsass\prelexer.cpp(65): error C2563: mismatch in formal parameter list [p:\project\node_modules\node-sass\build\binding.vcxproj]
..\libsass\prelexer.cpp(65): error C2440: 'specialization' : cannot convert from 'overloaded-function' to 'const Sass::Prelexer::prelexer' [p:\project\node_modules\node-sass\build\binding.vcxproj]
          None of the functions with this name in scope match the target type
..\libsass\prelexer.cpp(65): error C2973: 'Sass::Prelexer::sequence' : invalid template argument 'overloaded-function' [p:\project\node_modules\node-sass\build\binding.vcxproj]
          p:\project\node_modules\node-sass\libsass\prelexer.hpp(199) : see declaration of 'Sass::Prelexer::sequence'
..\libsass\prelexer.cpp(65): error C2440: 'specialization' : cannot convert from 'overloaded-function' to 'const Sass::Prelexer::prelexer' [p:\project\node_modules\node-sass\build\binding.vcxproj]
          None of the functions with this name in scope match the target type
..\libsass\prelexer.cpp(65): error C2973: 'Sass::Prelexer::sequence' : invalid template argument 'overloaded-function' [p:\project\node_modules\node-sass\build\binding.vcxproj]
          p:\project\node_modules\node-sass\libsass\prelexer.hpp(199) : see declaration of 'Sass::Prelexer::sequence'
..\libsass\prelexer.cpp(65): error C2563: mismatch in formal parameter list [p:\project\node_modules\node-sass\build\binding.vcxproj]
..\libsass\prelexer.cpp(65): error C2440: 'specialization' : cannot convert from 'char' to 'const char *const ' [p:\project\node_modules\node-sass\build\binding.vcxproj]
          Conversion from integral type to pointer type requires reinterpret_cast, C-style cast or function-style cast
..\libsass\prelexer.cpp(65): error C2973: 'Sass::Prelexer::exactly' : invalid template argument 'char' [p:\project\node_modules\node-sass\build\binding.vcxproj]
          p:\project\node_modules\node-sass\libsass\prelexer.hpp(17) : see declaration of 'Sass::Prelexer::exactly'
..\libsass\prelexer.cpp(65): error C2563: mismatch in formal parameter list [p:\project\node_modules\node-sass\build\binding.vcxproj]
..\libsass\prelexer.cpp(65): error C2563: mismatch in formal parameter list [p:\project\node_modules\node-sass\build\binding.vcxproj]
..\libsass\prelexer.cpp(65): error C2563: mismatch in formal parameter list [p:\project\node_modules\node-sass\build\binding.vcxproj]
..\libsass\prelexer.cpp(65): error C2563: mismatch in formal parameter list [p:\project\node_modules\node-sass\build\binding.vcxproj]
..\libsass\prelexer.cpp(65): error C2563: mismatch in formal parameter list [p:\project\node_modules\node-sass\build\binding.vcxproj]
..\libsass\prelexer.cpp(65): error C2563: mismatch in formal parameter list [p:\project\node_modules\node-sass\build\binding.vcxproj]
..\libsass\prelexer.cpp(65): error C2563: mismatch in formal parameter list [p:\project\node_modules\node-sass\build\binding.vcxproj]
..\libsass\prelexer.cpp(65): error C2563: mismatch in formal parameter list [p:\project\node_modules\node-sass\build\binding.vcxproj]
..\libsass\prelexer.cpp(65): error C2563: mismatch in formal parameter list [p:\project\node_modules\node-sass\build\binding.vcxproj]
..\libsass\prelexer.cpp(65): error C2563: mismatch in formal parameter list [p:\project\node_modules\node-sass\build\binding.vcxproj]
..\libsass\prelexer.cpp(65): error C2563: mismatch in formal parameter list [p:\project\node_modules\node-sass\build\binding.vcxproj]
..\libsass\prelexer.cpp(65): error C2563: mismatch in formal parameter list [p:\project\node_modules\node-sass\build\binding.vcxproj]
..\libsass\prelexer.cpp(65): error C2563: mismatch in formal parameter list [p:\project\node_modules\node-sass\build\binding.vcxproj]
..\libsass\prelexer.cpp(65): error C2440: 'specialization' : cannot convert from 'overloaded-function' to 'const Sass::Prelexer::prelexer' [p:\project\node_modules\node-sass\build\binding.vcxproj]
          None of the functions with this name in scope match the target type
..\libsass\prelexer.cpp(65): error C2973: 'Sass::Prelexer::alternatives' : invalid template argument 'overloaded-function' [p:\project\node_modules\node-sass\build\binding.vcxproj]
          p:\project\node_modules\node-sass\libsass\prelexer.hpp(142) : see declaration of 'Sass::Prelexer::alternatives'
..\libsass\prelexer.cpp(65): error C2440: 'specialization' : cannot convert from 'overloaded-function' to 'const Sass::Prelexer::prelexer' [p:\project\node_modules\node-sass\build\binding.vcxproj]
          None of the functions with this name in scope match the target type
..\libsass\prelexer.cpp(65): error C2973: 'Sass::Prelexer::alternatives' : invalid template argument 'overloaded-function' [p:\project\node_modules\node-sass\build\binding.vcxproj]
          p:\project\node_modules\node-sass\libsass\prelexer.hpp(142) : see declaration of 'Sass::Prelexer::alternatives'
..\libsass\prelexer.cpp(65): error C2440: 'specialization' : cannot convert from 'overloaded-function' to 'const Sass::Prelexer::prelexer' [p:\project\node_modules\node-sass\build\binding.vcxproj]
          None of the functions with this name in scope match the target type
..\libsass\prelexer.cpp(65): error C2973: 'Sass::Prelexer::alternatives' : invalid template argument 'overloaded-function' [p:\project\node_modules\node-sass\build\binding.vcxproj]
          p:\project\node_modules\node-sass\libsass\prelexer.hpp(142) : see declaration of 'Sass::Prelexer::alternatives'
..\libsass\prelexer.cpp(74): error C2440: 'specialization' : cannot convert from 'char' to 'const char *const ' [p:\project\node_modules\node-sass\build\binding.vcxproj]
          Conversion from integral type to pointer type requires reinterpret_cast, C-style cast or function-style cast
..\libsass\prelexer.cpp(74): error C2973: 'Sass::Prelexer::exactly' : invalid template argument 'char' [p:\project\node_modules\node-sass\build\binding.vcxproj]
          p:\project\node_modules\node-sass\libsass\prelexer.hpp(17) : see declaration of 'Sass::Prelexer::exactly'
..\libsass\prelexer.cpp(74): error C2563: mismatch in formal parameter list [p:\project\node_modules\node-sass\build\binding.vcxproj]
..\libsass\prelexer.cpp(74): error C2440: 'specialization' : cannot convert from 'char' to 'const char *const ' [p:\project\node_modules\node-sass\build\binding.vcxproj]
          Conversion from integral type to pointer type requires reinterpret_cast, C-style cast or function-style cast
..\libsass\prelexer.cpp(74): error C2973: 'Sass::Prelexer::exactly' : invalid template argument 'char' [p:\project\node_modules\node-sass\build\binding.vcxproj]
          p:\project\node_modules\node-sass\libsass\prelexer.hpp(17) : see declaration of 'Sass::Prelexer::exactly'
..\libsass\prelexer.cpp(74): error C2563: mismatch in formal parameter list [p:\project\node_modules\node-sass\build\binding.vcxproj]
..\libsass\prelexer.cpp(74): error C2563: mismatch in formal parameter list [p:\project\node_modules\node-sass\build\binding.vcxproj]
..\libsass\prelexer.cpp(74): error C2563: mismatch in formal parameter list [p:\project\node_modules\node-sass\build\binding.vcxproj]
..\libsass\prelexer.cpp(74): error C2563: mismatch in formal parameter list [p:\project\node_modules\node-sass\build\binding.vcxproj]
..\libsass\prelexer.cpp(74): error C2563: mismatch in formal parameter list [p:\project\node_modules\node-sass\build\binding.vcxproj]
..\libsass\prelexer.cpp(74): error C2563: mismatch in formal parameter list [p:\project\node_modules\node-sass\build\binding.vcxproj]
..\libsass\prelexer.cpp(74): error C2563: mismatch in formal parameter list [p:\project\node_modules\node-sass\build\binding.vcxproj]
..\libsass\prelexer.cpp(74): error C2563: mismatch in formal parameter list [p:\project\node_modules\node-sass\build\binding.vcxproj]
..\libsass\prelexer.cpp(74): error C2563: mismatch in formal parameter list [p:\project\node_modules\node-sass\build\binding.vcxproj]
..\libsass\prelexer.cpp(74): error C2563: mismatch in formal parameter list [p:\project\node_modules\node-sass\build\binding.vcxproj]
..\libsass\prelexer.cpp(74): error C2563: mismatch in formal parameter list [p:\project\node_modules\node-sass\build\binding.vcxproj]
..\libsass\prelexer.cpp(74): error C2440: 'specialization' : cannot convert from 'overloaded-function' to 'const Sass::Prelexer::prelexer' [p:\project\node_modules\node-sass\build\binding.vcxproj]
          None of the functions with this name in scope match the target type
..\libsass\prelexer.cpp(74): error C2973: 'Sass::Prelexer::alternatives' : invalid template argument 'overloaded-function' [p:\project\node_modules\node-sass\build\binding.vcxproj]
          p:\project\node_modules\node-sass\libsass\prelexer.hpp(134) : see declaration of 'Sass::Prelexer::alternatives'
..\libsass\prelexer.cpp(74): error C2440: 'specialization' : cannot convert from 'overloaded-function' to 'const Sass::Prelexer::prelexer' [p:\project\node_modules\node-sass\build\binding.vcxproj]
          None of the functions with this name in scope match the target type
..\libsass\prelexer.cpp(74): error C2973: 'Sass::Prelexer::alternatives' : invalid template argument 'overloaded-function' [p:\project\node_modules\node-sass\build\binding.vcxproj]
          p:\project\node_modules\node-sass\libsass\prelexer.hpp(134) : see declaration of 'Sass::Prelexer::alternatives'
..\libsass\prelexer.cpp(82): error C2440: 'specialization' : cannot convert from 'char' to 'const char *const ' [p:\project\node_modules\node-sass\build\binding.vcxproj]
          Conversion from integral type to pointer type requires reinterpret_cast, C-style cast or function-style cast
..\libsass\prelexer.cpp(82): error C2973: 'Sass::Prelexer::exactly' : invalid template argument 'char' [p:\project\node_modules\node-sass\build\binding.vcxproj]
          p:\project\node_modules\node-sass\libsass\prelexer.hpp(17) : see declaration of 'Sass::Prelexer::exactly'
..\libsass\prelexer.cpp(82): error C2563: mismatch in formal parameter list [p:\project\node_modules\node-sass\build\binding.vcxproj]
..\libsass\prelexer.cpp(82): error C2563: mismatch in formal parameter list [p:\project\node_modules\node-sass\build\binding.vcxproj]
..\libsass\prelexer.cpp(82): error C2563: mismatch in formal parameter list [p:\project\node_modules\node-sass\build\binding.vcxproj]
..\libsass\prelexer.cpp(82): error C2563: mismatch in formal parameter list [p:\project\node_modules\node-sass\build\binding.vcxproj]
..\libsass\prelexer.cpp(82): error C2563: mismatch in formal parameter list [p:\project\node_modules\node-sass\build\binding.vcxproj]
..\libsass\prelexer.cpp(82): error C2563: mismatch in formal parameter list [p:\project\node_modules\node-sass\build\binding.vcxproj]
..\libsass\prelexer.cpp(82): error C2440: 'specialization' : cannot convert from 'overloaded-function' to 'const Sass::Prelexer::prelexer' [p:\project\node_modules\node-sass\build\binding.vcxproj]
          None of the functions with this name in scope match the target type
..\libsass\prelexer.cpp(82): error C2973: 'Sass::Prelexer::sequence' : invalid template argument 'overloaded-function' [p:\project\node_modules\node-sass\build\binding.vcxproj]
          p:\project\node_modules\node-sass\libsass\prelexer.hpp(199) : see declaration of 'Sass::Prelexer::sequence'
..\libsass\prelexer.cpp(87): error C2440: 'specialization' : cannot convert from 'char' to 'const char *const ' [p:\project\node_modules\node-sass\build\binding.vcxproj]
          Conversion from integral type to pointer type requires reinterpret_cast, C-style cast or function-style cast
..\libsass\prelexer.cpp(87): error C2973: 'Sass::Prelexer::exactly' : invalid template argument 'char' [p:\project\node_modules\node-sass\build\binding.vcxproj]
          p:\project\node_modules\node-sass\libsass\prelexer.hpp(17) : see declaration of 'Sass::Prelexer::exactly'
..\libsass\prelexer.cpp(87): error C2668: 'Sass::Prelexer::exactly' : ambiguous call to overloaded function [p:\project\node_modules\node-sass\build\binding.vcxproj]
          p:\project\node_modules\node-sass\libsass\prelexer.hpp(17): could be 'const char *Sass::Prelexer::exactly<34>(const char *)'
          p:\project\node_modules\node-sass\libsass\prelexer.hpp(11): or       'const char *Sass::Prelexer::exactly<34>(const char *)'
          while trying to match the argument list '(const char *)'
..\libsass\prelexer.cpp(96): error C2668: 'Sass::Prelexer::exactly' : ambiguous call to overloaded function [p:\project\node_modules\node-sass\build\binding.vcxproj]
          p:\project\node_modules\node-sass\libsass\prelexer.hpp(17): could be 'const char *Sass::Prelexer::exactly<34>(const char *)'
          p:\project\node_modules\node-sass\libsass\prelexer.hpp(11): or       'const char *Sass::Prelexer::exactly<34>(const char *)'
          while trying to match the argument list '(const char *)'
..\libsass\prelexer.cpp(106): error C2440: 'specialization' : cannot convert from 'char' to 'const char *const ' [p:\project\node_modules\node-sass\build\binding.vcxproj]
          Conversion from integral type to pointer type requires reinterpret_cast, C-style cast or function-style cast
..\libsass\prelexer.cpp(106): error C2973: 'Sass::Prelexer::exactly' : invalid template argument 'char' [p:\project\node_modules\node-sass\build\binding.vcxproj]
          p:\project\node_modules\node-sass\libsass\prelexer.hpp(17) : see declaration of 'Sass::Prelexer::exactly'
..\libsass\prelexer.cpp(106): error C2668: 'Sass::Prelexer::exactly' : ambiguous call to overloaded function [p:\project\node_modules\node-sass\build\binding.vcxproj]
          p:\project\node_modules\node-sass\libsass\prelexer.hpp(17): could be 'const char *Sass::Prelexer::exactly<39>(const char *)'
          p:\project\node_modules\node-sass\libsass\prelexer.hpp(11): or       'const char *Sass::Prelexer::exactly<39>(const char *)'
          while trying to match the argument list '(const char *)'
..\libsass\prelexer.cpp(115): error C2668: 'Sass::Prelexer::exactly' : ambiguous call to overloaded function [p:\project\node_modules\node-sass\build\binding.vcxproj]
          p:\project\node_modules\node-sass\libsass\prelexer.hpp(17): could be 'const char *Sass::Prelexer::exactly<39>(const char *)'
          p:\project\node_modules\node-sass\libsass\prelexer.hpp(11): or       'const char *Sass::Prelexer::exactly<39>(const char *)'
          while trying to match the argument list '(const char *)'
..\libsass\prelexer.cpp(145): error C2563: mismatch in formal parameter list [p:\project\node_modules\node-sass\build\binding.vcxproj]
..\libsass\prelexer.cpp(145): error C2563: mismatch in formal parameter list [p:\project\node_modules\node-sass\build\binding.vcxproj]
..\libsass\prelexer.cpp(145): error C2563: mismatch in formal parameter list [p:\project\node_modules\node-sass\build\binding.vcxproj]
..\libsass\prelexer.cpp(145): error C2563: mismatch in formal parameter list [p:\project\node_modules\node-sass\build\binding.vcxproj]
..\libsass\prelexer.cpp(145): error C2563: mismatch in formal parameter list [p:\project\node_modules\node-sass\build\binding.vcxproj]
..\libsass\prelexer.cpp(145): error C2563: mismatch in formal parameter list [p:\project\node_modules\node-sass\build\binding.vcxproj]
..\libsass\prelexer.cpp(155): error C2440: 'specialization' : cannot convert from 'char' to 'const char *const ' [p:\project\node_modules\node-sass\build\binding.vcxproj]
          Conversion from integral type to pointer type requires reinterpret_cast, C-style cast or function-style cast
..\libsass\prelexer.cpp(155): error C2973: 'Sass::Prelexer::exactly' : invalid template argument 'char' [p:\project\node_modules\node-sass\build\binding.vcxproj]
          p:\project\node_modules\node-sass\libsass\prelexer.hpp(17) : see declaration of 'Sass::Prelexer::exactly'
..\libsass\prelexer.cpp(155): error C2563: mismatch in formal parameter list [p:\project\node_modules\node-sass\build\binding.vcxproj]
..\libsass\prelexer.cpp(155): error C2440: 'specialization' : cannot convert from 'overloaded-function' to 'const Sass::Prelexer::prelexer' [p:\project\node_modules\node-sass\build\binding.vcxproj]
          None of the functions with this name in scope match the target type
..\libsass\prelexer.cpp(155): error C2973: 'Sass::Prelexer::optional' : invalid template argument 'overloaded-function' [p:\project\node_modules\node-sass\build\binding.vcxproj]
          p:\project\node_modules\node-sass\libsass\prelexer.hpp(262) : see declaration of 'Sass::Prelexer::optional'
..\libsass\prelexer.cpp(155): error C2440: 'specialization' : cannot convert from 'char' to 'const char *const ' [p:\project\node_modules\node-sass\build\binding.vcxproj]
          Conversion from integral type to pointer type requires reinterpret_cast, C-style cast or function-style cast
..\libsass\prelexer.cpp(155): error C2973: 'Sass::Prelexer::exactly' : invalid template argument 'char' [p:\project\node_modules\node-sass\build\binding.vcxproj]
          p:\project\node_modules\node-sass\libsass\prelexer.hpp(17) : see declaration of 'Sass::Prelexer::exactly'
..\libsass\prelexer.cpp(155): error C2563: mismatch in formal parameter list [p:\project\node_modules\node-sass\build\binding.vcxproj]
..\libsass\prelexer.cpp(155): error C2563: mismatch in formal parameter list [p:\project\node_modules\node-sass\build\binding.vcxproj]
..\libsass\prelexer.cpp(155): error C2563: mismatch in formal parameter list [p:\project\node_modules\node-sass\build\binding.vcxproj]
..\libsass\prelexer.cpp(155): error C2563: mismatch in formal parameter list [p:\project\node_modules\node-sass\build\binding.vcxproj]
..\libsass\prelexer.cpp(155): error C2563: mismatch in formal parameter list [p:\project\node_modules\node-sass\build\binding.vcxproj]
..\libsass\prelexer.cpp(155): error C2563: mismatch in formal parameter list [p:\project\node_modules\node-sass\build\binding.vcxproj]
..\libsass\prelexer.cpp(155): error C2440: 'specialization' : cannot convert from 'overloaded-function' to 'const Sass::Prelexer::prelexer' [p:\project\node_modules\node-sass\build\binding.vcxproj]
..\libsass\prelexer.cpp(155): fatal error C1003: error count exceeds 100; stopping compilation [p:\project\node_modules\node-sass\build\binding.vcxproj]
  to_c.cpp
p:\project\node_modules\node-sass\libsass\sass.h(4): fatal error C1083: Cannot open include file: 'stdbool.h': No such file or directory [p:\project\node_modules\node-sass\build\binding.vcxproj]
  to_string.cpp
p:\project\node_modules\node-sass\libsass\sass.h(4): fatal error C1083: Cannot open include file: 'stdbool.h': No such file or directory [p:\project\node_modules\node-sass\build\binding.vcxproj]
  units.cpp
p:\project\node_modules\node-sass\libsass\sass.h(4): fatal error C1083: Cannot open include file: 'stdbool.h': No such file or directory [p:\project\node_modules\node-sass\build\binding.vcxproj]
  utf8_string.cpp
p:\project\node_modules\node-sass\libsass\sass.h(4): fatal error C1083: Cannot open include file: 'stdbool.h': No such file or directory [p:\project\node_modules\node-sass\build\binding.vcxproj]
  util.cpp
p:\project\node_modules\node-sass\libsass\sass.h(4): fatal error C1083: Cannot open include file: 'stdbool.h': No such file or directory [p:\project\node_modules\node-sass\build\binding.vcxproj]
p:\project\node_modules\node-sass\libsass\sass.h(4): fatal error C1083: Cannot open include file: 'stdbool.h': No such file or directory [p:\project\node_modules\node-sass\build\binding.vcxproj]
p:\project\node_modules\node-sass\libsass\sass.h(4): fatal error C1083: Cannot open include file: 'stdbool.h': No such file or directory [p:\project\node_modules\node-sass\build\binding.vcxproj]
p:\project\node_modules\node-sass\libsass\sass.h(4): fatal error C1083: Cannot open include file: 'stdbool.h': No such file or directory [p:\project\node_modules\node-sass\build\binding.vcxproj]
..\libsass\utf8_string.cpp(50): warning C4267: 'initializing' : conversion from 'size_t' to 'long', possible loss of data [p:\project\node_modules\node-sass\build\binding.vcxproj]
p:\project\node_modules\node-sass\libsass\sass.h(4): fatal error C1083: Cannot open include file: 'stdbool.h': No such file or directory [p:\project\node_modules\node-sass\build\binding.vcxproj]
gyp ERR! build error 
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (c:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "c:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd p:\project\node_modules\node-sass
gyp ERR! node -v v0.10.32
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 
Build failed

npm ERR! node-sass@1.0.1 install: `node build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@1.0.1 install script.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-sass"
npm ERR! cwd p:\project
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

**Comment by ramankarman** [comment]
I also found helpful [this comment](https://github.com/nwjs/nw-gyp/issues/63#issuecomment-77660581). After installing Python 2.7 and Visual C++ Build Tools I deleted node_modules folder, opened CMD from Administrator and ran `npm install --msvs_version=2015`. Aaand it installed successfully!

[This link](https://github.com/nodejs/node-gyp#on-windows) helped me to install Python and VS C++ build tools.
