### ISSUE TITLE
Installing 1.2.1 error on debian wheezy (Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found)

### ISSUE THREAD

**Issue by nsams** [sass/node-sass#517]
```
$ npm install node-sass
\
> gaze@0.6.4 install /home/niko/sasstest2/node_modules/node-sass/node_modules/gaze
> node-gyp rebuild

make: Entering directory `/home/niko/sasstest2/node_modules/node-sass/node_modules/gaze/build'
CXX(target) Release/obj.target/pathwatcher/src/main.o
CXX(target) Release/obj.target/pathwatcher/src/common.o
CXX(target) Release/obj.target/pathwatcher/src/handle_map.o
../src/handle_map.cc: In member function ‘bool HandleMap::Erase(WatcherHandle)’:
../src/handle_map.cc:41:26: warning: ‘void NanDispose(v8::Persistent<S>&) [with T = v8::Value]’ is deprecated (declared at ../node_modules/nan/nan.h:612) [-Wdeprecated-declarations]
../src/handle_map.cc: In member function ‘void HandleMap::Clear()’:
../src/handle_map.cc:48:28: warning: ‘void NanDispose(v8::Persistent<S>&) [with T = v8::Value]’ is deprecated (declared at ../node_modules/nan/nan.h:612) [-Wdeprecated-declarations]
CXX(target) Release/obj.target/pathwatcher/src/pathwatcher_linux.o
SOLINK_MODULE(target) Release/obj.target/pathwatcher.node
SOLINK_MODULE(target) Release/obj.target/pathwatcher.node: Finished
COPY Release/pathwatcher.node
make: Leaving directory `/home/niko/sasstest2/node_modules/node-sass/node_modules/gaze/build'

> node-sass@1.2.1 install /home/niko/sasstest2/node_modules/node-sass
> node scripts/install.js

    fetch : https://raw.githubusercontent.com/sass/node-sass-binaries/v1.2.1/linux-x64-v8-3.14/binding.node
progress : [====================] 100% 0.0s

Binary installed in /home/niko/sasstest2/node_modules/node-sass/vendor/linux-x64-v8-3.14

> node-sass@1.2.1 postinstall /home/niko/sasstest2/node_modules/node-sass
> node scripts/build.js

`linux-x64-v8-3.14` exists; testing

module.js:356
Module._extensions[extension](this, filename);
                            ^
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /home/niko/sasstest2/node_modules/node-sass/vendor/linux-x64-v8-3.14/binding.node)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/niko/sasstest2/node_modules/node-sass/lib/index.js:182:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
npm ERR! Linux 3.2.0-4-amd64
npm ERR! argv "node" "/usr/bin/npm" "install" "node-sass"
npm ERR! node v0.10.29
npm ERR! npm  v2.1.6
npm ERR! code ELIFECYCLE

npm ERR! node-sass@1.2.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the node-sass@1.2.1 postinstall script.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.
npm ERR! Linux 3.2.0-4-amd64
npm ERR! argv "node" "/usr/bin/npm" "install" "node-sass"
npm ERR! node v0.10.29
npm ERR! npm  v2.1.6

npm ERR! Uncaught, unspecified "error" event.
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/niko/sasstest2/npm-debug.log
```

Works correctly: node-sass@1.1.4

```
$ npm --version
2.1.6
$ node --version
v0.10.29
$ gcc --version
gcc (Debian 4.7.2-5) 4.7.2
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 7.7 (wheezy)
Release:        7.7
Codename:       wheezy
```

**Comment by ghasolutions** [comment]
I see this is closed and its not my intent to re-open it.  Rather I wanted to share that the above thread was very helpful in allowing me to get grunt-sass installed on CentOS6.5 using Vagrant Chef.  This is the sequence of commands that worked for me:

    # Get the CERN labs dev toolset which contains gcc 4.8
    wget -O /etc/yum.repos.d/slc6-devtoolset.repo http://linuxsoft.cern.ch/cern/devtoolset/slc6-devtoolset.repo

    # import the CERN PGP key
    rpm --import http://ftp.mirrorservice.org/sites/ftp.scientificlinux.org/linux/scientific/51/i386/RPM-GPG-KEYs/RPM-GPG-KEY-cern

    # install the various gcc libs
    yum install devtoolset-2-gcc.x86_64
    yum install devtoolset-2-binutils.x86_64
    yum install devtoolset-2-gcc-c++

    # force npm to use the 4.8 libs
    SKIP_SASS_BINARY_DOWNLOAD_FOR_CI=1 CC=/opt/rh/devtoolset-2/root/usr/bin/gcc CXX=/opt/rh/devtoolset-2/root/usr/bin/g++ npm install grunt-sass

**Comment by ralberts** [comment]
Thanks so much @am11!!! I just came across this error today and amazed you fixed it just 14 days ago!  Woohoo!  Doing "npm install node-sass@2.0.0-beta" worked for me on CentOS 6.5 / GCC 4.4.7.

**Comment by saper** [comment]
Got 

````
Error: /usr/lib/libstdc++.so.6: version GLIBCXX_3.4.18 required by /usr/local/lib/node_modules/node-sass/vendor/freebsd-ia32-14/binding.node not found
````

today when testing my fresh i386 binaries for FreeBSD. Here's why:

- the binding (and the sass/libsass, too) were compiled with non-system `g++48` is linked to the `libstdc++.so.6` shipped with `g++48`:

````
# ldd /usr/local/lib/node_modules/node-sass/vendor/freebsd-ia32-14/binding.node
/usr/local/lib/node_modules/node-sass/vendor/freebsd-ia32-14/binding.node:
        libstdc++.so.6 => /usr/local/lib/gcc48/libstdc++.so.6 (0x285b2000)
        libm.so.5 => /lib/libm.so.5 (0x281ad000)
        libgcc_s.so.1 => /usr/local/lib/gcc48/libgcc_s.so.1 (0x281c7000)
        libthr.so.3 => /lib/libthr.so.3 (0x281e3000)
        libc.so.7 => /lib/libc.so.7 (0x28091000)
````

However, this runtime path information seems to be not used when `node` `dlopen()`s the binding:
and tries to use system's (outdated) `/usr/lib/libstdc++.so.6` instead of compiler's `/usr/local/lib/gcc48/libstdc++.so.6`.

The reason why things start working after some system upgrade is that the system probably is getting an upgraded `libstdc++` library.

Will try to investigate whether we can influence runtime linker better.
