### ISSUE TITLE
node-sass@1.2.3 postinstall failing on Ubuntu 12.04.5

### ISSUE THREAD

**Issue by ixtli** [sass/node-sass#550]
The following is the relevant section of the failure:

```
jenkins@jenkins:XXX$ npm install node-sass
|
> node-sass@1.2.3 install XXX/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at XXX/node_modules/node-sass/vendor/linux-x64/binding.node

> node-sass@1.2.3 postinstall XXX/node_modules/node-sass
> node scripts/build.js

`linux-x64` exists; testing
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (XXX/node_modules/node-sass/lib/index.js:181:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

npm ERR! Linux 3.13.0-39-generic
npm ERR! argv "~/.nvm/v0.11.14/bin/node" "~/.nvm/v0.11.14/bin/npm" "install" "node-sass"
npm ERR! node v0.11.14
npm ERR! npm  v2.0.0
npm ERR! code ELIFECYCLE
npm ERR! node-sass@1.2.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@1.2.3 postinstall script.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.
jenkins@jenkins:XXX$
```

I've googled all over the place, but it seems as though this is a test failure and not anything to do with the actual build failing.

**Comment by briandela** [comment]
Getting this issue with Node 0.12 now. Any ideas how to solve this for node v0.12.

**Comment by kevinSuttle** [comment]
Same. 
OSX 10.10.2. 
Node v0.12 Installed via `brew`
Even tried `node-sass@2.0.0-beta`: no dice

**Comment by am11** [comment]
@briandela @kevinSuttle see https://github.com/sass/node-sass/issues/653.

**Comment by mcgwiz** [comment]
On Yosemite, node 0.12.0. Just resorted to [this](http://stackoverflow.com/a/4158763/). See section 3b of the accepted answer in order to downgrade node to 0.10.33.

**Comment by Martii** [comment]
Latest 0.10.x is [1.10.36](https://github.com/joyent/node/releases/tag/v0.10.36) btw

**Comment by am11** [comment]
Guys lets not discuss scattered/random matters under closed issues. 

The related issue is opened here: https://github.com/sass/node-sass/issues/655

If you are facing particular issue, search the issue tracker for the opened issue first, if not found open a new issue.

@Martii, and 0.10.36 is supported by v2.0.0-beta.

@mcgwiz, see the comments at https://github.com/sass/node-sass/issues/653. You can build the binary for Mac for both io.js and node.js v0.12.

**Comment by Martii** [comment]
Would be nice if GH would mirror the `div.state-closed` below too... didn't realize it was closed since I'm taken straight to the end here. My apologies yet again.

**Comment by am11** [comment]
@Martii, you can send feedback to GH team, they are very receptive (i.e. at the minimum, they reply to every email sooner or later).

**Comment by laurilehmijoki** [comment]
I'm seeing

```
Error: Module did not self-register.
    at Error (native)              
    at Module.load (module.js:355:32)                                                                  
    at Function.Module._load (module.js:310:12)                                                       
    at Module.require (module.js:365:17)                                                             
    at require (module.js:384:17)                                                                   
    at Object.<anonymous> (/Users/llehmijo/myapp/node_modules/node-sass
/lib/index.js:181:15)                                                                                 
    at Module._compile (module.js:460:26)                                                            
    at Object.Module._extensions..js (module.js:478:10)                                             
    at Module.load (module.js:355:32)                                                              
    at Function.Module._load (module.js:310:12)  
```

When node-sass version is **1.2.3** and Node.js version is **0.12.0**.

**Comment by xzyfer** [comment]
1.2.3 does not support node 0.12. Upgrade to 2.0.1 for for 0.12 support.

**Comment by coledot** [comment]
Still having this issue on OSX 10.10:

```
> node-sass@1.2.3 install node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at node_modules/node-sass/vendor/darwin-x64/binding.node

> node-sass@1.2.3 postinstall node_modules/node-sass
> node scripts/build.js

`darwin-x64` exists; testing
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (node_modules/node-sass/lib/index.js:181:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.5
npm ERR! code ELIFECYCLE

npm ERR! node-sass@1.2.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@1.2.3 postinstall script 'node scripts/build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     node_modules/npm-debug.log
```

Had to roll back to 1.2.2.

**Comment by am11** [comment]
@coledot
The latest stable version of node-sass is [v3.0.0](https://github.com/sass/node-sass/releases/tag/v3.0.0). You are using an ancient version v1.2.2/3.
Try out v3 to see what are you missing. ;)

**Comment by charmeleon** [comment]
I also had this version running node 0.11.13, Ubuntu 14.04. It's used as a dependency for gulp-sass so I can't change the version. I can confirm that using node 0.10.29 makes the error go away (but then I feel icky)

**Comment by xzyfer** [comment]
Node 0.11 is simply unsupported. This will not change. Updating to 0.12
will also resolve the issue.
