### ISSUE TITLE
node-sass@1.2.3 scripts/install.js failing on OS X

### ISSUE THREAD

**Issue by callumlocke** [sass/node-sass#569]
I get this when I do `$ npm install node-sass`:

```
> node-sass@1.2.3 install /Users/callum.locke/code/messing/exp/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /Users/callum.locke/code/messing/exp/node_modules/node-sass/vendor/darwin-x64/binding.node

> node-sass@1.2.3 postinstall /Users/callum.locke/code/messing/exp/node_modules/node-sass
> node scripts/build.js

`darwin-x64` exists; testing
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/callum.locke/code/messing/exp/node_modules/node-sass/lib/index.js:181:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
npm ERR! node-sass@1.2.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@1.2.3 postinstall script.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 13.4.0
npm ERR! command "node" "/usr/local/bin/npm" "i" "node-sass"
npm ERR! cwd /Users/callum.locke/code/messing/exp
npm ERR! node -v v0.11.14
npm ERR! npm -v TypeError: Cannot read property 'node' of undefined
npm ERR! npm -v     at /usr/local/lib/node_modules/npm/lib/npm.js:61:38
npm ERR! npm -v     at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/npm.js:520:3)
npm ERR! npm -v     at Module._compile (module.js:460:26)
npm ERR! npm -v     at Object.Module._extensions..js (module.js:478:10)
npm ERR! npm -v     at Module.load (module.js:355:32)
npm ERR! npm -v     at Function.Module._load (module.js:310:12)
npm ERR! npm -v     at Module.require (module.js:365:17)
npm ERR! npm -v     at require (module.js:384:17)
npm ERR! npm -v     at /usr/local/lib/node_modules/npm/bin/npm-cli.js:24:11
npm ERR! npm -v     at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:86:3)
npm ERR! npm -v  { [TypeError: Cannot read property 'node' of undefined]
npm ERR! npm -v   stack: 'TypeError: Cannot read property \'node\' of undefined\n    at /usr/local/lib/node_modules/npm/lib/npm.js:61:38\n    at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/npm.js:520:3)\n    at Module._compile (module.js:460:26)\n    at Object.Module._extensions..js (module.js:478:10)\n    at Module.load (module.js:355:32)\n    at Function.Module._load (module.js:310:12)\n    at Module.require (module.js:365:17)\n    at require (module.js:384:17)\n    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:24:11\n    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:86:3)' }
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/callum.locke/code/messing/exp/npm-debug.log
npm ERR! not ok code 0
```

For the record I've tried completely deleting my `~/.npm` and `~/.node-gyp` cache directories before re-running `npm install node-sass`, but I still get the same error.

**Comment by plaxdan** [comment]
Current stable node is now at 0.12. Can we have this one re-opened?

**Comment by am11** [comment]
@plaxdan, try: `npm install node-sass@2.0.1`.

**Comment by plaxdan** [comment]
^ got it. Thanks!
