### ISSUE TITLE
v2.0.0-beta node-gyp building for atom-shell fails

### ISSUE THREAD

**Issue by Larivact** [sass/node-sass#599]
Rebuilding for [atom-shell](https://github.com/atom/atom-shell) worked in v1.2.3 in v2.0.0-beta it fails.
Windows 7 64-bit
atom-shell tutorial: using native Node modules https://github.com/atom/atom-shell/blob/master/docs/tutorial/using-native-node-modules.md

**Works:**
```
npm install  node-sass@1.2.3 --msvs_version=2013
*moving into node-sass dir*
node-gyp rebuild --target=0.20.0 --arch=ia32 --dist-url=https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist --msvs_version=2013
```
**Fails:**
```
npm install  node-sass@2.0.0-beta --msvs_version=2013
*moving into node-sass dir*
node-gyp rebuild --target=0.20.0 --arch=ia32 --dist-url=https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist --msvs_version=2013
```
```

C:\Users\unknown\Desktop\Atom-Cito\node_modules\node-sass>node-gyp rebuild --target=0.20.0 --arch=ia32 --dist-url=https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist --msvs_version=2013
gyp info it worked if it ends with ok
gyp info using node-gyp@1.0.2
gyp info using node@0.10.33 | win32 | ia32
gyp info spawn python
gyp info spawn args [ 'C:\\Users\\unknown\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2013',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\unknown\\Desktop\\Atom-Cito\\node_modules\\node-sass\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\unknown\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\unknown\\.node-gyp\\0.20.0\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\unknown\\.node-gyp\\0.20.0',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\unknown\\Desktop\\Atom-Cito\\node_modules\\node-sass',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\unknown\\Desktop\\Atom-Cito\\node_modules\\node-sass\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=Win32' ]
Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu ermöglichen, müssen Sie den Schalter "/m" hinzufügen.
cl : Command line warning D9025: overriding '/GR-' with '/GR' [C:\Users\unknown\Desktop\Atom-Cito\node_modules\node-sass\build\binding.vcxproj]
cl : Command line warning D9025: overriding '/GR-' with '/GR' [C:\Users\unknown\Desktop\Atom-Cito\node_modules\node-sass\build\binding.vcxproj]
cl : Command line warning D9025: overriding '/GR-' with '/GR' [C:\Users\unknown\Desktop\Atom-Cito\node_modules\node-sass\build\binding.vcxproj]
cl : Command line warning D9025: overriding '/GR-' with '/GR' [C:\Users\unknown\Desktop\Atom-Cito\node_modules\node-sass\build\binding.vcxproj]
cl : Command line warning D9025: overriding '/GR-' with '/GR' [C:\Users\unknown\Desktop\Atom-Cito\node_modules\node-sass\build\binding.vcxproj]
  binding.cpp
  sass_context_wrapper.cpp
  ast.cpp
  base64vlq.cpp
  bind.cpp
..\src\binding.cpp(172): error C2664: 'int GetResult(v8::Handle<v8::Object>,Sass_Context *)' : cannot convert argument 1 from 'v8::Persistent<v8::Object,v8::NonCopyablePersistentTraits<T>>' to 'v8::Handle<v8::Object>' [C:\Users\unknown\Desktop\Atom-Cito\node_modules\node-sass\build\binding.vcxproj]
          with
          [
              T=v8::Object
          ]
          No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
..\src\binding.cpp(223): error C2664: 'int GetResult(v8::Handle<v8::Object>,Sass_Context *)' : cannot convert argument 1 from 'v8::Persistent<v8::Object,v8::NonCopyablePersistentTraits<T>>' to 'v8::Handle<v8::Object>' [C:\Users\unknown\Desktop\Atom-Cito\node_modules\node-sass\build\binding.vcxproj]
          with
          [
              T=v8::Object
          ]
          No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
..\src\binding.cpp(270): error C2664: 'int GetResult(v8::Handle<v8::Object>,Sass_Context *)' : cannot convert argument 1 from 'v8::Persistent<v8::Object,v8::NonCopyablePersistentTraits<T>>' to 'v8::Handle<v8::Object>' [C:\Users\unknown\Desktop\Atom-Cito\node_modules\node-sass\build\binding.vcxproj]
          with
          [
              T=v8::Object
          ]
          No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
..\src\binding.cpp(314): error C2039: 'New' : is not a member of 'v8::String' [C:\Users\unknown\Desktop\Atom-Cito\node_modules\node-sass\build\binding.vcxproj]
          C:\Users\unknown\.node-gyp\0.20.0\deps\v8\include\v8.h(1740) : see declaration of 'v8::String'
..\src\binding.cpp(314): error C3861: 'New': identifier not found [C:\Users\unknown\Desktop\Atom-Cito\node_modules\node-sass\build\binding.vcxproj]
..\src\binding.cpp(315): error C2039: 'New' : is not a member of 'v8::String' [C:\Users\unknown\Desktop\Atom-Cito\node_modules\node-sass\build\binding.vcxproj]
          C:\Users\unknown\.node-gyp\0.20.0\deps\v8\include\v8.h(1740) : see declaration of 'v8::String'
..\src\binding.cpp(315): error C3861: 'New': identifier not found [C:\Users\unknown\Desktop\Atom-Cito\node_modules\node-sass\build\binding.vcxproj]
..\src\binding.cpp(323): error C2039: 'New' : is not a member of 'v8::String' [C:\Users\unknown\Desktop\Atom-Cito\node_modules\node-sass\build\binding.vcxproj]
          C:\Users\unknown\.node-gyp\0.20.0\deps\v8\include\v8.h(1740) : see declaration of 'v8::String'
..\src\binding.cpp(323): error C3861: 'New': identifier not found [C:\Users\unknown\Desktop\Atom-Cito\node_modules\node-sass\build\binding.vcxproj]
..\src\binding.cpp(324): error C2039: 'New' : is not a member of 'v8::String' [C:\Users\unknown\Desktop\Atom-Cito\node_modules\node-sass\build\binding.vcxproj]
          C:\Users\unknown\.node-gyp\0.20.0\deps\v8\include\v8.h(1740) : see declaration of 'v8::String'
..\src\binding.cpp(324): error C3861: 'New': identifier not found [C:\Users\unknown\Desktop\Atom-Cito\node_modules\node-sass\build\binding.vcxproj]
  constants.cpp
  context.cpp
  contextualize.cpp
  copy_c_str.cpp
  error_handling.cpp
  eval.cpp
  expand.cpp
  extend.cpp
  file.cpp
  functions.cpp
  inspect.cpp
  json.cpp
  node.cpp
  output_compressed.cpp
  output_nested.cpp
  parser.cpp
  prelexer.cpp
  remove_placeholders.cpp
  sass.cpp
  sass2scss.cpp
  sass_context.cpp
  sass_functions.cpp
  sass_util.cpp
  sass_values.cpp
  source_map.cpp
..\src\libsass\sass_context.cpp(180): warning C4297: 'copy_strings' : function assumed not to throw an exception but does [C:\Users\unknown\Desktop\Atom-Cito\node_modules\node-sass\build\binding.vcxproj]
          The function is extern "C" and /EHc was specified
..\src\libsass\sass_context.cpp(184): warning C4297: 'copy_strings' : function assumed not to throw an exception but does [C:\Users\unknown\Desktop\Atom-Cito\node_modules\node-sass\build\binding.vcxproj]
          The function is extern "C" and /EHc was specified
  to_c.cpp
  to_string.cpp
  units.cpp
  utf8_string.cpp
  util.cpp
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\unknown\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Users\\unknown\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=0.20.0" "--arch=ia32" "--dist-url=https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist" "--msvs_version=2013"
gyp ERR! cwd C:\Users\unknown\Desktop\Atom-Cito\node_modules\node-sass
gyp ERR! node -v v0.10.33
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok

C:\Users\unknown\Desktop\Atom-Cito\node_modules\node-sass>
```

**Comment by am11** [comment]
Do you get the same result if you download and extract https://github.com/sass/node-sass/archive/v2.0.0-beta.zip, enter the directory via cmd/ps and run `node-gyp rebuild --msvs_version=2013`? 

Is there a reason you are not using our pre-built [published binary](https://github.com/sass/node-sass-binaries/tree/v2.0.0-beta), which get downloaded with `npm install node-sass`?

I can't reproduce this issue with VS2013 Update 4, otherwise it wouldn't be possible for me to build and publish binary for 2.0.0-beta.

**Comment by Larivact** [comment]
Microsoft Visual Studio Express 2013 for Windows Desktop - ENU with Update 4
Seems to be the same version you are using.

I don't get the same result, I get:
```

C:\Users\unknown\Desktop\node-sass-2.0.0-beta>node-gyp rebuild --msvs_version=2013
gyp info it worked if it ends with ok
gyp info using node-gyp@1.0.2
gyp info using node@0.10.33 | win32 | ia32
gyp info spawn python
gyp info spawn args [ 'C:\\Users\\unknown\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2013',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\unknown\\Desktop\\node-sass-2.0.0-beta\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\unknown\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\unknown\\.node-gyp\\0.10.33\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\unknown\\.node-gyp\\0.10.33',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\unknown\\Desktop\\node-sass-2.0.0-beta',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\unknown\\Desktop\\node-sass-2.0.0-beta\\build',
gyp info spawn args   '-Goutput_dir=.' ]

module.js:340
    throw err;
          ^
Error: Cannot find module 'nan'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at [eval]:1:1
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:456:26)
    at evalScript (node.js:536:25)
    at startup (node.js:80:7)
    at node.js:906:3
gyp: Call to 'node -e "require('nan')"' returned exit status 8. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\unknown\AppData\Roaming\npm\node_modules\node-gyp\lib\configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Users\\unknown\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--msvs_version=2013"
gyp ERR! cwd C:\Users\unknown\Desktop\node-sass-2.0.0-beta
gyp ERR! node -v v0.10.33
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok

C:\Users\unknown\Desktop\node-sass-2.0.0-beta>
```

```
Is there a reason you are not using our pre-built published binary,
which get downloaded with npm install node-sass?
```
I am using ```npm install node-sass``` I guess that means that I am also using your pre-build published binary. So your question means why I am not downloading them directly?

**Comment by Larivact** [comment]
I figured out that this works:
```
npm install  node-sass@2.0.0-beta --msvs_version=2013
*moving into node-sass dir*
node-gyp rebuild --msvs_version=2013
```
But as soon as i add the flags needed to make it work with atom-shell I get the output from my first comment.

**Comment by am11** [comment]
My question is why are you trying to build manually? Yes "node-gyp build" is a manual build process.
Normally people only do this:

```
npm install node-sass
```

And that's it! No need for VS to be installed, or node-gyp and no extra switches like --msvs_version=2013. The binary file matching your operating system architecture will be downloaded as part of node-sass installation process.

If you do want to install manually (for some reason), you can download this zip https://github.com/sass/node-sass/archive/v2.0.0-beta.zip, extract it and then from cmd

```
cd into/extracted/node-sass/folder
npm install
node-gyp rebuild
```

But again, you do not need it to consume node-sass! Yes if you want to contribute to code, then you will clone our repository and then you may need to use tools like node-gyp (we only use it when we make any changes in C++ files).

I don't have any idea what is atom-shell. What I know is its unnecessary for you to run `node-gyp rebuild` to rebuild the binary (unless there is a problem with our binary for your OS).

**Comment by Larivact** [comment]
[This](https://github.com/atom/atom-shell/blob/master/docs/tutorial/using-native-node-modules.md) is all I know. I am closing this issue because it's related to atom-shell not node-sass. I can use node-sass 2.0.0-beta without any problem with normal node. It just doesn't work with atom-shell. Atom-shell uses a different V8 version from official node therefore a native module needs some modification to work. The thing is that their instructions don't work for me.

@am11 thanks for your support
