### ISSUE TITLE
Windows: 'npm install node-sass' fails when module 'install.js' cannot be found.

### ISSUE THREAD

**Issue by lostPixels** [sass/node-sass#603]
Getting this error when installed node-sass.

17608 error node-sass@1.2.2 install: `node scripts/install.js`
17608 error Exit status 8
17609 error Failed at the node-sass@1.2.2 install script.
17609 error This is most likely a problem with the node-sass package,
17609 error not with npm itself.
17609 error Tell the author that this fails on your system:
17609 error     node scripts/install.js
17609 error You can get their info via:
17609 error     npm owner ls node-sass
17609 error There is likely additional logging output above.
17610 error System Windows_NT 6.1.7601
17611 error command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-sass"
17612 error cwd C:\www\Site
17613 error node -v v0.10.25
17614 error npm -v 1.3.24
17615 error code ELIFECYCLE

More environment info: 
Windows 7 x32

node-p process.arch
ia32

node -v
v0.10.25

**Comment by am11** [comment]
Please give it another try like [this](https://github.com/sass/node-sass/issues/580#issuecomment-68101835) and show the output (by wrapping the log in \`\`\`).

**Comment by lostPixels** [comment]
Hello, I just did this and my results are:
```
c:\temp>node -v
v0.10.25

c:\temp>npm -v
1.3.24

c:\temp>node -p process.arch
ia32

c:\temp>md temp

c:\temp>cd /temp

c:\temp>npm install node-sass; node
npm http GET https://registry.npmjs.org/node-sass%3B
npm http GET https://registry.npmjs.org/node
npm http 304 https://registry.npmjs.org/node
npm WARN deprecated node@0.0.0: To update or install node, go to http://nodejs.o
rg/
npm http 404 https://registry.npmjs.org/node-sass%3B
npm ERR! 404 'node-sass%3B' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404
npm ERR! 404 Maybe try 'npm search sass 3 '
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-sass;" "node"
npm ERR! cwd c:\temp
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.24
npm ERR! code E404
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     c:\temp\npm-debug.log
npm ERR! not ok code 0

c:\temp># javascript, node interactive console
'#' is not recognized as an internal or external command,
operable program or batch file.

c:\temp>require('node-sass')
'require' is not recognized as an internal or external command,
operable program or batch file.

c:\temp>require('node-sass').info()
'require' is not recognized as an internal or external command,
operable program or batch file.

c:\temp>require('node-sass').renderSync({data: 'p{color: magenta}'}).css
'require' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by lostPixels** [comment]
I've figured out the problem. All the paths to external files are being referenced from `c:/` instead of `c:/../my-project/node-modules/node-sass`

Once I grabbed `install.js` from a coworker and placed it where my installation was looking before it failed, things started to work. However it's failing on other dependencies that aren't pathed correctly.

**Comment by am11** [comment]
@lostPixels, it first appeared as the issue with win-x86 binary: `vendor/win32-ia32/binding.node`, but now it sounds like a different issue. Can you confirm if it is working on other Windows 7 32bit system?

**Comment by am11** [comment]
Closing due to inactivity. Please reopen if you get this error with v2.0.1: 

```powershell
npm install node-sass@2.0.1
```

**Comment by hisuwh** [comment]
I have just had this issue with node-sass@2.0.1

Building a laravel application and running 'npm install'

Getting 
'npm ERR! node-sass@2.0.1 install: 'node scripts/install.js'

**Comment by am11** [comment]
@hisuwh, not sure about laravel application. But you can quickly check and rule out whether it is node-sass issue with Windows 7 64-bit with this: https://gist.github.com/am11/e5de3c49c219f0811e1d. If you get error, please open a new issue with your output (preferably a gist link).

**Comment by hisuwh** [comment]
@am11 thanks for the quick response.  I will try this later

**Comment by chaim1221** [comment]
I just had this error with @2.0.1
```
> node-sass@2.0.1 install c:\InComm\enterprise-apps\Web\Admin\NxsassContent\node_modules\gulp-sass\n
ode_modules\node-sass
> node scripts/install.js

module.js:338
    throw err;
          ^
Error: Cannot find module 'C:\Users\celiyah\Documents\scripts\install.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Users\\celiyah\\AppData\\Roaming\\npm\\node
_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.6.0
npm ERR! code ELIFECYCLE

npm ERR! node-sass@2.0.1 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@2.0.1 install script 'node scripts/install.js'.
```

In my case it is looking in the Documents directory for what it can't find instead of `C:\`. Still, can anyone determine the source of this error? I've seen it with other packages as well and it's annoying.

**Comment by am11** [comment]
@chaim1221, please run this set of commands in cmd or powershell: https://gist.github.com/am11/e5de3c49c219f0811e1d, make an output gist and share the link.

**Comment by chaim1221** [comment]
Gist [here]:(https://gist.github.com/chaim1221/c0f17ac823dbf4aa63cf)

**Comment by chaim1221** [comment]
Never got to the install :-/

**Comment by am11** [comment]
Thanks! Is this powershell or cmd?
Also, which version of Windows?

**Comment by chaim1221** [comment]
Win8.1@latest, it's dev cmd (VS2013)

**Comment by am11** [comment]
Can you reproduce it in non-dev PowerShell (`$host.version.major === 4`)?

**Comment by chaim1221** [comment]
Yep, same output, added it as comment to previous [gist](https://gist.github.com/chaim1221/c0f17ac823dbf4aa63cf)

**Comment by am11** [comment]
Well this is highly irregular. It seems like it is somehow overwriting the cwd path.

When `pwd` is `c:\temp`, if you run `npm config list`, does it show something like this in the list:

> ; cwd = C:\temp

?

Conversely, what is the output of `node -p "process.cwd()"` at that location?

**Comment by chaim1221** [comment]
Sorry got taken away by a prod issue.

```
C:\temp1>npm config list
; cli configs
user-agent = "npm/2.6.0 node/v0.12.0 win32 x64"

; builtin config undefined
prefix = "C:\\Users\\celiyah\\AppData\\Roaming\\npm"

; node bin location = C:\Program Files\nodejs\node.exe
; cwd = C:\temp1
; HOME = C:\Users\celiyah
; 'npm config ls -l' to show all defaults.


C:\temp1>node -p "process.cwd()"
C:\temp1

C:\temp1>
```

**Comment by am11** [comment]
@chaim1221, I am using two Win8.1 systems and can't reproduce it on either. It might be some machine specific environment variable related issue.

Can you try switching nodejs or io.js versions using [nvmw](https://github.com/hakobera/nvmw) and see if you can install node-sass against anyone of these versions: https://github.com/sass/node-sass-binaries/releases/tag/v2.0.0 ?

**Comment by zgardner** [comment]
@am11 I got this error when trying to run ```npm install``` in my git bash window. When I ran the command through Web Storm, it worked. I think there is a limit to the amount of memory that the git bash window can use, and that install script is hitting it.

**Comment by igabesz** [comment]
I have the same issue. Win8.1 64bit plus VS2013 Ultimate (not Windows Desktop that you mentioned on the readme page, but the problem seems to be something different)
```
C:\W\WH-Mobile>npm install gulp-sass
-
> node-sass@0.9.6 install C:\W\WH-Mobile\node_modules\gulp-sass\node_modules\node-sass
> node build.js


module.js:340
    throw err;
          ^
Error: Cannot find module 'C:\W\build.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

npm ERR! node-sass@0.9.6 install: `node build.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the node-sass@0.9.6 install script.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\App\\Node.js\\\\node.exe" "C:\\App\\Node.js\\node_modules\\npm\\bin\\npm-cli.js" "install" "gulp-sass"
npm ERR! cwd C:\W\WH-Mobile
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

**Comment by igabesz** [comment]
Copied to issue #152

**Comment by xzyfer** [comment]
@igabesz you are using node-sass v0.9.6 which is very old and no longer supported. Please update to v2.1.1 or 3.0.0-beta.

**Comment by ravishtiwari** [comment]
@xzyfer is right, I was having same issue, updated gulp-sass version (which was using node-sass) and it's worked  like a charm for me...

**Comment by elporfirio** [comment]
Im on same, now trying to run NPM from vagrant machine, but I cant write on Windows Local disk.

**Comment by igabesz** [comment]
Thx for the suggestions, but it didn't work. Now I get the same error with 3.0.0-beta.7

```
C:\W\WH-Mobile>npm install gulp-sass@next
-
> node-sass@3.0.0-beta.7 install C:\W\WH-Mobile\node_modules\gulp-sass\node_modules\node-sass
> node scripts/install.js


module.js:340
    throw err;
          ^
Error: Cannot find module 'C:\W\scripts\install.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

npm ERR! node-sass@3.0.0-beta.7 install: `node scripts/install.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the node-sass@3.0.0-beta.7 install script.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\App\\Node.js\\\\node.exe" "C:\\App\\Node.js\\node_modules\\npm\\bin\\npm-cli.js" "install" "gulp-sass@next"
npm ERR! cwd C:\W\WH-Mobile
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

**Comment by xzyfer** [comment]
@igabesz can you please update your npm, your version is very old and likely incompatible with node-sass

```
npm install -g npm
```

**Comment by chaim1221** [comment]
So, I had this problem for months in a windows environment with Node. Kept looking in my Documents folder for install.js for dependencies, even when the bloomin' version was defined in the original install.js deps. Anyways, my final solution to all these Node EPERM or ENOENT errors on Windows (really):

Nuke Windows. Start over. Install Node.js fresh. Globally install NPM. Disable original NPM (where npm). Globally install your command line utilities (e.g., karma-cli). Then install anything else you need.

Still trying to figure out whether to blame Ballmer or Dahl.

**Comment by saper** [comment]
I wonder why in @igabesz case it suddenly ends up in `C:\W` ! Is there `C:\W\node_modules` somewhere?

@chaim1221 a bit extreme, but getting rid of strange `node_modules` directories is a good start.

**Comment by glennphilp** [comment]
Multiple people on my team have begun to experience this issue.
```
npm install node-sass
> node-sass@3.13.1 install /Users/glennphilp/Sites/playground/ihatetomatoes/node_modules/gulp-sass/node_modules/node-sass
> node scripts/install.js
module.js:471
    throw err;
    ^
Error: Cannot find module 'aws-sign2'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/glennphilp/Sites/playground/ihatetomatoes/node_modules/request/request.js:10:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.13.1 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.13.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
According to this line `npm ERR! node-sass@3.13.1 install: 'node scripts/install.js'` is node-sass looking in the wrong location for install.js? When I look inside my project_folder>node_modules>node-sass>scripts folder there is an install.js file.

**Comment by xzyfer** [comment]
Error: Cannot find module 'aws-sign2'

Suggests something caused npm to not install all its dependencies. Try
clearing your cache and try npm install again.

Unfortunately node-sass@3.x is very old, and unsupported.

**Comment by TEJAPS** [comment]
install node-sass using yarn
by using command:-

yarn add node-sass

**Comment by regrag** [comment]
rttrh

**Comment by yafetissac** [comment]
Here’s the solution:

sudo npm install --save-dev --unsafe-perm node-sass
Enjoy!

If thist doesn’t work try to install from a mirror

Full Source Available At [Here](https://icetutor.com/question/error-in-cannot-find-module-node-sass/)
