### ISSUE TITLE
Tests broken?

### ISSUE THREAD

**Issue by callumlocke** [sass/node-sass#631]
I just did `git pull` to get the latest master, then `npm install`, then `npm test`.

I get this:

```
> node-sass@2.0.0-beta pretest /Users/callum.locke/code/node-sass
> jshint bin lib test


> node-sass@2.0.0-beta test /Users/callum.locke/code/node-sass
> mocha test


fs.js:666
  return binding.readdir(pathModule._makeLong(path));
                 ^
Error: ENOENT, no such file or directory '/Users/callum.locke/code/node-sass/test/fixtures/spec/spec'
    at Object.fs.readdirSync (fs.js:666:18)
    at Object.module.exports.getSuites (/Users/callum.locke/code/node-sass/test/util/index.js:24:19)
    at Suite.<anonymous> (/Users/callum.locke/code/node-sass/test/spec.js:10:21)
    at context.describe.context.context (/Users/callum.locke/code/node-sass/node_modules/mocha/lib/interfaces/bdd.js:74:10)
    at Object.<anonymous> (/Users/callum.locke/code/node-sass/test/spec.js:9:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /Users/callum.locke/code/node-sass/node_modules/mocha/lib/mocha.js:185:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/callum.locke/code/node-sass/node_modules/mocha/lib/mocha.js:182:14)
    at Mocha.run (/Users/callum.locke/code/node-sass/node_modules/mocha/lib/mocha.js:394:31)
    at Object.<anonymous> (/Users/callum.locke/code/node-sass/node_modules/mocha/bin/_mocha:394:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0
```

On OS X 10.9.5. Any idea what I'm doing wrong?

**Comment by callumlocke** [comment]
I rebuilt the binaries myself following [these steps](https://github.com/sass/node-sass#rebuilding-binaries) and it worked
