### ISSUE TITLE
Instalation stuck at node scripts/install.js [OS X]

### ISSUE THREAD

**Issue by jakub-c** [sass/node-sass#641]
When running `npm install node-sass`, the process is getting stuck at node scripts/install.js

I'm running: OS X 10.10.1
Node versions tested: v0.10.35, v0.11.14

**Comment by justin-lefurjah** [comment]
I am having the same issue, also running OS X 10.10.1 and node v0.10.35

**Comment by michaelBenin** [comment]
Also experiencing issues with v0.11.14. 

````
Michaels-Air-2:industryweek-node michaelbenin$ npm i
npm WARN package.json querystring@0.2.0 querystring is also the name of a node core module.
 
> dtrace-provider@0.2.8 install /Users/michaelbenin/Projects/industryweek-node/node_modules/core-services-sdk/node_modules/core-service-discovery/node_modules/zkplus/node_modules/bunyan/node_modules/dtrace-provider
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
  ACTION binding_gyp_libusdt_target_build_libusdt .
Building libusdt for x86_64
rm -f *.gch
rm -f *.o
rm -f libusdt.a
rm -f test_usdt
rm -f test_usdt32
rm -f test_usdt64
rm -f test_mem_usage
gcc -O2 -arch x86_64   -c -o usdt.o usdt.c
usdt.c:212:9: warning: implicit declaration of function 'usdt_dof_section_free' is invalid in C99
      [-Wimplicit-function-declaration]
        usdt_dof_section_free(&strtab);
        ^
usdt.c:238:9: warning: implicit declaration of function 'usdt_dof_file_free' is invalid in C99
      [-Wimplicit-function-declaration]
        usdt_dof_file_free(provider->file);
        ^
2 warnings generated.
gcc -O2 -arch x86_64   -c -o usdt_dof_file.o usdt_dof_file.c
gcc -arch x86_64 -o usdt_tracepoints.o -c usdt_tracepoints_x86_64.s
gcc -O2 -arch x86_64   -c -o usdt_probe.o usdt_probe.c
gcc -O2 -arch x86_64   -c -o usdt_dof.o usdt_dof.c
gcc -O2 -arch x86_64   -c -o usdt_dof_sections.o usdt_dof_sections.c
rm -f libusdt.a
ar cru libusdt.a usdt.o usdt_dof_file.o usdt_tracepoints.o usdt_probe.o usdt_dof.o usdt_dof_sections.o 
ranlib libusdt.a
  TOUCH Release/obj.target/libusdt.stamp
  CXX(target) Release/obj.target/DTraceProviderBindings/dtrace_provider.o
In file included from ../dtrace_provider.cc:1:
../dtrace_provider.h:69:44: error: no type named 'Arguments' in namespace 'v8'; did you mean
      'v8::internal::Arguments'?
    static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                           ^~~~~~~~~~~~~
                                           v8::internal::Arguments
/Users/michaelbenin/.node-gyp/0.11.14/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../dtrace_provider.cc:1:
../dtrace_provider.h:70:45: error: no type named 'Arguments' in namespace 'v8'; did you mean
      'v8::internal::Arguments'?
    static v8::Handle<v8::Value> Fire(const v8::Arguments& args);
                                            ^~~~~~~~~~~~~
                                            v8::internal::Arguments
/Users/michaelbenin/.node-gyp/0.11.14/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../dtrace_provider.cc:1:
../dtrace_provider.h:87:44: error: no type named 'Arguments' in namespace 'v8'; did you mean
      'v8::internal::Arguments'?
    static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                           ^~~~~~~~~~~~~
                                           v8::internal::Arguments
/Users/michaelbenin/.node-gyp/0.11.14/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../dtrace_provider.cc:1:
../dtrace_provider.h:88:49: error: no type named 'Arguments' in namespace 'v8'; did you mean
      'v8::internal::Arguments'?
    static v8::Handle<v8::Value> AddProbe(const v8::Arguments& args);
                                                ^~~~~~~~~~~~~
                                                v8::internal::Arguments
/Users/michaelbenin/.node-gyp/0.11.14/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../dtrace_provider.cc:1:
../dtrace_provider.h:89:52: error: no type named 'Arguments' in namespace 'v8'; did you mean
      'v8::internal::Arguments'?
    static v8::Handle<v8::Value> RemoveProbe(const v8::Arguments& args);
                                                   ^~~~~~~~~~~~~
                                                   v8::internal::Arguments
/Users/michaelbenin/.node-gyp/0.11.14/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../dtrace_provider.cc:1:
../dtrace_provider.h:90:47: error: no type named 'Arguments' in namespace 'v8'; did you mean
      'v8::internal::Arguments'?
    static v8::Handle<v8::Value> Enable(const v8::Arguments& args);
                                              ^~~~~~~~~~~~~
                                              v8::internal::Arguments
/Users/michaelbenin/.node-gyp/0.11.14/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../dtrace_provider.cc:1:
../dtrace_provider.h:91:48: error: no type named 'Arguments' in namespace 'v8'; did you mean
      'v8::internal::Arguments'?
    static v8::Handle<v8::Value> Disable(const v8::Arguments& args);
                                               ^~~~~~~~~~~~~
                                               v8::internal::Arguments
/Users/michaelbenin/.node-gyp/0.11.14/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../dtrace_provider.cc:1:
../dtrace_provider.h:92:45: error: no type named 'Arguments' in namespace 'v8'; did you mean
      'v8::internal::Arguments'?
    static v8::Handle<v8::Value> Fire(const v8::Arguments& args);
                                            ^~~~~~~~~~~~~
                                            v8::internal::Arguments
/Users/michaelbenin/.node-gyp/0.11.14/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../dtrace_provider.cc:23:17: error: calling a protected constructor of class 'v8::HandleScope'
    HandleScope scope;
                ^
/Users/michaelbenin/.node-gyp/0.11.14/deps/v8/include/v8.h:816:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../dtrace_provider.cc:25:55: error: cannot initialize a parameter of type 'v8::Isolate *' with an lvalue of type
      'v8::Handle<v8::Value> (const v8::internal::Arguments &)'
    Local<FunctionTemplate> t = FunctionTemplate::New(DTraceProvider::New);
                                                      ^~~~~~~~~~~~~~~~~~~
/Users/michaelbenin/.node-gyp/0.11.14/deps/v8/include/v8.h:3435:16: note: passing argument to parameter 'isolate'
      here
      Isolate* isolate,
               ^
../dtrace_provider.cc:26:58: error: 'New' is a private member of 'v8::PersistentBase<v8::FunctionTemplate>'
    constructor_template = Persistent<FunctionTemplate>::New(t);
                                                         ^
/Users/michaelbenin/.node-gyp/0.11.14/deps/v8/include/v8.h:572:23: note: declared private here
  V8_INLINE static T* New(Isolate* isolate, T* that);
                      ^
../dtrace_provider.cc:26:28: error: too few arguments to function call, expected 2, have 1; did you mean
      'DTraceProbe::New'?
    constructor_template = Persistent<FunctionTemplate>::New(t);
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                           DTraceProbe::New
../dtrace_provider.h:69:34: note: 'DTraceProbe::New' declared here
    static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                 ^
../dtrace_provider.cc:27:25: error: member reference type 'Persistent<v8::FunctionTemplate>' is not a pointer;
      maybe you meant to use '.'?
    constructor_template->InstanceTemplate()->SetInternalFieldCount(1);
    ~~~~~~~~~~~~~~~~~~~~^~
                        .
../dtrace_provider.cc:27:27: error: no member named 'InstanceTemplate' in 'v8::Persistent<v8::FunctionTemplate,
      v8::NonCopyablePersistentTraits<v8::FunctionTemplate> >'
    constructor_template->InstanceTemplate()->SetInternalFieldCount(1);
    ~~~~~~~~~~~~~~~~~~~~  ^
../dtrace_provider.cc:28:25: error: member reference type 'Persistent<v8::FunctionTemplate>' is not a pointer;
      maybe you meant to use '.'?
    constructor_template->SetClassName(String::NewSymbol("DTraceProvider"));
    ~~~~~~~~~~~~~~~~~~~~^~
                        .
../dtrace_provider.cc:28:27: error: no member named 'SetClassName' in 'v8::Persistent<v8::FunctionTemplate,
      v8::NonCopyablePersistentTraits<v8::FunctionTemplate> >'
    constructor_template->SetClassName(String::NewSymbol("DTraceProvider"));
    ~~~~~~~~~~~~~~~~~~~~  ^
../dtrace_provider.cc:28:48: error: no member named 'NewSymbol' in 'v8::String'
    constructor_template->SetClassName(String::NewSymbol("DTraceProvider"));
                                       ~~~~~~~~^
../dtrace_provider.cc:30:31: error: no viable conversion from 'Persistent<v8::FunctionTemplate>' to
      'v8::Handle<v8::FunctionTemplate>'
    NODE_SET_PROTOTYPE_METHOD(constructor_template, "addProbe", DTraceProvider::AddProbe);
                              ^~~~~~~~~~~~~~~~~~~~
/Users/michaelbenin/.node-gyp/0.11.14/deps/v8/include/v8.h:196:26: note: candidate constructor
      (the implicit copy constructor) not viable: no known conversion from 'Persistent<v8::FunctionTemplate>' to
      'const v8::Handle<v8::FunctionTemplate> &' for 1st argument
template <class T> class Handle {
                         ^
/Users/michaelbenin/.node-gyp/0.11.14/deps/v8/include/v8.h:213:32: note: candidate template ignored: could not
      match 'Handle' against 'Persistent'
  template <class S> V8_INLINE Handle(Handle<S> that)
                               ^
/Users/michaelbenin/.node-gyp/0.11.14/src/node.h:227:72: note: passing argument to parameter 'recv' here
inline void NODE_SET_PROTOTYPE_METHOD(v8::Handle<v8::FunctionTemplate> recv,
                                                                       ^
../dtrace_provider.cc:31:31: error: no viable conversion from 'Persistent<v8::FunctionTemplate>' to
      'v8::Handle<v8::FunctionTemplate>'
    NODE_SET_PROTOTYPE_METHOD(constructor_template, "removeProbe", DTraceProvider::RemoveProbe);
                              ^~~~~~~~~~~~~~~~~~~~
/Users/michaelbenin/.node-gyp/0.11.14/deps/v8/include/v8.h:196:26: note: candidate constructor
      (the implicit copy constructor) not viable: no known conversion from 'Persistent<v8::FunctionTemplate>' to
      'const v8::Handle<v8::FunctionTemplate> &' for 1st argument
template <class T> class Handle {
                         ^
/Users/michaelbenin/.node-gyp/0.11.14/deps/v8/include/v8.h:213:32: note: candidate template ignored: could not
      match 'Handle' against 'Persistent'
  template <class S> V8_INLINE Handle(Handle<S> that)
                               ^
/Users/michaelbenin/.node-gyp/0.11.14/src/node.h:227:72: note: passing argument to parameter 'recv' here
inline void NODE_SET_PROTOTYPE_METHOD(v8::Handle<v8::FunctionTemplate> recv,
                                                                       ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/DTraceProviderBindings/dtrace_provider.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/michaelbenin/.nvm/v0.11.14/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1059:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/Users/michaelbenin/.nvm/v0.11.14/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/michaelbenin/Projects/industryweek-node/node_modules/core-services-sdk/node_modules/core-service-discovery/node_modules/zkplus/node_modules/bunyan/node_modules/dtrace-provider
gyp ERR! node -v v0.11.14
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm WARN optional dep failed, continuing dtrace-provider@0.2.8

> node-sass@1.2.3 install /Users/michaelbenin/Projects/industryweek-node/node_modules/grunt-sass/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /Users/michaelbenin/Projects/industryweek-node/node_modules/grunt-sass/node_modules/node-sass/vendor/darwin-x64/binding.node

> node-sass@1.2.3 postinstall /Users/michaelbenin/Projects/industryweek-node/node_modules/grunt-sass/node_modules/node-sass
> node scripts/build.js

`darwin-x64` exists; testing
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/michaelbenin/Projects/industryweek-node/node_modules/grunt-sass/node_modules/node-sass/lib/index.js:181:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

npm ERR! Darwin 14.0.0
npm ERR! argv "/Users/michaelbenin/.nvm/v0.11.14/bin/node" "/Users/michaelbenin/.nvm/v0.11.14/bin/npm" "i"
npm ERR! node v0.11.14
npm ERR! npm  v2.0.0
npm ERR! code ELIFECYCLE
npm ERR! node-sass@1.2.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@1.2.3 postinstall script.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.
Michaels-Air-2:industryweek-node michaelbenin$ 
````

**Comment by dzannotti** [comment]
Same issue here

**Comment by dzannotti** [comment]
Ok after a bit of head bashing i figured out that with node 0.10.36 everything works fine, so it's a compatibility problem with the latest node release, using nvm i was able to achieve what i needed

**Comment by christianromeni** [comment]
I was just wondering... But I guess you are already working on a fix? Not sure how to start my first project now :)

**Comment by jakub-c** [comment]
@christianromeni I'm not sure if you are sarcastic or you actually mean that you don't know how to start your project. If the latter is the case than you can install one of the previous versions by executing: npm install <package>@<version>, I suspect that something earlier than version 2 should work for you

**Comment by justin-lefurjah** [comment]
@christianromeni https://github.com/gruntjs/grunt-contrib-sass will work for you now. It is ruby based so you have to have that installed. Just look at the readme. I have heard it compiles a little slower than node-sass, but it probably won't be a big deal unless your project is huge.

**Comment by christianromeni** [comment]
Sorry, that was not beeing sarcastic.. I'm new to this...
I was trying not to use the grunt-contrib-sass because I didnt want to install ruby...
I'm currently installing by adding this line to my package.js: "grunt-bower-concat": "^0.4.0"
Could I just use a lower version (like 0.3.9??) and it will work?

**Comment by jakub-c** [comment]
@christianromeni I just looked at grunt-bower-concat dependencies and it doesn't look like it has anything to do with node-sass, so if you've got a problem using grunt-bower-concat than I would recommend filing an issue on their repo page. However if it's still a node-sass issue you should do as you described, but instead of changing version of grunt-bower-concat in your package.json you should find node-sass and set an earlier version number to something preceding version 2, than remove your node_modules folder and reinstall everything with `npm install`

**Comment by am11** [comment]
Is it like the process stuck forever or it throws after sometime with an error message?

**Comment by jakub-c** [comment]
@am11 In my case it looks like it's stuck forever. I gave it a minute or two to compute but after no result I've just terminated the process, I believe it's enough time.

**Comment by am11** [comment]
> I believe it's enough time.

Well I waited for ~30 mins, when I first encountered this error on Win. Eventually installation went through successfully. We figured out where it was hanging and fixed it. Now testing binary step (where it was hanging) was temporarily disabled in version v2.0.0-beta. Now it is really hard to guess what might be going wrong without any verbose output.

If you don't have time for such kind of diagnostic, then wait for vNext. We have some fixes in that area as well. 

Momentarily, does [this help](https://github.com/sass/node-sass/issues/640#issuecomment-72099897)? (manually binary installation)

**Comment by jakub-c** [comment]
@am11 Finally I had a while to test a solution suggested by you and it does work indeed. Thanks.

**Comment by am11** [comment]
@jakub-c, v2.0.1 (shortly after v2.0.0 stable) is released. Note that the current stable/production-ready version of node.js is v0.12. With node-sass v2+, we support both v0.10 and v0.12.

See node-sass release notes: https://github.com/sass/node-sass/releases/tag/v2.0.0
and that of node-sass-binaries: https://github.com/sass/node-sass-binaries/releases/tag/v2.0.0

**Comment by Centaur** [comment]
Problem persists with iojs-v2.4.0 and nodejs-v0.12.7.

**Comment by xzyfer** [comment]
@Centaur you problem is likely unrelated. Please open a new issue with the output from our [troubleshooting guide](https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md)

**Comment by dagelf** [comment]
I too thought there was a problem... After an hour: Ctrl + C
npm config set loglevel silly
npm install

.... It took 2 hours. But it finished. I'm using a shitty laptop and running from a USB root drive.
