### ISSUE TITLE
Issue installing node-sass-binaries

### ISSUE THREAD

**Issue by sairion** [sass/node-sass#665]
```
build	12-Feb-2015 13:37:59	> node-sass@2.0.0 install /home/.../node_modules/sass-loader/node_modules/node-sass
build	12-Feb-2015 13:37:59	> node scripts/install.js
build	12-Feb-2015 13:37:59	
error	12-Feb-2015 13:37:59	npm http GET https://registry.npmjs.org/file-loader
error	12-Feb-2015 13:37:59	npm http 304 https://registry.npmjs.org/file-loader
error	12-Feb-2015 13:37:59	npm http GET https://registry.npmjs.org/loader-utils
error	12-Feb-2015 13:37:59	npm http 304 https://registry.npmjs.org/loader-utils
error	12-Feb-2015 13:37:59	npm http GET https://registry.npmjs.org/json5
error	12-Feb-2015 13:37:59	npm http GET https://registry.npmjs.org/big.js
error	12-Feb-2015 13:37:59	npm http 304 https://registry.npmjs.org/big.js
error	12-Feb-2015 13:37:59	npm http 304 https://registry.npmjs.org/json5
error	12-Feb-2015 13:38:00	Can not download file from https://raw.githubusercontent.com/sass/node-sass-binaries/v2.0.0/linux-x64-nodejs-0.10/binding.node
build	12-Feb-2015 13:38:00	
build	12-Feb-2015 13:38:00	> node-sass@2.0.0 postinstall /home/.../node_modules/sass-loader/node_modules/node-sass
build	12-Feb-2015 13:38:00	> node scripts/build.js
build	12-Feb-2015 13:38:00	
error	12-Feb-2015 13:38:00	
error	12-Feb-2015 13:38:00	module.js:340
error	12-Feb-2015 13:38:00	    throw err;
error	12-Feb-2015 13:38:00	          ^
error	12-Feb-2015 13:38:00	Error: Cannot find module '/home/.../node_modules/sass-loader/node_modules/node-sass/node_modules/pangyp/bin/node-gyp'
error	12-Feb-2015 13:38:00	    at Function.Module._resolveFilename (module.js:338:15)
error	12-Feb-2015 13:38:00	    at Function.Module._load (module.js:280:25)
error	12-Feb-2015 13:38:00	    at Function.Module.runMain (module.js:497:10)
error	12-Feb-2015 13:38:00	    at startup (node.js:119:16)
error	12-Feb-2015 13:38:00	    at node.js:902:3
error	12-Feb-2015 13:38:00	Build failed
```

In my company's CI env, node-sass (more specifically, `sass-loader` pkg) install fails like above; It seems downloading libsass binding binary from unavailable location, which is https://raw.githubusercontent.com/sass/node-sass-binaries/v2.0.0/linux-x64-nodejs-0.10/binding.node . I'm experiencing this issue from an hour ago.

I think `v.2.0.0` branch has deleted?

**Comment by xzyfer** [comment]
Fixed by https://github.com/sass/node-sass/commit/c365f8c33825e67846d40e651f4bb7dd063461c5 and https://github.com/sass/node-sass/commit/ec16675f0062ab04e2399b6a64c63637b7887fe3
