### ISSUE TITLE
Failed Install - Cannot find module node-gyp

### ISSUE THREAD

**Issue by pdnellius** [sass/node-sass#696]
For some reason node-sass is failing global install. Installed node-gyp and all other dependencies, but for some reason the build continues to fail. Tried install on several versions of node, current version (using nvm to manage) is v0.11.16, but previously tried using v0.12.0 and io.js 1.3.0. 

Not sure where to go from here, anyone have any advice? Output below:

```
~  which node
/Users/pete.nellius/.nvm/v0.11.16/bin/node
```

```
~  npm install -g node-sass
/Users/pete.nellius/.nvm/v0.11.16/bin/node-sass -> /Users/pete.nellius/.nvm/v0.11.16/lib/node_modules/node-sass/bin/node-sass

> node-sass@2.0.1 install /Users/pete.nellius/.nvm/v0.11.16/lib/node_modules/node-sass
> node scripts/install.js

Can not download file from https://raw.githubusercontent.com/sass/node-sass-binaries/v2.0.1/darwin-x64-node-0.11/binding.node

> node-sass@2.0.1 postinstall /Users/pete.nellius/.nvm/v0.11.16/lib/node_modules/node-sass
> node scripts/build.js

module.js:338
    throw err;
          ^
Error: Cannot find module '/Users/pete.nellius/.nvm/v0.11.16/lib/node_modules/node-sass/node_modules/pangyp/bin/node-gyp'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
Build failed
node-sass@2.0.1 /Users/pete.nellius/.nvm/v0.11.16/lib/node_modules/node-sass
├── get-stdin@4.0.1
├── object-assign@2.0.0
├── replace-ext@0.0.1
├── nan@1.6.2
├── semver@4.3.0
├── mkdirp@0.5.0 (minimist@0.0.8)
├── shelljs@0.3.0
├── cross-spawn@0.2.6 (lru-cache@2.5.0)
├── chalk@0.5.1 (ansi-styles@1.1.0, escape-string-regexp@1.0.3, supports-color@0.2.0, has-ansi@0.1.0, strip-ansi@0.3.0)
├── meow@3.0.0 (minimist@1.1.0, camelcase-keys@1.0.0, indent-string@1.2.1)
├── npmconf@2.1.1 (uid-number@0.0.5, inherits@2.0.1, osenv@0.1.0, ini@1.3.3, once@1.3.1, nopt@3.0.1, config-chain@1.1.8)
├── gaze@0.5.1 (globule@0.1.0)
├── sass-graph@1.0.3 (commander@2.6.0, glob@4.4.0, lodash@2.4.1)
├── request@2.53.0 (caseless@0.9.0, json-stringify-safe@5.0.0, forever-agent@0.5.2, aws-sign2@0.5.0, stringstream@0.0.4, oauth-sign@0.6.0, tunnel-agent@0.4.0, isstream@0.1.1, node-uuid@1.4.2, qs@2.3.3, combined-stream@0.0.7, form-data@0.2.0, mime-types@2.0.9, http-signature@0.10.1, tough-cookie@0.12.1, bl@0.9.4, hawk@2.3.1)
└── mocha@2.1.0 (escape-string-regexp@1.0.2, diff@1.0.8, growl@1.8.1, commander@2.3.0, debug@2.0.0, glob@3.2.3, jade@0.26.3)
```
```
~  node-sass
/Users/pete.nellius/.nvm/v0.11.16/lib/node_modules/node-sass/lib/index.js:22
    throw new Error('`libsass` bindings not found. Try reinstalling `node-sass
          ^
Error: `libsass` bindings not found. Try reinstalling `node-sass`?
    at getBinding (/Users/pete.nellius/.nvm/v0.11.16/lib/node_modules/node-sass/lib/index.js:22:11)
    at Object.<anonymous> (/Users/pete.nellius/.nvm/v0.11.16/lib/node_modules/node-sass/lib/index.js:188:23)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/pete.nellius/.nvm/v0.11.16/lib/node_modules/node-sass/lib/render.js:3:12)
    at Module._compile (module.js:460:26)
```

**Comment by am11** [comment]
node.js v0.11.x (the whole branch was marked unstable) is not supported, please show the output with v0.12.0 (current stable) or v0.10.36  (previous stable).

**Comment by pdnellius** [comment]
well, I must've done something wrong initially, because when I went back to node v0.12.0 it solved the issue. 

Thanks for pointing me in the right direction!
