### ISSUE TITLE
Error while intalling node-sass

### ISSUE THREAD

**Issue by VaJoy** [sass/node-sass#722]
win7 64bit,` iojs v1.0.1`
when intalling `node-sass` it says:
```
Can not download file from https://raw.githubusercontent.com/sass/node-sass-binaries/v2.0.1/win32-x64-node-1.0/binding.node
```

should I gotta update iojs or other method to fix it?

**Comment by VaJoy** [comment]
the whole info:
```
E:\tomcat\webapps\djtTest>npm install node-sass -g
-
> node-sass@2.0.1 install E:\tomcat\webapps\djtTest\node_modules\node-sass
> node scripts/install.js

Can not download file from https://raw.githubusercontent.com/sass/node-sass-binaries/v2.0.1/win32-x64-node-1.0/binding.node

> node-sass@2.0.1 postinstall E:\tomcat\webapps\djtTest\node_modules\node-sass
> node scripts/build.js

module.js:324
    throw err;
          ^
Error: Cannot find module 'E:\tomcat\webapps\djtTest\node_modules\node-sass\node_modules\pangyp\bin\node-gyp'
    at Function.Module._resolveFilename (module.js:322:15)
    at Function.Module._load (module.js:264:25)
    at Function.Module.runMain (module.js:487:10)
    at startup (node.js:111:16)
    at node.js:809:3
Build failed
node-sass@2.0.1 node_modules\node-sass
├── object-assign@2.0.0                                                                                                                                                                                                                                               
├── get-stdin@4.0.1                                                                                                                                                                                                                                                   
├── replace-ext@0.0.1                                                                                                                                                                                                                                                 
├── nan@1.6.2                                                                                                                                                                                                                                                         
├── semver@4.3.1                                                                                                                                                                                                                                                      
├── shelljs@0.3.0                                                                                                                                                                                                                                                     
├── mkdirp@0.5.0 (minimist@0.0.8)                                                                                                                                                                                                                                     
├── cross-spawn@0.2.6 (lru-cache@2.5.0)                                                                                                                                                                                                                               
├── chalk@0.5.1 (ansi-styles@1.1.0, escape-string-regexp@1.0.3, supports-color@0.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)                                                                                                                                               
├── npmconf@2.1.1 (uid-number@0.0.5, inherits@2.0.1, osenv@0.1.0, ini@1.3.3, nopt@3.0.1, once@1.3.1, config-chain@1.1.8)                                                                                                                                              
├── meow@3.1.0 (minimist@1.1.0, camelcase-keys@1.0.0, indent-string@1.2.1)                                                                                                                                                                                            
├── gaze@0.5.1 (globule@0.1.0)                                                                                                                                                                                                                                        
├── mocha@2.1.0 (escape-string-regexp@1.0.2, diff@1.0.8, growl@1.8.1, commander@2.3.0, jade@0.26.3, debug@2.0.0, glob@3.2.3)                                                                                                                                          
├── sass-graph@1.0.3 (commander@2.6.0, lodash@2.4.1, glob@4.4.1)                                                                                                                                                                                                      
└── request@2.53.0 (caseless@0.9.0, json-stringify-safe@5.0.0, forever-agent@0.5.2, aws-sign2@0.5.0, stringstream@0.0.4, oauth-sign@0.6.0, tunnel-agent@0.4.0, isstream@0.1.1, node-uuid@1.4.2, qs@2.3.3, mime-types@2.0.9, combined-stream@0.0.7, tough-cookie@0.12.1
, form-data@0.2.0, http-signature@0.10.1, hawk@2.3.1, bl@0.9.4)
```

**Comment by am11** [comment]
With node.js v2.0.1, only iojs v1.2.0 is supported. See node-sass-binaries release notes: https://github.com/sass/node-sass-binaries/releases/tag/v2.0.0. Also readme: https://github.com/sass/node-sass-binaries#compatibility.

**Comment by VaJoy** [comment]
@am11 I updated iojs to 1.2.0 but still failed
```
Your environment has been set up for using io.js 1.2.0 (x64) and npm.

C:\Users\Administrator>npm install node-sass -g
C:\Users\Administrator\AppData\Roaming\npm\node-sass -> C:\Users\Administrator\A
ppData\Roaming\npm\node_modules\node-sass\bin\node-sass

> node-sass@2.0.1 install C:\Users\Administrator\AppData\Roaming\npm\node_module
s\node-sass
> node scripts/install.js

Can not download file from https://raw.githubusercontent.com/sass/node-sass-bina
ries/v2.0.1/win32-x64-node-1.2/binding.node

> node-sass@2.0.1 postinstall C:\Users\Administrator\AppData\Roaming\npm\node_mo
dules\node-sass
> node scripts/build.js

module.js:324
    throw err;
          ^
Error: Cannot find module 'C:\Users\Administrator\AppData\Roaming\npm\node_modul
es\node-sass\node_modules\pangyp\bin\node-gyp'
    at Function.Module._resolveFilename (module.js:322:15)
    at Function.Module._load (module.js:264:25)
    at Function.Module.runMain (module.js:487:10)
    at startup (node.js:111:16)
    at node.js:799:3
Build failed
npm WARN unmet dependency C:\Users\Administrator\AppData\Roaming\npm\node_module
s\phonegap\node_modules\phonegap-build requires colors@'0.6.x' but will load
npm WARN unmet dependency C:\Users\Administrator\AppData\Roaming\npm\node_module
s\phonegap\node_modules\colors,
npm WARN unmet dependency which is version 0.6.0-1
npm WARN unmet dependency C:\Users\Administrator\AppData\Roaming\npm\node_module
s\phonegap\node_modules\prompt\node_modules\winston requires colors@'0.x.x' but
will load
npm WARN unmet dependency C:\Users\Administrator\AppData\Roaming\npm\node_module
s\phonegap\node_modules\colors,
npm WARN unmet dependency which is version 0.6.0-1
node-sass@2.0.1 C:\Users\Administrator\AppData\Roaming\npm\node_modules\node-sas
s
├── object-assign@2.0.0
├── get-stdin@4.0.1
├── replace-ext@0.0.1
├── nan@1.6.2
├── semver@4.3.1
├── shelljs@0.3.0
├── cross-spawn@0.2.6 (lru-cache@2.5.0)
├── mkdirp@0.5.0 (minimist@0.0.8)
├── npmconf@2.1.1 (uid-number@0.0.5, inherits@2.0.1, osenv@0.1.0, ini@1.3.3,
nopt@3.0.1, config-chain@1.1.8, once@1.3.1)
├── gaze@0.5.1 (globule@0.1.0)
├── mocha@2.1.0 (escape-string-regexp@1.0.2, diff@1.0.8, growl@1.8.1, command
er@2.3.0, jade@0.26.3, debug@2.0.0, glob@3.2.3)
├── chalk@0.5.1 (ansi-styles@1.1.0, escape-string-regexp@1.0.3, supports-colo
r@0.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)
├── meow@3.1.0 (minimist@1.1.0, camelcase-keys@1.0.0, indent-string@1.2.1)
├── request@2.53.0 (caseless@0.9.0, json-stringify-safe@5.0.0, aws-sign2@0.5.
0, forever-agent@0.5.2, tunnel-agent@0.4.0, stringstream@0.0.4, oauth-sign@0.6.0
, isstream@0.1.1, qs@2.3.3, node-uuid@1.4.2, combined-stream@0.0.7, mime-types@2
.0.9, form-data@0.2.0, http-signature@0.10.1, tough-cookie@0.12.1, hawk@2.3.1, b
l@0.9.4)
└── sass-graph@1.0.3 (commander@2.6.0, lodash@2.4.1, glob@4.4.1)

C:\Users\Administrator>
```

**Comment by am11** [comment]
Yes that is a big ordeal in Windows for [multiple reasons](https://github.com/sass/node-sass/issues/708#issuecomment-76151398). We have taken care of for upcoming release for Linux and Mac completely, but for Windows, the workaround is still *half-way* (and if you are not using [nvmw](https://github.com/hakobera/nvmw), you will face this kind of issue in future).

The workaround is to use `iojs` to trigger npm explicitly:

```cmd
:: this is cmd
:: 
:: nvmw install iojs-v1.2.0
:: nvmw use iojs-v1.2.0
::
mkdir /temp; cd /temp
npm install npm
iojs node_modules\npm\bin\npm-cli.js install node-sass
:: success!
iojs
:: this is io.js interactive console (REPL)
> require('node-sass').renderSync({data: '.myClass { float: right } '})
```

**Comment by VaJoy** [comment]
@am11 still failed.... cry out loud...

```
E:\tomcat\webapps\djtTest>cnpm install npm
npm@2.6.1 node_modules\npm

E:\tomcat\webapps\djtTest>iojs node_modules\npm\bin\npm-cli.js install node-sass
\
> node-sass@2.0.1 install E:\tomcat\webapps\djtTest\node_modules\node-sass
> node scripts/install.js

Can not download file from https://raw.githubusercontent.com/sass/node-sass-binaries/v2.0.1/win32-x64-node-1.2/binding.node

> node-sass@2.0.1 postinstall E:\tomcat\webapps\djtTest\node_modules\node-sass
> node scripts/build.js

module.js:324
    throw err;
          ^
Error: Cannot find module 'E:\tomcat\webapps\djtTest\node_modules\node-sass\node_modules\pangyp\bin\node-gyp'
    at Function.Module._resolveFilename (module.js:322:15)
    at Function.Module._load (module.js:264:25)
    at Function.Module.runMain (module.js:487:10)
    at startup (node.js:111:16)
    at node.js:799:3
Build failed
node-sass@2.0.1 node_modules\node-sass
├── get-stdin@4.0.1                                                                                                                                                                                                                                                   
├── object-assign@2.0.0                                                                                                                                                                                                                                               
├── replace-ext@0.0.1                                                                                                                                                                                                                                                 
├── nan@1.6.2                                                                                                                                                                                                                                                         
├── semver@4.3.1                                                                                                                                                                                                                                                      
├── shelljs@0.3.0                                                                                                                                                                                                                                                     
├── mkdirp@0.5.0 (minimist@0.0.8)                                                                                                                                                                                                                                     
├── cross-spawn@0.2.6 (lru-cache@2.5.0)                                                                                                                                                                                                                               
├── chalk@0.5.1 (ansi-styles@1.1.0, escape-string-regexp@1.0.3, supports-color@0.2.0, has-ansi@0.1.0, strip-ansi@0.3.0)                                                                                                                                               
├── meow@3.1.0 (minimist@1.1.0, camelcase-keys@1.0.0, indent-string@1.2.1)                                                                                                                                                                                            
├── npmconf@2.1.1 (inherits@2.0.1, uid-number@0.0.5, osenv@0.1.0, ini@1.3.3, config-chain@1.1.8, nopt@3.0.1, once@1.3.1)                                                                                                                                              
├── gaze@0.5.1 (globule@0.1.0)                                                                                                                                                                                                                                        
├── mocha@2.1.0 (escape-string-regexp@1.0.2, diff@1.0.8, growl@1.8.1, commander@2.3.0, jade@0.26.3, debug@2.0.0, glob@3.2.3)                                                                                                                                          
├── request@2.53.0 (caseless@0.9.0, json-stringify-safe@5.0.0, forever-agent@0.5.2, aws-sign2@0.5.0, stringstream@0.0.4, oauth-sign@0.6.0, tunnel-agent@0.4.0, isstream@0.1.1, node-uuid@1.4.2, qs@2.3.3, form-data@0.2.0, tough-cookie@0.12.1, mime-types@2.0.9, comb
ined-stream@0.0.7, http-signature@0.10.1, bl@0.9.4, hawk@2.3.1)
└── sass-graph@1.0.3 (commander@2.6.0, lodash@2.4.1, glob@4.4.1)                                                                                                                                                                                                      

E:\tomcat\webapps\djtTest>
```

**Comment by VaJoy** [comment]
@am11 or u mean that I need to install `iojs` with `nvmw install iojs-v1.2.0`  ?
I gotta try it, wait a min...

**Comment by VaJoy** [comment]
@am11 deal it with nvmw, THX A LOT!!!!
