### ISSUE TITLE
Error while building node-sass | can not download file

### ISSUE THREAD

**Issue by Yobikap** [sass/node-sass#734]
Hi,

I'm getting error while running our project. It cannot download the binaries, and the binaries are not available with url:  https://raw.githubusercontent.com/sass/node-sass-binaries/v2.0.1/linux-x64-3.14.5/binding.node

How can I solve this problem?

Thanks

```
04-Mar-2015 10:14:00	Can not download file from https://raw.githubusercontent.com/sass/node-sass-binaries/v2.0.1/linux-x64-3.14.5/binding.node
04-Mar-2015 10:14:00	
04-Mar-2015 10:14:00	> node-sass@2.0.1 postinstall /var/opt/bamboo/xml-data/build-dir/WEB-ND-COMP/design/node_modules/grunt-kss/node_modules/kss/node_modules/node-sass
04-Mar-2015 10:14:00	> node scripts/build.js
04-Mar-2015 10:14:00	
04-Mar-2015 10:14:00	Building: /usr/bin/node node_modules/pangyp/bin/node-gyp rebuild
04-Mar-2015 10:14:01	make: Entering directory `/var/opt/bamboo/xml-data/build-dir/WEB-ND-COMP/design/node_modules/grunt-kss/node_modules/kss/node_modules/node-sass/build'
04-Mar-2015 10:14:01	  CXX(target) Release/obj.target/binding/src/binding.o
04-Mar-2015 10:14:01	In file included from ../src/binding.cpp:3:
04-Mar-2015 10:14:01	../src/sass_context_wrapper.h:4:34: error: libsass/sass_context.h: No such file or directory
04-Mar-2015 10:14:01	In file included from ../src/binding.cpp:3:
04-Mar-2015 10:14:01	../src/sass_context_wrapper.h:26: error: ISO C++ forbids declaration of ‘Sass_Import’ with no type
04-Mar-2015 10:14:01	../src/sass_context_wrapper.h:26: error: expected ‘;’ before ‘*’ token
04-Mar-2015 10:14:01	../src/binding.cpp: In function ‘void prepare_import_results(v8::Local<v8::Value>, sass_context_wrapper*)’:
04-Mar-2015 10:14:01	../src/binding.cpp:24: error: ‘struct sass_context_wrapper’ has no member named ‘imports’
04-Mar-2015 10:14:01	../src/binding.cpp:24: error: ‘sass_make_import_list’ was not declared in this scope
04-Mar-2015 10:14:01	../src/binding.cpp:36: error: ‘struct sass_context_wrapper’ has no member named ‘imports’
04-Mar-2015 10:14:01	../src/binding.cpp:36: error: ‘sass_make_import_entry’ was not declared in this scope
04-Mar-2015 10:14:01	../src/binding.cpp:40: error: ‘struct sass_context_wrapper’ has no member named ‘imports’
04-Mar-2015 10:14:01	../src/binding.cpp:40: error: ‘sass_make_import_list’ was not declared in this scope
04-Mar-2015 10:14:01	../src/binding.cpp:45: error: ‘struct sass_context_wrapper’ has no member named ‘imports’
04-Mar-2015 10:14:01	../src/binding.cpp:45: error: ‘sass_make_import_entry’ was not declared in this scope
04-Mar-2015 10:14:01	../src/binding.cpp:48: error: ‘struct sass_context_wrapper’ has no member named ‘imports’
04-Mar-2015 10:14:01	../src/binding.cpp:48: error: ‘sass_make_import_list’ was not declared in this scope
04-Mar-2015 10:14:01	../src/binding.cpp:49: error: ‘struct sass_context_wrapper’ has no member named ‘imports’
04-Mar-2015 10:14:01	../src/binding.cpp:49: error: ‘sass_make_import_entry’ was not declared in this scope
04-Mar-2015 10:14:01	../src/binding.cpp: In function ‘Sass_Import** sass_importer(const char*, const char*, void*)’:
04-Mar-2015 10:14:01	../src/binding.cpp:106: error: ‘struct sass_context_wrapper’ has no member named ‘imports’
04-Mar-2015 10:14:01	../src/binding.cpp: In function ‘void extract_options(v8::Local<v8::Object>, void*, sass_context_wrapper*, bool, bool)’:
04-Mar-2015 10:14:01	../src/binding.cpp:118: error: ‘sass_file_context_get_context’ was not declared in this scope
04-Mar-2015 10:14:01	../src/binding.cpp:122: error: ‘sass_data_context_get_context’ was not declared in this scope
04-Mar-2015 10:14:01	../src/binding.cpp:125: error: ‘sass_context_get_options’ was not declared in this scope
04-Mar-2015 10:14:01	../src/binding.cpp:146: error: ‘sass_make_importer’ was not declared in this scope
04-Mar-2015 10:14:01	../src/binding.cpp:146: error: ‘sass_option_set_importer’ was not declared in this scope
04-Mar-2015 10:14:01	../src/binding.cpp:150: error: ‘sass_option_set_input_path’ was not declared in this scope
04-Mar-2015 10:14:01	../src/binding.cpp:153: error: ‘sass_option_set_output_path’ was not declared in this scope
04-Mar-2015 10:14:01	../src/binding.cpp:154: error: ‘Sass_Output_Style’ was not declared in this scope
04-Mar-2015 10:14:01	../src/binding.cpp:154: error: ‘sass_option_set_output_style’ was not declared in this scope
04-Mar-2015 10:14:01	../src/binding.cpp:155: error: ‘sass_option_set_is_indented_syntax_src’ was not declared in this scope
04-Mar-2015 10:14:01	../src/binding.cpp:156: error: ‘sass_option_set_source_comments’ was not declared in this scope
04-Mar-2015 10:14:01	../src/binding.cpp:157: error: ‘sass_option_set_omit_source_map_url’ was not declared in this scope
04-Mar-2015 10:14:01	../src/binding.cpp:158: error: ‘sass_option_set_source_map_embed’ was not declared in this scope
04-Mar-2015 10:14:01	../src/binding.cpp:159: error: ‘sass_option_set_source_map_contents’ was not declared in this scope
04-Mar-2015 10:14:01	../src/binding.cpp:160: error: ‘sass_option_set_source_map_file’ was not declared in this scope
04-Mar-2015 10:14:01	../src/binding.cpp:161: error: ‘sass_option_set_include_path’ was not declared in this scope
04-Mar-2015 10:14:01	../src/binding.cpp:162: error: ‘sass_option_set_precision’ was not declared in this scope
04-Mar-2015 10:14:01	../src/binding.cpp: At global scope:
04-Mar-2015 10:14:01	../src/binding.cpp:165: error: ‘Sass_Context’ has not been declared
04-Mar-2015 10:14:01	../src/binding.cpp: In function ‘void get_stats(sass_context_wrapper*, int*)’:
04-Mar-2015 10:14:01	../src/binding.cpp:168: error: ‘sass_context_get_included_files’ was not declared in this scope
04-Mar-2015 10:14:01	../src/binding.cpp:172: error: ‘nullptr’ was not declared in this scope
04-Mar-2015 10:14:01	../src/binding.cpp: At global scope:
04-Mar-2015 10:14:01	../src/binding.cpp:180: error: ‘Sass_Context’ has not been declared
04-Mar-2015 10:14:01	../src/binding.cpp: In function ‘int get_result(sass_context_wrapper*, int*, bool)’:
04-Mar-2015 10:14:01	../src/binding.cpp:183: error: ‘sass_context_get_error_status’ was not declared in this scope
04-Mar-2015 10:14:01	../src/binding.cpp:186: error: ‘sass_context_get_output_string’ was not declared in this scope
04-Mar-2015 10:14:01	../src/binding.cpp:187: error: ‘sass_context_get_source_map_string’ was not declared in this scope
04-Mar-2015 10:14:01	../src/binding.cpp:198: error: ‘sass_context_get_error_json’ was not declared in this scope
04-Mar-2015 10:14:01	../src/binding.cpp: In function ‘void make_callback(uv_work_t*)’:
04-Mar-2015 10:14:01	../src/binding.cpp:212: error: ‘sass_data_context_get_context’ was not declared in this scope
04-Mar-2015 10:14:01	../src/binding.cpp:215: error: ‘sass_file_context_get_context’ was not declared in this scope
04-Mar-2015 10:14:01	../src/binding.cpp:218: error: cannot convert ‘Sass_Context*’ to ‘int*’ for argument ‘2’ to ‘int get_result(sass_context_wrapper*, int*, bool)’
04-Mar-2015 10:14:01	../src/binding.cpp:226: error: ‘sass_context_get_error_json’ was not declared in this scope
04-Mar-2015 10:14:01	../src/binding.cpp: In function ‘v8::Handle<v8::Value> render(const v8::Arguments&)’:
04-Mar-2015 10:14:01	../src/binding.cpp:248: error: ‘sass_make_data_context’ was not declared in this scope
04-Mar-2015 10:14:01	../src/binding.cpp: In function ‘v8::Handle<v8::Value> render_sync(const v8::Arguments&)’:
04-Mar-2015 10:14:01	../src/binding.cpp:265: error: ‘sass_make_data_context’ was not declared in this scope
04-Mar-2015 10:14:01	../src/binding.cpp:266: error: ‘sass_data_context_get_context’ was not declared in this scope
04-Mar-2015 10:14:01	../src/binding.cpp:273: error: cannot convert ‘Sass_Context*’ to ‘int*’ for argument ‘2’ to ‘int get_result(sass_context_wrapper*, int*, bool)’
04-Mar-2015 10:14:01	../src/binding.cpp: In function ‘v8::Handle<v8::Value> render_file(const v8::Arguments&)’:
04-Mar-2015 10:14:01	../src/binding.cpp:285: error: ‘sass_make_file_context’ was not declared in this scope
04-Mar-2015 10:14:01	../src/binding.cpp: In function ‘v8::Handle<v8::Value> render_file_sync(const v8::Arguments&)’:
04-Mar-2015 10:14:01	../src/binding.cpp:302: error: ‘sass_make_file_context’ was not declared in this scope
04-Mar-2015 10:14:01	../src/binding.cpp:303: error: ‘sass_file_context_get_context’ was not declared in this scope
04-Mar-2015 10:14:01	../src/binding.cpp:309: error: cannot convert ‘Sass_Context*’ to ‘int*’ for argument ‘2’ to ‘int get_result(sass_context_wrapper*, int*, bool)’
04-Mar-2015 10:14:01	make: Leaving directory `/var/opt/bamboo/xml-data/build-dir/WEB-ND-COMP/design/node_modules/grunt-kss/node_modules/kss/node_modules/node-sass/build'
04-Mar-2015 10:14:01	make: *** [Release/obj.target/binding/src/binding.o] Error 1
04-Mar-2015 10:14:01	gyp ERR! build error
04-Mar-2015 10:14:01	gyp ERR! stack Error: `make` failed with exit code: 2
04-Mar-2015 10:14:01	gyp ERR! stack     at ChildProcess.onExit (/var/opt/bamboo/xml-data/build-dir/WEB-ND-COMP/design/node_modules/grunt-kss/node_modules/kss/node_modules/node-sass/node_modules/pangyp/lib/build.js:271:23)
04-Mar-2015 10:14:01	gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
04-Mar-2015 10:14:01	gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
04-Mar-2015 10:14:01	gyp ERR! System Linux 2.6.32-431.17.1.el6.x86_64
04-Mar-2015 10:14:01	gyp ERR! command "/usr/bin/node" "/var/opt/bamboo/xml-data/build-dir/WEB-ND-COMP/design/node_modules/grunt-kss/node_modules/kss/node_modules/node-sass/node_modules/pangyp/bin/node-gyp" "rebuild"
04-Mar-2015 10:14:01	gyp ERR! cwd /var/opt/bamboo/xml-data/build-dir/WEB-ND-COMP/design/node_modules/grunt-kss/node_modules/kss/node_modules/node-sass
04-Mar-2015 10:14:01	gyp ERR! node -v v0.10.33
04-Mar-2015 10:14:01	gyp ERR! pangyp -v v2.1.0
04-Mar-2015 10:14:01	gyp ERR! not ok
04-Mar-2015 10:14:01	Build failed
```

**Comment by xzyfer** [comment]
Hi @Yobikap, how are you installing node-sass? If looks like you're using an unreleased/unstable version.

**Comment by Yobikap** [comment]
You can close this issue, you were right, I was using a wrong version.
