### ISSUE TITLE
io.js 1.4.3 OS X build failure

### ISSUE THREAD

**Issue by okket** [sass/node-sass#739]
When I try to install node-sass with io.js 1.4.3 on OS X Yosemite, I get the following error:

```
> node-sass@2.0.1 install /usr/local/lib/node_modules/node-sass
> node scripts/install.js

Can not download file from https://raw.githubusercontent.com/sass/node-sass-binaries/v2.0.1/darwin-x64-iojs-1.4/binding.node

> node-sass@2.0.1 postinstall /usr/local/lib/node_modules/node-sass
> node scripts/build.js

module.js:322
    throw err;
          ^
Error: Cannot find module '/usr/local/lib/node_modules/node-sass/node_modules/pangyp/bin/node-gyp'
    at Function.Module._resolveFilename (module.js:320:15)
    at Function.Module._load (module.js:262:25)
    at Function.Module.runMain (module.js:485:10)
    at startup (node.js:112:16)
    at node.js:863:3
Build failed
```

When I manually install pangyp in the node_modules directory (inside node-sass), it compiles and works.  Maybe pangyp should not only be dev dependency but default? Or would that be too much burden for the 99% which run the official node distribution?

**Comment by okket** [comment]
Oh, I see pangyp is a default dependency in master. Sorry for fuss. Waiting for a new release.
