### ISSUE TITLE
iojs install node-sass failed

### ISSUE THREAD

**Issue by willin** [sass/node-sass#747]
```
> node-sass@2.0.1 install /Users/willin/Documents/wulian/html/router-manage-2/node_modules/node-sass
> node scripts/install.js

Can not download file from https://raw.githubusercontent.com/sass/node-sass-binaries/v2.0.1/darwin-x64-iojs-1.4/binding.node

> node-sass@2.0.1 postinstall /Users/willin/Documents/wulian/html/router-manage-2/node_modules/node-sass
> node scripts/build.js

module.js:322
    throw err;
          ^
Error: Cannot find module '/Users/willin/Documents/wulian/html/router-manage-2/node_modules/node-sass/node_modules/pangyp/bin/node-gyp'
    at Function.Module._resolveFilename (module.js:320:15)
    at Function.Module._load (module.js:262:25)
    at Function.Module.runMain (module.js:485:10)
    at startup (node.js:112:16)
    at node.js:863:3
Build failed
```

**Comment by am11** [comment]
io.js v1.4 will be supported by next version of node-sass.
