### ISSUE TITLE
NPM exit status 1 on update

### ISSUE THREAD

**Issue by paynoattn** [sass/node-sass#759]
> node-sass@1.2.3 install /Users/cpawlukiewicz/www/www-ushealthresources-com/medsub-landing/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /Users/cpawlukiewicz/www/www-ushealthresources-com/medsub-landing/node_modules/node-sass/vendor/darwin-x64/binding.node

> node-sass@1.2.3 postinstall /Users/cpawlukiewicz/www/www-ushealthresources-com/medsub-landing/node_modules/node-sass
> node scripts/build.js

`darwin-x64` exists; testing
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/cpawlukiewicz/www/www-ushealthresources-com/medsub-landing/node_modules/node-sass/lib/index.js:181:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "update"
npm ERR! node v0.12.0
npm ERR! npm  v2.6.1
npm ERR! code ELIFECYCLE

npm ERR! node-sass@1.2.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@1.2.3 postinstall script 'node scripts/build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/cpawlukiewicz/www/www-ushealthresources-com/medsub-landing/npm-debug.log

How should I send the log?

**Comment by paynoattn** [comment]
Had a bad node-modules install apparently. Removed and rerand npm install to fix.
