### ISSUE TITLE
Error: Module did not self-register.

### ISSUE THREAD

**Issue by babsonmatt** [sass/node-sass#765]
Windows 7 x64 / iojs 1.5.1

Installed/compiled successfully with: npm install node-sass -g --msvs_version=2013e

Running `node-sass` gives the following:

```
$ node-sass
module.js:339
  Module._extensions[extension](this, filename);
                               ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:339:32)
    at Function.Module._load (module.js:294:12)
    at Module.require (module.js:349:17)
    at require (module.js:368:17)
    at Object.<anonymous> (c:\Users\Matt\AppData\Roaming\npm\node_modules\node-sass\lib\index.js:14:15)
    at Module._compile (module.js:444:26)
    at Object.Module._extensions..js (module.js:462:10)
    at Module.load (module.js:339:32)
    at Function.Module._load (module.js:294:12)
```

**Comment by am11** [comment]
You don't need `--msvs_version=2013e` switch.

This is a known issue with io.js with Windows: https://github.com/iojs/io.js/issues/751.

You need to make sure that your invocation call to `node-sass` should be prefixed by `iojs` not `node`. There is a `node.exe` packaged inside `iojs.msi`, which is a (bad) replacement for Linux symlink. Read more: https://github.com/iojs/io.js/issues/751#issuecomment-76609731.

Solutions:
* Use [nvmw](https://github.com/hakobera/nvmw), to fast switch between node/io.js versions, because they have their own workaround for it: they simulate Linux symlink with `node.cmd`.
* Explicitly prefix your command with `iojs`.

**Comment by babsonmatt** [comment]
Thanks for the hep! Much appreciated.
