### ISSUE TITLE
node-sass not installing correclty due to devDependency pangyp

### ISSUE THREAD

**Issue by thejsj** [sass/node-sass#771]
It seems like `npm install node-sass` is not getting installed correctly, because it's not getting built because it's not installing the `pangyp` package.

No clue why exactly this is happening. `pangyp` is listed as a devDependency, but it should still get installed.

-----
### Debugging Process

I kept getting this error while trying to run gulp node-sass:

```
/Users/jorgesilvajetter/Sites/2015/split-or-steal/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:22
    throw new Error('`libsass` bindings not found. Try reinstalling `node-sass
          ^
Error: `libsass` bindings not found. Try reinstalling `node-sass`?
    at getBinding (/Users/jorgesilvajetter/Sites/2015/split-or-steal/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:22:11)
    at Object.<anonymous> (/Users/jorgesilvajetter/Sites/2015/split-or-steal/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:188:23)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/jorgesilvajetter/Sites/2015/split-or-steal/node_modules/gulp-sass/index.js:3:17)
    at Module._compile (module.js:460:26)
```
After reinstalling it in multiple versions of node, I got started looking into the package itself. 

I noticed that the error came from here: 

```javascript
function getBinding() {
  var candidates = [
    path.join(__dirname, '..', 'build', 'Debug', 'binding.node'),
    path.join(__dirname, '..', 'build', 'Release', 'binding.node'),
    path.join(__dirname, '..', 'vendor', process.sassBinaryName, 'binding.node')
  ];

  var candidate = candidates.filter(fs.existsSync).shift();

  if (!candidate) {
    throw new Error('`libsass` bindings not found. Try reinstalling `node-sass`?');
  }

  return candidate;
}
```
I requires these three directories to exist, but the `build` directory didn't exist.
I then went to `package.json` and saw the `postinstall` script and ran it. 
```
$ npm run postinstall

> node-sass@2.0.1 postinstall /Users/jorgesilvajetter/Sites/2015/split-or-steal/node_modules/gulp-sass/node_modules/node-sass
> node scripts/build.js

module.js:338
    throw err;
          ^
Error: Cannot find module '/Users/jorgesilvajetter/Sites/2015/split-or-steal/node_modules/gulp-sass/node_modules/node-sass/node_modules/pangyp/bin/node-gyp'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
Build failed
```
Then I just intalled the `pangyp` module, ran `npm run postintall` and it worked.

**Comment by am11** [comment]
This issue has been fixed with node-sass `v3.0.0-alpha.0`.
