### ISSUE TITLE
libsass bindings not found with nw

### ISSUE THREAD

**Issue by hendore** [sass/node-sass#780]
I've installed node-sass as a dependency, I can confirm everything works as expected when running a script with ```node example.js``` however when I try to use node-sass from a node-webkit project ```nw example.html``` I get the following error.

```
[6708:0320/220558:ERROR:nw_shell.cc(335)] Error: `libsass` bindings not found. Try reinstalling `node-sass`?
```

Do I need to rebuild the bindings for the different environment?

**Comment by am11** [comment]
Which version of node.js, node-sass etc. and details how to reproduce the issue:
https://github.com/sass/node-sass/blob/master/CONTRIBUTING.md#bug-reports

**Comment by teejayhh** [comment]
I have the same issue. I tried to install node-sass@3.0.0-beta.2 into the grunt-sass project because I really need libsass 3.2 working. i am running the normal install routine inside of the the grunt sass project. the install script spits out the following. 
```
grunt-sass thomas$ npm install --save node-sass@3.0.0-beta.2
\
> node-sass@3.0.0-beta.2 install /Users/thomas/Desktop/awesome/node_modules/grunt-sass/node_modules/node-sass
> node scripts/install.js

Can not download file from:,https://github.com/sass/node-sass/releases/download//v3.0.0-beta.2/darwin-x64-14_binding.node

> node-sass@3.0.0-beta.2 postinstall /Users/thomas/Desktop/awesome/node_modules/grunt-sass/node_modules/node-sass
> node scripts/build.js

Building: /usr/local/bin/node node_modules/pangyp/bin/node-gyp rebuild --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
  CXX(target) Release/obj.target/libsass/src/libsass/ast.o
  CXX(target) Release/obj.target/libsass/src/libsass/base64vlq.o
  CXX(target) Release/obj.target/libsass/src/libsass/bind.o
  CC(target) Release/obj.target/libsass/src/libsass/cencode.o
  CXX(target) Release/obj.target/libsass/src/libsass/constants.o
........
```

hope someone can help.

**Comment by am11** [comment]
> install script spits out the following

1. It looks like it is manually building the binary just fine.
2. It is manually building the binary because we are yet to release prebuilding binaries for beta. So if you don't want it to manually build, you can use `node-sass@alpha` tag or github release tag alpha.1: https://github.com/sass/node-sass/releases/tag/v3.0.0-alpha.1.

**Comment by Munter** [comment]
I'm having the same issue.

This is my install log:

```
$ npm install node-sass@beta
 
> node-sass@3.0.0-beta.2 install /home/munter/git/fusile/node_modules/node-sass
> node scripts/install.js

Can not download file from:,https://github.com/sass/node-sass/releases/download//v3.0.0-beta.2/linux-x64-11_binding.node
 
> node-sass@3.0.0-beta.2 postinstall /home/munter/git/fusile/node_modules/node-sass
> node scripts/build.js

Building: /home/munter/.nvm/v0.10.29/bin/node node_modules/pangyp/bin/node-gyp rebuild --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
make: Entering directory `/home/munter/git/fusile/node_modules/node-sass/build'
  CXX(target) Release/obj.target/libsass/src/libsass/ast.o
  CXX(target) Release/obj.target/libsass/src/libsass/base64vlq.o
  CXX(target) Release/obj.target/libsass/src/libsass/bind.o
  CC(target) Release/obj.target/libsass/src/libsass/cencode.o
  CXX(target) Release/obj.target/libsass/src/libsass/constants.o
  CXX(target) Release/obj.target/libsass/src/libsass/context.o
  CXX(target) Release/obj.target/libsass/src/libsass/contextualize.o
  CXX(target) Release/obj.target/libsass/src/libsass/cssize.o
  CXX(target) Release/obj.target/libsass/src/libsass/emitter.o
  CXX(target) Release/obj.target/libsass/src/libsass/error_handling.o
  CXX(target) Release/obj.target/libsass/src/libsass/eval.o
  CXX(target) Release/obj.target/libsass/src/libsass/expand.o
  CXX(target) Release/obj.target/libsass/src/libsass/extend.o
  CXX(target) Release/obj.target/libsass/src/libsass/file.o
  CXX(target) Release/obj.target/libsass/src/libsass/functions.o
  CXX(target) Release/obj.target/libsass/src/libsass/inspect.o
  CXX(target) Release/obj.target/libsass/src/libsass/json.o
  CXX(target) Release/obj.target/libsass/src/libsass/node.o
  CXX(target) Release/obj.target/libsass/src/libsass/output.o
  CXX(target) Release/obj.target/libsass/src/libsass/parser.o
  CXX(target) Release/obj.target/libsass/src/libsass/plugins.o
  CXX(target) Release/obj.target/libsass/src/libsass/position.o
  CXX(target) Release/obj.target/libsass/src/libsass/prelexer.o
  CXX(target) Release/obj.target/libsass/src/libsass/remove_placeholders.o
  CXX(target) Release/obj.target/libsass/src/libsass/sass.o
  CXX(target) Release/obj.target/libsass/src/libsass/sass2scss.o
  CXX(target) Release/obj.target/libsass/src/libsass/sass_context.o
  CXX(target) Release/obj.target/libsass/src/libsass/sass_functions.o
  CXX(target) Release/obj.target/libsass/src/libsass/sass_util.o
  CXX(target) Release/obj.target/libsass/src/libsass/sass_values.o
  CXX(target) Release/obj.target/libsass/src/libsass/source_map.o
  CXX(target) Release/obj.target/libsass/src/libsass/to_c.o
  CXX(target) Release/obj.target/libsass/src/libsass/to_string.o
  CXX(target) Release/obj.target/libsass/src/libsass/units.o
  CXX(target) Release/obj.target/libsass/src/libsass/utf8_string.o
  CXX(target) Release/obj.target/libsass/src/libsass/util.o
  AR(target) Release/obj.target/sass.a
  COPY Release/sass.a
make: Leaving directory `/home/munter/git/fusile/node_modules/node-sass/build'
Build succeeded but target not found
node-sass@3.0.0-beta.2 node_modules/node-sass
├── get-stdin@4.0.1
├── nan@1.7.0
├── chalk@1.0.0 (escape-string-regexp@1.0.3, ansi-styles@2.0.1, supports-color@1.3.1, strip-ansi@2.0.1, has-ansi@1.0.3)
├── meow@3.1.0 (object-assign@2.0.0, camelcase-keys@1.0.0, indent-string@1.2.1)
├── npmconf@2.1.1 (uid-number@0.0.5, osenv@0.1.0, ini@1.3.3, inherits@2.0.1, config-chain@1.1.8, semver@4.3.1, nopt@3.0.1, once@1.3.1)
├── sass-graph@1.2.0 (commander@2.7.1, lodash@2.4.1, glob@4.5.3)
├── request@2.54.0 (caseless@0.9.0, json-stringify-safe@5.0.0, aws-sign2@0.5.0, forever-agent@0.6.0, form-data@0.2.0, stringstream@0.0.4, oauth-sign@0.6.0, tunnel-agent@0.4.0, isstream@0.1.2, node-uuid@1.4.3, qs@2.4.1, combined-stream@0.0.7, mime-types@2.0.10, tough-cookie@0.12.1, bl@0.9.4, hawk@2.3.1, har-validator@1.4.0, http-signature@0.10.1)
└── pangyp@2.1.0 (which@1.0.9, osenv@0.1.0, graceful-fs@3.0.6, nopt@3.0.1, semver@4.2.2, fstream@1.0.4, glob@4.3.5, npmlog@1.0.0, tar@1.0.3, request@2.51.0)
```

Result in node: 

```
$ node 
> require('node-sass')
Error: `libsass` bindings not found. Try reinstalling `node-sass`?
    at Object.sass.getBinaryPath (/home/munter/git/fusile/node_modules/node-sass/lib/extensions.js:146:11)
    at Object.<anonymous> (/home/munter/git/fusile/node_modules/node-sass/lib/index.js:14:36)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at repl:1:2
    at REPLServer.self.eval (repl.js:110:21)
```

I find the following of the install log most interesting:

```
> node scripts/install.js

Can not download file from:,https://github.com/sass/node-sass/releases/download//v3.0.0-beta.2/linux-x64-11_binding.node
```

and 

```
make: Leaving directory `/home/munter/git/fusile/node_modules/node-sass/build'
Build succeeded but target not found
```

**Comment by am11** [comment]
@Munter, it indeed is interesting. Would you open an separate issue? Because this is a different sort of a bug.

**Comment by am11** [comment]
v2.1.1 stable and v3 beta are released. If you are still seeing installation issue, feel free to reopen this.
