### ISSUE TITLE
Can't install node-sass beta: libsass.gyp not found

### ISSUE THREAD

**Issue by donaldallen** [sass/node-sass#802]
```sudo npm -g install node-sass@beta --unsafe-perm --verbose```

```
gyp: libsass.gyp not found (cwd: /usr/local/lib/node_modules/node-sass) while loading dependencies of binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/node-sass/node_modules/pangyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/node-sass/node_modules/pangyp/bin/node-gyp" "rebuild" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /usr/local/lib/node_modules/node-sass
gyp ERR! node -v v0.12.1
gyp ERR! pangyp -v v2.1.0
gyp ERR! not ok
Build failed
```

Any ideas why this may be happening? I've cleared the npm cache.

**Comment by am11** [comment]
Thanks for reporting this issue.

This is fixed by d89b901.

We are still working on pre-build binaries for beta, but if you want to build the binaries manually, you can go ahead and try `npm install node-sass@beta`. You would need to have gcc/g++ 4.7+ python2[6/7] installed in your system.
