### ISSUE TITLE
Installing 3.0.0@beta fails

### ISSUE THREAD

**Issue by emilbayes** [sass/node-sass#805]
Hi,

I'm running `iojs@1.6.1` and `npm@2.7.1` and `node-sass@3.0.0-alpha.0` and it works great!
However I just tried to upgrade to `node-sass@beta` and get the following error:

```
Error: `libsass` bindings not found. Try reinstalling `node-sass`?
    at Object.sass.getBinaryPath (/usr/local/app/node_modules/node-sass/lib/extensions.js:146:11)
    at Object.<anonymous> (/usr/local/app/node_modules/node-sass/lib/index.js:14:36)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:428:10)
    at Module.load (module.js:335:32)
    at Function.Module._load (module.js:290:12)
    at Module.require (module.js:345:17)
    at require (module.js:364:17)
    at Object.<anonymous> (/usr/local/app/tasks/lib/sass-edge.js:5:12)
    at Module._compile (module.js:410:26)

npm ERR! Darwin 14.1.0
npm ERR! argv "/usr/local/var/nvm/versions/io.js/v1.6.1/bin/iojs" "/usr/local/var/nvm/versions/io.js/v1.6.1/bin/npm" "run" "bundle"
npm ERR! node v1.6.1
npm ERR! npm  v2.7.1
npm ERR! code ELIFECYCLE
npm ERR! app@0.0.0 bundle: `npm run clean && gulp bundle`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the app@0.0.0 bundle script 'npm run clean && gulp bundle'.
npm ERR! This is most likely a problem with the app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run clean && gulp bundle
npm ERR! You can get their info via:
npm ERR!     npm owner ls app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/app/npm-debug.log
```

I believe this is the same bug @Munter is having in #780. Here's the output I get upon rebuilding:

```
-
> node-sass@3.0.0-beta.2 install /usr/local/app/node_modules/node-sass
> node scripts/install.js

Can not download file from:,https://github.com/sass/node-sass/releases/download//v3.0.0-beta.2/darwin-x64-43_binding.node

> node-sass@3.0.0-beta.2 postinstall /usr/local/app/node_modules/node-sass
> node scripts/build.js

Building: /usr/local/var/nvm/versions/io.js/v1.6.1/bin/iojs node_modules/pangyp/bin/node-gyp rebuild --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
  CXX(target) Release/obj.target/libsass/src/libsass/ast.o
  CXX(target) Release/obj.target/libsass/src/libsass/base64vlq.o
  CXX(target) Release/obj.target/libsass/src/libsass/bind.o
  CC(target) Release/obj.target/libsass/src/libsass/cencode.o
  CXX(target) Release/obj.target/libsass/src/libsass/constants.o
  CXX(target) Release/obj.target/libsass/src/libsass/context.o
  CXX(target) Release/obj.target/libsass/src/libsass/contextualize.o
  CXX(target) Release/obj.target/libsass/src/libsass/cssize.o
  CXX(target) Release/obj.target/libsass/src/libsass/emitter.o
  CXX(target) Release/obj.target/libsass/src/libsass/error_handling.o
  CXX(target) Release/obj.target/libsass/src/libsass/eval.o
  CXX(target) Release/obj.target/libsass/src/libsass/expand.o
  CXX(target) Release/obj.target/libsass/src/libsass/extend.o
  CXX(target) Release/obj.target/libsass/src/libsass/file.o
  CXX(target) Release/obj.target/libsass/src/libsass/functions.o
  CXX(target) Release/obj.target/libsass/src/libsass/inspect.o
  CXX(target) Release/obj.target/libsass/src/libsass/json.o
  CXX(target) Release/obj.target/libsass/src/libsass/node.o
  CXX(target) Release/obj.target/libsass/src/libsass/output.o
  CXX(target) Release/obj.target/libsass/src/libsass/parser.o
  CXX(target) Release/obj.target/libsass/src/libsass/plugins.o
  CXX(target) Release/obj.target/libsass/src/libsass/position.o
  CXX(target) Release/obj.target/libsass/src/libsass/prelexer.o
  CXX(target) Release/obj.target/libsass/src/libsass/remove_placeholders.o
  CXX(target) Release/obj.target/libsass/src/libsass/sass.o
  CXX(target) Release/obj.target/libsass/src/libsass/sass2scss.o
  CXX(target) Release/obj.target/libsass/src/libsass/sass_context.o
  CXX(target) Release/obj.target/libsass/src/libsass/sass_functions.o
  CXX(target) Release/obj.target/libsass/src/libsass/sass_util.o
  CXX(target) Release/obj.target/libsass/src/libsass/sass_values.o
  CXX(target) Release/obj.target/libsass/src/libsass/source_map.o
  CXX(target) Release/obj.target/libsass/src/libsass/to_c.o
  CXX(target) Release/obj.target/libsass/src/libsass/to_string.o
  CXX(target) Release/obj.target/libsass/src/libsass/units.o
  CXX(target) Release/obj.target/libsass/src/libsass/utf8_string.o
  CXX(target) Release/obj.target/libsass/src/libsass/util.o
  LIBTOOL-STATIC Release/sass.a
Build succeeded but target not found
node-sass@3.0.0-beta.2 node_modules/node-sass
├── get-stdin@4.0.1
├── nan@1.7.0
├── chalk@1.0.0 (escape-string-regexp@1.0.3, ansi-styles@2.0.1, supports-color@1.3.1, strip-ansi@2.0.1, has-ansi@1.0.3)
├── meow@3.1.0 (object-assign@2.0.0, camelcase-keys@1.0.0, minimist@1.1.1, indent-string@1.2.1)
├── npmconf@2.1.1 (uid-number@0.0.5, inherits@2.0.1, osenv@0.1.0, ini@1.3.3, once@1.3.1, nopt@3.0.1, config-chain@1.1.8, semver@4.3.1)
├── sass-graph@1.2.0 (commander@2.7.1, glob@4.5.3)
├── gaze@0.5.1 (globule@0.1.0)
├── request@2.54.0 (caseless@0.9.0, json-stringify-safe@5.0.0, aws-sign2@0.5.0, forever-agent@0.6.0, stringstream@0.0.4, oauth-sign@0.6.0, tunnel-agent@0.4.0, isstream@0.1.2, node-uuid@1.4.3, qs@2.4.1, combined-stream@0.0.7, form-data@0.2.0, mime-types@2.0.10, http-signature@0.10.1, bl@0.9.4, tough-cookie@0.12.1, hawk@2.3.1, har-validator@1.4.0)
└── pangyp@2.1.0 (which@1.0.9, osenv@0.1.0, rimraf@2.2.8, graceful-fs@3.0.6, nopt@3.0.1, glob@4.3.5, fstream@1.0.4, semver@4.2.2, minimatch@2.0.4, tar@1.0.3, npmlog@1.0.0, request@2.51.0)
```

I'm not sure if this line is expected or not:

```
Build succeeded but target not found
```

**Comment by Munter** [comment]
This does indeed look identical to my experience

**Comment by am11** [comment]
We are still [waiting for binaries](https://github.com/sass/node-sass/issues/800), and haven't create a release on GitHub for that reason.

The reason I published the release was so downstream devs can start experimenting with this cool new feature called Custom Function (using manual build fallback), but as per @Munter's report, the manual build process is broken because we had another brand new feature since alpha, "isolated libsass binaries", which resulted in revealing another limitation of `npm publish` as described here: https://github.com/sass/node-sass/pull/763#issuecomment-86293997.

I will see if I could gather the binaries and rollback that unbunding feature (or fix the issue) by the end of the day, otherwise I will un-publish the beta.

**Comment by am11** [comment]
The issue with manual installation is fixed and prebuild binaries for Linux and Windows are deployed. More platform prebuild binaries will be added subsequently.

https://github.com/sass/node-sass/releases/tag/v3.0.0-beta.4

**Comment by Munter** [comment]
Thanks for moving so quickly. Much appreciated! :+1:

**Comment by emilbayes** [comment]
:+1:

**Comment by mohsen1** [comment]
I'm still getting errors with `3.0.0-beta.4`

```
~/P/z/hail (master|✔) ❯❯ rm -rf node_modules/;
~/P/z/hail (master|✔) ❯❯ npm install node-sass@3.0.0-beta.4
npm WARN package.json hail@1.0.0 No repository field.
npm WARN package.json hail@1.0.0 No license field.
/
> node-sass@3.0.0-beta.4 install <<OMITTED>>hail/node_modules/node-sass
> node scripts/install.js

Can not download file from:,https://github.com/sass/node-sass/releases/download/v3.0.0-beta.4/darwin-x64-45_binding.node

> node-sass@3.0.0-beta.4 postinstall <<OMITTED>>hail/node_modules/node-sass
> node scripts/build.js

Building: /usr/local/bin/iojs node_modules/pangyp/bin/node-gyp rebuild
gyp: /Users/mohsen/.node-gyp/3.0.0/common.gypi not found (cwd: <<OMITTED>>hail/node_modules/node-sass) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (<<OMITTED>>hail/node_modules/node-sass/node_modules/pangyp/lib/configure.js:345:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.4.0
gyp ERR! command "/usr/local/bin/iojs" "<<OMITTED>>hail/node_modules/node-sass/node_modules/pangyp/bin/node-gyp" "rebuild"
gyp ERR! cwd <<OMITTED>>hail/node_modules/node-sass
gyp ERR! node -v v3.0.0
gyp ERR! pangyp -v v2.2.1
gyp ERR! not ok
Build failed
node-sass@3.0.0-beta.4 node_modules/node-sass
├── get-stdin@4.0.1
├── nan@1.9.0
├── mkdirp@0.5.1 (minimist@0.0.8)
├── chalk@1.1.0 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, strip-ansi@3.0.0, has-ansi@2.0.0)
├── gaze@0.5.1 (globule@0.1.0)
├── sass-graph@1.3.0 (lodash@2.4.2, commander@2.8.1, glob@4.5.3)
├── npmconf@2.1.2 (uid-number@0.0.5, ini@1.3.4, inherits@2.0.1, once@1.3.2, semver@4.3.6, osenv@0.1.3, nopt@3.0.3, config-chain@1.1.9)
├── meow@3.3.0 (object-assign@3.0.0, minimist@1.1.3, camelcase-keys@1.0.0, indent-string@1.2.2)
├── pangyp@2.2.1 (which@1.0.9, rimraf@2.2.8, graceful-fs@3.0.8, glob@4.3.5, fstream@1.0.7, semver@4.3.6, minimatch@2.0.10, osenv@0.1.3, nopt@3.0.3, tar@1.0.3, npmlog@1.0.0, request@2.51.0)
└── request@2.60.0 (aws-sign2@0.5.0, forever-agent@0.6.1, caseless@0.11.0, stringstream@0.0.4, oauth-sign@0.8.0, tunnel-agent@0.4.1, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, node-uuid@1.4.3, qs@4.0.0, combined-stream@1.0.5, form-data@1.0.0-rc3, mime-types@2.1.4, http-signature@0.11.0, tough-cookie@2.0.0, bl@1.0.0, har-validator@1.8.0, hawk@3.1.0)
~/P/z/hail (master|✔) ❯❯
```

Alos:
```
❯❯ curl https://github.com/sass/node-sass/releases/download/v3.0.0-beta.4/darwin-x64-45_binding.node
{"error":"Not Found"}⏎
```

**Comment by xzyfer** [comment]
@mohsen1 Please do not comment on closed issues in the future.

We do not support io.js 3.0 yet. Please see #1053 and #1054.

**Comment by mohsen1** [comment]
@xzyfer just noticed and deleted my comment before you commented here
