### ISSUE TITLE
linux-x64-iojs-1.6 node binding file missing preventing install

### ISSUE THREAD

**Issue by dworzanski** [sass/node-sass#811]
Hello,

I am trying to install [harp](https://github.com/sintaxi/harp) for which node-sass is a dependency.

I am running CentOS 7 with io.js 1.6.2 (latest).

I am getting an error that `https://raw.githubusercontent.com/sass/node-sass-binaries/v2.0.1/linux-x64-iojs-1.6/binding.node` cannot be downloaded.

```
$ pwd
/apps/static-server
$ npm install harp --save
npm WARN package.json static-server@0.0.1 No description
npm WARN package.json static-server@0.0.1 No repository field.
npm WARN package.json static-server@0.0.1 No README data
-
> node-sass@2.0.1 install /apps/static-server/node_modules/harp/node_modules/terraform/node_modules/node-sass
> node scripts/install.js

Can not download file from https://raw.githubusercontent.com/sass/node-sass-binaries/v2.0.1/linux-x64-iojs-1.6/binding.node

> node-sass@2.0.1 postinstall /apps/static-server/node_modules/harp/node_modules/terraform/node_modules/node-sass
> node scripts/build.js

module.js:318
    throw err;
          ^
Error: Cannot find module '/apps/static-server/node_modules/harp/node_modules/terraform/node_modules/node-sass/node_modules/pangyp/bin/node-gyp'
    at Function.Module._resolveFilename (module.js:316:15)
    at Function.Module._load (module.js:258:25)
    at Function.Module.runMain (module.js:451:10)
    at startup (node.js:123:18)
    at node.js:868:3
Build failed
harp@0.15.2 node_modules/harp
├── envy-json@0.2.0
├── commander@2.0.0
├── mime@1.2.11
├── async@0.2.9
├── fs-extra@0.6.4 (jsonfile@1.0.1, rimraf@2.2.8, ncp@0.4.2, mkdirp@0.3.5)
├── download-github-repo@0.1.3 (download@0.1.19)
├── connect@2.9.0 (methods@0.0.1, uid2@0.0.2, pause@0.0.1, cookie-signature@1.0.1, fresh@0.2.0, qs@0.6.5, bytes@0.2.0, buffer-crc32@0.2.1, cookie@0.1.0, send@0.1.4, debug@2.1.3, multiparty@2.1.8)
└── terraform@0.10.3 (lru-cache@2.5.0, marked@0.3.3, ejs@1.0.0, coffee-script@1.9.0, minify@0.3.0, stylus@0.47.3, jade@0.35.0, autoprefixer@5.1.0, less@1.7.5, node-sass@2.0.1)
```

When I try to in install node-sass by itself I get the same error:

```
$ pwd
/apps/static-server
$ npm install node-sass
npm WARN package.json static-server@0.0.1 No description
npm WARN package.json static-server@0.0.1 No repository field.
npm WARN package.json static-server@0.0.1 No README data
/
> node-sass@2.0.1 install /apps/static-server/node_modules/node-sass
> node scripts/install.js

Can not download file from https://raw.githubusercontent.com/sass/node-sass-binaries/v2.0.1/linux-x64-iojs-1.6/binding.node

> node-sass@2.0.1 postinstall /apps/static-server/node_modules/node-sass
> node scripts/build.js

module.js:318
    throw err;
          ^
Error: Cannot find module '/apps/static-server/node_modules/node-sass/node_modules/pangyp/bin/node-gyp'
    at Function.Module._resolveFilename (module.js:316:15)
    at Function.Module._load (module.js:258:25)
    at Function.Module.runMain (module.js:451:10)
    at startup (node.js:123:18)
    at node.js:868:3
Build failed
node-sass@2.0.1 node_modules/node-sass
├── object-assign@2.0.0
├── get-stdin@4.0.1
├── replace-ext@0.0.1
├── cross-spawn@0.2.6 (lru-cache@2.5.0)
├── nan@1.7.0
├── chalk@0.5.1 (ansi-styles@1.1.0, escape-string-regexp@1.0.3, supports-color@0.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)
├── mkdirp@0.5.0 (minimist@0.0.8)
├── semver@4.3.2
├── shelljs@0.3.0
├── meow@3.1.0 (minimist@1.1.1, camelcase-keys@1.0.0, indent-string@1.2.1)
├── npmconf@2.1.1 (uid-number@0.0.5, inherits@2.0.1, osenv@0.1.0, ini@1.3.3, once@1.3.1, nopt@3.0.1, config-chain@1.1.8)
├── gaze@0.5.1 (globule@0.1.0)
├── request@2.54.0 (caseless@0.9.0, json-stringify-safe@5.0.0, aws-sign2@0.5.0, forever-agent@0.6.0, stringstream@0.0.4, oauth-sign@0.6.0, tunnel-agent@0.4.0, isstream@0.1.2, node-uuid@1.4.3, qs@2.4.1, combined-stream@0.0.7, form-data@0.2.0, mime-types@2.0.10, http-signature@0.10.1, bl@0.9.4, tough-cookie@0.12.1, har-validator@1.4.0, hawk@2.3.1)
├── mocha@2.2.1 (escape-string-regexp@1.0.2, supports-color@1.2.1, diff@1.0.8, growl@1.8.1, commander@2.3.0, debug@2.0.0, glob@3.2.3, jade@0.26.3)
└── sass-graph@1.2.0 (commander@2.7.1, glob@4.5.3, lodash@2.4.1)
```

**Comment by dworzanski** [comment]
Perhaps this is related to [Issue 791](https://github.com/sass/node-sass/pull/791)?

**Comment by dominicbarnes** [comment]
```
> node-sass@2.0.1 install /Users/dominic/dev/duojs/sass/node_modules/node-sass
> node scripts/install.js

Can not download file from https://raw.githubusercontent.com/sass/node-sass-binaries/v2.0.1/darwin-x64-iojs-0.11/binding.node
```

I get similar results on node 0.10, 0.11, 0.12 and even iojs. (1.6.2)

**Comment by am11** [comment]
io.js v1.6 will be supported by node-sass v3.0.0. Currently you can try the released alpha and beta.

**Comment by dominicbarnes** [comment]
I've tested `v3.0.0-beta.4`, and it appears to work, but I see the following:

```
> node-sass@3.0.0-beta.4 install /Users/dominic/dev/duojs/sass/node_modules/node-sass
> node scripts/install.js

Can not download file from:,https://github.com/sass/node-sass/releases/download/v3.0.0-beta.4/darwin-x64-11_binding.node
```

It still works despite the message above, but it's a little confusing at first.

**Comment by am11** [comment]
> Can not download file from

Because I am waiting for some Mac guy to spare sometime and contribute the binaries at https://github.com/sass/node-sass-binaries repo. Related: https://github.com/sass/node-sass-binaries/pull/50. (for Mac, we need only four binaries)

**Comment by dworzanski** [comment]
> io.js v1.6 will be supported by node-sass v3.0.0. Currently you can try the released alpha and beta.

@am11 Thanks.

I'll let you close this issue -- I'm not sure if you want to deal with the Mac binaries issue posted by @dominicbarnes further here.
