### ISSUE TITLE
Can't run tests

### ISSUE THREAD

**Issue by paulmillr** [sass/node-sass#846]
On current `master`:

```
> node-sass@3.0.0-beta.5 pretest /Users/user/Developer/forks/node-sass
> jshint bin lib scripts test


> node-sass@3.0.0-beta.5 test /Users/user/Developer/forks/node-sass
> mocha test

fs.js:761
  return binding.readdir(pathModule._makeLong(path));
                 ^
Error: ENOENT, no such file or directory '/Users/user/Developer/forks/node-sass/test/fixtures/spec/spec'
    at Error (native)
    at Object.fs.readdirSync (fs.js:761:18)
    at Object.module.exports.getSuites (/Users/user/Developer/forks/node-sass/test/util/index.js:24:19)
    at Suite.<anonymous> (/Users/user/Developer/forks/node-sass/test/spec.js:11:21)
    at context.describe.context.context (/Users/user/Developer/forks/node-sass/node_modules/mocha/lib/interfaces/bdd.js:49:10)
    at Object.<anonymous> (/Users/user/Developer/forks/node-sass/test/spec.js:9:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /Users/user/Developer/forks/node-sass/node_modules/mocha/lib/mocha.js:192:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/user/Developer/forks/node-sass/node_modules/mocha/lib/mocha.js:189:14)
    at Mocha.run (/Users/user/Developer/forks/node-sass/node_modules/mocha/lib/mocha.js:422:31)
    at Object.<anonymous> (/Users/user/Developer/forks/node-sass/node_modules/mocha/bin/_mocha:398:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
npm ERR! Test failed.  See above for more details.
```

**Comment by saper** [comment]
Can you try

````
git submodule update --init
````
 
before running `npm test` ?

**Comment by am11** [comment]
@paulmillr, normally I run it like:

```bash
git clone https://github.com/sass/node-sass --recursive
cd node-sass
git submodule update --init --recursive
npm install
node scripts/build -f  # rebuild, optional
npm test
```

**Comment by xzyfer** [comment]
@paulmillr please confirm this is still an issue?
