### ISSUE TITLE
Undefined is not a function(

### ISSUE THREAD

**Issue by yormi** [sass/node-sass#881]
Hey folks !

Maybe I'm missing something but it looks like I have some problem... If you need more info, just ask :)

>Fatal error: undefined is not a function
TypeError: undefined is not a function
    at getOptions (/home/guillaume/Documents/LiU/TDDD27/slackportal/frontend/node_modules/grunt-sass/node_modules/node-sass/lib/index.js:137:73)
    at Object.module.exports.render (/home/guillaume/Documents/LiU/TDDD27/slackportal/frontend/node_modules/grunt-sass/node_modules/node-sass/lib/index.js:198:13)
    at Object.<anonymous> (/home/guillaume/Documents/LiU/TDDD27/slackportal/frontend/node_modules/grunt-sass/tasks/sass.js:23:9)
    at Immediate.immediate._onImmediate (timers.js:409:16)
    at processImmediate [as _immediateCallback] (timers.js:358:17)

I was using the library through grunt-sass but it seems that the problem comes from this awesome library. Hope this can help to make it better :dancers: 

Thanks for your work guys !

**Comment by xzyfer** [comment]
Can you please supply the output of `./node_modules/.bin/node-sass --version`, as well as your OSes and node version?

**Comment by yormi** [comment]
As you asked, hope you have everything you need !

>./node_modules/grunt-sass/node_modules/.bin/node-sass --version
2.1.1

>node -v
v0.12.2

>uname -a
Linux gibjiz 3.19.3-3-ARCH #1 SMP PREEMPT Wed Apr 8 14:10:00 CEST 2015 x86_64 GNU/Linux

Thank you for your time :)

**Comment by xzyfer** [comment]
It would appear you're setting an invalid value for `includePath`. It should be an array.

**Comment by yormi** [comment]
Oh ! That was it. I was sure I tried it with an array... completely my fault then...

Thank you for your help and keep up the good work mate :)
