### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by mwils-bp** [sass/node-sass#882]
For some reason I cannot install node-sass with:

```
npm install node-sass
```

Here is the output:

```
> node-sass@2.1.1 install /root/shelterstyle/node_modules/node-sass
> node scripts/install.js

module.js:333
    throw err;
          ^
Error: Cannot find module '/root/shelterstyle/node_modules/node-sass/scripts/install.js'
    at Function.Module._resolveFilename (module.js:331:15)
    at Function.Module._load (module.js:273:25)
    at Function.Module.runMain (module.js:490:10)
    at startup (node.js:124:16)
    at node.js:807:3
npm ERR! node-sass@2.1.1 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@2.1.1 install script.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.2.0-23-virtual
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "node-sass"
npm ERR! cwd /root/shelterstyle
npm ERR! node -v v0.11.13-pre
npm ERR! npm -v 1.4.6
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /root/shelterstyle/npm-debug.log
npm ERR! not ok code 0
```

**Comment by xzyfer** [comment]
You're using the unstable node v0.11 branch. We only support stable released. You'll need to switch to 0.10 or 0.12 to use node-sass.

**Comment by mwils-bp** [comment]
Thanks for the very quick reply @xzyfer! I'm going to switch over to v0.12.2 now :+1:

**Comment by mwils-bp** [comment]
Great that worked like a charm! Would it be worth adding this to the README? 

As I was pretty lost until your advice :)
