### ISSUE TITLE
could not install 3.0 on windows

### ISSUE THREAD

**Issue by chrisjfunk** [sass/node-sass#934]
got this error on windows with node0.12.2 npm 2.7.4 git windows mysysgit 1.9.5.1

npm ERR! Cloning into bare repository 'C:\Users\cfunk\AppData\Roaming\npm-cache\
_git-remotes\git-github-com-am11-pangyp-git-a953a761'...
npm ERR! Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.

full trace
C:\Users\cfunk>npm install node-sass@3.0
npm ERR! git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config -
-get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:751:12)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:110:17)
npm WARN addRemoteGit     at maybeClose (child_process.js:1015:16)
npm WARN addRemoteGit     at Socket.<anonymous> (child_process.js:1183:11)
npm WARN addRemoteGit     at Socket.emit (events.js:107:17)
npm WARN addRemoteGit     at Pipe.close (net.js:485:12)
npm WARN addRemoteGit  resetting remote C:\Users\cfunk\AppData\Roaming\npm-cache
\_git-remotes\git-github-com-am11-pangyp-git-7eb24aaa because of error: { [Error
: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit ]
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.ori
gin.url' }
npm ERR! git -c core.longpaths=true clone --template=C:\Users\cfunk\AppData\Roam
ing\npm-cache\_git-remotes\_templates --mirror git://github.com/am11/pangyp.git
C:\Users\cfunk\AppData\Roaming\npm-cache\_git-remotes\git-github-com-am11-pangyp
-git-7eb24aaa
npm ERR! git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config -
-get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:751:12)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:110:17)
npm WARN addRemoteGit     at maybeClose (child_process.js:1015:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (child_process.
js:1087:5)
npm WARN addRemoteGit  resetting remote C:\Users\cfunk\AppData\Roaming\npm-cache
\_git-remotes\git-github-com-am11-pangyp-git-a953a761 because of error: { [Error
: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit ]
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.ori
gin.url' }
npm ERR! git -c core.longpaths=true clone --template=C:\Users\cfunk\AppData\Roam
ing\npm-cache\_git-remotes\_templates --mirror git@github.com:am11/pangyp.git C:
\Users\cfunk\AppData\Roaming\npm-cache\_git-remotes\git-github-com-am11-pangyp-g
it-a953a761
npm ERR! git clone --template=C:\Users\cfunk\AppData\Roaming\npm-cache\_git-remo
tes\_templates --mirror git@github.com:am11/pangyp.git C:\Users\cfunk\AppData\Ro
aming\npm-cache\_git-remotes\git-github-com-am11-pangyp-git-a953a761: Cloning in
to bare repository 'C:\Users\cfunk\AppData\Roaming\npm-cache\_git-remotes\git-gi
thub-com-am11-pangyp-git-a953a761'...
npm ERR! git clone --template=C:\Users\cfunk\AppData\Roaming\npm-cache\_git-remo
tes\_templates --mirror git@github.com:am11/pangyp.git C:\Users\cfunk\AppData\Ro
aming\npm-cache\_git-remotes\git-github-com-am11-pangyp-git-a953a761: Permission
 denied (publickey).
npm ERR! git clone --template=C:\Users\cfunk\AppData\Roaming\npm-cache\_git-remo
tes\_templates --mirror git@github.com:am11/pangyp.git C:\Users\cfunk\AppData\Ro
aming\npm-cache\_git-remotes\git-github-com-am11-pangyp-git-a953a761: fatal: Cou
ld not read from remote repository.
npm ERR! git clone --template=C:\Users\cfunk\AppData\Roaming\npm-cache\_git-remo
tes\_templates --mirror git@github.com:am11/pangyp.git C:\Users\cfunk\AppData\Ro
aming\npm-cache\_git-remotes\git-github-com-am11-pangyp-git-a953a761:
npm ERR! git clone --template=C:\Users\cfunk\AppData\Roaming\npm-cache\_git-remo
tes\_templates --mirror git@github.com:am11/pangyp.git C:\Users\cfunk\AppData\Ro
aming\npm-cache\_git-remotes\git-github-com-am11-pangyp-git-a953a761: Please mak
e sure you have the correct access rights
npm ERR! git clone --template=C:\Users\cfunk\AppData\Roaming\npm-cache\_git-remo
tes\_templates --mirror git@github.com:am11/pangyp.git C:\Users\cfunk\AppData\Ro
aming\npm-cache\_git-remotes\git-github-com-am11-pangyp-git-a953a761: and the re
pository exists.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-sass@3.0"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\cf
unk\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:am
11/pangyp.git C:\Users\cfunk\AppData\Roaming\npm-cache\_git-remotes\git-github-c
om-am11-pangyp-git-a953a761
npm ERR! Cloning into bare repository 'C:\Users\cfunk\AppData\Roaming\npm-cache\
_git-remotes\git-github-com-am11-pangyp-git-a953a761'...
npm ERR! Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\cfunk\npm-debug.log

**Comment by chrisjfunk** [comment]
npm install pangyp works but npm install pangyp@a11.... version you are set to does not.
