### ISSUE TITLE
options.sourceMap Boolean

### ISSUE THREAD

**Issue by Munter** [sass/node-sass#953]
The README says having `sourceMaps` as a Boolean is possible:

> When sourceMap === true, the value of outFile is used as the target output location for the source map

```js
sass.render({
  data: 'body { h1 { backgroud: red; } }',
  sourceMap: true,
  outFile: 'foo'
}, function (err, result) { console.log(err, result); });
```

The above code results in this error:

```
path.js:313
        throw new TypeError('Arguments to path.resolve must be strings');
              ^
TypeError: Arguments to path.resolve must be strings
    at Object.exports.resolve (path.js:313:15)
    at prepareOptions (/home/munter/git/node-sass-evergreen/version-0/node_modules/node-sass/sass.js:68:22)
    at Object.exports.render (/home/munter/git/node-sass-evergreen/version-0/node_modules/node-sass/sass.js:137:13)
    at Object.module.exports.extend.render (/home/munter/git/node-sass-evergreen/version-0/index.js:64:10)
    at Object.<anonymous> (/home/munter/git/node-sass-evergreen/foo.js:23:7)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

node-sass info:
```
node-sass	3.0.0	(Wrapper)	[JavaScript]
libsass  	3.2.2	(Sass Compiler)	[C/C++]
```

**Comment by saper** [comment]
Using current master it works4me:

https://gist.github.com/729b99a3c85ac0f2fec6

**Comment by Munter** [comment]
Hmm. I'll retry when I get back to that setup.

**Comment by saper** [comment]
Your line numbers indicate you are using some different code...

**Comment by Munter** [comment]
Ah, damn. I'm working on a backwards compatible node-sass wrapper for build tools so they can be version agnostic. Looks like this stack trace hit node-sass 0.9.6, not 3.0.0. Sorry.

**Comment by saper** [comment]
Great it got sorted out quickly!
