### ISSUE TITLE
Can't find libsass in Docker image

### ISSUE THREAD

**Issue by kevinSuttle** [sass/node-sass#983]
**Dockerfile**
```go
FROM node:0.12.2 // also tried CentOS 6.6

COPY . /src
WORKDIR /src
CMD cd ./src;
RUN npm install --loglevel error;
EXPOSE 3000

CMD ["npm", "run", "dev"]
```

**package.json**
```javascript
  "scripts": {
    "start": "node bin/www",
    "predev": "gulp compile-sass",
    "dev": ". ./config/set-dev-env.sh; nodemon ./bin/www"
  },
```

**docker**
```bash
❯ docker run REDACTED                                                                                  01:24:16 PM

> REDACTED@0.0.0 predev /src
> gulp compile-sass

/src/node_modules/node-sass/lib/extensions.js:148
    throw new Error(['`libsass` bindings not found in ', binaryPath, '. Try re
          ^
Error: `libsass` bindings not found in /src/node_modules/node-sass/vendor/linux-x64-14/binding.node. Try reinstalling `node-sass`?
    at Object.sass.getBinaryPath (/src/node_modules/node-sass/lib/extensions.js:148:11)
    at Object.<anonymous> (/src/node_modules/node-sass/lib/index.js:16:36)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/src/node_modules/gulp-sass/index.js:157:21)
    at Module._compile (module.js:460:26)

npm ERR! Linux 4.0.3-boot2docker
npm ERR! argv "node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v0.12.2
npm ERR! npm  v2.9.1
npm ERR! code ELIFECYCLE
npm ERR! REDACTED@0.0.0 predev: `gulp compile-sass`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the REDACTED@0.0.0 predev script 'gulp compile-sass'.
npm ERR! This is most likely a problem with the REDACTED package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp compile-sass
npm ERR! You can get their info via:
npm ERR!     npm owner ls REDACTED
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /src/npm-debug.log
```

**Comment by xzyfer** [comment]
When you're switching environments i.e. docker mount, you need to reinstall node-sass to fetch the latest binary.

This usually happens when you run `npm install`, but it because node-sass is not a direct dependency (because you're using gulp-sass) `npm install` isn't running our postinstall script.

The easy fix here is 

```
RUN ./node_modules/gulp-sass/node_modules/node-sass/scripts/build.js;
```

**Comment by Snugug** [comment]
@xzyfer Is that something we need to look at for `gulp-sass`?

**Comment by xzyfer** [comment]
Yeah, I was going to open a PR. You need a post install to run our post
install haha

**Comment by Snugug** [comment]
:tongue: 
If you could file an issue we can address it/you can open a PR

**Comment by kevinSuttle** [comment]
This won't work (at least not the way I have it set up), because there is no `node_modules` folder under `gulp-sass`. 

```go
Step 5 : RUN npm install --loglevel error;
 ---> Using cache
 ---> 8a75e60fbe28
Step 6 : RUN ./node_modules/gulp-sass/node_modules/node-sass/scripts/build.js;
 ---> Running in 10980feb22b9
/bin/sh: 1: ./node_modules/gulp-sass/node_modules/node-sass/scripts/build.js: not found
INFO[0010] The command [/bin/sh -c ./node_modules/gulp-sass/node_modules/node-sass/scripts/build.js;] returned a non-zero code: 127
```

`build.js` appears to not ship with executable permissions. When I run that, this is what I get. 
```bash
The file './build.js' is not executable by this user
```

**Comment by kevinSuttle** [comment]
Ran `npm cache clean` and verified the permissions issue.

```go
Step 5 : RUN npm cache clean; npm install --loglevel error;
 ---> Running in c7e91c53ec36

> pre-commit@1.0.7 install /src/node_modules/pre-commit
> node install.js

 ---> b9a3f1278e28
Removing intermediate container c7e91c53ec36
Step 6 : RUN ./node_modules/gulp-sass/node_modules/node-sass/scripts/build.js;
 ---> Running in 626a22fc5c30
/bin/sh: 1: ./node_modules/gulp-sass/node_modules/node-sass/scripts/build.js: Permission denied
INFO[0047] The command [/bin/sh -c ./node_modules/gulp-sass/node_modules/node-sass/scripts/build.js;] returned a non-zero code: 126
```

**Comment by kevinSuttle** [comment]
Even changed it from `RUN` to `CMD`, and the image built successfully. However, running it, no dice, same issue.

**Comment by xzyfer** [comment]
Then you can use node to execute it.

```
node ./node_modules/gulp-sass/node_modules/node-sass/scripts/build.js
```

**Comment by kevinSuttle** [comment]
As before, it builds fine, but doesn't run because `node-sass` can't find `libsass` inside the container.

**Comment by kevinSuttle** [comment]
Would this help? https://registry.hub.docker.com/u/xzyfer/docker-libsass/

**Comment by kevinSuttle** [comment]
Seems related https://github.com/sass/node-sass/issues/800

**Comment by xzyfer** [comment]
I'm sorry but I don't understand your issue. Node sass installs libsass when it's installed.

It simply looks like your paths are incorrect. Find where ever your node-sass folder is and run the `scripts/build.js`. Looking at your OP it's located in `/src/node_modules/node-sass`.

**Comment by xzyfer** [comment]
The linked issue is unrelated.

**Comment by kevinSuttle** [comment]
```
Step 7 : RUN node ./node_modules/gulp-sass/node_modules/node-sass/scripts/build.js
 ---> Running in b25bfbbafd60
Detected a git install
Cloning libSass into src/libsass
Cloning into './src/libsass'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

INFO[0210] The command [/bin/sh -c node ./node_modules/gulp-sass/node_modules/node-sass/scripts/build.js] returned a non-zero code: 1
```

**Comment by xzyfer** [comment]
My mistake

```
RUN node ./node_modules/gulp-sass/node_modules/node-sass/scripts/install.js
```

**Comment by kevinSuttle** [comment]
So, the way I got this to work was by taking the commands out of the Dockerfile and into an npm script.

```
"scripts": {
		"postinstall": "node ./node_modules/gulp-sass/node_modules/node-sass/scripts/install.js",
```

**Comment by kevinSuttle** [comment]
Actually, this didn't work either, as node-sass wasn't listed in the node_modules folder in gulp_sass. I just pointed my postinstall script to node-sass directly, which helped shorten it. Works now.

`node ./node_modules/node-sass/scripts/install.js`

**Comment by erichonkanen** [comment]
hello, I am having a possibly similar issue.. were you able to resolve it? 

```# dockerfile

FROM node:0.12.7
RUN npm install -g ember-cli@0.2.7 \
    bower \
    phantomjs
RUN mkdir -p /code
WORKDIR /code
RUN npm update \
    npm rebuild node-sass@3.2.0 \
    bower install --allow-root
COPY . /code
EXPOSE 4200 35729


# command line

docker-compose -f compose.yml up
Creating clientweb_ember_1...
Attaching to clientweb_ember_1
ember_1 | version: 1.13.1
ember_1 | Could not find watchman, falling back to NodeWatcher for file system events.
ember_1 | Visit http://www.ember-cli.com/#watchman for more info.
ember_1 | Livereload server on http://localhost:35729
ember_1 | Serving on http://localhost:4200/
ember_1 | `libsass` bindings not found in /code/node_modules/broccoli-sass/node_modules/node-sass/vendor/linux-x64-14/binding.node. Try reinstalling `node-sass`?
ember_1 | Error: `libsass` bindings not found in /code/node_modules/broccoli-sass/node_modules/node-sass/vendor/linux-x64-14/binding.node. Try reinstalling `node-sass`?
ember_1 |   at Object.sass.getBinaryPath (/code/node_modules/broccoli-sass/node_modules/node-sass/lib/extensions.js:148:11)
ember_1 |   at Object.<anonymous> (/code/node_modules/broccoli-sass/node_modules/node-sass/lib/index.js:16:36)
ember_1 |   at Module._compile (module.js:460:26)
ember_1 |   at Object.Module._extensions..js (module.js:478:10)
ember_1 |   at Module.load (module.js:355:32)
ember_1 |   at Function.Module._load (module.js:310:12)
ember_1 |   at Module.require (module.js:365:17)
ember_1 |   at require (module.js:384:17)
ember_1 |   at Object.<anonymous> (/code/node_modules/broccoli-sass/index.js:5:12)
ember_1 |   at Module._compile (module.js:460:26)
ember_1 |   at Object.Module._extensions..js (module.js:478:10)
ember_1 |   at Module.load (module.js:355:32)
ember_1 |   at Function.Module._load (module.js:310:12)
ember_1 |   at Module.require (module.js:365:17)
ember_1 |   at require (module.js:384:17)
ember_1 |   at requireLocal (/code/node_modules/ember-cli/node_modules/process-relative-require/index.js:7:10)
ember_1 |   at /code/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/lib/style-plugin.js:45:18
ember_1 |   at Array.map (native)
ember_1 |   at /code/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/lib/style-plugin.js:28:40
ember_1 |   at lib$rsvp$$internal$$tryCatch (/code/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:489:16)
ember_1 |   at lib$rsvp$$internal$$invokeCallback (/code/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:501:17)
ember_1 |   at lib$rsvp$$internal$$publish (/code/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:472:11)
ember_1 |   at lib$rsvp$asap$$flush (/code/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1290:9)
ember_1 |   at process._tickCallback (node.js:355:11)
ember_1 |
```

**Comment by saper** [comment]
Please see comments above, you need to run `nam install node-sass` or just the installation script `node PATH/to/node-sass/scripts/install.js`

**Comment by erichonkanen** [comment]
@saper I have tried both of those...

Dockerfile
```
FROM node:0.12.7
RUN npm install -g ember-cli@0.2.7 \
    bower \
    phantomjs
RUN mkdir -p /code
WORKDIR /code
RUN npm install \
    npm rebuild node-sass@3.2.0 \
    bower install --allow-root
COPY . /code
EXPOSE 4200 35729
```

package.json
```{
  "name": "client-web",
  "version": "0.0.0",
  "description": "Small description for client-web goes here",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "start": "ember server",
    "build": "ember build",
    "test": "ember test",
    "postinstall": "node ./node_modules/broccoli-sass/node_modules/node-sass/scripts/install.js"
  },
  "repository": "",
  "engines": {
    "node": ">= 0.10.0"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "broccoli-asset-rev": "^2.0.2",
    "broccoli-sass": "^0.6.6",
    "ember-cli": "1.13.1",
    "ember-cli-app-version": "0.3.3",
    "ember-cli-babel": "^5.0.0",
    "ember-cli-coffees6": "0.2.1",
    "ember-cli-content-security-policy": "0.4.0",
    "ember-cli-dependency-checker": "^1.0.0",
    "ember-cli-htmlbars": "0.7.9",
    "ember-cli-ic-ajax": "0.1.1",
    "ember-cli-inject-live-reload": "^1.3.0",
    "ember-cli-qunit": "0.3.13",
    "ember-cli-uglify": "^1.0.1",
    "ember-data": "1.13.5",
    "ember-disable-proxy-controllers": "^1.0.0",
    "ember-export-application-global": "^1.0.2"
  }
}
```

still getting the error.. anything look incorrect in those two files? im using docker 1.3 + docker-compose

**Comment by erichonkanen** [comment]
strange.. I got it working by running `npm rebuild node-sass` in my bootstrap.sh script instead of in the Dockerfile... any ideas why?

Dockerfile
```
FROM node:0.12.7
RUN npm install -g ember-cli@0.2.7 \
    bower \
    phantomjs
RUN mkdir -p /code
WORKDIR /code
COPY . /code
RUN npm install \
    bower install --allow-root
EXPOSE 4200 35729
```

compose.yml
```
ember:
  build: .
  command: ./bootstrap.sh
  volumes:
    - .:/code
```

bootstrap.sh
```
#!/bin/sh
su -c "npm rebuild node-sass@3.2.0"
su -c "ember serve"
```

**Comment by hd-deman** [comment]
the solution is to install with `--unsafe-perm`.
```
npm --unsafe-perm install
```
see https://github.com/nodejs/docker-node/issues/88

**Comment by verlorendev** [comment]
>the solution is to install with --unsafe-perm.
>npm --unsafe-perm install
>see nodejs/docker-node#88 

it doesn't work for me. I've tried all methods counted before.
But still the same issue.
Does anyone has another suggestions to fix it?
