### ISSUE TITLE
Failing to download and install on MAC OS

### ISSUE THREAD

**Issue by banerjed** [sass/node-sass#990]
Dman-MBA-4:temp1 banerjed$ pwd
/Users/banerjed/work/temp1
Dman-MBA-4:temp1 banerjed$ npm -v              
2.10.1
Dman-MBA-4:temp1 banerjed$ node -v
v0.12.4
Dman-MBA-4:temp1 banerjed$ node -p process.versions
{ http_parser: '2.3',
  node: '0.12.4',
  v8: '3.28.71.19',
  uv: '1.5.0',
  zlib: '1.2.8',
  modules: '14',
  openssl: '1.0.1m' }
Dman-MBA-4:temp1 banerjed$ node -p process.platform
darwin
Dman-MBA-4:temp1 banerjed$ node -p process.arch
x64

Dman-MBA-4:temp1 banerjed$ npm install node-sass
\
> node-sass@3.1.2 install /Users/banerjed/work/temp1/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /Users/banerjed/work/temp1/node_modules/node-sass/vendor/darwin-x64-14/binding.node

> node-sass@3.1.2 postinstall /Users/banerjed/work/temp1/node_modules/node-sass
> node scripts/build.js

` /Users/banerjed/work/temp1/node_modules/node-sass/vendor/darwin-x64-14/binding.node ` exists. 
 testing binary.
Problem with the binary.
Manual build incoming.
Building: /usr/local/bin/node node_modules/pangyp/bin/node-gyp rebuild --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp: /Users/banerjed/.node-gyp/0.12.4/common.gypi not found (cwd: /Users/banerjed/work/temp1/node_modules/node-sass) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/banerjed/work/temp1/node_modules/node-sass/node_modules/pangyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 10.8.0
gyp ERR! command "/usr/local/bin/node" "/Users/banerjed/work/temp1/node_modules/node-sass/node_modules/pangyp/bin/node-gyp" "rebuild" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/banerjed/work/temp1/node_modules/node-sass
gyp ERR! node -v v0.12.4
gyp ERR! pangyp -v v2.2.1
gyp ERR! not ok 
Build failed
npm ERR! Darwin 10.8.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "node-sass"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.1.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.1.2 postinstall script 'node scripts/build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/banerjed/work/temp1/npm-debug.log

I uploaded the npm-debug.log at https://drive.google.com/file/d/0B6h0RvtECaNLMVhnSG1NTzZ1SDQ/view?usp=sharing

**Comment by banerjed** [comment]
This seems to be a duplicate of #693. Looks like node-sass-binaries are not supported for OS X older than 10.9
